### ISSUE TITLE
Consider using keyboard shortcuts

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#2053]
I use the [Trello](https://trello.com/) website a lot. One of the great things about Trello is that it has a lot of keyboard shortcuts for common actions. You can view all its keyboard shortcuts by pressing shift+?. Once you learn the keyboard shortcuts, the website becomes some much easier to use. For a great write-up on why websites should use keyboard shortcuts, see [this post](http://www.hanselman.com/blog/TheWebIsTheNewTerminalAreYouUsingTheWebsKeyboardShortcutsAndHotkeys.aspx).

I think that exercism could also benefit from some keyboard shortcuts, particularly for the submission page. Some possible shortcuts would be:
- Shortcut for starting a nitpick (essentially putting the focus in the comment box)
- Shortcut for toggling "this looks great"
- Shortcut for toggling expanded code view
- Shortcut for toggling muting
- Shortcut for next submission
- Shortcut for the three code tabs (Code, Readme, Test suite)
- Shortcut for copying code to your clipboard

There could be more, but these seem to be the most useful ones. 

As for how this could be implemented, there are various JavaScript libraries for this. Some of the shortcuts could also be implemented using [standard access keys](http://www.w3schools.com/tags/att_global_accesskey.asp), although they always require the users to at least press the alt button.

**Comment by kytrinyx** [comment]
Wow, I appear to have dropped the ball on this. It's been... 2 years. I still think this is a fantastic idea, so I'm not going to close the issue.

I don't have a list of existing shortcuts. I think if we look at the shortcuts that gmail uses for inspiration we might have a good starting point.

**Comment by kytrinyx** [comment]
I've added this to the list of things to consider when we do the redesign. I really love keyboard-only workflows, so I hope that we will be able to make this happen.

Meanwhile I'm closing the issue, since it's being tracked for the reboot.

**Comment by iHiD** [comment]
In a beautiful circular manner, I'm reopening this and assigning to to @ErikSchierboom to think about as part of v3 :)

**Comment by iHiD** [comment]
Also see https://github.com/exercism/website/pull/923 as the first sort of foray into this world.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
