### ISSUE TITLE
Support for PowerPC

### ISSUE THREAD

**Issue by villadalmine** [exercism/exercism#3745]
Do you know if someone installed it in powerpc, g4 or g5 Mac powerpc. To get working go in powerpc you need to have go interpreted using cross compiling.

**Comment by catb0t** [comment]
It seems that you can build Golang on that platform.

http://grokbase.com/t/gg/golang-nuts/1548n7py08/go-nuts-go-for-powerpc-if-not-how-to-build-gos-packages-with-cross-compiler-gccgo

http://grokbase.com/t/gg/golang-dev/14bhqjnsyd/goarch-values-for-powerpc

https://github.com/golang/go/issues/18031

**Comment by kytrinyx** [comment]
I could try cross compiling for PowerPC if someone wouldn't mind digging up the GOOS GOARCH values I'd need.

**Comment by villadalmine** [comment]
I tried in Linux and then in my PowerPC64 g5 with Ubuntu but failed with 1.9 and 1.5. I want also for PowerPC g4 but no support from go or I missed something. Also I want for openbsd but mainstream only support for amd64 
		
		

		---Rondan RinoCertificado en LPIC-3LPI ID:LPI000209832Verification Code:gbblvwyfxuRed Hat Certified Engineer -- RHCE -- RHCVA 

Blog:http://www.itrestauracion.com.arCv: http://cv.rinorondan.com.arhttp://counter.li.org Linux User -> #517918Viva La Santa Federacion!!Mueran Los Salvages Unitarios!! ^^^Transcripcion de la epoca ^^^
	




On Sat, Mar 24, 2018 at 6:08 PM -0300, "Katrina Owen" <notifications@github.com> wrote:












I could try cross compiling for PowerPC if someone wouldn't mind digging up the GOOS GOARCH values I'd need.

**Comment by kytrinyx** [comment]
> I tried in Linux 

None of our current linux builds worked for you?

**Comment by villadalmine** [comment]
I’m talking about go, create cross compiling package for ppwerpc64 , the package to then compile go in Ubuntu 16.04 with powerpc64 g5 , I tried one time and failed some test in compiling , i did not try to debug it, but I want compile go in ppc64 and ppc and then tried exercism cli. Did someone have go working in ppc or ppc64 in Linux and openbsd ?
		
		

		---Rondan RinoCertificado en LPIC-3LPI ID:LPI000209832Verification Code:gbblvwyfxuRed Hat Certified Engineer -- RHCE -- RHCVA 

Blog:http://www.itrestauracion.com.arCv: http://cv.rinorondan.com.arhttp://counter.li.org Linux User -> #517918Viva La Santa Federacion!!Mueran Los Salvages Unitarios!! ^^^Transcripcion de la epoca ^^^
	




On Sat, Mar 24, 2018 at 6:54 PM -0300, "Katrina Owen" <notifications@github.com> wrote:













I tried in Linux



None of our current linux builds worked for you?

**Comment by kytrinyx** [comment]
> Did someone have go working in ppc or ppc64 in Linux and openbsd

I'm pretty sure that people have cross-compiled Go for OpenBSD. E.g. the Hugo static site generator is written in Go, and is cross-compiled for OpenBSD, as can be seen on their release page: https://github.com/gohugoio/hugo/releases

I don't know anyone who cross-compiles for powerpc.

**Comment by villadalmine** [comment]
Yes, I need from PowerPC 32 and 64 bit, because openbsd and Linux do not support those native go , I need to expense more time to make cross compiling from my intel arch to generate at least ppc64  source package and try compile in ppc64 , but go do not support ppc32, when I have working go in my ppc64 I can try install exercism cli from source, so no one use ppc64 or ppc32 and have go installed and exercism cli ?Thanks for the help!!
		
		

		---Rondan RinoCertificado en LPIC-3LPI ID:LPI000209832Verification Code:gbblvwyfxuRed Hat Certified Engineer -- RHCE -- RHCVA 

Blog:http://www.itrestauracion.com.arCv: http://cv.rinorondan.com.arhttp://counter.li.org Linux User -> #517918Viva La Santa Federacion!!Mueran Los Salvages Unitarios!! ^^^Transcripcion de la epoca ^^^
	




On Sat, Mar 24, 2018 at 7:26 PM -0300, "Katrina Owen" <notifications@github.com> wrote:













Did someone have go working in ppc or ppc64 in Linux and openbsd



I'm pretty sure that people have cross-compiled Go for OpenBSD. E.g. the Hugo static site generator is written in Go, and is cross-compiled for OpenBSD, as can be seen on their release page: https://github.com/gohugoio/hugo/releases


I don't know anyone who cross-compiles for powerpc.

**Comment by villadalmine** [comment]
I used this example and the go document page, https://dave.cheney.net/tag/ppc64

**Comment by villadalmine** [comment]
I have compiled go1.8 in linux ppc64, so just left read about how to configure the environment variables for go and next step is install cli exercism from source :) :) ( I try go install GitHub.com/exercism/cli/exercism and I have a lot of errors, I used go but installed from packaged so all environment variables were never configured by me ...)

**Comment by villadalmine** [comment]
dalmine@ubuntu:~/gotest/go/bin$ ./exercism  version
exercism version 3.0.0-alpha.1
dalmine@ubuntu:~/gotest/go/bin$ uname -r
4.4.0-116-powerpc64-smp
dalmine@ubuntu:~/gotest/go/bin$

Thanks!! now is working in ppc64 !! just left check in go project what is the status for ppc32.
Can I help you with this version for ppc64 ?

**Comment by kytrinyx** [comment]
> now is working in ppc64

Excellent!

> Can I help you with this version for ppc64 ?

That would be wonderful!

If you want to submit a pull request to the master branch of https://github.com/exercism/cli (the build file is https://github.com/exercism/cli/blob/nextercism/bin/build-all) that would be a great help!

**Comment by villadalmine** [comment]
I did the PR for build-all

**Comment by iHiD** [comment]
@villadalmine @kytrinyx Is there action that's needed here for the new CLI or can we close this?

**Comment by kytrinyx** [comment]
This is done.
