### ISSUE TITLE
unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by redhatmk** [exercism/exercism#3796]
Hello,

I'm trying to submit a solution but I'm getting this error:

`unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value`

if ran this command `exercism --verbose submit Isogram.swift `

This is the response I'm getting:

```
Request POST http://exercism.io/api/v1/user/assignments
Response StatusCode=405
Response Body
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>


2018/07/10 12:57:35 unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value
```

Any of you knows either what I'm doing wrong or if any need to updated any of the libraries on my computer?

I'll really appreciate your help.

**Comment by unenglishable** [comment]
I'm getting the same error when trying to list tracks.

I also can't list problems for a track, or pretty much anything else for that matter.  I think there may be an issue with the API

**Comment by unenglishable** [comment]
Maybe just wait until this is done 😄 

![image](https://user-images.githubusercontent.com/3689811/42539976-75fb0f1a-8438-11e8-83fa-c0967b6036fe.png)

**Comment by guygastineau** [comment]
I think the migration is only until 16:00 UTC tomorrow.

**Comment by salvescoding** [comment]
Yeah I believe they are still with the migration because now when I go on the site I get the following message 

`{
error: " ------------------------------------------- We launched a brand new version of Exercism. Upgrade your client with: exercism upgrade Or delete the old CLI and follow the instructions on the new site to get the new one. "
}`

**Comment by redhatmk** [comment]
@salvescoding , any of you knows instructions to install the new client and remove the previous client?

**Comment by guygastineau** [comment]
@salvescoding did you get that on the site or through the cli client?  Currently I am still just getting the migration page that @unenglishable shared above when I visit exercism.io.

**Comment by kytrinyx** [comment]
Hi sorry about the confusion -- the migration is going to take an extra day, but it is progressing very nicely.

The new client is not yet released.
Once the new site is live, you should be able to run `exercism upgrade` to replace the current CLI with the new one.

I forgot to think about a different message for the CLI *while* we were migrating. I only thought through what should happen if you tried to use the old CLI against the new site (which wouldn't work).

**Comment by redhatmk** [comment]
@kytrinyx Thank you for the update. Please let us know when we can start pushing our code and if we need to do any changes to the client.

Thanks,
Luis

**Comment by iHiD** [comment]
I'm going to close this but please reopen and let us know if you still have an issue.
