### ISSUE TITLE
Enable full-width code window.

### ISSUE THREAD

**Issue by peschkaj** [exercism/exercism#3800]
When reviewing solutions it was previously possible to expand the size of the code window. With the new version of the site, there's no way to make the code view wider. This, in turn, makes it difficult to review code.

**Comment by kytrinyx** [comment]
Thank you, yes, we need to make sure you can see the full code example in the browser window.

**Comment by iHiD** [comment]
@peschkaj - We'll be adding this in the next month or two. Thanks for your patience.

**Comment by jonhoo** [comment]
A good start to this would be to be able to hide the pane with the "review" and "skip" buttons (before you've chosen to review the solution). I don't yet know what the view looks like after you've started a review, but at least this'd be a start!

**Comment by mzuther** [comment]
A simple solution: move the box "What can you learn from this solution?" from being right of the code box to right of the comment box. Then, just remove the "pure-u-md-1-2" class from the code box and your done. :)

**Comment by iHiD** [comment]
This got done.
