### ISSUE TITLE
Filter for solutions you're mentoring takes some time and does not give indication of work/progress

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3801]
When I change the filter settings, then there is nothing happening at first, then after about 8 to 10 seconds the filtered items are changing.

I can live with this slolyness and I am prepared, but this is really bad if I swap from an empty filterset to another. I never know if I am still seeing the old "nothing" or the new "nothing".

Some progressbar or a sandclock or something like this would be nice.

**Comment by iHiD** [comment]
This should be lots faster now. I will try and do a progress bar soon though.
