### ISSUE TITLE
Remove duplicate header

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#3812]
See how "Hello World" is duplicated here:

<img width="565" alt="screen shot 2018-07-14 at 11 23 17" src="https://user-images.githubusercontent.com/5421823/42723580-6473852e-8758-11e8-970e-5fd37ace86ce.png">

**Comment by nickborromeo** [comment]
👋 I have been seeing the label `status/coming-soon` and was not sure what that meant. 😄 It is already in the works and will be fixed soon? Maybe it could be helpful to create a doc enumerating the labels and giving a short description for them?

**Comment by iHiD** [comment]
>  It is already in the works and will be fixed soon?

Yeah - it sort of means "I'm going to do this so you don't need to write loads of things to persuade me about it :)"

I want to emulate [this section](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#issue-and-pull-request-labels) on the Atom CONTRIBUTING.md when I get through the crazy period.

**Comment by AlwinaO** [comment]
I'd like to claim this issue.

**Comment by PatrickMcSweeny** [comment]
Is it okay to close this?

**Comment by iHiD** [comment]
@PatrickMcSweeny Yes. Thanks for doing this  :)
