### ISSUE TITLE
what happened to teams?

### ISSUE THREAD

**Issue by jrr** [exercism/exercism#3815]
The old routes like https://exercism.io/teams/foo redirect to https://teams.exercism.io/ , which is hidden behind an http password.

The only trace I can find is [this](https://github.com/exercism/website-copy/blob/82b6cc8310aa8af2f443730bf5e1c565d4cf88a1/pages/about_v1_to_v2.md#a-new-mentorship-model):
> We will be addressing some aspects of the old model of communal feedback and learning with the new teams interface.

I assume teams v2 is still in development? It would be nice to explain with copy where the feature went and when to expect its return.

**Comment by iHiD** [comment]
Hi @jrr.

We were expecting to launch it at the same time as the new site, but we didn't quite have time to finish it. It will be coming in the next few days. I agree that it would be nice to have a landing page to explain this - I'll try and get the team to do that in the next day or so.

**Comment by cowlike** [comment]
@iHiD Is this still a thing? Asking because we had a lot of team activity going at one point and it looks like this issue is stalled indefinitely.

**Comment by iHiD** [comment]
Not stalled indefinitely. Stalled until I get a day free to do it. Sadly
I've not had a day free in the last 6 weeks. Busy dayjob. It'll definitely
be during October as I'm going to take a few days holiday and get on top of
it.

**Comment by jrr** [comment]
Is there anything I can do to help with this? I miss the teams interface!

**Comment by PatrickMcSweeny** [comment]
Is this closable?

**Comment by rpottsoh** [comment]
Likely since Teams is online.

**Comment by jrr** [comment]
Nice!

Is the new system documented anywhere? How is it differerent from teams v1?

**Comment by iHiD** [comment]
> Is the new system documented anywhere

Probably not anywhere near enough :)

The workflow is: Create a team, invite teammates, choose an exercise, submit it, get feedback from your teammates. Repeat. Hopefully it'll be intuitive enough for that to be doable, but if there's something clear, please open an issue and I'll try and make things clearer. I'm treating Teams as very beta right now :)
