### ISSUE TITLE
Add CTA at end of walk-through

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#3818]
Add button (in usual style - green) that says "Continue with the exercise" that closes the modal.

<img width="1116" alt="screen shot 2018-07-14 at 12 51 03" src="https://user-images.githubusercontent.com/5421823/42724181-6365cfea-8765-11e8-87cb-f8ceaf42305f.png">

**Comment by iHiD** [comment]
@kntsoriano I think this is a duplicate of another issue I tagged you in (but can't find). Either way, would be good to improve this with the exercise-specific instructions

**Comment by iHiD** [comment]
@kntsoriano The other issue was https://github.com/exercism/interactive-cli-walkthrough/issues/36 - Could you have a think about what is best to do here please and update that issue. I'm closing this one as a duplicate.
