### ISSUE TITLE
Broken syntax highlighting for F# code

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#3831]
The syntax highlighting for some F# code is broken:

![image](https://user-images.githubusercontent.com/135246/42727234-3169c0a8-87a3-11e8-9763-ae77c6472634.png)

See [this solution](https://exercism.io/mentor/solutions/52c84eb7f36c4d5992550f73eb73742c).

It might have something to do with the apostrophe in `canAttack'`, which is not an allowed character in many languages but is in F# (and it is not uncommon).

**Comment by NobbZ** [comment]
I can reproduce this on [prisms testdrive](https://prismjs.com/test.html) with the follwoing code:

```fsharp
let foo' = failWith "foo"

let bar' = failWith "bar"
```

Therefore I filed an upstream bug: PrismJS/prism#1480

**Comment by ErikSchierboom** [comment]
Thanks @NobbZ!

**Comment by iHiD** [comment]
Thanks both. I'm marking this as `wontfix` as it's outside of our remit, but I'll leave it open for now in case others find it.
