### ISSUE TITLE
Some Profile Tags Missing

### ISSUE THREAD

**Issue by jpreese** [exercism/exercism#3835]
On the profiles page (https://exercism.io/profiles/jpreese), it does not look like all of the tags are there. A couple examples:

Mentors page itself:
![image](https://user-images.githubusercontent.com/6980197/42728489-68bf823c-8789-11e8-9368-064c4e73914b.png)

My profile:
![image](https://user-images.githubusercontent.com/6980197/42728492-728e6882-8789-11e8-8172-fdedce5066fd.png)

In this case, I'm missing the F# (and Go) mentor tag.

It also doesn't look like maintainers are given tags at all (e.g. "C# Maintainer). I'm not sure if that's intended or not.

**Comment by jpreese** [comment]
Ah ok yeah, that fixed the Mentor part. I'm not seeing the Maintainer part.

**Comment by NobbZ** [comment]
Maintainership is a oneway thing. You get listed on the page with a card, but you wont get a badge for your profile.

**Comment by jpreese** [comment]
It looks like on https://github.com/exercism/website/blob/master/app/views/profiles/show.html.haml it's supposed to be there.

**Comment by iHiD** [comment]
We can track it here. I'll work this out. Thanks.
