### ISSUE TITLE
Formalized process to become a mentor?

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3836]
Currently anyone can become a mentor who knows the correct link.

Is it planned to formalize this process a bit more, such that new mentors need to get invited by other mentors, maintainers or site owners? Or at least that a proper application becomes necessary?

**Comment by iHiD** [comment]
Technically, yes. The Google form process will be rolled into the new website and the whole thing will be made significantly less shit :)

In terms of quality control, we have loads of thoughts on this that warrant a proper discussion. But for now we're in "recruit enough not to fail" mode.

**Comment by sshine** [comment]
Since this question has been answered, I'm going to close this issue. A proper discussion is still warranted, but it would probably not get the warranted attention if we have it here.

**Comment by iHiD** [comment]
V3 is reshaping this too.
