### ISSUE TITLE
student: exercism command to redownload the solution

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3838]
As a student I probably want to re-iterate a certain exercise, but I have not access to my old exercism-workspace, as I am on another computer. Therefore I need to redownload the exercise.

To do this, I need to remember the tracks and the exercises slug, and I need to remember wich flags I need to use. Therefore a simple textbox like that one that is available before submitting an exercise the first time, containing a copy pastable command were a huge help.

**Comment by budmc29** [comment]
I agree, this is a pain point.

**Comment by renao** [comment]
Ping! Yes, would be great 👍

**Comment by iHiD** [comment]
We added this a while back, so I'm closing this :)
