### ISSUE TITLE
🆘 failing upload of solution with new version

### ISSUE THREAD

**Issue by rachelhornung** [exercism/exercism#3841]
Hi,
I'm not sure whether I'm missed something on the new website, but I updated my exercism client, reconfigured the setup and tried to upload the last exercise I had downloaded prior to the system switch. However, I only see this:

$exercism submit /home/rachel/exercism/python/secret-handshake/secret_handshake.py
Error: couldn't find it

It doesn't make a difference whether I provide the full path or just the file or whether I move out of the directory. Did I miss somethig for the setup?

Thanks for your help,
Rachel

**Comment by NobbZ** [comment]
You need to redownload the exercise to fetch the necessary metadata file.

It's in the migration guide:

https://exercism.io/cli-v1-to-v2

**Comment by rachelhornung** [comment]
Thanks for the feedback. I still can't upload my solution, though. I tried to download the exercise anew, but get an error that the Solution was not found. I tried removing the old exercise folder. I tried different spellings of the exercise, but that changes the error to Exercise not found. What am I doing wrong?

$ exercism download --exercise=SECRET-HANDSHAKE --track=PYTHON -v

========================= BEGIN DumpRequest =========================
GET /v1/solutions/latest?exercise_id=SECRET-HANDSHAKE&track_id=PYTHON HTTP/1.1
Host: api.exercism.io
Authorization: Bearer f2c775c1-3a5f-4843-a3dd-385c54ca826f
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.4 (linux/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 16 Jul 2018 03:38:33 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.10.3 (Ubuntu)
Set-Cookie: site_context=normal; domain=.exercism.io; path=/
Set-Cookie: _exercism_session=OsrsY3vpvVhxX%2Fam41w%2BNi97v05hnhCbS%2BmoB0GfogtX1boDnbEhRXJehtJDxr9ys9eGTQvyDdHX5yNQ6tqbDPh2eVomwFzxau9buMolkKxiOvJfJPsbGXQi8VBrn3WNAMMEW0COw1EszurOagcKvQoXGRrAEUt8tH77LZRnNffM3oidhmraxvjI7nHOiTODOYxCCb3f9dJVjYDLBjizhlazNEnSE7gu103rpC3PyyrfJLP4xFBZG2xaeVUpdhJIAZS3eFXgA9%2BrrPrZ--7pqQ2Gtsm3xYaIOZ--fTt3CMVUxQ6WLy%2BU%2FbYd7Q%3D%3D; domain=.exercism.io; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 9d6c6cd8-9a3b-4fcd-bd70-ac00f5dda7df
X-Runtime: 0.097086
X-Xss-Protection: 1; mode=block


========================= END DumpResponse =========================

Error: Solution not found

**Comment by NobbZ** [comment]
This means that you do not fulfill the requirements to download the exercise, please check if you can access that exercise from the website.

**Comment by iHiD** [comment]
Can this be closed?

**Comment by rachelhornung** [comment]
Yes
