### ISSUE TITLE
🆘 migration impressions (stuck!)

### ISSUE THREAD

**Issue by jrr** [exercism/exercism#3842]
I tried to resume my current track tonight and got stuck.

For context, my migrated status (F#) is 18/18 core exercises completed, and 27 _extra exercises_ completed.

I upgraded the CLI with `exercism upgrade` to v3.0.3.

Then, optimistically, I tried to `exercism fetch`:
```
Error: unknown command "fetch" for ""
Run ' --help' for usage.
```

So, that doesn't work anymore. Bummer. (existing issue https://github.com/exercism/exercism.io/issues/3798 ) It would have been nice if the command still worked, but at least it should probably tell me what to do instead.

At this point I opened the [migration guide](https://exercism.io/cli-v1-to-v2).

> The new website relies on a metadata file that the old website did not provide. If you don't have this file, you will not be able to submit the exercise.
>
> The easiest way to ensure that you have the file is to copy your old solution somewhere, call exercism download for the exercise again, and then copy your solution back in.

It seems like this is written for somebody in the middle of an exercise. I guess I'll go back to one of my completed exercises and try to `exercism download` it?

```
> cd saddle-points
> rm -rf *
> exercism download --exercise=saddle-points --track=fsharp

Error:

    Welcome to Exercism!

    To get started, you need to configure the the tool with your API token.
    Find your token at

        /my/settings

    Then run the configure command:

        exercism configure --token=YOUR_TOKEN
```

Okay, let's do that.

```
johnruble@jrrmbp ~/e/f/saddle-points (master) [255]> exercism configure --token=(token)

Error:
    The default Exercism workspace is

      /Users/johnruble/Exercism

    There is already something there.
    If it's a directory, that might be fine.
    If it's a file, you will need to move it first, or choose a
    different location for the workspace.

    You can choose the workspace location by rerunning this command
    with the --workspace flag.

      exercism configure --token=(token) --workspace=/Users/johnruble/Exercism
```

_that might be fine._

I ran the suggested command, and it seemed to work. Now once more trying to download an old exercise:

```
johnruble@jrrmbp ~/e/f/saddle-points (master)> exercism download --exercise=saddle-points --track=fsharp
Error: Solution not found
```

What did I do wrong?

**Comment by NobbZ** [comment]
I do assume that you are missing prerequisites for that exercise somehow. Can you access the exercises page or is it still locked?

What is the status of sum of multiples? Have you submitted that on the last 14 days before migration or is it older? Have you put it on mentoring manually? Are you in normal or independent mode?

**Comment by jrr** [comment]
Ah, I hadn't noticed: the saddle points exercise is locked. I had submitted that one shortly before the site went down, so maybe it didn't make it into the data migration.

Looking at previous exercises, I'm able to download anything that's not locked, whether it's core or extra, completed or in-progress. So the CLI works well for unlocked exercises. When trying to download a locked exercise, maybe instead of _Error: Solution not found_, it should say something like _Error: exercise locked_, with some kind of explanation of what it takes to unlock the exercise.

Speaking of which, that's where I'm stuck now: how do I unlock additional _extra exercises_?

**Comment by NobbZ** [comment]
By completing the prerequisite.

That must be mentored **and** completed though.

There is currently a known bug with the status of migrated data.

**Comment by jrr** [comment]
How do I see the prerequisite relationships?

Could you link to the other bug, so that I can follow it (and get notified when it's fixed, so I know when to try to use Exercism again).

**Comment by NobbZ** [comment]
Sadly th only way to learn about prerequisites is to read the tracks config file on GitHub :(

exercism/exercism.io#3817 should be the bug that tracks unlocking issues with migrated data. But as I'm on my mobile I only did a rushed search, I might have missed the correct issue.

**Comment by redhatmk** [comment]
@jrr I follow the [ migration guide](https://exercism.io/cli-v1-to-v2) and I was able to submit my last solution but I tried to fetch for a new problem:
```
exercism fetch swift
Error: unknown command "fetch" for ""
Run ' --help' for usage.
```
Do I need to do something to be able to fetch new problems?

**Comment by NobbZ** [comment]
There is no fetch anymore it's download now. And unless you already submitted a solution, you can find the exact command to download the exercise on its page.

**Comment by redhatmk** [comment]
@NobbZ In that case I need to know the next exercise to download?. Because previously with the fetch it was downloading the next exercise after your submission.

**Comment by NobbZ** [comment]
You need a mentor to accept your submission anyway before you can download the next core exercise, so you are supposed to choose from the extra exercises those that suite you or to simply wait for approval. This is the new workflow.

**Comment by redhatmk** [comment]
@NobbZ , How can do for a mentor to accept my submission?

**Comment by NobbZ** [comment]
Wait. We have quite a backlog. And we can't even see how big that backlog is.

Also as a mentor on elixir and Erlang I have not the slightest clue about what's going on on other tracks, but as I said already, I'm not even sure how far we covered the backlog on those tracks...

**Comment by NobbZ** [comment]
Ps: if it's a legacy submission you also need to opt in from the solution page. Hopefully you haven't tried to reiterate since then...

**Comment by redhatmk** [comment]
@NobbZ it would helpful when somebody submit there solution you can see the previous submitted solutions. Just to have a clue if are doing the things in right way. Like it was before.

**Comment by iHiD** [comment]
Can this be closed?

**Comment by jrr** [comment]
Yes, it's working now. Thanks. Closing.
