### ISSUE TITLE
🆘 Unable to submit or download following migration

### ISSUE THREAD

**Issue by nmegrant** [exercism/exercism#3844]
I have a couple of issues, which may or may not be related. 

My old exercism directory is still present with all of the exercises I had completed/was working on prior to migration. While the migration was taking place, I completed an exercise. Trying to submit/move on after this exercise is where I'm running into problems.

My original directory was called "exercism" (lower case 'e'). When I use the _exercism workspace_ command now, I get _**/Users/username/Exercism**_ (upper case 'e') as a result. No such directory is visible (using both the _ls_ and _ls -al_ commands). However if I fully type out _cd Exercism_, I can enter the directory (the table autocomplete will not work - I have to type out the full directory name). When I go into this directory it is identical to my old exercism directory (all the same completed exercises).

I've tried to submit my latest completed exercise from both directories with no success. Here are the result when I tried using old versus new exercism directories:

Under my old exercism directory, I get the following result:
_**MyComputer:meetup user$ exercism submit ~/exercism/python/meetup/meetup.py
Error: not in workspace**_

Under the new, invisible Exercism directory, I get
_**MyComputer:python user$ exercism submit ~/Exercism/python/meetup/meetup.py
Error: couldn't find it**_

I've seen similar issues here that recommended re-downloading the exercise. It seems to have work for other people. I have also tried this, but it doesn't seem to be working for me. When I try to re-download the meetup exercise I get the following:

Under my old exercism directory, I get the following result:
_**MyComputer:python user$ exercism download --exercise=Meetup --track=Python
Error: Solution not found**_

Under the new, invisible Exercism directory, I get the same result:
_**MyComputer:python user$ exercism download --exercise=Meetup --track=Python
Error: Solution not found**_

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.3
Latest:  3.0.3

Operating System
----------------
OS:           darwin
Architecture: amd64

Configuration
----------------
Home:      
Workspace: /Users/ngrant/Exercism
Config:    /Users/ngrant/.config/exercism/user.json
API key:   2084*****************************92c

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 236.287999ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 1.637526355s

Not sure if anyone can help. Ideally I'd like to have just a normal, visible directory that I can do my exercises in like before. Hope that will be a possibility! Thanks.

**Comment by NobbZ** [comment]
1. This is an issue common to Mac and Windows. Please rename your folder to match the casing of your config, or change your config to match the casing of your physical path name.
2. Please refer to https://exercism.io/cli-v1-to-v2. Especially make sure that you backup your solution, redownload via the new CLI to get the metadata, copy over your solution, submit.

You might get a "solution not found" when trying to download, even though the webpage suggests you should be able to do the download. There are several tickets open because of this, but currently there is no proper workaround :(

**Comment by nmegrant** [comment]
I had previously tried re-name the casing in my config file, but it didn't work and I was concerned about messing around with it too much. I'll try changing the name of the folder to see if that will do it. Thanks for the quick response!

**Comment by nmegrant** [comment]
Still no luck. I tried renaming the folder to match the casing of the config. These are the results:

MyComputer:python user$ exercism submit ~/Exercism/python/meetup/meetup.py
Error: couldn't find it
MyComputer:python user$ exercism download --exercise=Meetup --track=Python
Error: Solution not found
MyComputer:python user$ exercism submit ~/Exercism/python/meetup/meetup.py
Error: couldn't find it

Does this mean I'm waiting for the tickets to be addressed/workaround to be found?

**Comment by NobbZ** [comment]
“Couldn't find it” is much better than “not in workspace”, this actually means that exercism recognizes your directory structure now.

“Solution not found” though, means that the system thinks that you haven't progressed enough through the track and are missing preconditions. Please check if the exercise in question is accessible through the webpage.

**Comment by nmegrant** [comment]
@NobbZ That's good news! Looks like the exercise is no longer available to me post-migration (although it was available pre-migration). Guess I have to wait for some of my old work to be reviewed before I can get access again? Thanks again for the quick responses!

**Comment by guygastineau** [comment]
Additionally, if you are submitting a track you completed during migration then you need to redownload the problem.  The old directory won't include the `.solution.json` file that problems come with now. As such the cli won't think the problem is there.

I had to do this withbeer_song from the Ruby track.
Ex.
`exercism -t Ruby -e beer-song`

**Comment by iHiD** [comment]
Can this be closed?

**Comment by nmegrant** [comment]
Yes, it can. Thanks!
