### ISSUE TITLE
mentor: Solutions just mentored are “stale”

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3846]
In the elixir track I just mentored a solution of the `robot-simulator`, since its from the migrated dataset, it has already been 15 days old.

This solution was not available in my mentored solutions as “waiting for them” as I had expected, but instead it was “stale”.

I would expect that “stale” status is given based on the age of the last interaction with a solution rather than solely on the submission date.

There are other voices in exercism/v2-feedback#195 reporting missing solutions in “waiting for them”, perhaps those reportings are related.

**Comment by iHiD** [comment]
Have I fixed this?

**Comment by NobbZ** [comment]
I have no clue, I can not find that a `robot-simulator` in any of the filters now...

**Comment by iHiD** [comment]
Closed. If anyone sees this again, pls reopen and nag me :)

**Comment by cherylli** [comment]
Just happened to me in the python track where I just mentored a few solutions. Solutions are 21, 18, 18, and 13 days old respectively. Matrix and Twelve Days

**Comment by Stigjb** [comment]
I have had three solutions go into stale. One of them is approved, but still appears under stale. The other two are waiting for a new iteration.

**Comment by iHiD** [comment]
Could I have the solution id of the approved one pls?

**Comment by Stigjb** [comment]
a137be6a6d8e49a3bda3a74a3918742e

**Comment by iHiD** [comment]
Ok, so this issue here is that that solution is approved by not completed, so it is stale (ie it's waiting for action from the user) but it doesn't massively make sense for you to see it there. So maybe it would be better to change the "completed" filter to be an "approved" filter.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
