### ISSUE TITLE
As a student, I was not notified that the track has no mentor and would have wait forever he validation of my submission

### ISSUE THREAD

**Issue by daverick** [exercism/exercism#3847]
It happened to me in the Common Lisp track.

I submitted a solution but was never informed that there is no mentor for this track and that I should complete the exercise (unapproved) if I wanted to access one day the next exercise

**Comment by verdammelt** [comment]
As the maintainer and one of those "mentors" I'd like to apologize. I have a bit of a backlog unfortunately.

**Comment by sshine** [comment]
I'm going to close this issue because it relates to a specific track in the past.

The issue of assessing whether a track has active mentors is at least addressed in #5191.
