### ISSUE TITLE
mentor: Add link to own solution

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#3849]
When reviewing a solution as a mentor, I regularly find myself wanting to compare it to my own solution, for reference. Maybe a link to my own solution could be added?

**Comment by Atulkmr** [comment]
@iHiD Has anyone started working on this? If no, I'd want to do that.

**Comment by iHiD** [comment]
Hi @Atulkmr - Thanks for offering. I'll be doing it as part of the work I'm doing for https://github.com/exercism/exercism/issues/4658 and https://github.com/exercism/exercism/issues/4687
