### ISSUE TITLE
🆘 Error: Client.Timeout // Configuring the Authentication Token 

### ISSUE THREAD

**Issue by StrangeNectar** [exercism/exercism#3851]
I am getting an error attempting to configure the API-Key for Exercism CLI. I have successfully installed the CLI app on my Windows Subsystem for Linux. (Ubuntu latest stable build.) When I run the command shown below:

`exercism configure -token=<token string>`

Where `<token string>` is the authentication token that resides on my exercism.io profile under settings.

The console error is as follows:

`Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.

Get https://api.exercism.io/v1/ping: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Upon running `exercism troubleshoot` the output is as follows:

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.4
Latest:  3.0.4


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:
Workspace:
Config:
API key:   <not configured>
Find your API key at /my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 150.481ms

Exercism:
    * /ping
    * [Get /ping: unsupported protocol scheme &#34;&#34;]
    * 44µs


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

**Comment by kytrinyx** [comment]
@StrangeNectar I'm so sorry I missed this.

I'm confused as to why the troubleshoot command is not showing us where your configuration is coming from.

Would you try running `exercism configure --show`? Do you have an env var named `EXERCISM_CONFIG_HOME` or `XDG_CONFIG_HOME`?

**Comment by kytrinyx** [comment]
> on my Windows Subsystem for Linux. (Ubuntu latest stable build.)

@StrangeNectar Are you able to install the client and configure it if you install it directly within Linux? I'm wondering if this has something to do with using this from windows within linux.

**Comment by StrangeNectar** [comment]
@kytrinyx Interestingly enough I attempted this on my Home PC, which is running Fedora. I was running into the same error. Not sure why this might be.

Thank you for the tip @NobbZ I was on Ubuntu 16.04 WSL and that must have been why it wasn't working for me. I attempted the configuration on Ubuntu 18 WSL, and everything worked out flawlessly. Thank you both so much for your help with this issue!

**Comment by NobbZ** [comment]
So what is alarming for me here is, that 16.04 seems not to work. As well as there is at least a Fedora version which does not work (correctly).

I really do not care for Ubuntu 14.04, as it is end-of-life (soon), but 16.04 has another 3-ish years. The affected Fedora version needs to be checked if it is still supported, also we need to check if this also affects the most current version.

In my opinion we need to take care of that and make sure that the binary is runnable and configurable on all major distributions that are "alife" in terms of their creators.

I'd say these are Debian, Ubuntu, Fedora, maybe CentOS.

I do not think that we need to take special care for Arch or Gentoo users, as they usually are able to deal with simple problems on their own or build from source as a last resort and upstream necessary changes.

**Comment by StrangeNectar** [comment]
@NobbZ It is a little odd that it isn't working on 16.04. I can double check the version of Fedora that I am using, and I can send that information your way?

I would love to help as much as I can.

**Comment by iHiD** [comment]
Can this be closed?

**Comment by kytrinyx** [comment]
I'm going to go with "yes". @StrangeNectar if you run into more trouble, would you open a new issue, please?
