### ISSUE TITLE
Installation instructions should detect operating system

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#3855]
It would be great if the installation instructions page would automatically detect your operating system. As an example, this is also what happens when you go to `https://www.microsoft.com/net/download`.

**Comment by NobbZ** [comment]
If this gets added, please give the ability to override manually.

**Comment by ErikSchierboom** [comment]
> If this gets added, please give the ability to override manually.

Oh absolutely! It's just that a sensible default could help a bit.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
