### ISSUE TITLE
community solutions: No formatting applied to comments

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3859]
When I am looking at comments made to community solutions, they seem to be rendered without any formatting.

I do remember I had once written those comments with markdown, but the formatting is gone.

Example: https://exercism.io/tracks/elixir/exercises/bob/solutions/d937ef6f3c45400d96187667d8aa3fe9

In my last comment I am pretty sure that I have written `` `hey/1` `` instead of simply ``hey/1``.

**Comment by seanhandley** [comment]
It'd be awesome to have GHFM with syntax highlighting, like you get on github comments!

**Comment by NobbZ** [comment]
This is a bug report about legacy comments in migrated data.

There are other tickets that complain about the inability to create new comments at all.

I do assume that once comments get enabled are with markdown, since mentoring dialogue already is formatted using markdown and students reflection are going to be rendered as markdown as well once the corresponding PR has been merged.

But I'm not sure what you actually mean by GHFM.

**Comment by seanhandley** [comment]
Ah, my bad @NobbZ. I didn't want to duplicate an issue and this one seemed to be the same I was experiencing.

GHFM = Github-Flavoured MarkDown.
