### ISSUE TITLE
mentoring: give feedback of progress

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3860]
Currently I am doing a lot of mentoring on elixir and erlang, but there is not much visible feedback of progress.

Even though the cards in the list are changing/moving upwards, the scrollbar of the site stays at the same length. There is no number indicating the length of the queue. Really no encouraging feedback at all that indicates a shrinking queue.

**Comment by iHiD** [comment]
Thanks @nobbz. We'll work on this as a priority.

**Comment by iHiD** [comment]
I'm going to close this as we added counts to the dashboard since then. We'll also be thinking things through more about this for v3.
