### ISSUE TITLE
When new exercises are added to Exercism Tracks, how do they get auto-unlocked for students who should have access?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#3867]
@ihid, @kytrinyx  I have just added pangram to the Delphi track.  It is not a core exercise and is unlocked by hello-world.  I see the exercise listed on the Delphi language page, but it is locked.  My account on the site has all the other Delphi exercises unlocked and completed.  I do not know how to unlock pangram.

**Comment by NobbZ** [comment]
Has your hello world solution been approved by a mentor and completed by you? Or is it just in legacy mode?

**Comment by rpottsoh** [comment]
@iHiD  I would like to report that the previously locked exercise is now no longer locked.  :champagne:   Thanks.  Also, listing the available exercises beneath each of the core exercises is a nice touch. :+1: 

For me this issue is closed.  Feel free to close.

**Comment by rpottsoh** [comment]
Please see related comments in dupe #4080

**Comment by kytrinyx** [comment]
I *think* this has been solved. I'm going to go ahead and close this. If it's not solved for you, would you please comment here and I'll re-open it so we can investigate?

**Comment by rpottsoh** [comment]
I have checked again for the symptom that raised this issue and am no longer coming across it.  :+1:   I have no idea when it was fixed...

**Comment by iHiD** [comment]
I run this manually each time.

**Comment by rpottsoh** [comment]
ewww.  So you are manually keeping tabs on when exercises are being added and then (re)applying a fix?  Thanks for doing this.  Hopefully at some point you won't have to personally step in.  Can this be automated?  Or are you working on a permanent solution?

**Comment by iHiD** [comment]
@ErikSchierboom messages me every time anyone adds an exercise, then I run a script :)

The script takes about 8hrs to run. It's hard to speed up :)

**Comment by ErikSchierboom** [comment]
And there is of course the caveat that I only notify Jeremy when I see a change (and that only happens for the tracks I've completed).

**Comment by rpottsoh** [comment]
ugh....  I have been adding exercises to the Delphi track at a pretty healthy clip, thanks to @filiptoskovic.  I am not sure anymore I if all the new exercises are properly unlocked.  I no longer hold the status of having completed all the core exercises. :smile: 

@filiptoskovic I believe you have completed all the core exercises in Delphi.  Are you able to tell if any of the recent exercises that you have added, that you should be able to access, are currently locked?

Likely all but maybe the most recent additions will be properly unlocked for you as @iHiD runs "the fix" script with enough frequency.

@ErikSchierboom and @iHiD thanks for keeping tabs on the additions.

**Comment by filiptoskovic** [comment]
@rpottsoh I have completed 14/15 exercises. All exercises are unlocked except last one (Luhn).

**Comment by iHiD** [comment]
I've run the script probably 3 times per week, and it's global. If anyone wants to take a gander, 
I'd appreciate your thoughts. The [script is here](https://github.com/exercism/website/blob/master/app/services/fix_unlocking_in_user_track.rb). It needs:
- Making it faster
and/or
- Making it more SQL based (without locking things)

The key is probably writing something that just checks what's changed, and then working out who might be affected, rather than acting upon everything. That should make it all faster.

**Comment by arthurhess** [comment]
Hi, is this still an issue? I was going to suggest creating an ActiveJob worker for the `FixUnlockingInUserTrack` service and setting it up to run daily with [sidekiq-scheduler](https://github.com/moove-it/sidekiq-scheduler) or something of the sort.

Does it make sense?

**Comment by iHiD** [comment]
It won't be an issue in v3. Thanks for the suggestion though :)
