### ISSUE TITLE
`exercism submit exercise` is not showing link with submitted solutions

### ISSUE THREAD

**Issue by redhatmk** [exercism/exercism#3868]
The previous version of `exercism` when I submitted it was providing a link with the submitted solutions. For example [http://exercism.io/tracks/swift/exercises/etl](http://exercism.io/tracks/swift/exercises/etl). 

But right now the same link is pointing to my on submitted solutions.

**Comment by redhatmk** [comment]
@kytrinyx,

For example, with the previous version when you submit a solution you would get something like this:

```
exercism submit  RnaTranscription.swift
Your swift solution for rna-transcription has been submitted.

Programmers generally spend far more time reading code than writing it.
To benefit the most from this exercise, find 3 or more submissions that you can
learn something from, have questions about, or have suggestions for.
Post your thoughts and questions in the comments, and start a discussion.
Consider revising your solution to incorporate what you learn.

Yours and others' solutions to this problem:
http://exercism.io/tracks/swift/exercises/rna-transcription
```

Were in the URL `http://exercism.io/tracks/swift/exercises/rna-transcription` it was pointing to previous submissions and were you can check and compare what you have done in comparing your implementation with the rest of the people's implementation. 

Please let me know if you have any questions.

**Comment by kytrinyx** [comment]
> you can check and compare what you have done in comparing your implementation with the rest of the people's implementation.

Thank you, this is the information I was looking for.

Are you doing the Swift track in normal (mentored) mode, or in independent mode?

**Comment by kytrinyx** [comment]
@redhatmk As a workaround until we decide exactly how we want this to actually work, you can use the following:

```
open $(exercism submit RnaTranscription.swift)
```

This will open to your solution page directly, and the link to the community solutions is in the top right corner, right underneath the iteration count.

**Comment by kytrinyx** [comment]
I'm going to close this, since we do provide a link to the community solutions. Though we're not providing these in the CLI, we do have a workaround for getting there quickly.

@redhatmk If this doesn't solve your problem, please share more about your workflow, and we can reconsider whether we need more product discussion around this.
