### ISSUE TITLE
🆘 Cannot open after exercism upgrade in window10

### ISSUE THREAD

**Issue by tonytan1** [exercism/exercism#3875]
I am using exercism on windows10 64bit, but it seems fail to open after upgrade.
The error popup is attached. I am not sure if there is any problem on my operating system or something else. Any suggestion ?

```
Unhandled Exception: System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at shim.CommandExecutor.execute(String process, String arguments, String working_directory, Boolean is_gui, Boolean wait_for_exit, Boolean requires_elevation)
   at shim.ShimProgram.Main(String[] args)
```

![getattachmentthumbnail](https://user-images.githubusercontent.com/10009989/42791155-78100184-89a1-11e8-8077-3ecb75181742.png)

![getattachmentthumbnail](https://user-images.githubusercontent.com/10009989/42791151-72318706-89a1-11e8-9903-a10f2dc54efd.png)

**Comment by NobbZ** [comment]
This is a know bug and will be fixed in the next version. But until then you have to manually download the release package and copy the files manually to the correct places. You can use `where exercism` to find out where the current binary lives.

**Comment by guygastineau** [comment]
Did you upgrade from an earlier version or exercism or install with a binary from the releases page?

**Comment by nickborromeo** [comment]
> This is a know bug and will be fixed in the next version

I am presuming here that _next version_ is V2? If that is the case @tonytan1 can you confirm that the new version did indeed fix your issue? 😄

**Comment by NobbZ** [comment]
No, "next version" in this context was meant as "the next CLI release". The bugfix necessary is incorporated into CLI v3.0.5, once one has upgraded to or installed that version manually, then the `exercism upgrade` command should work correctly.

@iHiD @kytrinyx I think this can be closed.

**Comment by tonytan1** [comment]
sure my pleasure

**Comment by kytrinyx** [comment]
Thanks, everyone!
