### ISSUE TITLE
🆘 Issues downloading an exercise

### ISSUE THREAD

**Issue by MadhaviLosetty** [exercism/exercism#3877]
Hi, I have upgraded to exercism latest version [exercism version 3.0.4]. I am trying to resubmit one of the old exercise which was downloaded with old version and it doesn't contain metadata. Now when I am trying to download as suggested by the exercism along with metadata, getting the following error.

exercism download --exercise=rna-transcription --track=javascript
Error: rna-transcription not within workspace.

Also from where would we get to know what is the UUID to download an exercise.

**Comment by guygastineau** [comment]
- Have you joined the track on the new site?
- What is the status of your old submissions 
  on the JavaScript track?

**Comment by MadhaviLosetty** [comment]
Yes I have joined JavaScript track.  I could still see my old submissions and mentor made a comment on my submissions too.

**Comment by guygastineau** [comment]
I'm not sure what that error message is hinting at then.  Good luck. I hope someone who knows more finds this.

**Comment by nickborromeo** [comment]
👋 @MadhaviLosetty I am not a go expert my any means 😅 but I took a look at the CLI code and found this snippet

```go
// ErrNotInWorkspace signals that the target directory is outside the configured workspace.
type ErrNotInWorkspace string

// ErrNotExist signals that the target directory could not be located.
type ErrNotExist string

func (err ErrNotInWorkspace) Error() string {
	return fmt.Sprintf("%s not within workspace", string(err))
}
```

It looks like based on the comment of the error that is thrown the directory you are trying to download the exercise into is outside the directory that you configured 

One thing you could do is to run the `exercism troublehsoot` command and the output will have a section called Configuration that will show you your workspace. You can double check that the value there makes sense. 

You can also use https://exercism.io/cli as a possible reference.

**Comment by iHiD** [comment]
Can this be closed?
