### ISSUE TITLE
mentor: Links in notifications mail don't include iteration

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#3881]
When I get a notification mail as a mentor, it contains a link to go to the corresponding submission. However, this link does not include the iteration, so if a student has posted another iteration after the mail was sent, the link leads to a different page.

**Comment by NobbZ** [comment]
The same is true for notifications on the website.

**Comment by iHiD** [comment]
@kntsoriano Can you add iteration id to both notifications and emails pls?

**Comment by iHiD** [comment]
The best method of solving this will be to change the link to be a link to `my_solution_iteration_path(solution, iteration)`

**Comment by lastgabs** [comment]
I'll take this over if @kntsoriano isn't on it already!

**Comment by kntsoriano** [comment]
@lastgabs Go ahead :)

**Comment by iHiD** [comment]
I've assigned this to myself to block anyone else from doing it while @lastgabs is giving it a go :)

**Comment by iHiD** [comment]
Reassigning this to @loriking and @amaliacardenas as part of their Rails Girls Summer of Code project :)

**Comment by PatrickMcSweeny** [comment]
Any progress on this?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
