### ISSUE TITLE
Automate steps to execute tests when mentoring.

### ISSUE THREAD

**Issue by FabienTregan** [exercism/exercism#3882]
Hi,

  I have made a few code reviews yesterday, and noticed that I ended up reading the code without running the tests.

  ## When I run the tests I do this:

1. Select and copy the uuid from the adresse bar in the browser where I am viewing the code
2. `exercism download -u [paste the uuid]
3. cd to the download directory (nice that I can just copy/paste the path from previous output)
4. switch to my IDE an open the said directory (most of the time the code is larger than the textarea on the website anyway)
5. open the test file and remove all the `@ignore` annotations (for the java track,other languages probably have similar step) and save
6. gradle test
7. switch back to the browser to write the feedback (and validate)

  ## When I don't run the test I do this:

 1. read the code in the browser
 2. write the feedback (and validate)

  ## Questions

 * Am I the only one too lazy to do this every time ?
 * Did I miss some mentor oriented features from the CLI ?
 * Would it be to difficult to propose a default process that could be supposed to work for most mentors ? (note that the steps I describes are not applied as-is when it is not the first iteration)

  ## What I imagine for now (highly subject to discussion)

We could provide a "copy to clipboard" button that would generate the command line that would run many of these steps in one operation (lets make sure it is a red button that only get enabled once we have viewed all the code, we are running code from unidentified source locally !)

**Comment by NobbZ** [comment]
Originally it was planned that in v2 testsuites are submitted by the client as used by the student.

Du to some general problems with this apprach the CLI does currently not do so, and current testsuites as from the repository are assumed.

At the end everything relates to exercism/cli#458

**Comment by iHiD** [comment]
Really helpful idea. Thanks. I'm realistically not going to be able to give this attention for the next couple of weeks, but very keen to see what you all think about this.

**Comment by kybernetikos** [comment]
This would be cool, although I'd like automated testing that just reports the result in the browser even more.  Like a CI badge.  I vaguely remember a service that offered this kind of thing for free to community projects, but I can't find it now.

**Comment by rpalo** [comment]
I was looking at this too, since I'm running essentially:

```bash
exercism download --uuid=BLAHBLAHBLAH
cd exercise_dir
sed -i'' '/skip/d' exercise_test.sh
bats exercise_test.sh
shellcheck exercise.sh
```

for every new solution I mentor.  

It looks like there's already a mechanism for calculating/displaying the exercise's mentor-download-command, but right now it's basically hardcoded to just to `download --uuid` command.  Would a pull request for a little more custom per-track download script or command be welcome?  Or is there a better way to approach this?  Just a thought.  Of course, it's just as easy for me to put a `mentor_bash` script in with my shell scripts, so no biggie either way :smile:

**Comment by iHiD** [comment]
> Would a pull request for a little more custom per-track download script or command be welcome? 

I think a PR would be premature as there would be a lot to discuss first, and it would probably need to be lots of PRs to various repos. I'm happy to continue the discussion here and then maybe we get to that point through.

As a sidenote, I'm still very wary of encouraging auto-running user-submitted code. I also don't run the tests myself when mentoring, but I understand that different languages offer more complexities than Ruby that makes this more of an essential thing to do.

**Comment by gitlui** [comment]
Maybe this could be automated by the usage of docker images? There would be almost no problems with stuff like rm -rf commands and such. And the images are almost always there for every language prepackaged with the required tools.
This even leaves open the possibility to automatically start a docker container with the submitted code just after it was pushed. Of course there are some costs for aws instances or such by doing so.
But there are ways to limit the number of concurrently running instances and implementing queues with wait times for resubmits to prevent DoS attacks and such.

**Comment by weakish** [comment]
> It's a security concern to run or not run the tests without looking at the code first.

The learner (submitter) should always make sure tests are passed before submitting the answer.
Mentors are not expected to run tests:

1. This may have serious security issue as pointed out by @NobbZ 
2. This is just a bad habit, like pushing untested code to repository.

> This even leaves open the possibility to automatically start a docker container with the submitted code

Maybe using some travis like CI services? In some cases learners do need this kind of service:

1. as a beginner, struggling to setup a working environment for that language
2. on a device where they cannot run tests, for example, on an iPad

**Comment by iHiD** [comment]
Thanks all. We'll be running tests server side in the next couple of months.
