### ISSUE TITLE
Syntax highlight of java generics and lambdas

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3890]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/217._
_Originally posted by @FabienTregan._

#

When inserting some java with generic code, selecting the code then pressing the "code" button, things go fine avec the code syntex highlighted.

But then when you go on the preview tabpane, it get all messed up :
```
private Function<String[], String> x = null;
```
becomes
```
private Function<string string> x = null;
</string>
```
(coma is lost, `String` is lowercased)

and 
```
private Function<String[], List<String>> x = x -> x;
```
becomes
```
private Function<string list>&gt; x = x -&gt; x;
</string>
```

The preview (worst) version is the one that gets in the comment. (Happened to me [here](https://exercism.io/mentor/solutions/564b228764cc4d0b89cfd1bbb1ca5be6#discussion-post-133739))

**Comment by kluufger** [comment]
👋

It seems to also affect elixir

```
defp trim_alpha(<<char, rest::bytes>>, acc) when char in ?a..?z or char in ?A..?Z do
  trim_alpha(rest, <<char, acc::bytes>>)
end
defp trim_alpha(<<char, rest::bytes>>, acc) do
  trim_alpha(rest, acc)
end
defp trim_alpha(<<>>, acc), do: acc
# etc (for german)
```
is turned into
<img width="455" alt="screen shot 2018-08-02 at 8 32 21 am" src="https://user-images.githubusercontent.com/35971588/43572561-67fa912a-962f-11e8-98d1-b4f70830ea7e.png">

**Comment by grantwinney** [comment]
I'm not sure if this is related or not, but it seems to be in the same arena.

I posted some additional C# tests to a student like this:

```csharp
[Fact]
public void With_h1_header_level_with_hash_in_text()
{
    var markdown = "# This will be an h1 for c# language";
    var expected = "<h1>This will be an h1 for c# language</h1>";
    Assert.Equal(expected, Markdown.Parse(markdown));
}

[Fact]
public void Parses_normal_text_with_hash_as_a_paragraph()
{
    var markdown = "This will be a paragraph about c#";
    var expected = "<p>This will be a paragraph about c#</p>";
    Assert.Equal(expected, Markdown.Parse(markdown));
}

[Fact]
public void Parses_normal_text_with_asterisk_as_a_paragraph()
{
    var markdown = "This will be a paragraph with ***";
    var expected = "<p>This will be a paragraph with ***</p>";
    Assert.Equal(expected, Markdown.Parse(markdown));
}

[Fact]
public void Unordered_lists_with_hash_in_text()
{
    var markdown =
        "* Item 1 for c#\n" +
        "* Item 2 for c#";
    var expected = "<ul><li>Item 1 for c#</li><li>Item 2 for c#</li></ul>";
    Assert.Equal(expected, Markdown.Parse(markdown));
}
```

And it rendered like this, removing all HTML tags. Actually, it's almost like it rendered the HTML tags (like the unordered list in the last "test") but then displayed everything as plaintext anyway.

```csharp
[Fact]
public void With_h1_header_level_with_hash_in_text()
{
    var markdown = "# This will be an h1 for c# language";
    var expected = "This will be an h1 for c# language";
    Assert.Equal(expected, Markdown.Parse(markdown));
}

[Fact]
public void Parses_normal_text_with_hash_as_a_paragraph()
{
    var markdown = "This will be a paragraph about c#";
    var expected = "This will be a paragraph about c#";
    Assert.Equal(expected, Markdown.Parse(markdown));
}

[Fact]
public void Parses_normal_text_with_asterisk_as_a_paragraph()
{
    var markdown = "This will be a paragraph with ***";
    var expected = "This will be a paragraph with ***";
    Assert.Equal(expected, Markdown.Parse(markdown));
}

[Fact]
public void Unordered_lists_with_hash_in_text()
{
    var markdown =
        "* Item 1 for c#\n" +
        "* Item 2 for c#";
    var expected = "
Item 1 for c#
Item 2 for c#
";
    Assert.Equal(expected, Markdown.Parse(markdown));
}
```

**Comment by mawis** [comment]
Same problem affects Rust code a lot.

**Comment by kytrinyx** [comment]
Thanks everyone. I'm not sure if this is a problem in the underlying Prism library, or in how we're passing it to the library.

**Comment by iHiD** [comment]
@grantwinney @mawis Could you open separate issues for your examples please as although they smell the same, they're probably different bugs.

@grantwinney Your issue is definitely a bug our end and not with Prism (unlike this main issue)
@mawis I need to see code to know whether this is an issue with Prism or us. I'm using https://prismjs.com/test.html to work it out.

**Comment by iHiD** [comment]
@grantwinney From what you wrote am I right in thinking that your issue is specific to the fact you're posting in comments, rather than if you just submitted code?

**Comment by grantwinney** [comment]
That's correct @iHiD, I was posting code in the comments field for the student to see. I removed the comment here (to keep the thread clean), and opened a separate issue. https://github.com/exercism/exercism/issues/4240

**Comment by iHiD** [comment]
Thank you!

**Comment by iHiD** [comment]
@kluufger Do you have a sample solution uuid where this happened pls?

**Comment by kluufger** [comment]
@iHiD [sure](https://exercism.io/mentor/solutions/b370fed11dc1438b8d508944c8c0af30?iteration_idx=1).

Off-topic, while searching for that solution, I've noticed that
```elixir
&[&1 | &2]
```
is colored a bit [strangely](https://exercism.io/mentor/solutions/8d1cbce8f8e44e7aa45071f08f451293?iteration_idx=1) as well

**Comment by iHiD** [comment]
If you look at that first solution, is that better for you now?

Re - the second one - no idea :) Feel free to create a separate issue for that and we'll get to it, but probably as a lower priority.

**Comment by kluufger** [comment]
> If you look at that first solution, is that better for you now?

@iHiD yes, it looks great now, except for 
```elixir
defp trim_alpha(<<>>, acc), do: acc
```
part:
<img width="337" alt="screen shot 2018-08-21 at 1 16 29 pm" src="https://user-images.githubusercontent.com/35971588/44403608-74c18980-a544-11e8-935d-ba5bd6a717ee.png">

I'd expect the `<<>>` brackets in the last clause to be gray as well (they are brown for me right now).

**Comment by iHiD** [comment]
I've just tested on https://prismjs.com/test.html with that code and Elixir selected as the language, and the bug is present there too. Could you open an issue at https://github.com/PrismJS/prism/issues for that one pls? We won't fix it here.
