### ISSUE TITLE
[mentor] Accidentally approved, cannot revoke it

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3891]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/216._
_Originally posted by @c-dante._

#

Title. I accidentally hit "Approve + Comment" instead of just "Comment" -- it's no big deal, but would be nice to undo that.

Same with editing / deleting comments, but I wager those are in another issue already.

**Comment by jmrunkle** [comment]
This - it just happened to me too. Never realized there was no way to undo that.

**Comment by jmrunkle** [comment]
It is also mildly important because it is much harder to see comments from students once the solution has been approved.

**Comment by iHiD** [comment]
The consequences of this are are strong. Unlocking exercises, emailing the student, etc. So unapproving it is difficult.

**Comment by c-dante** [comment]
From a strictly UX standpoint, even having an undo window or are you sure window from the mentor perspective is useful.

Given that there is a hard to undo state after, it should be fine for the extra click.

**Comment by iHiD** [comment]
Agree entirely.

**Comment by paparomeo** [comment]
Got bitten by this today, where a "slip of the mouse" made me approve an exercise where the tests don't even work. :disappointed: A confirmation, or a grace period (even a short one like one minute), would be enough to avoid/correct the mistake, since it's pretty obvious after the erroneous approval has been given.

**Comment by sshine** [comment]
I just write "Oops, I accidentally approved you when ... is missing. Would
you like to try and fix that while also having the option to solve the next
exercise?"

If I never hear back from this request, nothing bad has happened.

**Comment by paparomeo** [comment]
@sshine: that's also what I do. That doesn't make it a good UX to have irrevocable actions that can happen with a single click. I know there's bigger fish to fry, but at some point it would be good to improve the user experience in this case.

**Comment by sshine** [comment]
I've only accidentally clicked it ~5 in 1000 times, and I've associated
practically no cost with doing so, but it does seem a bit problematic when
you phrase it like that.

**Comment by iHiD** [comment]
We're going to be changing this bit quite a lot for the v3 changes, so I suspect we won't change it beforehand, but I agree about irrevocable actions and will take that into consideration in the future.

**Comment by paparomeo** [comment]
Thank you for the update @iHiD. Looking forward to it!

**Comment by clockelliptic** [comment]
Yes, I just accidentally approved a solution that, thankfully, was just proper enough for approval. 

There _**really really really really**_ should be an "Are you sure?" prompt. From a UX standpoint, the prompt is pretty much mandatory given the consequences of accidental approval. 

Accidental approval degrades the record of published solutions and potentially robs a student of the ability to get proper mentoring in the case that a low-quality mentor was their last contact.

**Comment by iHiD** [comment]
I added a confirmation and it's annoyed people so I've reverted it. We'll either find a better way, or more likely we'll just wait to v3 when this changes anyway.
