### ISSUE TITLE
Running the website on windows

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3895]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/209._
_Originally posted by @FabienTregan._

#

Hi, I tryed to run the server on windows following the instructions in https://github.com/exercism/website/blob/master/README.md and needed to add a few step (I know some of them are windows related, not sure they all are.)

* before installing Ruby, I needed to install CMake
* add this line to gemfile : `gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]` (unwanted on linux)
* before running any of the `bundle` commands, I hade to install bundle : `gem install bundler`
* after the mysql commands, I hade to `mysql -e "ALTER USER 'exercism_reboot'@'localhost' IDENTIFIED WITH mysql_native_password BY 'exercism_reboot'" -u root -p`, maybe I was missing a lib to use the default authentification method (that seemed a better solution but I don't know anything about ruby / rails)
* `bundle exec rake bin/setup`did not create the tables, `bin/setup` gives and error. I hadet to `rake db:drop db:create db:schema:load`

then `http://localhost:3000` complains about missing `//= require simplemde/dist/simplemde.min.js`. I could manual fix the problem in an hugly way, but then another .js was unfound. Ihid on slack told me :
>The bin/setup *should* have ran "yarn install" which should have installed the assets. You shouldn't need to add it to the gemfile. [...]

Maybe the problem is that I don't have yarn installed.

I'm not in a hurry to run the server locally, but wanted to trace my experience while am still uneperienced.

**Comment by iHiD** [comment]
I'm closing this as a lot has changed since this.
