### ISSUE TITLE
Make it easier to download next core track exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3913]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/178._
_Originally posted by @HarrisonMc555._

#

This may be something that can wait until after launch, but I think it would significantly improve the UI.

One thing I liked about exercsim-v1 was that if I wanted to download the next exercise, I simply typed `exercism download <track>`. I didn't even have to open a browser or anything.

This may be by design in order to encourage people to actively check the exercism-v2 page and see the feedback they've gotten before downloading the next exercise. I'm guessing that's why you have to manually "complete" an exercise in order to move on to the next one.

Maybe I'm just lazy, but it just seems a little annoying to go to the next core exercise's page, copy and paste the download command or exercise slug, go back to my command line, and download it.

**Comment by agoldh20** [comment]
For sure my favorite part about v1 was the ```exersicm fetch ruby``` if I wanted the next ruby exercise. Please bring that feature back!

**Comment by iHiD** [comment]
There are no "next exercises" any more beyond the core track so I'm not sure how this would work? You unlock exercises on the website then choose the one you want to download. 

Would you want `exercism download ruby --next-core-exercise` or `exercism download ruby --random-side-exercise` or something?

**Comment by john681611** [comment]
Yeah, this is super frustrating when you are just starting out and can power through and the site isn't updating.
`exersicm fetch` was a great command and I really don't see why its not been continued in some form in the newer version.
Just make default `exercism download <track>` get the next core one and add a flag for getting any extras.

**Comment by peschkaj** [comment]
@iHiD those would both be great options. As a future nicety/stretch goal, it would be cool to have `exercism download ruby --random-side-exercise --difficulty easy` or something like that so the user knows what kind of challenge they're getting. I'm not sure I'd want to get a difficult exercise when I've said "Oh, I've got an hour to goof off and Game of Thrones isn't on... I know, I'll do an exercism!"

**Comment by iHiD** [comment]
> Yeah, this is super frustrating when you are just starting out and can power through and the site isn't updating

@john681611 I don't understand what you mean about "site isn't updating" Could you expand pls?

**Comment by agoldh20** [comment]
Exercism didn't used to be broken down into core exercises, it used to just be exercises that should be done in a specific order.

**Comment by kytrinyx** [comment]
@agoldh20 The decision to do break it down into core/side exercises was deliberate. We're aware that there are trade-offs, and we made them quite carefully.

In independent mode there is no distinction between core/side exercises, though, so that might be an option. I think there are some small changes we could make to the independent track that would help make this experience better for those who are not interested in the core/side distinction. We'll need to think it through on the product-side.

**Comment by john681611** [comment]
> > Yeah, this is super frustrating when ou are just starting out and can power through and the site isn't updating
> 
> @john681611 I don't understand what you mean about "site isn't updating" Could you expand pls?

Ignore that your system has changed to depend on mentors so i just needed to turn it off)

**Comment by trevordmiller** [comment]
I recently upgraded to the latest CLI and really miss the `exercism fetch {track}` as well. I would really like the `exercism download {track} {next}` type things as suggested where {next} is the next problem in the track or the next side problem if all core problems have been completed.

**Comment by iHiD** [comment]
I'm closing this as we're moving even further away from a linear progression in v3, so this won't be coming back. Thank you all for your thoughts.
