### ISSUE TITLE
500 Internal Server Error when submitting some previous (non-current) exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3914]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/176._
_Originally posted by @HarrisonMc555._

#

When I tried to submit a revised version of an exercise (Python: reverse-string), I got a `500 Internal Server Error`. When I made *another* edit and submitted that, it gave me the same error. However, when I edited the current exercise I was on (Python: bob) **and** a completely different exercise (Python: leap), it didn't return an error.

I wish I could provide more details for debugging, but I'm not sure what else to provide. Here's the output of `mentorcism troubleshoot`:

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.0-alpha.9.mentors
Latest:  2.4.1


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/harrison
Workspace: /home/harrison/mentorcism
Config:    /home/harrison/.config/mentorcism/user.json
API key:   9f1c*****************************d22

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 88.684484ms

Exercism:
    * https://mentors-beta.exercism.io/api/v1/ping
    * [connected]
    * 671.547354ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

**Comment by iHiD** [comment]
@kytrinyx Is this closeable?

**Comment by kytrinyx** [comment]
I think so. If not, it will happen again, and we can open a new issue.
