### ISSUE TITLE
Unable to comment on published submissions

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3921]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/163._
_Originally posted by @NobbZ._

#

Currently there seems to be no way to comment on published submissions.

https://exercism-mentors.slack.com/archives/CAQP7JL3T/p1529789240000024

**Comment by iHiD** [comment]
We added this.
