### ISSUE TITLE
Leave of Absence notification

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3922]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/162._
_Originally posted by @simpleauthority._

#

Greetings,

Please see the Slack thread: https://exercism-mentors.slack.com/archives/CAQP7JL3T/p1529803004000045

Mentors should have the ability to let everybody know they are currently away and not mentoring. Ideally, it should have a "return date" that will show on the profile letting people know when they will be back.

**Comment by iHiD** [comment]
This will become irrelevant with v3, and I'm not going to do it beforehand, so I'm going to close this. Sorry we didn't get round to it beforehand.
