### ISSUE TITLE
Been here before copy button feedback missing

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3926]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/158._
_Originally posted by @ErikSchierboom._

#

While I love the copy button in the "Been here before" section of an exercise, there is no obvious feedback that anything happened when I click on it, except for the text to be selected. A little tooltip would help here, similar to [this example on SO](https://stackoverflow.com/questions/37381640/tooltips-highlight-animation-with-clipboard-js-click/37395225#answer-37395225):

![image](https://user-images.githubusercontent.com/135246/41808748-6e065ef8-76e2-11e8-83a2-3ace9b64387e.png)

**Comment by iHiD** [comment]
We fixed this.
