### ISSUE TITLE
Let people view old notifications

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3936]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/134._
_Originally posted by @martinfreedman._

#

Once I have responded to a notification, it disappears. I was expecting any v2 to provide a notification history with metadata of userid, exercise, likes flags and date. (see also #130)

**Comment by bdjnk** [comment]
I find it very obnoxious that notifications are irretrievably lost once they have been "read". I'm actually scared to read them unless I have time to resolve it fully in that moment. This, for me, is a significant disincentive from using the site in a frequent quick way. Regarding GitHub notifications, [recently read notifications **are** available](https://github.com/notifications?all=1).

**Comment by Cohen-Carlisle** [comment]
It would be nice to set a time-to-live on read notifications instead of immediately destroying them.

**Comment by PatrickMcSweeny** [comment]
I think this could be closed.

**Comment by iHiD** [comment]
Thanks @PatrickMcSweeny
