### ISSUE TITLE
Cannot tell if there are any comments on other iterations

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3941]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/128._
_Originally posted by @martinfreedman._

#

I cannot see if there are comments on other iterations, again a feature I would miss. 

I will stop adding issues for now. And await feedback on these and if this is the correct place to discuss the design questions.

The new design looks great but  not sure about all this loss of functionality I have seen so far.

**Comment by iHiD** [comment]
We added this.
