### ISSUE TITLE
Cannot expand solution box

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3942]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/126._
_Originally posted by @martinfreedman._

#

This is a great feature in v1 with the sw ne arrows button.  I tried double clicking on the latest solution tab but that does nothing. I hope this is the plan for the final release. I look at the solution on different devices and the expand feature is invaluable

**Comment by ruanpienaar** [comment]
yeah, solution box could be slightly larger, or at least include some button that expands it:
<img width="1285" alt="screenshot 2018-12-07 at 16 46 51" src="https://user-images.githubusercontent.com/584394/49661034-f7ad1800-fa3f-11e8-9cfa-bf8ce4728b61.png">

**Comment by iHiD** [comment]
We allowed full-width solution boxes :+1:
