### ISSUE TITLE
Informing students of test suite updates

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3943]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/125._
_Originally posted by @rpottsoh._

#

On V1 there is no way to inform students that the test suite for an exercise has been updated.  I think this would be a nice addition to V2. 

If V2 can track when a student last fetched an exercise it should then be able to display an indicator next to the exercise on the site to catch the students attention.  The indicator should be intuitive to mean that the exercise has been updated and that they should re-fetch the exercise.  An alternative approach might be to email the students that have fetched a particular exercise when those exercises have been updated....  I am more in favor of the first idea personally.

@kotp put it this way:
> Something a lot less than an announcement, something slightly more than silence.

**Comment by Stargator** [comment]
I would also add to inform mentors of this as well. Since when mentoring, we will download the student's solution, but the test suite might have changed.

I would be of the mind that the mentor should be informed of changes to the test suite, but given the test suite by which the student's solution should be run against.

That way the mentor can provide feedback as well as serve as another voice recommending the student re-fetch the exercise and try their solution against the updated test suite.

**Comment by iHiD** [comment]
I *believe* that the `download --uuid=xxx` will honour the point in time that the solution was implemented, and download the relevant tests. This might not be true for legacy ones but should be for new ones where the tests change.

**Comment by NobbZ** [comment]
@kytrinyx once said the first time an exercise is downloaded, it will be fixed to exactly those tests forever. You can not update to more current tests.

This is contrary to what was advertised in the early alpha testing were it was said that we will be able to see even local modifications to the tests a student made without requiring him to submit the tests explicitly.

**Comment by iHiD** [comment]
> @kytrinyx once said the first time an exercise is downloaded, it will be fixed to exactly those tests forever. You can not update to more current tests.

That is correct.

> This is contrary to what was advertised in the early alpha testing were it was said that we will be able to see even local modifications to the tests a student made without requiring him to submit the tests explicitly.

Obviously we can only see local modifications to test if they get from student's computer to us. As I believe the CLI is currently ignoring the test pattern, I imagine this is not the case. But I might be wrong.

**Comment by NobbZ** [comment]
Yeah, I know that this is complicated, and I already made a lot of comments pointing out the blocking stones...

**Comment by Stargator** [comment]
I feel like I was told I could submit the test suite if I had changed it. But I can't recall ever doing so and I don't see an example of that in any of my v1 submissions.

**Comment by rpottsoh** [comment]
I thought the CLI would balk at any upload (submitted) files that contained the word `test` in their name.   Uploading a modified test suite would also require renaming the file name.  I have not tried uploading a test suite so I don't have first hand experience to work from...

**Comment by kotp** [comment]
It can be submitted as can be seen in this screenshot today. 

The command I used was `exercism submit hello_world.rb hello_world_test.rb`

![submit_test_too](https://user-images.githubusercontent.com/16747/43680304-a774992c-9805-11e8-91df-08cac1d2248a.png)

Of course, this makes no matter unless we know which version of the CLI it is... exercism version 3.0.6
