### ISSUE TITLE
Make interesting conversations about code easier to find?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3944]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/124._
_Originally posted by @stoft._

#

Hi,

Sorry if this is a duplicate or similar, I searched a bit, couldn't find anything and my time is too limited to research more before posting.

I'm an old exercism user who loved it for a few months three years ago and since then have only used it sparingly, mostly due to other priorities in life but also due to spending time on a coding project of mine instead of coding exercises. I do still recommend it far and wide whenever I get the chance.

Today a new exercism user who had seen our conversations from three years ago and found them really valuable took the time to hunt us down on Slack and personally communicate his appreciation:

> I just wanted to thank each of you for the wonderful conversations you've had around solving a number of the Elixir exercises on Exercism. My solution (...) for say the `sublist` exercise is inspired by each of your solutions in different ways. Thank you once again as your conversations make learning Elixir even more exciting for me through Exercism as I can look forward to more of these learnings (through conversations around each iteration) each time I pick up a new exercise :slightly_smiling_face:. Please do keep these conversations going whenever you solve more exercises in any language!

This made me realise that one of the best things about exercism to me was, and still is the fantastic conversations people have about code. My personal experience is also that these conversations do not always occur on Exercism and my worry is that with thousands of solutions to the same problem the interesting conversations become hard to find. Moving forward into v2 it would be nice if these conversations could be amplified somehow so that they become easier to find, e.g. for people who join the community years after the conversations happened. Perhaps this diverges from the goals of v2 but I couldn't stop myself from at least providing the feedback.

Regardless, a big thank you for making exercism!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
