### ISSUE TITLE
Delete uploaded files

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3946]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/107._
_Originally posted by @budmc29._

#

I had a look through the issues and could not find any reference to this, or maybe I missed it.

Is there any way to delete a submission? By mistake I uploaded my npm_folder with the submission and I would like to delete the folder/files.

![no_file_deletion](https://user-images.githubusercontent.com/7063792/30040315-8aafdc70-91d5-11e7-8018-aeea8e6059ee.png)

**Comment by iHiD** [comment]
Closed in favour of #3848.
