### ISSUE TITLE
“curly” needs a name

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3956]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/60._
_Originally posted by @NobbZ._

#

The cute new logo-mascot needs an official name. For now I call it “curly” because its made from curly brackets, but I hope there will be better ideas around…

**Comment by iHiD** [comment]
Closing. I'm happy with "curly"  :)
