### ISSUE TITLE
Check all headers around the site are sentence-case

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3966]
From: https://github.com/exercism/v2-feedback/issues/159

**Comment by amaliacardenas** [comment]
List of the titles that need to be changed

- [x] `app/views/solutions/show.html.haml:            %h2 Community Comments`
- [x] `app/views/team_pages/_header.html.haml:    %h1 The Exercism Team`
- [x] `app/views/team_pages/contributors.html.haml:  %h2 Our Volunteer Contributors`
- [x] `app/views/team_pages/maintainers.html.haml:  %h2 Our Track Maintainers`
- [ ] `app/views/team_pages/mentors.html.haml:  %h2 Our Track Mentors`
- [ ] `app/views/team_pages/show.html.haml:      %h2 Our Core Team`
- [ ] `app/views/teams/teams/index.html.haml:    %h1 Your Teams`
- [ ] `app/views/teams/teams/index.html.haml:      %h2 Pending Invitiations`
- [ ] `app/views/teams/teams/memberships/index.html.haml:    %h1 Your Team`
- [ ] `app/views/teams/teams/memberships/index.html.haml:        %h2 Pending Invitations`
- [ ] `app/views/teams/teams/my_solutions/index.html.haml:    %h1 Your Solutions`
- [ ] `app/views/teams/teams/my_solutions/show.html.haml:          %h3 Team Feedback`
- [ ] `app/views/teams/teams/new.html.haml:    %h1 Create New Team`
- [ ] `app/views/teams/teams/new.html.haml:        %h3 Team Name:`
- [ ] `app/views/teams/teams/new.html.haml:          %h3 Change Logo:`
- [ ] `app/views/teams/teams/new.html.haml:        %h3 Invite Team Members:`
- [ ] `app/views/teams/teams/solutions/index.html.haml:    %h1 Your Team's Solutions`
- [ ] `app/views/teams/teams/solutions/show.html.haml:          %h3 Team Feedback`
- [ ] `app/views/tracks/index.html.haml:      %h1 Language Tracks`

**Comment by amaliacardenas** [comment]
All  h1/h2/h3, breadcrumbs, tabs, and other titles were modified to sentence case. exercism/website#292
