### ISSUE TITLE
Buttons should be disabled upon press

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3969]
Buttons should be disable then once they've been pressed to avoid multiple server calls. For AJAX actions, re-enable them if appropriate once we have a response. It might be worth using a general JS rule for anything with the class of `.pure-button', but we will need thorough testing of all pages if we go down that route, as there are some buttons that open modals, which should not be disabled.

I imagine that doing something like `$button.attr(disabled: true).addClass('disabled')` would be appropriate.

Pls start with the commenting buttons on mentors and my solution page. Thanks :)

Triaged from: https://github.com/exercism/v2-feedback/issues/173

**Comment by PatrickMcSweeny** [comment]
It seems like [this commit](https://github.com/exercism/website/commit/54a57284d9f36102c429a6874c35212852171e91) would take care of this issue. Is there anything else that would need to be added?

**Comment by iHiD** [comment]
@PatrickMcSweeny 
1. That class needs adding to all non-ajax buttons.
2. For AJAX buttons we should probably have a different class and a new method that uses the Rails ajax callback, not the `click` method, and then re-enables the button on the ajax response.
