### ISSUE TITLE
Fix reflections.

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3972]
- [ ] Change the [view](https://github.com/exercism/prototype/tree/master/app/views/my/solutions/reflection/_publish_solution_form.html.haml) to render as markdown*
- [ ] Render out markdown wherever we show `solution.reflection`. There's a `ParsesMarkdown.parse()` method that will help here.

There's some UI we use for this in other places such as [here]( https://github.com/exercism/prototype/tree/master/app/views/my/solutions/_discussion.html.haml). It relies on the JavaScript of `setupNewDiscussionPost()` [here](https://github.com/exercism/prototype/tree/master/app/assets/javascripts/solution.coffee), so this could probably all be extracted into a nice widget.

**Comment by nicolechalmers** [comment]
@iHiD As per our conversation, I've changed the design of the reflection text box slightly.

- box border and quote icon #32B392
- "HiDs reflection:" Semi-bold, font size 14
- quote icon is Font Awesome quote-left
- text regular, font size 14

<img width="689" alt="screen shot 2018-07-25 at 14 02 01" src="https://user-images.githubusercontent.com/5421823/43199839-9b67ed40-9013-11e8-978e-6b8940fcb369.png">

**Comment by rrcobb** [comment]
Seconded. It's almost worth killing the reflection feature entirely in favor of asking for a first comment as a reflection. The comments feature has both markdown rendering and edit / delete functionality (#3894)

**Comment by rrcobb** [comment]
(for instance, see this [solution](https://exercism.io/tracks/rust/exercises/diffie-hellman/solutions/bc02fc0cef374647a6af068e40027068) where the comment renders nicely (and can be edited / deleted) and the reflection renders poorly and can't be changed.

Love the pedagogy of doing a reflection when completing an exercise. Thanks for thinking about the learning process!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
