### ISSUE TITLE
🆘 Issues with compaitability

### ISSUE THREAD

**Issue by Robinwithahood** [exercism/exercism#3977]
Hello,

I have been trying to submit my solutions using the "exercism submit" method through the command prompt. I seem to have issues doing so, as I keep getting an error that says "unsupported 16-bit application", which further mentions "The program or feature cannot start or run due to incompatibility with 64-bit versions"
and asks me to reach out to the software vendor. I would appreciate any assistance regarding the issue. 

-- 
Robin

**Comment by NobbZ** [comment]
This is a known bug in the updater. Automatic updating will not work before you installed the not yet released version manually.

Please download the release ZIP manually from github.com/exercism/cli and unzip it at the correct place.

You can use `where exercism` to find the folder where the current version is installed.

**Comment by kytrinyx** [comment]
You can find the most recent release at https://github.com/exercism/cli/releases/latest

**Comment by iHiD** [comment]
Can this be closed?

**Comment by Robinwithahood** [comment]
Yes

**Comment by iHiD** [comment]
Thanks :)
