### ISSUE TITLE
cli: Allow downloading of latest version

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#3983]
As @kytrinyx explained to me in https://github.com/exercism/cli/issues/649#event-1738999726, unlocking an exercise results in pinning the linked version to the version at the time of unlocking. This means that later fixes won't be reflected when you re-download the exercise. Most of the time, this is probably what you want, but I can think of two cases where being able to explicitly download the latest version of an exercise would be helpful:

1. When a critical fix has been applied.
1. When a track maintainer wants to verify the latest version of an exercise.

**Comment by NobbZ** [comment]
3. When you revisit your old exercises to let them match current testsuite and changed idioms
4. When you revisit old exercises to let them mirror your gain in experience

**Comment by kytrinyx** [comment]
Thanks! This is not related to the CLI, as far as I can tell. I think it's worth considering all of these use cases from a product perspective. In particular, I think that there are a slew of things we'll want to do specifically to help maintainers maintain and verify their tracks.

**Comment by iHiD** [comment]
Done.
