### ISSUE TITLE
Allow mentors to view other mentors' comments

### ISSUE THREAD

**Issue by scarerkite** [exercism/exercism#3988]
It would be really helpful for mentors to be able to view other mentors' comments. I've learned a lot from being able to see how other people made suggestions on solutions on the old site, or on my own solutions and it would be great to get that functionality back. 

Right now I feel a little isolated just seeing solutions that I am mentoring, and rather than constantly posting on Slack asking how to make helpful suggestions, it would be nice to be able to browse and see how other mentors tackle certain patterns.

**Comment by iHiD** [comment]
Yep - great point. This is something we'll work on soon :)

**Comment by dpolivaev** [comment]
As a beginning mentor, I would be interested to study solutions mentored by others filtered
by track, excersize, and status(completed or not). Ideally, I would just press a button on the solution I see on my own mentor dashboard to see all other solutions mentored by the others. Given this feature, I could learn which aspects were addressed by other mentors in comparable cases and how they communicate their concerns/suggestions/questions.

Are you still working on this feature request? Do you have any estimate when it can be available?

**Comment by dpolivaev** [comment]
Beyond that, I would like to be able to ask other mentor questions about their comments so that it is not visible to the mentees. This way mentor comments could be reviewed by other mentors, and I believe that reviews are great way of improvement and raising awareness.

**Comment by iHiD** [comment]
I've added this to the roadmap. I hope to get to it during October.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
