### ISSUE TITLE
Alignment of filter menu on mentor dashboard is off

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#3994]
See:

![image](https://user-images.githubusercontent.com/135246/42900898-5b41fe84-8aca-11e8-8400-05fb62431e10.png)

**Comment by iHiD** [comment]
I love your attention to detail :)

**Comment by iHiD** [comment]
No. You're great :)

**Comment by ErikSchierboom** [comment]
![You're awesome](https://i.imgur.com/CCLPv27.gif)

**Comment by ErikSchierboom** [comment]
> I do not get it… I just see a triangle…

That's odd. It is of course a screenshot. Can you open this link: https://user-images.githubusercontent.com/135246/42900898-5b41fe84-8aca-11e8-8400-05fb62431e10.png

**Comment by NobbZ** [comment]
Still a triangle... Of course I see as well the red box and the other stuff, but I do not see **it**.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
