### ISSUE TITLE
auto-indents should stay consistent w.r.t spaces vs tabs

### ISSUE THREAD

**Issue by NotTheEconomist** [exercism/exercism#3998]
Currently when writing a comment, inserting a newline on an indented line makes the new line smart indent to the same level. However this indentation is created with tabs regardless of how the previous line was indented.

Without dredging up any holy wars on the subject, some languages are very particular about indentation. Particularly Python I found my code mis-indented because the standard four-space indentation I wrote by hand was followed by 2 two-space-width indents on the following lines:

``````plaintext
```python
def some_function():
    # hand indented by four spaces followed by a carriage return
		# appears visually the same on the Write tab, but is actually 2 two-space-width tabs, which
		# makes the code incorrect (this is a syntax error in Python)
```
``````

The above was pasted directly from a comment section, and visually appears as:

![image](https://user-images.githubusercontent.com/3775259/42911538-44e03d88-8aa0-11e8-8064-0e7bf978f8ff.png)

**Comment by NobbZ** [comment]
This would also brake Haskell code, which uses a layout rule to determine blocks.

Things might get even worse if we ever introduce a `whitespace` track ;)

**Comment by iHiD** [comment]
Is this still relevant since the various changes to the editor over the last few months?

**Comment by iHiD** [comment]
Closed due to lack of response.

**Comment by sshine** [comment]
Since <kbd>Tab</kbd> no longer indents in the editor, I suppose it isn't possible to cause this bug.

Related issues:
- #4144 requests that <kbd>Tab</kbd> should allow indentation again,
- #4534 documents some other UI bugs.
