### ISSUE TITLE
Pre-select existing tracks on mentor configure

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4001]
When changing the tracks I want to mentor at mentor/configure it would helpful if the tracks I've already chosen were pre-selected. Thanks :)

**Comment by NobbZ** [comment]
As far as I understood @kytrinyx a while ago, that page is only temporary, and will eventually be replaced by a proper process (#3836)

**Comment by kytrinyx** [comment]
@NobbZ If we can make this (probably temporary) page remember selections, that would be incredibly helpful in the meanwhile!

**Comment by NobbZ** [comment]
Maybe you are right, but the deselecting them and submit should remove me as a mentor or confusion will be even bigger than it is now.

**Comment by iHiD** [comment]
So the action for whoever does this:
1. Set any existing mentorships as checked when the page loads.
2. Add any newly ticked mentorships on submission
2. Delete any unchecked mentorships on submission

**Comment by strickinato** [comment]
🎉 I got this working and tested 🎉

Even though it's temporary, it should be a nice addition!

**Comment by nicolechalmers** [comment]
Thank you!

**Comment by iHiD** [comment]
Brilliant. You're great! So although it's temporary, we'll definitely keep the general code and move it into another place so it **will** persist :)
