### ISSUE TITLE
Allow mentors to change tracks

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4002]
After changing the tracks I'm mentoring at /mentor/configure, the track I chose not to mentor still shows as a "Track" when "Status" is set to "Requires action from you". I changed /mentor/configure so should be only mentoring Python but the filter still shows Ruby.

<img width="533" alt="screen shot 2018-07-19 at 09 26 44" src="https://user-images.githubusercontent.com/5421823/42930800-e663a5f6-8b35-11e8-85fd-41e05440a485.png">

**Comment by NobbZ** [comment]
As far as I understood @kytrinyx a while ago, you can not use the mentioned page to opt out from a track to mentor.

**Comment by nicolechalmers** [comment]
Thanks for clarifying @NobbZ . I remember this now.

**Comment by iHiD** [comment]
This got fixed.
