### ISSUE TITLE
Change mentor progress to be a rolling week.

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4004]
@iHiD announced the progressbar for mentors the other day, and asked if we would prefer fixed week starting at sunday or monday or a rolling week.

A first feeling of mine was "Who cares?" and I voted for a fixed week starting at monday, since he said, thats what the current implementation is and I did not want to put further burden on him or other developers.

But today I went to my mentors dashboard and have seen, that I have ~30 mentorings of the needed 20.

This has a psychological effect on me: I'm "finished" and can't motivate me much to do further mentoring and I really have to force myself to do something.

Another fear I have, is that next monday this number will tell me that I did nothing. That I'm lazy. That I leave my fellow students alone! I'll cry and scream that all this isn't true and deep dive into mentorings until the bar is at least half full, tuesday and wednesday will be used to fill the other half. But then its full again and I'm back were I am today.

Therefore I want to start a public discussion about what other mentors prefer.

The current options originally given by @iHiD are:

* Fixed week, starting at Sundays
* Fixed week, starting at Mondays
* A rolling week

Also I'd might to ask for a fourth option: Make it configurable individually for each montor. Let him/her choose between a fixed week (and one of the 7 days) and a rolling week.

**Comment by ErikSchierboom** [comment]
I had the exact same feeling. Originally, I thought: "why not just use the work week." However, having giving it some thought after reading you post, I must say I am now firmly into the camp on the rolling update (for all the reasons you already gave). The most important reason to me is that I am also afraid that mentors will think they're "done," and then don't visit the website until the next week.

**Comment by kytrinyx** [comment]
I originally thought a fixed work week was good, but I am now entirely convinced that a rolling week is the way to go. 👍

**Comment by mawis** [comment]
For me both (fixed week and rolling 7 days) would work. I don't feel "done" after 20 exercises. But I think going with the rolling 7 days would help solving the problem that when a week starts is a very cultural thing. I don't think we could ever agree on a common week day to be the correct one.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
