### ISSUE TITLE
Everything after <- not being rendered

### ISSUE THREAD

**Issue by SinRas** [exercism/exercism#4011]
__Here is the code that was written in the code block:__
```
difference_of_squares <- function( natural_number ){
  square_of_sum = sum( 1:natural_number )**2
  sum_of_squares = sum( (1:natural_number)**2 )
 return( square_of_sum - sum_of_squares )
}
```
---
__How it was rendered in comments:__
![image](https://user-images.githubusercontent.com/18718139/42962025-df996204-8ba5-11e8-88c7-3482d3ae848e.png)

**Comment by NotTheEconomist** [comment]
Is it being rendered as an (improper) HTML comment? `<!-- some comment goes in here -->` is pretty close to `<- some text`. I wonder if the lexer is behaving badly?

**Comment by KittenHero** [comment]
duplicate of  #3970

**Comment by iHiD** [comment]
Can this be closed?

**Comment by SinRas** [comment]
@iHiD yep it's solved. thanks for heads up.
