### ISSUE TITLE
Remove "medium" time tag

### ISSUE THREAD

**Issue by hilary** [exercism/exercism#4014]
See screenshot...

Even when we're computing time to complete, using the same term for both is likely to lead to confusion.

![screen shot 2018-07-19 at 2 52 05 pm](https://user-images.githubusercontent.com/809393/42973212-324a9e3a-8b67-11e8-9b1d-1c497c8354c9.png)

**Comment by c-dante** [comment]
What, you don't like your 🍳 medium | easy?

Something as simple as a clock icon next to one might clear that up :)

**Comment by hilary** [comment]
Come to think of it, I'm not wild about difficulty: Easy, Medium and Hard, either. It feels less than motivating to me. I would prefer something that felt more about the problem and less about the learner. Complexity: Simple, Average and Complex feels more neutral to me.

**Comment by iHiD** [comment]
Let's remove the "time" label for now.

**Comment by PatrickMcSweeny** [comment]
It appears that this issue was resolved by [this commit](https://github.com/exercism/website/commit/e9500bc485d17feb778b5e4c4eb3b04b0db0d9b3) and she be closed.
