### ISSUE TITLE
Consider giving visual indicated of completion for unlocked extra exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4017]
Your personal track page now shows underneath each core exercise the extra exercises it unlocks. These extra exercises are displayed through icons. It might be useful if there was some way in which one could see if you've already completed the extra unlocked exercise.

**Comment by iHiD** [comment]
We have debated this one a *lot* internally. The key to the debate is that we want people to feel a sense of calm and completion as they progress through the core exercises. There is concern that having 100 exercises in various states will totally eradicate that. On the other hand, we also really like the idea of giving that information on progression inline. Now the basic version is up, I think we'll leave it for a couple of weeks then reevaluate this once the waters have calmed.

Thanks for bringing it up, it's good to have public visibility on it, and I'm welcome to hearing people's thoughts on the topic :)

**Comment by ErikSchierboom** [comment]
I understand what kept you from implementing it. Good to hear it has been given serious thought. Another, less intrusive option, is to add the status as part of the tooltip when hovering: see #4016.

**Comment by iHiD** [comment]
That's a really nice idea, @ErikSchierboom .

**Comment by yyyc514** [comment]
+1.  I constantly wish for this.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
