### ISSUE TITLE
Update Copy & Links on Mentor Landing Page

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4033]
The copy and links on this page need updating.

<img width="728" alt="screen shot 2018-07-22 at 00 24 17" src="https://user-images.githubusercontent.com/5421823/43046122-1e8fc306-8dc5-11e8-89f4-f7dc0dddf879.png">

<img width="922" alt="screen shot 2018-07-22 at 00 24 14" src="https://user-images.githubusercontent.com/5421823/43046120-1d37569a-8dc5-11e8-873e-81f3f8b9e812.png">

**Comment by iHiD** [comment]
This was done.
