### ISSUE TITLE
How to publish hidden solution?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4047]
@enaheld commented on [Mon Jul 23 2018](https://github.com/exercism/discussions/issues/231)

Apologies if I'm asking this question in the wrong place.
When I submit a solution and then go to the "community solutions" page for that exercise, my solution is market "hidden" with a box that says "Publish your solution to see others' reaction." When I click "publish your solution..." bar, my solution displays but it doesn't publish. I've searched for instructions on how to publish solutions but I can't find anything. Could someone let me know how to do it? Thanks

**Comment by rpottsoh** [comment]
This is really @enaheld's issue.  I've just moved it here for them.

**Comment by zancas** [comment]
I have the same issue.

**Comment by rpottsoh** [comment]
@iHiD or @kytrinyx

**Comment by jabbalaci** [comment]
Same issue here. What's the solution?

**Comment by jabbalaci** [comment]
@enaheld : Right, it did the trick. Thanks.

**Comment by whatevergeek** [comment]
this seems to be a disadvantage in the mentored track.
how to convert the current one to an independent track?

**Comment by iHiD** [comment]
@jabbalaci @zancas @enaheld Is this still an issue?

**Comment by enaheld** [comment]
Not for me

**Comment by zancas** [comment]
Not for me.

**Comment by kytrinyx** [comment]
Thanks everyone; closing!
