### ISSUE TITLE
🆘 Access Denied

### ISSUE THREAD

**Issue by richardworking** [exercism/exercism#4054]
trying to upgrade exercism on Windows 10, and getting and Access Denied. Chocolatey is up to date with the latest version, so I am not sure what is happening here.

**Comment by NobbZ** [comment]
What have you done to get accees denied? `choco upgrade`? If so, did you try it in a regular or elevated terminal? Please try again using the latter if you haven't already.

**Comment by richardworking** [comment]
thanks - I was using a regular terminal. I will use an elevated terminal. extreme rookie, so I first need to find out what an elevated terminal is, but will update once I do.

**Comment by NobbZ** [comment]
Elevated/privileged/administrator. Just right click on your windows button, there should be 2 options for a terminal, choose that with administrator or similar in its name.

**Comment by iHiD** [comment]
Can this be closed?

**Comment by richardworking** [comment]
HI Jeremy - yes. I have been inactive for a little while.


apologies - do you need me to close it?

________________________________

**Comment by iHiD** [comment]
No probs. I can do it. Thanks :)
