### ISSUE TITLE
Use Haskell syntax highlighting from Prism for PureScript Track

### ISSUE THREAD

**Issue by spicydonuts** [exercism/exercism#4063]
The PureScript track solutions have no syntax highlighting and the "Test Suite" tab is empty.

**Comment by mawis** [comment]
Prism has no syntax highlighting for PureScript, but the Haskell formatter should work okay for PureScript code. We already map `purescript` as a language to `haskell`.

So I think a mapping from the `purs` file extension to `haskell` should be added, the same way as Idris is configured to use the Haskell syntax highlighting.

**Comment by mawis** [comment]
For me the “Test Suite” tab isn't empty (anymore?).

**Comment by kytrinyx** [comment]
I'm not sure if @iHiD or @kntsoriano is the best person for this one. (TL;DR: we can map PureScript to Haskell in the Prism syntax highlighting)

**Comment by iHiD** [comment]
@spicydonuts @mawis If you PR `purs` to https://github.com/exercism/website/blob/master/config/initializers/prism.rb#L227, I'll merge it :)

**Comment by mawis** [comment]
@iHiD PR submitted :)

**Comment by iHiD** [comment]
Thanks! Assigned to @kntsoriano :)
