### ISSUE TITLE
Absolute path of file from computer shown in solution

### ISSUE THREAD

**Issue by mienaikage** [exercism/exercism#4066]
I downloaded the exercise `leap` which I had done previously, which resulted in the files being downloaded to a `leap-2` directory. Multiple files were submitted, and now on the site it shows the absolute path of those files from my computer.

https://exercism.io/solutions/c7569cfd9d7b43d2ab61da19b550e12d

**Comment by iHiD** [comment]
@kytrinyx This might be CLI doing things differently with multiple files, or a bug in the API in the way we're handling them. If you have any insight, let me know, otherwise I'll dig into the API side later :)

**Comment by kytrinyx** [comment]
I am aware of the problem and mapped out a plan to fix it. Thank you!

**Comment by iHiD** [comment]
Great. Thanks. I'll leave it to you then :)

**Comment by iHiD** [comment]
@kytrinyx Once this is triaged to CLI repo could you add the label `status/triaged-to-repo` on this pls and link the issue there. Thank you <3

**Comment by kytrinyx** [comment]
triaged to https://github.com/exercism/cli/issues/699

**Comment by kytrinyx** [comment]
I've submitted a pull request to clean up these paths on download.
