### ISSUE TITLE
cli: sometimes solution downloads into alternative locations

### ISSUE THREAD

**Issue by hilary** [exercism/exercism#4072]
# Summary

When downloading a solution (say, for exercise `foo`) using

```
exercism download --uuid=<SHA>
```

the files download to `~/Exercism/users/<username>/<track>/foo/`. The contents of that directory are usually

```
README.md
cases_test.<ext>
foo.<ext>
foo_test.<ext>
```

However, on occasion, the contents of the directory are different. I've seen two variations so far.

This issue is baffling the first time a mentor encounters it, as it causes the solution to fail the tests. The mentor has to figure out that the solution shown on the website is not the solution that the tests are running against. 

The issue also adds one more step to mentoring, as I now list the contents of the directory after each download to guard against the issue. I can't just do it reflexively, either, as I missed variation 2 that way until it failed the tests.

## Variation 1

```
README.md
cases_test.<ext>
foo.<ext>
\\foo.<ext>
foo_test.<ext>
```

In this variation, `foo.<ext>` may be empty or, for exercises with a stub file, it may contain the stub. (I haven't tracked whether the behavior is consistent w/re stub files or not). Regardless of the content of `foo.<ext>`, the actual solution is in `\\foo.<ext>`. [Here's](https://exercism.io/mentor/solutions/aa9fe553b4194201a6f949b833f8ee06) one solution I encountered variation 1 on.

Other moderators from multiple tracks have also reported seeing variation 1 on slack.

## Variation 2

```
README.md
cases_test.<ext>
foo_test.<ext>
src/
src/foo/
src/foo/foo.<ext>
```

I encountered variation 2 for the first time on July 25th (PDT), which is when I decided to file this issue. I encountered variation 2 when downloading [this solution](https://exercism.io/mentor/solutions/43bc7c210ed74c80acde32ffbd0dcc8e).

**Comment by Cohen-Carlisle** [comment]
I've experienced variation 1 a few times in the elixir track.

**Comment by nickborromeo** [comment]
👋 they there! just looking over the issue, and was wondering if this should be moved over to `exercism/cli` based on

> The Command-Line Client (CLI) For problems with the Command-Line Client (CLI), open an issue in exercism/cli.

**Comment by iHiD** [comment]
This exists at https://github.com/exercism/exercism.io/issues/3870

I know @hilary checked this repo for issues and wouldn't have spent her time documenting if she'd found it. I wonder if leaving it open, adding a "triaged" label and adding a note of where it is on CLI would be a good strategy, to help discoverability of issues.

@kytrinyx @nickborromeo @hilary Thoughts?

**Comment by kytrinyx** [comment]
Yeah, anything we can do to help discovery!

We have two problems related to paths. One shows up as `\\` in the downloaded paths and filenames, and the other is that I had some experimental behavior that would create a new directory with a numeric suffix if an exercise directory already exists, and it's not properly supported.

I am working on fixes to:

- ensure that the CLI handles those situations correctly
- ensure that the CLI handles the bad data from previous submissions correctly
- clean up all the bad data in the database
- an `exercism doctor` command that will do the cleanup on the filesystem locally

**Comment by kytrinyx** [comment]
For reference:
- https://github.com/exercism/cli/issues/665 for stray `\\` in filenames 
- https://github.com/exercism/cli/issues/661 for downloads that go to the wrong place (exercise directory with numeric suffix)

**Comment by Stargator** [comment]
@kytrinyx For the `exercism doctor` command to work in my case, it would not only have to correct `\\folder-name\\filename.ext`, but the contents of `filename.ext` are not the same as what is shown on the website. it looks like the first two lines or so.

See: #4101 for details. I looked, but didn't catch these other reports.

**Comment by kytrinyx** [comment]
@Stargator thanks, I wasn't aware of that. In that case I think the download command is choking in some way.

**Comment by hilary** [comment]
@kytrinyx Just to make your life more interesting, I mentored an exercise today in which the files that showed in the GUI had the `//<filename` versions. 😭 

I was scrambling to catch up and do my mentoring part, so I'm afraid I didn't nab the solution uuid.

**Comment by kytrinyx** [comment]
_No no no no nooooo!!11!!_

Well. Ok :)
I'll find it (can do a lookup in the database for it).

**Comment by kytrinyx** [comment]
I've submitted a pull request to clean up these paths on download.
