### ISSUE TITLE
'Community solutions' pages show all solutions as published 13 days ago

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism#4073]
On the community solutions pages for multiple exercises across multiple tracks, every single published solution reads that they were published 13 days ago, with the notable exception being my own published solution.
![screenshot from 2018-07-25 22-47-17](https://user-images.githubusercontent.com/1254212/43238639-fdf06cdc-905c-11e8-8fd5-af1fcf99c4be.png)

**Comment by nickborromeo** [comment]
I am not 100% sure about this but it looks like this is the result of the launch of V2 of the site. I also have the same behavior.

![exercism](https://user-images.githubusercontent.com/1518902/43244393-503ea2c2-905f-11e8-9917-d84b02a61685.png)


I for sure did not publish the `hello-world` exercise 13 days ago. 😄 

I looked at the [code](https://github.com/exercism/website/blob/6b2665d35a4f1705c77c91ba3bbc07567f910ada/app/views/solutions/_solution.html.haml#L2-L5) and it looks right. It takes the `published_at` column of the solution and displays that on the page. 

This must be a data backfill to the new database and all the completed solutions have the same `published_at` date.

**Comment by NobbZ** [comment]
Well, it is "published at", not "submitted at". Before the launch there was no distinction, today it is.

I assume that the published at us therefore the launch date, as pre launch you couldn't have had published something

**Comment by iHiD** [comment]
@nickborromeo and @NobbZ are correct. We generally set timestamps to be a fixed migration time for any new fields. It might be that we backfill the published at to the last submission date, as I hadn't considered that that field is exposed in the UI.

**Comment by PatrickMcSweeny** [comment]
This appears to be fixed now.

https://exercism.io/tracks/ruby/exercises/grains/solutions
