### ISSUE TITLE
Should the site allow some considerations to help maintainers?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4079]
@kytrinyx has asked that I open this issue here in order to share some comments that took place in exercism/interactive-cli-walkthrough#47.  The pertinent comments follow:

#### July 19th, 2018 @rpottsoh said:
As a maintainer it would be nice to be able to see the site from time to time as a new student sees it; to make sure changes to documentation or links appear and work correctly. This is a feature of v1 that I am missing.

#### July 20th, 2018 @iHiD said:
Can you expand on where that's not the case please?

#### July 20th, 2018 @rpottsoh said:
I don't see how I can visit the Delphi track page and see it just as someone would just starting an exercise, clicking it for the first time after it was unlocked.

For example, I only see a way to get here, https://exercism.io/tracks/delphi/installation, because pangram is now unlocked for me and the intro page for the exercise is still available to me since I have not yet submitted a solution. Once I submit a solution a lot of this information is hidden away.

I believe there is an issue related to this somewhere, I don't know where though. Under v1 all of the documentation that a track had available was always easy to find. At the moment the stricter feeling of the v2 structure only allows me to see what someone thinks I only need to see. This is too restrictive. We need to be able climb to a higher altitude from time to time to see other aspects that previous choices have locked us out of. Does that make sense?

#### July 20th, 2018 @iHiD said:
That makes sense. We'll look into it. My suggestion in the interim would be
to sign up as a new user and explore that way.

#### July 20th, 2018 @rpottsoh said:
The thought had crossed my mind, but creating dummy users while effective is kludgy.

💡 if using dummy users is an easier way to handle this wouldn't it be nice to, perhaps, omit these dummy users from statistical information? Perhaps if there was some way to tag a maintainers' dummy doppelganger so that it would be "ignored" essentially..... I wouldn't want excessive use of a dummy account to influence the numbers...

**Comment by rpottsoh** [comment]
@kytrinyx felt this was an interesting discussion and thought other maintainers might be interested in this topic.

**Comment by Insti** [comment]
> creating dummy users while effective is kludgy.

I've also created a dummy user to view the site as a user.
I doubt the number of dummy users will be statistically significant.

**Comment by Stargator** [comment]
> I doubt the number of dummy users will be statistically significant. If all the maintainers had to do it, not just once, but many times in order to go back and "start fresh' again. Those numbers could increase steadily over the years.

Plus, who wants to keep track of dummy accounts?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
