### ISSUE TITLE
Add private mentor notes.

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4083]
The first thing I do when I come across a solution I've not mentored before is solve it myself. Because of the way tracks are set up now, I sometimes just knock together a solution in my text editor. For example, I just mentored Ruby#pangram, and so I wrote this:
```
def pangram?(sentence)
  sentence.downcase.scan(/[a-z]/).uniq.size == 26
end

p pangram?('abcdefghijklmnopqrstuvwxyz')
p pangram?('a quick movement of the enemy will jeopardize five gunboats')
p pangram?('7h3 qu1ck brown fox jumps ov3r 7h3 lazy dog')
p pangram?('the quick brown fox jumps over the lazy dog')
```

In doing this I had some thoughts and refactorings, as well as the eventual code. I'd like to be able to record those thoughts (and for a simple exercise like this, the code) by an exercise, then consider them next time I mentor the same exercise. This would allow me to build a volume of notes for an exercise, which makes it quicker for me to work with.

I therefore think that as part of the new mentor-tools modal we're making, we should allow a text box that a mentor can just write their own personal notes in, that are linked to the track/exercise in question.

FYI, we're already adding other things to the mentor tools modal such as a link to your published solution, a link to other mentors' solutions, etc.

Thoughts from mentors welcome.

**Comment by F3PiX** [comment]
I think it would be awesome, but... currently I am recording those kind of thoughts and notes elsewhere, and I have a lot of extra functionality (search FTW)  to make that super useful. 
So, I'd think a very basic feature will come in handy for cases like yours, where you don't want to repeat the same steps for every mentoring on the same exercise. 
For people like me, who are recording more, I don't think it's worth (or doable for that matter) to achieve the same level of usefullness  as a dedicated note app. However, I think I would use that notepad too, but for things regarding a specific solution or student, that doesn't need to be persistent.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
