### ISSUE TITLE
Define a public API

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4087]
Lets define a public API which we can use to write our own clients.

An API which makes us as students and mentors able to not leave our editor of choice.

Given an appropriately defined API a student were able to see comments of a mentor directly in his editor, could reply to them and submit a new solution in a single go.

Mentors could see their queue and directly download solutions, test them, etc, possibilities are plenty…

**Comment by iHiD** [comment]
@NobbZ Very keen to do this. The current API is effectively public but undocumented. Once it's stable with the CLI, we'll document it and then can take feature requests for individual features. I'll mark this as a discussion and you and others can suggest functionality you'd like to be able to access here.

**Comment by iHiD** [comment]
Relevant: https://twitter.com/andrewradev/status/1023151506604867585

**Comment by NobbZ** [comment]
I'll quote myself from the slack here, as not everyone can join that discussion and this is not only relevant for mentors, but maintainers or students as well:

> I've heard about that vim-wrapper, but thats not what I am talking about. That plugin does not offer any more as the CLI does. What I was thinking about was **full** exercism integration into an editor through publishing and opening the API specs. Such that (given I've driven my plugin thus far) I could replace the page by my editor.

**Comment by NobbZ** [comment]
I never understood it like that, but comparing to this plugin helped me to better describe what this suggestion is about.

**Comment by ErikSchierboom** [comment]
This would be great to help with creating automated tools involving exercism (e.g. for downloading tests and running them).

**Comment by hoovercj** [comment]
I'm very interested in this. I'm quite keen to solve exercises and mentor students without leaving VS Code

**Comment by iHiD** [comment]
Could you all make a list of the functionality you need pls?

The obvious ones for me are:

- Download solution
- Submit solution

Both of which are in the API, just not documented. If you can give me a list of the functionality you need I will start thinking it through.

**Comment by hoovercj** [comment]
This will be my "living list" as I think of things. I almost made an extension back when nextercism was first announced to wrap the CLI but other projects got in the way and I've forgotten what I had planned :-)

But as far as things I'd like outside of the CLI:

* Iterations
    * Utilize editor diff views to diff iterations (both for mentors and students)
    * This might be the most important
* Solution Comments
    * Take feedback into account in the editor / see students explanation in the editor
    * Allow posting comments
* Mentor Queue Information
    * View queue
    * View solutions per exercise (as available in the site now)
    * Allow approving, commenting, etc. (least important request)


My naive thought is that it would be great to be able to get the files in the body of responses and not in files. For example, if I want to get the different iterations of the solution for a single file, I just want the text contents to pass to the editor, I don't want a zip file that I have to process. At least for the early solutions this should be sufficient.

**Comment by xiegeo** [comment]
Here is my list for what I could use an API for:

- Build missing features. Such as suggesting a random task from unlocked tasks. If I want a feature that's not provided by the website or CLI, I could build my own to an API. If the feature is really useful, it can be included by the official tools.

- Integrate with other services. For example, I can show my latest accomplishments in exercism on my personal website.

- Data analyze. Download and analyze different solutions to the same tasks. For example, find fastest, shortest, or classify solutions by technic. Make it easier to find unique and interesting solutions.

**Comment by bencoman** [comment]
@iHiD, Pharo is derived from Smalltalk, and similarly doesn't work with code stored in files but stored in-Image instead.  So we're forging ahead with our IDE interface to Exercism.  From examining ```exercism --verbose``` we already have exercise downloading working(exercism/pharo#32), and submitting seems feasible(exercism/pharo#96).  The next most useful function is retrieving a list of exercises available to download, for presenting in a menu. (I read somewhere to old CLI had this.)  We would make use of this as soon as it is available.  

The workaround I was thinking of was sucking the full exercise list out of the github repo, 
or just hardcoding the list in our tool, but it will be awkward filtering on student progress without the knowledge maintained on Exercism server.

**Comment by macta** [comment]
@bencomam the list of exercises can come from the config.json which is in the repo - better if the api exposed that, but a workaround is to use that file.

**Comment by sshine** [comment]
@iHiD wrote:
> Could you all make a list of the functionality you need pls?
> The obvious ones for me are:
> - Download solution
> - Submit solution

As a mentor I'd like `exercism comment [--approve] feedback.txt`, since what I'm doing right now is give feedback and then copy-paste it into a text file in their directory, so that I can search for feedback I've already given and copy-paste when applicable. With an `exercism comment` function I could do it the other way around.

(I'd like queue control as a command-line feature as suggested by @NobbZ in the issue description, but not as urgently as `exercism comment [--approve] feedback.txt`.)

**Comment by sshine** [comment]
Add public API functions for inspecting the progress of language track queues (suggested in #4167):

> I would very much like statistics on how a track is progressing.
>
> I imagine a bar chart across time that contains:
>
> - How many (non-)Core exercises are in the queue
> - How many new (non-)Core exercises were put in the queue for each day in the last month.
> - How many (non-)Core exercises were popped from the queue (across all mentors).
> 
> [...] Perhaps if these statistics could be prioritised as an API feature, we can leave initial statistics renderings as user tools, since the bar for adding command-line tools to a language track is lower than adding production-value pages to the website.

**Comment by samWson** [comment]
You might be interested in this. For the [exercism/pharo](https://github.com/exercism/pharo) language track we have been making our own client using the API so to speak. 

Smalltalk, and by extension Pharo, lives inside its own development environment where you are always dealing with objects instead of files. Trying to integrate this with the exercism command line tool caused us problems, so we instead fetch and submit exercises directly using HTTP requests to `api.exercism.io`.

We only just recently got this working. At the moment all it can do is fetch and submit exercises.

**Comment by bencoman** [comment]
And for concrete sample code, we have [ExercismCommand](https://github.com/exercism/pharo/blob/master/dev/src/ExercismTools/ExercismCommand.class.st) with subclasses... 
- [ExercismDownload](https://github.com/exercism/pharo/blob/master/dev/src/ExercismTools/ExercismDownload.class.st) 
- [ExercismSubmit](https://github.com/exercism/pharo/blob/master/dev/src/ExercismTools/ExercismSubmit.class.st) 

and tests...
- [ExercismDownloadtest](https://github.com/exercism/pharo/blob/master/dev/src/ExercismTools/ExercismDownloadTest.class.st)
- [ExercismSubmitTest](https://github.com/exercism/pharo/blob/master/dev/src/ExercismTools/ExercismSubmitTest.class.st)

**Comment by NobbZ** [comment]
Please remember that this was not asked, only to be able to download and submit, this was also asked to be able to operate the full site without leaving my editor of choice.

* Browsing my tracks as a student
* Choose/Update exercises
* Submit solutions
* Read and answer a mentors feedback
* Browse exercises that needs mentoring as a mentor
* give feedback as a mentor
* Basically: make me able to drop the webbrowser

**Comment by uzilan** [comment]
It would also be nice if I could draw statistics about my own progress - which tracks I've joined, how many exercises I've done and how many are waiting etc - would be awesome to be able to show that as charts (for example in my github exercism solutions repo)

**Comment by diabolicle** [comment]
I would like the ability to easily retrieve track and exercise icons from the API.

**Comment by iHiD** [comment]
@diabolicle For what purpose?

**Comment by diabolicle** [comment]
@iHiD I found out you can get the images from assets.exercism.io so please disregard my previous comment. I just started hacking together a client for vscode and thought it would be neat to include the images.

**Comment by IsaacG** [comment]
I'd really enjoy an API endpoint which allows me to check for new notifications.

**Comment by LeaveNhA** [comment]
I've made something but I don't know it's still relevant.

https://github.com/LeaveNhA/exercism-layer

**Comment by NobbZ** [comment]
I wasn't able to find any meaningfull code in that repository that actually calls out to the `exercism` tool or API.

Also most of the output on the GIFs does look like the old output from the v2.x CLI.

Also the age of the last commit (2 years) makes me think, that the repository is meant to work with an old version of exercism that simply does not work today anymore.

Neither does the old CLI work with the current website, nor were the commands compatible with the new CLI, as there is no `fetch` anymore and they way downloading works in general has been redesigned.

**Comment by LeaveNhA** [comment]
That's why I wrote it.
I wanted to give something back to `community`.
If you all aim something like this, I can help you guys.

**Comment by ronCYA** [comment]
I understand the API isn't documented but is effectively public. Is there a basic list of current endpoints/methods/etc we can experiment in the dark with?

**Comment by iHiD** [comment]
@ronCYA The API does what the CLI does. What are you looking to do with it?

**Comment by ronCYA** [comment]
@iHiD Oh sorry I didn't know. I've taken a look at the commands in exercism/cli/ now and see I misunderstood what kind of API this is. I wondered if there'd be dummy/test data or an API that would let me pull down published solutions and comments without needing to scrape them.

I'm fascinated with the automated analyser work being done and wanted to research the feasibility/effectiveness of some ideas I had. Mainly, AST-diffing _between_ existing solutions (as opposed to the solution being analysed) and natural language understanding on existing mentor comments.

The intent would be to categorise solution approaches and predict comments so mentors could spend more time on the human aspects of mentoring. Sky-pie stuff but worth toying with!

**Comment by iHiD** [comment]
> The intent would be to suggest comments for mentors to make, so they could spend more time on the human aspects of mentoring.

We already do this via the analyzers :) What language(s) are you interested in?

Here's an example from JavaScript:

<img width="521" alt="Screenshot 2019-09-24 at 13 17 35" src="https://user-images.githubusercontent.com/286476/65764286-299d8100-e11d-11e9-8b57-9b3707938805.png">

>  I wondered if there'd be dummy/test data or an API that would let me pull down published solutions and comments without needing to scrape them.

If you'd like some data to work with, you can reach out to me on our Slack and I can send you something. You can also chat to others working on things there too. Are you a mentor currently?

**Comment by casca** [comment]
Is there a public endpoint to get the number of solutions published by a specific user?

I wanted a badge for my exercises repo so I wrote a [small scraper](https://github.com/casca/exercism-stats-scraper) but I'd like to use a cleaner solution.

**Comment by iHiD** [comment]
Nope. There probably will be in v3 (coming later in the year). We also have plans to add badges etc too. Nice work on the scraper :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by ModProg** [comment]
This is still relevant because there still is no public API documentation

**Comment by DeepSpace2** [comment]
Any news on this?

Attempting to implement https://github.com/exercism/cli/issues/1042 (although in a slightly different approach) I got as far as making a request to `https://exercism.org/api/v2/tracks/${track}/exercises` however the objects returned by that API do not have status info (available/in-progress), only a "locked" boolean.  I tried to use a `?status=available` query params but it did nothing (I still got all of the exercises).

**Comment by IsaacG** [comment]
> Any news on this?
> 
> Attempting to implement [exercism/cli#1042](https://github.com/exercism/cli/issues/1042) (although in a slightly different approach) I got as far as making a request to `https://exercism.org/api/v2/tracks/${track}/exercises` however the objects returned by that API do not have status info (available/in-progress), only a "locked" boolean. I tried to use a `?status=available` query params but it did nothing (I still got all of the exercises).

I believe there is no plan at this time to work on documenting the API. Your best bet is to use the Chrome Network Inspector and see how the site sends requests.
