### ISSUE TITLE
Can't submit an exercise 

### ISSUE THREAD

**Issue by neetimsina** [exercism/exercism#4088]
Whenever I try to submit an exercise, the command-line doesn't respond
![screenshot from 2018-07-29 12-17-33](https://user-images.githubusercontent.com/41776813/43363646-70a7ad98-9329-11e8-9098-d31f30d72629.png)

**Comment by NobbZ** [comment]
What operating system are you using? What shell? How long have you tried to wait? Why are you trying to submit a test? Does this also happen when you try to submit from your exerercism workspace?

**Comment by neetimsina** [comment]
I use linux, waited for about 10 minutes. The computer got heated up and exercism alone used all 100% of my CPU power. ![screenshot from 2018-07-31 01-37-29](https://user-images.githubusercontent.com/41776813/43420333-1298d638-9463-11e8-98a1-46903aaa7155.png)

**Comment by NobbZ** [comment]
Can you please answer the last bit of my question, does this also happen if you submit your solution from a proper place?

Under the assumptions this is `hello-world` of the `python` track, you should move your solution to `$(exercism workspace)/python/hello-world` first and try submitting from there.

Could you also please tell the version of the CLI? `exercism version`.

**Comment by iHiD** [comment]
Can this be closed?
