### ISSUE TITLE
Number of solutions per week alignment off when displaying three digits

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4091]
See:

![image](https://user-images.githubusercontent.com/135246/43369987-8215e420-9377-11e8-822b-b8c5e4f21106.png)

**Comment by iHiD** [comment]
This issue is basically you just showing off, isn't it! ;)

**Comment by kytrinyx** [comment]
I laughed out loud. Thank you @ErikSchierboom !!

**Comment by sshine** [comment]
Ha ha. I'm closing this one.
