### ISSUE TITLE
How should we evolve Exercism Teams?

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4093]
We've kept Teams simple to start with but we'd like to understand more about how you'd like to use it so we can make it even better.

When we launch Teams, you'll be able to:
- create new teams and invite new members
- see who in your team has accepted invites
- choose any track and exercise to work through with your team(s)
- give feedback on your team mates' solutions 
- receive notifications when your team mates leave feedback

**What else would make the team process more fun / easier / even more collaborative? Please add your comments below.**

Thanks :)

**Comment by devillexio** [comment]
We use exercism.io at work for a _weekly coding challenge_, where we pick an exercise, work on it for a week and then present our solution to the team during the next meeting. We have a few folks doing the NodeJS track, as well as individuals doing Go, Rust, and Closure.

What would be great if you show a list of exercises that everyone is still busy with, or have access to. It's quite difficult to pick the next exercise when you don't know which of the exercises are available on the tracks the team are busy with.

**Comment by rodeoclown** [comment]
- I'd love to be able to filter out other team members' exercises I've already looked at and/or given feedback to.
- A button to clear all notifications would be nice too. Sometimes the number of unviewed exercises could get quite large, and the only way to reduce that number was to individually click through to each.

**Comment by strickinato** [comment]
I thought this was an interesting idea: https://github.com/exercism/exercism.io/issues/3979

**Comment by guygastineau** [comment]
@strikinato thanks.

After thinking more on this I think it is easy enough to mentor everyone on a team without having the mentor features programmed into teams.

In a big company I guess it would be neat if they could set up a small team of internal mentors to get everyone's code up to par on some sort of joint learning endeavor.

**Comment by nicolechalmers** [comment]
Thank you all for your feedback on how we evolve the Teams site.
I will come back to this conversation when we're ready to apply product work area.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
