### ISSUE TITLE
Only able to submit imported exercises for mentoring one at a time....

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4094]
I apologize if this issue is redundant; please direct me to the appropriate issue if this is the case....

@iHiD 
I completed all the exercises of a track prior to the move to v2 from v1.  Why can I only submit my submissions for mentoring one at a time and not all at once.  This affects the core as well as non-core exercises, effectively nullifying the difference between the two types.  Once I submit one of the completed, imported, exercises for mentoring, all of the other imported exercises have this message displayed across the top of the site page of that exercise:
`This solution has been imported from an old version of the website. Once your other solutions on this track have been mentored you may request mentoring for this.`

Is this a bug?  I am looking to understand why I can only submit my exercises for mentoring one at a time and only after a mentor has approved the one and only exercise I am allowed to submit.  It is going to take forever (a long time) to get through this.

**Comment by NobbZ** [comment]
Nope, this is the result of #3866.

As those who sent plenty, if not all solutions to the mentors at once, usually did pretty much the same mistakes in all submissions. Also as a mentor it is annoying to see ~25 submissions which are all of the same student, especially before we were able to filter this was a major annoyance.

**Comment by NobbZ** [comment]
You could also ask @kytrinyx and @iHiD if they will instapublish your submissions as both of you probably agreed upon the fact that you do “good” work.

What you want to do is far from beeing an every day task, its a one time thing to give the track a headstart.

**Comment by rpottsoh** [comment]
A @NobbZ'ism, `instapublish` :+1:   I like it.

@iHiD or @kytrinyx what do you think?  This is not high priority but would be helpful, unless you have an alternative course of action to suggest.
