### ISSUE TITLE
Unable to complete exercise in Independent mode

### ISSUE THREAD

**Issue by ZapAnton** [exercism/exercism#4099]
When I tried to submit `Wordy` exercise to the Rust track, I could not complete it on the website, since there was no "Complete Exercise" button. Instead only the following message is printed:

```text
This solution has been imported from independent mode.
Mentoring will become available when your other solutions have been mentored.
```

Which is strange, because the same day I could complete several exercises this way.

I also tried submitting the exercise several times, and there were no iterations displayed on the website.

CLI version 3.0.4

Exercise uuid: d3bb8c4724c64976be2622cb7b24eea9

**Comment by iHiD** [comment]
Thanks for reporting. This is a result of a change I deployed recently. It'll be back in the next hour or two. Sorry for the frustration.

**Comment by Insti** [comment]
I get the same message viewing already submitted (legacy) exercises and am unable to see pre-existing comments on them. I assume this is related.
