### ISSUE TITLE
mentor: Solution received from CLI not the same as on website

### ISSUE THREAD

**Issue by Stargator** [exercism/exercism#4101]
I literally just reviewed my first solution and approved it. Then proceeded to the next student in the queue.

The solution I needed to get was via `exercism download --uuid=b6b406adae2b47eaa7faee9b3a702db3`

But when I pulled down the solution, I did not find a complete copy of the solution as shown on the website.

* Instead, I got a oddly named file `\\lib\\leap.dart` which should have been the folder `lib` containing the file `leap.dart`
* And the copy of the solution wasn't complete, it was just the first two lines it seems.

### The solution **as shown** on the website:
<img width="596" alt="screen shot 2018-07-31 at 3 29 18 pm" src="https://user-images.githubusercontent.com/7527155/43482695-64ce1b60-94d7-11e8-8b8f-4012b761dfad.png">

### Where the solution **should** be found, but isn't:
<img width="730" alt="screen shot 2018-07-31 at 3 29 33 pm" src="https://user-images.githubusercontent.com/7527155/43482696-64e1f4f0-94d7-11e8-9789-759014bb4b2f.png">

### Where **part** of the solution is:
<img width="712" alt="screen shot 2018-07-31 at 3 29 39 pm" src="https://user-images.githubusercontent.com/7527155/43482697-64f4dd68-94d7-11e8-8ba1-bb3b8142cd72.png">

**Comment by iHiD** [comment]
Thanks for the detailed report. I think this is probably the same as https://github.com/exercism/cli/issues/665 but I'll wait for @kytrinyx to come back from her break and tell us :)

**Comment by Stargator** [comment]
@iHiD I'm on a MacOS, just FYI. I also downloaded 3 more solutions with no problems.

**Comment by kytrinyx** [comment]
I've submitted a pull request to clean up these paths on download.
