### ISSUE TITLE
Fix getting started instructions everywhere

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4102]
We recently launched the v2 site, and a lot of the instructions for individual tracks are still explaining how to get started in the v1 site--so now they're wrong in lots of places.

e.g. C++ Hello World says:
> Getting Started
> Make sure you have read the C++ page on exercism.io. This covers the basic information on setting up the development environment expected by the exercises.

This is wrong and should say something like: 
> To get started, make sure you have C++ installed (Instructions here) and the Exercism CLI installed (Walkthrough here)

@jackhughesweb I'd like you to take a look at this. A lot of the information you need is in @kytrinyx's head. She's off for a couple of days but I'll ask her to give you an outline of how this all works when she's back, so hold of until then :)

**Comment by iHiD** [comment]
My temporary fix for this is https://github.com/exercism/exercism.io/issues/4108 btw.

**Comment by kytrinyx** [comment]
I'm back! Let's catch up in Slack tomorrow (your afternoon / my morning) and we can hash out the details and document them here.

**Comment by kytrinyx** [comment]
While this is probably wrong for a lot of different tracks, here's the basic setup for C++, which will be similar for the other languages.

The C++ exercise readmes are generated from this Go template: https://github.com/exercism/cpp/blob/master/config/exercise_readme.go.tmpl

They're generated using the Configlet tool:
https://github.com/exercism/configlet/releases/latest

The documentation for the README generation is here:
https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md#generating-a-readme

**Comment by kytrinyx** [comment]
Suggested approach (from discussion in Slack) would be:

- fix it for C++
- write up a meta issue that explains clearly what is wrong
- submit a sub-issue to each language track pointing to the meta issue, asking to make sure this is fixed for that track

**Comment by rpottsoh** [comment]
#4076 seems related to this issue as well.
