### ISSUE TITLE
Sorting of community solutions - oldest first?

### ISSUE THREAD

**Issue by ghost** [exercism/exercism#4104]
Are the community solutions sorted oldest to newest?
I think it should be the other way around because you're supposed to be interested in the fresh new implementations, right?

For example, https://exercism.io/tracks/python/exercises/hello-world/solutions .
There are 535 pages of solutions published 19 days ago, and only the very last two solutions date back to 16 and 14 days ago respectively.

Also, a lot of these solutions were actually uploaded years ago - maybe the "date published" can be changed accordingly?

**Comment by NobbZ** [comment]
The ordering itself is subject to change, I remember there was a ticket around this, polanning to sort them semi-randomly.

But publishing date will stick to be the migration date for the old data. As there was no exercism v2 2 months or 2 years ago one had publish to.

The explicit act of publishing a solution has only been added recently.

**Comment by willbasky** [comment]
And it will be great to sort by `well done` and `like it` also!

**Comment by n41r0j** [comment]
How about exercises that have been renewed, and for example use different return types? 

I've noticed this a couple of times in the Rust track, where when I wanted to find inspiration from others, I often found myself browsing through all the pages to find a recent solution that contained the latest exercise.

If the aim is to give useful solutions, then the solutions should apply to the correct problems.

Versioning an exercise could solve this, I guess?

**Comment by lwaite2010** [comment]
Perhaps it would be nice to be able to order or filter solutions either by the track language version. Working on the Elm track I find that some of the solutions from even a few months ago no longer work because of changes to the language.

**Comment by Stigjb** [comment]
I second the ability to filter solutions by the track version. I want to for instance see the most liked/commented community solution that applies to the current version of the exercise.

An alternative to filtering would be to mark solutions with an 'old version' flag that is visible on the results page, before clicking on a specific solution.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
