### ISSUE TITLE
Waiting for a long time for Go mentorship

### ISSUE THREAD

**Issue by mccollomds** [exercism/exercism#4106]
I have two frozen tracks after the upgrade. I've tried resubmitting the exercises, but nothing seems to get them into the reviewers queue. I'd love to keep progressing, but I can't open any new exercises

**Comment by rpottsoh** [comment]
Which tracks?  @ihid will want to know. 

Sent from my android device.

**Comment by rpottsoh** [comment]
Ok, those are exercises.  Which language track(s) are you experiencing the issue?

**Comment by mccollomds** [comment]
Sorry - the Go track

**Comment by iHiD** [comment]
@mccollomds Sorry for the frustration! (and thanks @rpottsoh)

> I've tried resubmitting the exercises, but nothing seems to get them into the reviewers queue. 

Can you just describe what you mean by them not getting into the reviewers queue? Does it say that a mentor will give you feedback. Do you have a screenshot as an example pls?

**Comment by mccollomds** [comment]
I've resubmitted the exercise 3 times since the upgrade. It seems like there must be a bug because other exercises have been reviewed, but those two have sat for over 16d without feedback. 
<img width="1178" alt="screen shot 2018-08-01 at 5 58 52 pm" src="https://user-images.githubusercontent.com/38952860/43552509-c2554556-95b8-11e8-9a70-798c326fa1de.png">

**Comment by iHiD** [comment]
@mccollomds Yeah, so there's just a big queue on the Go track atm. Sorry. Our mentors are churning away as fast as they can but they've struggling a little under the load. Go is one of three tracks where we really need more mentors than we have. We're trying to work out if there is a solution for this (e.g. auto-unlock after 3 days without mentoring) but we've not come up with a solution we're happy with yet. 

I'll ping this to the Go mentors and hopefully one of them will let you jump the queue and they'll mentor you next :)

**Comment by iHiD** [comment]
Can this be closed?

**Comment by sshine** [comment]
Ping, @mccollomds. :)
