### ISSUE TITLE
Setup issue: Add to $PATH in macOS 64-bit

### ISSUE THREAD

**Issue by klamgade** [exercism/exercism#4112]
While trying to **_Add to $PATH in macOS 64-bit_** following the attached instruction, I get an error saying "command is not found". Any idea on this?

note: I have checked and confirmed that it's 64-bit system and the commands are correct as mentioned on instruction.

**Followed below instrcution:**
<img width="714" alt="screen shot 2018-08-02 at 9 47 56 am" src="https://user-images.githubusercontent.com/14478366/43561915-6b661dd2-966d-11e8-9a83-36ff2136cfe2.png">

**Comment by NobbZ** [comment]
Oh, wait it's sourcing the profile, so restart shouldn't be necessary...

Can you please `tail ~/.bash_profile`?

**Comment by iHiD** [comment]
Can this be closed?
