### ISSUE TITLE
Signup fields difficult to read, poor contrast.

### ISSUE THREAD

**Issue by alexkingnz** [exercism/exercism#4113]
Undoubtedly I have a poor (LCD) monitor.  (Philips 170S)

I'm attaching a picture of the signup page as rendered on my monitor.

I can't see the explanation text in the signup fields on the page.  Actually, if I move my head to an awkward angle to the screen, I can just make out some text, it looks like a handle and two password fields.

If I mouse over the fields, I get an unhelpful tip, which I can read clearly "Please fill out this field".

I suggest either increasing the contrast of the help text, or giving the fields headings, or improving the tool tips, or a combination.
![img_20180802_095508](https://user-images.githubusercontent.com/3311026/43562495-ff91655e-9670-11e8-9b85-4fbcbaf34486.jpg)

Jeremy Walker suggested I post an issue here.

Thanks
- Alex

**Comment by bdjnk** [comment]
The should be a deeper concern here that [placeholders in form fields are harmful](https://www.nngroup.com/articles/form-design-placeholders/) generally.

**Comment by iHiD** [comment]
Interesting article. Thanks.

Large sites like Twitter and Facebook both use this pattern (screenshots below) so it's not something that I'm generally concerned about, as they'll invest lots in trying to make the signup process seamless. But it's something we'll have a think about.

<img width="629" alt="screen shot 2018-08-02 at 14 47 03" src="https://user-images.githubusercontent.com/286476/43587945-4653181a-9663-11e8-9257-600d8abaa1f4.png">

<img width="442" alt="screen shot 2018-08-02 at 14 47 07" src="https://user-images.githubusercontent.com/286476/43587847-0f1a5426-9663-11e8-8e47-2564a496b01c.png">

**Comment by unused** [comment]
Yes, I've form fields on my list and I can make some suggestions. As a rule of thumb every input must have a label. Placeholders are okay to pass some extra information e.g. if an input requires a specific format, but as already mentioned one should better not use them at all as the information disappears as soon as someone starts writing, better use some extra-information (referenced with `aria-describedby`) in that case.

I will come up with a suggestion to use labels and move them above the field similar to material design inputs.

If you want to have very good accessibility use labels before/above the input with full fontsize and don't move them around on focus.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
