### ISSUE TITLE
Add "Pause Track" option

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4123]
- [ ] Add button above "Leave Track" in mentored mode
- [ ] Add button above "Leave Track" in independent mode
- [ ] Add modal like Leave Track, which explains what it's doing
- [ ] Put the user track into paused mode but don't remove the solutions.

**Comment by PatrickMcSweeny** [comment]
I could tackle this if no one else is working on it.

**Comment by iHiD** [comment]
Sure. Thanks! :)

**Comment by PatrickMcSweeny** [comment]
Any thoughts on what a user should see when they click the link for a track they have paused?
