### ISSUE TITLE
inconsistent number of exercises (python track)

### ISSUE THREAD

**Issue by rachelhornung** [exercism/exercism#4124]
In the tracks overview python is listed with 118 exercises, on the top of the python track page it displays 106 exercises. The numbers in the "What's next box" for a given exercise match 106.
Only noticed this for python, so far.

![python_track](https://user-images.githubusercontent.com/2362113/43615656-8c7e9a94-966d-11e8-8241-4674d7fa751f.png)
![tracks_overview](https://user-images.githubusercontent.com/2362113/43615658-8da3802e-966d-11e8-8ea9-26ffc2b4a659.png)

**Comment by rachelhornung** [comment]
probably related to  #4115

**Comment by cmccandless** [comment]
It appears that deprecated exercises are being included in the total for the track overview.

**Comment by cmccandless** [comment]
On a related note: it appears that solutions for deprecated exercises are being included in the `completed` total for track progression:

Screenshot:

![screenshot of total completed exercises including deprecated](https://github.com/cmccandless/legendary-palm-tree/raw/master/exercism_track_progression_deprecated_submissions.png)

Also, some Python track statistics for reference:
Total: 120
Foregone: 1
Deprecated: 12
Active (Sum of Core + Non-core): 107
Core: 15
Non-core: 92

**Comment by nicolechalmers** [comment]
I've noticed inconsistency in total number of exercises on the tracks/haskell/exercises page which I think might be related to this issue.

<img width="329" alt="screen shot 2018-08-10 at 12 59 40" src="https://user-images.githubusercontent.com/5421823/43954985-b16262fa-9c9e-11e8-8de6-d2e9b2de6a3b.png">
<img width="476" alt="screen shot 2018-08-10 at 13 04 16" src="https://user-images.githubusercontent.com/5421823/43954986-b18fb3f4-9c9e-11e8-9a29-4fc15acfe521.png">
