### ISSUE TITLE
Cannot publish solution

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4126]
In the Independent track, I see no way of publishing (finalizing) my solution. How do I do that? I may have missed something in the UI :( I also tried to publish from the Community solutions page but couldn't either.

**Comment by iHiD** [comment]
Is this still an issue?

**Comment by ftt** [comment]
I am no longer on the independent track. Is it safe to switch to it and back to mentored to verify? I.e. what information will be lost in the switch?

**Comment by texastoland** [comment]
This may be related to #4432 but not specific to switching.

**Comment by iHiD** [comment]
Closing in favour of #4432.
