### ISSUE TITLE
Beginner Interaction with Terminal

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4127]
I have just barely started with the Javascript track but am stuck! I have moved the folder successfully to the bin folder and even have downloaded the hello-world files.

However this bit of code won't run. My terminal won't recognize this function.
`jasmine hello-world.spec.js`

I've tried downloading jasmine and node.js but that hasn't fixed my problem.

I know I am a super beginner at this but can someone help me see what I'm missing here?

**Comment by iHiD** [comment]
@abigailloosle This issue has been moved to this repository.

I suspect that it would be worth you going through some exercises on a more beginner-orientated site to get a good understanding of things like Jasmine, then return here when you built up your knowledge a little bit. You'll be very welcome :)
