### ISSUE TITLE
Turning on branch protection for all tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4129]
### Background

 A couple of months ago @nicolechalmers started doing sketches, designs, and wireframes based on the [design documents](https://github.com/exercism/docs/blob/master/about/conception/README.md) that Thalamus and I have spent the past 6+ months working on. More recently, @ccare and @iHiD started implementing a prototype based on those designs. We've made some design decisions that we believe will be a vast improvement over the current website, particularly with respect to how changes in track repositories are reflected on the site.

### Current Situation

In the current website, track repositories are all submodules in a Ruby gem which has some additional logic related to tracks and exercises. This means that we need to

- ... in the gem:
  - update all the submodules
  - bump the version
  - publish a new version to rubygems
- ... in the website (_and_ the api):
  - update the version of the gem in the lockfile
  - commit
  - deploy

In other words, this involves committing to three different repositories and deploying two different codebases.

There are a lot of places where this can go wrong, not to mention _I have to actually deploy_. Sometimes I get busy, and which point all the hard work that all the maintainers do gets held up.

That's not acceptable.

### Changes in Nextercism

In the nextercism prototype we're working directly with the tracks' git repositories themselves. We will be updating these continuously, so any changes to the tracks should be reflected on the website near-instantaneously (well, it might take a minute, but probably not much longer than that. Compared to the day-to-week lag that you all are used to operating with, this will probably feel like a bit of a miracle).

On the other hand, this means that if we screw up master in any way on a track, that will be reflected on the website immediately.

### Proposal

So. In order to protect the website I wish to turn on branch protection for the master branch of all tracks. That will mean that:

- master cannot be pushed to directly
- before they can be merged, all pull requests must
  - have at least one approval
  - have a passing build
  - be up-to-date with master

This means that even trivial changes will need to go into a branch and a pull request, and be approved by one of the other maintainers.

This might be a little bit annoying, but I think it's worth it.

If you have any counter-arguments or can think of anything I've missed, or other ways to protect the website from bad changes, I'd love to hear your thoughts.

If you think this seems reasonable but don't have anything to add to the discussion, please add a 👍 reaction.

**Comment by iHiD** [comment]
@kytrinyx Where do we go from here in this discussion?

**Comment by kytrinyx** [comment]
@iHiD I think we need to go to first principles and decide what is crucial in order to protect the integrity of the site. I don't know what that is right now.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
