### ISSUE TITLE
Validate the test data version as part of a travis build

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4131]
Thanks to the work of @rbasso (see https://github.com/exercism/x-common/pull/602, https://github.com/exercism/x-common/issues/625, https://github.com/exercism/x-common/issues/673, etc) and many more, we now not only have a schema but also a test data version.

In https://github.com/exercism/x-common/issues/524 @robkeim started to think about how to propagate changes from `x-common` to the tracks. In this issue @ErikSchierboom wrote:

> Yes, sending an update each time something changes in x-common can be tiresome, but the alternative (manually keeping track of x-common) is not a whole lot better.

So, I thought about a way that doesn't generate a lot of mails, issues or notifications, but makes sure that at least every time someone actually is working on a test file it is up to date.

I started to work on a script ([check-testversion.py](https://github.com/behrtam/xpython/blob/test-version-check/test/check-testversion.py)) for the python track that checks the versions for all exercises that are part of a travis build against the newest version in the `x-common` repo, a bit like a linter or stylechecker. It still needs a lot of cleanup and testing, but it at least proves that the basic idea is working.

The basic concept is ...

1. get a list of changed files `git diff --name-only $TRAVIS_COMMIT_RANGE`
2. get the newest version from `canonical-data.json` through `https://api.github.com/repos/...`
3. get the actual version from a comment in the test file `# test @ version: 1.0.0`
(maybe it should be excluded into a separate JSON file as part of the exercise directory)
4. compare the versions and output some infos

As a test I changed the anagram version back from 1.0.1 to 1.0.0 in this commit: https://github.com/behrtam/xpython/commit/3dc7acd3fd2eaee4098ca0e71e40c9dbc3a65fe4
Which resulted in a failed build as expected: https://travis-ci.org/behrtam/xpython/jobs/219306945#L163

I don't know if this will finally be integrated into the python track or if this is a good idea at all, but I thought maybe some parts of this could also be interesting for other tracks.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
