### ISSUE TITLE
Include a "Journey Test" in the CI build of each track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4132]
_(spawned from discussion in #79)_

**tl;dr:** come up with a way to automate [journey style](http://martinfowler.com/bliki/UserJourneyTest.html) tests in CI for each track so that maintainers spend less time doing bookkeeping and have more room to use their judgment and creativity.
# Context

One of the more labor intensive parts of maintaining a track is ensuring that submissions from contributors are fit for production use.  The maintainer must verify:
- the tests and sample implementation are present and fully implement the exercise (especially with respect to the attendant `canonical-data.json` or, absent that on par with implementations in other tracks);
- the tests are reasonably exemplary: especially how those tests define the interface/protocols of the solution;
- if it's a new-to-the-track exercise, that it was properly included in the `config.json`;
- that the exercise can be successful served by the CLI (e.g. does not include any binaries);
- in the case where the build of the exercise _outside_ the track repo runs differently than the exercise _inside_ the track repo, that when fetched by exercism programmers, will continue to work.
# Problem

Some of this work requires human judgment, but a good deal of it is manual, monotonous and error-prone.  It also takes precious volunteer time of maintainers on ensuring that newly implemented exercises don't break production.
# Proposal

In CI (i.e. Travis) automate a full [Journey Test](http://martinfowler.com/bliki/UserJourneyTest.html) of an exercism programmer implementing the all the exercises of the track, for each track.  This involves:
1. Setup both the track language tool chain and Ruby in CI;
2. Download and stand-up `x-api`, configured to serve exercises from the HEAD of the branch being built instead of the ref of the submodule;
3. Download and configure the exercism CLI;
4. Iterate over the set of exercises, fetch each, "solve" by copying over the "example" solution and run the tests.
## Requirement: Be Modular

This should be done in a way such that the work required specifically for the track (e.g. which track is in play, where to copy solutions from, how to run the tests on the exercises, what pre- or post- steps are required) is separated from the common work of standing-up a local copy of `x-api`.  In this way, whenever details about the common work changes, it can be reflected in the Journey in one place.
# Resources
- The Java track has implemented such a test in bash: [journey-test.sh](https://github.com/exercism/xjava/blob/master/bin/journey-test.sh).
- Regardless of the track language, Ruby is required in the CI environment as it is a dependency of `x-api` (read: given the desire to provide a test harness and the difficulty in maintaining bash, implementers are strongly encouraged to consider Ruby).
# Next Steps
- Question the premise.  Question the proposal.  Is there another/easier way to squash the waste of reviewing the syntax of track submissions?
- If you agree with the proposal, use the prior art to guide an implementation in one track.  Be mindful of the parts that are track-specific.
- Use the test harness to implement the same on a second track and evaluate.
- Incorporating learnings, if this approach seems sound, fan-out an issue in each track for implementing this in Travis, providing implementation guidance.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
