### ISSUE TITLE
"File not moved"

### ISSUE THREAD

**Issue by aliklynnlyle** [exercism/exercism#4133]
Hello, I am stuck at: 

" if [ -f ~/bin/exercism ]; then echo "file moved"; else echo "file not moved"; fi
file not moved "

Not seeing a way to ask a mentor, though? I tried changing my permissions and that didn't seem to work.

Thanks in advance!

**Comment by NobbZ** [comment]
Can you please provide the output of `stat ~/bin/exercism`?

**Comment by aliklynnlyle** [comment]
stat: No such file or directory

**Comment by NobbZ** [comment]
But you are sure you have `cp`d it first?

**Comment by NobbZ** [comment]
Wait, I think it's even better you start the installation from scratch, copy pasting each command and it's output here into the issue, wrapped in a proper fenced codeblock until you get to the `if` from above.

**Comment by aliklynnlyle** [comment]
OK wonder if I should try to uninstall first then?

**Comment by NobbZ** [comment]
It doesn't seem as if there were something to uninstall...

**Comment by aliklynnlyle** [comment]
ok here is the latest in the process:

exercism configure --token=73c748c2-02c8-417c-b082-4a1799ca1040
Error: 
    The default Exercism workspace is

      /Users/Alicia/Exercism

    There is already something there.
    If it's a directory, that might be fine.
    If it's a file, you will need to move it first, or choose a
    different location for the workspace.

    You can choose the workspace location by rerunning this command
    with the --workspace flag.

      exercism configure --token=73c748c2-02c8-417c-b082-4a1799ca1040 --workspace=/Users/Alicia/Exercism

**Comment by NobbZ** [comment]
Ah, nice, so it seems you came much further than before.

But you token is now compromised, you should reset it, but I was unable to find such a button on the website.

But everything else is said in the error message, if you want to keep your old workspace, just copy the command and run it, if not specifiy a different workspace or delete the old one and create a new.

**Comment by aliklynnlyle** [comment]
Ok just copy which command?

**Comment by NobbZ** [comment]
That one in the error message you have posted. It's the very last line of your post.

```
$ exercsim configure --token=… --workspace=…
```

**Comment by iHiD** [comment]
Closing this as it's stale. Feel free to reopen if still relevant.
