### ISSUE TITLE
Permit associating shared 'mentor notes' with each exercise

### ISSUE THREAD

**Issue by frerich** [exercism/exercism#4135]
In the Haskell track (and I suspect this is true of other language tracks), many submissions suffer from the same deficiencies and thus would benefit from the same suggestions. It's typically short stuff like (in the Haskell case):

* In the Leap exercise, defining a separate `isDivisibleBy` function might be useful; also, `rem` is preferable to `mod` here.
* In the Collatz exercise, don't recurse and count manually but rather try to take advantage of standard library functions like `genericLength`, `takeWhile` and `iterate`.
* In the Pangram (and Isogram) exercises, avoid `nub` due to O(n^2) complexities but rather hint at `Data.Set`
* In the Phone Number exercise, pattern matching is a viable alternative to parsing the input string.
* In the Rna transcription exercise, the standard function `mapM` is a great fit.

etc.

It would be great if it was possible to store such insights along with each exercise, so that fellow mentors have an easier time. Maybe it would also be a good place to store little text fragments to use when writing a comment

**Comment by iHiD** [comment]
So this is similar to https://github.com/exercism/exercism.io/issues/4083 but for shared stuff. 

We're going to do this but haven't yet worked out how to structure it. It'll be some sort of GitHub repo that everyone can PR to I think. I'll chat it over with the product team and we'll work out the methodology.

**Comment by aldraco** [comment]
Especially for the earlier exercises, having notes and a full list of things to look for would enable more people to chip in as mentors, sooner. This sounds like a net win - more comprehensive coverage of coverage, and more mentors available for the earlier exercises, which often have more solutions that need feedback.

**Comment by JWKyle** [comment]
I agree.  As a less seasoned developer, I think it would help more people like me lessen the confidence gap, especially when giving feedback.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
