### ISSUE TITLE
Leave track does not clear all the solutions like mentioned

### ISSUE THREAD

**Issue by budmc29** [exercism/exercism#4136]
I completed the exercises on the old version.

`budmc29`

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/7063792/43644967-6d47a4ca-9728-11e8-9738-016d7c515665.png">

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/7063792/43644982-74ca991e-9728-11e8-9811-9dc8aae2c865.png">

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/7063792/43644996-824134b8-9728-11e8-8594-9097dde3aa93.png">

**Comment by iHiD** [comment]
Weird. Thanks. @kntsoriano ?

**Comment by iHiD** [comment]
This is my bad. I screwed up your PR someone @kntsoriano. Do you have the original branch locally still? Ping me on Slack about this :)

**Comment by budmc29** [comment]
This is fixed now, thanks.
