### ISSUE TITLE
Configlet: doesn't use `hints.md` anymore?

### ISSUE THREAD

**Issue by guygastineau** [exercism/exercism#4139]
Sorry if this is a dup.  I couldn't find clear info on it.

I'm just trying to confirm whether or not configlet  utilizes the hints.md for exercise readme's anymore.

Asking for a friend :stuck_out_tongue_winking_eye: 
Thanks

**Comment by guygastineau** [comment]
I am trying to clean up my stale issues, but this one is important.  I've seen some people on slack trying to figure out if they can use the hints.md that is still in some tracks, and I think we should make it clear whether it is still used or not

**Comment by rpottsoh** [comment]
I know `configlet` will insert hints.md if found.  It may only be doing it as long as `{{- with .Hints }}` appears in a track's `exercise_readme.go.tmpl` file.  I may not be completely correct about this last part, but I know that occurrences of hints.md that appear in /.meta/ do end up inserted into README when `configlet generate` is executed.

**Comment by guygastineau** [comment]
@rpootsoh thanks
