### ISSUE TITLE
Crowdsourcing mentor notes

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4140]
We've been exploring different ideas for how we can provide mentors with helpful notes and guides to different exercises. We have some nice long-term plans about writing guides for mentors for each exercise. However, it's become clear that there is also an appetite for mentors just to crowdsource their thoughts.

We're going to add a couple of extra bits to the mentoring UI to show crowd-sourced notes (per track/exercise), and also a space for personal notes (per track/exercise/mentor). This will fulfil #4083 and  #4135. However, we don't **need** to get this into the UI to get started, so we've put together a [mentoring repository](https://github.com/exercism/mentors) where we can store notes by each exercise.

- The structure within the repository is: `/tracks/ruby/exercises/isogram/README.md`
- Mentors can easily edit the files within GitHub to create Pull Requests for changes.
- We'll be offering some mentors write permissions to the repo so that they can merge PRs without waiting for us to check everything.
- In the near-future we'll auto-pull things into the website to display it for mentors at the relevant time.

Please use `###` for headings and try to keep to a structure of:
- **Reasonable solutions**: 1+ solutions that solve this problem well.
- **Common suggestions**: Good suggestions specific to this exercise. Good lessons that emerge from it. 
- **Talking points**: Questions to challenge more advance learners with.

If there are other headings that people feel would be useful, please discussion them here.

Here's an example I just made for [Ruby's Isogram](https://github.com/exercism/mentors/blob/master/tracks/ruby/exercises/isogram/README.md).

<details>
<summary>This is how you create a new file:</summary>

![Create a new file](http://g.recordit.co/96zCDgEkfG.gif)

</details>

**Comment by kytrinyx** [comment]
I added one for `two-fer` on the Go track https://github.com/exercism/mentors/blob/master/tracks/go/exercises/two-fer/README.md

**Comment by sshine** [comment]
This issue is part announcement and part documentation. The documentation already exists in https://github.com/exercism/website-copy 's README, so we can safely close this.
