### ISSUE TITLE
Add user preference to restore "Tab to Indent" in Mentor comments editor

### ISSUE THREAD

**Issue by yawpitch** [exercism/exercism#4144]
A recent change (described [here](https://exercism-mentors.slack.com/archives/CAQP7JL3T/p1533285596000123?thread_ts=1533279906.000188&cid=CAQP7JL3T)) "broke" the previous behaviour of the comments editor in the "Mentor discussion" area of each exercise. Previously the `tab` key had performed its traditional text editor duty, indenting the text. Now it navigates the focus of the UI. While this is certainly a good thing for those with Accessibility needs, it means that entering code blocks in languages such as Python that are indent-sensitive has become quite difficult.

While there are obviously manual workarounds, they're all problematic, as Python is *extremely* sensitive to mixed indentation depths, and basically the only solution is to keep a text editor window open while doing any code examples and copy and paste from that. That isn't always a serviceable option.

Ideally there would be a user preference in the editor that would re-enable `tab` for indentation for any user that chose to forgo the Accessibility navigation feature. Ideally this would persist, site-wide, for that user's account.

**Comment by sshine** [comment]
I think this level of configurability adds complexity we don't want. The feedback window already contains a number of UI bugs, and we'd probably introduce more if we think that extending the features of an in-line multi-purpose editor and maintaining it as a website template is the best way to go.

I'd rather see a makeover of the feedback window that is maintained separately and doesn't have funny rendering and reaction artifacts. I don't know if there is a good intermediate step before we start hitting a decent in-browser editor for students that could also be used for the feedback window.

Could a satisfactory hack be an in-browser user script?

**Comment by sshine** [comment]
To underline the complexity that this feature request adds, should we also provide an option to decide between tabs and spaces, and should we provide an option for how many spaces constitutes a tab?

**Comment by iHiD** [comment]
I believe we could potentially add the shift-tab option. Maybe as part of https://github.com/exercism/exercism/issues/5039 if @yyyc514 fancied trying to implement it as part of that. That's a more likely short/medium-term solution than a user preference (purely based on complexity/time dev tradeoff).

We're also add in-browser coding and need a solution for that (we'll probably be using [ACE](https://ace.c9.io) as the editor).

**Comment by yyyc514** [comment]
If no one objects and it just happens to be super easy (don't want to lose focus)... **but isn't shift-tab supposed to go BACKWARDS???**  Not sure it's a good substitute keystroke for tab.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
