### ISSUE TITLE
Should there be a Slack channel for students?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4146]
Presently https://gitter.im/exercism/support sees a fair amount of traffic.  It serves as a catch all place where students go to ask all sorts of questions about anything pertaining to Exercism....

Usually the questions relate to configuration issues and sometimes language related.  If the questions are not too involved they get answered on the spot otherwise they are advised to open an issue and where to open it.  People end up in this room I guess because they are not sure where to go for help, especially if they are new.  Also, response times in this gitter room are pretty short. Nod to @nobbz and @kotp.

**Comment by NobbZ** [comment]
Most students will probably have a GitHub account already, though accessing gitter is relatively easy. Slack on the other hand requires just another account to create and the process is not always easy, as slack workspaces aren't public, they are locked down per definition and you need an invitation to join.

So a student had to request his invitation first, then from the invitation he can actually register to that workspace, than he will be pushed through some tutorial before he will be able to actually ask his question.

Gitter does just work after granting gitter access to GitHub profile.

**Comment by rpottsoh** [comment]
I agree.  But I thought maybe it was worthwhile to at least create the issue since mentors and maintainers are being discussed as it relates to Slack.

I am not sure how people are finding the gitter/support room.

**Comment by iHiD** [comment]
I would rather not add a new Slack for students. 

However, I'm interested in discussing a tool that allows students to interact on the website with a Slack channel in the mentors room. I do something similar to that in one of my businesses for support through Intercom and it's very effective.

Then there is no extra signup at all for students and they never have to leave the Exercism website.

**Comment by rpottsoh** [comment]
That is an interesting angle.  Maintainers should also be included (allowed).

**Comment by iHiD** [comment]
So I think the "Mentors Slack" will become "Mentors and Maintainers" Slack, with private channels for each tracks' maintainers, but then the maintainers can also join in discussions on the main language tracks.

ie, you'd be in:
- track-delphi
- maintainers-delphi

Then maybe (very maybe) we'd have a channel called `support` which students were able to post into.

**Comment by rpottsoh** [comment]
Sounds very reasonable. :wink:
