### ISSUE TITLE
Resetting the API token

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4150]
Sometimes a token slips through a bug report or exercism was configured on so many systems, that one lost overview over his devices and want to revoke all of them at once.

In v1 this was very easy, we were able to reset the API key from the very same page were we could copy it from.

It seems as if this `reset` action is missing from v2.

**Comment by iHiD** [comment]
Agreed.

**Comment by NobbZ** [comment]
I've spotted another token, can we please have this soon?

**Comment by NobbZ** [comment]
And another month… Can someone please take care of this?

**Comment by NobbZ** [comment]
Please, can we have at least have some hints were to look for solving this?

It has happened again!

**Comment by iHiD** [comment]
I've added it to the roadmap. I have a 10hr flight tomorrow night and I'm hoping to pick some of these low-hanging-fruit off during it.

**Comment by iHiD** [comment]
@NobbZ Done. Deploying shortly.
