### ISSUE TITLE
Not in workspace: Trailing Slash in custom workspace path

### ISSUE THREAD

**Issue by Jarvvski** [exercism/exercism#4153]
When trying to submit, I got an error for not being in the workspace. I've had a look at #4070 among others, but that didn't solve my issue because it's based on the default paths set by Exercism.

I originally updated the `~/.config/exercism/user.json` to reflect where I store my exercism stuff:
```
{
  "apibaseurl": "https://api.exercism.io/v1",
  "token": "XXXXX",
  "workspace": "/Users/jarvis/code/xcsm/"
}
```

Running the workspace argument also returns the correct path:
```
$ exercism workspace
-> /Users/jarvis/code/xcsm/
```

The actual path of course is:
```
$ pwd
-> /Users/jarvis/code/xcsm
```

I realised that perhaps exercism wasn't trimming trailing slashes, and after testing, this did indeed fix it.

This is of course a minor nit pick. I'm also unsure how many people set custom paths for the exercises, or if I'm just `wrong` for leaving the trailing slash in the first place. Either way, I thought I'd respond here in case anyone else sees this.

**Comment by guygastineau** [comment]
I think it expected that users wanting a custom workspace will use the workspace flag with the config command in the cli.

**Comment by Jarvvski** [comment]
@guygastineau I'm not so sure. Considering I saw that it created a `.config/` sub directory (with .config being a very common place to store such things) it makes perfect sense that someone would just change that file.

It works fine, it's just I expected it to trim the trailing `/` off the end of the path

**Comment by guygastineau** [comment]
I agree it is common for computer users to edit files in a `.config/` directory.
I am, however, sure that the cli is expecting the changes to be made through its options.
This is evidenced by it not formatting your alteration of the configuration file.

I think it might be reasonable for you to request that the cli remove trailing `/` from the path in the config.
That being said, almost every tool I use throws an error if I mis-format the config instead of fixing it auto-magically.

Happy coding :smile:

**Comment by NobbZ** [comment]
If the filepath prefix function mentioned in exercism/cli#637 works as expected, a trailing slash in the config won't be an issue anymore.

**Comment by guygastineau** [comment]
Thank you @NobbZ

**Comment by guygastineau** [comment]
@Jarvvski

Have you had a chance to upgrade the cli and see if it is fixed for this issue?

**Comment by Jarvvski** [comment]
@guygastineau, @NobbZ has the CLI been updated to use that?

I last upgraded on Saturday

**Comment by NobbZ** [comment]
It has not. Just look at https://github.com/exercism/cli/releases, there you can check for the date and version number of the latest release.

Also the issue I linked to is still open, so you can safely assume that **that** thing hasn't been fixed so far, regardless if there was a release or not.

And, last but not least, `exercism upgrade` is able to tell you whether or not a new release has happened as well as `exercism troubleshoot`

**Comment by Jarvvski** [comment]
Ah, its the cli repo. Sorry I didn't see any releases here and just didn't give it a thought!

**Comment by kytrinyx** [comment]
This has now been released.
