### ISSUE TITLE
Is Hamming too complex for non-English speakers?

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4155]
I've just been reading through the Hamming README (in Ruby specifically). There's lots of words in here that are potentially unusual/challenging for non-native-english speakers. (I am a native speaker so this is a question)

I've highlighted some words below that stood out to be as maybe things I wouldn't know if I wasn't a native speaker of a different language.

> A mutation is simply a mistake that occurs during the creation or copying of a `nucleic acid`, in particular DNA. Because `nucleic acids` are vital to `cellular` functions, mutations tend to cause a ripple effect throughout the cell. Although mutations are technically mistakes, a very rare mutation may equip the cell with a `beneficial` attribute. In fact, the `macro effects` of evolution are attributable by the accumulated result of beneficial `microscopic` mutations over many generations.

> The simplest and most common type of nucleic acid mutation is a point mutation, which replaces one base with another at a single `nucleotide`.

> By counting the number of differences between two `homologous` DNA strands taken from different `genomes` with a common `ancestor`, we get a measure of the minimum number of point mutations that could have occurred on the `evolutionary` path between the two strands.

Should we try to make this README more accessible to non-native speakers? Did anyone non-native-english find it hard the first time they came across it?

**Comment by NobbZ** [comment]
Perhaps it might be easier to understand when we use Wikipedias abstract from the IT Hamming Distance?

> In information theory, the Hamming distance between two strings of equal length is the number of positions at which the corresponding symbols are different. In other words, it measures the minimum number of substitutions required to change one string into the other, or the minimum number of errors that could have transformed one string into the other. In a more general context, the Hamming distance is one of several string metrics for measuring the edit distance between two sequences.

Also it might be even easier to understand for most people, as you can give examples that are actual words and not abstract random letters representing a DNA.

**Comment by rpottsoh** [comment]
When writing testdata and READMES in problem-specifications it is encouraged to keep the language as simple as possible, to not use unecessarily complex language. 

Sent from my android device.

-----Original Message-----

**Comment by benrodenhaeuser** [comment]
I think what is a bit confusing about this README is that the first few paragraphs contain a lot of background info that merely "provide context", so to speak. This is also where the technical jargon is used. Some people might think they need to understand this context in order to solve the exercise, which isn't really the case. 

The last couple of paragraphs, on the other hand, do contain a concise description of the actual implementation task that should be accessible for non-native speakers of various levels: 

```md
It is found by comparing two DNA strands and counting how many of the
nucleotides are different from their equivalent in the other string.

    GAGCCTACTAACGGGAT
    CATCGTAATGACGGCCT
    ^ ^ ^  ^ ^    ^^

The Hamming distance between these two DNA strands is 7.
```

So how about shuffling the order? Start with the above quote, mildly edited, followed by  the background info (also mildly edited).

**Comment by NobbZ** [comment]
As Hamming Distance is applicable to any 2 sequences of information given they have the same length, I'm not a fan of limiting it to its biological specialisation.

I never was, to be honest.

In theory, even these two erlang lists could be analised via hamming distance and would have a distance of 2:

```
A = [ok, undefined, {foo, bar}]
B = [error, undefined, {two, elements}]
```

Each list contains 3 elements. We can compare each of those for equality. So the first (`ok` and `error`) and last (`{foo, bar}` and `{two, elements}`) differ.

Of course, for the sake of simplicity we should limit the tests to strings or sequences of numbgers.

**Comment by iHiD** [comment]
So I really love the story. It makes me feel like I'm solving a real problem, not a toy problem. But it does feel like I'm learning a lot of molecular biology to get there, which could be a little intimidating for english-speakers and even more so for non-native speakers.

There's also a lot of information in general before the task. I've only done Hamming for the first time today because every time I've looked at it in the past I've thought I'd really need to give some serious time to the exercise. I now realise it's very simple.

As this is the first exercise for Ruby and maybe other tracks, I worry that we could put people off by having so much text. 

This is a shorter, less technical version I just made up. I'm not suggesting we replace it with this, but it might give us some thought about how we could improve it:

```
Your body is made up of cells that contain DNA. Those cells regularly wear out and need replacing, which they achieve by dividing into daughter cells. In fact, the average human body experiences about 10 quadrillion cell divisions in a lifetime!

When cells divide, their DNA replicates too. Sometimes during this process mistakes happen and single pieces of DNA get encoded with the incorrect information. If we compare two strands of DNA and count the differences between them we can see how many mistakes occurred. This is known as the "Hamming Distance".

We read DNA using the letters C,A,G and T. Two strands might look like this:

    GAGCCTACTAACGGGAT
    CATCGTAATGACGGCCT
    ^ ^ ^  ^ ^    ^^

The have 7 differences, and therefore the Hamming Difference is 7.

The Hamming Difference is useful for lots of things in science, not just biology, so it's a nice phrase to be familiar with :)
```

**Comment by tehsphinx** [comment]
@iHiD I like your suggestion. It's a lot easier to read and understandable to a non-native speaker like me -- although my english is probably too good meanwhile to be a measure here. Additionally it reduces/simplifies the amount of domain specific knowledge included in the description.

At the same time it keeps the exercise in the **ascii space** which is important, I think. On the go track for example I would have to dismiss a lot of solutions comparing bytes if the strings to be compared were not limited to ascii.

**Comment by iHiD** [comment]
@kytrinyx What is the best way of going about making this change? A PR to problem specifications?

**Comment by iHiD** [comment]
Closing this in favour of https://github.com/exercism/problem-specifications/pull/1360
