### ISSUE TITLE
Error message when downloading from a track one hasn't joined is not clear

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4159]
Currently when a potential student tries to download from a track he hasn't joined yet, he gets the message "Solution not found", instead he should see an explanation that he needs to join the track before downloading the exercise, as well as a link to the tracks page, such that he can join easily after following the link.

**Comment by iHiD** [comment]
Yes. Good point. The API does return this already I believe so I think it's just a CLI change.
