### ISSUE TITLE
mentor: show concept goals of an exercise

### ISSUE THREAD

**Issue by Emerentius** [exercism/exercism#4160]
When evaluating a solution, I'd like to be able to quickly check what the goals of an exercise were so I can better judge whether a student has achieved that. Every exercise has a few concept tags attached to it, but they are not visible when mentoring.

It would be nice if I could see them without having to go into the student track view.

**Comment by kytrinyx** [comment]
@Emerentius we're currently working on integrator mentor notes into the mentor UI. Actually adding notes for each exercise is a work in progress, of course, and we're crowd-sourcing based on notes from all the mentors.

You can see what the existing notes look like so far:

- Ruby: https://github.com/exercism/mentors/tree/master/tracks/ruby/exercises
- Haskell: https://github.com/exercism/mentors/tree/master/tracks/haskell/exercises
- Kotlin: https://github.com/exercism/mentors/tree/master/tracks/kotlin/exercises
- Go: https://github.com/exercism/mentors/tree/master/tracks/go/exercises

I am not sure how much the topics by themselves would help, as in many cases the topics aren't so much about the goals of an exercise, but various elements that they might touch on.

**Comment by Emerentius** [comment]
That would also solve the problem. I proposed this because I didn't want to make a large request.
