### ISSUE TITLE
Add a way for users to unpublish solutions

### ISSUE THREAD

**Issue by orenyk** [exercism/exercism#4163]
I was looking for a way to unpublish some of my earlier solutions and couldn't see a way to do that through the website. If such a feature doesn't exist it would be great if it could be considered. Thanks!

**Comment by iHiD** [comment]
@orenyk Thanks for the issue. It's something that's coming soon but we haven't quite got round to yet. I imagine it will land at some point during August :)

**Comment by orenyk** [comment]
@iHiD is there WIP I could jump in on or a particular way you'd like it implemented. I wouldn't mind taking a stab at it myself if you'd like. Thanks!

**Comment by glhrmv** [comment]
I'm assuming this feature hasn't been implemented at, is there an ETA on it?

**Comment by shrugalic** [comment]
The reason I was interested in this feature is because I accidentally published a [non-compiling solution for an exercise](https://exercism.io/my/solutions/0db5d42185c34e55b62fb59f3e264e48?iteration_idx=2).

Submitting yet another solution (a working one this time) for the same exercise **automatically updated the published version** with it, which is good enough for me.

I don't think my published solution adds anything new compared to other published solutions, so I wouldn't mind deleting it, but at least it doesn't do any harm either.

**Comment by PatrickMcSweeny** [comment]
It'd be good to add a link for unpublishing a solution on the solution page itself. I spent far more time than I care to admit looking for a link there.

**Comment by iHiD** [comment]
Want to open an issue for that?

**Comment by arcseldon** [comment]
@iHiD - Done yet? If not, please can you reply with new ETA.

**Comment by PatrickMcSweeny** [comment]
@arcseldon You can publish/unpublish solutions here:

https://exercism.io/my/solutions

You can find a link to it on your profile page.

**Comment by arcseldon** [comment]
@PatrickMcSweeny - Thank you, exactly what I was hoping for :) Still unclear how to navigate to that URL from the Exercism landing page or menu options. Assume I am missing something obvious - nevermind, bookmarked the above.

**Comment by shrugalic** [comment]
Click your picture on exercism and go to [my profile](https://exercism.io/my/profile) (possibly with `/new` at the end if never visited before)
There you'll find [Change public solutions](
https://exercism.io/my/solutions)

**Comment by PatrickMcSweeny** [comment]
I agree that it is confusing. I already opened #4525 to put a link to unpublish the solution directly on the solution page.

**Comment by arcseldon** [comment]
@PatrickMcSweeny @shrugalic - Thanks both. 

Another consideration (usability only) might be to disable community publication of a solution (which I did by accident) for anyone that hasn't opted into creating a public profile.

**Comment by PatrickMcSweeny** [comment]
Update: I opened a [pull request](https://github.com/exercism/website/pull/498) to add a button to unpublish a solution on the 'my solution' page. That should make things less confusing.
