### ISSUE TITLE
Give useful error messages for the error types that the API returns on download

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4164]
_Imported from https://github.com/exercism/cli/issues/560._
_Originally posted by @FabienTregan._

#

# Environment

* windows 10, cmd.exe shell
* latest CLI from github nextercism branch

# Observed behaviour

Trying to download from a track you have not joined gives an error message which does not help the user to solve the problem :
```
D:\code\Exercism>v2.exe download hello-world --track=c
Error: Solution not found
```
Repeating the same command after you joined the track works as intended:
```
D:\code\Exercism>v2.exe download hello-world --track=c

Downloaded to
D:\code\Exercism\workspace\c\hello-world
```

**Comment by iHiD** [comment]
@kytrinyx Can I assign this to you and add the `cli` label to it, or is there extra API work you need?

**Comment by kytrinyx** [comment]
@iHiD The API doesn't return an error message, it just returns an error code. I don't want to hard-code the error message in the CLI, because then if we change it, we would have to cut a new release and get people to upgrade before they see the new message.

**Comment by iHiD** [comment]
@kytrinyx I believe the API does return an error message. 

A current test for an example of this is:
```ruby
    get latest_api_solutions_path(exercise_id: exercise1.slug), headers: @headers, as: :json
    assert_response 400
    expected = {error: {
      type: "track_ambiguous",
      message: "Please specify a track id",
      possible_track_ids: [exercise1.track.slug, exercise2.track.slug]
    }}
    actual = JSON.parse(response.body, symbolize_names: true)
    assert_equal expected, actual
```

If something needs changing, let me know :)

**Comment by kytrinyx** [comment]
`track_ambiguous` is fine, we're getting the message and handling it.
It's all the `render_solution_not_found` calls that are not providing any context:

https://github.com/exercism/website/blob/49450d71253cfbbb49ad7c4660ad74e060a315dc/app/controllers/api_controller.rb#L34-L36

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
