### ISSUE TITLE
Student: updated exercises notification

### ISSUE THREAD

**Issue by mikewalker** [exercism/exercism#4171]
I assume that at some point exercises and/or tests will be updated. As a student it would be nice to get notified when exercises that I have submitted are updated. This would allow the student to ensure that their solution conforms to the updated version.  

Is this something that is in the works or possible?

**Comment by guygastineau** [comment]
That's a good question for a feature that would be amazing to have.

I think many tracks are lacking a system for keeping track of the test versions currently, and this could be a huge roadblock for test update notifications.

Perhaps there is a way to do this by having a standardized location across tracks for keeping track of version information.

We have a solution for that in bash and Ruby has one too, but I think we keep them in different places.  The one for the ruby track is also more controlled.

**Comment by NobbZ** [comment]
In theory, this place is called “git history”, and it should be easy to discover if the testfiles of an exercise have changed since the commit SHA thats in the database for his solution.

The problem with this is, that after a student has downloaded an exercise for the first time, it will be fixed to exactly that SHA forever. The student will not be able to update the tests at all.

At least this is the status quo.

**Comment by guygastineau** [comment]
@NobbZ 

I have heard what you are saying before.

It confuses me a little bit, because as I've been updating exercises for the bash track other students and I have been able to get the new tests with a simple `exercism download` for the solution.

Do you know how old your information is?

**Comment by mikewalker** [comment]
It sounds like the student is stuck with the version of the exercises that they have solved. Even if we can't update it would be nice if we had a way easily determine which exercises have been updated. The student could perhaps force the download of the new version, and merge there old solution into the new exercise if it stuff fits.

What I am thinking is that we could put some of the updating process and merging onto the student. The biggest issue of course is still going to be identifying which exercises among the exercises the student has completed have been updated.

I'm sure, there are a lot of complexities involved here. From a students perspective this would be a nice to have feature though. :)

**Comment by guygastineau** [comment]
I just checked to make sure.  I had an old version of the anagram_test.sh for the bash track.
I ran `exercism download -t bash -e anagram`
I got the new test in my directory.

I need to rework this exercise anyway.  After that I will submit and see if the test updates for me on the website too.  As of now without submitting again the test on the website looks like the old one for me.

**Comment by guygastineau** [comment]
I submitted my new solution and I can now confirm that the original test downloaded by a student will be the one that appears on the website with their solution.
The one that is downloaded is, however, the newest version anytime someone runs:
- `exercism download -t <track> -s <exercise_slug>`

**Comment by kytrinyx** [comment]
@guygastineau I'm confused about this. You said:

> The one that is downloaded is, however, the newest version anytime someone runs [...]

Given the following scenario:

- you unlocked an exercise and submitted a solution
- you deleted your local directory containing that exercise
- you downloaded it again using the `exercism download` command

You're saying that under these circumstances you get the _newest_ version of a test suite, not the version that was on master of the track repository at the time when you unlocked the exercise?

**Comment by guygastineau** [comment]
Yes, that is exactly right.

Also, I don't even need to delete the exercise directory if it was downloaded since the V2 release to get the test updates.

Let me know if you want any more clarification.

**Comment by kytrinyx** [comment]
Thanks @guygastineau. This is a bug, in that case.

The behavior _should_ be that once you've unlocked the exercise, any time you (or a mentor, or someone else) downloads your solution, they should get the test suite that was current at the time when you unlocked it.

Beyond this, it sounds like there's also a feature request in here: to allow a student to update their exercise to get the most recent version. This is a broader product discussion, and we would need to ensure that whichever iteration you download, you get the version of the test suite that was pinned when that solution was submitted.

And then it sounds like there's another feature request on top of this: to notify people when an exercise has changed. (Also a product discussion to be had).

**Comment by kytrinyx** [comment]
@guygastineau Getting a separate issue for each thing would be very valuable!

Let's keep #4213 and close this one -- and open two new issues for the two feature requests!
