### ISSUE TITLE
Exercism is downloading solution on beta Pharo track - how to stop it?

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4175]
Hi we're in the process of implementing the Pharo track (Smalltalk needs a bit of jiggery to play well with exercism as it doesn't normally use text files) - and we've almost got it there - however when I "download" the hello-world exercise it gives me both the test file and the solution file?

I am confused by this as config.json has a regex for solution_pattern, which appears to work as if you don't implement an exercise with a solution, the configlet linter complains. So what is the trick to just getting the test file? I also tried adding an ignored pattern but that didn't help either.  

My regex's look as follows (essentially, not something that ends with Tests.class.st):
```
"solution_pattern": "\\w+([^T][^e][^s][^t])\\.class\\.st",
 "ignored_pattern": "\\w+([^T][^e][^s][^t])\\.class\\.st",
 "test_pattern": "\\w+Test\\.class\\.st", 
```
Is this a side effect of being in "beta" mode? Or is there some subtlety we also need to take care of?

**Comment by NobbZ** [comment]
I've taken a look at the Pharo track directly. All files you have there are meant to be downloaded.

You have a testfiles and you have a stub file, what you are missing is an example file, which then is not to be downloaded. It is usually named `example.*`.

**Comment by macta** [comment]
Hi thanks - how does it decide what the example is called? I was hoping that the config.json specifying that the solution is <exercise>.class.st would steer it towards considering that as the example solution?

Its confusing to me - that configlet calls this a solution which you must provide, and which I wouldn't expect to get downloaded?

In Pharo/Smalltalk - where TDD originated, you don't provide a stub as the environment will create one for you when you get a failed test - so I don't want to provide one, and let people experience that for themselves.

Equally, I'm trying not to have to parse and rewrite lots of code to suite exercism - it should be flexible enough to handle this.

I'm currently trying to get a second exercise visible just to try this again - as its just possible that I'm getting the solution because I've tried the track and submitted a solution - albeit the wrong one in y experimentation (and so its downloading it).

Its a bit frustrating that there is no way for track developers to reset things themselves, to do proper testing.

**Comment by NobbZ** [comment]
I do see what you mean, it seems as if what is called `solution` by the `configlet` is actually called `example` everywhere else. I do assume, that the server does not read this key, but uses hardcoded `[Ee]xample` pattern (or uses a different key).

I'm not proficient in the websites codebase to quickly find which of both is true...

**Comment by NobbZ** [comment]
Okay, well, at least it is read from config:

https://github.com/exercism/website/blob/d41dbeb4dadc814329dfc0c6ab147adab881061d/app/models/git/exercism_repo.rb#L65-L68

And then it seems to be used here, to keep all files that match the regexp?

https://github.com/exercism/website/blob/7428e2138a1e52a56e2f2dbe50a06327a15a292a/app/models/git/exercise_reader.rb#L35-L48

Now I'm totally confused as well.

**Comment by macta** [comment]
It seems like I'm not going crazy then... hopefully someone can wade in and help me understand if its a bug, or if there is something i can configure better.

Meanwhile, I can't seem to try another example as the site thinks I've completed the track even though I've added a new core exercise.

**Comment by macta** [comment]
It looks like the ruby track gets around this by stuffing the solution in a .meta/solutions directory and then configuring the solutions regex to point to that .meta/solutions dir.

This is confusing though - either you have a regex's for solutions and ignored or you don't - it doesn't seem to honour them

**Comment by sshine** [comment]
@macta: Without having read this issue's details, has it been resolved in time?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
