### ISSUE TITLE
Strong/Bold on the new site is indistiguishable from normal text

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4179]
The stylesheet for exercism makes it very hard to see bold (`<strong>`) text.

Look at https://exercism.io/tracks/pharo/installation where it says NOTE: and Did you know - those are supposed to be bold, but in chrome I can hardly tell the difference.

I would expect them to be black like a Title (e.g. the name of an exercise).

This makes it difficult for us to highlight important information for students IMHO.

**Comment by PatrickMcSweeny** [comment]
[This bit of CSS](https://github.com/exercism/website/blob/master/app/assets/stylesheets/pages/generic-page.scss#L54) gives strong tags the same font weight as normal text, which kind of defeats the purpose of using them.

**Comment by sshine** [comment]
I believe that `<strong>` is quite visible now.

So much that they look like small headers.

If you'd like, you can change the `<em>` you use to `<strong>`.
