### ISSUE TITLE
Should some exercises have track-independent topics? If so, how?

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism#4186]
In https://github.com/exercism/exercism.io/issues/4110, it's decided that there are some exercises where *all implementing tracks* should have the `math` topic for those exercises.

How will this be maintained going forward? Suppose that a contributor now adds the affine-cipher to a track that didn't have it. Who or what (if anything) will tell that contributor that `math` should be one of its topics?

**Comment by petertseng** [comment]
It sounds like there may be a justifiable case for having a track-independent list of topics to be associated with each exercise.

Of course, tracks will may want to add their own track-specific topics; that is fine.

One may also wonder whether tracks may want to remove a track-independent topic. I have not yet thought of a exercise/topic/track triplet where removal is desired.

But track maintainers would have to be aware of such a thing, otherwise they will get confused about where their topics are coming from.

**Comment by rpottsoh** [comment]
@rpottsoh: [said](https://github.com/exercism/exercism.io/issues/4110#issuecomment-410418472);

> Perhaps comments should be added to all the testdata files that have been identified as mathy. Seems like we need to establish a policy for identifying new exercises as mathy going forward.

@kytrinyx  [said](https://github.com/exercism/exercism.io/issues/4110#issuecomment-410454838):

> Yes, we'll need a way to ensure that exercises get their canonical topics. I'll think on it.

**Comment by kytrinyx** [comment]
I actually think this would make sense to keep in the `metadata.yml` file.

**Comment by petertseng** [comment]
A point in favour of track-independent topics: Saves individual tracks' maintainers and contributors from having to make potentially duplicate decisions regarding those topics.

Let's say these topics go in `metadata.yml`, which I'd find an eminently reasonable place for them.

The next question would be: How would these get propagated to individual tracks?

* Tracks do NOT include these topics in their config.json. Instead, the website merges metadata.yml topics (track-independent) with the config.json topics (track-specific).
    * Less duplication
    * Possibly more confusing. A person reading config.json might be confused about where the track-independent topics are coming from, if the reader is unaware of that.
    * Creates another point where individual tracks depend on problem-specifications, and I was under the impression that generating READMEs was meant to move in the direction of removing those dependencies. Then again, in https://github.com/exercism/exercism/issues/4183 w/ non-default capitalisation/punctuation a dependence on metadata.yml got accepted, so apparently this is okay.
* Tracks DO include these topics in their config.json, possibly with machine assistance.
    * Pros/cons are pretty much the exact opposite of the above, so I won't rehash

**Comment by kytrinyx** [comment]
Ok, I think it sounds like `metadata.yml` is a good place.

I tentatively prefer the second option, of adding the topics in their config. That means that they can exclude topics if they think that makes more sense, and it's more explicit. We could add machine assistance if we want to, but I think that for now the one-time cost for maintainers when adding a new exercise is quite low.

**Comment by sshine** [comment]
Depending on what it is topics describe, some topics may be track-independent and others may be track-dependent.

For example, I just changed topics in "RNA Transcription" in exercism/haskell#762 from `maybe` to `either`, both Haskell terms. (`either` is called `result` in Ocaml.)

Some tracks may choose that "RNA Transcription" is not the place to introduce error handling.

A track-independent topic may be be `error-handling`, but like there is `exceptions`, an appropriate track-independent sub-category could be `error-aware-return-types`.

I think we should either not enforce that tracks have any external consistency in topics, or make sure that TOPICS.txt has coverage and provide a commit hook that helps contributers pick valid topics. And still allow for the selection of topics to vary between tracks.

I have no vision for topics, so I can't decide.

**Comment by kytrinyx** [comment]
> some topics may be track-independent and others may be track-dependent.

Yepp, that's exactly right. This is the reason I'd prefer it to not be automated.

I don't think we should enforce consistency, just have the tooling to make consistency easy. My gut sense is that if we do the work to assign topics and work with them / use them for a while, we'll get a better idea of what we need.

We _may_ want a very small number of topics to be enforced (the only one I can think of right now is `math`, and this is only because we want to ensure that math-y exercises are never core exercises on a track), but I don't think we need to do a lot off work on that right now. We have bigger fish to fry :)

For the metadata yaml, we can have an optional parameter `required` for each topic so that it defaults to `false` when not present.

**Comment by kytrinyx** [comment]
@sshine ... Haskell _might_ be an outlier when it comes to mathiness. That said, I actually do think that it would be worth moving these out to be side exercises, as there are almost certainly a decent subset of folks who would be absolutely fine with the _functional_ side of things and still feel intimidated by the math side of things.

**Comment by petertseng** [comment]
Since it is likely that this will go in problem-specifications: If it does, I suggest it be added to the section of the CONTRIBUTING.md added by https://github.com/exercism/problem-specifications/pull/1406 (or whenever that documentation has moved to, if it has moved by the time this plan is implemented).

That section is attempting to list the ways in which individual tracks might be dependent on problem-specifications. Currently the only one I know of is a non-default `title`. This would be another dependency, so I'd like it listed along with the other dependencies.

**Comment by kytrinyx** [comment]
I agree, that would be a good place for this.

**Comment by sshine** [comment]
Closing this issue as the answer is yes.

@petertseng: You suggest that we add a section in CONTRIBUTING.md that lists how tracks depend on problem-specifications. Do you mean ways in which tracks can attain independence from problem-specifications? The example you give is a non-default `title`, and using topics not listed in TOPICS.txt is another. Perhaps we should wait until exercism/problem-specifications#1560 resolves.

**Comment by petertseng** [comment]
> You suggest that we add a section in CONTRIBUTING.md that lists how tracks depend on problem-specifications. Do you mean ways in which tracks can attain independence from problem-specifications?

It reads like that's a possible rephrasing of what I said approached from another angle. I can try to rephrase to explain how I connect what the two of us said.

Currently, for **the website** to be able to serve a track as it was intended, having a copy of the track repo is not sufficient. For at https://exercism.io/my/tracks/haskell, the exercise with the slug `etl` is displayed at "ETL" instead of "Etl" as it would have been by default. For the website to know that `etl` should be displayed as "ETL", it is necessary for the website to have a copy of problem-specifications. If the website maintainers wished for the website to no longer need a copy of problem-specifications to properly serve each track (the aforementioned *independence*), the information mapping `etl` to "ETL" would have to go elsewhere.

How does this apply to this issue?

Since the decision is that the final arbiter of topics is `config.json` and not anything in problem-specifications (even if problem-specifications will eventually make suggestions and/or requirements), the website will remain able to get its topics from `config.json` and not problem-specifications. Thus, this issue does not add another dependency on problem-specifications. 👍

**Comment by petertseng** [comment]
Note that it was correct to close this issue, having received its answer of "yes". This issue does not cover the implementation.

**Comment by petertseng** [comment]
EBWODP: I place my trust in the interested parties to open the appropriate issues (not yet opened) regarding implementation, and do not presume to dictate when those parties should open those issues.
