### ISSUE TITLE
markdown input box treats `---` as start of an enumeration

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4188]
when I want to set a horizontal ruler in a comment via putting at least three dashes on a single line (`---`) and hit enter thereafter to get into a new line, then the box starts the newline with a dash and a space (`- `).

The latter is equivalent to `* ` in markdown and marks a bulletpoint in an enumeration.

**Comment by iHiD** [comment]
@kntsoriano This might be something you can solve quickly, but might just be a limitation of the text-editor we're using. If you can't see an easy fix within 30mins, then let's not worry about it for now.

**Comment by iHiD** [comment]
@NobbZ This got fixed.
