### ISSUE TITLE
new Pharo track can't seem to create new exercises to test with? (stuck at 1)

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4189]
I thought there was a problem adding new exercises after a user had completed everything (it just says success and never lets you continue) - however I created a new user and it just shows 1 exercise available even though there are 3 in the config.json?

No matter what I do, I can't seem to get it to recognise the new exercises? the configlet linter is recognising them in travis - so why doesn't exercism? Is it broken globally - or is it somethingi about new tracks that aren't online yet? Or is my config wrong somehow? Help?

**Comment by iHiD** [comment]
@kntsoriano Could you have a look at this pls?

**Comment by iHiD** [comment]
See https://exercism-team.slack.com/archives/GC3K95MRR/p1533648701000447

**Comment by iHiD** [comment]
Maybe related to https://github.com/exercism/exercism.io/issues/4193 (no idea but it might be)

**Comment by kntsoriano** [comment]
@macta The Pharo track should have three exercises now. Could you check if this is correct?

**Comment by macta** [comment]
Yes - that’s fixed it! Thnx
