### ISSUE TITLE
ActiveRecord::StatementInvalid in my/user_tracks#leave

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4191]
## Error in Exercism V2

**ActiveRecord::StatementInvalid** in **my/user_tracks#leave**
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`exercism`.`reactions`, CONSTRAINT `fk_rails_51c7d8b8ad` FOREIGN KEY (`solution_id`) REFERENCES `solutions` (`id`)): DELETE FROM `solutions` WHERE `solutions`.`id` = 24699

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b695dd49c5395001831f1cb?event_id=5b69612e0028ca79e3f00000&i=gh&m=ci)

## Stacktrace

    app/controllers/my/user_tracks_controller.rb:40 - block in leave
    app/controllers/my/user_tracks_controller.rb:39 - leave

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b695dd49c5395001831f1cb?event_id=5b69612e0028ca79e3f00000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by kntsoriano** [comment]
The fix wasn't deployed, thus leading the error to be raised again.
