### ISSUE TITLE
ActiveRecord::RecordInvalid in git:sync

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4193]
## Error in Exercism V2

**ActiveRecord::RecordInvalid** in **git:sync**
Validation failed: Name can't be blank

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b6553cc15318500185e84ce?event_id=5b697f530028d338ab390000&i=gh&m=ci)

## Stacktrace

    app/services/git/syncs_mentors.rb:48 - block in upsert_mentor!
    app/services/git/syncs_mentors.rb:40 - tap
    app/services/git/syncs_mentors.rb:40 - upsert_mentor!
    app/services/git/syncs_mentors.rb:22 - block in upsert_mentors!
    app/services/git/syncs_mentors.rb:21 - map
    app/services/git/syncs_mentors.rb:21 - upsert_mentors!
    app/services/git/syncs_mentors.rb:16 - sync_mentors!
    app/services/git/syncs_mentors.rb:9 - call
    app/services/git/syncs_website_copy.rb:5 - call
    app/jobs/sync_repo_update_job.rb:24 - sync_repo!
    app/jobs/sync_repo_update_job.rb:12 - perform
    app/services/git/syncs_updated_repos.rb:25 - block in sync
    app/services/git/syncs_updated_repos.rb:25 - sync
    app/services/git/syncs_updated_repos.rb:18 - block in run
    app/services/git/syncs_updated_repos.rb:17 - loop
    app/services/git/syncs_updated_repos.rb:17 - run
    app/services/git/syncs_updated_repos.rb:5 - run
    lib/tasks/git.rake:10 - block (2 levels) in <main>

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b6553cc15318500185e84ce?event_id=5b697f530028d338ab390000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by kntsoriano** [comment]
Fixed according to Bugsnag.
