### ISSUE TITLE
Track progress bar should reflect unusually ordered exercises

### ISSUE THREAD

**Issue by tychota** [exercism/exercism#4199]
When I'm looking at https://exercism.io/my/solutions/ca1740aadcea45beaf97623ccdc87568
I see:

![image](https://user-images.githubusercontent.com/13785185/43780540-1d887b7c-9a5b-11e8-8b5e-65b2e4851a83.png)

I find the progress rather confusing:
- first round is green and full
- next two rounds are disabled
- fourth round is green border and white inside

As a new user I don't catch up what that means.

I'n comparison this is way clearer:

![image](https://user-images.githubusercontent.com/13785185/43780744-9b6c3f38-9a5b-11e8-928a-c526614b315f.png)

**Comment by NobbZ** [comment]
Can you please tell which tracks you made those screenshots from?

**Comment by iHiD** [comment]
And whether these are new tracks or tracks that have been around for a while pls?

**Comment by iHiD** [comment]
Two things could probably cause this:
1. A legacy track (where exercises appear out of order)
2. A normal track where the exercises have been reordered by the maintainers.

@jackhughesweb Could you have a think about how best to solve this pls. Ping me on Slack if you want to discuss as it might require some extra knowledge.

**Comment by tychota** [comment]
Sorry for not answering. I was in vacation and didn't get any notifications. Glad it is fixed.
