### ISSUE TITLE
Web editor

### ISSUE THREAD

**Issue by LoganDark** [exercism/exercism#4203]
I have read:
- #494
- #2191

---

This idea was first thrown around YEARS ago. Apparently, your solution was to make the tool easier to install. Sure, it's easy to install. However, the current process of doing an Exercism exercise is still:

- Download the Exercism toolkit
- Run a command in the terminal to download it
- Open an editor
- Find the exercise file in your editor (this can be surprisingly difficult)
- Install dependencies
- Enable all tests
- Figure out the solution
- Go back to the terminal
- Run the command to submit your solution

...
...
...
...
...

Programmers are lazy people.

I am a lazy person.

I do not like this.

I would like a simpler method of completing Exercism exercises than this.

I'm sure many others would agree that these steps are better than what I listed above:

- Click an edit button
- Edit code immediately
- Click a button to run tests, if they all pass then click Submit

This would be a huge convenience to everyone, especially beginners. Thoughts?

**Comment by LoganDark** [comment]
> Last but not least, you only install the CLI tool once. After it is installed you can download the exercises immediately.

Fine, eliminate one step. There's still the hassle of running the commands, setting up your editor for the project, etc.

I understand some people prefer their local editor despite the tedious process of setting everything up, but there is not even an _option_ for those who prefer to click a button, edit code immediately, hit submit and be done.

**Comment by NobbZ** [comment]
Well another problem were that its close to impossible to maintain the necessary infrastructure for more than 50 tracks to run the tests online.

It was said once we have an average of 1500 submissions a day. If those were all done in a web editor and tested online, that would result in much more than 1500 testruns, as a student usually runs the tests multiple times before he finishes his assignment.

Some languages do even require you to have special tooling, only available on certain platforms, eg Delphi.

Also the WEB-UI eliminates the freedom of using as many files one likes.

And believe me, learning the tools around a language with the language is worth the hassle.

If though its mainly the problem to figure out the name of a file, then this is a problem with the track. Most of them have agreed on using the exercises name, cased (snake-, camel-, or kebap-cased) according to the idioms of the language as the entrypoint of your script, of course adding the languages file ending.

**Comment by LoganDark** [comment]
> kebap-cased

~kthen~

Anyway, yes, this would likely take a long time and lots of work. This is a suggestion, not an order. Things can take time.

The platform wouldn't matter because the tests, compiling, etc. would be done on the server.

**Comment by NobbZ** [comment]
I'm not sure what you mean by “~kthen~”.

And I never understood this as an order, I just explained why things are as they are and wont be changed. During the last one or two month there was already a similar question, which was turned down with words similar like these: “this is how exercism works, if you do not like it there are alternatives that have a web ui, move on and use those”, but I can not find it anymore, I had linked it…

And of course does the platform matter, delphi is only available for windows, so we would need a windows server only for that single track. Perhaps there are tracks which language is only available on MacOS? I've never seen MacOS hosting…

**Comment by LoganDark** [comment]
"~kthen~" means you made a typo. :p

> And of course does the platform matter

> delphi is only available for windows, so we would need a windows server only for that single track. Perhaps there are tracks which language is only available on MacOS? I've never seen MacOS hosting

https://www.lmgtfy.com/?q=macos+vps

**Comment by iHiD** [comment]
@LoganDark Thanks for opening this issue and your suggestions. As @NobbZ said, this isn't something that's going to happen in the short term as it is immensely challenging from technical, logistic and financial POVs.

If you're going to contribute to Exercism (including opening issues here) can you please familiarise yourself with our [Code of Conduct](https://exercism.io/code-of-conduct). Things such as posting `lmgtfy` links and commenting on typos is patronising and rude. If an experienced developer like @NobbZ says "I've never seen MacOS hosting" then they are probably making a point that that's a pretty unusual thing which will involve a lot of support and maintenance. By dismissing it in a patronising way, it just comes across like you've not considered those tradeoffs, and reflects badly on you. It benefits no-one.

Thank you.

**Comment by LoganDark** [comment]
> As @NobbZ said, this isn't something that's going to happen in the short term as it is immensely challenging from technical, logistic and financial POVs.

I understand that. If you read my posts, you would know that.

Thank you for your feedback.

Now please leave me alone.
