### ISSUE TITLE
Exercise README is not updated

### ISSUE THREAD

**Issue by ZapAnton** [exercism/exercism#4204]
As of exercism/rust#586 the commands to download the exercises have been updated for the new version
of CLI in the `luhn-from` and `luhn-trait` exercises of the Rust track.

Ten days later and it seems like website still renders the old version:

![image](https://user-images.githubusercontent.com/8658767/43836492-30fb6c82-9b1e-11e8-8c5c-8df1065ddfc6.png)

**Comment by kntsoriano** [comment]
@ZapAnton I've checked the website and it seems that the instructions have updated. Could you check if I haven't missed anything?

**Comment by ZapAnton** [comment]
I have checked `luhn-from` and `luhn-trait` READMEs and they are still old.
Perhaps the problem is about the exercise's state?
I am checking the READMEs in the independent mode and I have already completed the exercises.
Don't know if this helps but here are the links:
- [luhn-trait](https://exercism.io/my/solutions/26d6307ec9ab4005b2619d16404dd2ec)
- [luhn-from](https://exercism.io/my/solutions/33e5788d3b604d97831f6893c3a480f2)

**Comment by ZapAnton** [comment]
I have checked the READMEs using other account and they are updated.
So maybe there is indeed a problem on my end

**Comment by kntsoriano** [comment]
@ZapAnton I think that the instructions showed to you are based on what version you've done the exercise with. @iHiD Is this correct?

**Comment by NobbZ** [comment]
Yes, this is correct. Exercises READMEs, tests and other auxiliary files should be pinned to the version that was current when **downloading** the exercise for the first time.

There have been bugs around this earlier, but those have been fixed now and the documents displayed on the webpage have never been affected by this bug and have been displayed in the fixed version always.
