### ISSUE TITLE
Allow tracks to customise the download instructions

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4209]
For less "file based" languages - or those that use a common IDE, its useful to customise the download instructions as you may not need to use the exercism cli, but instead a plugin in the environment itself.

this makes it less confusing for students if they get the right instructions (e.g. Pharo is not strictly file based - we've re-used some git infrastructure to play well with exercism, but we don't expect users to use the cli, but simply enter exercise names into a menu in the IDE).

**Comment by rpottsoh** [comment]
For now I think all you can do is create your own plugin that makes the necessary calls to the CLI for the student.  Once the API (what the CLI uses) has been published your plugin could then be updated to completely assume the roll of the CLI.

**Comment by iHiD** [comment]
Related to https://github.com/exercism/exercism/issues/4087

**Comment by macta** [comment]
My point is that if you create your own plugin - the instructions on the site will still point you to the exercism cli - so you have to hope users will properly read your installation guide and in subsequent exercises will remember what they read.

**Comment by rpottsoh** [comment]
You could always add a `hint` comment to the top of the first few exercises testsuites to advertise the availability of a plugin.  Include the link back the installation instructions, https://exercism.io/tracks/pharo/installation

The installation instructions should cover those people that are new to the track and the language it is teaching.  Those that are joining the track, and may already have tools in place, may opt to skip the installation instructions.  You would hope they would at least read them once just to make sure that everything they have conceived of for their setup is in line with what the track maintainers have envisioned. :+1:  I know, a lot people don't like to read instructions first. :-1: 

Installation instructions are always available on each track's site page.

**Comment by macta** [comment]
The hint is a good idea - and very pretty doable to try it out anyway.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
