### ISSUE TITLE
The exercise you are submitting doesn't have the necessary metadata

### ISSUE THREAD

**Issue by redhatmk** [exercism/exercism#4214]
Hello,

I'm trying to submit a file but I'm getting this error:

```
Error: 

    The exercise you are submitting doesn't have the necessary metadata.
    Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.
```
I re-installed the client following this [instructions](https://exercism.io/cli-walkthrough) but still getting the same error above. Any of you knows what can I do to fix this issue?

I'll really appreciate your help.

**Comment by rpottsoh** [comment]
It sounds like you are trying to upload an exercise that was not first downloaded from the v2 site.  It sounds like you first downloaded it prior to the new site being released, meaning you fetched (downloaded) the exercise from the old site with the old CLI.  If you follow the directions provided at https://exercism.io/cli-v1-to-v2 you should be fine.  Read the whole thing.  Making sure the CLI is current is only part of the issue.

**Comment by redhatmk** [comment]
This is the version of the client I'm using:

```
exercism version 3.0.6
```

This is the url from the config:

```
API Base URL:  (-a, --api)        https://api.exercism.io/v1
```
I have follow the instructions in [https://exercism.io/cli-v1-to-v2](https://exercism.io/cli-v1-to-v2)

I have use this ways to submit my code:

```
exercism submit SpaceAge.swift
```

and
 
```
 exercism submit /Volumes/<path>/SpaceAge.swift
```
I'm missing something?

**Comment by NobbZ** [comment]
Yes, you are missing to delete and redownload it, as described in the guide that was linked quite a few times. If though you have redownloaded that exercise and it still does not work, state so explicitely.

"I followed the guide at XYZ" doesn't count for me, as I've written this multiple times, just to realise at the end of the discussion that I skipped a step because I haven't seen it or thought it were unimportant.

**Comment by rpottsoh** [comment]
That doesn't look correct.  Try
```
exercism download --exercise=spaceage --track=swift
```

**Comment by redhatmk** [comment]
The instructions are wrong

it should be

```
exercism download --exercise=THE_EXERCISE --track=Language
```

In this particular case the command it worked is:

```
exercism download --exercise=Space-Age --track=Swift
```

**Comment by NobbZ** [comment]
That is what is written in the instructions...
