### ISSUE TITLE
When I sign out of exercism - get page not found?

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4216]
When I sign out - I get a msg "Oh dear, we can't find that page. Sorry about that.
Continue by heading back to the homepage." for the url : https://exercism.io/users/sign_out

**Comment by iHiD** [comment]
Is this reproducible every time for you?

**Comment by macta** [comment]
Yes - with different user names too - I pick logout in the top corner and then that url gives me the message indicated.

**Comment by seanknox** [comment]
Confirmed that I also get a 404 on the sign out link.

**Comment by PatrickMcSweeny** [comment]
The sign out link sends a DELETE request so linking to it from here or anywhere else sends a GET request, thus the 'Not found' message. @macta, are you opening the link in a new tab? That is the only way I am able to reproduce the bug myself. If I click the sign out link inside of the same tab, it works fine.

**Comment by macta** [comment]
Nope, I’m on an exercise and pick my profile menu (top right) and pick sign out. I get that page

I think someone else confirmed it too.

**Comment by macta** [comment]
Actually, I tried again today - and it doesn't seem to do it anymore both with a github login and email address login - so maybe something changed?
