### ISSUE TITLE
Reacting to you own solution

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4217]
I can currently react to one of my own solutions, and thus mark it as being "Genius" :) See exercise  
https://exercism.io/tracks/csharp/exercises/bob/solutions/c47e972bd190206351c30978

I don't think we should be able to do this :)

**Comment by sshine** [comment]
I really don't see the problem here. :-D

Social networks generally allow you to like your own things. It's just gimmicky.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
