### ISSUE TITLE
Feature Request: let students get test updates

### ISSUE THREAD

**Issue by guygastineau** [exercism/exercism#4219]
I believe this should be an: if/when they want, in other words, of their own volition kind of feature.

This was originally discussed in connection with this bug: #4213

**Comment by guygastineau** [comment]
related to this bug  #4213

**Comment by Insti** [comment]
Still no progress on this? Is there any way for me to get updated versions of the test suite for an exercise?

**Comment by iHiD** [comment]
For now: Create a second user for "maintainer testing". Start track in Independent mode. Start an exercise to see test suite. Then leave the track and rejoin it then start the exercise again to see the new version. Etc.

**Comment by Insti** [comment]
What about me, as a student, who just wants the updated test suite?

**Comment by NobbZ** [comment]
Until this get fixed, we (students) won't be able to update the testsuite.

The only thing we could do is to download from the repository, and update the implementation accordingly.

But we (mentors) won't see the updated tests then…

We (students) won't be able though to re-request mentorship for those updated exercises.

So as you can see there are a lot of things to sort out first, to make it happen. But yes, I'd like to have the possibility as well.

**Comment by bdjnk** [comment]
I'd like to suggest being more aggressive about updating test suites.

I'd prefer that downloading a exercise would automatically update the test suite (if you've already solved the exercise against an earlier iteration of it) with a message letting you know this occurred.

I'd also prefer not allowing submission against an outdated test suite.

It seems to me worthwhile to keep everyone up to date and working against the same set of requirements.

**Comment by Insti** [comment]
It is also a problem that the README is not updated so bug fixes/clarifications are never displayed to the student.

**Comment by tmccombs** [comment]
As a student, when I download a new exercise, that I haven't downloaded before, I seem to get an old version. I think maybe I'm getting the version from when I started the track instead of the version from when I first download the exercise. 

I understand why it should download an older version for an exercise I've already started, but it seems odd to download older versions for exercises I haven't downloaded before. This is particularly problematic for the Julia track, where I'm getting old test that still use `use Base.Test` which doesn't compile in Julia 1.0

**Comment by iHiD** [comment]
This last point was a bug which has been fixed FYI.

**Comment by iHiD** [comment]
> I'd also prefer not allowing submission against an outdated test suite.

As a user, this would annoy me so much though. If I'd just downloaded and solved an exercise, then go to submit it and I'm told the requirements have changed.

> It seems to me worthwhile to keep everyone up to date and working against the same set of requirements.

I agree with this in principle, but I don't get the practical route forward that doesn't provide an unexpected user experience.

**Comment by bdjnk** [comment]
> > I'd also prefer not allowing submission against an outdated test suite.
>
> As a user, this would annoy me so much though. If I'd just downloaded and solved an exercise, then go to submit it and I'm told the requirements have changed.

While this might be unexpected and potentially irritating it would also be rare, and the reality is *the requirements **have** changed* and I would prefer to face that upfront than find out later I'm out of date and out of sync.

I would be fine with a compromise where submission is allowed but a warning is given that the test suite is outdated and detailing a way to update it.

**Comment by iHiD** [comment]
> I would be fine with a compromise where submission is allowed but a warning is given that the test suite is outdated and detailing a way to update it.

This is what I've done.
