### ISSUE TITLE
Exercises imported from independent mode not accepting solutions

### ISSUE THREAD

**Issue by seanknox** [exercism/exercism#4221]
I can't progress past the first few exercises in mentor mode. They were "imported from independent mode" and valid submissions apparently, but they're stuck as "in progress."

**Comment by iHiD** [comment]
I'm going to need some more details here. Could you post some of the error messages or screenshots you're seeing pls.

**Comment by seanknox** [comment]
Sure thing. Here's the Go track I'm on:

![exercism](https://user-images.githubusercontent.com/1231630/44005457-9ce9085c-9e28-11e8-8213-8ff9aa6e41e5.png)

Here's one of the exercises that was imported from independent mode:

![exercism](https://user-images.githubusercontent.com/1231630/44005470-c6caaf40-9e28-11e8-86cd-a3e4267c8edf.png)

**Comment by iHiD** [comment]
So from your screenshot, it looks like Raindrops has been approved by a mentor and so you can go there to complete that exercise, at which point you should be able to request mentoring for one of the other two solutions. Does that work?

**Comment by seanknox** [comment]
That makes sense. I didn't realize that mentors must look at solutions before allowing progression. Thanks!
