### ISSUE TITLE
Unapproved completion incorrectly shows extra exercises as unlocked

### ISSUE THREAD

**Issue by ivenk** [exercism/exercism#4223]
When clicking on the "Complete exercise (Unapproved)" button the text reads : 

> **you will not unlock this exercise's side exercises**
you'll no longer get mentor feedback on this exercise
you will be able to reactivate the exercise in the future

Despite this I still unlock all of the extra exercises.

<img width="599" alt="bildschirmfoto 2018-08-11 um 23 24 38" src="https://user-images.githubusercontent.com/33981703/43996190-b8d7f304-9dbd-11e8-8136-1940b0af981d.png">

**Comment by ivenk** [comment]
The first one is unlocked (left most). The others are locked and clicking on them brings me back to the same page.

<img width="635" alt="bildschirmfoto 2018-08-12 um 17 55 25" src="https://user-images.githubusercontent.com/33981703/44003792-1028cb92-9e59-11e8-9cd3-4fc18eb9e0f3.png">
<img width="717" alt="bildschirmfoto 2018-08-12 um 17 55 31" src="https://user-images.githubusercontent.com/33981703/44003793-11b4342e-9e59-11e8-963d-61b20441966f.png">

**Comment by ivenk** [comment]
Update: 
I submitted a new solution to the exercise and it got approved by a mentor. However the exercises still remain locked. 

This image shows the completed exercise and its extras. Clicking on every extra exercise except the first one brings me back to the same page.
<img width="633" alt="bildschirmfoto 2018-08-13 um 15 40 58" src="https://user-images.githubusercontent.com/33981703/44035219-47b6fdb6-9f0f-11e8-9a4f-d84454813199.png">

Checking my unlocked exercises shows that the extras are not actually unlocked.
<img width="1111" alt="bildschirmfoto 2018-08-13 um 15 41 12" src="https://user-images.githubusercontent.com/33981703/44035260-62fcf9e0-9f0f-11e8-8b61-bfebc6f3bc35.png">

**Comment by ivenk** [comment]
Okay great, thanks !

**Comment by kntsoriano** [comment]
@jackhughesweb I can work on this :) I'll unassign you from this issue.
