### ISSUE TITLE
[Markdown] Mentoring: Multiline code issue when using HEREDOC

### ISSUE THREAD

**Issue by budmc29** [exercism/exercism#4224]
Works fine on modern markdown processors (like Github's):
```bash
  local Usage <<ABC  
    Text here  
  ABC
```

<img width="590" alt="image" src="https://user-images.githubusercontent.com/7063792/44006461-bb87b502-9e7c-11e8-9624-8a59d71793a0.png">

<img width="584" alt="image" src="https://user-images.githubusercontent.com/7063792/44006463-c108e014-9e7c-11e8-8bc1-97261186c8a5.png">

**Comment by iHiD** [comment]
@budmc29 Got a solution uuid I work from pls?

**Comment by iHiD** [comment]
I believe this is now fixed. Old comments are being updated. If you could check you're happy with a new comment, that'd be great. Thanks :)

**Comment by budmc29** [comment]
Yes, looks like it's fixed, thanks.

**Comment by iHiD** [comment]
Great! :)
