### ISSUE TITLE
Regenerating exercises with a new template doesn't seem to update it on my track?

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4226]
I've tweaked the template we use for generating the readme files (to add some better download instructions for using the Pharo plugin).

The files I have checked in reflect this new change however on the site when I look at unfinished exercises they don't show the new changes? 

Is there some kind of cache timeout? The about.md file seems to update almost instantly when changed. Or is there some kind of versioning rule - in that I only see the same version of the instructions when I unlocked it (but then how do you fix an error?)

**Comment by guygastineau** [comment]
I think they are probably pinned to the hash of the version you downloaded.  Checkout #4213 and the closed issue mentioned there

**Comment by guygastineau** [comment]
Have you confirmed that they update for exercises you haven't started yet?

**Comment by macta** [comment]
Yes - a new exercise seems to get the changes. This seems like a harsh limitation if you make a typo o reed to add extra details to help unblock people.

**Comment by iHiD** [comment]
In the situation you describe it could be harsh. However, if the tests and readme changes halfway through someone doing an exercise, and then everything is different for them, that would be very confusing, which is why this restriction is there. This was something the maintainers very actively wanted.

**Comment by iHiD** [comment]
It fixes the version when you unlock it, not download it.

**Comment by guygastineau** [comment]
That is Interesting.  Seemingly undefined behavior in the go template might be something people want to know about.  It should be completely unrelated to how readmes are displayed on the website though.

**Comment by macta** [comment]
@iHiD well then maybe there is a caching bug? Regenerating my readme files should show new content - if you are caching do you hash the content somehow (which should be different now that I've removed CR's from the go template).

**Comment by macta** [comment]
e.g. https://exercism.io/my/solutions/8b647b5848fe4ca0995bc8738af004c3 (not sure if there is a way to expose a public URL to this) - is showing 3 paragraphs in the Downloading section - however the readme.md file has only a single paragraph and if you view it in github its showing correctly on master?

**Comment by macta** [comment]
@iHiD so in unmentored mode - what unlocks it - just publishing a new exercises that would be unlocked for unmentored folks? This makes it incredibly frustrating for new track developers - the act of seeing something with no way to better control how you can see it to test it means you can't easily refine things to make them look good. I find this all very frustrating - it really needs to work better.

**Comment by iHiD** [comment]
@macta When an exercise is unlocked it's README and Test Suite are locked to the git sha at that point in time. This is a feature that was heavily requested previously.

I appreciate that you're finding it frustrating to test these things and as I've said before I'm sorry that that's the case. However, the act of building a whole set of extra modes for maintainers that change all the rules is not something I can do overnight. I'm a volunteer working on this in my spare time too, and I'm working through hundreds of issues affecting lots of people - I think I'm submitted about 250 pull requests in the last 3 weeks. Things will get better over time, but I don't have some way of improving this without dedicating lots of time too it, which is the one thing I don't have right now.

As I've said before, the easiest solution right now is to leave the track and start it again, which while frustrating, is only 2 or 3 button clicks. If you do that in independent mode then you don't need to worry about progression or unlocking to be able to see things.

**Comment by macta** [comment]
@iHiD for the uninitiated its not so obvious that these are all related things - it never occurred to me that it would be designed this way and that leaving a track would also affect/reset the documentation you see. I think there are a few lessons to be learned from all this... but one might be to document it slightly better so that newcomers aren't scratching their heads getting frustrated.

Anyway - yes, I'll leave the track again and in unmentored mode can review how the templates are looking.

**Comment by kytrinyx** [comment]
> one might be to document it slightly better so that newcomers aren't scratching their heads getting frustrated

@macta the current state of the documentation is my fault--we've been snowed under with everything going on, and I've still not got the bandwidth to sort it out (need to fix some CLI bugs before I can tackle it). I've put documentation as my top priority after the CLI, and I expect to spend most of September focusing on it (I have a day job, so when I say most of September I mean nights and weekends).

**Comment by macta** [comment]
@kytrinyx I guess the silver lining is that you can see where we got stuck/frustrated and document those bits. I dont think you need a ton of docs that will only get outdated - just something about the flow. Possibly the end to end user journey and what a track contributes to make that possible eg when a user comes to exercism they see languages which is due to every track having a logo in track/img/icon.png that has been registered in exercism (submit an issue to do this), and a summery description in config.json.

When a user drills down on a track, they see
/docs/About.md as well a tiny code snippet from /docs/snippet.txt. Etc.

Just an idea anyway.

I suppose my biggest frustration has been in the difficulties in testing this flow as we’ve sorted things out - and want to check how they look/function.


 more

**Comment by kytrinyx** [comment]
> I suppose my biggest frustration has been in the difficulties in testing this flow as we’ve sorted things out

@macta that makes a ton of sense--this was not made any easier for you seeing as Pharo is the first track to develop in beta on the new site, _just_ as we've been scrambling to figure out the rough edges on the user-facing side.

> I dont think you need a ton of docs that will only get outdated - just something about the flow.

I think you're probably right--I just need a few hours of calm to actually dig in!
