### ISSUE TITLE
Should notify people the right way to check exercism CLI version.

### ISSUE THREAD

**Issue by kenshinji** [exercism/exercism#4227]
In your website it says you should check `exercism` version by `exercise version`, however it should be `exercism --version`
<img width="215" alt="screen shot 2018-08-13 at 12 21 55" src="https://user-images.githubusercontent.com/1403893/44012683-81cddc20-9ef3-11e8-9abc-486090b818b2.png">
<img width="215" alt="screen shot 2018-08-13 at 12 21 38" src="https://user-images.githubusercontent.com/1403893/44012684-82007478-9ef3-11e8-9b5e-c32fdc637dbf.png">

<img width="464" alt="screen shot 2018-08-13 at 12 19 17" src="https://user-images.githubusercontent.com/1403893/44012643-29fe7342-9ef3-11e8-9109-48d3ff8bfa82.png">

**Comment by NobbZ** [comment]
The instructions are for version 3 of the CLI. Since your exercism reports 2.4.1, you got a really old version installed. If you are on Linux `exercism upgrade` should just work.

If you get permission errors during upgrade, you have probably installed the old version using a package manager, in this case you should remove it first and install as described in the instructions

**Comment by kenshinji** [comment]
@NobbZ yeah, it works after I ran `exercism upgrade`. Since I installed exercism CLI tool through Homebrew, I guess the release on Homebrew should be upgraded?

**Comment by iHiD** [comment]
@kenshinji The package on Homebrew is up to date, so I think maybe your Homebrew is out of date?

```
iHiD@iHiD~/Projects/work/reachora/api: brew list exercism
/usr/local/Cellar/exercism/3.0.6/bin/exercism
```

**Comment by kenshinji** [comment]
@iHiD Here is my brew version info

```
~ ⌚ 10:16:29
$ brew -v                                                                                                                                                                                      ‹ruby-2.4.2›
Homebrew 1.7.1
Homebrew/homebrew-core (git revision bda60; last commit 2018-08-13)

~ ⌚ 10:16:35
$ brew info exercism                                                                                                                                                                           ‹ruby-2.4.2›
exercism: stable 3.0.6 (bottled), HEAD
Command-line tool to interact with exercism.io
https://cli.exercism.io/
/usr/local/Cellar/exercism/2.4.1 (6 files, 8.8MB) *
  Poured from bottle on 2018-03-05 at 12:04:42
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/exercism.rb
==> Dependencies
Build: dep ✘, go ✘
==> Options
--HEAD
	Install HEAD version
```

**Comment by NobbZ** [comment]
Then there is probably an older version of exercism earlier in your path.

```sh
for e in $(which exercism -a); do
  printf "Path: %s; Version: %s\n" $e $(exercism version || exercism --version)
done
```

Please provide output of that little script.

It's typed on a mobile though and therefore untested.

**Comment by iHiD** [comment]
Can this be closed?

**Comment by kenshinji** [comment]
@iHiD closing.
