### ISSUE TITLE
exercise_readme.go.tmpl interprits new lines strangely

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4228]
The template file exercise_readme.go.tmpl doesn't seem to work like the docs files - any new CR in the text will cause a new paragraph to be generated on the site.

This is a little unexpected - but not sure if this is simply the GO way? It should probably be noted a bit more clearly (or fixed if possible). I would expect double new lines to generate a new paragraph.

The implication is that you need to turn softwraps on in your editor.

**Comment by sshine** [comment]
@macta: Can you tell me if this problem persists?

I'm usure if I understand the problem description correctly. Haskell's [`config/exercise_readme.go.tmpl`](https://github.com/exercism/haskell/blob/master/config/exercise_readme.go.tmpl) contains single linebreaks that are interpreted softly when converted to Markdown in the README. Could this be a bug related to CRLF being interpreted as two linebreaks maybe?

**Comment by sshine** [comment]
Closing this issue due to lack of response.
