### ISSUE TITLE
My data is not available after migration

### ISSUE THREAD

**Issue by gregmcaree** [exercism/exercism#4232]
Hi,

Prior to migration I logged onto exercism.io using the log in using git-hub option. user id: greg.mcaree369@gmail.com

Now I am unable to log in using this method and had to create a new account where I was able to do this using the same user id.

This means that I don't now have access to all of my previous solutions. There are around 23 in the Clojure track that I would be interested in recovering. I have also checked my email is verified on github and that excercism has access privileges.

Please refer to the email trail between hello@exercism.io, jeremy@exercism.io and greg.mcaree369@gmail.com

Is my data retrievable and can you add it to my new account? 

Kind Regards,
Greg

**Comment by rpottsoh** [comment]
Have you tried logging in by clicking the `with GitHub` button?

Assuming you get logged in to your old account make sure you read up on upgrading the CLI to the latest version:
https://exercism.io/cli

and follow these instructions https://github.com/exercism/website-copy/blob/master/pages/cli_v1_to_v2.md

**Comment by gregmcaree** [comment]
Hi Ryan
Yes , have installed new client and can submit exercises where I have
started on the java tract.
My problem is when I use the login via github button. I am denied access.
I have synced my passwords, made sure exercise is granted access to my
account on github, endured that github only has one primary email account
set up which corresponds to the exercise email but still can't get in.
Can you tell me if the data from the old closure tract still exists?
Thanks,
Greg

**Comment by rpottsoh** [comment]
> Can you tell me if the data from the old closure tract still exists?

@iHiD or @kytrinyx would you shed some light on @gregmcaree question and offer any insight into is login woes?

thanks

**Comment by iHiD** [comment]
All your data is still there. 

I just don't understand why you can't log in. This is the only situation where we've have this problem :(

Could you try revoking the Exercism oauth app on GitHub and then signing in using GitHub on Exercism pls?

**Comment by sshine** [comment]
Hi @gregmcaree: Do you still have an interest in getting back into your Exercism account?

If this is the case, then following the instructions of revoking OAuth access might help us detect similar problems of other unreported cases.

**Comment by gregmcaree** [comment]
Hi Simon,

I can get into my account no problem. The issue is that there are a number
of solutions from the Clojure track which are not available to me.

This occurred after the application migrated to a new platform.

If I go ahead and revoke OAuth access are you saying I may be able to
retrieve this data and still have access to the solutions on the Java track?

Kind Regards,
Greg.

**Comment by sshine** [comment]
@gregmcaree: No, the OAuth revoke was only if you couldn't get into your account.

It sounded on @iHiD that he also thought it was an authentication problem.

You say you've made sure that your GitHub email is the same as the one Exercism knows: Do you know this because the emails you receive from Exercism are addressed directly to this email address without any forwarding being involved?

In that case, perhaps the database is in a bad state; @iHiD would be able to confirm when he's got the time.

**Comment by iHiD** [comment]
> The issue is that there are a number of solutions from the Clojure track which are not available to me.

Can you define "not available". Maybe provide a screenshot? As far as I can tell from the DB, you should be able to go to `https://exercism.io/my/tracks/clojure` and then select a mode (mentored or independent/practice) and then your solutions will be there. If that's not the case, I'll need a screenshot to be able to move forward. Thanks.

**Comment by sshine** [comment]
Closing due to lack of response.
