### ISSUE TITLE
Deploy maintainer sync bot

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4233]
We have a bot that will allow maintainers of individual tracks add new maintainers to their track by accepting a pull request.

It's a GitHub App written using the Probot framework, which is node:
http://github.com/exercism/maintainer-sync

Can we get this deployed?

**Comment by iHiD** [comment]
@kytrinyx Do we need keys or anything?

**Comment by kytrinyx** [comment]
We will need some keys and things. I have to actually create the GitHub app on github.com for this.

**Comment by kytrinyx** [comment]
I've set up the app and given the keys and env vars to @iHiD

**Comment by iHiD** [comment]
@ccare Let's look at this when we're together tomorrow.

**Comment by iHiD** [comment]
@kytrinyx Can we close this?

**Comment by kytrinyx** [comment]
Yes! Sorry--should have done that. I still have to figure out why it's not responding properly. I have a pairing session set up with one of the probot maintainers this week.
