### ISSUE TITLE
In mentor view show student & mentor's languages

### ISSUE THREAD

**Issue by salticus** [exercism/exercism#4235]
When signing up as a student or mentor, Exercism asks which languages I have experience using (say 1 year or more.) When as a mentor I look at a solution for mentoring, I see the student's languages and my own displayed as emoji/symbols.

The goal is to get a quick feel for the student's background, remind myself of my own potential biases (i.e. Python Taoism ;-) and identify common experience that may be useful for mentoring.

(One might go further with other information such as years of experience in a language, area of experience (classroom/professional/hobbyist,) general goal for Exercism, "velocity" on Exercism, etc. A tangential idea would be to link emoji to their respective language page. All of those ideas seem like they need some hashing out, so I'm trying to start with suggesting the simplest version of showing previous language experience.)

Thoughts?

**Comment by salticus** [comment]
> The apparent problem to me on this would be feeling intimidated to mentor if the student has more apparent experience than you, or more is more broadly experienced.

> I was smacked down once because I asked a question of someone much more experienced than me, someone that I had looked up to.  And I knew they had much more experience than me and that was why I went to ask them.  And then was ignored when I asked for more information (They had used words that I had no idea what they meant, though I was sure those words had nothing to do with programming.)

> My point is, knowing that they have 15 years in 6 different languages and thinking that they will take guidance from me with `x` months in one language can be a very intimidating thing.  It could be better to not know. :slightly_smiling_face:

> Victor Goff

Very true! I hadn't thought of that angle.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
