### ISSUE TITLE
Poor Contrast Grey-on-White Text

### ISSUE THREAD

**Issue by SSPJ** [exercism/exercism#4237]
This is similar to #4113 but is a more general comment on the text for the whole site. "We envision a world where anyone from any background. . ." includes people who can't see well!

The background is `#FFFFFF` (white) and the foreground is `#9A9A9A` (grey).  For reference, here's the [WebAIM contrast checker](https://webaim.org/resources/contrastchecker/?fcolor=9A9A9A&bcolor=FFFFFF) with those values.

I have to zoom to **240%** before I can meaningfully read any of the text. At that zoom level, it is hard to navigate the page.

**Comment by rpottsoh** [comment]
I personally would love to see a contrast ratio of at least 7:1.  Looks like we are at 2.81:1 now.  I agree that the text is hard to read.  Depending on which computer of mine that I am using I have to zoom a little as some letters do not stand out very well, the worse offender being the letter `s`.  The middle of the letter all but disappears leaving just the very top and bottom of the letter to be seen.  At home I wear dime store cheaters when I am on the site to make it less strenuous on my eyes.  The foreground to background contrast is not good. 

Some complaints on the appearance of the text were raised early on in the first beta release of the v2 site, last year.  I don't recall which issues those are.  I don't know what plans the development team has going forward to address ease of readability issues like this.

From my end of the internet it just looks like a different font selection would go along way to help matters.

The font and contrast used by GiHub in the edit box I am typing this message in is quite easy to read...  As is the rest of the text on the GitHub site.

**Comment by iHiD** [comment]
Thanks for the issue. This is something we are and will continue to work on. We have lots of work going on for accessibility being spearheaded by @uused over here: https://github.com/exercism/website/pull/182 where he's also helping us understand things we need to do better.

> Some complaints on the appearance of the text were raised early on in the first beta release of the v2 site, last year. 
> The font and contrast used by GiHub in the edit box I am typing this message in is quite easy to read... As is the rest of the text on the GitHub site.

Just FYI, we responded to that by changing to the same font as GitHub use. The problem generally around the site is that we use a thiner font-weight I think.

**Comment by perogi** [comment]
+1 on this - I cannot read this site at all. I have to highlight or copy the pages so i can see them.

**Comment by iHiD** [comment]
@perogi Could you send a screenshot please so I can see how things look for you?

**Comment by rpottsoh** [comment]
@perogi take a picture with a camera even and post that image.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
