### ISSUE TITLE
Clicking Approve and Comment does not clear comment preview

### ISSUE THREAD

**Issue by devillexio** [exercism/exercism#4238]
I've noticed a few times that clicking the _Approve and Comment_ button while having the _Preview_ tab selected, results in the contents of the _Preview_ tab copied to the new comment input.

Only when you select the _Write_ tab on the new comment input and flip back to the _Preview_ tab, is the old comment text cleared.

I'm currently using Firefox Developer Edition v62.0b16 (64 bit).

**Comment by iHiD** [comment]
@devillexio We merged a fix for this last night. I'm not sure if it got deployed before this morning. So I think this is fixed but could you confirm if you still have the issue pls? (cc @jackhughesweb)

**Comment by devillexio** [comment]
You are correct, this issue is now resolved! 🎉
