### ISSUE TITLE
[Markdown] Comment box rendered / removed html markup that was part of a code snippet

### ISSUE THREAD

**Issue by grantwinney** [exercism/exercism#4240]
As part of a conversation with a student, I posted some code in the comment field that included html markup, something like this:

```html
<h1>This is an h1 header</h1>
<p>This is a paragraph</p>
<strong>Some strong text</strong>
<ul><li>List item 1</li><li>List item 2</li></ul>
```

When viewing it in the "Preview" tab, or after clicking the "Comment" button, it seems to render the html markup (as can be seen with "List item 1" and "List item 2" below) but then not show any of the other effects (such as the H1 header and strong text that isn't actually in bold).

```text
This is an h1 header
This is a paragraph
Some strong text

List item 1
List item 2

```

**Comment by NobbZ** [comment]
All together with all those issues about generics or template variables or pairwise greater/lesser than signs, let me think this is an issue with the markdown renderer.

Which one do we use?

**Comment by iHiD** [comment]
redcarpet (GitHub's)

**Comment by iHiD** [comment]
This one is definitely something we're doing wrong. I just don't know what yet :)

I can write failing tests now though which is good. @grantwinney If you could reduce that down to the minimum version that fails to render properly that would be super helpful.

**Comment by grantwinney** [comment]
Yep, I'll do that the next time I mentor a solution.

**Comment by grantwinney** [comment]
I reduced the example @iHiD - is that what you were looking for?

**Comment by iHiD** [comment]
@grantwinney Got a solution uuid I work from pls?

**Comment by iHiD** [comment]
I've deployed a fix that @kntsoriano wrote and am updating all comments now. Please could you check in a couple of hours as to whether you're happy that existing and new comments are fixed. Thanks! :)

**Comment by grantwinney** [comment]
Sorry, don't have the UUID anymore @iHiD. I tested it out though and it looks good now. Thanks!
