### ISSUE TITLE
Solution to core exercise remains unreviewed since July 19th

### ISSUE THREAD

**Issue by akeating** [exercism/exercism#4243]
Hi, thanks for such a great learning resource! 

I submitted the last of my solution edits to rust / pythagorean-triplet on July 19th. 

<img width="1201" alt="screen shot 2018-08-16 at 3 34 56 pm" src="https://user-images.githubusercontent.com/1427265/44238618-59cccf00-a16a-11e8-86ab-e01f2fee4a61.png">

Noting that the first attempt was reviewed and I pushed three updates. Obviously I would only expect a review for the last one.

I'm guessing somehow this is missing from a review queue somewhere? I know everyone is busy, but it's hard to know when to raise an issue when there's no transparency around review timelines. Of course, if this is normal, I will close this issue right away. 

Please let me know if I can help with any additional information.

**Comment by iHiD** [comment]
I'll take a look in my morning for you :)

**Comment by akeating** [comment]
I'd be quite happy working on this myself without mentorship. Well it seems pointless keeping this issue open
