### ISSUE TITLE
Leave conversation shows error

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4245]
Whenever I try to leave a conversation, I get an error page:

![image](https://user-images.githubusercontent.com/135246/44251440-9e9f4700-a1f8-11e8-911a-3af006bd6f00.png)

**Comment by jackhughesweb** [comment]
@ErikSchierboom Did this issue occur when selecting "Leave conversation" without sending any comments?

**Comment by ErikSchierboom** [comment]
@jackhughesweb That is correct!
