### ISSUE TITLE
Add "zen" mode for reviewing solution

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4246]
Maybe it would be useful to add a "zen" mode for reviewing a solution, where all non-essential components are hidden to allow us to focus on the code to be reviewed. This "zen" mode could even use the screen's full width, which would help review code that spans more than the displayed number of columns.

**Comment by F3PiX** [comment]
I like that! Would you prefer 'total zen'? Because I'd also like to see my previous comments in this mode. What do you think?

**Comment by ErikSchierboom** [comment]
I think this should also include the previous comments, but I'll leave that to the designers :)

**Comment by Alexhans** [comment]
Regardless of what the approach to help with this issue is, it certainly seems important to have a way where you can expand the code window and make use of screen estate or easily copy it to clipboard to analyse the code in an editor of choice (I've seen quite a few community solutions that didn't really pass the original unit tests).

**Comment by NobbZ** [comment]
Instead of copy pasting you can use `exercism download --uuid=...`. I consider this much easier than copy pasting and also less error prone as you'll get the correct tests as well.

**Comment by mayurdw** [comment]
Is this feature going to be developed in the foreseeable future? I would very much like this more than having to download solutions.

**Comment by NobbZ** [comment]
In most cases you (should) want running the tests anyway, therefore I (personally) do not see any sense in not downloading the students solutions.

This does not mean though, that I'm against a way to increase the size of the code display or the comment box.

**Comment by danruff5** [comment]
I personally don't run the tests. I can see weather the student is understanding the logic. At least for only the simpler solutions. But on the code review page the code is never wide enough to see the width of the lines. Even in the tests. It will be way easier to be able to just view the code all at once. Especially if you are doing multiple of the same project in a row. You learn the solution and can, for the most part, be able to see if the solution is correct.

Another suggestion would be to run the tests on server side and show the result in the review (but for all tracks that would be very difficult)

**Comment by itarato** [comment]
Not a mentor, but for reviewing community solutions I'm using this bookmark:

```javascript
javascript:jQuery('#solution-page%20div.widget-panels').removeClass('widget-panels%20widget-panels--vertical-split');void(0);
```

It removes the horizontal layout and makes the code full width.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
