### ISSUE TITLE
[Markdown] Anything in angle brackets in the Comments textbox is being treated as a tag that needs closed

### ISSUE THREAD

**Issue by grantwinney** [exercism/exercism#4247]
If I add text like this in the Comments textbox:

```
IEnumerable<string> factors = new List<int> { 3, 5, 7 };
```

It treats `<string>` and `<int>` like html tags that need to be closed when it renders the output:

```
IEnumerable<string> factors = new List<int> { 3, 5, 7 };</int></string>
```

You can see an example of this [here](https://exercism.io/mentor/solutions/b0447496bd8b4d9889fda933afa40390?iteration_idx=2#discussion-post-161133).

Similarly, this:

```
<string><int><um no>
```

Renders like this:

```
<string><int><um no></um></int></string>
```

**Comment by iHiD** [comment]
I've deployed a fix that @kntsoriano wrote and am updating all comments now. Please could you check in a couple of hours as to whether you're happy that existing and new comments are fixed. Thanks! :)

**Comment by grantwinney** [comment]
When I type the same thing in this comment box, without backticks, I don't see any closing tags automatically generated by GitHub.

But I confirmed that if I include backticks in the Exercism comment window, then the closing tags don't generate, so I'm cool with closing this if that's good enough. I can't imagine a time I'd want to type something in brackets without including backticks...

**Comment by iHiD** [comment]
In Github, it strips that tags. In Exercism we close the tags. I think with either you'll get incorrect input unless you use backticks.

For reference, Github does this:
<img width="397" alt="screen shot 2018-08-23 at 17 31 23" src="https://user-images.githubusercontent.com/286476/44538846-6ddc7780-a6fa-11e8-87d9-30ccd0757050.png">
<img width="309" alt="screen shot 2018-08-23 at 17 31 26" src="https://user-images.githubusercontent.com/286476/44538847-6ddc7780-a6fa-11e8-994a-eafbd933e439.png">

Thanks for your helping in solving this.
