### ISSUE TITLE
NoMethodError in my/solutions#walkthrough

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4248]
## Error in Exercism V2

**NoMethodError** in **my/solutions#walkthrough**
undefined method `token' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b76a6c7e0086a0018748a1b?event_id=5b76c496002ac594b5090000&i=gh&m=ci)

## Stacktrace

    app/models/user.rb:69 - auth_token
    app/services/render_user_walkthrough.rb:28 - auth_token
    app/services/render_user_walkthrough.rb:19 - substitute_tokens!
    app/services/render_user_walkthrough.rb:9 - call
    app/controllers/my/solutions_controller.rb:32 - walkthrough

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b76a6c7e0086a0018748a1b?event_id=5b76c496002ac594b5090000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by iHiD** [comment]
@kntsoriano We render the CLI walkthrough to logged-out users now so this token bit needs a default.

**Comment by kntsoriano** [comment]
@iHiD I think it's a different error based on what the Bugsnag trace looks like. The error is that we have users who don't have auth tokens. Should this be the case?

**Comment by iHiD** [comment]
The users without auth tokens are `[205729, 205697, 205717, 205706, 205736, 205707, 205703]`

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **pages#cli_walkthrough**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b76a6c7e0086a0018748a1b?event_id=5b7dacc4002d943fd7000000&i=gh&m=ra)

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**NoMethodError** in **pages#cli_walkthrough**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b76a6c7e0086a0018748a1b?event_id=5b7daf9d002ac4395c220000&i=gh&m=fx)

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**NoMethodError** in **my/solutions#walkthrough**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b76a6c7e0086a0018748a1b?event_id=5bcf1be700309bcb27b30000&i=gh&m=ra)

**Comment by iHiD** [comment]
@kntsoriano Can this be closed?
