### ISSUE TITLE
[Markdown] Unexpected HTML tags appeared in a Markdown code block

### ISSUE THREAD

**Issue by kornelski** [exercism/exercism#4250]
In a comment to an excercise I've posted code like this:

````markdown

```rust
let mut matchers = HashMap::new(); // should be fine
let mut matchers: HashMap<char, char> = HashMap::new(); // more usual way of specifying the type
```

````

but it was rendered as:

>      let mut matchers = HashMap::new(); // should be fine
>      let mut matchers: HashMap<char char> = HashMap::new(); // more usual way of specifying the type
>      </char>

Note that `<char, char>` was interpreted as an (invalid) HTML tag.

**Comment by iHiD** [comment]
@kornelski Do you have a sample solution uuid pls?

**Comment by kornelski** [comment]
Sorry, I didn't record it. But the issue is easly reproducible by entering the markdown code in any comment.

**Comment by iHiD** [comment]
No worries. I've deployed a fix that @kntsoriano wrote and am updating all comments now. If you could check in a couple of hours as to whether you're happy that it's fixed, that'd be great :)
