### ISSUE TITLE
Explaination for "Pythagorean Triplet" Exercise (Python Track)

### ISSUE THREAD

**Issue by TiDreyer** [exercism/exercism#4251]
The introduction of the "Pythagorean Triplet" side exercise in the python track does not reflect the requirements of the unit tests. There is a comment in the unit test file explaining the exercise better, maybe this should be moved to the introduction.

**Comment by rpottsoh** [comment]
A Python specific issue should be raised at https://github.com/exercism/python/issues.
However, if you feel the issue pertains to the general nature of the exercise, meaning it would affect all tracks that are implementing this exercise, then I encourage you to open an issue at https://github.com/exercism/problem-specifications/issues.

**Comment by rpottsoh** [comment]
This issue can likely be closed.

**Comment by TiDreyer** [comment]
Thanks for the clarifications and sorry for not checking GitHub regularly...
I'm closing the issue now ;)
