### ISSUE TITLE
"Expire" mentorships

### ISSUE THREAD

**Issue by nuclearwessel** [exercism/exercism#4253]
Three of my previously submitted solutions from the Erlang core track have been pending approval since the migration (Leap, Collatz, and Raindrops). I posted to the gitter support channel requesting an update and it sounds like there may be a bug preventing these solutions from showing in the mentoring queue.

https://exercism.io/my/solutions/dce9384ebb0d41a3aca3099a792ba432
https://exercism.io/my/solutions/04f56f9d08d646cbb487b0c29433974a
https://exercism.io/my/solutions/92c4a984dd514f99ade15e40ea73da42

I did have one other Erlang legacy solution approved since the migration, the only difference I see with these three is that they had prior conversations where the other did not. Not sure if that would be enough to confuse the system into thinking they were already reviewed?

**Comment by iHiD** [comment]
@nuclearwessel: @Nobbz and I have tracked this down - sorry. There is a bug that needs fixing.

Note to self: For old conversations with old conversations, the original participant(s) in the conversation has been marked as the mentor. This person might not be a mentor. We need to guard against this and effectively expire these records.

**Comment by iHiD** [comment]
@nuclearwessel We did this btw :)
