### ISSUE TITLE
Complete FAQ of the new changes: Can't see other people's submissions

### ISSUE THREAD

**Issue by bbtdev** [exercism/exercism#4254]
Hello,

I haven't been using exercism for a few months, but it seems I can't see other people's submission anymore?
Also I can't move on to the next exercise until a mentor reviews my code?

I really like the mentorship feature, I need it, but are the above true? Or Idk where to click?

**Comment by iHiD** [comment]
Thanks for the post :) This is a duplicate of #4172. See my latest comment here. Thanks! https://github.com/exercism/exercism/issues/4172#issuecomment-414164731
