### ISSUE TITLE
Waiting for mentor's feedback in Elixir track

### ISSUE THREAD

**Issue by sytong** [exercism/exercism#4255]
I have completed an Elixir exercise a week ago but I still haven't received feedback.
Whereas I received feedback from the Ruby track much faster (within a day).

May I ask is this simply because I am stuck in a long queue in the Elixir track?

**Comment by NobbZ** [comment]
I skimmed the queue with all filters available and I am unable to find a submission from a user "sytong" in any of the elixir exercises.

Could you please elaborate which username you have on exercism or even better tell us the URL of your submission and if it is marked core for you? Also is it a legacy solution or a regular one?
