### ISSUE TITLE
[Markdown] Type annotations in a codeblock get mangled in the output.

### ISSUE THREAD

**Issue by ptillemans** [exercism/exercism#4257]
When mentoring rust, I noticed in snippets which I reply to the students that type information gets mangled:

`collect::<Vec<char>>` --> `collect::<vec>&gt;`

I have no clue why the capital V turns into a lower case v, where the *char* went to and why the first '>'  survives but the second one turns into an xml entity.

@iHiD  mentioned that this phenomenon looks different from other similar ones and asked to log this issue

**Comment by mawis** [comment]
It seems that Prism tries to normalize everything it thinks is HTML code. So everything gets converted to lower-case and HTML tags within HTML tags get removed completely (that's why the “<char>” is missing completely in the result.

**Comment by iHiD** [comment]
@ptillemans @mawis Do you have a sample solution uuid pls?

**Comment by iHiD** [comment]
I've deployed a fix that @kntsoriano wrote and am updating all comments now. Please could you check in a couple of hours as to whether you're happy that existing and new comments are fixed. Thanks! :)

**Comment by mawis** [comment]
I cannot provide an example anymore. For Rust it seems to work correctly now.

**Comment by iHiD** [comment]
Great :)
