### ISSUE TITLE
Can't see download instructions for a submitted exercise

### ISSUE THREAD

**Issue by janetriley** [exercism/exercism#4259]
The download instructions aren't visible once you've submitted something for an exercise. 

I'm coming back to `exercism` after a few years away. (The new site looks great!)  There was still an open exercise, but I deleted the files off my laptop a long time ago.  I was able to figure out most of the command from another exercise, but it took several attempts to dope out the exercise name for "word count" -   turns out you put a dash between words.  

The [migration instructions](https://exercism.io/cli-v1-to-v2) expect you to have the old files handy, and use underscores for spaces. 

It would be handy if there were a way to see the download command again.

**Comment by ftt** [comment]
You can use `exercism download -u *UUID*` where *UUID* is a random looking sequence of characters at the end of the URL of your exercise: https://exercism.io/my/solutions/...UUID is here...

**Comment by janetriley** [comment]
Thanks. That might be a good item to add to a FAQ.   

I got unstuck by doping out how the exercises were named. I opened the ticket for the next person in this situation. 

I don't want to be prescriptive about an implementation, because I'm not a user experience person and I don't know the user community.  I was stuck, and I looked in all the places I could think of. Is there a way to make the right next step available on the site?

**Comment by NobbZ** [comment]
Still there should be a copy-button, that makes it easy to get the download command, similar to how it is already for a fresh assignment.

It just consumes unnecessary time to either guess the exercises slug from the name or selectively copying the UUID from the URL.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
