### ISSUE TITLE
Exercise missing a stub

### ISSUE THREAD

**Issue by ftt** [exercism/exercism#4261]
I've noticed that when I download the "Sublist" problem in the Rust track, `lib.rs` is empty. Usually, it contains a stub with the not-implemented macro in the body of a function called by tests. I can infer the required signature from those tests but want to report it in case it's a bug (i.e. the stub should be there but was lost on download or something).

**Comment by NobbZ** [comment]
Seems to be as intended:

https://github.com/exercism/rust/blob/master/exercises/sublist/src/lib.rs

**Comment by NobbZ** [comment]
Beeing more awake now, and not only between changing the diapers of my baby and giving her a milk, I want to elaborate a bit on that, but please be aware that I am not sure where in the track this exercise occurs, ie is it a more advanced one, is it core or side, is it early, all these things are unknown to me.

Some tracks follow the spirit to only provide stubs at the beginning of a track while leaving them away later on to make the student learn how to write those from the ground.

**Comment by ftt** [comment]
Oh right, I can just look at the code! :) Thank you! I will submit a PR to add a note to the README that this is intended.
