### ISSUE TITLE
[ANNOUNCEMENT] We are merging the JavaScript and ECMAScript tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4264]
The ECMAScript track was started several years ago to tackle modern JavaScript concepts, and over the past few years, these have become the standard. As such, we are going to merge the two tracks into one, using the exercises that are in the ECMAScript track, and deprecating the ones in the JavaScript track.

The merged track will be called JavaScript.

Getting this right on the site is a bit tricky, and we are working out the details. We intend to run the migration in the next 24 hours. We're still working out the details of the migration plan, and we will update this issue with tweaks and news.

The current plan is:

- [x]  Finish writing the migration logic
- [x] Notify mentors in Slack about the migration and ask them to stop mentoring on these two tracks for a bit.
- [x] Draft an email to everyone who has signed up to either JavaScript or ECMAScript since we launched the new site, explaining what is happening.
- [x] Push a change to the website that locks the JavaScript and ECMAScript tracks so that nobody can mentor or submit code during the migration.
- [x] Open a 🚧 work in progress 🚧 pull request on the ECMAScript track renaming it to "JavaScript" https://github.com/exercism/ecmascript/pull/453
- [x] Test the lock on the site 
- [x] Open a 🚧 work in progress 🚧 pull request on the JavaScript track renaming it to "JavaScript (Legacy)", and updating `active` to be false, and updates the README to explain what's up. https://github.com/exercism/javascript/pull/560
- [x] Test the lock on the CLI.
- [x] Notify everyone on the `exercism/javascript` team who is not also in the `exercism/ecmascript` that they can become maintainers, but we don't want to presume. Just ask us.
- [x] (Temporarily) Archive the javascript and ecmascript repositories so that there are no changes during the migration
- [x] Run the migration.
- [x] Copy mentors over
- [x] Un-archive the javascript and ecmascript repositories
- [x] Merge the 🚧 work in progress 🚧 PRs on both repositories -- the site will be updated with the new values
- [x] Rename the javascript repository to DEPRECATED.javascript
- [x] Archive the `DEPRECATED.javascript` repository (permanently, this time) 
- [x] Rename the 'javascript' track in the site database
- [x] Rename the 'ecmascript' track to 'javascript' in the site database
- [x] Rename the `exercism/ecmascript` team to `exercism/javascript`
- [x] Rename the `ecmascript` repository to `javascript`
- [x] Add redirect from `/tracks/ecmascript` to `/tracks/javascript`
- [x] Unlock the tracks on the site
- [x] Sort out the javascript track logo
- [ ] ~Send the email~
- [ ] Put a banner on the site

/cc @exercism/javascript @exercism/ecmascript

**Comment by ErikSchierboom** [comment]
Great idea! Good luck with the migration.

**Comment by kytrinyx** [comment]
Update: @exercism/javascript I'm going to send you all an email with details, but the short version is that I won't add you to the @exercism/ecmascript team automatically.

**Comment by kytrinyx** [comment]
I messed up the `@exercism/ecmascript` rename. I think I fixed it, but if something seems off, please holler.

**Comment by kytrinyx** [comment]
@exercism/javascript The track is live on the site, and ready for you to polish. I'm thinking there are probably a few places where it should say JavaScript rather than ECMAScript (I made some guesses, but left some I was unsure about).

We will send out the emails to everyone who has participated in the javascript and ecmascript tracks in the morning.

**Comment by kytrinyx** [comment]
Aaaand, we realized we could just put a banner on the site for a while instead of sending everyone email. So we'll do that.

**Comment by tejasbubane** [comment]
We got an issue in javascript track which is little unexpected - https://github.com/exercism/javascript/issues/461

I am wondering if this has anything to do with the migration. Can someone here have a look please?

**Comment by iHiD** [comment]
I will, but I want to understand the issue first as I think we might have a problem with some of the legacy JS exercises being set to core (which means running the script won't fix it). It's top on my priority list when I get 30mins free.

**Comment by kytrinyx** [comment]
I'll close this. If anyone sees strangeness, please open a new issue and we'll tackle it specifically!
