### ISSUE TITLE
Mentoring: Incorrect file name when using "Download this solution" \\

### ISSUE THREAD

**Issue by budmc29** [exercism/exercism#4265]
For some exercises the main file has extra slashes, `\\`.

Some of the exercises are fine, some have this bug, can't seem to notice a pattern.

`exercism download --uuid=268177bfcf56453caa31ebcff20a13ff`

MacOS latest version, iterm2

<img width="524" alt="image" src="https://user-images.githubusercontent.com/7063792/44311741-e8e51b80-a3e4-11e8-9dbb-445b6cbebd8e.png">

**Comment by kytrinyx** [comment]
Thanks @budmc29. This is being tracked in https://github.com/exercism/cli/issues/665 -- I'm working on another bug right now, but this one is next up once the first one is solved.

I'm going to close this as a duplicate.
