### ISSUE TITLE
[TRACKING] Remove obsolete version tracking assertions in exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4266]
In the old version of the website we had a problem where there was no indication which version of an exercise the user had solved.

For example, given two users, Alice and Bob, and an exercise Relay Race, we often saw the following situation:

1. Alice submitted a solution to Relay Race that passed the tests.
1. The maintainers of the track updated the tests for Relay Race in a way that was backwards incompatible.
1. Bob looked at Alice's solution.
1. The site is displaying the most recent tests.
1. Bob tells Alice that the submitted solution doesn't work.

A hacky workaround that we used in many tracks was to add a version to the exercise tests, and the test suite would include a failing assertion that included that version number.

That way Alice would have something in the solution that had the version number, and when Bob looked at the solution on the site, it's clear that the tests have one version and the solution have another.

This additional bookkeeping was a burden on everyone, but it was better than the experience people got when they were told they were wrong unnecessarily.

In the new site we have fixed the underlying design issue that caused this problem.

Now, when Alice unlocks an exercise, we pin the exercise to the most recent SHA of the track repository.

So the repository might move on, but Alice's exercise will stay at the same version.

- If Alice downloads the exercise to a different computer, it will have the same test suite.
- If Bob looks at the exercise online, it will have the same test suite.
- If Bob downloads the exercise, it will have the same test suite.

I will be submitting individual issues to each track about removing the now-obsolete bookkeeping logic.

## How you can contribute

If you have five minutes, would you go to one of the linked issues and figure out whether or not there are version assertions in the exercises? Add a comment to the linked issue (not this one) with your findings.

This will help us close all the issues in the tracks that don't need any further work in this regard.

---

_Side notes:_

* There was a bug with the pinning, which is being fixed today. See https://github.com/exercism/exercism/issues/4213
* We're discussing the possibility of letting people explicitly un-pin and re-pin an exercise to get the latest version of the tests. See https://github.com/exercism/exercism/issues/4219 for details.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
