### ISSUE TITLE
having trouble installing exercism in cli

### ISSUE THREAD

**Issue by kwambugu** [exercism/exercism#4267]
despite following the interactive walk through i still get the following error:  exercism: command not found
please help

**Comment by kwambugu** [comment]
Hi was finally able to make it work-this is after googling for solution
,thanks

**Comment by rpottsoh** [comment]
@kwambugu would you let us know more about the issue you were having so that we might learn where the walk through might be weak and could be improved.  Glad to see that you managed to figure things out. 👍

**Comment by kwambugu** [comment]
Registering of bin path to .bash_profile
