### ISSUE TITLE
Reset My Track

### ISSUE THREAD

**Issue by davidfrogley** [exercism/exercism#4270]
I've looked through the FAQ and forum, and it appears there is currently no way to delete solutions or un-publish solutions or reset a language track. Even though I selected the mentored option for my C# track, I was in a hurry at the time and marked my solutions as complete without waiting for mentor feedback. However, now I'd like to un-publish my solutions and delete them entirely, even completely reset my C# track if possible to a pristine state (as if I had just barely started the track).

Is this possible?

**Comment by iHiD** [comment]
You can use use the "Leave Track" button on the right hand side of the track page :)

**Comment by davidfrogley** [comment]
I tried the "Leave Track" already. When I re-joined the track, all my previous solutions, published or otherwise, and my previous progress were still there.

**Comment by iHiD** [comment]
For clarity, you tried Leave Track today and it didn't remove your solutions?

**Comment by davidfrogley** [comment]
No, I tried "Leave Track" about two weeks ago. Then, about a week later, I joined the track anew and saw that my progress and solutions from my before were all still there.

**Comment by rpottsoh** [comment]
try again, today.  Leave Track has been getting some TLC very recently.

**Comment by davidfrogley** [comment]
Excellent! Seems to work now the way I had hoped. Thanks much!

**Comment by iHiD** [comment]
Great :)

**Comment by TomasHubelbauer** [comment]
FWIW there is now an explicit menu item for this:

![image](https://user-images.githubusercontent.com/6831144/213918352-705c4369-80c7-4646-8a41-c54b282dbd49.png)
![image](https://user-images.githubusercontent.com/6831144/213918349-d472ff4e-5be8-4033-90ca-05f1ba422514.png)
