### ISSUE TITLE
Text on settings page is too light

### ISSUE THREAD

**Issue by TannerFilip** [exercism/exercism#4272]
As the title says, the text on the settings page (https://exercism.io/my/settings) is too light. WCAG 2.0 requires a contrast of 4.0 on normal text, and right now it looks like it's 2.07 with `#B1B1B1` on `#FAFBFC`. Something like `#747476` would be a lot easier to see.

**Comment by iHiD** [comment]
Hi @TannerFilip. Which text are you referring to? I can't see anything with `#B1B1B1` on that page.
