### ISSUE TITLE
Python Track awaiting mentor feedback

### ISSUE THREAD

**Issue by thomasintrouble** [exercism/exercism#4274]
Hi
Firstly thanks for creating Exercism, it’s a great resource and very easy to use.
I’ve started the Python track and had feedback on the first proper exercise (“Leap”) within about 30 minutes. However I’ve not had any feedback on "Bob" or any of the side exercises submitted in the last 4 days. Of course, this is a free resource so I’m more than happy to wait if this is the normal timeframe. However I though I would ask just in case I hadn’t submitted properly, or if there was some other problem with the system?
Many thanks in advance
Tom 
( username thomasintrouble)

**Comment by spelga** [comment]
Hi,

I'm also awaiting feedback on this track. I'm now awaiting feedback for 8 extra exercises, some as old as a month old however some have only been completed very recently. It would be great if someone could take a look.

Not sure on the etiquette on adding to this issue or if it should be a new issue. Went for this is as the issue is the same but happy to raise another issue if that is deemed appropriate.

Thanks

py4me

**Comment by iHiD** [comment]
Thanks for the empathetic issue :)

As a general rule core exercises should be mentored within 24hrs (a couple of tracks are overloaded so slower than this but nearly all are within 24hrs). Side exercises can take a similar time or take forever (ie we'll currently never get to them) depending on the amount of submissions and mentors. We have over 200 python submissions per day and it's out busiest track, so the side exercises are more on the forever end of the spectrum right now. As we recruit more mentors this should improve but for now it is what it is.

You can review other people's solutions on side exercises (there's a link in the "what's next" bit) so hopefully you can learn from that in the meantime.

Thanks for your understanding.

**Comment by thomasintrouble** [comment]
Thanks very much for getting back to me and totally understand how busy you must all be. My core exercise has been waiting 3 days now, so hopefully it is at the front of the queue as the next assignment looks interesting! Keep up the great work.

**Comment by spelga** [comment]
Thanks iHiD I hadn't realised that I could see the other solutions. That will do well for now.

**Comment by iHiD** [comment]
No probs. That's a new feature from yesterday so probably wasn't there when you submitted :)

**Comment by iHiD** [comment]
@thomasintrouble If it's still there by the weekend reopen this and paste the solution URL and I'll check in case there's a bug :)
