### ISSUE TITLE
Cannot download student's solution with cli

### ISSUE THREAD

**Issue by mawis** [exercism/exercism#4275]
When I try to download the solution of this: https://exercism.io/mentor/solutions/66199fc9fb3e4ef0b61d104eb015e1b7 is use the following command: `exercism download --uuid=66199fc9fb3e4ef0b61d104eb015e1b7`

However while downloading I don't get the solution the user has submitted and that is visible on the website, but just the standard exercise template:

```rust
pub fn find_saddle_points(input: &[Vec<u64>]) -> Vec<(usize, usize)> {
    unimplemented!(
        "find the saddle points of the following matrix: {:?}",
        input
    )
}
```

*Note:* There are no other files where the solution could be contained in:

```
.
├── Cargo.toml
├── .gitignore
├── README.md
├── .solution.json
├── src
│   └── lib.rs
└── tests
    └── saddle-points.rs
```

**Comment by iHiD** [comment]
Interesting bug. Thanks.

**Comment by kytrinyx** [comment]
This is the same bug as #4066.

I have submitted a fix to the CLI, and will cut a release as soon as this is reviewed and approved.
