### ISSUE TITLE
ActiveRecord::ValueTooLong in api/solutions#update

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4277]
## Error in Exercism V2

**ActiveRecord::ValueTooLong** in **api/solutions#update**
Mysql2::Error: Data too long for column 'file_contents' at row 1: INSERT INTO `iteration_files` (`iteration_id`, `filename`, `file_contents`, `file_contents_digest`, `created_at`, `updated_at`) VALUES (867810, 'helloworld', x'cffaedfe0700000103000080020000000f00000040060000850020000000000019000000480000005f5f504147455a45524f00000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000019000000280200005f5f54455854000000000000000000000000000001000000003002000000000000000000000000000030020000000000070000000500000006000000000000005f5f74657874000000000000000000005f5f5445585400000000000000000000e015000001000000fffe010000000000e0150000040000000000000000000000000400800000000000000000000000005f5f73747562730000000000000000005f5f5445585400000000000000000000e014020001000000f600000000000000e0140200010000000000000000000000080400800000000006000000000000005f5f737475625f68656c7065720000005f5f5445585400000000000000000000d815020001000000aa01000000000000d81...

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b7c723c4efd6c00192b0c1a?event_id=5b7c723c002acceff4520000&i=gh&m=ci)

## Stacktrace

    app/services/create_iteration.rb:14 - block in call
    app/services/create_iteration.rb:13 - each
    app/services/create_iteration.rb:13 - call
    app/controllers/api/solutions_controller.rb:112 - update

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b7c723c4efd6c00192b0c1a?event_id=5b7c723c002acceff4520000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by iHiD** [comment]
@kytrinyx I'll catch this in the API, but I wonder if it's worth checking the filesize in the CLI too to avoid someone killing their network.

**Comment by kytrinyx** [comment]
💯 Yeah, we should definitely not bother sending massive files across the wire only to complain after the fact!

**Comment by kytrinyx** [comment]
I've opened an issue in the CLI repository for this.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
