### ISSUE TITLE
ActionController::UnknownFormat in registrations#new

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4278]
## Error in Exercism V2

**ActionController::UnknownFormat** in **registrations#new**
ActionController::UnknownFormat

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b7c697c0b9f04001810cb95?event_id=5b7c697c002ac9bd9e2a0000&i=gh&m=ci)

## Stacktrace

    gems/responders-2.4.0/lib/action_controller/respond_with.rb:213 - respond_with

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b7c697c0b9f04001810cb95?event_id=5b7c697c002ac9bd9e2a0000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by iHiD** [comment]
@kntsoriano This is cause by a bot. Shall we just ignore it or should we do something with it?

**Comment by kntsoriano** [comment]
According to Bugsnag, it's classified as a low importance error.

We can either ignore it, or add the `ActionController::UnkownFormat` error to our list of ignored errors.

**Comment by kntsoriano** [comment]
I'm closing this :)

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionController::UnknownFormat** in **registrations#new**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b7c697c0b9f04001810cb95?event_id=5bd41ce100308012dd8a0000&i=gh&m=ra)

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ActionController::UnknownFormat** in **sessions#new**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b7c697c0b9f04001810cb95?event_id=5c470d180034380425760000&i=gh&m=fx)

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionController::UnknownFormat** in **registrations#new**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b7c697c0b9f04001810cb95?event_id=5c5e28fc0035a08f7b6d0000&i=gh&m=ra)
