### ISSUE TITLE
[Python] Issue in calculating the Hamming Distance exercise

### ISSUE THREAD

**Issue by abonello** [exercism/exercism#4285]
I am getting the following error when running the test. This relates 
self = <hamming_test.HammingTest testMethod=test_disallow_first_strand_longer>

    def test_disallow_first_strand_longer(self):
>       with self.assertRaisesWithMessage(ValueError):
E       AttributeError: 'HammingTest' object has no attribute 'assertRaisesWithMessage'

I tried running both under python 2.7.9 and python 3.6.2. 
Operating system MacOSX 10.10.5
pytest 3.0.5 (python 2)
pytest 3.7.2 (python 3)

**Comment by pernambucano** [comment]
Hi, @abonello!
I tested here (MacOSX 10.13.6, python 3.7, pytest 3.7.2) and it worked fine. However, if you indent the code `def assertRaisesWithMessage(self, exception):
    return self.assertRaisesRegex(exception, r".+")` to the left it would not be part of the class HammingTest anymore, and therefore it would give you this error. Maybe when you copy-pasted this code somewhere it auto-formatted in the wrong way. Give it a try, see if this is the reason for your problem. If you need anything else just answer here, and I'll try to help you.

**Comment by abonello** [comment]
Update.
When I am working with unittests. I start by commenting out everything and then start uncommenting one test at a time. Without realising I commented out the utility function at the bottom. Will pay more attention next time.

**Comment by pernambucano** [comment]
Don't worry, I also do that a lot xD. 
Good luck on the python track!
o/

P.S.: @iHiD , could you close this issue please?

**Comment by jonaho** [comment]
The unit testing module deprecated "assertRaisesRegexp" in favor of "assertRaisesRegex" in Python3, so those running Python2 for Pytest will have errors with the error raising of that method.

**Comment by NobbZ** [comment]
Python 2.7 is officially discontinued. You shouldn't use it anymore. Therefore what you descibe is a non-issue.
