### ISSUE TITLE
Unreviewed side excercises in Haskell track

### ISSUE THREAD

**Issue by sgerber-hyperanna** [exercism/exercism#4286]
Hi all,

Firstly thanks to all the Haskell mentors - it's been really great getting your feedback! For the core exercises I always get feedback within a couple of days. 

However, most of the side exercises I have completed have not been reviewed. In some cases for nearly a month.

https://exercism.io/my/solutions/9ecc93e9b51d4ed3ae5dc6d3e572cd70
https://exercism.io/my/solutions/0998e26daaad47268b598e64a302b97c
https://exercism.io/my/solutions/0998e26daaad47268b598e64a302b97c
https://exercism.io/my/solutions/0998e26daaad47268b598e64a302b97c
https://exercism.io/my/solutions/a16e51c04cf544e982bf0a08a086baec

Cheers,

**Comment by iHiD** [comment]
@sgerber-hyperanna The length of queue atm means that side exercises get reviewed sporadically compared to core exercises which are prioritised. That won't change until we have more mentors so in the meantime I recommend looking at the community solutions (you'll find links on your solution) and learning from those. Thanks for your understanding :)
