### ISSUE TITLE
[Scala] Link to "Complex Numbers" is broken

### ISSUE THREAD

**Issue by edejong** [exercism/exercism#4287]
The other exercises use hashes, but the "complex numbers" exercise links to:
https://exercism.io/my/solutions?exercise_id=complex-numbers&track_id=scala

When clicking the link I just see the Scala track again as opposed to the exercise

**Comment by iHiD** [comment]
@exercism/scala Have you changed anything to do with the unlocking of Complex Numbers recently?

**Comment by ricemery** [comment]
Complex Numbers is a new exercise for Scala. It was added on Aug 16.
Maybe something is messed up in the config.json, but nothing looks
obviously wrong.

**Comment by iHiD** [comment]
Ok great. I have to run scripts manually when new exercises are added atm
to unlock it for existing track-takers. I'll sort it. Thanks :)

**Comment by ricemery** [comment]
Cool. Thank you.
FYI - we added diamond about a month ago.

**Comment by ricemery** [comment]
@iHiD - Do I need to tell you when we add a new exercise to a track? I just added rotational-cipher to the Scala track.

**Comment by iHiD** [comment]
Yes pls, ideally for the moment. Although I run a catchall script most days anyway.
