### ISSUE TITLE
Markdown bold not working on Ubuntu

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/exercism#4288]
Marking things `**bold**` should look like **this**, but currently has no discernible effect on the look of the text. Interestingly, the HTML does have enclose the `**text**` in a `strong` tags like so: `<strong>text</strong>` but something must be messing with the styling because on both firefox and chrome on Ubuntu I did not see any visual difference. Interestingly on macOS the text is **bold** in both firefox and chrome.

**Comment by iHiD** [comment]
Ubuntu uses a different font to MacOS, so I wonder if it doesn't have the specified font-weight. I'll try and work out a way to take a look. Thanks.

**Comment by sshine** [comment]
I believe this is a duplicate of #4179. I might have closed that issue by making a wrong assumption.

@Cohen-Carlisle: Can you confirm if this is still a problem?

**Comment by Cohen-Carlisle** [comment]
This does appear to be fixed for markdown comments as well.
