### ISSUE TITLE
Next exercise still locked after exercise completion

### ISSUE THREAD

**Issue by paparomeo** [exercism/exercism#4289]
My **Linked List** exercise (https://exercism.io/my/solutions/f79a9d0412504e5891e15ca60226c41f) in the JavaScript track was approved by a mentor and I've marked it as completed, but the next core exercise **Pascal's Triangle** in the JavaScript track hasn't unlocked. I'd really like to continue progressing in the track: any help will be much appreciated.

**Comment by iHiD** [comment]
I'll have a look at this but I'm not around today or tomorrow so will have
to ask for your patience. Sorry.

**Comment by paparomeo** [comment]
No worries. Probably fallout from merging the ECMAScript and legacy JavaScript tracks. Thanks for looking into it!

**Comment by jsplaine** [comment]
@iHiD I've had this same issue for about 5 weeks now if you don't mind taking a peek.

**Comment by paparomeo** [comment]
I thought of helping, but looking at the source code it looks like this might be something at the database level that I won't be able to help.

**Comment by iHiD** [comment]
@paparomeo @partyblanket Is this fixed for you now? (It won't be for anyone else - I'm testing on your accounts)

@jsplaine According to the database, there doesn't seem to be a problem on your track. Has it resolved itself?

**Comment by paparomeo** [comment]
Fixed for me @iHiD. Much appreciated! For my part this issue can be closed.

**Comment by iHiD** [comment]
@paparomeo Thanks for letting me know. Sorry it took so long to sort.

**Comment by partyblanket** [comment]
@iHiD fixed for me too, thank you!

**Comment by APegram** [comment]
After submitting the second exercise in the Python track, I seem to not be able to unlock the next exercise. Is anyone able to help resolve this?

**Comment by lfplazas10** [comment]
I have the same issue as most of the people above, I completed the space age exercise (Go track)  but the next one seems continues to be locked. tia

**Comment by lfplazas10** [comment]
Never mind, just found out about the independent mode.

**Comment by APegram** [comment]
Yeah I ended up turning independent mode on
