### ISSUE TITLE
Mentors: Source code is shown in tiny box

### ISSUE THREAD

**Issue by lathspell** [exercism/exercism#4290]
In mentoring mode the source is shown in a tiny box which is totally unnecessary.
If I remove the following CSS element, the page takes the whole monitor width which is much better.

Testet on https://exercism.io/mentor/solutions/7b622d5fec4f40558c2ff10a3458d7c1

    .lo-container {
        width: 1200px;

**Comment by lathspell** [comment]
Because they probably didn't and used the standard setting of their Content-Management-System?
Mabe it's possible to use 1200px as minimum for small screens but allow up to relative value of 50% screenspace? (don't know if modern CSS can do that)

**Comment by sshine** [comment]
I agree with you that such a narrow box is not a good way to view source code, and I am only lucky to be mentoring on tracks where source code lines are often very short. Changing the width of the source code box will require more re-designing than changing the width of the main content area.

Considering @iHiD already viewed this, and he's in charge of the website, I'm closing this issue.
