### ISSUE TITLE
[Python] Rest-API: Sorting of user list

### ISSUE THREAD

**Issue by karelvancamp** [exercism/exercism#4293]
It's not defined in the Instruction Methods if and how the users should be sorted.

> {"users":<List of User objects for <users>>}

Though it does seem to require alphabetic sort based on object.name to pass the tests.

**Comment by cmccandless** [comment]
I've [created an issue](https://github.com/exercism/problem-specifications/issues/1304) for this in the proper repository. This one may be closed.
