### ISSUE TITLE
Reminder after commenting a submission for student or mentor

### ISSUE THREAD

**Issue by amoradell** [exercism/exercism#4295]
Is it possible to have a reminder for student or mentor to answer after a period, a week for example ?

**Comment by guygastineau** [comment]
I think this is a good idea.

**Comment by kaiomagalhaes** [comment]
👍

**Comment by sshine** [comment]
I believe this feature was added, so I'm closing this issue.

Also, for the record, another feature was added that removes the mentor after not responding for a week.
