### ISSUE TITLE
Unable to submit.

### ISSUE THREAD

**Issue by RahulEcon** [exercism/exercism#4296]
Hi,
I've just completed your 'Hello World!' exercise for python but when I try to submit it I get an error message saying, "You are submitting a directory, which is not currently supported". I have not changed the directory and it is the same as the one the file originally downloaded to. I'm new to this so could you please help me out? Thank you in advance.

**Comment by NobbZ** [comment]
You need to specify the file(s) to submit, not a directory, so the command you need to use should look something like this `exercism submit hello_world.py`.

**Comment by RahulEcon** [comment]
Oh thank you. Figured it out.
