### ISSUE TITLE
Page navigation in 'Community solutions' stays on first page

### ISSUE THREAD

**Issue by LemuelCushing** [exercism/exercism#4297]
Trying to navigate beyond the first page of the 'Community solutions' isn't working. The ```pages=/d``` query string is added to the query string, but the page stays the same after reloading.

**Comment by iHiD** [comment]
@LemuelCushing I can't reproduce this. Is it still a problem for you? If so, do you have a sample URL pls?

**Comment by LemuelCushing** [comment]
Oh, sorry. It seems that it is no longer an issue, as I can't reproduce it now as well. Thanks!
