### ISSUE TITLE
Commenting should check solution_mentorship, not just track_mentorship

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4299]
When I've previously commented on someone's code in a track that I'm not (or no longer) a mentor of, I can _see_ their solution, but I cannot comment. I think that's fine :)

That said, I still have a button that says "comment".

We should figure out what the right way to indicate what your status is: why you're seeing this and that you cannot post.

**Comment by iHiD** [comment]
Could I have a screenshot please? These pages are fraught with different states, so I need to understand exactly what is rendered to understand what various codepaths are getting you into that state.

**Comment by kytrinyx** [comment]
I can't, because someone approved it after I posted this, so it's no longer in the same state.

**Comment by kytrinyx** [comment]
Wait. I'm wrong.

**Comment by kytrinyx** [comment]
<img width="422" alt="screen shot 2018-08-28 at 4 30 49 pm" src="https://user-images.githubusercontent.com/276834/44754612-c4252e00-aadf-11e8-99a4-068abe742e9f.png">

**Comment by iHiD** [comment]
Ah - I see. I didn't understand that you also get the comment box. 

Note to self: Avoid the abuse vector of banned-mentors still commenting.

**Comment by luchiago** [comment]
Hi, this issue still needs help?

**Comment by iHiD** [comment]
@luchiago Thank you for offering, but we're not accepting PRs to the website at the moment. If you'd like to help with Exercism in general, there will soon be lots of work across the language tracks.

**Comment by luchiago** [comment]
Ok, thanks for noticing me. Also, when the new issues are ready I want to help :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
