### ISSUE TITLE
Reaction notification is equally prominent as conversation/mentoring notifications

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4301]
I got a notification today that said:

> X has reacted to your solution to Leap on the Go track.

This was in a long list of notifications about comments and solutions on exercises that I'm mentoring.

I was very confused as to why, when I clicked the button, I was suddenly in the community solutions section of the site.

I feel like it would be useful if it were distinctly clear on the notification page that a notification is _meaningful_ (mentoring you've received, an approval, a new solution on something you're mentoring, a comment on something you're mentoring) as opposed to a vanity statistic.

When I put on my empathy hat, I do realize that other people might care about reactions 😁 but they're distinctly not _actionable_ in the same way that other notifications are.

**Comment by iHiD** [comment]
_(I was about to totally pounce on your penultimate paragraph before I saw your final one :))_

I think we maybe want something similar to how GitHub group notifications. For GitHub it's by repo, but for us it could be by type (mentoring/admin/reactions-comments/etc). I think that would achieve what you want but allow people to choose which they care about the most without us forcing that opinion on them. We can order the categories in the order we think matters most. Thoughts?

**Comment by kytrinyx** [comment]
@NobbZ I think you're right that there are several distinctions that seem useful.

Mentoring vs Student -- I probably want to look through all my mentoring notifications in the same sitting, and student ones separately.

Different languages -- if I'm mentoring in multiple languages I definitely want to stay in one mode throughout (I'm particularly bad at context switching). As a student I don't actually know if language matters. I think @NobbZ and @ErikSchierboom and @daveyarwood might be able to speak to that one.

**Comment by iHiD** [comment]
I'm happy to do the major groups and subgroups by language too.

**Comment by ErikSchierboom** [comment]
I think I would prefer to have them also grouped by language, as I usually focus on a single language at a time.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
