### ISSUE TITLE
Ability to see original exercise (for refactors only?) 

### ISSUE THREAD

**Issue by cheerfulstoic** [exercism/exercism#4315]
I was submitting my first mentor feedback for the Markdown exercise in the Elixir track and I realized I couldn't figure out how to see the original code so that I could compare the learner's solution to the original.  I realize this isn't normally a problem as the initial "solution" is generally empty functions, but for refactoring I could see this being very handy.

Asking on Slack, NobbZ pointed out that I could go [the repo](https://github.com/exercism/elixir) for the track, so a solution might be as simple as updating the mentor documents.

**Comment by sshine** [comment]
@cheerfulstoic: Super late reply: I would definitely visit the track repo for the stub, yes.

If you think that mentors on average don't know this, perhaps we have a communication problem.

I'm closing this issue now, but feel free to respond or reopen if this still matters to you.
