### ISSUE TITLE
Ability to navigate to my/tracks from Menu

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4316]
A link to "Tracks" above "Your profile" in the menu would help with navigation and is important for mobile.

<img width="241" alt="screen shot 2018-08-28 at 11 57 13" src="https://user-images.githubusercontent.com/5421823/44790147-715a7d80-ab96-11e8-87db-fea8a205b6fb.png">

**Comment by iHiD** [comment]
@jackhughesweb Can you PR this to master pls.
