### ISSUE TITLE
Can't download exercises

### ISSUE THREAD

**Issue by mu5tan6** [exercism/exercism#4321]
I recently upgraded to the latest version of exercism (3.0.9) and now I can't download exercises while at work.  I have the http_proxy and https_proxy environment variables set and everything worked on a previous version (2.2.6) but now it doesn't.  

Any suggestions?

Here is a dump of exercism troubleshoot
> exercism.exe troubleshoot

<details>
<summary> Troubleshooting Information</summary>

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.9
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: proxyconnect tcp: EOF

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\crchapma
Workspace: C:\Users\crchapma\Exercism (default)
Config:    C:\Users\crchapma\AppData\Roaming\exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: proxyconnect tcp: EOF]
    * 3.0241ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: proxyconnect tcp: EOF]
    * 3.0241ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```
</details>

_Edited for formatting -kytrinyx_

**Comment by rpottsoh** [comment]
Did you happen to use successfully any other versions of v3 prior to 3.0.9?

**Comment by mu5tan6** [comment]
Sorry, no.  I'm recently coming back to Exercism so haven't used it in a while.

**Comment by NobbZ** [comment]
He can't even do most of the steps, since due to the connectivity problems, he isn't even able to configure the token.

And it seems as if the CLI were trying to use the proxy. I do not have a proxy to test. All my internet connections are NAT'd.

But according to google, it seems that HTTPs support for proxies has only been added recently to gos stdlib.

@exercism/cli, which version of go is used to bundle the release? For me, from https://medium.com/@mlowicki/https-proxies-support-in-go-1-10-b956fb501d6b and https://golang.org/doc/go1.10#net/http, it reads as if HTTPS wasn't allowed before 1.10.

@mu5tan6: Could you please doublecheck if the variables are set up correctly, correct URL, username, password, schema, port etc?

**Comment by nywilken** [comment]
> which version of go is used to bundle the release? 

@NobbZ thanks for calling this out; I wasn’t aware that HTTPs proxy support was only in 1.10. We currently support building and testing on 1.9 and 1.10, which seems like it can no longer be. 

With that being said, I believe the last release was made with 1.10.3. I know we strip the debug info from our binaries so not sure if you can grab it from gdb. @kytrinyx can say for sure.

**Comment by nywilken** [comment]
> I believe the last release was made with 1.10.3.

I realize now that I might have built my version locally so please take this with a grain of salt and wait for confirmation from @kytrinyx.

**Comment by mu5tan6** [comment]
The variables are setup correctly.  I verified by rerunning debug using the old 2.2.6 version and the connection completed successfully.  I also set the proxy variable to incorrect values and reran 2.2.6 debug to make sure it would fail to connect and it did fail.  

So I am confident that my proxy settings are correct.

**Comment by NobbZ** [comment]
I installed a squid locally for testing:

```plain
$ HTTPS_PROXY=http://localhost:3128 exercism troubleshoot 

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.9
Latest:  3.0.9


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/nmelzer
Workspace: /home/nmelzer/exercism
Config:    /home/nmelzer/.config/exercism
API key:   c838*****************************75b

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 144.312653ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 207.690275ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

I have not configured squid for HTTPS though, so I can not check that one.

**Comment by NobbZ** [comment]
Ps: I did of course the countercheck, it fails when I point the environment variables to something not existing.

**Comment by kytrinyx** [comment]
I built the latest release with Go 1.10.3

**Comment by mdkling** [comment]
I believe I have the same issue.  I was successfully using Exercisim behind a proxy with CLI 2.4.1 in February 2018.  I just installed CLI 3.0.9 and 'exercisim configure' failed due to apparent proxy issues:

```
$ exercism configure --token=[redacted]
Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.

Get https://api.exercism.io/v1/ping: proxyconnect tcp: net/http: TLS handshake timeout
```

<details>
  <summary>$ exercism troubleshoot</summary>

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.9
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: proxyconnect tcp: net/http: TLS handshake timeout

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/kling
Workspace: /home/kling/exercism (default)
Config:    /home/kling/.config/exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: proxyconnect tcp: net/http: TLS handshake timeout]
    * 10.08934s

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: proxyconnect tcp: net/http: TLS handshake timeout]
    * 10.089647s


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

</details>

<details>
  <summary>$ exercism.legacy debug</summary>

```
**** Debug Information ****
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 3.0.9
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/kling
Config File: /home/kling/.exercism.json
API Key: c54e*************************5e2
Exercises Directory: /home/kling/exercism
Testing API endpoints reachability
        * GitHub API: https://api.github.com/ [connected] 95.7683ms
        * API: http://exercism.io [Get https://exercism.io/: x509: certificate signed by unknown authority] 833.5947ms
        * XAPI: http://x.exercism.io [Get https://x.exercism.io/: x509: certificate signed by unknown authority] 1.2214837s

A newer version of the CLI (v3.0.9) can be downloaded here: https://github.com/exercism/cli/releases/tag/v3.0.9

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
```
</details>
<p><p>
I don't think it matters in this case, but I'm using WSL Ubuntu on Windows 10.  I ran through the interactive walk-through, but it dead-ended after I couldn't configure the API key.

**Comment by mdkling** [comment]
exercism/cli#714 appears to be related

**Comment by kytrinyx** [comment]
@nywilken would you be able to compile a build for @mdkling and @mu5tan6 on your computer, and see if that works? I wonder if there's something weird going on with my installation of Go.

**Comment by nywilken** [comment]
> @nywilken would you be able to compile a build for @mdkling and @mu5tan6 on your computer, and see if that works? 

@kytrinyx I can definitely handle that. @mdkling, @mu5tan6 I’ll ping this thread once I push a build out. Thanks for sticking with us as we troubleshoot this issue.

**Comment by nywilken** [comment]
@mdkling @mu5tan6 please find the binary rebuilds at https://github.com/nywilken/exercism-cli/releases/tag/v3.0.9-go1.10.4. These binaries were built using Go 1.10.4.

I did some testing on my end using Charles proxy on Linux and WIndows and found that setting HTTPS_PROXY and HTTP_PROXY to the Proxy service provided by Charles works as expected. With the previous builds by @kytrinyx and my most recent builds. 

However, I did notice that when trying to connect on Windows with SSL Proxying turned on for https://api.exercism.io I received the error `x509: certificate signed by unknown authority` on Windows and was not able to connect. Which required me to trust a few certificates in order to get things to work. 

@mdkling looking at the output you provided for v2.4.1 I see that you are getting a bad certificate error for the two exercism endpoints. Meaning the client is not actually working. Had it worked you should see `[connected]` as the response for each of the endpoints. I'm not sure why GitHub failed in 3.0.9 yet. 
Do you know if your proxy, and Ubuntu install, have their root certificates up to-date? Have you tried using the windows binary in the standard windows command prompt (non WSL)? 

@mu5tan6 the same question for you. The EOF error that you are getting almost implies that the proxy is bailing for some reason. Have you tried running the debug command in 2.4.1? I am curious to see what the output is.

**Comment by mdkling** [comment]
Still getting errors:
"proxyconnect tcp: net/http: TLS handshake timeout" on WSL
"dial tcp: lookup api.github.com: no such host" on Windows


_https://github.com/nywilken/exercism-cli/releases/download/v3.0.9-go1.10.4/exercism-linux-64bit.tgz_
<details> 
 <summary>$ exercism.pr0 troubleshoot</summary>

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.9
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: proxyconnect tcp: net/http: TLS handshake timeout

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/kling
Workspace: /home/kling/exercism.pr0 (default)
Config:    /home/kling/.config/exercism.pr0
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: proxyconnect tcp: net/http: TLS handshake timeout]
    * 10.092076s

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: proxyconnect tcp: net/http: TLS handshake timeout]
    * 10.092191s


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```
</details>

<br/>
<br/>
<br/>

_https://github.com/exercism/windows-installer/releases/download/v1.5.3/ExercismCLIInstaller.exe_
<details>
  <summary>PS C:\Users\user> exercism.exe troubleshoot</summary>

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.9
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: dial tcp: lookup api.github.com: no such host

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\user
Workspace: C:\Users\user\Exercism (default)
Config:    C:\Users\user\AppData\Roaming\exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: dial tcp: lookup api.github.com: no such host]
    * 497.7µs

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: dial tcp: lookup api.exercism.io: no such host]
    * 35.1279ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```
</details>

<br/>
<br/>
I have limited control over my Windows certificates, but they should all be in order on the Windows side.  However, it looks like there are some certificates that I need to manually import on the WSL side (cf. Microsoft/WSL/issues/316).  I'll see if I can figure that out and let you know if it makes a difference.

**Comment by mu5tan6** [comment]
No change for me either:
I have not tried 2.4.1 but I do have 2.2.6 and it works.
 ************************************************************************************************************
Here is output from new 3.0.9 build.
exercism.exe troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.9
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: proxyconnect tcp: EOF

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\crchapma
Workspace: C:\Users\crchapma\Exercism (default)
Config:    C:\Users\crchapma\AppData\Roaming\exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: proxyconnect tcp: EOF]
    * 3.0139ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: proxyconnect tcp: EOF]
    * 3.0139ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
**********************************************************************************************
**********************************************************************************************
and output from 2.2.6

> exercism.exe debug

**** Debug Information ****
Exercism CLI Version: 2.2.6
Exercism CLI Latest Release: 3.0.9
OS/Architecture: windows/amd64
Build OS/Architecture windows/amd64
Home Dir: C:\Users\crchapma
Config file: C:\Users\crchapma\.exercism.json
API Key: Please set your API Key to access all of the CLI features
Exercises Directory: C:\Users\crchapma\exercism
Testing API endpoints reachability
        * GitHub API: https://api.github.com/ [connected] 305.9934ms
        * API: http://exercism.io [connected] 1.2359148s
        * XAPI: http://x.exercism.io [connected] 1.2409192s

A newer version of the CLI (v3.0.9) can be downloaded here: https://github.com/exercism/cli/releases/tag/v3.0.9

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

**Comment by kytrinyx** [comment]
For a moment I thought that maybe this has something to do with the fact that the old exercism was HTTP, whereas this one is HTTPS... but the new CLI is also unable to connect to GitHub (https://api.github.com), which means that this is likely not relevant.

I honestly don't know what question to ask here. @nywilken @NobbZ -- if you have any ideas, that would be welcome!

**Comment by nywilken** [comment]
@mu5tan6 do you have both HTTP_PROXY and HTTPS_PROXY set? If so are they pointing to the same proxy URL? 

If HTTPS proxy is different from HTTP_PROXY what happens when you set the variable to the same HTTP value?

Also have you tried setting only one of the variables? 

That error seems to imply that it is unable to connect to your Proxy.

**Comment by mu5tan6** [comment]
Thank you @nywilken for the suggestion.  Removing the HTTPS_PROXY value solved the problem.  I am finally back up and running.  Any thoughts on why it worked with the older version of exercism?

**Comment by mu5tan6** [comment]
Also, removing the HTTPS_PROXY variable breaks other applications, Pip for instance.  I wasn't able to install the pytest module until I restored the HTTPS_PROXY variable.  I think there might still be a problem with the exercism CLI but at least I have a work around now.

**Comment by NobbZ** [comment]
You can `unset HTTPS_PROXY` in a shell session dedicated to exercism, or write a wrapper script:

```
#!/usr/bin/env bash

unset HTTPS_PROXY
exercism "$@"
```

Save this as `proxycism` or however you like (but not `exercism`) in your PATH and use it in the future. Don't forget to `chmod +x` it!

**Comment by mu5tan6** [comment]
Thanks @NobbZ for the suggestion.  Your wrapper is for Linux and I'm in Windows but I can probably do the same thing with a batch file.  Or try really messing things up and using the new Windows Bash shell to run exercism:)

**Comment by mdkling** [comment]
I'm still having certificate issues on the WSL side, but I've got the Windows client working now, so I think it's close-able on my end.

**Comment by mu5tan6** [comment]
My issue is handled so yes as far as I'm concerned it can be closed.

**Comment by iHiD** [comment]
Thanks both.
