### ISSUE TITLE
Independent mode students can't unsubmit an exercise submitted for mentoring

### ISSUE THREAD

**Issue by coriolinus** [exercism/exercism#4322]
I have [an exercise](https://exercism.io/my/solutions/6c9c1c2169a9488aad6d7510da9292cb) which has been sitting in the mentoring queue for over a month. I am in independent mode for this track. 

In the time since, I've completed other exercises which would be more interesting to talk about. However, given that independent mode restricts one to a single mentoring request at a time, I'm currently stuck just waiting for someone to get to it before I can proceed. 

Requested feature: students in independent mode can withdraw an exercise from mentoring consideration, freeing them to submit a different exercise.

**Comment by iHiD** [comment]
This will be fixed by https://github.com/exercism/website/pull/413
