### ISSUE TITLE
Robot name in scala is missing

### ISSUE THREAD

**Issue by LoafingBunny** [exercism/exercism#4325]
the main class Robot that the student should complete is missing. There are just the tests with broken dependencies

**Comment by NobbZ** [comment]
As the file doesn't exist in the repository as well, you are probably meant to implement it from scratch.

**Comment by LoafingBunny** [comment]
I think that at least an API is required to solve an exercise.

**Comment by LoafingBunny** [comment]
ok that was expected
https://github.com/exercism/scala/issues/484#issuecomment-358470175

**Comment by NobbZ** [comment]
I'm not doing any scala in my real life or on exercism, but I did other tracks that did not provide any stubs.

All of them were solvable, and in pure TDD (aka tests first), you start with a test that fails because there is not even a class.
