### ISSUE TITLE
Track sign-up: "Normal mode" vs "Mentored mode" on button

### ISSUE THREAD

**Issue by ardrigh** [exercism/exercism#4327]
I noticed when I visited the updated website (great work!) that the text for the Go track offered me a "Normal mode" and Independent Mode.

I signed up for the Rust track, and that offered me a "Mentored mode (Recommended)" vs Independent mode. Other tracks like Bash and Python use this same text.

Is the Go track text using an old button text?

**Comment by iHiD** [comment]
It should be "Mentored Mode" everywhere. Thanks :)

**Comment by PatrickMcSweeny** [comment]
![screenshot from 2018-09-12 11-35-03](https://user-images.githubusercontent.com/1254212/45436124-09209700-b680-11e8-80eb-f873a5fbf8cc.png)

@ardrigh Is this the screen you're you were talking about?

**Comment by PatrickMcSweeny** [comment]
[This line](https://github.com/exercism/website/blob/master/app/views/my/tracks/_started_modal.html.haml#L13) in the view code says "Mentored Mode" and [this line](https://github.com/exercism/website/blob/master/test/system/join_track_test.rb#L22) in the tests specifically looks for a button that says "Mentored Mode"

**Comment by ardrigh** [comment]
I didn't capture a screenshot at the time, but yes it was that dialogue that was showing the "Normal mode" text.

I just left the Go track and rejoined the Go track, and the text now appears with "Mentored mode" as expected :+1:

**Comment by iHiD** [comment]
The incorrect button is [here](https://github.com/exercism/website/blob/6643f91a458313991a0db3ab0c80b9c7ea181652/app/views/my/tracks/_v1_migration_modal.html.haml) if anyone wants to PR it.
