### ISSUE TITLE
Track sign-up: Unable to cancel sign-up process

### ISSUE THREAD

**Issue by ardrigh** [exercism/exercism#4328]
When I go to add a new track, I press the 'Join track' button and the UI appears giving the option of which mode to choose.

There doesn't appear to be any way to cancel this UI in the browser (or just Firefox?). I tried pressing Escape key, and there are no back/cancel visible action buttons on the screen.

Using the 'Back' option in the browser was the only way to remove the window, which leaves the user unable to continue reading the page beneath.

Update: When using the Back option in the browser the new track appears under https://exercism.io/my/tracks
When I click on the track it takes me back to the UI to select a mode, even though I have tried to cancel out of this sign-up process.

I then have to join and leave the track to remove it from my tracks screen.

**Comment by guygastineau** [comment]
I don't work on that part of the website, but it sounds like clicking join signs you up to the track, and it requires you to choose which mode you would like for the track.

Letting a user cancel selecting the mode would leave them signed up without being designated as mentored or independent mode.

It sounds like you would prefer if the signing up for the track were deferred by the backend until the mode selection is made.  This should make it safe to have a cancel option at the step where you're wanting it.

Only someone more involved than I am could say whether or not that is desirable behavior.

**Comment by sshine** [comment]
@guygastineau: That does sound like desirable behavior.

**Comment by guygastineau** [comment]
Well, I notice a silly assumption in my previous comment now.

We should verify that this behavior hasn't already been implemented unbeknownst to this issue.

**Comment by iHiD** [comment]
My take on this is that when you click "Join track" you intend to join the track, which is what happens.

Once you've joined the track, the first step is to choose the mode. Soon there will be other steps too. It's not like there is a barrier being placed (e.g. a paywall or some action beyond a simple button click). So I think this current behaviour is pretty acceptable tbh.

**Comment by sshine** [comment]
@guygastineau: This is still current behavior.

@iHiD: Sounds reasonable.

I've re-labeled it as `type/improvement` and we can refer to this issue should the need arise.

In the meantime, I'm closing the issue.
