### ISSUE TITLE
"Download" and "Submit" command line hints are editable

### ISSUE THREAD

**Issue by gDelgado14** [exercism/exercism#4329]
The command line hints which the user can copy are for some reason input boxes. This means a user can edit them and copy them.

Here's an example screenshot:

![uhoh](https://i.imgur.com/1tf4AQW.png)

This means that the user will be able to copy that dangerous command onto their clipboard!

**Comment by iHiD** [comment]
Thanks. If anyone wants to fix this they'd be welcome. Pls add system test. Thanks :)
