### ISSUE TITLE
Devise bypass option is deprecated

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism#4330]
While running the system tests locally I got the following warning:

DEPRECATION WARNING: [Devise] bypass option is deprecated and it will be removed in future version of Devise. Please use bypass_sign_in method instead.

Referring to this line: 

https://github.com/exercism/website/blob/master/app/controllers/my/settings_controller.rb#L23

**Comment by iHiD** [comment]
Thanks @PatrickMcSweeny. I'd happily accept a PR for that.
