### ISSUE TITLE
Re-submitting exercise does not update code 

### ISSUE THREAD

**Issue by stiad** [exercism/exercism#4331]
For some reason when I submit an exercise and later make a modification prior to a mentor viewing it, and sometimes after a mentor has viewed it, it will allow me to submit the exercies but does not update the code shown.

**Comment by EarthlingRich** [comment]
On the top right of the solution page there are small boxes with a number. These are the submitted itterations. Do you have those?

**Comment by stiad** [comment]
I do now, does it only iterate after the mentor has commented?

**Comment by EarthlingRich** [comment]
Nope, it should be there when you submit.

**Comment by iHiD** [comment]
Can you post a screenshot and a link to a solution uuid when this happens next for you please.

**Comment by stiad** [comment]
This doesn't seem to be an issue for me anymore, I think we can chuck it up to caching issues on my side.
