### ISSUE TITLE
SUBMIT

### ISSUE THREAD

**Issue by AndyS97** [exercism/exercism#4332]
Hi, I'm new at exercism and I'm having some troubles. I just don't know how to submit an exercise. Can somebody walk me through it? Please.

**Comment by rpottsoh** [comment]
Have you downloaded an exercise? 

Exercism upload -h will provide some help.

Make sure you have read https://exercism.io/getting-started


Sent from my android device.

**Comment by AndyS97** [comment]
exercism submit PATH/TO/FILE that I'm having trouble. The exercise should be at the Exercism file that they provide? I'm typing this way at the command prompt: exercism submit C:\Users\User Acer\Exercism\java. I tried putting exercism submit Greeter.java but I'm getting this message in both cases:  The file you are trying to submit cannot be found.

**Comment by rpottsoh** [comment]
Did you configure the cli?  The file your uploading must appear in the workspace.


Sent from my android device.

**Comment by NobbZ** [comment]
@rpottsoh it is `exercism submit -h`, not `upload`.

----

@AndyS97 It sounds as if you are doing `hello-world` on the java track. The file has to stay exactly where it was downloaded to. Assuming you have default settings, that file should have been downloaded to `%HOME%\Exercism\java\hello-world\src\main\java\Greeter.java`, also there should be some more files and folders at `%HOME%\Exercism\java\hello-world`.

Most of those files are build- or test-instructions, your actual solution belongs to the `Greeter.java` file.

To submit it `cd` into `%HOME%\Exercism\java\hello-world` and from there `exercism submit src\main\java\Greeter.java`.

**Comment by rpottsoh** [comment]
>  it is exercism submit -h, not upload.

My bad, the price one pays when working from memory and typing on their phone.  Thanks for correcting.

**Comment by NobbZ** [comment]
1. If your PATH contains spaces, you need to quote it, eg: `"C:\Users\User Acer\Exercism\java\hello-world\src\main\java\Greeter.java"`.
2. When trying to use a relative path, you need to `cd` into the appropriate base folder first. If you want to use `exercism submit src\main\java\Greeter.java` to submit, you need to `cd "C:\Users\User Acer\Exercism\java\hello-world"` first.

Also you should probably change the name of the user (or the home dir at least), as spaces in file- and pathnames often will make you problems with many programs.

**Comment by AndyS97** [comment]
@NobbZ Thank you very much. The problem was the " ", I actually felt a little dumb because while I was looking for solutions to the problem I read somewhere about this and I totally forgot. Thank you, you helped me a lot, now I can go on learning.
