### ISSUE TITLE
exercism download --exercise=leap --track=javascript  .... doesn't.

### ISSUE THREAD

**Issue by mcampbell** [exercism/exercism#4334]
Running this command downloads the following files, but no "leap.js", nor anything that resembles a skeleton file to edit.  Is this something on exercise 2 I'm supposed to know?

```
% ls
total 32
drwxr-xr-x  6 mcampbell  staff   204 Sep  5 20:11 ./
drwxr-xr-x  3 mcampbell  staff   102 Sep  5 20:11 ../
-rw-------  1 mcampbell  staff   216 Sep  5 20:11 .solution.json
-rw-r--r--  1 mcampbell  staff  1489 Sep  5 20:11 README.md
-rw-r--r--  1 mcampbell  staff   636 Sep  5 20:11 leap.spec.js
-rw-r--r--  1 mcampbell  staff  1608 Sep  5 20:11 package.json
```

The same happens for me on mac or linux

**Comment by NobbZ** [comment]
This is by design of the track, you are required to implement it on your own.

**Comment by tejasbubane** [comment]
Yes this is by design, please find the instructions for running tests here: https://exercism.io/tracks/javascript/tests. When you run the tests, you should see some error like this:

```
 FAIL  ./leap.spec.js
  ● Test suite failed to run

    Cannot find module './leap' from 'leap.spec.js'
```

First line in `leap.spec.js` tries importing the solution file:
```js
import { isLeap } from './leap';
```

You are supposed to create this file and add your solution there.

**Comment by tejasbubane** [comment]
@viktorhbk Can you share your `leap.js` file? Note that spec file expects named export (not default). https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#Description

**Comment by viktorhbk** [comment]
leap.js
```
export const isLeap = (year) => {
	if(year % 4 === 0) {
		if(year % 100 !== 0 || year % 400 === 0)  {
			return true;
		}
	}
	return false;
}
```

**Comment by tejasbubane** [comment]
That looks all good to me. If you have `leap.js`, `leap.spec.js`, `package.json` in the same directory, it should work. Can you make sure these files are in same directory and show the complete error that you are getting?

**Comment by viktorhbk** [comment]
![leap](https://user-images.githubusercontent.com/33513522/47101748-9fc61200-d243-11e8-81d3-6fd5918d6acf.PNG)

**Comment by tejasbubane** [comment]
Ok I am unable to spot the issue here. Is the editor not saving file because of eslint errors or something?

@matthewmorgan can you see what is wrong here?

**Comment by matthewmorgan** [comment]
@viktorhbk I think the linting issue is a Windows related issue.  Someone else mentioned this in https://github.com/exercism/javascript/issues/502#issuecomment-430649864.

I think this is not the same issue as @mcampbell has reported.  Can we disentangle these please?

@mcampbell did @NobbZ answer your question?

**Comment by NobbZ** [comment]
I'm a bit confused here. Is this windows or is this linux? If the former, are you using WSL or a POSIX wrapper? Are you sure both your `bash` as well as VScode are looking at the same directories? Can you confirm so by using `ls` and `cat leap.js`?

**Comment by viktorhbk** [comment]
@NobbZ Can confirm that after changing CRLF to LF in editor it worked. I'm using wsl.

**Comment by iHiD** [comment]
Closing this as it's stale. Feel free to reopen if still relevant.
