### ISSUE TITLE
UX: Links not easily sharable.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism#4337]
It's not easy to share a link to a solution.

The standard link when looking at one of my solutions is: https://exercism.io/my/solutions/a42418ff7a574868b8df23028c2ebadd

But if I try to share this with anyone they get show an error message (maybe after being  redirected to a sign in page.)

> Oh dear, we can't find that page. Sorry about that.
> Continue by heading back to the homepage.

It is possible to share if you go to the community solutions and find yours and copy *that* link:

https://exercism.io/tracks/ruby/exercises/hello-world/solutions/a42418ff7a574868b8df23028c2ebadd

But this is not at all easy or intuitive.

Suggestion, replace the "my" in the "standard" url with the username, so that: 

https://exercism.io/Insti/solutions/a42418ff7a574868b8df23028c2ebadd

Is the main url in the browser and if this url is shared it is accessible to non-logged in users.

**Comment by iHiD** [comment]
There are various versions of those links
- `/my` is private to the user
- `/mentor` is for mentors
- `/admin` is for admins.

None of them are designed to be be publically shared. As you say, the community solution link is the one that is designed for that, so I think we should maybe expose that more clearly.

I've long considered redirecting `/my/...` to the community solution if you're a different user, but I'm not sure whether I like it or not as an idea.

**Comment by Dr-Emann** [comment]
There's a wrinkle for mentors: `/my/...` may not have a community solution link. For mentors, it might make sense to redirect to the the `/mentor/...` link for them.

Ideally, there would be a canonical `/solution/ID`, which, depending on what you're logged in as, shows either the `/my` UI, the `/mentor` UI, the `/admin` UI (which I'm not familiar with), the community solution UI, or a permission denied UI, and navigating via any of the prefixes should redirect to the proper prefix.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
