### ISSUE TITLE
My C# track solutions not appearing in mentors backlog

### ISSUE THREAD

**Issue by FilippoElia** [exercism/exercism#4339]
It's two week I am not receiving any mentor comment, despite I have submitted solutions.
I have chatted with one of the mentors who told me that none of my solutions were appearing in their "to be replied" list. He suggested to upgrade my client and re-submit, I did it, moving from 3.0.5 to 3.0.9 and re-submit one of my solutions, but it did not work.
To be noted that I started the track in independent mode and then moved to mentored mode, with already a few exercises in the main stream ready to be commented (actually some of them have been indeed replied by mentors, meaning that at least some were in their list).
At the moment I have two exercises in the main stream ("allergies" and "saddle points") and around ten extra-exercises waiting for mentor comments.
Thanks for helping me out of the deadlock.
BTW let me thank you for your great job. The site and the service your are offering is awesome! Thank you all!

**Comment by Joerg9** [comment]
Hi, I've started the C# track in the independent mode too. Then I changed it to mentor mode. I didn't get any comments yet but I don't know how long I have to wait. I can't proceed so I will wait.

But switching the mode maybe cause a problem.

**Comment by FilippoElia** [comment]
On average, before getting stuck as described above, the mentors were pretty reactive. They replied within a couple of days, worst case.

**Comment by Joerg9** [comment]
I just got an answer. So they're pretty fast. And it works !

**Comment by FilippoElia** [comment]
I switched to independent and than back to mentored mode... I guess I have unblocked the situation.
The button "request for feedback" was available again.

**Comment by m4lvin** [comment]
Does this maybe also affect the C track? I am waiting for a reply on my first submission there.

**Comment by FilippoElia** [comment]
> Does this maybe also affect the C track? I am waiting for a reply on my first submission there.

How long have you been waiting?  My impression is that I somehow triggered an anomaly switching from independent to mentored modes... the point is that I am not getting support ...

**Comment by m4lvin** [comment]
I have been waiting for two weeks now, I think. But I never switched modes for the C track.

**Comment by FilippoElia** [comment]
in my case, when the platform was working properly, I was getting replies within two days. Much less on average. You may be stuck in the same problem of mine ... 
BTW are you using an anonymous profile on exercism? I am, and if you are too may be a clue.

**Comment by Joerg9** [comment]
Is it a main or an extra exercise? The extra or bonus exercises are taking much longer.

**Comment by Joerg9** [comment]
I got response for a couple of main exercises within one or two days. And I am still waiting for the extra exercises, that's about two weeks now. One of the mentors told me that the main exercises have priority so that you can go forward. 

Now go to your track and take a look: How many students and how many mentors are there? Assume that every student submits an exercise every day. That's the amount of exercises the mentors have to look at. So I've learned some patience.

**Comment by FilippoElia** [comment]
> Now go to your track and take a look: How many students and how many mentors are there? Assume that every student submits an exercise every day. That's the amount of exercises the mentors have to look at. So I've learned some patience.


I know that they are doing a great job and I can only thank for the support I got. I can wait no problem, but I do think that a bit of feedback and timing "predictability" is needed.
Actually, still I do not know if my last request for comment has been queued in mentors back log or not (the previous one was not I am sure of that because I chatted with a mentor, then I switched back on forth from independent and mentored mode and the problem seemed to be fixed because I got a reply on a main exercise, then I requested a feedback on an extra one and I am waiting for that)

**Comment by Joerg9** [comment]
Your are right. Communicating the current waiting time would be helpful.

I switched from non-mentored to mentored too. I've got four replies of main exercises but no replies of bonus exercises yet. And I don't know whether they have been queued in the mentors back log.

**Comment by iHiD** [comment]
Hello. Bonus exercises will be queued but appear behind core exercises. We're about to change the functionality so that people only receive mentoring on bonus exercises if they specifically ask for it and limit how many bonus exercises can be queued at any time. That should remove the burden for mentors and mean more exercises get mentored. We'll launch that this week.

**Comment by iHiD** [comment]
Tracking issue for that here: https://github.com/exercism/exercism/issues/4375

**Comment by FilippoElia** [comment]
Thanks Jeremy.
I am not optimistic because I did request for mentoring on a unique bonus exercise without receiving it. My issue is different I am afraid.
