### ISSUE TITLE
"pub" not found on windows

### ISSUE THREAD

**Issue by symedley** [exercism/exercism#4342]
following the absolute beginner instructions for exercism on windows,
on ths page
https://exercism.io/tracks/dart/tests#windows
the command 
C:\Users\JaneDoe>pub get
fails because there is no pub or pub.exe or pub.bat or pub.bash.
What am i missing?

**Comment by NobbZ** [comment]
You probably missed the installation steps described at https://exercism.io/tracks/dart/installation

**Comment by symedley** [comment]
it would be real helpful to know where 'pub' is supposed to be installed....

**Comment by rpottsoh** [comment]
@symedley also be aware that the CLI command is `download` and no longer `fetch`.  The instructions at the link you mentioned in your opening comment need to be updated.

You will need to indicate via. the website that you are interested in working on a particular exercise before the CLI will allow you to `download` it.

I'm sorry I can't answer your actual question about `pub`, I don't know anything about it.

@exercism/dart

**Comment by NobbZ** [comment]
`puv.bat` should be in the very same folder as `dart.exe`. both in the bin folder of the SDK.

**Comment by Stargator** [comment]
@symedley, @NobbZ was correct it seems you missed the steps to install Dart.

`pub` is apart of the Dart SDK. When you install Dart, `pub` will be found in the Dart bin/ folder.

**Comment by symedley** [comment]
Okay. Got it. It's pub.bat, and even though /c/src/flutter/bin/cache/dart-sdk/bin is in my path, batch files aren't found by path, so i have to type the whole path (or alias something).
i.e.
/c/src/flutter/bin/cache/dart-sdk/bin/pub.bat get

**Comment by Stargator** [comment]
@symedley Why are you using flutter's cache directory instead of installing Dart standalone?

**Comment by symedley** [comment]
Good question. I'm not sure. I started with flutter, and then didn't want to make a duplicate installation of dart, I guess. Will it make a difference? Should i do a standalone install of dart and then point flutter to the standalone installation? Or should I let flutter maintain its own copy of dart?
