### ISSUE TITLE
Local development website blocked for WSL

### ISSUE THREAD

**Issue by bencoman** [exercism/exercism#4346]
This is a notice to anyone struggling to run a local copy of the website on Windows Subsystem For Linux.
This seems blocked by "socketpair() syscall ignores non-blocking request (SOCK_NONBLOCK, O_NONBLOCK)" Microsoft/WSL#3100.  

This is reported fixed in build 17666, next scheduled release [Version 1809 (October 2018)](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1803_(April_2018_Update))
Current Windows Insider Slow Ring build 10.0.17754 (11 Sept 2018)

Install log exercism/pharo#103 from my OS build 17134.285 Version 1803 (April 2018 Update). 

Happy to hear from anyone that worked around this issue. I'm currently running the website on another local non-Windows machine.

Get your Windows Version with ```winver```.

**Comment by iHiD** [comment]
Is this still an issue?

**Comment by bencoman** [comment]
My system current status is...
C:> ver
Microsoft Windows [Version 10.0.17134.407]

and I'm not in a position right now to use the "Insider builds"
However it shouldn't be much longer before this should generally be able to be tested...
https://blogs.windows.com/windowsexperience/2018/11/13/resuming-the-rollout-of-the-windows-10-october-2018-update/
https://www.microsoft.com/en-us/itpro/windows-10/release-information

> Notice: November 13, 2018: We have resumed rolling out all editions of Windows 10 October 2018 Update, version 1809, for Windows client and server. 

So we should be able to get a firm indication within a month.

**Comment by kenliu** [comment]
bump

**Comment by iHiD** [comment]
@kenliu What action are you bumping? :)

**Comment by kenliu** [comment]
Sorry for not being clear there. Was thinking this issue could be closed since it was pending a Windows Update in October 2018.

**Comment by bencoman** [comment]
I raised the issue it so I should have another go at it, however I'm unable to get to it for a few weeks.
@kenliu, are you able to try it per https://github.com/exercism/pharo-smalltalk/issues/103?
