### ISSUE TITLE
Powershell track is invisible

### ISSUE THREAD

**Issue by y0rrik** [exercism/exercism#4348]
Currently, Powershell track is invisible. It cannot be found at the main page.
It's not even shown as a 'Joined' though I follow the track.
Everything else works pretty fine (cli commands to get/submit tasks, web interface and email updates)

It has been discovered by googling and getting a straight link to the track.

**Comment by iHiD** [comment]
Thanks for posting the issue. The PowerShell track is [not yet launched](https://github.com/exercism/powershell/blob/master/config.json#L3).
