### ISSUE TITLE
Commenting on a submission moves it down the queue in the mentor dashboard

### ISSUE THREAD

**Issue by tekerson** [exercism/exercism#4349]
While mentoring a recent solution, I think I've come across an issue; If the student/author comments on their own submission some time after the initial submission it seems that the submission is pushed down the queue on the mentor dashboard.

I believe the solutions in the dashboard are ordered oldest first (within core/non-core), but are they ordered by submission date or last activity date? I don't believe that just commenting should push the submission to the back of the queue.

**Comment by iHiD** [comment]
Nice spot. Thank you. I've fixed this as part of https://github.com/exercism/website/pull/413
