### ISSUE TITLE
Cli does not expand ~/

### ISSUE THREAD

**Issue by GotFlojo** [exercism/exercism#4351]
# I think the cli client (linux 64 3.0.9) creates faulty config files everywhere you run it.
I downloaded the cli  from github because the Fedora 28 version is buggy and crashes.
The thing is: I have a config in

>  $HOME/.config/exercism

 but exercism complained it is unconfigured.

With `configure --token=foo` I got it working again. 
I then changed the directory I was in and wanted to use it again when _again_ it complained about a missing token. 
That got me confused and I looked into the config and `exercism troubleshoot` and noticed the settings to be: `Config: ~/.config/exercism `
I then had a deeper look into the previous dir where it had worked before and noticed the following:

exercism seems to create `~/.config/exercism` - **literally**. It does not expand the `~` to `$Home.` so
wherever I run exercism it will create this `~/.config/exercism `directory structure even in my /home dir it will create a `~/` directory. 
This is incredibly annoying.

**Comment by NobbZ** [comment]
I see 2 issues here:

1. The `~` doesn't get expanded
2. Why is there `~` at all? Have you set `XDG_CONFIG_HOME` or `EXERCISM_CONFIG_HOME` to have that `~`?

**Comment by GotFlojo** [comment]
Hi
had a look at `env` and `XDG_CONFIG_HOME` was indeed set to `~/.config`
I set it to `$HOME/.config`. Now it seems to work. I'm not sure how it got set and if if survives a reboot but so far so good.

**Comment by GotFlojo** [comment]
Ok, I feel quite embarassed somewhere in my convoluted zshrc XDG_CONFIG_HOME got set to ~/.config.
Fixed now and everything is fine

**Comment by NobbZ** [comment]
I'm happy you was able to fix your problem permanently, still I consider it a bug that `~` doesn't get expanded to the equivalent of `$HOME`.

@exercism/cli
