### ISSUE TITLE
I found a workaround for un-unlockable exercises

### ISSUE THREAD

**Issue by guygastineau** [exercism/exercism#4352]
After completing all core exercises in the Bash track I was initially dismayed that new exercises I added were not unlocked for me.

Today I realized that I can download them with the cli and that finally unlocks them in the GUI.

I know some other maintainers keep a development account in independent mode.
I thought many people would be relieved to learn about this behavior.  Also, I wanted @kytrinyx and @iHiD to know about this in case it means there is a bug somewhere.

In the meantime I am just happy that I can now do the exercises that I added.

**Comment by kytrinyx** [comment]
I *think* this is a bug, but it certainly is useful for maintainers :)

@iHiD what do you think of adding a rule in the API that if you're listed as a maintainer or mentor on the track, you can download locked exercises (but can't submit them until you unlock them in the UI)?

**Comment by guygastineau** [comment]
Thank you @kytrinyx.

Should this get the bug label?
I can't add it in this repo.

**Comment by iHiD** [comment]
Posting to something like `https://exercism.io/my/solutions?exercise_id=gigasecond&track_id=cfml`

I think this issue can be closed. Do you agree?

**Comment by guygastineau** [comment]
Yes
