### ISSUE TITLE
It would be helpful to have more expressive page meta titles

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4356]
This is my current set of open tabs:

<img width="1413" alt="tabs" src="https://user-images.githubusercontent.com/276834/45599029-e48b2e80-b9a1-11e8-9545-0b6ff76afaf8.png">

One of these is the mentor dashboard :)

Here's another set of tabs that I had open recently (this was mid-workday, during a deploy of a PR entitled _Add logging for strict validation of legacy lenient JSON schemas_.)

<img width="1423" alt="tabs-deploys" src="https://user-images.githubusercontent.com/276834/45599058-7135ec80-b9a2-11e8-99ef-246920c29f6e.png">

The things that would help me the most when looking at the tabs for Exercism are:

Which user is this?
Which exercise is this?
Which track is this?
Which page is this?

In terms of mentoring, something like this would help:

_Mentor Dashboard &middot; Exercism_
_`username1` &middot; Go/TwoFer &middot; Exercism_
_`username2` &middot; Go/TwoFer &middot; Exercism_

**Comment by iHiD** [comment]
If anyone would like to implement this, [this](https://github.com/exercism/website/blob/master/app/helpers/metadata_helper.rb#L28) is the bit of code that needs things adding to it.

**Comment by sfairchild** [comment]
I can look at this one.

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/417
