### ISSUE TITLE
Deprecated exercises in non-logged in user track view

### ISSUE THREAD

**Issue by hilary** [exercism/exercism#4360]
If you view a track as a non-logged in user, deprecated exercises appear in the view. While that may have been desirable in exercism v1 (or not, might have been a bug), I would argue that it is not desirable in exercism v2.

Rationale:
- What that view does: If you click on an exercise, it takes you to a page of community solutions
- The role of community solutions is changing in exercism v2; we're moving to something more like model solutions...
- Model solutions for deprecated exercises doesn't make sense (at least, it doesn't to me!)

**Comment by iHiD** [comment]
Agreed. I've marked this with community-pr-welcome.
