### ISSUE TITLE
Source link for "Two Fer" exercise is unrelated

### ISSUE THREAD

**Issue by spazm** [exercism/exercism#4361]
the "Two Fer" exercise lists a "Source" of https://en.wikipedia.org/wiki/Two-fer , which is a pretty sparse disambiguation page that has nothing to do with the problem.

(at least as viewed just now on the #perl5 track)

Any idea where this question originated so we credit them with a link back?

**Comment by rpottsoh** [comment]
See for background on this exercise 
https://github.com/exercism/problem-specifications/issues/757

Sent from my android device.

**Comment by iHiD** [comment]
@kytrinyx Any ideas on this pls?

**Comment by hilary** [comment]
I'll do this one, and use https://github.com/exercism/problem-specifications/issues/757 as the source link.

**Comment by rpottsoh** [comment]
exercism/problem-specifications#1350 has been merged, I think this is can be closed.

**Comment by iHiD** [comment]
Thanks @rpottsoh

**Comment by mbbroberg** [comment]
Thanks for fixing it @hilary! 

This looks to take care of your request @spazm. I'll close this issue as resolved. Thank you for catching it and bringing up the need 👍

**Comment by spazm** [comment]
Woohoo, thanks all!
