### ISSUE TITLE
Can I haz onboarding?

### ISSUE THREAD

**Issue by GantMan** [exercism/exercism#4362]
![wtf](https://user-images.githubusercontent.com/997157/45765433-a89ed600-bbfa-11e8-9fe1-5c7ecb768744.gif)

**Comment by iHiD** [comment]
Hmmm. That's not good! 

@GantMan Any ideas what might be causing this? What's your browser, OS, etc?
@kntsoriano Can you look at this asap pls?

**Comment by GantMan** [comment]
I'm on Mojave, and I get the same problem on Chrome or Safari!

I'm a long time member, just trying to do the upgrade to the new system.  No clue why it's complaining.  My Safari is pure vanilla.

**Comment by kntsoriano** [comment]
@GantMan Any way I can get in touch with you privately? Just need to ask a few questions in order to resolve this.

**Comment by GantMan** [comment]
@GantLaborde on Twitter and Gant with the domain infinite.red for email

**Comment by GantMan** [comment]
So the issue seems to be that my GitHub email was not passing internal verification.  Fair enough, but now that I've fixed my GitHub email, I can't seem to clear the cache exercism server-side.
