### ISSUE TITLE
Show student names to mentors on solution pages, if available

### ISSUE THREAD

**Issue by dpolivaev** [exercism/exercism#4363]
As a mentor, I want to easily see student's names on the solution page so that I can properly address them in my comments. 

Currently, only the student's login name is displayed.

**Comment by NobbZ** [comment]
What other name would you like to see?

**Comment by dpolivaev** [comment]
Information from the profile page, if it exists. In some cases I was able to find the link, but as it does not always exists, it is not always easy.

**Comment by NobbZ** [comment]
So you want to write like this:

> Hello Norbert, don't you think calling `foo` where much easier to read than `bar`?

Instead of this:

> Hello @NobbZ, don't you think calling `foo` where much easier to read than `bar`?

As a user who massively relies on notifications and at-mentions, I prefer the latter.

**Comment by dpolivaev** [comment]
I see advantage of at-mentions only in group discussions (slack channels, forum threads or similar) to get notifications when I am mentioned.
In the case I write someone a personal letter delivered only to that person, I prefer to use their name. And I myself prefer to be addressed as Dimitry, not as @dpolivaev when I get a post like that.

**Comment by NobbZ** [comment]
Then you probably have choosen the wrong screenname. I like to be addressed as NobbZ, even in RL.

**Comment by dpolivaev** [comment]
What do you mean by "screen name" ?  Can it be changed?

I think there are actually two names: the login name and the name configured in exercism user profile.

The first is pretty technical and can not be changed later. In my case it is my github user name. So it would not be possible for more than one person world wide to set it to Dimitry, and it is also always limited to one word.

There is also name chosen by a user in their exercism profile (see screen shots). 
![myprofile](https://user-images.githubusercontent.com/1558052/45841864-63be9080-bd1b-11e8-8ba8-f408931ba7fd.png)
![exercismname](https://user-images.githubusercontent.com/1558052/45841883-6b7e3500-bd1b-11e8-9dcb-b75e8e680ba8.png)

This one can be set to whatever user wants. You can set it to `@NobbZ` , I can set it to `Dimitry`, as I did, and somebody else could set it to Prof. Dr. Dr. Someone. 

Actually, I would expect the profile name to be shown and used in all personal posts.

**Comment by dpolivaev** [comment]
I have learned see that the problem is not restricted to student names, and I shall create a new issue to describe it.
