### ISSUE TITLE
Show user names instead of user handles on solution pages, if available

### ISSUE THREAD

**Issue by dpolivaev** [exercism/exercism#4365]
As a mentor, I consider the feedback I give my students as a kind of personal relationship. I want the students to improve and write them individual recommendations, they answer me, we communicate like writing personal notes or letters.

I would prefer that their posts start with a usual greeting using my name. And I would like to start my feedback greeting them by names. I think that it would make the feedback emotionally easier to trust and to accept. 

Unfortunately, the exercism website currently shows only our user handles. Actually, user handles are quite a technical thing set on github and not to be used in other context. For communication, I would like that my students are shown the name I can configure on my profile page. And if someone prefers using their handles as names, they could enter them instead of their real names on the user profile page.

Maybe you could show both, but in doubt the name is the more important one.

![my_profile](https://user-images.githubusercontent.com/1558052/45926917-b28e4500-bf2a-11e8-9efb-a19b6fd03658.png)
![discussion](https://user-images.githubusercontent.com/1558052/45927029-f7b37680-bf2c-11e8-80d4-6f27217a5417.png)

**Comment by NobbZ** [comment]
I can only repeat what I said elsewhere, the user should be able to choose which name is displayed.

**Comment by iHiD** [comment]
@kytrinyx @nicolechalmers I'm interested in your thoughts on this.

**Comment by dpolivaev** [comment]
What do you think about asking feedback to this request in the mentor's slack?

**Comment by iHiD** [comment]
Yes. Feel free :) I think the conclusion will be the same as what @NobbZ says, which is that people should be able to choose how their name is displayed. I would be against it showing a name, even though I have that on my profile. My handle is what I used around the internet and I would expect it to be used there too, exactly the same as on GitHub. But I understand others might prefer their name to be displayed.

**Comment by dpolivaev** [comment]
Originally I assumed that "name" is exactly how the user prefers to  be addressed. Actually you could enter your handles there so that displaying the name would still display your handles as I suggested in this request. And now I do not see much sense in a slack discussion or even worse a vote between two possibilities: if you @iHiD  and @NobbZ prefer having your handle displayed and I prefer using my name displayed, could the both become possible?

Also, if for you "name" is something not related to how you are addressed and shown to the other people, one could either make configurable which field is displayed or add a new field called "displayed name" or "nick". 

I would be thankful if you do any of this because for me being addressed by my handle does not feel any good.

**Comment by kytrinyx** [comment]
I don't know if we use "name" for anything; I would not be philosophically opposed to changing it to say "display name (defaults to handle if empty)".

**Comment by iHiD** [comment]
I'm not opposed to a "display name" field, but it needs updating in lots of places, and we need to add DB and UI to allow people to set that. So there's enough there that it's not trivial. I'll add it to the roadmap but it won't be a priority unless someone convinces me otherwise :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
