### ISSUE TITLE
Extra exercises in python track not being reviewed

### ISSUE THREAD

**Issue by mandos9** [exercism/exercism#4366]
Hi all,

Thank you for your great service! I have done some of the extra exercises of the python track and have not received any feedback from a mentor since almost 2 months now. Is it an issue with not having enough people to work on it?

Best,

**Comment by iHiD** [comment]
Hello. Yes - that's the issue.

I'm hoping that #4375 will start to help, along with a load of other things we have on the roadmap to make mentoring easier over the next few weeks. I'm going to close this the fixes we're working on are covered by lots of issues, but thanks for opening the issue and for your understanding :)
