### ISSUE TITLE
No feedback on golang track after switching back to mentored mode and solutions of other peoples don't appear

### ISSUE THREAD

**Issue by paulbonneau** [exercism/exercism#4367]
Hi,

Profile url : https://exercism.io/profiles/paulbonneau

Thank you for your wonderful website, really helpful material for learning and practicing code.

I think I have an issue with one of the track I’m following but I’m not sure : None of the exercises I submitted on my track have been reviewed and I think it could be caused by the fact that I started the GOLANG track on independent mode and then switch back to mentor mode (I start submitting exercises after I switched back to mentored mode).

Maybe its just because there’s no one available at the moment which is not a problem at all for me, but I’m reporting this just in case.

Plus, I can’t find a link to other peoples solutions for the exercises I submitted (maybe I’m the only one but I doubt it). For example https://exercism.io/my/solutions/58d73ae735b14da7803829c1d7b94586 , can’t find other’s solutions here (maybe it is elsewhere, I’ve this platform searched but didn’t found).

Thanks again for your very valuable work !

Regards,
Paul.

**Comment by hilary** [comment]
Hi Paul!

Are the exercises you have submitted since switching to mentored mode core exercises or side exercises? The Golang track is particularly in need of additional mentors, so we're focusing on mentoring core exercises at the moment.

**Comment by paulbonneau** [comment]
It was a core exercise, but someone came to review it so no bug here !
Just wanted to report it in case of. This issue can be closed, no bug here.

Thanks again for your work !

**Comment by iHiD** [comment]
This will hopefully also be better sorted by https://github.com/exercism/exercism/issues/4375 - Thanks :)
