### ISSUE TITLE
As a student, how do I know if mentors are active in my track?

### ISSUE THREAD

**Issue by ftt** [exercism/exercism#4368]
Currently, there is no way for me to see if there are any active mentors in my track.

For example, the number of Rust mentors has increased over time, but I feel like the lag between solution submission and its review has also increased.
Is it because there are no active mentors?
Is it because mentors are active but overwhelmed by the amount of solutions?
Is it because mentors tend to ignore solutions to some exercises?

Would be cool to see something like "historically, solutions to this exercise take _n_ days on average before review". That would set some expectations :)

**Comment by mbbroberg** [comment]
Great question @ftt. I dig the feature idea 😄, as long as it's after other big ideas [on the roadmap](https://exercism.io/roadmap). 

FWIW, there are currently [28 mentors listed on the site](https://exercism.io/tracks/rust/mentors) and over 6,000 students 🤯. I think Rust got a lot more popular and it's taking a bit to review. Good luck!

**Comment by iHiD** [comment]
I want us to get much better at providing this information to learners. I really like the "historically, solutions to this exercise take n days on average before review" idea. I've added this to the roadmap - thanks.
