### ISSUE TITLE
Permission denied for configuration with CLI token

### ISSUE THREAD

**Issue by ynmwong** [exercism/exercism#4369]
I installed it on my Mac today. When I tried to configure with my CLI token, it returned "permission denied". Has anyone had the same issue?

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.9
Latest:  3.0.9

Operating System
----------------
OS:           darwin
Architecture: amd64

Configuration
----------------
Home:      /Users/melodywong
Workspace: /Users/melodywong/Exercism (default)
Config:    /Users/melodywong/.config/exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 249.307794ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 1.306721535s

**Comment by NobbZ** [comment]
Can you please paste the full error message? Please remember to remove/redact the token everywhere it appears.

**Comment by ynmwong** [comment]
The error message it returned:
Error: open /Users/(username)/.config/exercism/user.json: permission denied

What do you mean by removing token everywhere? Could you explain it more? Thank you!!

**Comment by mbbroberg** [comment]
Hey @ynmwong, welcome to Exercism 👋. I'm sorry you ran into a couple of challenges, but we can work through them quickly enough. 

Regarding **permissions**, the installation process assumes your current user has permission to work in `/Users/(user)/.config/exercism/`. To ensure you can read and write to it, run: 

```
$ chmod +rw /Users/$USER/.config/exercism/user.json
```

> Note I also added `$USER` to the path, which will return the current user, so this command will work for you and me without edit. 

On removing the token everywhere, it's advised to never publish a unique identifier to GitHub. That can be an API token, password, or other private information. Once you do, it's easy for others to pull that information and then use your permission level to pretend to be you or do things that you don't want to do 😄. 

In this case, a user can only submit to Exercism as you. It's not ideal but it's also not an emergency in my opinion. The team is working on a way to reset it via https://github.com/exercism/exercism/issues/4150, so keep an eye on that for a resolution. 

Good luck and happy exercising! 🏃🏃🏃

**Comment by iHiD** [comment]
Can this be closed?
