### ISSUE TITLE
Missing links on https://exercism.io/my/tracks/kotlin

### ISSUE THREAD

**Issue by lathspell** [exercism/exercism#4370]
Using google I found the following two pages that seem not to be linked anywhere from the language page https://exercism.io/my/tracks/kotlin :
- https://exercism.io/tracks/kotlin/tests
- https://exercism.io/tracks/kotlin/installation

**Comment by mbbroberg** [comment]
Thanks for looking to improve Exercism @lathspell! These resources are linked to during installation and at the bottom of each exercise (see images below). 

I believe these overall track pages are to get students to see the value in joining the track. Once they join, more resources are presented to them. If you see an opportunity to add more value up front, you can propose a change to the related file. The page you referred to renders from the [files in this folder](https://github.com/exercism/kotlin/tree/master/docs).

If that addresses your concern, please close the issue and open a PR when you're ready. Cheers 🎉 

<img width="656" alt="screen shot 2018-10-01 at 9 25 56 am" src="https://user-images.githubusercontent.com/1744971/46302217-5e541800-c55d-11e8-8a6f-4ec889c2e830.png">

<img width="509" alt="screen shot 2018-10-01 at 9 35 14 am" src="https://user-images.githubusercontent.com/1744971/46302227-60b67200-c55d-11e8-8414-a7d3df1aac04.png">

**Comment by lathspell** [comment]
The instructions are only visible for exercises that are not yet completed. Now that I completed all exercises in the Kotlin track I have no links to the help pages :-) (e.g. to show them to students I mentor)

Additionally, now that I do not see them anymore, I'm not encouraged to improve them.

IMHO they should be always displayed at the bottom of the track page (and maybe always at the exercise). More help helps more!

**Comment by sshine** [comment]
The hyperlinks in OP appear to work at this point.

> Now that I completed all exercises in the Kotlin track I have no links to the help pages e.g. to show them to students I mentor.

That seems like a bad bug. Could you provide a screenshot of this? I will close this issue for two reasons: The original problem is only tangentially related, and I would like to highlight the second problem by bumping it.
