### ISSUE TITLE
illegal character when visit https://exercism.io/cli-walkthrough

### ISSUE THREAD

**Issue by mojobiri** [exercism/exercism#4371]
![image](https://user-images.githubusercontent.com/664081/46211877-4ef68400-c33d-11e8-99ca-d0edfc1bdf24.png)

**Comment by rpottsoh** [comment]
What did you click on just prior to receiving that error message?  What path did you start down, Linux, Mac, Windows?

**Comment by mojobiri** [comment]
The issue is on Windows 10, Firefox Developer Edition 63.0b9 (64-bit)
Works fine on Firefox in Ubuntu.

**Comment by rpottsoh** [comment]
Do you know where you were in the Windows path of the walk through?

Are you saying that the Windows walk through works fine if you are using Firefox in Ubuntu or that the the Linux walk through works fine using Firefix in Ubuntu.

I need to establish with path you are taking first in the walk through, then we can worry about which browser you are using and in which OS.  At this point it is most important to know how you are traversing the walk through and where you are at in the walk through when you experience the error.  Other can then try to see if they can recreate the error.

**Comment by mojobiri** [comment]
It's simply the page cannot be displayed in Windows with Firefox
![image](https://user-images.githubusercontent.com/664081/46218121-8e789c80-c34c-11e8-9d2d-5750bcdcdaaf.png)

**Comment by rpottsoh** [comment]
I cannot recreate the symptom with my Windows 7 (32 bit) system with Version 62.0.2 (32-bit) of Firefox (latest one available for my OS).  Also not reproducible on the same computer using Chrome browser.  Sorry.

**Comment by mojobiri** [comment]
Yeah, Chrome works fine. Probably some issue with my setup. Thank you! Closing.
