### ISSUE TITLE
Unable to sign in with account from v1

### ISSUE THREAD

**Issue by vitoreiji** [exercism/exercism#4372]
I haven't used exercism in a while and just found out about the rewrite. I don't remember my old password, so I tried resetting it, but the email wasn't found. I tried signing up with my old email and handle, but I get an error saying the handle is taken. I am not sure if that is because someone else took that handle or because it is associated with my old account.

How can I find out?

The handle in question is `vitoreiji` and the email is `vitoreiji0` at gmail.

**Comment by NobbZ** [comment]
Try using the GitHub login method.

**Comment by vitoreiji** [comment]
That worked. I had completely forgotten I had used my Github account to log in in the past.
Thank you!
