### ISSUE TITLE
Change "Last updated 2 months ago" to "Last updated 67 days ago"

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#4374]
The submission queue is currently opaque beyond the top 20 elements.

Until some progress statistics show up, mentors can't know if their efforts to shorten the waiting time or the queue length are in vain.

1. [ ] The simplest improvement we can make is **change "Last updated 2 months ago" to "Last updated 67 days ago"** on the mentor dashboard. This will let me know within an hour or day of mentoring whether I'm effectively reducing the average waiting time or not, without having to wait a month and see that the top 20 elements are now updated "3 months ago" and not knowing if I got through 1%, 10% or 99% of them.

   It looks like this could *almost* be a one-liner in [this dashboard .haml file](https://github.com/exercism/website/blob/master/app/views/mentor/dashboard/_solution.html.haml). Perhaps, instead of [`time_ago_in_words`](https://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/DateHelper.html#method-i-time_ago_in_words) we could pass some of the granularity options that are mentioned under `distance_of_time_in_words`. Perhaps there's need of a specialised timespan formatter. I'm not an expert.

2. [ ] The next-simplest improvement we can make is **add a total queue count for core/non-core exercises** on the mentor dashboard. This will let me know whether I'm effectively reducing the length of the queue, without having to wait a month to see @ihid's statistics and conclude that "shoot, Haskell got more popular!"

   This is probably not a one-liner, but requires a couple of ORM-specific lines in [the dashboard controller](https://github.com/exercism/website/blob/master/app/controllers/mentor/dashboard_controller.rb) and a line in some dashboard .haml file.

   A problem is that the dashboard lists all exercises for all the tracks you mentor, so either the statistics must be combined for all the tracks you've selected, or the total should only show when you've selected a specific track.

   It would be an obvious next step to make this number depend on all the queue filters, and to make the "total" correspond to "length of this particular queue you've produced by filtering", but those are "nice to have" compared to a pair of total core/non-core in queue for a single language track.

I've experienced that Haskell mentors aren't active lately. Of course, I don't know why this is, and I've only been a mentor for about a month, so the long-term effects of mentoring haven't hit me yet, but one short-term effect is that I don't know if I'm doing any significant difference to the hidden bulk of non-core exercises in queue.

I've addressed the need for a more advanced statistical overview of the submission queue, and I fully accept that those things don't build themselves. Still, I don't find it very fun to give feedback in the dark. I think adding *two* stats ("67 days" instead of "2 months", and "39/517 total core/non-core exercises in the queue for Haskell") would be very empowering, quite easy to add, somewhat easy to refactor wrt. better UX.

I'd really like to not have to write them, because my current spare-time hacking is already split three-ways and does not involve Rails. But if there aren't any planned resource allocations (I can see that exercism/website was last committed to 25 days ago), I might give it a shot for great good. (@ihid encouraged me to do this 15 days ago on Slack, and I've narrowed the problem down as much as I could to make it feasible for anyone else or myself.)

**Comment by iHiD** [comment]
Thank you :) I'll look into this in the coming days :)

**Comment by sshine** [comment]
Awesome, thanks @PatrickMcSweeny!
