### ISSUE TITLE
ActionView::Template::Error in my/tracks#show

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4376]
## Error in Exercism V2

**ActionView::Template::Error** in **my/tracks#show**
undefined method `title' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b8ecc7b84453c001a03fbd2?event_id=5bb525c300301b3d16620000&i=gh&m=ci)

## Stacktrace

    app/views/my/tracks/_started_modal.html.haml:26 - _app_views_my_tracks__started_modal_html_haml___1745446426999066569_70045853716520
    app/views/my/tracks/show.html.haml:43 - block in _app_views_my_tracks_show_html_haml___3819632181609732549_38332760
    app/views/my/tracks/show.html.haml:37 - _app_views_my_tracks_show_html_haml___3819632181609732549_38332760

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b8ecc7b84453c001a03fbd2?event_id=5bb525c300301b3d16620000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by kntsoriano** [comment]
@iHiD I noticed this error happened because people were joining the Javascript (Legacy) track. Should we set it as inactive in the DB?

**Comment by iHiD** [comment]
Yes please.

**Comment by kntsoriano** [comment]
Done.

**Comment by iHiD** [comment]
Thanks :)

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionView::Template::Error** in **my/tracks#show**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b8ecc7b84453c001a03fbd2?event_id=5bbcc559003047e807fa0000&i=gh&m=ra)

**Comment by iHiD** [comment]
@kntsoriano Can this be closed?

**Comment by kntsoriano** [comment]
Let's close. Last bug was 4 months ago.

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionView::Template::Error** in **my/tracks#show**](https://app.bugsnag.com/exercism/exercism/errors/5b8ecc7b84453c001a03fbd2?event_id=5d1f14ce0048775f7fd20000&i=gh&m=ra)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
