### ISSUE TITLE
ActiveJob::DeserializationError in ActiveStorage::AnalyzeJob@default

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4378]
## Error in Exercism V2

**ActiveJob::DeserializationError** in **ActiveStorage::AnalyzeJob@default**
Error while trying to deserialize arguments: Couldn't find ActiveStorage::Blob with 'id'=372

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b4474c390734d001bd3f9eb?event_id=5bb16db5002fdb81d4d40000&i=gh&m=ci)

## Stacktrace

    gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:346 - raise_record_not_found_exception!

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b4474c390734d001bd3f9eb?event_id=5bb16db5002fdb81d4d40000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by kntsoriano** [comment]
@iHiD Not really a problem. This happens when an account is deleted. This error will eventually go away after Sidekiq has retried them enough. A step we can do next is to look at the Sidekiq queue all jobs relating to the user.

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveJob::DeserializationError** in **ActiveStorage::AnalyzeJob@default**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b4474c390734d001bd3f9eb?event_id=5bb7c17600303cd67a3e0000&i=gh&m=ra)
