### ISSUE TITLE
Import from old website won't let me get mentored.

### ISSUE THREAD

**Issue by linesthatinterlace** [exercism/exercism#4380]
I submitted a bunch of solutions to the Haskell track in the old version of the website. I'd quite like to get these mentored, but it seems to be a bit stuck - all my solutions apart from "Hello, world!" say "you must get your other solutions mentored", and of course "Hello, world!" doesn't need mentoring, so it doesn't mention this.

I tried going back to Independent mode and then to Mentored mode again, but it didn't work.

**Comment by iHiD** [comment]
This will get fixed by https://github.com/exercism/exercism/issues/4375

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this as a duplicate. If you want to follow along, go ahead and subscribe to https://github.com/exercism/exercism/issues/4375 🌸
