### ISSUE TITLE
Show basic stats about the solution

### ISSUE THREAD

**Issue by Rots** [exercism/exercism#4381]
As a user, when browsing community solutions, it would be useful to have some basic stats about the solutions, e.g. lines of code, % of comments, number of files/functions so that it's easier to find interesting ones to investigate.

**Comment by iHiD** [comment]
Hello. Thanks for your suggestion :)

We have lots of plans for this, some of which are discussed at https://github.com/exercism/exercism/issues/4067#issuecomment-407702570

When we get there, we'll definitely think about these things. Would you mind posting a comment on that issue with the thoughts above and close this one please? :)
