### ISSUE TITLE
Script a PR to each track's config.json which adds the relevant file extensions

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4386]
We will use this for a couple of different purposes:

- **syntax highlighting** - the Prism library can use file extensions to determine which syntax highlighting lexer to use
- **inferring files to submit with CLI** - the CLI can submit an exercise directory, but this often contains temp files, build files, artifacts, etc that we don't care to upload. The extensions will help us decide which files should be submitted

We can get the extensions from GitHub's Linguist project:
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

The key should be named `extensions`, and contain an array of bare extensions (no dot): `["cpp", "h"]`.

# 

There are three things that make this a lot easier than you might imagine.

- An Exercism-specific gem named [Trackler](http://github.com/exercism/trackler), which has all the tracks in it.
- An Exercism-specific command-line tool named [Configlet](http://github.com/exercism/configlet), which lets you reformat the edited config to make sure we don't have weird whitespace or whatever in it when scripting the change.
- A GitHub-specific command-line tool named [Hub](http://github.com/github/hub) which lets you create PRs from the command-line.

```
gem install trackler
```

```
require 'trackler'
Trackler.tracks.each do |track|
  # track.id
  # track.language
end
```

You will need to have all the tracks forked and checked out to your local filesystem.
I have mine at `~/exercism/tracks/`. Use `trackler` to write a quick script to clone them all.

You will also need to be authenticated with Hub, so try submitting an issue to one of your test repositories to get that sorted before going down the scripting path.

The basic idea is to loop through all the tracks and then have your script `cd` into the track directory to do whatever it needs to do.

```
require 'trackler'

root = File.pwd
Trackler.tracks.each do |track|
  Dir.chdir File.join(root, "tracks", track.id)

  # shell out to do the work
  # shell out to github/hub to create the PR

  sleep 2 # to avoid hitting abuse rate limits on GitHub
end
```

You'll want to make sure that the track repository is completely up-to-date and clean:

```
  puts %x(git reset --hard)
  puts %x(git checkout master)
  puts %x(git fetch origin master)
  puts %x(git reset origin/master --hard)
```

Then, you'll sometimes want to run through the script several times, so check out the branch with `-B` rather than `-b`. `-B` means _check out a new branch if it doesn't already exist, otherwise check out the existing one_.

```
  puts %x(git checkout -B #{BRANCH_NAME} --track)
```

After changing the config, make sure you reformat it with Configlet:
```
  puts %x(#{CONFIGLET_PATH} fmt . -v)
```

Then add the config file, commit the change, and push up your branch.

Finally, to create the PR do two things:

- append the URL of the tracking issue to the commit message text. This will add a dynamic link to the pull request in the timeline, which makes it easy to see the status of the task at a glance (see https://github.com/exercism/meta/issues/19, which shows purple for all the merged PRs. A PR that is closed will be red. A PR that is still open will be green).
- submit the PR using `hub`

```
  msg = <<-MSG
  The title of the PR

  The body and description for the PR
  MSG
  issue = 'exercism/meta#95'
  destination = 'exercism:master'
  source = "#{ORG_NAME}:#{BRANCH_NAME}"
  desc = "#{msg}See #{issue}"
  puts %x(hub pull-request -b #{destination} -p -h #{source} -m "#{desc}")
  sleep 2
end
```

# 
See https://github.com/exercism/meta/issues/107

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
