### ISSUE TITLE
Submit issue to all tracks about having correct test command in each exercise README

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4393]
## Problem

Several tracks put a generic instruction in the exercise README that says something like:

> Run the following command:
> 
> ```
> $ test hello-world/HelloWorld.ext
> ```

Where 'hello-world' (or something else) is hard-coded, and then the README explains to swap that out with the actual name of the exercise and file.

## Solution

Our README generator is now smart enough to be able to generate the proper file name so that each README has the correct instructions.

Groovy did it here: https://github.com/exercism/groovy/blob/master/config/exercise_readme.go.tmpl#L13

We have `.Spec.MixedCaseName` and will need to add `.Spec.SnakeCaseName` for languages that use that convention. We already have the `.Spec.Slug` for languages that use kebab-case.

### Submit issues
Submit an issue to all exercism tracks that explains

- the problem
- the suggested solution
- a link back to this issue

Note that some tracks have fixed this, and other tracks have a single command that works for all the exercises, so it's not relevant.

Instead of figuring out which tracks this is relevant for, I make the issue text say something like "If this isn't relevant to this track, go ahead and close this issue".

You might be able to use blazon: https://github.com/exercism/blazon

Otherwise:

- write a template issue
- use the [octokit library](https://github.com/octokit/octokit.rb) to do a search for all repos on the exercism org with the topic 'exercism-track' -- you'll need a GitHub personal access token https://github.com/settings/tokens (probably need 'public_repo' scope)
- for each repo use the github/hub library to submit the template issue https://github.com/exercism/docs/blob/71551cd82a3c6ef3678b00ac82be74c84cb96609/language-tracks/launch/open-issues.md#bulk-issues - https://github.com/exercism/docs/issues/10

### Fix documentation
We will also need to update the documentation, to mention these variables: https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
