### ISSUE TITLE
Waiting for feedback on Ruby Hamming exercise for a week

### ISSUE THREAD

**Issue by monfresh** [exercism/exercism#4403]
Hello. I submitted a solution to the Ruby Hamming exercise about a week ago, and I have not received feedback yet. How long is the typical wait time for the Ruby track? Here is a link to my solution:
https://exercism.io/my/solutions/bfca75e256de44b39675dbf57236212b

Thanks!

**Comment by darrenrjones** [comment]
I came here for a similar issue, I was getting mentor support and then I didn't come back to a problem for a week or 2 and now I can't get it approved. I submitted an improved answer and still nothing.

https://exercism.io/my/solutions/bd606f058ce545ffbbad8ec1dc747248?iteration_idx=3#discussion-post-197415

**Comment by monfresh** [comment]
Any updates on this? I received an email about mentorship not being available for side exercises, but Hamming is a core exercise, and from what I can tell, I cannot start the next one until this one is approved. Thanks for looking into this.

**Comment by iHiD** [comment]
@monfresh Is this still relevant?

**Comment by monfresh** [comment]
I think this can be closed now. A mentor reached out and I updated my code based on his feedback. Now I'm waiting to hear back.
