### ISSUE TITLE
REST-api exercise has no icon

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4407]
![image](https://user-images.githubusercontent.com/135246/46675039-e2ea0a80-cbdd-11e8-93a9-a3543f85300b.png)

**Comment by rpottsoh** [comment]
An issue needs to be opened in exercism/website-icons to have a new icon produced for the new exercise.  See exercism/website-icons#7

**Comment by rpottsoh** [comment]
I opened issue exercism/problem-specifications#1271 a while back to try and address this situation.

**Comment by ErikSchierboom** [comment]
Thanks for the pointer. I'll close this in favor if https://github.com/exercism/website-icons/issues/12.
