### ISSUE TITLE
Problem Submitting

### ISSUE THREAD

**Issue by gatsu12** [exercism/exercism#4409]
I've tried reading other similar problems and did everything I could think of, but I can't seem to submit the exercise. I have the files within the 'workspace' folder, but I keep getting an error saying the "The file you are trying to submit cannot be found." This is my first time using Exercism, so I could definitely be doing something wrong here. I've attached a screenshot of the error I'm getting to see if anyone knows why this is happening.
![submit](https://user-images.githubusercontent.com/40731003/46774791-07ff7b80-ccb9-11e8-9a60-2e6e4dd3c3cc.JPG)

Thanks in advance for your help!

**Comment by NobbZ** [comment]
You are already in `...\Exercism`, from there you try to submit `Exercism\python\hello-world`. There are some issues with this.

1. The absolute path you try to submit is `...\Exercism\Exercism\python\hello-world`. A level of `Exercism` to much.
2. You are trying to submit a diorectory, which is currently not possible, you need to specify the file to submit explicitely.

So either `cd` into the exercises directory and do `exercism submit hello_world.py` or from where you was before `exercism submit python\hello-world\hello_world.py`.

**Comment by iHiD** [comment]
Can this be closed?
