### ISSUE TITLE
"TypeError: (0 , _reverseString2.default) is not a function" issue with "npm test"

### ISSUE THREAD

**Issue by luismartinezs** [exercism/exercism#4412]
I am just begun with the JS track.
I am trying to do the tests using the npm test command as explained. But I get error below.
It says that reverseString is not a function, but the file reverse-string.js contains it and it is a function:

```
npm test

> exercism-javascript@0.0.0 test C:\Users\saito\Exercism\javascript\reverse-string
> jest --no-cache ./*

 FAIL  ./reverse-string.spec.js
  ReverseString
    × empty string (7ms)
    ○ skipped 4 tests

  ● ReverseString › empty string

    TypeError: (0 , _reverseString2.default) is not a function

      4 |   test('empty string', () => {
      5 |     const expected = '';
    > 6 |     const actual = reverseString('');
        |                    ^
      7 |     expect(actual).toEqual(expected);
      8 |   });
      9 |

      at Object.<anonymous> (reverse-string.spec.js:6:20)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 skipped, 5 total
Snapshots:   0 total
Time:        2.518s
Ran all test suites matching /.\\*/i.
npm ERR! Test failed.  See above for more details.
```

My reverse-string.js file:

```
'use strict'

export const reverseString = (str) => {
    return str;
};
```
reverse-string.spec.js file (I remvoed all tests except the first one for short:

```
import reverseString from './reverse-string';

describe('ReverseString', () => {
  test('empty string', () => {
    const expected = '';
    const actual = reverseString('');
    expect(actual).toEqual(expected);
  });
});
```

My only guess is that there's something wrong with the modules imported when I use "npm install".
This test is just an example, it happens so far with all exercises I've done, except, for some reason I can't understand, with the first one, "hello world". Maybe I have to change something in the file package.json?
I copy its content below just in case:

```
{
  "name": "exercism-javascript",
  "version": "0.0.0",
  "description": "Exercism exercises in Javascript.",
  "author": "Katrina Owen",
  "private": true,
  "repository": {
    "type": "git",
    "url": "https://github.com/exercism/javascript"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-jest": "^21.2.0",
    "babel-plugin-transform-builtin-extend": "^1.1.2",
    "babel-preset-env": "^1.4.0",
    "eslint": "^5.6.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-import": "^2.14.0",
    "jest": "^23.6.0"
  },
  "jest": {
    "modulePathIgnorePatterns": [
      "package.json"
    ]
  },
  "babel": {
    "presets": [
      [
        "env",
        {
          "targets": [
            {
              "node": "current"
            }
          ]
        }
      ]
    ],
    "plugins": [
      [
        "babel-plugin-transform-builtin-extend",
        {
          "globals": [
            "Error"
          ]
        }
      ],
      [
        "transform-regenerator"
      ]
    ]
  },
  "scripts": {
    "test": "jest --no-cache ./*",
    "watch": "jest --no-cache --watch ./*",
    "lint": "eslint .",
    "lint-test": "eslint . && jest --no-cache ./* "
  },
  "eslintConfig": {
    "parser": "babel-eslint",
    "parserOptions": {
      "ecmaVersion": 7,
      "sourceType": "module"
    },
    "env": {
      "es6": true,
      "node": true,
      "jest": true
    },
    "extends": "airbnb-base",
    "rules": {
      "import/no-unresolved": "off",
      "import/extensions": "off",
      "import/prefer-default-export": "off",
      "import/no-default-export": "off"
    }
  },
  "license": "MIT",
  "dependencies": {}
}
```
Thanks

**Comment by jackyzhen** [comment]
darthbob is right. The test expects a default export but what you have right now is a named export. See :https://stackoverflow.com/a/33611943

**Comment by darthbob88** [comment]
See also https://wesbos.com/javascript-modules/

**Comment by luis-martinez-s** [comment]
@darthbob88 thanks, that article has been very instructive

**Comment by catb0t** [comment]
seems like the error message could use improvement if it's possible? then the next person won't have such an ugly weird error message and ask this question

**Comment by anthonybronkema** [comment]
> Just at a guess, the problem might be that your test expects `import { reverseString } from './reverse-string.js'` I just changed my code to `import secretHandshake from './secret-handshake';` and it has the same problem.

Thank you @darthbob88. I wasn't used to looking for that, no I know for the future. Mine was on the two-Fer Javascript lesson and I had to change
```javascript
import twoFer from './two-fer';
```
to 
```javascript
import { twoFer } from './two-fer';
```

The error I was initially getting was `TypeError: (0 , _twoFer2.default) is not a function`

**Comment by iHiD** [comment]
Can this be closed?

**Comment by plungu** [comment]
I downloaded the hello-world exercise and copied the solution and it just doesn't work. This is very discouraging to a beginner. Makes exercism feel really janky. Someone should take ownership and make this work.
