### ISSUE TITLE
Mentoring for the best solution within a conceptual approach

### ISSUE THREAD

**Issue by dvrensk** [exercism/exercism#4415]
*[This started as a post in the 'track-ruby' Slack channel but it was suggested that I move it here.  References should be understood in the context of the Ruby track, but I would be surprised if this weren't relevant for some other tracks too.]*

Hello everybody!  I'm new here, so please excuse me (and inform me) if I'm a bit lost or if what I'm about to say has been addressed before.  So far I've mentored 20 or so solutions each of the early exercises and I'm noticing that for some exercises, like Raindrops, Hamming and Acronym, there are several valid mental models that lead to very varying solutions which are all reasonable and clean.  I've begun calling these mental models _approaches_ (XP talks of a _metaphor_, but I feel that's too abstract for little exercises), and as an example, in Hamming I see 2 valid approaches based on coherent mental models:

1. Pair up the characters from each string and count how many pairs are twins (the `zip`, or pairing, approach).
2. After making sure the strings are the same length, work an index _i_ through both strings and count the number of times the char in position _i_ is different in the two strings (the `times`, or index, approach).

The [Mentor Notes for Hamming](https://github.com/exercism/mentors/tree/master/tracks/ruby/exercises/hamming) talk about 3 different _strategies_ where the first two correspond with my approaches (1-1 and 2-2) and the 3rd is a sort of hybrid that, in my opinion, looks like the student has been rummaging through the Lego box attaching methods to other methods until the tests passed.  I would like to argue that it does _not_ correspond to a mental model that the student came up with beforehand, and for this reason I find it useful to separate "strategies" and "approaches".

**Q1:** Is it useful to separate "strategies" and "approaches"?  Are those good terms?

Now, for each approach we can imagine one ideal solution which the students are (or should be) striving towards, and as a mentor, I try to help them getting there.  I'm becoming increasingly convinced that I should _not_ try to make the student pick the approach that I like the best or that's listed first in the Notes.  In many cases though I feel that they deserve to know about another approach before moving on to the next exercise.  Sometimes I mention one explicitly, sometimes I challenge them to implement it, sometimes I just hint that they could look at others' solutions, and sometimes I do nothing.

**Q2:** Are there approaches (not strategies) that are so much more preferrable that we should point the students that way, or is it better to encourage them to make the best of the strategy they have picked?  Which attributes might qualify an approach for stardom? (Better readability, more Ruby-ish style, better performance on edge cases or in general, less memory usage, …)  Is the `zip` approach preferrable in Ruby exactly because it's not available in most other languages?

**Q3:** When and how should we point out other strategies as FYIs, not as something to be implemented?

Now for the question that sparked this thread: When working through Acronym (after mentoring it a few times already, yes, wrong order, bad mentor) I identified an Approach that I hadn't seen in the little sample of solutions that I had encountered so far.  You are surely aware of the two main approaches:

1. Grab the first letter in each word in the string, and string them together. (The `scan` approach.)
2. Extract the words, then take the first letter of each and string them together. (The `split` approach.)

Their corresponding pen-and-paper models would be

1. `scan`: Circle each letter that should form part of the acronym.
2. `split`: Draw a vertical line or a slash between words. (Or, if you're doing it in a word processor, hit _Enter_ before each word.)

The 3rd model is _Strike out all characters that do not belong in the acronym_.  While the first two _extract_ an acronym out of a string, this one _reduces_ a string to its acronym.  It can be visualised like this (imagine only one line is visible at a time):

```
Ruby on Rails
R--- o- R----
R    o  R
R  o  R
RoR
```

and implemented with gsub:

```ruby
module Acronym 
  def self.abbreviate(string)
    string.tap do |s|
      s.gsub!(/(?<=\w)\w+/, '') # Remove letters after a letter
      s.gsub!(/\W+/,        '') # Remove non-letters
      s.upcase!
    end
  end
end
```

Version with named regexen:

```ruby
module Acronym
  def self.abbreviate(string)
    string.tap do |s|
      s.gsub!(LETTERS_AFTER_LETTER, '')
      s.gsub!(NON_LETTERS,          '')
      s.upcase!
    end
  end

  LETTERS_AFTER_LETTER = /(?<=\w)\w+/
  NON_LETTERS = /\W+/
end
```

Even briefer (but then I can't think of a good name for the regex):

```ruby
module Acronym
  def self.abbreviate(string)
    string.tap do |s|
      s.gsub!(/(?<=\w)\w+\W*/, '')
      s.upcase!
    end
  end
end
```

And that gets us to Q4, thank-you-so-much-for-reading-all-the-way!

**Q4:** What do you think of the 3rd approach and the implementations?

I realise that some part of the answers will be concerned with readability of regexen, and perhaps that merits a whole separate discussion.  Tell me what you think!

**Comment by iHiD** [comment]
I like the idea that rather than looking at "coding strategies" we should look at "conceptual approaches". That's much more empathetic to how  a learner will be trying to solve the problem.

I wonder if there's an argument that in helping learners, our job is not to point them towards the right strategy, but to help make their approach as idempotent as possible. Sometimes that'll mean pointing them down a totally different route maybe. For example, I dislike the "striking out" approach 3 that you outline, but if someone submitted it, it's correct or incorrectness is nothing to do with idiomatic Ruby. I wonder if our job is to try to help them make that solution more idiomatic, rather than push them into a different approach.

**Comment by iHiD** [comment]
@joelq wrote on Slack: 

> @dvrensk I like your distinction between "coding strategies" and "conceptual approaches"!
>
> In my experience, students solving Hamming tend to go towards strategy 3 in the guide which you describe as _a sort of hybrid that, in my opinion, looks like the student has been rummaging through the Lego box attaching methods to other methods until the tests passed_
I wonder if that's because the students don't have a good mental model to work off of. Or maybe they have a good mental model but struggle to describe it in Ruby code? :thinking_face:
> 
> As mentors, should we focus on helping the student refine their mental model rather than discussing the code first?
> 
> Does the translation between mental model and code better lend itself to a declarative code style?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
