### ISSUE TITLE
Handle solutions returning 403

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism#4417]
I came across this solution link in `haskell` channel on slack: https://exercism.io/mentor/solutions/59bcb8278c014394a48eb6ad76bab119

Page returns 403:

![screen shot 2018-10-12 at 10 16 16 pm](https://user-images.githubusercontent.com/980783/46882681-2b6b2780-ce6d-11e8-8493-fbe0b65871d4.png)

I see this in chrome:

![screen shot 2018-10-12 at 10 16 43 pm](https://user-images.githubusercontent.com/980783/46882685-31f99f00-ce6d-11e8-87ff-e81f20afc0ce.png)

And firefox just shows blank page with this error in console:

![screen shot 2018-10-12 at 10 16 26 pm](https://user-images.githubusercontent.com/980783/46882697-3faf2480-ce6d-11e8-8dd9-4aca25b45fc8.png)

I suggest we should show a proper error message that user is unable to view the solution.

**Comment by tejasbubane** [comment]
Why I am unable to see the solution although I have completed exercise in older version of exercism is probably another issue.

![screen shot 2018-10-12 at 10 26 41 pm](https://user-images.githubusercontent.com/980783/46882940-eeebfb80-ce6d-11e8-872b-a88dace99b54.png)

**Comment by iHiD** [comment]
Yep - good plan.

> Why I am unable to see the solution although I have completed that exercise in older version of exercism is probably a separate issue.

There was no "completing" in previous exercism.

**Comment by tejasbubane** [comment]
> There was no "completing" in previous exercism.

But it shows `Completed` in the track page:

![screen shot 2018-10-13 at 12 12 51 am](https://user-images.githubusercontent.com/980783/46887969-ca4b5000-ce7c-11e8-91fc-f5344d009310.png)

**Comment by iHiD** [comment]
I'm confused :) Are you a Haskell mentor?

**Comment by tejasbubane** [comment]
Nope. Not a Haskell mentor. [This](https://exercism.io/profiles/tejasbubane) is my profile.

**Comment by iHiD** [comment]
So if you're not a Haskell mentor, you can't see other people's to-be-mentored Haskell solutions via a `/mentor/solutions/xxx` link, which is the link you posted at the top.

**Comment by tejasbubane** [comment]
Ok that explains it. In previous version it was possible to see other solutions after submitting which made me think that way.

**Comment by iHiD** [comment]
You can see other solutions, but you can't see them through the mentoring link. Those are private to track-mentors.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
