### ISSUE TITLE
Mentor disappeared, how do I get back on track?

### ISSUE THREAD

**Issue by darrenrjones** [exercism/exercism#4424]
I submitted a solution and got feedback, submitted another and got more feedback, now he is nowhere to be found and it is not marked complete so I can't continue on in my track. What can I do? Mentors are still default on the main track, correct? 

https://exercism.io/my/solutions/bd606f058ce545ffbbad8ec1dc747248

**Comment by rpottsoh** [comment]
Which track?

**Comment by darrenrjones** [comment]
javascript...

**Comment by rpottsoh** [comment]
I have alerted the mentors for this track to take a look at this issue.  Hopefully you'll hear something soon.

**Comment by darrenrjones** [comment]
Thank you sir.
