### ISSUE TITLE
Haskell exercise needs mentor to progress on track

### ISSUE THREAD

**Issue by paparomeo** [exercism/exercism#4425]
I have an exercise in the Haskell track which has been waiting for a mentor for two months now. This is an exercise which I started 4 years ago in the previous incarnation of exercism and had feedback from a couple of mentors back then, so it might be because of that that it won't appear in the mentors' dashboard. Any help would be appreciated so I can progress on this track.

https://exercism.io/my/solutions/05326e85251148b9b81d67b7d1d280ee

**Comment by sshine** [comment]
I'll give you feedback on this later today.

It seems that your solution is not in the queue for some reason.

Thanks for reaching out.

**Comment by sshine** [comment]
I've given you feedback now, so this issue can be closed unless you have other submissions stuck in limbo outside the queue.

**Comment by paparomeo** [comment]
Thank you very much for the review @sshine! I'll now be able to progress to the remaining exercises.
