### ISSUE TITLE
How healthy is the Exercism Open Source Organisation?

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4427]
We would like to understand more about what is happening across the Exercism GitHub organisation, where the activity is, who is contributing where, etc. This will help us understand which areas need more support and allocate resources accordingly.

This is a tracking issues for the [Open Source Stats repository](https://github.com/exercism/open-source-stats), which I'm specifically setting up to be a Hacktoberfest project.

Can we put together a series of helpful scripts and results that tell us how healthy each repository is, what our overall contributions look like, etc?

If you can think of any interesting questions that would be useful for understanding the health of our community, please open more issues at the [Open Source Stats repository](https://github.com/exercism/open-source-stats/issues) and label them with Hacktoberfest. And if you fancy hacking on the GitHub API, please do that too :)

**Comment by Ornataweaver** [comment]
Do you think #UserStoryHub would be helpful in this cause?
Is the naming clear? Does it convey useful meaning?
If GitHub is 'C', UseStoryHub would be 'Python', easier for beginners to engage.

**Comment by rpalo** [comment]
Any preference or anti-preference for the language used for possible scripts?

**Comment by Ornataweaver** [comment]
I want a place where I can put my suggestions. So users' suggestions would compete and you would find out what people need the most.

For example I need a dark theme for the website, my eyes get sore.
I wanna know how many other users have the same problem.
 
A repo where I wouldn't be afraid of posting. Something like
https://github.com/kelseyhightower/nocode, but not that much chaotic.

**Comment by Ornataweaver** [comment]
This issue is the closest thing I found to my imaginary repo.
That's why I'm putting my ideas here, I don't mean to spam.

**Comment by iHiD** [comment]
@Ornataweaver This might be the closest thing to your imaginary repo, but it's not that repo, so please don't post things here that aren't relevant to Exercism. You could start that repo and try and raise awareness of it through marketing or reaching out to people on social media etc, or start a Kickstarter or something similar. But Exercism isn't the place to post your ideas for other projects.

**Comment by Ornataweaver** [comment]
This isn't about other projects. I'm specifically speaking about exercism dark theme.

You had told me before not to talk about my ideas in this organization; So I don't say anything irrelevant.

Should I open an issue for it? I'm just trying to get a repo so I would keep number of issues low, unless many people want it.

**Comment by iHiD** [comment]
> Do you think #UserStoryHub would be helpful in this cause?
Is the naming clear? Does it convey useful meaning?
If GitHub is 'C', UseStoryHub would be 'Python', easier for beginners to engage.

This is nothing to do with a Dark Theme.

We have discussed this previously, if you have a feature request, firstly search for open or closed issues that reference that idea to see if there it has already been discussed. If it's not then you can open an issue requesting it. If you'd done that for Dark Theme you'd see it has already been discussed.

The only question for this thread is regarding any things that are for measuring the health of the Exercism OOS community.
