### ISSUE TITLE
Broken alignment for the Side exercise submit message 

### ISSUE THREAD

**Issue by ZapAnton** [exercism/exercism#4435]
The `Your exercise has been submitted successfully. You may mark it as completed, browse other solutions, or request mentoring.` seems to strongly align to the left side of the page instead of the usual center alignment:

![image](https://user-images.githubusercontent.com/8658767/47305383-fd869f80-d631-11e8-9170-c01f6fa5c3d1.png)

**Comment by shabankayitare** [comment]
hey there anyone to help me?
i'm stuck with submitting my first exercise
got this error:
 The file you are trying to submit cannot be found.

        C:\Users\Teacher\Exercism\javascript\hello-world\TO\SOLUTION

**Comment by PatrickMcSweeny** [comment]
This appears to be a duplicate of #4420
