### ISSUE TITLE
got stuck about submitting my exercise

### ISSUE THREAD

**Issue by shabankayitare** [exercism/exercism#4436]
hey there anyone to help me?
i'm stuck with submitting my first exercise
got this error:

    The file you are trying to submit cannot be found.

        C:\Users\Teacher\Exercism\javascript\hello-world\hello_world.js

**Comment by rpottsoh** [comment]
What does
```
exercism workspace
```
reveal?

**Comment by shabankayitare** [comment]
this one
C:\Users\Teacher\Exercism

**Comment by shabankayitare** [comment]
I try using command prompt but failed and even GIT bash failed too

**Comment by rpottsoh** [comment]
Please post what `exercism troubleshoot` returns.

from your "c:\users\teacher\exercism\javascript\hello-world" folder you should be able to:
```
exercism submit hello_world.js
```

**Comment by shabankayitare** [comment]
C:\Users\Teacher\Exercism\javascript\hello-world>exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.10
Latest:  3.0.10


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\Teacher
Workspace: C:\Users\Teacher\Exercism
Config:    C:\Users\Teacher\AppData\Roaming\exercism
API key:   cc69*****************************68a

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 434.0494ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 1.0816148s


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.

C:\Users\Teacher\Exercism\javascript\hello-world>exercism submit hello_world.js
Error:

    The file you are trying to submit cannot be found.

        C:\Users\Teacher\Exercism\javascript\hello-world\hello_world.js

**Comment by shabankayitare** [comment]
C:\Users\Teacher\Exercism\javascript\hello-world>exercism submit hello_world.js
Error:

    The file you are trying to submit cannot be found.

        C:\Users\Teacher\Exercism\javascript\hello-world\hello_world.js

**Comment by rpottsoh** [comment]
Simple question then.  Does the file `hello_world.js` exist in the folder?

**Comment by shabankayitare** [comment]
let me  try will tell you

**Comment by shabankayitare** [comment]
I got this
![image](https://user-images.githubusercontent.com/43929728/47311276-90770800-d639-11e8-9000-f8343ee804e2.png)
I guess the remaining is about debugging,right?
thank you for your help

**Comment by shabankayitare** [comment]
done!!!!
![image](https://user-images.githubusercontent.com/43929728/47311434-04191500-d63a-11e8-9113-6f94cf76c2f3.png)

**Comment by rpottsoh** [comment]
No.  you didn't type `exercism submit hello-world.js`.  It appears as though you just types `hello-world.js` and windows tried to execute your script......

**Comment by shabankayitare** [comment]
thank you sir,
I got stuck from morning!!!
just a small error like that!
hhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by rpottsoh** [comment]
The source of your trouble was in typing an underscore `_` when you should have been typing a hyphen `-`.  Spelling counts.  :smile: 

Were you able to submit hello-world?

**Comment by shabankayitare** [comment]
yeah I got the error!!
and i'm already submit
thank you again!!!!

**Comment by rpottsoh** [comment]
Feel free to close this issue since the problem has been resolved.  I'm glad it wasn't too serious and that you are now on your way.  Have Fun!

**Comment by jafar021** [comment]
You are writing hello_world.js while the name of file is hello-word.js

**Comment by rpottsoh** [comment]
@shabankayitare / @iHiD this issue may be closed.
