### ISSUE TITLE
Improve display of '0 mentors' on tracks

### ISSUE THREAD

**Issue by swalladge** [exercism/exercism#4442]
On tracks which have no mentors yet, it shows the same message but of course "0 mentors":

![1540596740](https://user-images.githubusercontent.com/9714796/47596687-7b023500-d9cf-11e8-8936-8fe405649f3f.png)

Perhaps this could be changed to a message that includes a link to the become a mentor page and a friendly message encouraging the user to mentor or send to someone they know who might want to mentor?

Happy to PR if this would be a good idea.

**Comment by iHiD** [comment]
We shouldn't have any tracks without mentors. That's really problematic if this is the case. Can you remember which track was this was on?

**Comment by swalladge** [comment]
Yep, in fact I came across a few: D, Ballerina, LFE, MIPS.

**Comment by sshine** [comment]
Although this is ~11 months ago, the situation of tracks with zero mentors is much the same:

```
$ cd website-copy/mentors
$ git pull --rebase upstream/master
$ for track in *
  do
    [ -d "$track" ] && cat $track/*.json | \
      jq -c -s --arg track "$track" \
        '[$track, ([ .[][] ] | length) ]' 
  done | grep ,0

["ceylon",0]
["coq",0]
["d",0]
["factor",0]
["fortran",0]
["gnu-apl",0]
["haxe",0]
["idris",0]
["lfe",0]
["pony",0]
```

But besides tracks that have zero mentors, another related problem is tracks that have mentors listed for which nobody gives feedback. So I would summarize the problem of "0 mentors" as threefold:

1. The "0 Mentors" message shows up funny, okay.
2. The "N mentors" for N > 0, when nobody is mentoring.

Perhaps people should be temporarily removed from the mentoring overview until they start to give feedback again? There are some more considerations to this.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
