### ISSUE TITLE
Please confirm whether img/icon.png is still necessary for all tracks

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism#4451]
As an example, see that an arbitrary track, prolog, has:

* https://github.com/exercism/prolog/blob/master/img/icon.png
* attribution for this icon in https://github.com/exercism/prolog/blob/master/README.md#swi-prolog-icon

however, I have not been able to convince myself that this icon has anything to do with https://assets.exercism.io/tracks/prolog-hex-turquoise.png or indeed whether it is shown anywhere on the site at all.

Could you either:

* Give me an example of where on exercism.io the icon.png is used so that future questions can be staved off
* OR confirm that it's not being used anywhere, in which case I will be removing both the icon and the attribution thereof from tracks I'm interested in (but I will not be leading an effort to remove them from *all* tracks)

**Comment by iHiD** [comment]
@petertseng Thanks :) They are not used anywhere and can be removed. 
@kytrinyx Fancy scripting opening an issue anywhere these exist?

**Comment by petertseng** [comment]
Very good, thank you.

I will be closing this issue since I got the answer I needed.

If y'all choose to create issues requesting removal of icon.png, I leave it to y'all's choice whether to link them all to this issue or another that you create.
