### ISSUE TITLE
Remove n+1s in ExerciseMap

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4454]
There are a load of N+1s that seem to be coming from the the ExerciseMap class

<img width="700" alt="screen shot 2018-11-04 at 15 05 38" src="https://user-images.githubusercontent.com/286476/47965785-3287ee80-e043-11e8-9340-6314d02dcb09.png">

**Comment by kntsoriano** [comment]
Ready for review https://github.com/exercism/website/pull/460.
