### ISSUE TITLE
Javascript leap, 4 tests be skipped.

### ISSUE THREAD

**Issue by konni2020** [exercism/exercism#4455]
When I run `npm test`, it show:

```
Test Suites: 1 passed, 1 total
Tests:       4 skipped, 1 passed, 5 total
Snapshots:   0 total
Time:        1.264s
```
Is it a normal behavior?

**Comment by iHiD** [comment]
Hello. Yes it is. The idea is to make each test pass, and then unskip the next one and run it. That allows you to solve one step at a time.

See Understanding Skip Tests in the [JavaScript tests](https://exercism.io/tracks/javascript/tests) for more info.
