### ISSUE TITLE
Allow mentors to verify mentor notes

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4456]
With the addition of mentor notes, one thing I found I wanted to do is to see how they were rendered to the mentor. At the moment, I believe I can only do this when I am actually mentoring an exercise. However, this means that I cannot check the mentoring notes for an exercise that is not in the mentoring queue. It would be helpful if I could also see the mentoring notes for exercises that are not in the mentoring queue.

**Comment by iHiD** [comment]
You can see them via: `https://exercism.io/mentor/exercise_notes?track_id=ruby&exercise_id=isogram`. It's slightly different (as not in a modal) but I think it's probably good enough?

**Comment by ErikSchierboom** [comment]
Good enough for me. Thanks
