### ISSUE TITLE
Error: lstat /home/dj911ice/exercism: no such file or directory

### ISSUE THREAD

**Issue by dj911ice** [exercism/exercism#4473]
I am still having trouble having anything submitted and it seems to be a configuration issue, but how do I have it point to the path at hand?

![screenshot from 2018-11-15 12-23-06](https://user-images.githubusercontent.com/21042279/48570035-4cda8b80-e8d1-11e8-8c7d-db9769d52887.png)

**Comment by NobbZ** [comment]
There is no track `crystal_exercises`, therefore I guess you didn't download through the exercism CLI but by other means. Please use `exercism download` as described in the individual assignment, solve the exercise and then submit from the location it was originally downloaded to.

**Comment by dj911ice** [comment]
Thank you! I created the project manually initially, Although I wish I could change where it would download to. After downloading I was able to submit.

**Comment by NobbZ** [comment]
You can change where to download to. `exercism config --workspace` or something like that. You still have to adhere to exercism internal structure.
