### ISSUE TITLE
Old issues jumped to top of queue

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/exercism#4474]
This is an example:

https://exercism.io/mentor/solutions/1b5de2e499304815891a38e48b85cc7a

This jumped to the top of the queue. A mentor had been helping them.

**Comment by iHiD** [comment]
That was abandoned, so I'm going to say this isn't a bug and is behaving as expected. Thanks for reporting though :)

I'm going to close in favour of https://github.com/exercism/exercism/issues/4476
