### ISSUE TITLE
Ruby Twelve Days not showing button to update exercise

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism#4480]
I was excited about the new feature to update exercises to the latest version because that would give me the ability to update the Ruby Twelve Days implementation to include the change that [I introduced](https://github.com/exercism/ruby/pull/859). However, when I go the solution page, I don't see the button where it should be. Screenshot:

![screenshot from 2018-11-17 16-39-40](https://user-images.githubusercontent.com/1254212/48666044-172bd300-ea88-11e8-8987-7b76a4a38c32.png)

**Comment by iHiD** [comment]
What's your solution id?

**Comment by PatrickMcSweeny** [comment]
1919ea09570e4323af9e86eeb83e248b

**Comment by sshine** [comment]
@PatrickMcSweeny, @iHiD: Can this be closed?

**Comment by PatrickMcSweeny** [comment]
I't  still happening

**Comment by iHiD** [comment]
The button only appears when the test file hasn't been changed. In this situation that hasn't happened, so the button doesn't appear.

**Comment by PatrickMcSweeny** [comment]
It seems like it would be necessary to fix this because there might be other situation where tests might depend on external files.

**Comment by iHiD** [comment]
Maybe, but it's a much more complicated thing to try and work out. The feature we added is one for allowing students to get updates when the test-suites change. I think "allowing students to get updates when any file in the exercise directory of the repo changes" is a different feature, which I'm happy to be proposed.

An easier solution in the meantime would just be to say that something in the tests-file needs to change. I'd suggest a comment saying `# songs.txt last updated on XYZ`. That will solve this immediately for you.

**Comment by PatrickMcSweeny** [comment]
I opened exercism/ruby#1005 to address this.

**Comment by sshine** [comment]
> "allowing students to get updates when any file in the exercise directory of the repo changes" is a different feature, which I'm happy to be proposed.

I was planning to do that, so for the record, this feature request is not forgotten.
