### ISSUE TITLE
Run tests on CLIENT and upload results to Exercism

### ISSUE THREAD

**Issue by yyyc514** [exercism/exercism#4488]
Leo Benkel on Slack:

> One big update would be to know if the test pass so as a mentor, i know if the code is working and can review pretty much from my phone

ihid: 

> This is very well covered in discussion, and probably not going to happen any time soon, as it would be extremely complex and expensive to make it happen.

I suggested running the tests LOCALLY and just uploading the results - which seems (overall) pretty trivial in complexity to me (at least compared to a server side solution).  @iHiD asked me to open an issue here... 

One imagines the pseudo-code would look something like this:

`exercism submit raindrops.rb`

```
file = $1
add_file_to_upload(file)
(output, status) = test_runner(tests_for(file))
add_file_to_upload("test_output.txt", output)
add_file_to_upload(tests_for(file))
do_submission
```

Related:
https://github.com/exercism/exercism/issues/23
https://github.com/exercism/exercism/issues/1757

**Comment by yyyc514** [comment]
I think we already have the ability to upload multiple files - at least I've seen submissions posted with two files attached IIRC.

**Comment by sshine** [comment]
A similar issue to this one was closed in favor of server-based test runners.
