### ISSUE TITLE
Teams Duplication

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4491]
I'm not sure why but I seem to have 2 of the same team on my teams dashboard.
 
<img width="964" alt="screen shot 2018-11-19 at 16 25 10" src="https://user-images.githubusercontent.com/5421823/48720757-3d807880-ec18-11e8-944c-cdde65fd76d9.png">

**Comment by sshine** [comment]
@nicolechalmers: Do you still, or can this bug report be closed?

**Comment by nicolechalmers** [comment]
@sshine I can't see duplication now so it looks like it's fixed. Thanks for checking.
