### ISSUE TITLE
Teams: my first impressions

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4492]
I signed into the new teams site for the first time.  This is what I was presented with:

![image](https://user-images.githubusercontent.com/6978003/48723834-b3271d00-ebf5-11e8-8f26-bb7078757008.png)

I opted to check out the Akron Code Club choice.  This is a team from V1.

Selecting team ACC I am presented with:

(I have obscured the team members identities)
![image](https://user-images.githubusercontent.com/6978003/48724412-21b8aa80-ebf7-11e8-9bb0-177755c6fdea.png)

None of the member listed is clickable in anyway, including myself.  I am also not an admin of this team.  The last two member listed are designated as admins.

If I click `Your solutions` I am presented with:
![image](https://user-images.githubusercontent.com/6978003/48724551-7b20d980-ebf7-11e8-9f6a-5c4b9ad5d7ca.png)

The `Track` drop down has no choices to select.  If I type a track name it is erased as soon as I click on the `Exercise` dropdown.

If I move on to `Other's solutions`:
![image](https://user-images.githubusercontent.com/6978003/48724652-cdfa9100-ebf7-11e8-947e-7539933058c0.png)

page behavior is the same as `Your solutions`.

`Members` looks like:
![image](https://user-images.githubusercontent.com/6978003/48724770-1d40c180-ebf8-11e8-8920-397600f98a3c.png)

I have hidden the names of the members.  The full names of the members appear in this list and no github handles.

I don't know if it was the intention to port teams from V1 to V2.  There doesn't appear to be any data behind the ACC team.  I am not an admin for this team so I cannot speak to that aspect of the operation of team interface.

It would be fine to remove this team.  None of the members is active (except for myself) on Exercism in such a way that warrants a team.

If I could be given admin rights I could further review the site via. this team.

**Comment by rpottsoh** [comment]
I have tried creating a new team.

**Comment by sshine** [comment]
I'm closing this issue, but as I've labelled it "area/teams", it can be found again.
