### ISSUE TITLE
Markdown inconsistency in code blocks within bullet lists

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#4494]
When giving Markdown feedback and adding a code block "within" a bullet list:

    1. Here be code:

           Codey McCodeface

    * Here be more code:

          Codey McCodeface

why must the code be indented by `4 + length("1. ")` or `4 + length("* ")`, respectively, rather than a fixed 8 spaces? It'd be very nice if it was a fixed amount, since 7 spaces are not nice, and a number of spaces that depends on the number of characters in the bullet symbol makes for a lot of irregularity.

Having 8 (or 4 + 4 x *number of nested bullet lists*) would be consistent with Stackoverflow.

**Comment by NobbZ** [comment]
Because this is how markdown works.

To make a block thing belong to the previous bullet point, you need to indent it to the same level as the previous content is.

Also a code block is indented by 4 spaces.

Thats why you need 7 spaces in the first case and 6 in the other.

As I tend to prefer backticks anyway, you also can use this:

````
1. foo

   ```
   # your code
   ```
```

**Comment by sshine** [comment]
> this is how markdown works

This is how the current implementation of Markdown works.

I'm arguing that

* Markdown works in many ways
* This way is not the same way as Stackoverflow
* This way is less ideal

and yes, using triple-backticks is probably preferrable to a variable level indentation. However, it does not read as nicely in plaintext, and since I'm using my code snippets more than any one student, I'd like for them to be convenient for me in plaintext.

I've refrained from using this combination of bullets and code blocks.

Feel free to close this issue if you disagree that it's bad.

**Comment by sshine** [comment]
I realize that this is also the choice for GitHub's Markdown.

I'll contend.

**Comment by NobbZ** [comment]
The version github uses complies with commonmark spec, as you can see in examples [233](https://spec.commonmark.org/0.28/#example-233) and [234](https://spec.commonmark.org/0.28/#example-234), please file a bug report at stack exchange, they need to repair their markdown parser.
