### ISSUE TITLE
Broken url

### ISSUE THREAD

**Issue by rt711** [exercism/exercism#4498]
On page: 
https://exercism.io/tracks/elixir/resources

The ExUnit link is broken, the currently working url is:
https://hexdocs.pm/ex_unit/ExUnit.html

I would submit this change directly to website-copy repository, but the elixir/resources page is missing from there.

**Comment by tejasbubane** [comment]
@rt711 The file resides here: https://github.com/exercism/elixir/blob/master/docs/RESOURCES.md please send a PR to that repository.

**Comment by rt711** [comment]
@tejasbubane Thank you, PR sent. Should I close this issue?

**Comment by tejasbubane** [comment]
@rt711 yes you can close this issue now.
