### ISSUE TITLE
Show estimate of how many other submissions are waiting for mentor feedback

### ISSUE THREAD

**Issue by crazyimp** [exercism/exercism#4504]
Hi,
before advancing in the normal mode (with mentor feedback), you end up waiting for feedback - some kind of estimate of how many other submissions are already in the queue would be great :).
A more advanced version would take the current feedback rate into account and show something like "your submission will be reviewed in about a day" or such.

**Comment by crazyimp** [comment]
@katrinleinweber

**Comment by sshine** [comment]
@crazyimp: This feature was added, so I'm closing this issue.
