### ISSUE TITLE
Make date of approval and mentor who approved visible in the UI

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4506]
As a student I'm interested in who approved my solution, especially when there were more than 1 mentors involved in the discussion **or** if the mentor simply gave no feedback at all.

In general as a student I am interested in the date of approval as well as the date of submitting each iteration or date of publishing.

**Comment by sshine** [comment]
@NobbZ: Is it not the case that email notifications mention the mentor who approved?

Perhaps for those who disable email notifications, it is still not apparent what mentor approved.

**Comment by NobbZ** [comment]
I'm pretty sure there weren't any names in the mail when I reported this. Also the :+1: reaction on the issue supports my memories :D 

Though I have done a shallow search for exercism related mails in my inbox, and it seems names are there.

So I think we can close this for now.
