### ISSUE TITLE
A couple of solutions is marked as approved and published without mentor interaction

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4507]
Yesterday I realised that some solutions of mine seem to be marked as approved and published without any interaction with a mentor.

Also those exercises do not appear in my git repository, which I started only weeks before the relaunch.

Since I only added exercises to the repository that I solved I can be sure that exercises missing in the repository are legacy. I can assume the same for all exercises that are missing the metadata file.

@iHiD asked me to open an issue and give some sample UUIDs:

* C#, Clock, 3571acf55d5340f9ac27c7f8d43724c3
* Clojure, RNA Transcription, 8cad2df3f3de4770bb11aa8ea6c0d3bb
* Clojure, Word Count, 1eb08f2acf1a49d8bbc8631cf4bf7d0f
* Crystal, Hamming, 2c7ef4fd0b2d48bb8abfa5dd136a2975
* Crystal, RNA Transcription, 0ce5d935392c408e837e334404d04f82
* Crystal, Bob, 431883905582499a829954ed05359625
* Crystal, Rainsdrops, 4b6761823d2649eeb34058fd57d02045
* Crystal, Leap, d39f09edb59d439297b931b65105efe2
* Crystal, Pangram, e23633758e0b4d3aa5eedf3cca901e1f

And there are probably many, many, more, I only skimmed the 6 tracks I joined which start with `C`, and only the core exercises. So there are 24 more tracks and a lot of side exercises to check if they are in the correct state.

**Comment by iHiD** [comment]
Hi @NobbZ. So all of these have been approved and published during the migration, which was the behaviour we chose to do back then. Is the problem that you want to submit these for mentoring but can't as they're already approved?

**Comment by NobbZ** [comment]
Yes, I want them to get mentored, but I can't because they are already approved and published.

And why have these already been approved, while there have been and still are others which are published but marked as legacy, such that I can put them into a mentors queue?

**Comment by iHiD** [comment]
Trying to debug....

Is there a pattern where the core exercises are not available, but the side exercises are?

**Comment by iHiD** [comment]
@nobbz Does this give you the option now?: `C#, Clock, 3571acf55d5340f9ac27c7f8d43724c3`

**Comment by NobbZ** [comment]
Yes, I can request mentoring on that exercise now.

**Comment by iHiD** [comment]
Great. Thanks. The others should work for you as well now.

**Comment by NobbZ** [comment]
Today something like this has happened again.

I was looking at iteration 1 of 4554fbbadb2a463a813f9629e51a4983 (side), "this has been imported from an earlier version", then I downloaded it, solved against the tests associated to it due to the import (tests have changed between initial submission and ETL) and then submitted it. After submitting the solution was marked as **published**. I was unable to request mentorship for this exercise.

Another exercise 7394a312896646ce8457dd40eb6ebb0d (side) a couple of hours earlier, was also marked as import but also was marked as "testsuite has been updated", so I clicked the update tests button, downloaded, solved, submitted and I was able to request mentorship.

**Comment by NobbZ** [comment]
Even worse, as I realise now... for 4554fbbadb2a463a813f9629e51a4983 the **newest** submission has been published, but the comments I left there back in v1 on the first iteration are displayed on the site.

**Comment by NobbZ** [comment]
It seems as if I learned a little bit more about this issue today.

I wanted to go through some legacy solutions again, update them to make them match the current testsuite and then request mentorship for them.

So I downloaded d937ef6f3c45400d96187667d8aa3fe9 (elixir/bob) as it was marked legacy.

To make it pass the current tests, I had to rename the module and add a check for "forceful shouting" as this new category has been added since I submitted the exercise the last time.

Now the tests passed and I submitted the updated file. Now the solution is marked as "completed and published".

I like to get it reviewed by a mentor.

**Comment by sshine** [comment]
@NobbZ: Does this only relate to legacy solutions?

What would you propose we do in order to resolve this issue?

**Comment by NobbZ** [comment]
According to our observations, this is only an issue for legacy submissions.

And a solution to the problem were to not change there status to "published" after updating them. Perhaps even keep the "legacy" status? But changing them to regular submissions that haven't been completed would be totally fine.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
