### ISSUE TITLE
Feature request: Slack bot (queue status, recommend solutions to mentors)

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#4508]
## Feature 1: Queue status

Lately I've hacked together a status report for #track-haskell; it looks approximately like:

    Core queue status:
    0 `Leap`, 0 `Space Age`, 8 `Bob`, 8 `Pangram`, 1 `Collatz Conjecture`, 0 `RNA Transcription`, 2 `Sum Of Multiples`, 0 `Difference Of Squares`, 0 `Grains`
    Total: 19
    Wait: 6 days

    Non-core queue top 3 waiting time:
    4 `Anagram` (2 months)
    2 `Hamming` (3 months)
    3 `Nucleotide Count` (4 months)
    Total to get below 1 month: 9

It's semi-automated by hacking the internal mentor queue API and dealing with session cookies.

A public API for this information was requested in #4087, and in particular [in this comment](https://github.com/exercism/exercism/issues/4087#issuecomment-422041252).

One path to a more maintainable solution for this could be:
- Make the internal API able to spit out JSON besides HTML embedded in Javascript based on HTTP headers.
- Add token-based authentication next to session-based authentication by giving the token in `~/.config/exercism/user.json` if the user is a registered mentor.
- *(Document the API.)*

Then features like Slack bots could be crowdsourced and popularised with less effort.

## Feature 2: Recommend solutions to mentors

I've been thinking of prototyping a recommender bot saying something like

    Hey @sshine, someone just posted a solution to Space Age! Want to mentor it? https://...

It can be built by *polling* on the API above, or we can *push* these notifications as students publish solutions. It should be opt-in, and it shouldn't assume that if because you've already done a bunch of one type that you necessarily want to do a bunch more.

As an extra feature, recommend exercises to everyone if there are mentoring notes available.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
