### ISSUE TITLE
Solution to core exercise remains unreviewed since October 13th

### ISSUE THREAD

**Issue by fdumontmd** [exercism/exercism#4514]
Hi,

my solution to rust / parallel-letter-frequency (https://exercism.io/my/solutions/eb4e4d40b3504d3e8523361d82963e67) has received no feedback from mentors since it was submitted on October 13th.

For the previous exercises, I would get a review in a week, two at most.

My apologies if it's all normal and due to mentors being overloaded.

**Comment by sshine** [comment]
I can see that the average waiting time on the Rust track is currently one month, at least for the later core exercises. So it appears to be the case that mentors are simply being overloaded. :-)

**Comment by fdumontmd** [comment]
Thank you for the feedback; I'll wait then (I have the Advent of Code to keep me busy).
