### ISSUE TITLE
Missing error translation in API when requesting solution file

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4517]
If you request a solution file from the API and it cannot be found, the API responds with a 404 and an error message, however the message in this case is an i18n error saying that the translation of the message is missing.

E.g.:

```
 curl h -v -H "Authorization: Bearer $API_TOKEN" https://api.exercism.io/v1/solutions/$UUID/files/path/to/file.ext
...
{"error":{"type":"file_not_found","message":"translation missing: en.api.errors.file_not_found"}}
```

I don't think we need a very fancy error message, maybe something like "The file was not found."

This is a pretty straight forward fix, I think. We probably just need to add an entry to the i18n file in the [website repo](https://github.com/exercism/website). The file is at `config/locales/en.yml`.

I triaged this as "priority/medium" because we do not yet show this message in the CLI, but there is a pull request in progress that will add the behavior to show error messages from the API.

**Comment by pgaspar** [comment]
@kytrinyx I can take this on if that's ok with you :+1:

**Comment by iHiD** [comment]
@pgaspar Go for it :)

**Comment by iHiD** [comment]
Could you also add a testcase for this scenario as I'm presuming there's not one as we didn't see the incorrect message. Thanks :)
