### ISSUE TITLE
Write a script to reconcile maintainers.json and actual maintainer team

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4520]
We have active maintainers who are not currently listed in the maintainers.json file, and inactive maintainers who (probably) are.

We need to nag active maintainers to add themselves, and ask inactive maintainers if they'd like to set themselves to "alumnus" status (they can always come back if they get the bandwidth back in their life).

**Comment by abir4l** [comment]
I want to start contributing and I'm interested in this issue, however, I can't seem to locate the maninainers.json file on the website repo, could you share a bit more info on the file.

**Comment by rpottsoh** [comment]
Each track has a maintainers.json file located at `exercism/<track id>/config`

**Comment by abir4l** [comment]
Thank you for that. I can now locate the files and hopefully write a script that lists the maintainers, but I'm confused with the nagging and asking part, should the script email the users or send some notification through GitHub, which i can't find in API documentation of GitHub, can you clarify this bit to me please?

**Comment by rpottsoh** [comment]
I can't really clarify for you, I think @kytrinyx will need to do that for you.  My suggestion, however, would be to inform people via github and not by direct email.

**Comment by kytrinyx** [comment]
GitHub doesn't have an API directly for notifications, and we don't want to email people directly (also, not everyone has a public email address on GitHub). I think the nagging itself would probably have to be in the form of opening an issue in the repo for that person.

> I hadn't used the website before this, so would i be right to assume the feature needed is on the website?

Only indirectly. The `config/maintainers.json` file is used to show the maintainers on the site (e.g. https://exercism.io/tracks/ruby/maintainers)

**Comment by kytrinyx** [comment]
Thinking about this a bit more, I think we have the following scenarios when comparing the GitHub team to the maintainers file. Here are the possible combinations that we'd find for a given person.

1.
- :x: GitHub team
- ✅ maintainers.json, alumni: true
- ➡️ This is fine. No action necessary.

2.
- :x: GitHub team
- ✅ maintainers.json, alumni: false (or missing)
- ➡️ Open PR to update the maintainers.json file to have `alumni: true` for that user. (Can be scripted)

3.
- ✅ GitHub team
- ✅ maintainers.json, alumni: false (or missing)
- ➡️ This is fine. No action necessary.

4.
- ✅ GitHub team
- ✅ maintainers.json, alumni: true
- ➡️Open issue for me (`@kytrinyx`) to remove them from the team

5.
- ✅ GitHub team
- ❌ maintainers.json
- ➡️Open an issue that asks that person to add themselves to the maintainers file, or remove themselves from the GitHub team if they're no longer actively maintaining. They're always welcome to come back later!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
