### ISSUE TITLE
Accessibility - font sizes are small and hard coded

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism#4521]
It seems to me that the font size of a good portion of the text on the web site is unnecessarily small, which would make it hard to read for people who do not have good eyesight. Furthermore, the vast majority of the font-sizes are encoded using pixels rather than relative units such as em. The reason this is significant is that some users change the default font size in their browser to make it larger so that text is easier to read, but font-sizes coded in pixels will override these settings. If the font-sizes were set using 'ems' then they would adjust along with the default font size of the browser.

**Comment by PatrickMcSweeny** [comment]
@rpottsoh As for font sizes being hard coded, almost all of the font sizes are set using pixels so that speaks for itself. Here's a screen shot from a track page where I noted some of the text with small font-sizes.

![screenshot from 2018-12-03 12-19-18](https://user-images.githubusercontent.com/1254212/49390661-872c9100-f6f7-11e8-9c69-7c9c5af04121.png)

**Comment by rpottsoh** [comment]
Thanks this will be helpful to others.  I had tried areas of the site that are essentially just text (derived from MD) that appear to scale just fine when I adjust the zoom setting in Chrome.

**Comment by PatrickMcSweeny** [comment]
I realize that zooming is an option but I still think it would be good to use relative font sizes. I personally like to adjust the default font size in my browser and when I use websites that hard code their font sizes I feel like an element of control is being taken away from me.

**Comment by rpottsoh** [comment]
I understand better now, this makes sense.  Thanks for explaining.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
