### ISSUE TITLE
submitting

### ISSUE THREAD

**Issue by cvivona** [exercism/exercism#4523]
I downloaded and coded the hello world file and cannot figure out how to submit.  it is saved to  D:\Python Programs\hello_world.py. and it says it cant find the file. I dont know what to do

**Comment by NobbZ** [comment]
Hello @cvivona!

One thing to consider is, that windows (as well as linux) needs spaces to be escaped in one way or another. The simplest way were to use doublequotes (`"`) around the path to the file.

The other thing I realize with your command is, that it doesn't look like the usual path that exercism would expect.

The CLI strictly requires you, to have all solutions below the folder that is configured as your workspace.

And under the workspace you need a folder for the track and then for the exercise.

The best way is to simply edit, test and submit the exercises from where they are downloaded to by `exercism download --track=... --exercise=...`.

**Comment by NobbZ** [comment]
hello @cvivona, have you been able to sort out your issue or do you need further
