### ISSUE TITLE
Solution uploaded in a C:/Exercism/go/triangle-2/ subdirectory

### ISSUE THREAD

**Issue by bitfield** [exercism/exercism#4531]
In [Solution dab161dff305454ba184bf721f759465](https://exercism.io/mentor/solutions/dab161dff305454ba184bf721f759465), it looks as though the student has run something like:

```
exercism submit C:\\Exercism\go\triangle-2\triangle.go
```

and thus we've ended up with this file layout:

```
.
├── C:
│   └── Exercism
│       └── go
│           └── triangle-2
│               └── triangle.go
├── README.md
└── triangle_test.go
```

Is this a known issue?

**Comment by kytrinyx** [comment]
Yeah, this was a bug in the earliest versions of the new CLI.

I *believe* I've gotten the CLI side of things sorted out (provided that they actually upgrade their CLI). I've opened a couple issues to get legacy data cleaned up and to ensure that if we do see a numeric prefix, the API responds with an error asking them to upgrade their client.

https://github.com/exercism/exercism/issues/4519

I'm going to close this one, as I think the other issues cover it, but we may find that we've overlooked some part of it once we get the data cleaned up. In that case we can reopen this (or open a new one to address specifically the bits that are left over.

Thanks @bitfield !
