### ISSUE TITLE
mentorcism: Consider dropping star-based rating

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#4541]
This issue comes from both the standpoint of me as a student and me as a mentor.

## The current state
First, let's look at what exercism says about rating mentors:

> **Rate your mentors**
> Help us improve our mentoring by rating your mentors.
> Your mentors *will not* see your rating.

I am assuming that _us_ here is the exercism collective including myself as mentor.

Second, let's see what I get as a mentor:

> **YOUR MENTOR RATING**
> 4.8 / 5
> The median mentor rating is 4.83. If you'd like to improve your mentor rating, check out the community mentor notes on each solution, which provide useful pointers.

IIRC the message changes a bit when it's above the median to something like "you're doing great".
As noted by #4496 and also [mentioned by Tim Hawes](https://exercism-team.slack.com/archives/CARRG4MNC/p1542578239156500), as a mentor this rating doesn't do anything for us other than _maybe_ add some gamification for some of us without _any_ way of actually receiving feedback on how to improve unless we ask for it.

## The problem as a mentor

> https://exercism-team.slack.com/archives/CARRG4MNC/p1542578239156500
> **Tim Hawes**: You know, something that just dawned on me, is that mentor rating is really quite useless as a self evaluation tool without any comments on how to improve. My rating has been slowly declining, I guess that is to be expected as the number of solutions one mentors increases, but I wish I knew where I fell short, if it is something I could make better.

In short: without actual feedback _nothing_ is telling me what I did right or wrong and how to improve it. 

I found myself negatively impacted when suddenly my perfect score dropped to 4.83, climbed back to 4.92 and dropped again to 4.8, climbed to 4.9 and dropped back to 4.8. What am I not doing perfectly? This whole messaging about the median and "how to improve" only indicates that I'm doing _something_ wrong, good luck to me figuring out what exactly.

That brings me to the second point, also made by @F3PiX:

## The problem as a student

> https://exercism-team.slack.com/archives/CARRG4MNC/p1543052170182100?thread_ts=1542578239.156500&cid=CARRG4MNC
> **Maud de Vries**: I'm not convinced at all that mentors should strive for 5 * ratings, nor that good mentoring always receive 5 *.
> **Maud de Vries**: I'm also not convinced that it's a good idea to ask students to help make the mentor better. To me, a student should invest in their own learning, not in their mentor's learning. I feel the mentors should help other mentors to get better.

As a student,
- when I deliver a "perfect" solution, I usually don't rate the mentor at all, because they didn't mentor me; this is different for other people. 
- when the mentoring is good as in nothing special, I only give five (5) stars because I know it will impact them negatively if I give four (4) stars, but personally I want to reserve that for something exceptional; this is different for other people
- I don't actually see the rating a mentor has, I don't see the impact of my rating, and my rating is nothing more than an arbitrary value that is probably 5 stars for the majority of all ratings.
- how is this rating helping them if they don't see it? I have so many questions as a student because of the dialog and the way it is worded.

## Proposal
I don't know how to fix this, but:
- apart from allowing people to _comment_ on the mentoring (#4496) I would drop the star rating altogether because it only detracts from the mentoring.
- if rating is something we want, rate up or down.
- if rating stays as it is, stop counting ratings given on 0 interactions or "Thanks" messages. These ratings don't indicate any mentoring and only in- or deflate your rating.

Youtube and Netflix switched to thumbs up and down, medium only has positive "wordless" feedback now, in order to give negative feedback you must comment. If gamification is something that we want, instead allow students to give mentors badges like with Uber: "Great Conversation", "Learned Lots", "Pushes Me to be Better", and use the "less than perfect" rating with a "what went wrong" like on Uber, Deliveroo, DoorDash and many other services: "Pedantic", "Don't understand the suggestions", "Unclear explanation".

## Additional context
http://www.evanhamilton.com/star-rating-systems-j-curve/
http://www.lifewithalacrity.com/2005/12/collective_choi.html

**Comment by alex-bender** [comment]
To have badges like with Uber it a great idea.
Also, probably it could be useful if students would be able to can vote for mentor notes to kind of promote notes into mentoring notes if the note is actually good written.

**Comment by F3PiX** [comment]
@SleeplessByte: thanks for bringing this up and the thoughtful explanation. 👍 
  
As quoted, I'm all for not star rating the mentors, I'd prefer that students would rate what they learned from an exercise. (The Uber-like badges sound great.)

In the meantime, I'd prefer to see what the mean/average of mentoring for a specific _exercise_ is, as a comparison, rather than the mean of mentor ratings. I believe that would be a step in giving mentors information about the result of what they're doing.

**Comment by SleeplessByte** [comment]
Yes. That would already help. It's still very opawur, but is at least
trackable on a personal level

**Comment by saveriomiroddi** [comment]
> I found myself negatively impacted when suddenly my perfect score dropped to 4.83, climbed back to 4.92 and dropped again to 4.8, climbed to 4.9 and dropped back to 4.8. What am I not doing perfectly?

Found myself in this situation as well. Ultimately, I think a minimalist approach like having testimonials only could be preferrable - if a student is particularly happy, they'll leave a testimonial, if they don't, they leave things as they are. As a mentor, I can acceptably understand the general satisfaction just by looking at how many people is happy.

There's clearly always a downside of having a measurment less, if one's really into "data science" :grimacing:. But even in this perspective, the average star rating is too much of a black box to give any value - having a median of 4.83 means that essentially everybody's getting 4 and 5 stars, which in turn shows that the starts don't work the intended way. Now that I think about it, since there are essentially only two evaluations, a (transparent) thumbs up/down (and none) would fit better.

**Comment by yyyc514** [comment]
>  a (transparent) thumbs up/down (and none) would fit better.

You need an "i was pleased" cue at least if you're going to have testimonials (in there current form).  Right now you're only asked about a testimonial if you leave a 5 star rating.  So we always get positive, encouraging testimonials. 

If every student just got a blank box asking for thoughts then surely some fo the time we'd get "un-testimonials".  Of course that might also be valuable... but then I'd want some way to manage my testimonials - learn from and delete the negatives, etc.

**Comment by saveriomiroddi** [comment]
> You need an "i was pleased" cue at least if you're going to have testimonials (in there current form). Right now you're only asked about a testimonial if you leave a 5 star rating. So we always get positive, encouraging testimonials.
> 
> If every student just got a blank box asking for thoughts then surely some fo the time we'd get "un-testimonials". Of course that might also be valuable... but then I'd want some way to manage my testimonials - learn from and delete the negatives, etc.

Maybe there could be a system with thumbs up/neutral/down plus a comment box, where:

- in case of positive, the comment is published (as testimonial);
- in case of neutral/negative, it's not published, and in the latter case, it's also notified to the admins.

In real world, I guess neutral/negative reviews are going to be comparatively very little (considering that the "median is 4.83" :wink:), and I think there's nothing wrong with not publishing neutral/negatives, as long as it's communicated to the student. The thumb neutral/negative has an effect, anyway, if the student intends to affect the overall mentor rating.

**Comment by boazjr** [comment]
I just started mentoring and I was surprised by this score. I agree with most of the comments here: 

I think the data is practically non actionable. 

Students can get more out of mentors by continuing a discussion. It's not a one sided relationship- you are not being spoon fed, you are given an opportunity to grow, which can be challenging. For example, if a student doesn't understand something the mentor is communicating it's up to him to ask which enables the student and the mentor to improve. Leaving a rating doesn't add any value. 

Assuming that students took time that the mentor reciprocated. The outcomes are: the student learned something, or the student  is frustrated with the relationship.

If the student is frustrated with the relationship, he should be given a new mentor - actionable.  

There needs to be an additional edge case for inappropriate behavior - swearing, sexual innuendos, and such, which both the mentor and the student should be able to raise if they choose to.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
