### ISSUE TITLE
mentor: show the valuabilty of decisions to mentor

### ISSUE THREAD

**Issue by MaksimDanilau** [exercism/exercism#4542]
From my perspective, the mentoring of tasks from tracks is more valuable.

So, it will be great to have on the mentoring dashboard the mark (some label) that shows that the task is a part of the main language track.

Now, also, there is no any opportunity to see the structure of the main track in independent mode.

**Comment by iHiD** [comment]
Hi @MaksimDanilau - I'm not sure I quite understand. By the "main track" do you mean the "core exercises"? If so, then they are already marked as "Core".

**Comment by MaksimDanilau** [comment]
Hello @iHiD, @NobbZ . Yes, I meant "core exercises". I don't know how, but I really didn't see any of this labels. I was searching for a filter in the filtering panel, and then, when I haven't found it, I wrote an issue.

So, the "core" mark was in the blind spot for me. Thanks for your comments, and sorry for wasting your time.
