### ISSUE TITLE
Wanting To Help

### ISSUE THREAD

**Issue by ClockworkOmega** [exercism/exercism#4543]
Hey Guys,

I'm a senior computer science major and I'm looking to get some experience contributing to open source projects and advancing my knowledge. I primarily have been taught in C++ with some limited experience in C# and Python. Is there anything I can do to help out or even maybe offer review of C++ code? I appreciate any feedback you can give me.

**Comment by PatrickMcSweeny** [comment]
Have you looked into becoming a mentor?

https://exercism.io/become-a-mentor

**Comment by PatrickMcSweeny** [comment]
Another way to contribute is to become a track maintainer:

https://exercism.io/become-a-maintainer

Here is the repository for the C++ track:

https://github.com/exercism/cpp

**Comment by ClockworkOmega** [comment]
Thanks for the advice. I'll look into those options and try out some of the current course work to see how it all works.
