### ISSUE TITLE
Exercism submit first exercise 

### ISSUE THREAD

**Issue by chloesf** [exercism/exercism#4545]
Hello, trying to submit my first exercise on the Go Track. 
I keep getting the Error: 

    The file you are trying to submit cannot be found.

Version
----------------
Current: 3.0.11
Latest:  3.0.11

Operating System
----------------
OS:           darwin
Architecture: amd64

Configuration
----------------
Home:      /Users/chloe
Workspace: /Users/chloe/Exercism
Config:    /Users/chloe/.config/exercism
API key:   21b4*****************************ec3

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 117.84469ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 240.051699ms

**Comment by NobbZ** [comment]
What is the command you use when you submit, from which folder do you do that?

**Comment by chloesf** [comment]
exercism submit /Users/chloe/Documents/Any folder/main.go

**Comment by NobbZ** [comment]
Literally 'Any folder' with a blank? You need to escape it.

Anyway, that given path is not in your exercism workspace. Do not move the files around after you have downloaded them using `exercism download`.

**Comment by sshine** [comment]
Due to the passage of time, I'm closing this issue.

@chloesf: If you by any chance still need help submitting issues, please write back.
