### ISSUE TITLE
Suggestion: Mentor scoring calculation

### ISSUE THREAD

**Issue by dstockto** [exercism/exercism#4547]
Despite a mentor's best efforts some students are not looking for that interaction or maybe have had a bad day or any other reason. This means that an otherwise excellent mentor can receive an anomalously low score. The opposite may be true as well and a poor mentor could receive an anomalously high score from a student who doesn't feel comfortable giving a lower rating for poor mentoring.

The suggestion would be to remove the top and bottom 5% of scores from the calculations so that these anomalous scores will not have an impact on a mentor's ratings.

**Comment by SleeplessByte** [comment]
I still think #4541 is the better way. This doesn't actually fix this issues and only hides them deeper. The fact that "5 stars" does not have the same meaning to everyone is at the core issue here.

**Comment by ConSou** [comment]
Hello,
Is removing the top and bottom 5% something we still want to do?  If so I can work on adding the trimmed mean of the ratings as the mentor rating.  Or is another solution based on #4541 the route this is going?
