### ISSUE TITLE
Old logo/branding on 24 Pull Requests page

### ISSUE THREAD

**Issue by missmatsuko** [exercism/exercism#4548]
Found this page via the 24 Pull Requests site: http://24pullrequests.exercism.io/

The branding and logo is totally different from the main Exercism site. I'm guessing it's using the old logo and branding?
https://exercism.io/about-v1-to-v2

**Comment by iHiD** [comment]
Thanks for reporting! 

@kytrinyx Thoughts?

**Comment by kytrinyx** [comment]
Shoot. I missed this, and now it's basically Christmas.

How about we take down the site, @iHiD ? (I can do that by deleting https://github.com/x24pr)

**Comment by missmatsuko** [comment]
If the page is being deleted, might want to redirect the page to the main GitHub repo also.

**Comment by iHiD** [comment]
@kytrinyx So a redirect from http://24pullrequests.exercism.io/ to https://github.com/exercism/exercism?

**Comment by iHiD** [comment]
@ccare Could you please add a redirect from http://24pullrequests.exercism.io/ to https://exercism.io/contribute

**Comment by missmatsuko** [comment]
Looks like the redirect has been added

**Comment by iHiD** [comment]
Thanks for following up!
