### ISSUE TITLE
Remove "TODO: The maintainers have not provided a description for this track." message from track descriptions

### ISSUE THREAD

**Issue by missmatsuko** [exercism/exercism#4550]
There's several tracks here on the [tracks listing page](https://exercism.io/tracks) that have this text as its description:
> TODO: The maintainers have not provided a description for this track.

Can this text be removed and the default be a blank description instead? I don't think there's much benefit to showing this message, except maybe to remind maintainers to add content. It also appears on the track's detail page (e.g. https://exercism.io/tracks/purescript).

Additionally, I clicked through to one of the tracks that is missing a description, and it does have about content:
https://exercism.io/tracks/vimscript

In this case, can we default to the first X characters or paragraph(s) of the about content?

**Comment by iHiD** [comment]
Hello. Thanks for the issue. I'm not sure I want to remove this as I want maintainers to add it. It feels like a simple thing that maybe the community could help with. Do you fancy PRing for vimscript?

**Comment by missmatsuko** [comment]
Still, I think it'd be a better experience for learners if it defaulted to empty text instead of the existing TODO text.

Can we remove the default TODO text *and* make issues in the tracks that are missing descriptions? I wonder if maintainers even look at that page on the site, maybe they don't know it's missing content.

**Comment by iHiD** [comment]
I'll think about it. I'm not sure what's changed since we launched to justify removing the TODO. It **is** a bad experience but that's sort of the point. It's a canary for that track's maintainers not having the time or desire to fix it, and therefore hopefully encourages other people to come and get involved in fixing it, and involved in Exercism in general.

**Comment by iHiD** [comment]
There is already an issue open for this on every track btw.

**Comment by missmatsuko** [comment]
It seems like that's the only place where a TODO message is displayed on the front-end.

You agree that it's a bad experience - why punish the users for something maintainers haven't gotten around to yet?

Since there's an issue, that should be the reminder for them to get to it rather than a TODO message on the frontend.

**Comment by iHiD** [comment]
Totally. And that's exactly why it's there. To say to the maintainers "your bit of the site looks incomplete". I entirely agree with everything you're saying, but my desire to find helpful people out there who might contribute to fix things, outweighs my desire to provide a finished-looking experience. Exercism isn't finished - it totally needs people to help and make it better.

Maybe we should change the language to "TODO - Help improve Exercism and provide a description" hyperlinked to the open issue in the repos. Maybe that would have the desired effect better.

**Comment by docljn** [comment]
Hello from a code-triage volunteer.

As this issue has been open for several years, and the cofounder (@iHiD) has stated their preference for the status quo, I would like to propose that this issue be closed.
