### ISSUE TITLE
"I'll pass, thanks" is now "Leave conversation"

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4555]
@bitfield commented on [Tue Dec 11 2018](https://github.com/exercism/website-copy/issues/659)

On the 'Mentoring workflow' page the references and screenshots to the "I'll pass, thanks" button need updating to "Leave conversation".

---

@rpottsoh commented on [Sun Dec 16 2018](https://github.com/exercism/website-copy/issues/659#issuecomment-447694164)

[mentoring_workflow.md](https://github.com/exercism/website-copy/blob/master/pages/mentoring_workflow.md)

---

@rpottsoh commented on [Sun Dec 16 2018](https://github.com/exercism/website-copy/issues/659#issuecomment-447694963)

cc: @iHiD 

I think this should be moved to exercism/exercism.

**Comment by iHiD** [comment]
I think they're different. "I'll pass now" is before you join a conversation, "leave conversation" is once you've joined it.

**Comment by bitfield** [comment]
Oh, my bad, sorry. Maybe a note here in the document would be helpful ("For solutions you're already mentoring, this button will show "Leave conversation" instead. Clicking it will abandon the solution and return it to the mentor queue, but you won't ever see it in your dashboard again.")

**Comment by iHiD** [comment]
Yep. Happy to accept a PR for that!

**Comment by bitfield** [comment]
Should the PR be against `exercism` or `website-copy`?

**Comment by rpottsoh** [comment]
The PR will have to be in website-copy as that is the repo that contains [mentoring_workflow.md](https://github.com/exercism/website-copy/blob/master/pages/mentoring_workflow.md).  The PR should close this issue.
