### ISSUE TITLE
Discussion: mentoring by students

### ISSUE THREAD

**Issue by MaksimDanilau** [exercism/exercism#4556]
As a student on the Phyton-track, I see the real lack of mentors. By my calculations, every mentor should approve approximately four hundred decisions to move all students of track forward. 

In my mind, students, that have passed some task, are able to mentor it. They already focused on it and really in context. So, in some way, they can share their experience.

Finally, I suggest discussing the opportunity of mentoring by experienced in some field student.

**Comment by iHiD** [comment]
Anyone can become a Python mentor. They just need to go to the become-a-mentor page and sign up. There's no barrier :)

**Comment by iHiD** [comment]
Well, if someone doesn't have knowledge or expertise, then I'm not sure they would be a good person to mentor someone else's solutions? They are either good enough to mentor (so can become a mentor) or not good enough to mentor (in which case they shouldn't give feedback). 

Maybe they **are** good enough to mentor, but they don't **believe** they are good enough to mentor. If that is the case then that is a different question about how we make mentoring feel more accessible, which is something we can address. But the barriers are there for a reason, as we want to protect the quality of mentoring. 

We have lots of changes and improvements coming generally, and specifically to the Python track, which will hopefully make it as responsive as other tracks (where you normally receive feedback almost immediately).

**Comment by MaksimDanilau** [comment]
@iHiD Sounds great! I will close this discussion for now. Your point of view about mentoring feel is strong, I agree with it.

Thanks!
