### ISSUE TITLE
Solution filter improvements

### ISSUE THREAD

**Issue by alex-bender** [exercism/exercism#4560]
Hey guys, I've almost cleaned the python queue -- from 15 days to 3. So it was near to 100 back and forth from solutions list page (`https://exercism.io/mentor/dashboard`) to the specific solution (`https://exercism.io/mentor/solutions/<hash>`). And here what I found:
The filtering disappears when you go back from solution page to the list one, by clicking browsers "Back" button.
Steps to reproduce:
1. Go to mentor dashboard
2. Next solutions to mentor, filter tasks, enter "Leap" for example
3. Visit the solution page
4. Click back
5. The `Exercise` field is still populated with "Leap" but the list isn't ordered by exercise.

Additional thing -- it would be nice to know how many solutions are pending. I'd like to know an approximate time what I need to spend on reviewing all existing solutions for the specific task.

As about filter -- maybe it would be better to add `#leap` or `/python#leap` to the URL to make this filtered list accessible from the outside directly?

Thanks

**Comment by iHiD** [comment]
> Hey guys, I've almost cleaned the python queue -- from 15 days to 3. 

That's absolutely amazing. Thank you!!

> The filtering disappears when you go back from solution page to the list one, by clicking browsers "Back" button.

Is this a duplicate of https://github.com/exercism/exercism/issues/3975 ?

> Additional thing -- it would be nice to know how many solutions are pending. I'd like to know an approximate time what I need to spend on reviewing all existing solutions for the specific task.

Yeah - that's a good idea. The reason it's not there is simply because the SQL to do this is quite slow at the moment. But it's something I'm working on.

**Comment by alex-bender** [comment]
Yeah, seems that it's a duplicate.
And great to know that `counter` is coming soon! Thanks!
Should I close the issue then?

**Comment by iHiD** [comment]
Could you open an issue for the counter (just copy/paste what you wrote here) pls? I don't think it's covered anywhere atm.

And then yeah, closing would be great. 

Thanks again for doing Python - you might be interested in these, which aim at making mentoring quicker moving forward:
- https://github.com/exercism/python/issues/1614
- https://github.com/exercism/python/pull/1633

**Comment by alex-bender** [comment]
Here is it: https://github.com/exercism/exercism/issues/4561
Going to read those tickets.
Thanks!

**Comment by F3PiX** [comment]
> Hey guys, I've almost cleaned the python queue

O wow!! That's amazing! 
And, it's also such a great start for the restructured track PR, where Jeremy pointed to.

**Comment by alex-bender** [comment]
@F3PiX Thanks!
