### ISSUE TITLE
Can't progress in mentor mode, can't ask for feedback in independent mode

### ISSUE THREAD

**Issue by garare** [exercism/exercism#4562]
I was blocked from progressing to the next exercise while in mentor mode because I had to wait for a mentor to approve the exercise I was on. I couldn't wait so I decided to try independent mode. I completed an exercise in independent mode, and now I can't ask for mentor feedback.

**Comment by F3PiX** [comment]
Hi garare! 
Just checking: 
- do you mean you can't ask for mentor feedback on the exercise you completed*? Or you completed exercise X, started exercise Y, and can't ask for mentor feedback on exercise Y?
- What do you mean by 'can't ask for mentor feedback' ? Is the button on the screen, is it disabled? Maybe add a screenshot?

**Comment by garare** [comment]
I completed exercise X in mentor mode. Couldn't progress to exercise Y because it's locked and I have to wait for mentor approval on exercise X. Switched to independent mode and I'm now able to attempt exercise Y. Finished exercise Y and can't ask for mentor feedback because button is disabled.

![screenshot from 2018-12-19 17-16-56](https://user-images.githubusercontent.com/40824712/50253978-ebb34580-03b1-11e9-9f2b-285b37c54dae.png)

**Comment by F3PiX** [comment]
Cool, that helps. Next check: did you request feedback on side exercises when still in Mentored Mode? 
(You can check on the your track page https://exercism.io/my/tracks/... . Exercises that you requested mentoring on are marked with a green text balloon.)

**Comment by F3PiX** [comment]
NO, wait, in Independent Mode mentor feedback is disabled. This is the message when switching to independent mode on the Python track:
>In Independent Mode all of the exercises within a track are unlocked and students can work through them freely. Note that in this mode Mentor feedback is disabled. This mode is for people who want to do fast deep-dives into a track and is not recommended for those that want the full Exercism experience.

**Comment by iHiD** [comment]
@garare What's the id of the solution from the screenshot? (You can find this in the URL). Thanks :)

**Comment by iHiD** [comment]
@garare So from checking the database (which is 21 days further forward than when you posted so things might have changed) it seems that you have requested mentoring on a couple of solutions already for this track. You can only request mentoring for one exercise at a time as @F3PiX says, so I think that's the issue here. Does that make sense?
