### ISSUE TITLE
ruby track excercise status - request mentor feedback

### ISSUE THREAD

**Issue by mikewalker** [exercism/exercism#4563]
I believe that there may be an issue with some exercises. From what I under stand there should only ever be 3 side exercises waiting for feedback. In the ruby track I appear to have 5 exercises with that state. I'm not sure if this has anything to do with it but I did just recently unpause the ruby track. 

Also I noticed that none of these exercise will allow me to cancel the mentor feedback request.

![screenshot from 2018-12-19 20-27-42](https://user-images.githubusercontent.com/1875177/50263971-4908c000-03cd-11e9-87f2-fe1f31c8ddb7.png)

All of the exercises that show the little speach bubble thing in the upper right show the message "Well done on submitting. A mentor will leave you feedback as soon as possible."

**Comment by iHiD** [comment]
Please could you send me some of the ids of the solutions (you can get this from the URL when you click on a solution). Thanks.

**Comment by mikewalker** [comment]
Just noticed something about these exercises when I was getting the id's for you. It looks like thay may have been completed prior to v2. These exercises did receive some feedback when completed in v1 of exercism. I had the ruby track paused for a while possibly during the period that the mentor feedback process changed.

These exercises also seem to be counting towards the maximum requests, so I am unable to request 
feedback on any other exercise now.

Here are the id's. 

26ab4838d5b24514a1b8e270c692265f
333a08bcbb5046c69b2122dcce381a5b
2eac9ad848c043f3aab5bcac0e79fed0
e90fd0b95dc6410ca36053b1ed838eb3
72fbc1be7a944385b727db2fb79e4d04

**Comment by SleeplessByte** [comment]
I'll take these.

**Comment by mikewalker** [comment]
I think we might still have an issue here. Thanks to @SleeplessByte there are no longer 5 exercises waiting for mentor feedback. We are now below the maximum of three so the request button should be enabled again for other side exercises.

There are now two that are not completed now and are in process. So if you count those two towards the maximum of three requests there should be one available. However the request mentor feedback button is still disabled on other exercises.

**Comment by mikewalker** [comment]
Another piece of the puzzle. I noticed that there is a deprecated exercise that I had completed in v1. Since I cannot open it to get the id, I downloaded it, updated the code and submitted again. This gave me the id that could then open. The deprecated exercise is showing a status message.

Well done on submitting. A mentor will leave you feedback as soon as possible. 

So maybe this is also counting towards the mentor request count? It is also showing as a side exercise if I open it using the direct link. Its id in case you need it is ef1c372fa8c34d018efbdfd24a5f43d5.

**Comment by mikewalker** [comment]
I do believe we have it, the deprecated binary was just approved and now the request for feedback is enabled again. Once other two are completed I'll check and make sure the limit of three is working as expected. I anticipate that it will now.

**Comment by mikewalker** [comment]
This can be closed now, everything behaving correctly now.

**Comment by kotp** [comment]
Thank you @mikewalker .
/close
