### ISSUE TITLE
Merry Christmas!

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4564]
To @exercism/track-maintainers and everyone else that has contributed to Exercism in 2018, I just want to say a huge thank you on behalf of the Exercism team. We've helped tens-of-thousands of people this year on Exercism, that that wouldn't have happened without you. 

I will be taking a break for the next couple of weeks, so responses will be slower than normal. I wish you all a merry Christmas and a happy new year.

**Comment by kotp** [comment]
It's not July yet! lol
