### ISSUE TITLE
Rust / powershell tracks mentoring

### ISSUE THREAD

**Issue by norricorp** [exercism/exercism#4565]
Are these tracks being mentored?
Submitted solution for PS several weeks ago and nothing.
And now with rust, solution is several days old and nothing.
I do realise that being a mentor is a full time unpaid job so very difficult. But exercism did go down this route and it is not always working. If feedback is slow then momentum is lost, interest fades. 
Perhaps it is time to revert to the previous website.
Regards
John

**Comment by NobbZ** [comment]
Rust ist actively mentored but has a long queue according to my knowledge. You'll need to wait. I can't say anything about Powershell.

But please be aware that during the holidays, new year and such much people tend to be with family and therefore have much less time for exercism. Please be exceptionally patient during the next week or two.

**Comment by PatrickMcSweeny** [comment]
@norricorp How would reverting to the previous website help?

**Comment by F3PiX** [comment]
@norricorp I'm sorry to hear that. Just checking: do you know you can go for Independent Mode? You could still ask mentoring on exercises, but you don't need to wait for approval to proceed  through the track.

**Comment by norricorp** [comment]
@PatrickMcSweeny - the old website did not have the mentoring. Students could comment on others work or answer questions on their own work.
@F3PiX - yes, I did know that. I do like the mentoring idea but it has to work. I did some javascript exercises and the mentoring there worked. Comments and approval within a few days so momentum and interest was not lost. But perhaps independent mode is the best way with rust.

**Comment by norricorp** [comment]
is the --all option still available with download?

**Comment by iHiD** [comment]
@norricorp There is no `--all` option in the CLI now. I'm going to close this issue as there's nothing we can do to help here. Independent mode gives you the functionality of the old site, or you can wait for the mentoring functionality on the new site. Good luck! :)
