### ISSUE TITLE
where are the functional specifications

### ISSUE THREAD

**Issue by ttellerx** [exercism/exercism#4568]
I don't understand how to exercises are specified. I can download them OK  However, the only documentation is a README.md file which is just general and does not tell me what the functional definition of the code is for this particular exercise.
I am using c++.
I read that it is cheating to look at the x_test.cpp file however, am I right in assuming that the x_test.cpp file is the only place where you can figure out what methods and classes are to be defined?

**Comment by kytrinyx** [comment]
Thank you @NobbZ. Closing this, as the question has been answered, but @ttellerx if you're still confused please feel free to respond here and we can help you further.
