### ISSUE TITLE
Problem with submitting my solution

### ISSUE THREAD

**Issue by ziggez** [exercism/exercism#4569]
Okay, so i have read through some of the threads but i cant seem to find something useful to help me here. i downloaded the example solution or whatever its called that is listed on the exercise (step 1 download, step 2 create it manually with your own editor, step 3 submit) but when i try to submit it, i type in:
exercism submit C:\Users\alex\Exercism\c\HelloWorld!\Debug\HelloWorld.exe  [C:\Users\alex\Exercism\c\hello-world]
this is where i get stuck, i am supposedly going to submit the file downloaded, but it only comes in source and doesnt leave me an option to submit it as a file. if i only submit the first dir, i get the error that i dont have the metadata. any help whatsoever would be appreciated! =)

**Comment by kytrinyx** [comment]
@ziggez Would you please try the following?

1. Move (rename) `hello-world` directory to something like `backup-hello-world`
1. Download the exercise again `exercism download --track=c --exercise=hello-world`
1. Copy your solution file(s) into the new directory that got created
1. Then run the submit command again, ensuring that you are listing the file path to the solution file(s) relative to where you are on the filesystem.
    So if you have changed directory into `C:\Users\alex\Exercism\c\hello-world` then you would run
    ```
    exercism submit hello-world.c hello-world.h
    ```
    But if you are in `C:\Users\alex\Exercism\c` then you would run
    ```
    exercism submit hello-world\hello-world.c hello-world\hello-world.h
    ```

**Comment by mikewalker** [comment]
`exercism submit hello-world\hello-world.c hello-world\hello-world.h`

Actually for the c track wouldn't that be
`exercism submit hello-world\src\hello-world.c hello-world\src\hello-world.h`

Note the "src" in the path.

**Comment by oribandel** [comment]
Hi, 
Unfortunately, I had the problem as described above - I don't succeed to submit my first exercise. I followed every step as described above (renaming the folder, redownloading, etc.) and still, I get this message: 
The file you are trying to submit cannot be found. 
c:\Users\orib\Exercism\python\hello-world.c 

In the command I had written was: 
exercism submit Exercism\python\hello-world.c hello_world.h 
(in the command prompt, under User\orib\exercism)

I hope you can clarify what do I missing in the process. 
Thanks!

**Comment by NobbZ** [comment]
> c:\Users\orib\Exercism\python\hello-world.c

Are you really sure you are submitting the correct path? I'd not expect `*.c` and `*.h` files to live in the folders for the `python` track, also the folder for the actual exercise is missing.

Perhaps you meant to `exercism submit C:\Users\orib\Exercism\c\hello-world\hello_world.c C:\Users\orib\Exercism\c\hello-world\hello_world.h`?

**Comment by oribandel** [comment]
The path I submitted is the location where the "hello-world" exercise was downloaded to (after executing the "exercism download --track=c --exercise=hello-world" command. 

Herein a printscreen of the  location:
![image](https://user-images.githubusercontent.com/22278667/52729530-083eb900-2fc2-11e9-8108-5552e1a0f0f8.png)

**Comment by NobbZ** [comment]
Your screenshot clearly shows that it's containing python files. It has probably been created by `exercism download --track=python --exercise=hello-world`.

**Comment by oribandel** [comment]
Thanks!
It seems like I getting it wrong. sorry, I'm new to this so I'm trying my best. 
Few things (might help me understand this better): 
1. Shouldn't the Python file be in the folder created by the `exercism download --track=python --exercise=hello-world`   ? if not - where should they be located? 
2. I thought that I should submit the original python exercise file which I added my code on (the code I added is the solution of the exercise), am I right or wrong? If I should submit the solution in another way - please direct me. 

Hope I manage to explain what I'm missing
Thanks

**Comment by NobbZ** [comment]
> 1. Shouldn't the Python file be in the folder created by the `exercism download --track=python --exercise=hello-world`   ? if not - where should they be located?

The python files are **exactly** in the folder that is created by that command, and exactly that is the folder you have shown in the screenshot.

> 2\. I thought that I should submit the original python exercise file which I added my code on (the code I added is the solution of the exercise), am I right or wrong? If I should submit the solution in another way - please direct me.

Yes, you are expected to submit that files, but some comments earlier you try to submit `*.c` and `*.h` files, that are not python files. Python files are `*.py`.

It might help if you actually enable display of fileendings.

**Comment by oribandel** [comment]
Hallelujah!!!!
NobbZ - you are an ANGEL!!! 
Thanks, your assistant was valuable! 
Ths gap was *.py addition the prompt ending, hereinunder:

![image](https://user-images.githubusercontent.com/22278667/52784503-04607480-305e-11e9-87ab-a2de684f99ab.png)
