### ISSUE TITLE
number of unlocked exercises incorrect?

### ISSUE THREAD

**Issue by mikewalker** [exercism/exercism#4570]
I just completed the first two exercises in go. The first exercise "Hello-World" unlocked space-age, and list-ops. The second exercise unlocks leap, triange,and proverb according to the icons under the two core exercises. This comes to a total of 5 side exercises that should be unlocked. 

However if you look at the side exercises there are now 10 exercises unlocked. This doesn't seem to add up.

**Comment by kytrinyx** [comment]
Thanks @mikewalker, that does sound suspicious.

@iHiD When you get back from the holidays would you take a look at this one?

**Comment by NobbZ** [comment]
On a manual scan of the go track config, I found 11 exercises marked `core: false, unlocked_by: null`.

**Comment by F3PiX** [comment]
That seems to be intentional. From the Ruby track, after launch:
"We should have 4 or 5 exercises that are "core": false, "unlocked_by": nil. These are bonus exercises that will be available as soon as you join the track, along with the first core exercise."

**Comment by rpottsoh** [comment]
Csharp and Delphi tracks also have the same thing going on.  A few exercises that are not core and are not unlocked by a core exercise;  bonuses........


Sent from my android device.

**Comment by iHiD** [comment]
This might be fixed by https://github.com/exercism/website/pull/485 - I'll ask you to take a look once I've merged/deployed it.

**Comment by mikewalker** [comment]
I'm not quite sure anymore, I have progressed quite a ways into the go track now. What I can tell you is that the number shown as unlocked by core exercise is a few lower than the actual number of unlocked. So I guess the question now is should those two numbers match? Seems like there are a few bonus exercises that don't need to be unlocked by completing a core exercise.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
