### ISSUE TITLE
Allow student to 'follow' mentor.

### ISSUE THREAD

**Issue by lbsa71** [exercism/exercism#4571]
As a student, I want to be able to choose a set of mentors so that I can create 'rapport' with them over time.

Implementation idea: Being able to 'like' or 'fav' a mentor, meaning that I would prefer that mentor to guide me on the next exercise I submit.

Related:
https://github.com/exercism/exercism/issues/4567

**Comment by iHiD** [comment]
Thanks!

We have this functionality baked in via the ratings dialog (ie, if you rate someone 5* then we presume you like that person. If you rate them 1* we presume you don't etc). We just don't use this in a helpful way in the UI yet. I'm going to close this in favour of #4567 as the two are two sides of the same product feature I think :)
