### ISSUE TITLE
Mentor Rating should be displayed to 2 dp

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/exercism#4573]
My current rating has been hovering around 4.69 but when it reached 4.7 it looked a bit odd.

It would be clearer if shown to 2 dp.

This can be solved with:

.rating #{number_with_precision(@mentor_rating, precision: 2)} / 5 

in show.html.haml

I have not submitted this as a pull request since I can't get the code to run locally and don't want to submit potentially broken code.

**Comment by ConSou** [comment]
Hello, I can get this changed.
