### ISSUE TITLE
Ruby track - core progress blocked

### ISSUE THREAD

**Issue by mikewalker** [exercism/exercism#4574]
The core exercise that is currently waiting for mentoring was originally completed in exercism v1. This was about 10 months ago. At some point the track was also paused, and subsequently unpaused. 

The exercise that is waiting for mentoring did receive some mentoring in v1 so I'm not sure if its even in the mentoring queue for v2 of the site. 

Would it be possible to get this exercise approved so that progress can be unblocked? The id of the exercise is 124d4a21f3d3453a919ba48c9d6aa018.

There are also issues with the side exercises but that is covered under a different issue. https://github.com/exercism/exercism/issues/4563

**Comment by SleeplessByte** [comment]
I'll take this.

**Comment by mikewalker** [comment]
Thanks, core is no longer blocked so this issue can probably be closed now.
