### ISSUE TITLE
Been waiting 2 months for mentor approval in Javascript track.

### ISSUE THREAD

**Issue by eddcoons** [exercism/exercism#4576]
I got some feedback when I first submitted my solution for a core exercise but I haven't had any feedback or approval since resubmitting. I think I resubmitted correctly, but maybe something is wrong on my end. Or is there just a long wait for the JS track? 

Here's the link: https://exercism.io/my/solutions/0211408b48b8423687203cdb3fc84b8c 

Thanks for any help!

**Comment by F3PiX** [comment]
Hi @eddcoons. Sorry to hear that, thanks for sharing! There's someone going to take over shortly.

**Comment by F3PiX** [comment]
@ihid Mentoring is done, this can be closed.

**Comment by eddcoons** [comment]
@F3PiX -- Thanks so much!
