### ISSUE TITLE
JavaScript and TypeScript track issues

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#4577]
As per @iHiD, this is mainly feedback for @F3PiX and @kytrinyx and others working on the general curriculum. For reference, I mentor Ruby, JavaScript, TypeScript and Kotlin and student C#, Elixir, Prolog and Rust.

[From slack (#track-javascript)](https://exercism-team.slack.com/archives/CATCV452S/p1545906120011000?thread_ts=1545407027.008900&cid=CATCV452S), reformatted slightly:

> *tejasbubane [7 days ago]*
Hi @SleeplessByte Can you elaborate a little please? I would like to understand what you feel can be improved.

This is in response to an earlier conversation between me and @iHiD about putting potential restructure of the JavaScript track on the short list and me saying the "current composition is less than great [...] and I don't think it's right, right now".

## Leap

> *Derk-Jan Karrenbeld [19 hours ago]*
> @tejasbubane of course!
>
> I'll make a few posts in order to structure my thoughts:
>
> The first exercise is `leap`. What leap is supposed to teach is currently not defined and is pretty divided between mentors. You can see [here (typescript)](https://github.com/exercism/website-copy/pull/640/files/c0b68f71452c1b63446f851c5bb8a9f3d59f0837#r238226837). It seems that the tendency is to _not_ care about the order if a student is new, but the [Haskell notes](https://github.com/exercism/website-copy/commit/a3a968d2580fdbfe5fa2eb49a932b3c0682ba618#r31525210) do include it, whereas python [leaves it in the middle](https://github.com/exercism/website-copy/pull/562/files).
>
> However, [in the channel](https://exercism-team.slack.com/archives/CASDGG84B/p1543925972011900.) you can see all these different opinions about what should be taught.

This refers to a conversation started by @mrtank, in the csharp track channel. I will quote a bit as shown in the slack preview:

> *Márton Garai [1:19 PM]*
I mentored Leap, when I got the comment, that is not about clean coding, rather it's just a code golf (my suggestions leaded to a concise version, which he/she felt to be just a code golf). I wrote a mini novel about what is that exercise about, but the student reverted it's code to the initial version, and published that one, missing `&&` and `||` and single return statement from his code. What are your oppinion about are we doing code golf, or is it just *that* opinionated? (edited) 

Basically this shows the opinions mentors have about what looks right, what is right, what should be right and most importantly: _what is the point of the exercise_. I point this out:

> The exercise tags don't match the mentor notes, which don't match the mentor execution, which is not something that is agreed upon across languages or as a whole.
>
> The problem here is that exercism is supposed to informally teach you to be fluent in a certain language, and _not_ teach you how to program. Some languages have way more beginners/juniors than others, but that shouldn't change the goal.
>
> If mentors can't even agree on what is important, (this does NOT need to be the same across languages), then the exercise at best is underdefined (instructions/test) or at worse is not a good exercise, because if mentors don't know what is "right", how are students supposed to get it right?

And this here is the crux of the problem. `leap` is an underdefined exercise that is IMO _not_ a good exercise as a core one at ALL! I think `two-fer` is _must_ better as a "non hello-world" exercise and in most languages teaches you about string manipulation / interpolation and / or formatting, as well as default arguments if they exist. It's also agreed upon by most if not all mentors what the idiomatic solution is.

My suggestion for leap follows directly:

> My suggestion here would not having this mathy exercise at all, and/or have each student answer a few simple questions during hello world:
> - experience with programming
> - interested in code style
> - interested in speed optimizations
>
> It should be defined what the goal is of the exercise, because right now, there is "none". Some mentors across multiple languages even feel that if statements are better suited than boolean operators, so that can not be the goal of the exercise, yet it's tagged as such.

## RNA-transcription

> The RNA exercise is fine. It's a nice use-case to teach about maps, and/or replace using a function. Nothing too interesting, but a tad more things to work with here.

> Introduces depending on implementation:
`const`, `Object.create` / `{}`, `String#split`, `Array#join`, `String#replace`, `Regex#test`

This exercise is concise, agreed upon by most if not all mentors, in all languages, how this should be solved and what the alternatives are. Usually teaches students about pattern matching, stream processing and/or object/hash lookups.

## Simple Cipher

> But then comes simple cipher. So first you have leap, an underdefined exercise that is very simple, as well as RNA transcription that is also simple but touches small new subjects (maps/sets/string replacement), and then there is this. An exercise that takes many students exponationally/factorially longer than the other two, combined, is more complex and has a lot more to deal with. It introduces Random, loop iteration, is mathy, string manipulation, charcodes (and strings being sorta like char arrays if we get into optimisation), a lot of more complex modulo arithmetic, and consists of four parts ["boilerplate", "validation", "generation", "transformation"](
https://github.com/exercism/website-copy/pull/605/files), each that could have been its own exercise _at this point in the track_.
> 
> It simply is NOT a good exercise as the third exercise. It's a GREAT exercise to have students show what they have done.

I think this is the MAIN issue with both TS and JS. The exercise is not in the right place. It's too much, and it doesn't work with anything that comes after it. It touches too many subjects at once, which I listed right after:

> It basically touches these functions, depending on implementation, which have NOT been touched before, depending on implementation:
> 
> `String#reduce`, `String#includes` , `String#indexOf`, `String#charAt`, `String#charCodeAt`, `String.fromCharCode`, `Array`, `Array.fill`, `Array.from`, `Regex.test`

And I even forgot to mention the `Math.rand`, the concept of dry-ing up, constructor vs method validation, positive vs negative regex (all are true vs. some are false), and as listed above, charcodes, complex modulo arithmetic, and loops vs streams.

> As well as basically needing someone to *see* that encode and decode are the same, in order to come up with a sane solution, be comfortable with modulo math in order to *know* that you can wrap around any number on the number line, (not just zero), *know* how ASCII codes work (or use a very slow indexOf / includes for each char lookup) and so forth.

And 80% of the time they don't.

## After that

> If the next exercise was another level up, I could understand why it is the way it is, but it's not. Pangram only requires you to test if each letter of the alphabet is present in the string, which can introduce you to:
>
>`String#toLowerCase` / locale version, `String#includes`, `Array#every`
>
> It's só much simpler, goes back to teaching a "single" subject (loops/every). It just doesn't make sense.
>
> The #track-typescript track here is _worse_ as it puts RNA transcription _after_ simple cipher. The #track-ruby has not even unlocked this exercise by the time you reach Isogram, the 10th (*!!!*) exercise in the ruby-track.

I think it's at the right place in the Ruby track. It's at the wrong place in the JS and TS tracks. 

## Conclusion
> *Derk-Jan Karrenbeld [19 hours ago]*
> @tejasbubane so in short:
> - if we look only to the first few exercises, they are underdefined, and not lineair in terms of difficulty.
> - not ordered in terms of difficulty
> - doesn't teach single / small subjects in the beginning
> - does not teach a student how to write idiomatic javascript, in a steady manner.

I hope this is a decent elaboration on what I think is not right :), and I am definitely up for discussions and/or seeing what would be good. On the other hand, my JS PR's to add mentor notes have been open since _21 Nov 2018_. I definitely don't feel motivated to keep writing them since it's just sitting there.

**Comment by kytrinyx** [comment]
> my JS PR's to add mentor notes have been open since _21 Nov 2018_.

Ouch. It sounds like we don't have JS folks looking at those PRs. Let me look into that!

**Comment by tejasbubane** [comment]
Sorry but is there another repo for mentor notes? [ref](https://github.com/exercism?utf8=%E2%9C%93&q=mentor&type=&language=)

I usually keep an eye on https://github.com/exercism/javascript/pulls

**Comment by SleeplessByte** [comment]
@tejasbubane [here](https://github.com/exercism/website-copy/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3ASleeplessByte+). As you can see some have been merged, some have no interaction :)

**Comment by rpottsoh** [comment]
@kytrinyx or @iHiD perhaps there needs to be a general announcement to all mentors on Slack to check out exercism/website-copy for updates to mentor notes for the various tracks they mentor.  I am sensing that there are mentors out there unaware.....

**Comment by kytrinyx** [comment]
@rpottsoh You're probably right. I know we announced this back when we added it, and then again when we started including it in the site, but we probably need a better way to make new mentors aware of it, and make sure that existing mentors didn't miss the discussion when it happened, as there are _LOTS_ of discussions happening, and we're not always reading it all (I'm one of those who mostly _can't_ keep track!).

**Comment by iHiD** [comment]
@SleeplessByte Thanks for all this. Over the next few weeks @F3PiX will follow up with the JS maintainers and you about some of the work she's doing on improving the structure of tracks and how she can help JS.

I will post something on Slack in the next few days reminding people about the mentor notes. @tejasbubane I've invited you to a Slack channel about this.

**Comment by boazblake** [comment]
Hi there seems to be an error in the armstrong exercise. Not sure if I should open a new issue but in the intro the digit 9 should be marked as NOT an Armstrong Number, but also the first test is wrong as 5 is also not an armstrong number.

**Comment by iHiD** [comment]
@boazblake Thanks for reporting. Yes, please open a new issue for this, either here or preferably at https://github.com/exercism/javascript - thanks!

**Comment by iHiD** [comment]
I'm going to close this as this progression is now happening off GitHub with @F3PiX, and @kytrinyx has messaged the JavaScript maintainers.
