### ISSUE TITLE
JavaScript Track is stuck

### ISSUE THREAD

**Issue by Elaniobro** [exercism/exercism#4579]
I recently completed the `rna-transcription` practice, all tests passed. There is no way for me to "publish" my solution. So now I am currently waiting on a mentor? There are no other challenges for me to tackle as the rest are locked. Is this expected behavior?

**Comment by Elaniobro** [comment]
Gotcha, and thank you for your response. 

I thought I was not in mentor mode, as all my solutions up until this one, I could publish. 

How do I switch out of that mode?

**Comment by Smarticles101** [comment]
go to [your javascript track page](https://exercism.io/my/tracks/javascript), scroll about 1/4 of the way down. You're looking for the last box on the right side before you reach the extra exercises. The box is called "Danger zone" and has a button to switch to independent mode.
