### ISSUE TITLE
cannot complete exersie after switching  to independent mode

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [exercism/exercism#4585]
Hello exercism!

I think there is a small bug in the website. I started with scheme mentor mode, and 
then switched to independent mode, and I cannot now finish the Hamming 
exercise in scheme track because it waits a mentor to comment even when I 
am now in independent track. And I cannot look into other people exercises this way.
My account is AlexanderKoshkarov.

Thank you,

Alex.

**Comment by AlexanderKoshkarov** [comment]
I have not noticed the button :) sorry

**Comment by HarrisonMc555** [comment]
I ran into the same issue.
