### ISSUE TITLE
Exercism in 2019

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4588]
2019 is here and we're **really** excited about what we're going to achieve with Exercism. I wanted just to outline a few high level things that are on our radar to give people an idea of what we're focussing on.

There are 4 key high-level objectives we have for this year:
1) Make mentoring as fun and rewarding as possible
2) Improve a learner's journey with improved structure and more/better content.
3) Make a bigger deal of our community and highlighting people's huge contributions
4) Explore how we can expand Exercism (or build something in partnership to it) to reach total beginners

Exercism is about to hit 250,000 members and is growing faster than ever. That means more solutions submitted, which could result in more pressure on mentors, slower response times, and more frustration for learners. We are also still currently *only* growing by word-of-mouth and trying to keep Exercism on the down-low. By the end of this year, we want to be close a point where we *can* shout about what we're doing and be able to cope with the demand. Even a small amount of marketing would realistically result in 50k submissions/day, which means we need excellent systems/people in place to cope. And we want to thrive, not just cope.

Achieving this is going to involve a mixture of clever technology (e.g. automatic analysis of solutions to recommend common improvements), tooling (e.g. mentor notes, cleverer mentor dashboard), content (e.g. articles on different approaches to a solution), expectation-management (e.g. estimated time to mentoring), community management (e.g. giving people a place to help get each other unstuck - forums?) and ensuring that our mentors/maintainers/contribute are energised by Exercism not burned out by it. And this in parallel with dealing with the 300 or so open issues that already exist :)

In order to manage all this, we need to take Exercism from being a website to being an organisation. We need people working on Exercism full-time and need money to spend on things like servers. We have started this process by incorporating Exercism as a non-for-profit company and applying for a handful of grants. We are planning to invest a lot of energy into getting this part really right, being super-transparent to the community, making sure people's voices are clearly heard, and building an organisation that we are really proud us.

One thing that we feel very strongly about is that we want to get there correctly more than we want to get there quickly. Exercism is a large, complex and ambitious project with dozens of repositories, over 3,000 contributors, and a complicated and long-term set of goals. In order to achieve its potential (and for us to not burn out on the way) we need to take the time to make the right decisions and to ensure that we carry everyone with us as we go. I know that sometimes things can feel slow and that seemingly easy solutions aren't implemented quickly but please know that that is not because we don't care, but because we care so much and so want to ensure we get things right.

Over the next few weeks, I'm going to be posting a few more updates about our near-future plans for how we address some of the things I've mentioned about. In the meantime, I just want to thank you for reading this and for being part of Exercism. We are passionate about giving people opportunity through learning and improving their programming skills, and we are so grateful you're here as part of this journey. Thank you! 💙

**Comment by F3PiX** [comment]
Great plan! Exciting.

**Comment by yyyc514** [comment]
It'll be great to see these things as blog posts in the future instead of Github issues. :-)

**Comment by AgonIdrizi** [comment]
Great improvements.
I also want to add that 'Online completion of exercises' is a must have feature(as soon as possible), that will also help reach total begginers.
Cheers.

**Comment by olesia28** [comment]
Your resource is perfect and I am very pleased with your service.  I've already completed tasks from 1 till 7 in C# track and they seemed a bit easy for developer with some experience. Could you say, please, are the following tasks more complicated or this course for beginners? And do you plan add  advanced C# course, I mean tasks like a small project using OOP principles, Dependency Injection, Tasks, Multithreading, etc.

**Comment by iHiD** [comment]
(cc @ErikSchierboom)

**Comment by iHiD** [comment]
@olesia28 I'm closing this issue as it shouldn't still be open, but Erik will reply to your questions about the C# track. Thank you for your kind comments :)

**Comment by ErikSchierboom** [comment]
@olsesia28 The latter exercises will definitely be more involved, so I think you'll find interesting and challenging exercises later in the track.

Our focus is on the language itself, so that excludes dependency injection and such. We'll keep the suggestion in mind though.

**Comment by olesia28** [comment]
> The latter exercises will definitely be more involved
That's great! 

> We'll keep the suggestion in mind though.
Thanks!
