### ISSUE TITLE
404 when i submit a solution

### ISSUE THREAD

**Issue by IlyaKryazhev** [exercism/exercism#4591]
https://exercism.io/my/solutions/608cae7be7714c10be99dc45faaebb19
Please, help me, i do not understand how to fix this problem.
I submit solution and then this error turns out.

**Comment by Smarticles101** [comment]
@IlyaKryazhev what command are you using to submit your solution exactly

**Comment by IlyaKryazhev** [comment]
exercism submit hello-world.js

**Comment by NobbZ** [comment]
@ihid have you checked if that specific I'd belongs to the correct user or if it belongs to a user at all?

**Comment by iHiD** [comment]
@IlyaKryazhev I suspect that you are logged in with a different account to the one that you have configured on the CLI. That post is assigned to `Ilya`, which I presume is you but maybe logged in via email not GitHub?
