### ISSUE TITLE
Deploying Website -- rake tasks

### ISSUE THREAD

**Issue by jwo** [exercism/exercism#4593]
Hiya! I'm playing around with getting an instance of the website up and running. I'm using the docker version, and everything is great!

How do you schedule your rake tasks to run, and on what frequency? I find that I have to run the following frequently, and they don't exit themselves, so I have to control-c them.

* `rails git:sync` :  `Git::SyncUpdatedRepos.run`
* `Git::FetchUpdatedRepos.run`
* `Git::UpdateRepos.()`

Do you have three different processes always running with the git rake tasks? And, is there an order in which they are designed to run? 

Thanks in advance, I've been an exercism fan for many years. ❤️

**Comment by iHiD** [comment]
Hello :) They're long running tasks so not expected to exit and they can run in parallel. I'll need @ccare or @kntsoriano to give you exact details as they've written this section.

**Comment by kntsoriano** [comment]
@jwo Hello! Thanks for reaching out. I've nothing to add as @iHiD has said everything I know about them. You are correct that there are three processes running, and as far as I know, there is no particular order in which they should be ran.

@iHiD I think we should look into using a `Procfile` in order to run these processes easier while developing.

**Comment by jwo** [comment]
Right on. I think I'm good to go with the issue. I'll just enumerate some of the findings from doing a deployment if they help anyone in future.

1. As written, the rake tasks are run with the idea that they are long running and don't stop. This can generally be changed by switching `.run` to `.sync`

Purpose of the tasks:

* `Git::UpdateRepos` - Will run through all repos and schedule a repo-update
* `Git::FetchUpdatedRepos` - Does the job of fetching git repos locally
* `Git::SyncUpdatedRepos`- - Does the job of looking at each local repo and bringing in new exercises into the DB

So, the order in which they need to run, for first time developers, appears to be:

1. Git::UpdateRepos
2. Git::FetchUpdatedRepos
3. Git::SyncUpdatedRepos

One other further finding:
* When deploying, the website code needs to be on the same server as the sidekiq server. This is because the sidekiq server fetches the repos locally, and the website will call `track.head` to get the latest version for exercises. Therefore, if deploying with docker-compose (for example), have them share a volume.
* the `SERVER_IDENTITY` is very important, you should not ignore that :)


Since there's nothing else I'm waiting on, going to close this. But obvs feel free to reopen if you like.
