### ISSUE TITLE
Order of Community Solutions does not encourage interaction

### ISSUE THREAD

**Issue by dougal** [exercism/exercism#4594]
👋 @iHiD

When browsing solutions to an exercise I have just completed, the exercises are [ordered by the number of reactions](https://github.com/exercism/website/blob/master/app/controllers/solutions_controller.rb#L6).

While this ordering makes sense when looking for the best or most interesting solutions, there is no way to see solutions by other users who have recently completed the same exercise. I feel that such an ordering would encourage more interactivity between users, especially on extra exercises where mentoring is not usually available.

![screenshot 2019-01-10 at 21 39 43](https://user-images.githubusercontent.com/1256/50998727-40189380-1520-11e9-97ce-816669f7f872.png)

**Comment by Smarticles101** [comment]
I agree, it would be nice if there was a dropdown of options so we could sort by most reactions, least reactions, oldest, newest, most iterations, etc...

I think most iterations would be particularly valuable as a student could see how another user took their solution and improved on it immensely.

**Comment by dougal** [comment]
> I think most iterations would be particularly valuable as a student could see how another user took their solution and improved on it immensely.

I like this.

**Comment by iHiD** [comment]
Bonjour :)

So there's lots to unpack here. Fundamentally I agree that the current way of visualising solutions sucks quite hard, but I've been reluctant to improve it as we have some big changes coming soon (exemplar solutions, AST-analysed groups, etc).

I think this is probably a duplicate of https://github.com/exercism/exercism/issues/4067 and can be closed as such, but I'd really value any extra thoughts you have on that thread.

**Comment by dougal** [comment]
Agree on duplicate. :)
