### ISSUE TITLE
Exercise I was mentoring has vanished

### ISSUE THREAD

**Issue by paparomeo** [exercism/exercism#4595]
An exercise I was mentoring and which is still appearing in my notifications (I've kept it there and haven't dismissed it), is gone, and I get the 404 page: https://exercism.io/mentor/solutions/0ceaebcafc584c29a5613e9d36b76f44.

I'm keen to understand if the student has deleted their profile or the exercise or something since I don't what to disappoint them.

**Comment by iHiD** [comment]
That solution has been deleted. Either they've quit the site or deleted their solution (or left the track). I have no more information than that, sorry! Thank you for checking though!

**Comment by paparomeo** [comment]
Thanks for checking. I suspected as much. Shall I open new issues for a more informative web page when a solution has been deleted (rather than the generic 404) and also for notifications for that solution to be removed from a mentors notification list?

**Comment by iHiD** [comment]
Yes please. That'd be helpful. Solutions get properly deleted (rather than soft-deleted) so I'm not sure how we'd implement the "this solution is no loner here" page but having a tracking issue is good. And the not-deleting notifications is definitely a bug so yes please to that. Thank you! :)
