### ISSUE TITLE
Dead link in "Useful PHP Resources"

### ISSUE THREAD

**Issue by tunggnu** [exercism/exercism#4596]
Hi, please remove this link [PHP Security Cheatsheet](https://www.owasp.org/index.php/PHP_Security_Cheat_Sheet) from [Useful PHP Resources](https://exercism.io/tracks/php/resources) because OWASP has deleted it.

**Comment by rpottsoh** [comment]
@tunggnu thanks for bring this issue to light.  Would you be willing to open a PR to update the MD file to remove the dead link?  This: https://github.com/exercism/php/blob/master/docs/RESOURCES.md is the file that needs to be corrected.  The @exercism/php maintainers I am sure will appreciate the help.

If you (or whomever) decide to open a PR in the exercism/php repo, please include a blurb in the intital comment that will close this issue when the PR is merged.

**Comment by tunggnu** [comment]
Thank you for guidance. I opened a new issue in PHP repo and created a PR.
