### ISSUE TITLE
Idea: Allow students to signal intent to become mentors

### ISSUE THREAD

**Issue by rpalo** [exercism/exercism#4597]
What if students could flag themselves as prospective mentors for the track that they're working on?

Then, mentors mentoring could give a little bit of priority to submissions by those students.  This has the potential of becoming abused (i.e. everyone marking "wants to mentor this track" and the flags meaning nothing), but I think there are workarounds or limits that could combat that, and honestly, I don't really think there are *that* many people that would abuse it.  It could be something that you can only see if you're *already* a mentor in another language?  Or maybe that doesn't buy us anything in terms of growing active mentor numbers.

It could just be a little flag on their solution that the mentors can see from the backlog list.

**Comment by mikewalker** [comment]
As a student some explanation of the path between student and mentor would be good too.

**Comment by F3PiX** [comment]
@rpalo I had this wild idea of adding an exercise near the end of a track where the exercise would be: mentor a few submissions of an earlier exercise. I don't know how we could design/implement that. And it wouldn't be a substitute for your suggestion. But what do you think about it?

**Comment by rpalo** [comment]
@F3PiX I'm not sure about that.  I think it would help make students more aware of the possibility of becoming a mentor and how it's not actually all that scary, which is a good thing.  

I think that if it was listed as a core -- or even side -- exercise, people's need to unlock achievements and completely complete the track would drive some people who aren't necessarily suited to mentoring to mentor anyways.  

If it was listed on the side somewhere as an additional activity and it didn't get in the way of the students getting 100% completion on a track, then I think it's probably a great idea!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
