### ISSUE TITLE
How to remove student-abandoned submission from pipeline

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4599]
2 months ago a student submitted an incomplete solution asking for help, because the tests where inconsistent with the readme provided. We gave the student the missing pieces of the readmu such that he would be able to continue the exercise. All mentors left the conversations such that the exercise will be in the main queue again and not be tied to any specific moderator.

Sadly the student never reported back.

How can we pop the exercise from the queue without approving it?

**Comment by bitfield** [comment]
Am I right, though, that if you as a mentor abandon a solution, you won't see it in the queue again?

So if it's technically in the queue, but no mentors can see it, is it really in the queue at all? 🤔

**Comment by iHiD** [comment]
Deep.

**Comment by NobbZ** [comment]
Perhaps add a button that enables the mentors to ping the student without making it necessary to claim the exercise? That button also could take the exercise from the queue again, as this clearly states "we are waiting for the student".

**Comment by F3PiX** [comment]
I like @nobbz suggestion! Every once and a while I see a solution that I'd like to give a quick comment without claiming the mentoring.  Like a quick answer to a question.

**Comment by bitfield** [comment]
I'm not sure if this 'drive-by mentoring' idea is such a good one. I think if you're giving advice on a solution, you *are* mentoring the student, so you should stick with the problem until they're done. Which is how it works now, of course.

**Comment by F3PiX** [comment]
I was talking about questions where I would be able to add something helpful and that goes unanswered because I'm _not_ going to mentor it.

**Comment by sshine** [comment]
@NobbZ: Would you still consider this request relevant?

In my experience, the place where student-abandoned submissions go to die is after I've responded and they don't respond back. This works until the point where I hypothetically delete my Exercism account, and the queue gets flooded with thousands of these. (I've seen this happen with the number being dozens.)

Maybe the solution is to eventually mark an unapproved solution as dead independently of it waiting for the student and not being visible to the mentor who last responded, which is how I think is the most satisfying current state these can have right now?

**Comment by NobbZ** [comment]
I have not encountered the issue since then knowingly. So I don't think this is relevant beyond that one time.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
