### ISSUE TITLE
Hamming exercise in Python track - moving from side to core excercise

### ISSUE THREAD

**Issue by zarniak** [exercism/exercism#4600]
Hi,

 on the beginning i would like to thank you for great platform and easy way to learn python.

 i am making progress with help of mentors since mid of 2018. **Meanwhile python track changed - exercise "Hamming" moved from side to core**. i have already submitted it before change of track and it seems to be still submited as side exercise and to gain feedback i have to reqest for it - should i request for mentor feedback to get feedback OR should i simply wait because it is now a core exercise OR should i submit the answer one more time?

Would be grateful for any instruction.

**Comment by zarniak** [comment]
Hi,

 i think issue solve itself in the moment when exercise before "hamming" ("two_fer") has been marked as completed by mentor - now "hamming" is on the right track (core) and submitted solution is waiting for mentor to pick it up.

everything is working just fine!

**Comment by iHiD** [comment]
Thanks for updating us! :)
