### ISSUE TITLE
Copy change - published solutions

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4602]
Page: published solutions
Change: I think the last bullet point here should read "Are there new concepts here that *you* could read more about to develop *your* understanding?" 

<img width="446" alt="screen shot 2019-01-17 at 12 23 27" src="https://user-images.githubusercontent.com/5421823/51346591-deda4e00-1a52-11e9-887a-fde0ecf947c6.png">

**Comment by rpottsoh** [comment]
I like the suggestion.  I also like the word `improve` more than `develop`.  The difference is subtle.

**Comment by rpottsoh** [comment]
I also like `A lot can be learnt...` or `Much can be learnt...` instead of `A huge amount can be learnt...`  I don't say learnt (learned), but I am looking the other way on that one.  :smile:

**Comment by nicolechalmers** [comment]
Nice. I agree with both of those suggestions.

Hmm learnt/ learned - it should probably be **learned** because we stick to US spellings elsewhere on the site. Good spot!

**Comment by iHiD** [comment]
I'll merge a PR with:
-  `A lot can be learned` instead of `A huge amount can be learnt`
- `Are there new concepts here that you could read more about to develop your understanding?` for the last bullet point.

I'll do it when I get chance otherwise :)
