### ISSUE TITLE
Some published solutions have incorrect code

### ISSUE THREAD

**Issue by guygastineau** [exercism/exercism#4603]
Hi all, I couldn't find another issue about this, so please point me to an original issue if this is a duplicate.

Several of my exercises. It seems mostly from the bash track have different code that I didn't write.  Often it is in a different programming language.

I will grab some links and add them to comments below.

**Comment by guygastineau** [comment]
Here is one for the Bob exercise in bash

[Link](https://exercism.io/tracks/bash/exercises/bob/solutions/91848d595e724776ba46b3f0be9ca072)

**Comment by iHiD** [comment]
Erm.... This is super-weird. I'll look into this now.

**Comment by iHiD** [comment]
@guygastineau Have you used Exercism on a shared computer at all?

**Comment by iHiD** [comment]
I see what's broken in the data but not the cause. It's nothing to do with you specifically so ignore my previous comment. Looking into it further.

**Comment by iHiD** [comment]
Got it. https://github.com/exercism/website/pull/506

**Comment by guygastineau** [comment]
@iHiD thank you so much.

I noticed this a few weeks ago, but I figured it was already brought to attention by someone else.  Especially since I hadn't logged in for months.

Now I'm really glad that I made this issue.

Thank you for being an indispensable factor in this community.

**Comment by iHiD** [comment]
Thanks @guygastineau. Means a lot 💙
