### ISSUE TITLE
Inactivity Message Wording

### ISSUE THREAD

**Issue by BethanyG** [exercism/exercism#4604]
![automated_inactivity_message](https://user-images.githubusercontent.com/5923094/51355799-0e964f80-1a6d-11e9-96de-07e3b480a47a.png)

...suggest this read:

> Mentor [_mentor name_]  **has been** removed from this conversation due to inactivity. This solution **has been** resubmitted to the queue for a new mentor to review.

**Comment by BethanyG** [comment]
alternative:  Mentor [mentor name] **is being** removed from this conversation due to inactivity. This solution **has been** resubmitted to the queue for a new mentor to review.

**Comment by iHiD** [comment]
@BethanyG Thanks. Mind reviewing https://github.com/exercism/website/pull/505 please?

**Comment by BethanyG** [comment]
Apologies for the delay!  Reviewed & suggested.  Please let me know if you need anything else.

**Comment by iHiD** [comment]
@sshine Thanks :)

> Remove the quotes around the mentor's name so that it reads more naturally. (Yes, can be abused by mentors picking names like "without a name".)

I considered this but decided that the "abuse" vector meant that quotes were important. I find them a bit ugly too, but I'm ok with it I think.

> Use softer wording wrt removing mentors, since technically a mentor can go in and grab the task again. If they're the first one to pick it up from the queue again, it may have a negative impact that they were "removed".

It won't appear in the queue again for the same mentor FYI. What wording would you suggest?

> Change last part to present tense so that it sounds like something is happening.

I've changed that in the PR (https://github.com/exercism/website/pull/505). Do you think it needs more changes?

**Comment by pgaspar** [comment]
I was about to post an identical issue because I just found this copy issue on the website myself.

<img width="514" alt="screen shot 2019-01-21 at 17 35 52" src="https://user-images.githubusercontent.com/31735/51490540-7e754480-1da3-11e9-999a-37a3f2116385.png">

It's still there for messages sent before the fix on https://github.com/exercism/website/pull/505.

Should we also consider retro-actively updating the existing comments @iHiD? I find it likely that others will notice the typo and eventually create new issues.

**Comment by iHiD** [comment]
Yeah - I can regenerate them when I get a few mins.

**Comment by sshine** [comment]
I'm closing this issue since the only outstanding issue is to update the wording of notifications sent to people prior to exercism/website#505 on Jan 18, 2019. This cannot be considered important any longer.
