### ISSUE TITLE
Community Blog Link targets the wrong page

### ISSUE THREAD

**Issue by bwestover** [exercism/exercism#4614]
Hello, I noticed today that the link to the "Community Blog" in the profile dropdown menu appears to go to the wrong place:
### Screenshot
![image](https://user-images.githubusercontent.com/1987494/51428487-2b3f9e00-1bb9-11e9-816f-c5bda3e1a4e6.png)

### Source
```html
<a href="https://teams.exercism.io">Community Blog</a>
```

I'm guessing that should go to https://exercism.io/blog/ instead.

<h6>P.S. - I :heart: Exercism. Thanks for all you do to make it great. </h6>

**Comment by iHiD** [comment]
Great catch. Thank you!
