### ISSUE TITLE
Submitted solution does not appear in web interface

### ISSUE THREAD

**Issue by joce** [exercism/exercism#4615]
I recently submitted an update to a solution to C# `BankAccount` and the updated solution does not appear in the web interface.
This situation appears to be unique to the `BankAccount` problem as I can update other solutions without issues.
I'm using the following command line to submit:
```
exercism submit bank-account\BankAccount.cs
```
The submission appears successful as I get the following message: 
```
    Your solution has been submitted successfully.
    View it at:


    https://exercism.io/my/solutions/f55e0c628a15473fb44f3e14c2225d3a
```
I've also tried re-downloading the solution 
```
exercism download --exercise=bank-account --track=csharp
```
then re-doing my solution before re-uploading it, to no avail. 😞 

You can find the solution Exercism displays on the web site at the address above.  
The solution I'm trying to submit is the following:
```csharp
using System;
using System.Runtime.CompilerServices;

public class BankAccount
{
    bool m_IsOpen;
    decimal m_Balance;

    [MethodImpl(MethodImplOptions.Synchronized)]
    public void Open()
    {
        m_Balance = 0m;
        m_IsOpen = true;
    }

    [MethodImpl(MethodImplOptions.Synchronized)]
    public void Close()
    {
        m_IsOpen = false;
    }

    public decimal Balance
    {
        [MethodImpl(MethodImplOptions.Synchronized)]
        get
        {
            if (!m_IsOpen)
                throw new InvalidOperationException();
            return m_Balance;
        }
    }

    [MethodImpl(MethodImplOptions.Synchronized)]
    public void UpdateBalance(decimal change)
    {
        if (!m_IsOpen)
            throw new InvalidOperationException();
        m_Balance += change;
    }
}
```
```
> exercism debug

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.11
Latest:  3.0.11


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\joce
Workspace: C:\Users\joce\Exercism
Config:    C:\Users\joce\AppData\Roaming\exercism
API key:   2e1f*****************************774

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 47.0391ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 446.8008ms
```

**Comment by ghibulo** [comment]
I'm reporting the same issue with Dart...
exercism submit lib/leap.dart 
    Your solution has been submitted successfully.
    View it at:   
    https://exercism.io/my/solutions/4ec4d413c5ed45fbacc6a291d78cad85

exercism debug

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.11
Latest:  3.0.11


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/ghibulo
Workspace: /home/ghibulo/exercism2
Config:    /home/ghibulo/.config/exercism
API key:   5996*****************************1a4

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 468.864931ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 1.915383122s

**Comment by maxveldink** [comment]
Seeing the same issue with the Kotlin track; Here is my debug info:

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.11
Latest:  3.0.11


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\Max VelDink
Workspace: C:\Users\Max VelDink\Exercism
Config:    C:\Users\Max VelDink\AppData\Roaming\exercism
API key:   580a*****************************c9f

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 70.7834ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 633.3072ms
```

**Comment by jdsutherland** [comment]
I'm not sure if this is going to relevant to the particular issues folks are having here but what might be related is that the submit cmd currently doesn't do much error handling when printing a success message. I have a PR that addresses this here https://github.com/exercism/cli/pull/793.

It's possible that the submission requests (by the users in this thread) are returning a non successful response but the success message is printed, which is adding further confusion here.

**Comment by mkast** [comment]
Re-submitting worked now for me!
Thanks a lot!

**Comment by sshine** [comment]
@ihid: Is it safe to assume that this is fixed now?
