### ISSUE TITLE
Performance differs between tracks when downloading exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4617]
While working on multiple language tracks, I've found that the time it takes to download an exercise can _greatly_ differ between tracks. At first I thought I was just having "bad luck" or something, maybe an inconsistent speed of my internet connection. However, I've been able to reproduce this over multiple tracks on different machines.

These are some sample timings on my MacBook Pro:

Ruby:

```pre
192:binary-search-tree erikschierboom$ time exercism download --exercise=series --track=ruby

Downloaded to
/Users/erikschierboom/Programming/exercism/exercises/ruby/series

real    0m1.525s
user    0m0.091s
sys     0m0.033s
192:binary-search-tree erikschierboom$ time exercism download --exercise=series --track=ruby

Downloaded to
/Users/erikschierboom/Programming/exercism/exercises/ruby/series

real    0m1.192s
user    0m0.093s
sys     0m0.030s
192:binary-search-tree erikschierboom$ time exercism download --exercise=series --track=ruby

Downloaded to
/Users/erikschierboom/Programming/exercism/exercises/ruby/series

real    0m0.697s
user    0m0.090s
sys     0m0.029s
```

JavaScript:

```
192:binary-search-tree erikschierboom$ time exercism download --exercise=series --track=javascript

Downloaded to
/Users/erikschierboom/Programming/exercism/exercises/javascript/series

real    1m44.025s
user    0m7.938s
sys     0m51.841s
192:binary-search-tree erikschierboom$ time exercism download --exercise=series --track=javascript

Downloaded to
/Users/erikschierboom/Programming/exercism/exercises/javascript/series

real    1m45.144s
user    0m7.845s
sys     0m52.263s
192:binary-search-tree erikschierboom$ time exercism download --exercise=series --track=javascript

Downloaded to
/Users/erikschierboom/Programming/exercism/exercises/javascript/series

real    1m43.712s
user    0m7.870s
sys     0m52.043s
```
As one can see, the difference is huge! I'm not sure if this is actually an issue with the CLI though, it could of course just as well be something with the API being called.

**Comment by jdsutherland** [comment]
In the CLI, the download command makes a request for each individual file as part of a for loop. I wonder if the time difference is due to JavaScript having significantly more files to download?

**Comment by ErikSchierboom** [comment]
> [...] and didn't get values anywhere close to the discrepancies you've reported

This is odd. Having a concurrent download might be useful though it is easy to implement.

**Comment by ErikSchierboom** [comment]
Edit: at the moment, the speed is fantastic again, also for tracks with more files. Maybe it is thus the API that may be slow in some situations?

**Comment by iHiD** [comment]
@kytrinyx Erik and I have been debugging this offline. The API is responding in a few ms, so I don't think the issue is there. Is there any sort of `--debug` switch in the CLI or anything that Erik could use. Or do you have any ideas about how we could debug further?

**Comment by rpottsoh** [comment]
Without knowing what all has been tried offline.  Would it be possible for @ErikSchierboom to use a different computer and/or OS from the same physical location?

**Comment by ErikSchierboom** [comment]
Well, I have tried it on:

- Home Mac OS machine (slow)
- Home Windows computer (slow)
- Work Windows computer (slow)

So it has been tested on two locations with two operating systems.

**Comment by ErikSchierboom** [comment]
And it seems strangely linked to the javascript and typescript tracks, I don't have this issue for any of the other tracks.

**Comment by iHiD** [comment]
Could there be anything on your setup that does something when CDing into a directory with node_modules or anything? I wonder if the CLI is CDing into the Dir and automatically running something as a side-effect.

A parallel is Ruby where if you cd into a dir with `.ruby_version`, your OS switches to use that version of Ruby, which can take a few seconds.

**Comment by rpottsoh** [comment]
I just tried `exercism download --exercise=series --track=javascript` on my old Windows 7 laptop here at work and the first try was about 4 seconds.  A second attempt was roughly 2 seconds.  

I am running the CLI from the default folder that is presented to me when I open CMD.

**Comment by ErikSchierboom** [comment]
Not that I know of, but I can't rule it out of course.

**Comment by rpottsoh** [comment]
Is the symptom the same regardless of running the 64 bit / 32 bit version of the CLI?

**Comment by ErikSchierboom** [comment]
I haven't yet tried, good idea!

**Comment by rpottsoh** [comment]
My work computer can only run the 32 bit version.  My home computer...  is at home.  I run the 64 bit version there.  Sometimes I notice the same task performed on either computer taking longer on the machine running the 64 bit CLI.    I've not given it much thought.

**Comment by jdsutherland** [comment]
You can get debug output with the `-v` flag:
`exercism download -v testercism download --exercise=series--track=javascript`

AFAICT, there's no mechanism in the CLI to account for this discrepancy in performance of javascript and typescript vs other tracks. The download command doesn't have conditional behavior when on downloading from different tracks (e.g. ruby vs javascript).

The verbose output might be useful.

If network issues have been ruled out and the verbose output doesn't help, you might try using `dtruss` (mac) to view syscall info. If any unexpected js-related stuff is happening, the syscall output should show it.

**Comment by rpottsoh** [comment]
Just retried downloading `series` on my home computer...  Got same results as I did earlier on work computer.  
It doesn't like you @ErikSchierboom. 😜

**Comment by jdsutherland** [comment]
@SleeplessByte this seems somewhat plausible. @ErikSchierboom definitely run your benchmarks in as isolated a shell as possible (i.e. don't run in vscode with a bunch of js plugins - use the basic terminal).

**Comment by ErikSchierboom** [comment]
@jdsutherland I had already reset my authentication token :)

**Comment by kytrinyx** [comment]
Do we know if it's the CLI itself or the HTTP requests? (I.e. if you run the requests with curl, are they also slow?).

Do we know if the length of time that it takes is proportional to the number of files that get delivered?

**Comment by iHiD** [comment]
It's not the API. I checked the logs. So it's either CLI or Erik's machine.

**Comment by ErikSchierboom** [comment]
I'm happy to close this issue, as it appears to be very specific to this one exercise. Lately I have not seen any of this type of delay for the other tracks I'm working on.
