### ISSUE TITLE
How are volunteer contributions counted?

### ISSUE THREAD

**Issue by Smarticles101** [exercism/exercism#4618]
Under the team page, if you click on [volunteer contributors](https://exercism.io/team/contributors) you see a list of many people who have contributed to exercism. I'm curious how the website counts a user's contributions, and what counts as a "contribution" from the website's end.

**Comment by sshine** [comment]
These statistics are pulled from GitHub, and they define a contribution [as such](https://github.blog/2013-01-07-introducing-contributions/):
> Whenever you commit to a project’s default branch or the gh-pages branch, open an issue, or propose a Pull Request, we’ll count that as a contribution.
