### ISSUE TITLE
Contrast between fonts

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4619]
### https://exercism.io/blog

> News, interviews and articles from the Exercism community.

Should contrast more with text above

**Comment by iHiD** [comment]
<img width="538" alt="screenshot 2019-01-21 at 16 02 08" src="https://user-images.githubusercontent.com/286476/51504463-fa689000-1d95-11e9-8e29-f3f229a289d5.png">

Looks good on latest MacOSx. Let's close this for now and test it on some other OS/browsers when we have time.

**Comment by sshine** [comment]
I'm closing this issue as I assume you are both satisfied with the color scheme since it hasn't changed with reference to this PR since.
