### ISSUE TITLE
Choosing an exercise in Teams

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4620]
For @iHiD 
<img width="843" alt="screen shot 2019-01-21 at 15 35 10" src="https://user-images.githubusercontent.com/5421823/51503898-a90ad180-1d92-11e9-9982-af1a91614675.png">

**Comment by iHiD** [comment]
@nicolechalmers Can you reproduce this?

**Comment by sshine** [comment]
@nicolechalmers: I'm closing this for now, as I think we might have gotten massive amounts of feedback if choosing a language on Teams was broken. I have verified that it works on my computer using the C track. I have not taken any other parameters into account.

**Comment by iHiD** [comment]
Thanks @sshine.
