### ISSUE TITLE
Comment icon but no comments 

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4621]
For @iHiD 

https://exercism.io/my/tracks/python shows the chat icon on Leap to show I have a comment but when I go to https://exercism.io/my/solutions/b51a04ee7ef845fe92fe6a0e9b826e1e there are no comments

**Comment by sshine** [comment]
@iHiD: This can probably be closed?

**Comment by iHiD** [comment]
It was a long time ago so I'm going to say yes.
