### ISSUE TITLE
Position in Mentoring Queue

### ISSUE THREAD

**Issue by mstange22** [exercism/exercism#4624]
Hello!  First off, I just wanted to say that I'm thankful to have found you guys and I think what you're doing is really great.  I hope to be able to contribute at some point - I'm just not quite there yet.  Also, apologies if this has already been addressed.  I did a quick search and didn't find anything similar.
***
So, I'm currently in 6 different language tracks and I'm sure it comes as no surprise that some tracks receive more attention than others.  I have Go and Python submissions that are currently being reviewed daily, but I have Java and C++ solutions that have not been reviewed in well over a week.

I understand that this is all volunteer-based and I have no expectations that someone is just going to review my code for free immediately, but a bit of clarity would be nice so we can make a decision on how to proceed. 

My thought is that a student would be able to see where their submission is currently sitting in the queue - like "your solution is in position x.  We estimate that your solution will be reviewed in y days."  That number could update as solutions in the queue are processed.

Thanks again for all that you're doing.  I'm really enjoying the tracks!

**Comment by Smarticles101** [comment]
I think that would be a nice addition. Based off the rate submissions have been mentored in, say, the past week, give the student an estimate on how soon they can expect a review

**Comment by mstange22** [comment]
Thanks for the quick response!

**Comment by borispov** [comment]
> @mstange22 
> This does mean that there could be no-one ahead of you, but no-one wants to mentor your solution, so it sits there for a while.

For one solution I got mentored really fast, but that other solution that I really would benefit the mentor's review, I just don't seem to get. Now I understand that maybe it's simply avoided. 

The only choice remains is doing side-track exercises?

**Comment by iHiD** [comment]
It's much more likely to be a long queue than you being avoided :) Which track and which solution uuid (you can get it from the URL)?

**Comment by chokn** [comment]
Or perhaps just showing an average response time by track with an upper and lower range. 

My first 3 solutions in the Java track were all reviewed in less than a day, but perhaps that set up unrealistic expectations, because my fourth solution (c1a6a4c76c7e44ff8bc9b74c03aee858) has been waiting on a review for a week. I was starting to get concerned that my solution fell through the cracks. 

Thank you all for all your hard work. I think this is my new favorite learning platform.

**Comment by wonhyeongseo** [comment]
> @iHiD Mentors can choose which solution they mentor. The UI presents the top 20 solutions and then they choose.

How does the UI generate the top 20 solutions?

**Comment by NobbZ** [comment]
They are grouped by category: core, side, legacy.

Inside of each category they are sorted by age (oldest first).

Then you see the categories after each other. Well, at least if the first displayed category has less than 20 entries.

(This is a simplified version of what really happens)

**Comment by mikedamay** [comment]
https://github.com/exercism/exercism/issues/4624#issuecomment-456509508

> One issue I have with this is that the "queue" is only loosely a queue...

If like me you are trying to decide whether to shift to unmentored mode (haskell track) then knowing that there is little activity in a track would help make up my mind.

**Comment by smeruelo** [comment]
I think this issue can be closed since it's already implemented (https://github.com/exercism/website/pull/650/).

**Comment by iHiD** [comment]
@smeruelo Thanks :)
