### ISSUE TITLE
Insert nav_divider image using CSS rather than HTML

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism#4626]
I noticed that the navigation HTML is littered with image tags that could be inserted using the 'after' pseduo-element. This would clean up the templates and make the generated HTML more semantic.

If it is agreed that this would be the best approach I could on a pull request for this.

**Comment by iHiD** [comment]
@PatrickMcSweeny Thanks. Could you give me an example please?

**Comment by PatrickMcSweeny** [comment]
All of the nav_divider method calls on this and other template pages insert image tags:

https://github.com/exercism/website/blob/master/app/views/solutions/show.html.haml

nav_divider definition here:

https://github.com/exercism/website/blob/master/app/helpers/a11y_helper.rb#L19

**Comment by iHiD** [comment]
If you can find a DRY way to do it then this seems great :)
