### ISSUE TITLE
canceling modal dialog for unpausing leaves site in ambiguous state

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4628]
Let me explain this in better detail.  I paused the Ruby track....  I then tried to unpause the track.  

When I reentered the Ruby track, via the list of tracks, I am presented with a modal dialog inviting me to unpause or cancel...  I decided to cancel.  Upon clicking cancel I am left in the Ruby track.  I am free to navigate the track page as though the track was unpaused.

For example, if I attempt to switch to independent mode from the track page a modal dialog is displayed inviting me to switch to independent mode or to cancel.  If I choose to switch to independent mode the modal dialog for unpausing reappears.  Not the wrong response, maybe.  Should I be allowed to make changes to a paused track?  While still in the track's page the first button in the Danger Zone is a Pause Track button.  If it is OK to be in the track page shouldn't the button become an unpause button?

From what I can tell the site is properly maintaining and detecting the paused / not paused state of a track.  It would be nice if when opting to cancel from the unpause dialog the user was returned to the track list page or if the track's page had an indication on the page that the track you are in is paused and to limit what you are allowed to do.
 
A quick search for any issues that might relate to this one didn't turn anything up.  Please close if this issue is redundant.

**Comment by iHiD** [comment]
Thanks, @rpottsoh. Fixed via https://github.com/exercism/website/pull/521/files

**Comment by rpottsoh** [comment]
@iHiD the new behavior looks good!  Thanks.
