### ISSUE TITLE
x509 error when configuring token

### ISSUE THREAD

**Issue by kamakazi17** [exercism/exercism#4630]
Getting a x509 error. Anyone have any ideas?

$ exercism configure --token=[token] -v

========================= BEGIN DumpRequest =========================
GET /v1/ping HTTP/1.1
Host: api.exercism.io
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (darwin/amd64)

========================= END DumpRequest =========================

Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.

Get https://api.exercism.io/v1/ping: x509: certificate signed by unknown authority

**Comment by NobbZ** [comment]
Make sure your systems root CAs are up to date, I'm not sure how this can be done on macos though...

**Comment by azaslavsky** [comment]
Follow up for others that ran into this on OSX: updating my macOS version (Sierra -> Mojave) solved the issue for me.  Seems like the best way to update Apple certs is to get a new OS version where they're bundled in.
