### ISSUE TITLE
Functional Programming 

### ISSUE THREAD

**Issue by brianboros7** [exercism/exercism#4632]
Hello there,
I was loving your site until I logged out and logged back in and can't find where I was. I was in the C# track, and when I used to go to the Hello World section, previous to getting started I was able easily find the Functional Programming section and OOP. The OOP link was to Microsoft documentation. The function programming was a book from Exercism. I can't find neither now and It really is upsetting. None of the links in the C# learning are to any of this. Why did this happen? Where do I find this now? Something so simple as it was on the C# introduction page that can't be found, or it was on the Hello World C# page and isn't there now. There were many links. Please let me know.

**Comment by brianboros7** [comment]
Also, the page had an Exercism URL and it was like a Book. I was on Chapter one. It was the same website and all.

**Comment by PatrickMcSweeny** [comment]
Is this what you were looking for?

https://livebook.manning.com/#!/book/functional-programming-in-c-sharp/chapter-1

**Comment by brianboros7** [comment]
Yes, let's open one for the "About" page as the perfect reference page.

Brian S. Boros

(C):  219-671-0342

(w): http://briansboros.com/

(e): brian.boros7@gmail.com

<https://www.facebook.com/Brian-S-Boros-923097297803806/>
<https://twitter.com/briansboros>
<https://www.linkedin.com/in/brian-boros-020ba957>
<https://plus.google.com/u/0/%20brianborossocialentrepreneur/>

**Comment by rpottsoh** [comment]
Logout and then you can visit the track page instead of signing back.  You will see the track's about page then.

**Comment by brianboros7** [comment]
Ok, well, that' s still strange I guess. Take Care

Brian S. Boros

(C):  219-671-0342

(w): http://briansboros.com/

(e): brian.boros7@gmail.com

<https://www.facebook.com/Brian-S-Boros-923097297803806/>
<https://twitter.com/briansboros>
<https://www.linkedin.com/in/brian-boros-020ba957>
<https://plus.google.com/u/0/%20brianborossocialentrepreneur/>

**Comment by iHiD** [comment]
The links are on the right hand side of the track page when you're logged in to a track :)

**Comment by PatrickMcSweeny** [comment]
@iHiD Those aren't the same links that are on the "About" page. The functional programming link mentioned in this issue is not listed there.

![screenshot from 2019-01-24 19-48-01](https://user-images.githubusercontent.com/1254212/51718000-28a5d400-2011-11e9-990b-0337df8b0c92.png)

It is also not on the "Resources" page.

**Comment by brianboros7** [comment]
I realize that. But, I was able to get to the Functional Programming and
such from there.... Not the reverse. I'd have to read through now and
figure it out, but I knwo I got there twice. etc. You got the links for me
and I appreciate that.

Brian S. Boros

(C):  219-671-0342

(w): http://briansboros.com/

(e): brian.boros7@gmail.com

<https://www.facebook.com/Brian-S-Boros-923097297803806/>
<https://twitter.com/briansboros>
<https://www.linkedin.com/in/brian-boros-020ba957>
<https://plus.google.com/u/0/%20brianborossocialentrepreneur/>

**Comment by iHiD** [comment]
There are links in the body of the text on the "About the Track" page but these no longer available when you go to the "Hello World" section. The content of the "About this track" page is not intended to be guidance for a student, it's intended to give a flavour for the track. If there is important information that's needed, it should be in one of the seconds on the track link, or it should be in the Hello World README.

(cc @ErikSchierboom)

**Comment by brianboros7** [comment]
Ok, I understand. Thanks!

Brian S. Boros

(C):  219-671-0342

(w): http://briansboros.com/

(e): brian.boros7@gmail.com

<https://www.facebook.com/Brian-S-Boros-923097297803806/>
<https://twitter.com/briansboros>
<https://www.linkedin.com/in/brian-boros-020ba957>
<https://plus.google.com/u/0/%20brianborossocialentrepreneur/>

**Comment by ErikSchierboom** [comment]
@brianboros7 As @iHiD said, if you feel that there is documentation or links missing in the C# track, feel free to open an issue at https://github.com/exercism/csharp.
