### ISSUE TITLE
Add one-click unsubscribes from individual email types

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4634]
We're adding more email types and I want people to be able to unsubscribe from one type immediately, and be able to control their email notifications without needing to log in.

**Comment by NobbZ** [comment]
Please, require at least a password when using such a link, elsewhise anyone who received a forwarded mail could temper with my notification settings.

**Comment by kytrinyx** [comment]
I feel very strongly that unsubscribe should be a single click without requiring a password.

I do like the idea of being able to share a newsletter with someone, but I wouldn't recommend forwarding it. I'd rather we had a link in the email that is to an archived version of the newsletter online.
I'm not sure what the effort would be to implement something like that.

**Comment by kytrinyx** [comment]
I still feel strongly that unsubscribe should be a one-click affair. We can add something to the boilerplate of the email that warns people. I'd much rather we have one-click unsubscribe than have a shareable newsletter.

**Comment by laginha87** [comment]
If a notification email is sent after unsubscribing it would solve the issue of someone unsubscribing your account.

**Comment by iHiD** [comment]
This is now done. @NobbZ There is a setting in your preferences to disable the functionality.
