### ISSUE TITLE
Globally improve Hello World pages

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4635]
A few months ago, I made a [walkthrough video](https://www.youtube.com/watch?v=ixSJXImknnk) for Hello World on Ruby, which is embedded into the hello-world instructions page. It's been watched 2.5k times, so it's obviously got some value to people.

Having reflected, I think the hello-world page generally is too complicated. The page is good for your second/third exercise, but it's no-where near friendly enough for the first exercise you do on Exercism. I want to improve the page (either by changing the content or adding a "first time here" modal) to make it friendlier. It should also point people to exercism/exercism to log issues if they get stuck.

**Comment by BethanyG** [comment]
I know this sounds strange, but what about a pre-"Hello World" exercise for all tracks that's about testing your CLI round-trip? That might also be an opportunity to point potential students in the direction of getting a code editor set up, and learning a little about the command line by linking to some short, friendly tutorials.  Then the next task that unlocks is choosing a language track, and getting started with Hello World?  

And if someone is already good with all of that, they can skip straight to the exercises.

**Comment by iHiD** [comment]
I think that should be the purpose of hello world. Otherwise I don't really
see what the purpose of hello world, especially as most tracks are adopting
two-fer as the next exercise, and hello world already doesn't have
mentoring.  Thoughts?

**Comment by BethanyG** [comment]
Humm.  Good point.  Although, for some languages Hello World is more involved than it is for others.  
I don't have *vast* experience, but with the "newbies" that I've watched use exercism for the first time, the CLI round-trip is the biggest hurdle, and once they get that, they are happy to plug away at the language.  

So I think making that super-clear and friendly with supporting materials (where to start with IDEs, where to learn more about command lines, places like repl.it to go if they don't have easy access to installing stuff on their computer....etc....)

**Comment by iHiD** [comment]
Yep. 100% agree with this. This is exactly why I want to craft this
exercise really carefully to achieve that (and is also part of my
motivation for moving docs out of the individual tracks into one central
place where we can easily cross reference stuff etc).

I think any track where hello world is more involved than basically a
one-liner should have the exercise changed or a comprehensive stub that
means only one line needs inserting.

**Comment by NobbZ** [comment]
> for some languages Hello World is more involved than it is for others.

Can you name them?

Returning a static string is easily possible even in C.

**Comment by BethanyG** [comment]
Java and Go come to mind.  But overall, I agree with @iHiD - "Hello World" could be a good opportunity to test out the CLI round trip, get a student socialized to overall community expectations and norms, and get them some short, friendly links on basic tools they might need or use, with emphasis on how the process works across tracks, and where it might differ.  

Then they can get down to plugging on their chosen tracks....or they can just hop to it if the prelude is old news.

**Comment by rpottsoh** [comment]
Reading this chain of comments has caused me to reflect back on the [discussion](https://github.com/exercism/problem-specifications/issues/520) to make `hello-world` be the defacto first exercise of all tracks and be considered as the most simple exercise with the sole purpose of allowing the student to confirm that their tooling for a given track is setup and working correctly.  The creation of `two-fer` was an offshoot of that discussion, almost two years ago.  Sorry for the quasi off-topic post.

**Comment by NobbZ** [comment]
@BethanyG said:
> Java and Go come to mind.

Neither of them is hard to implement:

```java
public static string hello() { return "Hello, World!"; }
```

```go
func hello() string { return "Hello, World!" }
```

Plus/minus some necessary boilerplate like package declaration or a wrapping class. I do not see anything complicated here.

The only thing that could make this even easier is to return `void`/`unit` or a similar thing that roughly means "nothing", but that would be hard to have a test for that would be able to test if the testing framework and compiler are actually installed correctly.

**Comment by rpottsoh** [comment]
> Returning a static string is easily possible even in C.

I had a student refactor the Delphi `hello-world` in just this manner, no function at all.

**Comment by BethanyG** [comment]
@NobbZ  - _agreed_ - but for someone who's only dealt with the console for JavaScript, or with Python, setting up the infrastructure for Java or Go can be daunting.  Heck - setting up the test infrastructure for any of these tracks can be daunting at first, in addition to the "necessary boilerplate"....it may be that I've encountered _programming_ newbies..and that if I watched someone who was experienced, it would be a non-issue.  Although - it did take me a few rounds to get **Hello World** done on the Go track to the auto-bots satisfaction...

I think it's more a debate about where we expect students to be when they start a particular track.  I think there's an unspoken expectation that a given student is fluent with the command-line and with troubleshooting setup issues and testing for any language that they choose.  And that they will go find and read documentation to get things working.  But that's not always the case - and many learners need a visual or some sort of walk-through to build confidence.  Or very very clear, short steps - even if those steps are:

1)   Do this tutorial about the command line.  
2)  Go here to learn about code editors and how to set one up for your computer and this language
3)  Go here to learn about the test package we use for this language, and how to set that up.
4)  Watch this video for how to download and set up the exercism CLI
5)  Download this test file, type in "hello world", and upload it to exercism 

I don't know that I am being very articulate here, so I apologize.  I think it's a hard balance between being welcoming and encouraging -- but also **not** being a site dedicated to "beginners at programming".

**Comment by kytrinyx** [comment]
> "Hello World" could be a good opportunity to test out the CLI round trip, get a student socialized to overall community expectations and norms, and get them some short, friendly links on basic tools they might need or use, with emphasis on how the process works across tracks, and where it might differ.

This is an excellent point, @BethanyG.

We'll have a bunch of things we can do to smooth the process for folks. Whatever we do, though, we should identify any of our tracks that have a hello-world that is more complex than it should be, and simplify those.  I've opened an issue about this: https://github.com/exercism/exercism/issues/4707.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
