### ISSUE TITLE
Auto-mention teams in website-copy PRs

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4637]
It would be nice if when someone creates a PR to website-copy we could have a bot that auto-commented ccing in the relevant website-copy language team by looking at the directory structure of the file that's changed.

Is this something you could script, @kytrinyx? I guess we'd need to host it, so we should discuss how we want to set that up if so? I could do that framework bit and deploy it with @ccare, then give you a space to insert the script into? I feel like we're going to end up with lots of these bots.

**Comment by F3PiX** [comment]
Or we use a GitHub PR Template? If it's possible to add the team mention dynamically...

**Comment by iHiD** [comment]
> Or we use a GitHub PR Template? If it's possible to add the team mention dynamically...

@F3PiX Yeah. I considered this as a nice short term fix, but figured if we can get it absolutely correct rather than relying on users, it would better :)

> but perhaps waiting for GitHub Actions to come out of beta might be an option for these kind of notification bots

@SaschaMann I know nothing about GitHub Actions, but @kytrinyx will :)

**Comment by kytrinyx** [comment]
Actions would be perfect for this use case. In the meanwhile, how about a cron job that ran every hour on open PRs? I don't feel like writing a whole bot for it, but I wouldn't mind doing a one-off thing like this until Actions are available? It doesn't need to be instant feedback.

**Comment by iHiD** [comment]
Do you have an eta (days/weeks/months/years) on Actions? I don't mind just waiting a month if that's the OOM we're talking about.

**Comment by SleeplessByte** [comment]
Just commenting so I track this. I actively mention tracks myself in PRs and I need to stop doing that once this lands.

**Comment by kytrinyx** [comment]
@iHiD There's currently no ETA for the public launch on Actions. I would say it's farther out than is useful to us.

**Comment by kytrinyx** [comment]
@SleeplessByte You know you can hit "subscribe" for an issue or PR, right? :)

**Comment by SleeplessByte** [comment]
@kytrinyx yep! I wasn't using GH interface and they didn't expose that button as far as I could tell 😅

**Comment by kytrinyx** [comment]
@SleeplessByte That makes so much sense now 😁

**Comment by F3PiX** [comment]
How about this for an interim solution, until the actions go live?
https://github.blog/2017-07-06-introducing-code-owners/ 
Given that we could address a team based on the track name directory

**Comment by kytrinyx** [comment]
Yeah, I think it's worth trying out code owners for this for now.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
