### ISSUE TITLE
Line Height / Formatting Overlap in Exercise Comments

### ISSUE THREAD

**Issue by BethanyG** [exercism/exercism#4640]
The line hight for rendered comments is tight when using the **inline code tag** (`example of in-line code tag`).   This is both in the "view community solutions" page, and the main "mentoring" page.

 In FireFox in particular, the highlighted in-line code overlaps the letter descenders from the line above.   but it's tight for most browsers.  Please see the series of screengrabs below for details.

### Firefox:

<details>
    <summary>
       Linux
    </summary>

![2019-01-27-190132_674x178_scrot](https://user-images.githubusercontent.com/5923094/51807066-02fa1400-2237-11e9-877a-3805739d8698.png)
</details>

<details>
    <summary>
       Mac
    </summary>
<img width=50% alt="example_comments" src="https://user-images.githubusercontent.com/5923094/51807076-2e7cfe80-2237-11e9-8ae8-284008d94c15.png">

![mentor_comment_chrome](https://user-images.githubusercontent.com/5923094/51807130-caa70580-2237-11e9-9ece-d6c43ada0df9.png)
</details>

### Chrome

<details>
    <summary>
       Mac
    </summary>
<img width="631" alt="chrome_comments" src="https://user-images.githubusercontent.com/5923094/51807204-d0e9b180-2238-11e9-8dd5-d08ce103a352.png">
</details>

### Safari

<details>
    <summary>
       Mac
    </summary>
<img width="577" alt="safari_comments" src="https://user-images.githubusercontent.com/5923094/51807197-be6f7800-2238-11e9-9987-bd8454a633fc.png">
</details>

### MS Edge

<details>
    <summary>
       Win 10.1
    </summary>

<img width="636" alt="edge_comments" src="https://user-images.githubusercontent.com/5923094/51807210-e7900880-2238-11e9-9d95-d53cf9a32772.png">

</details>

**Comment by PatrickMcSweeny** [comment]
It looks like this is happening not just with the inline code blocks. The descenders of other letters are being cut off as well.

**Comment by PatrickMcSweeny** [comment]
Actually I think the non-inline code descenders just have really poor visibility which makes it look like they are being cut off. This is not something you want in a font that is easily readable.
