### ISSUE TITLE
Speech Bubbles Signifying Comments Don't Render in the Edge Browser

### ISSUE THREAD

**Issue by BethanyG** [exercism/exercism#4641]
Please see the screengrabs below for more detail.  They are of the same exercise, one viewed in **Chrome on a Mac**, one in **Edge on MS Win 10.1**.  The little speech bubbles that are above the iterations to show discussion/comment don't appear to render on Edge.

<details>
    <summary>
        Luhn Comment Bubbles on Mac/Chrome
    </summary>
<img width="1282" alt="Chrome_luhn_comments_bubbles" src="https://user-images.githubusercontent.com/5923094/51807436-8584d280-223b-11e9-83e6-c879f0efad47.png">

</details>

<details>
    <summary>
        Luhn Comment Bubbles on Win10/Edge
    </summary>

<img width="1282" alt="edge_luhn_comments_bubbles" src="https://user-images.githubusercontent.com/5923094/51807442-9f261a00-223b-11e9-96a3-cd1ad2619aa8.png">

</details>

**Comment by iHiD** [comment]
Ooooh. That's not good! Could you try the same Win10 machine with Chrome pls?

**Comment by iHiD** [comment]
And could someone else confirm this on a different machine please?

**Comment by rpottsoh** [comment]
Here is what I see with Edge on win 10.
![image](https://user-images.githubusercontent.com/6978003/51952130-4904d280-2405-11e9-912e-20f9e5700ea1.png)

**Comment by iHiD** [comment]
@rpottsoh Helpful. Thanks.
@BethanyG I think this **might** be specific to your machine. Two ideas that spring to mind to try and debug/confirm this:
- Do you have an adblocker or anything running on Edge. 
- Do you have Font Awesome installed as a local font?

@ErikSchierboom As someone I know uses Windows sometimes, what do you see?

**Comment by BethanyG** [comment]
@iHiD  - Yup.  Closed as "not relevant".  I was using an older version of Edge (which is the first thing I should have checked - **I am sorry about that!)**.  Its supposed to update in sync with Win 10, but there's something going on where it isn't.  Sigh.

**Comment by iHiD** [comment]
No probs!
