### ISSUE TITLE
Allow comments modal not rendering buttons properly

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism#4642]
Browser: Latest Firefox `64.0.2 (64-bit)` on OSX Mojave `10.14.1`

![screenshot 2019-01-28 at 3 31 23 pm](https://user-images.githubusercontent.com/980783/51828539-ca7b3880-2311-11e9-9752-db3250e5d27e.png)

**Comment by iHiD** [comment]
Thanks @tejasbubane. Fixed by https://github.com/exercism/website/pull/548
