### ISSUE TITLE
Updated exercise blurb not appearing on site

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4644]
PR exercism/problem-specifications#1449 updated the blurb of Gigasecond in metadata.yml 2 days ago.  I am not seeing the blurb changed on the site.  A blurb is displayed beneath the each exercise while in mentored mode, they are not displayed while in independent mode (I am not sure why that is..).

**Comment by rpottsoh** [comment]
Update:  The blurb for gigasecond has updated.  It took a little longer to appear on the site than others usually.  

Closing this issue since there doesn't appear to be anything to worry about.  👍

**Comment by iHiD** [comment]
Interesting. I wonder if we actually listen for updates to problem specifications, or if that just updates when I deploy. I'll check.

**Comment by iHiD** [comment]
Hmmm. Seems like it should work! As you say, let's leave this as an anomaly and if it happens again.
