### ISSUE TITLE
Add "Edit on Github" link to Mentor notes to allow easily submitting simple PRs via the web in minutes/seconds

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#4647]
I’ve seen a few open source projects do this with great success in getting people to contribute quick fixes they otherwise would never be bothered to do. @iHiD

**Comment by F3PiX** [comment]
It's already there :-))

**Comment by yyyc514** [comment]
<img width="835" alt="screen shot 2019-01-30 at 12 11 47 pm" src="https://user-images.githubusercontent.com/6473/51999087-020bf100-2488-11e9-83f4-a35668ffd7ef.png">

Nope.   

---

Yes, now that I looked VERY carefully I found it at the very, very bottom.  But some notes are quite long... why should I have to scroll all the way to the bottom, and do we want to encourage contributions or not?  I've been doing this months and never even knew the feature existed.  It should be moved to the top in the header so it's obvious.  Right now (if you're only skimming quickly) it just looks like part of the notes, it's not obvious that it's a specific link to a specific exercise.

If we have any type of metrics... move it to the top and I wouldn't be surprised if usage doubled.

**Comment by yyyc514** [comment]
VS
<img width="835" alt="screen shot 2019-01-30 at 12 11 47 pm" src="https://user-images.githubusercontent.com/6473/51999430-c291d480-2488-11e9-8465-b268d59910f0.png">

Still a little subdued, but I only spent a minute on it.

**Comment by yyyc514** [comment]
VS 
<img width="854" alt="screen shot 2019-01-30 at 12 17 18 pm" src="https://user-images.githubusercontent.com/6473/51999457-d3424a80-2488-11e9-8242-b1ce4605c969.png">

Still a little subdued but I only spent a second on it.

**Comment by BethanyG** [comment]
I have a further twist:  for Python, there aren't many mentor notes at all.  I'd love to add some (and am in the process of doing so), but if there aren't notes already...there is no link.  ;-)

**Comment by iHiD** [comment]
@yyyc514 We'll work something out to improve this :)

> I have a further twist: for Python, there aren't many mentor notes at all. I'd love to add some (and am in the process of doing so), but if there aren't notes already...there is no link...that I can see. ;-)

@BethanyG For seasoned mentor-note-writers, having a button here would be a great idea. For people that don't know how to structure notes (or worst, don't know about mentor notes fullstop) a button could be quite confusing/overwhelming. Our plan was to link people to a page that talks about what mentor notes are and how to add then. Part of my thinking atm is to monitor better people's activity on GitHub so we can have contextual actions in the site based on whether someone has previously done things like edit notes. It might be that we can have a contextual issue template or something in the GitHub repo to allow. So in short, this is definitely something we want to do, but I'd like to think it thought a little more before we commit to a method.

@kytrinyx Do you have any wisdom about how we could best utilize GitHub to make this clear and easy for someone? (I'm thinking specifically that dropping someone into a new `mentoring.md` in the right directory structure is good, but that we somehow need some surrounding info). I also wonder if for new mentor notes, we'd be better making the modal inline on Exercism and just pushing a PR via GitHub's API.

**Comment by kytrinyx** [comment]
> Do you have any wisdom

Ooof. This is not my strong suit, unfortunately. I think the biggest thing that I've struggled with since the dawn of Exercism is how much context and where that context needs to live to be helpful, etc.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
