### ISSUE TITLE
ActiveRecord::RecordNotUnique in my/user_tracks#create

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4652]
## Error in Exercism V2

**ActiveRecord::RecordNotUnique** in **my/user_tracks#create**
Mysql2::Error: Duplicate entry '16-261309' for key 'index_user_tracks_on_track_id_and_user_id': INSERT INTO `user_tracks` (`user_id`, `track_id`, `created_at`, `updated_at`) VALUES (261309, 16, '2019-02-01 00:02:31', '2019-02-01 00:02:31')

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5c538c976bec9a0019222359?event_id=5c538c97003560194a520000&i=gh&m=ci)

## Stacktrace

    app/services/join_track.rb:9 - call
    app/controllers/my/user_tracks_controller.rb:11 - create

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5c538c976bec9a0019222359?event_id=5c538c97003560194a520000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ActiveRecord::RecordNotUnique** in **my/user_tracks#create**](https://app.bugsnag.com/exercism/exercism-v2/errors/5c538c976bec9a0019222359?event_id=5c538c97003560194a520000&i=gh&m=fx)

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveRecord::RecordNotUnique** in **my/user_tracks#create**](https://app.bugsnag.com/exercism/exercism-v2/errors/5c538c976bec9a0019222359?event_id=5c7fdf6b0036b930d9710000&i=gh&m=ra)

**Comment by victorbrender** [comment]
All the Bugsnag urls return 404. Is this issue still relevant and if yes, could we update the external urls?

**Comment by iHiD** [comment]
Hello. No, this isn't still relevant, and we won't have external urls as they contain sensitive data. Thank you though :)
