### ISSUE TITLE
Allow students to indicate desire to be unassigned from a mentor for a given task

### ISSUE THREAD

**Issue by nathanchere** [exercism/exercism#4653]
This would solve a few problems.

1) Mentors who start looking at a task but then either don't have the time/effort/attention to finish writing their feedback and don't come back for days (or weeks, or ever...) leaving a task in limbo.

2) Mentors who are overly opinionated and narrow minded in their reviews. I've personally had this experience more than once where someone refuses to approve my solution simply because it's not *their* particular approach (e.g. because I didn't think their suggestion to collapse logic into a single regex was in any way beneficial, and they would not approve the solution until it was entirely solved *their* way).

How I would picture it is you have an option (near `Solve (Unapproved)`) to request another mentor. I'm not sure how to prevent it from being overused yet - maybe if it is only available after a mentor has assigned a solution to themselves and `x` time period (e.g. 24 hours) has passed without any comment. I know we already have auto-unassignment after 7 days but that's still a long time to be left waiting for any kind of response or knowing what is happening. Either way, when you select `Request a different mentor`, you also have an option to indicate why - 

* Mentor has been unresponsive (also provide a notice that mentoring is voluntary and can take time, be patient etc)
* Mentor has been hostile (e.g. dogmatic attitude, spiteful feedback etc)
* Mentor doesn't seem helpful (e.g. doesn't really know what they are doing, communication problems)
* I just feel more comfortable with someone else reviewing

If we aren't going to do anything meaningful with the mentor ratings, this could also offer another metric for tracking mentor performance. For example if someone has a significant number of "mentor has been hostile" feedbacks, this would be a lot more insightful than someone getting 1 star ratings which could be anything from the student wasn't getting enough feedback to felt like they were getting too much feedback about something they don't care about and just want to move to the next excercise.

**Comment by sshine** [comment]
This relates to #4674, #4757, #4758. These may be used to eventually address the negative experience described, if not through a "request new mentor" feature as repeatedly described, then in some deeper way. For now I'm linking these issues together so they will all be rediscovered together.

**Comment by jhass** [comment]
I think this is a good idea, a more friendly framing/phrasing for this could be "request a second (mentor) opinion" and it doesn't have to exclude the original mentor from the conversation. It can be their learning experience too after all.

**Comment by iHiD** [comment]
This will be changing for v3 so that students can leave the conversation at any time.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
