### ISSUE TITLE
More indication of what each side exercise is about (perhaps by showing blurb?)

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism#4655]
Let's say I'm a student trying to decide which side exercise to tackle next!

Currently on a page like https://exercism.io/my/tracks/c , I do get to see the blurbs (one-liners, whatever you want to call them) of the core exercises! So I get to know that "Difference of Squares" is "Find the difference between the square of the sum and the sum of the squares of the first N natural numbers.", great! I first would like to posit that that sentence gave me a lot more information about what the exercise would be about than "Difference of Squares".

The blurb was provided by https://github.com/exercism/problem-specifications/blob/master/exercises/difference-of-squares/metadata.yml#L2 .

I sadly do not get the same capability for side exercises, since I only get the name and topics. So I'd have to visit each exercise in question to decide whether it is something I want to do.

In case you wonder, I don't actually care about seeing this issue implemented since there are few enough exercises that I can map from name to exercise content easily, but I cannot guarantee that every person in this position will have the same capability.

I can see this being important if the name is not going to be content-focused, as in https://github.com/exercism/problem-specifications/issues/1451 's proposal to rename retree to satellite.

**Comment by iHiD** [comment]
I don't have an immediate solution but I definitely agree with the point.

**Comment by PatrickMcSweeny** [comment]
Maybe it we could have it so that the blurb of each exercise would become visible in a popup if you hover/focus on the name of the side exercise.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
