### ISSUE TITLE
Solution not being reviewed

### ISSUE THREAD

**Issue by zenicu** [exercism/exercism#4659]
Greetings!

I have an issue regarding my submitted solution on the Javascript track.

It has been over 4 days since I posted it and yet no mentor has given it any attention, and I just wanted to inquire as to what are the regular times between submitting and reviewing, because there may also be an issue because I downloaded this exercise when the old website system was up and running ( I saw that they call it Legacy somewhere ?) but I resolved the problem within the new system and by the new standards. 

I would appreciate if some light would be shed on this matter.

**Comment by F3PiX** [comment]
Hi! JavaScript is a very popular language, and the waiting time tend to be longer. 
But to investigate if something went wrong: can you post a link to your solution please?

**Comment by zenicu** [comment]
Certainly, if the waiting time is the thing, I am sorry, I just wanted to clarify it.
The link is over here: https://exercism.io/my/solutions/433eba85f85a4972bbd898b5c6ce656a
Thank you for your time.

**Comment by PatrickMcSweeny** [comment]
There is no 'regular' time. It varies depending on a lot of factors. Waiting several days can happen sometimes, and other times solutions might get reviewed the same day.

**Comment by SleeplessByte** [comment]
Hi there! The current queue is about 8 days.

**Comment by pavelshackih** [comment]
Hi! Same with my solution https://exercism.io/my/solutions/f8d1c0bb7f4e4e8c98f875d34e510dec :(

**Comment by niilz** [comment]
Do you know by any chance what is the approximate queue on the RUST track?

**Comment by zenicu** [comment]
As @SleeplessByte  stated, the queue is a little higher, around a little above a week, as Javascript is a really popular track.  We can enjoy the side exercises in the meanwhile. Nevertheless, the mentors are doing an awesome job.

**Comment by SleeplessByte** [comment]
@niilz I think it's between 1 and 4 weeks unfortunately! If you've been waiting over 2 weeks, can you post your url? I'll try to forward it to one of the Rust mentors :)

**Comment by niilz** [comment]
@SleeplessByte  Thank you very much for the info. I have not waited for two weeks yet. So no worries.
