### ISSUE TITLE
strange path in the solution

### ISSUE THREAD

**Issue by elyashiv** [exercism/exercism#4675]
I don't know if the student did something funny, or if this is a bug:

![strange_path](https://user-images.githubusercontent.com/1577529/52465762-80534c00-2b88-11e9-832a-679e0e829d0f.png)

Solution id: bf2cc9e48c4c43d4a8f33bb863ce0b6f

**Comment by NobbZ** [comment]
This is a known and fixed bug. Ask them to update the CLI.
