### ISSUE TITLE
Suggestion: Provide cleaned/sanitized database from production for work on performance/query tuning issues

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#4682]
For complex query tuning and large optimizations I find it super helpful to have a representative dataset locally (when system sizes permit such things).  An alternative is having actual access to production and logs and performance monitoring, but I assume that'd be a much harder thing to get.

In the past I've accomplished this my having a backup server (part of the "production" cluster) take a full backup the DB, import it, sanitize it (remove personal/identifiable) data, run some sort of sanity checks, and then make that available for developers to use for development purposes (instead of working with an "empty" system).

Is there some chance we could get such a periodic dump of the Exercism DB?  Could we decide which data is personal/identifiable and discuss this possibility?

I've only glanced at the schema... but assuming the actual solutions are all on the filesystem... it seems the biggest source of personal data would be the "users" table.  Then of course there is the idea that even if you dropped the whole table you'd still be able to discern things about real users by comparing their production IDs (if you mentor them, say) and then reviewing the local data you have... but that's just going to give you metrics style data (how many solutions submitted, iterations, etc)...

Could we have a discussion about the possibility of something like this?

Related: https://github.com/exercism/exercism/issues/4680

If I had the ability to dig into this myself I might, but I'd first start with running the actual query and then EXPLAINING it, etc... all things which are really hard to do without an actual dataset to work with.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
