### ISSUE TITLE
Completed task still unapproved

### ISSUE THREAD

**Issue by sevine** [exercism/exercism#4683]
2 days ago I had complete the task, but it still not approved. How much time I should wait this? What about promized 15 minutes for checking tasks?

**Comment by NobbZ** [comment]
You can only complete after approval, so I'm not sure what your issue is. Also I've never seen some 15 minutes promise anywhere, could you elaborate on this?

**Comment by sevine** [comment]
So how long to wait approval? It some non comfortable to wait so long term

**Comment by rpottsoh** [comment]
Which track are you working in?  Some tracks have a very long queue of student submissions to work through.  I recommend patience and if there are side exercises available that you haven't worked on, try those out in the mean time.

**Comment by sevine** [comment]
I have got approve. 
P.S. it was C# and "Two Fer" exercise
