### ISSUE TITLE
Anonymise mentor/solutions/xx links

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4686]
- [ ] To protect privacy when solutions are shared between mentors, change these links so people who aren't the student or active mentor can't see who is contributing. 
- [ ] Allow any mentor to see any other solution irrespective of the tracks they mentor.

**Comment by pgaspar** [comment]
Love this idea! I'm always weary of sharing solution URLs in public places such as Github for privacy reasons :+1: And being able to see solutions from other tracks is very useful as well!

**Comment by iHiD** [comment]
Great! I don't know why I didn't think of it earlier! :)
