### ISSUE TITLE
Code snippets rendered differently between logged in and not logged in

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4690]
Ballerina is my guinea pig.  The code snippet here: https://exercism.io/tracks/ballerina looks fine, the text is crisp and easy to read.  However, the code snippet for Ballerina displayed here: https://exercism.io/my/tracks/ballerina is illegible.  The issue also exists for Crystal so I presume this issues applies to all tracks.

Please close this issue if it is redundant.

**Comment by sshine** [comment]
I'm sorry, I cannot tell the difference. They are equivalent on my screen. Could you perhaps explain by showing screenshots? The code snippet on the Ballerina track in particular is however oversized and invokes scrollbars so I cannot fully see it:
![ballerina](https://user-images.githubusercontent.com/50879/66167731-48c77180-e63b-11e9-9d83-17fc475520a7.png)

Ping @exercism/ballerina.

**Comment by iHiD** [comment]
@rpottsoh Is this related to whether one is in "dark mode" or "normal mode"? Does the problem still exist? (@kntsoriano has done some work on fixing a related problem to that elsewhere, so if it is the same area, it might now be fixed)

**Comment by PatrickMcSweeny** [comment]
I opened a pull request for this a while ago.

**Comment by Stigjb** [comment]
I can confirm this on Firefox on Mac OS.

/tracks/ballerina (in incognito window)
![bilde](https://user-images.githubusercontent.com/418181/66895359-df5c4100-eff2-11e9-83fb-3bd1da0f239c.png)

/my/tracks/ballerina
![bilde](https://user-images.githubusercontent.com/418181/66895379-edaa5d00-eff2-11e9-9476-4cf31b846cb2.png)

Firefox 69.0.2
Mac OS Catalina
