### ISSUE TITLE
Redacted user details when initially viewing solution

### ISSUE THREAD

**Issue by pgaspar** [exercism/exercism#4692]
@iHiD Now that https://github.com/exercism/website/pull/569 was merged, whenever I click on a new solution from my mentoring queue I'm not able to see the user's name and avatar until I click "Review this solution".

<img width="373" alt="screen shot 2019-02-12 at 02 32 21" src="https://user-images.githubusercontent.com/31735/52607698-15975e80-2e6f-11e9-93f3-75242b1eda28.png">

I'm not sure that was intended, but I suspect it wasn't.

**Comment by iHiD** [comment]
It wasnt. I'll fix it
