### ISSUE TITLE
Allow exercise update without submission

### ISSUE THREAD

**Issue by cmccandless** [exercism/exercism#4694]
From https://github.com/exercism/cli/issues/802#issuecomment-462392209

> > Then when you submit, it always just works and you **must** press the update button on the site and download again in order to update.

> I just had a use case where apparently I had downloaded the exercise before, never submitted and deleted the exercise directory (TBH, I have no idea why I cleared the directory, thus removing any local evidence of a previous download :man_shrugging:). When I redownloaded, the test suite was out-of-date, but the update button does not appear on the site until a submission has been made.

> It would be nice if that button were visible without submission.

TL;DR: when an exercise test suite has changed since last download, the user can click a button to update and redownload. This button is currently not visible unless the user has already submitted a solution. This issue suggests making that button visible whether a submission has been made or not.

**Comment by rpottsoh** [comment]
I just stumbled on this issue myself and was in the process of opening an issue when GitHub kindly pointed out (reminding me) that this issue already existed.  😃

**Comment by mpizenberg** [comment]
This was puzzling me today as I wanted to check that a track update was effective on exercism. I didn't understand why some exercises were using the updated track and some the old. I didn't remember that I had already downloaded the "old" exercises previously.
