### ISSUE TITLE
Feature request: paid priority mentorship

### ISSUE THREAD

**Issue by cayblood** [exercism/exercism#4697]
Hey @kytrinyx and team! Just want to say how much I enjoy using exercism to learn unfamiliar languages or to brush up on rusty tools in my toolbelt. I have been stuck in various tracks for lack of a mentor response, and while I can go ahead and do the tracks in solo mode, I actually enjoy the insights of experienced mentors. I would be happy to pay a subscription fee that could be used to help incentivize mentors to respond to my submissions more quickly. Another potential model could be the ability for a user to attach a bounty to individual exercises that would be paid to the mentor upon achieving a successful well-crafted submission.

**Comment by Smarticles101** [comment]
Related to #4304 

As hesitant as I am to agree with this, it could help solve the long wait time some tracks have.

Bringing in paid subscription, if we pay the mentors for feedback, could raise problems.
* Mentors doing it just for money, feedback quality might decrease
* Spam mentors joining for money who don't actually know what they're talking about

And what about the members who don't have the subscription? Their feedback time would go down as mentors would prefer paid solutions.

**Comment by iHiD** [comment]
@cayblood Thanks for the idea, and it's great to know that you value the mentoring enough to pay for it! :) 

We're actively not going to prioritise people who have money over people who don't have money so we won't be allowing people to purchase any type of premium subscription. I feel similarly about the bounty idea as it effectively jumps the solution to the top of the queue, even if only more implicitly. 

I believe the key is to make improvements across the whole stack/process which means there are enough mentors to keep up with demand. We think that our [Automated Mentoring Support Project](https://exercism.io/blog/automated-mentoring-support-project) and our [Track Anatomy Project](https://exercism.io/blog/track-anatomy-project) will both play big parts in solving this, along with things like [The Mentor/learner Relationship Project](https://github.com/exercism/exercism/issues/4658) and [keeping mentors more engaged](https://github.com/exercism/exercism/issues/4688). I hope that within the next few months, this just is no longer a problem for us. Our mentor-signup rate means we can **easily** cope with the amount of submissions, if only we can keep our mentors engaged (which we currently don't do well enough).

**Comment by vermiculus** [comment]
> if we pay the mentors for feedback…

> We're actively not going to prioritise people who have money over people who don't have money so we won't be allowing people to purchase any type of premium subscription.

Just to add a data point, I appreciate this. If money ever got involved, it would trigger moonlighting clauses in my employment contract and I would have to stop mentoring ☹️ I suspect the same would be true for a decent portion of other mentors.

**Comment by cayblood** [comment]
@vermiculus Thanks for this perspective. However, it seems like this feature could be implemented in such a way that mentors could avoid working on paid submissions.

**Comment by iHiD** [comment]
I think if other mentors were getting paid for mentoring, that would have the same effect. 

I'm going to close this as it's not something we're going to do, but thanks again for the suggestion :)
