### ISSUE TITLE
RSS feed does not encode HTML properly

### ISSUE THREAD

**Issue by yyyc514** [exercism/exercism#4698]
<img width="737" alt="screen shot 2019-02-13 at 11 22 36 am" src="https://user-images.githubusercontent.com/6473/52726567-6d25ef00-2f81-11e9-8ceb-9211a0f1e499.png">

I think HTML is being escaped when it should be RAW so feed readers can render it.

**Comment by iHiD** [comment]
@yyyc514 Thanks. How can I easily test this? I don't use RSS.

**Comment by sshine** [comment]
@yyyc514, @iHiD: Is this fixed?

**Comment by yyyc514** [comment]
![Screen Shot 2019-10-01 at 4 52 16 AM](https://user-images.githubusercontent.com/6473/65947933-42e94a80-e407-11e9-861a-b63078d23ab1.png)

Yes. So very very beautiful.

**Comment by sshine** [comment]
Hooray!
