### ISSUE TITLE
Potential bug: Notifications after leaving exercise

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#4700]
As per https://github.com/exercism/website-copy/pull/675#discussion_r256523282, last week I left a comment on a solution, and pressed "leave conversation". In the subsequent days I did receive notifications whenever the student _or_ mentor did something notification-worthy.

The notifications have now stopped, but my assumption is that it's approved and finished.

Unfortunately I mentored 140 solutions and I can't find it, but I only left *2* since the "leave" functionality was added, so hopefully @iHiD can query this.

**Comment by sshine** [comment]
Related: #4722

**Comment by iHiD** [comment]
I believe I fixed this bug, so I'm going to close this.
