### ISSUE TITLE
Able to complete locked exercise

### ISSUE THREAD

**Issue by ssjrnath** [exercism/exercism#4701]
I have a scenario where I am able to complete the `locked side exercise`, but only one.
I expect it is the next exercise that will unlock after the mentor approval of the core exercise.

Is it expected behaviour or is it a bug?

**Comment by rpottsoh** [comment]
Which track?

It could be possible the maintainer(s) updated the `config.json` for that track.  It defines which tracks are core and which are sides.  It also controls the ordering and which core exercises unlock which side exercises.

If this scenario describes what you are seeing then I expect everything will sort itself out as you proceed through the track.

It could be something altogether different in which case just disregard what I have said.  :smile:

**Comment by ssjrnath** [comment]
@rpottsoh  it is in `Rust` track.

I guess the completion of the core exercise will unlock the side exercise.
If I am not wrong the mentor also won't update the `config.json` until the core exercise completes.

**Comment by guygastineau** [comment]
He means the `config.json` that lives in the track repo.  It is managed by the maintainers.

That file for the Rust track is [here](https://github.com/exercism/rust/blob/master/config.json).
So, nobody will modify this file based on a student's completion of an exercise.

I think that @rpottsoh meant to say that the maintainers could have changed which core exercise unlocks the side exercise in question.  If you want to check the file, then you could see if the exercise is still unlocked by the same one, or you could verify that it has changed.

Anyway, good luck.

Guy

**Comment by sshine** [comment]
I'm closing this issue as it appears that @ssjrnath is not stuck.

Yes, this sounds like a database artifact from having rearranged the ordering.

Typically this requires @iHiD to run a script that potentially fixes database entries.
