### ISSUE TITLE
no response after submission

### ISSUE THREAD

**Issue by ederies** [exercism/exercism#4703]
I submitted an exercise and I have not received response in 24 hours.

**Comment by Smarticles101** [comment]
Which track? Some tracks have longer mentor wait times then others. Mentoring is done all by volunteers, and improving the mentoring process is being worked on so we can increase mentor involvement.

**Comment by ederies** [comment]
Hi there, it's Python.

**Comment by Smarticles101** [comment]
Looks like the python queue currently has 839 solutions waiting for review, the oldest of which are 8 days old. I'd suggest working on side exercises or maybe other languages while you wait. I personally find that the  go track has a turn around time of around a day.
