### ISSUE TITLE
Blank images for new exercises

### ISSUE THREAD

**Issue by Smarticles101** [exercism/exercism#4708]
I noticed that newer exercises on the website don't have images. 

Maybe we should assign some default icon to new exercises, or require a icon made before they're added to the site?

<img width="430" alt="screen shot 2019-02-15 at 3 03 25 pm" src="https://user-images.githubusercontent.com/11557291/52884206-f9c3df00-3132-11e9-8d88-1cbcc6e315f9.png">
<img width="1157" alt="screen shot 2019-02-15 at 3 03 11 pm" src="https://user-images.githubusercontent.com/11557291/52884209-ffb9c000-3132-11e9-8b04-d401aa1158ab.png">

**Comment by F3PiX** [comment]
Yeah, that looks weird. Possible duplicate of https://github.com/exercism/exercism/issues/4460

**Comment by Smarticles101** [comment]
closing in favor of #4460
