### ISSUE TITLE
What needs to be done to rename a language track?

### ISSUE THREAD

**Issue by samWson** [exercism/exercism#4710]
Hi team,

I'm trying to get more advice on this problem and this seems like the best place. We at the [exercism/pharo](https://github.com/exercism/pharo) team want to rename our language track from `pharo` to `pharo-smalltalk`.

Pharo 7 has recently been released and we are targeting it for future development. Due to the unique way of programming Smalltalk, `pharo` is effectively a reserved word and the name of our repository conflicts with it. This causes problems for us.

Renaming the language track will mean we won't have to do awkward work arounds and hacks to get our code running.

What do we need to do to change the name of our language track in the exercism ecosystem? Our repository name and other internal usage will be simple enough. I imagine the CLI tool will need a change? What else would there be?

We are keeping track of the issue [here](https://github.com/exercism/pharo/issues/121). Let me know if there are any questions.

**Comment by iHiD** [comment]
1. On the website side, it's really simple. I can do it for you on-demand.
2. On GitHub, we just need to rename the repos and update and copy anywhere
3. The tricky bit is what happens to people's local solutions - their existing solutions are fine (as they're encoded by their ids) but they'll end up with two directories in their filesystem, one for `pharo` and one for `pharo-smalltalk`. I can't see a way around that, and I don't think it hugely matters, but that's the only real thing that I think will break.

I would suggesting doing (2) then pinging me to do (3) when you're done. 

@kytrinyx What haven't I thought of?

**Comment by samWson** [comment]
@iHiD our language track is still in development so step 3 should impact very few people at the moment. I'll get on to step 2 and get back to you.

**Comment by samWson** [comment]
@iHiD We're ready to change the name but I can't access the repositories settings so I can't change it. I don't know if it is the same with the other maintainers. Would this have been an assigned permission when the repo was created? Looking at our teams page it dosen't look like I can change these permissions. Is this something you can help with?

**Comment by kytrinyx** [comment]
I've renamed the repo.

**Comment by samWson** [comment]
Thanks @kytrinyx. @iHiD if you can handle step 1 for us now, that would be great. I don't think step 3 is a problem for us as we don't make use of the filesystem. Instead all exercise solutions stay inside the Pharo image. In any case it is only our maintainers who will be affected at the moment.

**Comment by iHiD** [comment]
I'll do this tomorrow. I need to walk it through carefully to avoid us ending up with two tracks :)

**Comment by iHiD** [comment]
This is done now.
