### ISSUE TITLE
Custom download command on website

### ISSUE THREAD

**Issue by bencoman** [exercism/exercism#4711]
Pharo's strongly coupled IDE is one of its major attractions and we are using it to interact via the Exercism API to download/submit rather than the exercism command line client.  I'd like to customize the website's sidebar instructions shown on each exercise page, changing it from...
```
1. Download: 
    exercism download --exercise=acronym --track=pharo    
2. Solve: 
    Use your code editor to solve the problem locally.
3. Submit: 
    exercism submit /path/to/file [/path/to/file2 ...]     
```
to something like this which would suit our REPL ...
```
1. Download: 
    Exercism new track: 'pharo' ; exercise: 'acronym' ; download ; browse    
2. Solve: 
    Use your code editor to solve the problem locally.
3. Submit: 
    Exercism new class: YourClass1; class: YourClass2; submit   
```

Relevant code appears to be...
https://github.com/exercism/website/blob/fc53174a40/app/models/exercise.rb#L32-L40

I presume this could go in our config.json file?  https://github.com/exercism/pharo/blob/79ed89ee/config.json

Can someone suggest a parameter name (e.g. custom_command) that might be used like this...
```
  def download_command(team: nil)
    cmd = "exercism download --exercise=#{slug} --track=#{track.slug}"
    cmd += " --team=#{team.slug}" if team
    .... cmd = custom_command.download  if  custom_command.download ....
    cmd
  end

  def submit_command
       cmd = "exercism submit /path/to/file [/path/to/file2 ...]"
    .... cmd = custom_command.submit  if  custom_command.submit ....
       cmd
  end
```

Any concerns with such an arrangement?

**Comment by iHiD** [comment]
Nice idea. I need to think about this properly but I have a very jetlagged week coming up..If you've not heard back from me by the end of the week, ping me and I'll get back to you.

**Comment by bencoman** [comment]
@iHiD > If you've not heard back from me by the end of the week, ping me and I'll get back to you
Ping!   :^)

**Comment by bencoman** [comment]
ping :)

**Comment by iHiD** [comment]
Hello :) Sorry. I still need to find time to think about this. It's lower on my priority list than lots of things though, and my day-job is busy enough atm that my priority list is already slow, so I'll have to ask for your continued patience. But please keep pinging me :)

**Comment by bencoman** [comment]
No problem. I'll check back in a few weeks.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
