### ISSUE TITLE
Next exercise closed in independent mode 

### ISSUE THREAD

**Issue by BolkeDeBeer** [exercism/exercism#4712]
I can't move on to exercise Leap (in Swift) after the terminal said I had successfully submitted the earlier two exercises.

Incidentally: I started in mentored mode, but after I guess a week my code still wasn't looked at, so I went to independent.

**Comment by iHiD** [comment]
@BolkeDeBeer I'm closing this as it's been a long time now. Please comment and reopen if it's still a problem. Sorry that you didn't receive an answer at the time.
