### ISSUE TITLE
Why nobody comes to mentor me in php & JS ?

### ISSUE THREAD

**Issue by cleargoal** [exercism/exercism#4716]
Hi everybody,
are here mentors missed in areas PHP & JS?
Or, what reason are you need to mentoring somebody like me?
What can I do, to invite mentor to review my exercise solution?

**Comment by iHiD** [comment]
Hello. There's just a bit of a wait for those tracks.

**Comment by cleargoal** [comment]
Thanks for your response!

**Comment by iHiD** [comment]
No probs. Thanks for your patience :)

**Comment by iHiD** [comment]
If you paste a solution id for each track, I'll ping the mentors to take a look :)

**Comment by cleargoal** [comment]
Cool! You are very kind

https://exercism.io/my/solutions/2c479bd9082e401086e6dd3de9dd1225
https://exercism.io/my/solutions/2f3122d6864c44938f99cfd775e649bb#discussion-post-285452
https://exercism.io/my/solutions/fe4cc1391e954f68a2ef3fca426947b2#discussion-post-285656

**Comment by cleargoal** [comment]
Javascript mentor came to my track!
Thank you!

**Comment by iHiD** [comment]
Great :)
