### ISSUE TITLE
Error: not in workspace

### ISSUE THREAD

**Issue by slickepinne** [exercism/exercism#4717]
Hej there, 

I know I'm not the first one with this issue. But I think I tried all of the other solutions. :) Still got that error. Obviously, I'm on a mac. :) 

![screen shot 2019-02-20 at 16 47 20](https://user-images.githubusercontent.com/19774772/53104208-3d518b00-352f-11e9-8184-a58c721e182a.png)

I also tried to move the file to the workspace directory but when doing so, I get the following error:

```
The file you are trying to submit cannot be found.

        /Users/slickepinne/projects/exercism/Exercism/ruby/high-scores/high_scores.rb
```

Thanks a lot!

**Comment by NobbZ** [comment]
You need to cd into `Projects`, not `projects`, the CLI is case sensitive
even if your local filesystem might not.

Am Mi., 20. Feb. 2019, 16:51 hat Svenja Schäfer <notifications@github.com>
geschrieben:

**Comment by slickepinne** [comment]
Thank you so much! I did check the capital E but not my projects folder. :)
