### ISSUE TITLE
Make it easier to import completed Personal Edition exercises into Teams Edition

### ISSUE THREAD

**Issue by Moeser** [exercism/exercism#4718]
There's no easy way to import an already completed exercise from Personal Edition mode into Teams Edition.  To do this, I end up having to download the same exercise in Teams Edition via the client, copy the completed solution from the Personal Edition directory, then re-submit it in the Teams Edition directory.  If I don't have the Personal Edition solution available anymore, I first have to re-download the Personal Edition solution before I can copy it over.  The process quickly gets tedious if I want to import a lot of completed exercises to a team.

Two suggestions that could make this better:
* Add a `--team=<teamname>` option to the `exercism submit` command that will submit the solution to the `<teamname>` in Teams Edition instead of Personal Edition.  This could also be useful for importing a completed solution from one team to another.
* Add an area in Teams Edition UI where we can select individual exercises from this same language track that we've already completed in Personal Edition (or another team), to be imported into a target team. (This would be extra useful if the computer where the Personal Edition exercises were completed is no longer available, saving the extra step of having to re-download all solutions we want to import.)

Optionally, in both cases, it might be a good idea to automatically add a comment indicating that this solution was imported from Personal Edition, with a link to the Personal Edition solution so any mentor feedback and comments can be viewed.

**Comment by Eddie-Hartman** [comment]
Please consider this for V3.

**Comment by iHiD** [comment]
Teams is going away at v3 launch and then being totally rebuilt afterwards, so we'll consider it for this.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by Eddie-Hartman** [comment]
@iHiD @ErikSchierboom 
Not sure if this should remain closed or be re-opened so it could be considered for inclusion in v3 teams launch.

**Comment by iHiD** [comment]
@Eddie-Hartman I'll leave it closed as we'll be thinking through this demarkation as a core part of how we design the product. But thanks for the prompt 🙂
