### ISSUE TITLE
Deeply frustrated with wait time for mentor

### ISSUE THREAD

**Issue by frankhale** [exercism/exercism#4719]
I'm doing the Elixir track and finished the 2nd exercise (Bob) 4 days ago and am still waiting. It would be super helpful if we could just do as many exercises as we wanted and then have them all be sitting later for mentor review. The only way for me to move on and even see the 3rd exercise currently is if I approve without mentor which defeats the entire idea of why I am doing the track.

**Comment by iHiD** [comment]
You could alternatively switch to independent mode, where you don't have to wait for a mentor at all. The link is on the right-hand side. I don't know the elixir track, but are there side exercises you could be doing while you wait?

**Comment by frankhale** [comment]
Sorry to vent my frustration here. I may just go ahead and do the independent mode. Thank you!
