### ISSUE TITLE
Core or not core in the "exercises to mentor" list?

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4721]
In the exercises to mentor view, I can see a list of core-exercises.

It shows "Hamming" as a core (which corresponds to the config, and has been since 8 months at least).

It does contain a single submission, a couple of hours old, which is not marked as core though.

![core-or-not-core](https://user-images.githubusercontent.com/58951/53233900-b3b8cf00-368e-11e9-924f-7c0b5ccd3e71.png)

**Comment by iHiD** [comment]
Yeah - we need to change the labels to be clearer. I imagine it's independent mode which is why it doesn't show as core (because there's no core/side in independent mode).

**Comment by BethanyG** [comment]
Was going to log an issue centered on color coding these, but got distracted with mentor notes.  One thought:
![queue_sample](https://user-images.githubusercontent.com/5923094/53987274-63e9f700-40d5-11e9-87eb-a3b2c01dcc66.png)

**Comment by iHiD** [comment]
Yeah. Something like that will work.

**Comment by NobbZ** [comment]
I do think that prior to the dashboard redesign legacy and independent exercises were marked as such. I've not seen any legacy since then, but can you confirm if it will still be recognizable as such?

**Comment by iHiD** [comment]
This is done now as per @BethanyG's suggestion. Legacy exercises are no long considered as such in the UI.
