### ISSUE TITLE
Something weird in the Ruby queue 

### ISSUE THREAD

**Issue by F3PiX** [exercism/exercism#4725]
There are solutions in the mentor queue that are already under mentorin, 'waiting for them'.

1) We discussed this one on Slack: 0a5ff6272efa4b4cbddc71fc820fef06

The mentor confirmed that it was still in their own mentoring list. So it doesn't look like the mentor accidentally left 
2) b5192ccba59e4d82b34f1f6456600176 Same thing: already in mentoring, showing up in Mentor Queue. (Same mentor.)

I did a quick scan of the Ruby track, and it looks like it's only these two.

For reference: Slack discussion: https://exercism-team.slack.com/archives/CAQP7JL3T/p1550852427030300?thread_ts=1550843358.022500&cid=CAQP7JL3T
And this solution was the OP that instigated the Slack thread: 5c4dcc839efd4aa586479f23f295afae

Mysterious....

**Comment by sshine** [comment]
@iHiD, @F3PiX: Was this eventually resolved?

**Comment by iHiD** [comment]
I don't remember tbh, but it will be too long ago for me to debug now.

**Comment by kotp** [comment]
And it will come back if it wasn't.  The nature of things.
