### ISSUE TITLE
GitHub authentication fails

### ISSUE THREAD

**Issue by lauraBaakman** [exercism/exercism#4729]
I tried to sign up using a GitHub account, after giving permission to use my GitHub account I got an error message: 

> Sorry, we could not authenticate you from GitHub

I did receive an email from GitHub.com that A third-party OAuth Application was added.

**Comment by iHiD** [comment]
Hello. There's an FAQ for this [here](https://exercism.io/faqs) (you'll need to search that page for GitHub)

**Comment by lauraBaakman** [comment]
Thank you! That solved my issue. 

Might I suggest adding a link to the FAQ in the error message. I'd be willing to make the PR, but that wouldn't be in line with your contributing guideline ;-).

**Comment by iHiD** [comment]
Thank you for reading the guidelines! :)

I am happy for you to do it if you don't mind, but I'm also happy to add it if you prefer, as I know my way around the codebase. Your shout :)

**Comment by lauraBaakman** [comment]
Please do it for me. I gave it a try, but I slightly overestimated how easy that would be with my limited knowledge. 

I'd be interested to see your solution, if you wouldn't mind linking the commit.

**Comment by iHiD** [comment]
I will await you giving a :+1: to https://github.com/exercism/website/pull/585 :)
