### ISSUE TITLE
Side exercises unlocked without completing any core exercises

### ISSUE THREAD

**Issue by dalDevelo** [exercism/exercism#4730]
On the JS track, I've noticed that 10 of the side exercises appear to be unlocked without having competed the first core exercise. I have downloaded the hello world exercise, but it has not been submitted. I assume this is a bug?

I'm not sure if this is relevant, but I have completed core exercises on a different track, so I'm not sure if this has somehow unlocked some of the side exercises in a different track. I'm also not sure if this is related to #4570, hence why I've opened separate issue.

**Comment by iHiD** [comment]
Thanks. It's not a bug, it's a design-choice of the maintainers. The JS track is actually currently undergoing a rethink in terms of structure so I'll CC the team doing that into this to think about :)

(cc @exercism/javascript)

**Comment by SleeplessByte** [comment]
Hi! If you look here: https://github.com/exercism/javascript/pull/590 you'll find that we have a whole list of "bonus exercises" not unlocked by anything. This is to be expected.

We are currently in round 2 of the curriculum change -- assigning the bonus exercises is something past round 3.
