### ISSUE TITLE
Mentor mode is hard to read code as it cuts of solutions silently

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4735]
I was suprised that mentor mode displays code in a 50/50 split (vertically) and has no border or scroll bars on that code so its easy to miss code that gets cut off (see photo).

While students shouldn't have long lines of code, its true that most laptops favour horizontal space over vertical, and in the mentor screen its very exagerated as you are seeing half the space that the student had when writing the code.

At the very least put borders and scroll bars, but why not move the commenting aspect below the code (so split horizontally instead of vertically). OR have a movable split pane (I think there are js libraries for that these days). OR have a copy button to let me easily copy the code into an editor (a hack but would help a bit).

A
![image](https://user-images.githubusercontent.com/5553623/53728989-e7a0ab00-3e6b-11e9-85da-57bcd5394f10.png)

**Comment by macta** [comment]
> put borders and scroll bars is the easy fix

**Comment by PatrickMcSweeny** [comment]
Have you tried enabling dark theme mode? That would help with the borders issue you are describing.

I think it's important to keep in mind that this is one opinion as for what would make a better UI, and it would be better to phrase these as suggestions. I personally like to use the up and down arrows on my keyboard to scroll up and down on pages, and internal scroll bars would interfere with this.

I agree that a button to quickly copy the contents of the code box would be a useful feature.

**Comment by jonhoo** [comment]
FWIW, I've found this to get a decent amount better with these custom style rules (I used [Stylus](https://duckduckgo.com/?q=stylus+browser+extension&t=ffab&ia=web), but whatever floats your boat):
```css
.lo-container { max-width: none; }
body .md-editor textarea { height: 50vh; }
```
The right-hand side panel still ends up pretty wide though.

**Comment by rpottsoh** [comment]
> Have you tried enabling dark theme mode?

This is how I role.  Is easier on my eyes and the colors pop more against a black background.  Also code snippets I input into my comments follow the dark theme as well, a bonus IMO.

Having the ability to expand and contract the tabbed window, like in V1 would be nice.  Also, not to pour fuel on the flame, the ability to compare two submissions was a nice capability of V1.  Sometimes a students change(s) can be subtle and difficult to quickly/easily spot.

**Comment by macta** [comment]
@jonhoo thanks for the tip - I installed the chrome plugin Stylus and added the following code overrides (with all the defaults) - this gives a great horizontal split:
```
.lo-container {
    max-width: 1600px; }
.panels > .lhs {
    width: 100%; } 
.panels > .rhs {
    width: 100%; }
```

**Comment by Sir4ur0n** [comment]
@macta That's perfect! Can't this be the default? Or at the very least, an option in the settings?

Thank you for sharing this!

**Comment by iHiD** [comment]
> Can't this be the default? Or at the very least, an option in the settings?

It'll eventually be an option in the settings, which is why this issue is still open :)

**Comment by cowlike** [comment]
I'm not sure if I should create a separate issue or if this is where my comment belongs but... the above problem is present *everywhere* that code is displayed. Whether you're looking at the test suite, a personal solution, solutions on the team site, whatever. They all use that non-resizable text display for the code and it is a pretty bad user experience. 

You mentioned that 
> it'll eventually be an option in the settings

Do you mean that there will be a setting that will give you a resize splitter or something? Shouldn't that simply be the default everywhere you are showing this kind of control with scroll bars. I would hate for this to get "fixed" on some particular view but not anywhere else. Viewing code is an essential feature on this site.

**Comment by iHiD** [comment]
We will give a single option in settings for code to be left/right split or full-width for all places where it occurs in the site.

**Comment by sshine** [comment]
@iHiD: It sounds like you have prioritized this, but that the tags don't imply this yet.

Could you apply either "status/on-roadmap", "status/in-progress" or "status/fixed"?

**Comment by iHiD** [comment]
This is done. Setting at the bottom of [preferences](https://exercism.io/my/settings/preferences/edit).
