### ISSUE TITLE
Swift Submission Permission Denied

### ISSUE THREAD

**Issue by Oajamal2** [exercism/exercism#4738]
I downloaded Exercism today and was attempting to complete the Hello World submission for Swift. I tried to submit the assignment using Terminal and when I directed it to the file, the terminal returned permission denied. 
<img width="680" alt="screen shot 2019-03-04 at 4 51 51 pm" src="https://user-images.githubusercontent.com/48226582/53768230-d40e3800-3e9d-11e9-9830-58ff9f314316.png">

**Comment by kytrinyx** [comment]
Hello @Oajamal2.

You need to submit the file with the `exercism` program. Here you are telling the terminal to execute the file `Exercism/swift/hello-world/Tests/HelloWorldTests/HelloWorldTests.swift`.

The submit command is:

```
exercism submit Exercism/swift/hello-world/Tests/HelloWorldTests/HelloWorldTests.swift
```

**Comment by NobbZ** [comment]
Also, wenn usually do not want to submit the tests, but only the implementation.

**Comment by Oajamal2** [comment]
Thank you both @kytrinyx and @NobbZ! I appreciate your help and was able to complete my first submission.
