### ISSUE TITLE
Student having trouble uploading solution and tests

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/exercism#4739]
Here is the link:

https://exercism.io/mentor/solutions/4dbdd1c5947e4e0e874507c06d6cf512?iteration_idx=6

**Comment by NobbZ** [comment]
There was at least one iteration that included both, tests and code, could you elaborate on what the actual problem is?

**Comment by sshine** [comment]
I'm closing this issue because time has passed without a response.
