### ISSUE TITLE
Make docker image available

### ISSUE THREAD

**Issue by augnustin** [exercism/exercism#4740]
As far as I'm concerned, I sandbox all of my work using Docker. This would be nice if there were a Docker image pre-installed with exercism, or even better, with dependencies installed for the selected track.

Then commands would be available using `docker run XXX` but that's still quite simple.

**Comment by NobbZ** [comment]
Similar requests have been made in the past.

Accepting this would put a lot of work to the maintainers of a track to keep those image-descriptions up to date.

Also it would require maintainers to learn docker additionally to all those tools they already have to learn.

It might be a lot easier for those students that want to use docker, to just create a container on their own, matching their docker-workflow.

**Comment by sshine** [comment]
Many tracks may already have Docker images deployed for CI, so the distance is perhaps not so big.

But I also would not expect track maintainers to gather around this effort considering that very few students will request this functionality.

**Comment by NobbZ** [comment]
I haven't seen a single one, though things might change now with the shift from travis to GitHub Actions.

**Comment by iHiD** [comment]
Docker images are not something Exercism is going to maintain for the foreseable future, but if individual people want to then they can. For example [this](https://github.com/unused/exercism-docker) is unofficially maintained as a fork of the exercism website.

As we're having in-browser coding, I think this makes this even less important, as by the point someone wants to definitely use the env, learning how to install it is actually valuable.

So I vote to close this as wontfix.

**Comment by vitebo** [comment]
I did something similar to use the exercism CLI in [this repository](https://github.com/vitebo/exercism)
for each language i end up creating a dockerfile just changing the volume on run

**Comment by iHiD** [comment]
Thanks @vitebo. 

Closing this now as per my previous comment.
