### ISSUE TITLE
Document how track reorderings affect student's progression

### ISSUE THREAD

**Issue by emcoding** [exercism/exercism#4742]
Reorderings of core exercises in tracks causes changes in the student's progression and the mentor queue that are hard to understand for maintainers and mentors. 

Let's document the different scenario's and their behaviour. 
   
The behaviour seems to depend on the kind of change:
1) _Adding or changing_ core exercises affects the next unlock for students in the track. And the mentoring queue. Students will have 2 or more unlocked core exercises: the one that was in mentoring before the change, and the newly added core exercise(s). 
2) _Removing or demoting core exercises_ affects students who has that exercise queued for mentoring. 

Resulting in a few different scenario's:
- the new core exercise is now _earlier_ than the last exercise the student completed: e.g. New Core on position nr 3, student has submitted nr 7. Does the student need to complete _both_ exercises to proceed to nr 8? 
- new core exercise is _after_ the last exercise the student completed: Are we sure that this does not make the new core available for submitting?
- I can confirm that a mentored and completed core exercise that moves up to a position later in the track doesn't affect these orderings.   
- the new core used to be side:   Does the student need to complete _both_ exercises to proceed? What happens if the student already requested mentoring on the same exercise when it was a side (but not completed yet)? And what if it _was_ completed?
- a core exercise is demoted to side, while the student has a submission waiting for mentoring. Will it be removed from its (high) position in the mentor queue? How will the student be aware that a new core exercise is unlocked? (-> They may not come back to the site if there's no mentoring notification on the former core.) 

I'm not even sure if the different scenario's have different behaviours in the first place. 🙃

**Comment by guygastineau** [comment]
Good questions.  I recently noticed this happened to me in ruby.  It let me have matrix, acronym, and series open at once, and I submitted matrix and acronym at the same time.  I received mentoring simultaneously.

Series was populated with a legacy solution of mine, but it appears to be submitted and awaiting mentor feedback.  Strangely, high-scores is still locked even though I was past it (it is the prerequisite for matrix, so this makes no sense to me).

Even more alarming: when I read #rubytrack's [config.json](https://github.com/guygastineau/ruby/blob/master/config.json) It says that robot-name should be a core exercise, but mine is chilling with a completed status in the side exercises, and it has not been moved to core.  I completed robot name when side exercises still had to be mentored, and I got approval/completed with the button and published it.

I know my comments weren't that organized, but hopefully this info from my account will be helpful in piecing together answers.

Thanks for asking good questions @F3PiX 

Guy Gastineau

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
