### ISSUE TITLE
Legacy comments in legacy solution are out of order

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4743]
On the old site I had a lot of nice and long term discussions around some exercises. I did not necessarily find them in V2, but it did not matter, as the discussions were a thing of the past.

But today I went through my legacy submissions and already filed related bugs, now I see another one.

The legacy comments that were made in V1 are displayed out of order and their order does not make any sense.

https://exercism.io/my/solutions/d937ef6f3c45400d96187667d8aa3fe9?iteration_idx=2

The order of comments seems to be consistent though.

**Comment by PatrickMcSweeny** [comment]
FYI, that solution is marked as private.

**Comment by NobbZ** [comment]
Well, no. Its my personal link, not a mentoring link, and I pasted it as is out of lazyness. I could have put simply the UUID and the iteration number. Website admins and developers will be able to extract the data they need to look into the bug.

As this also only affects comments displayed on the "mentoring" I can't even provide a public link, since mentoring happens in private and is not public at all.

**Comment by NobbZ** [comment]
I just realise, this seems to be a dupe of #4078

**Comment by sshine** [comment]
Let's close this one, then. Since they're linked by reference, any additional details in this issue are available.

**Comment by NobbZ** [comment]
I actually wanted to close it... Seems as if I had clicked the wrong button...
