### ISSUE TITLE
Support general mentor guidelines for each track

### ISSUE THREAD

**Issue by cmccandless** [exercism/exercism#4745]
from @jeffdparker (slack)
> There are a number of issues that come up throughout the track.  For example, the issue of assembling a string by concatenation rather than appending to a list and using join().

> I propose to add a mentoring document to the general work area that includes general guidelines.  Of course I will overlook your pet peeve, so you will have to add it .

> Putting a general note in with all the problem specific notes may be the wrong place, but it would be nice to have a single spot to discuss optional tests, or List Comprehensions, etc.

from @cmccandless (slack)
> It would be nice to have the contents of such appear seamlessly with the exercise-specific mentoring notes.

> This would also make sure there was *something* in the mentor notes for every exercise.

> What I'm suggesting would actually require some changes to the website itself, pulling both from the general track guidelines (new feature) and the track/exercise notes (existing feature)

To summarize:

- Add document for general mentor guidelines that are language-specific, but not exercise-specific. I recommend storing this document in exercism/website-copy, at `tracks/${track}/mentoring.md`
- If the above document exists, append or prepend (discuss this below) its contents to the mentor notes for an exercise. If that exercise does not have its own `mentoring.md` yet, just use the track guidelines as the mentor notes.

tagging @iHiD

**Comment by ErikSchierboom** [comment]
I would really like this. My preference goes out to prepending.

**Comment by cmccandless** [comment]
Looking at the draft-in-progress in https://github.com/exercism/website-copy/pull/856, it occurs to me that general mentor notes might be a slightly longer document than the specific ones, so I agree that appending makes more sense.

**Comment by tejasbubane** [comment]
I was just about to create an issue towards this. Would be really useful to have it.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
