### ISSUE TITLE
Check if tests pass before submitting

### ISSUE THREAD

**Issue by alebaffa** [exercism/exercism#4746]
I just saw a submission empty (I can give you the link if you want). I don't know why the user has submitted an empty solution, but it is now in my list of feedback to give and it makes no sense to leave a comment on it. I think this can be an improvement for the cli.

The cli should check whether the tests pass or not before pushing the code to exercism. If the tests don't pass, it fails displaying a console message like _"sorry, you have to pass all the tests before submitting your solution"_.

What do you think?.

**Comment by F3PiX** [comment]
@dogweather In the first case: I start telling that the code didn't pass the tests (after I confirmed that), and ask the if they managed to run the tests, and if they could post the output and/or need help. 
In the second case: I start the review with my observation about the extra line, and ask the test questions as in the first case.

**Comment by Moeser** [comment]
Some languages will cache test results ( .pytest_cache for example ), and those can be farmed for info on whether tests were run and whether they were successful.

**Comment by iHiD** [comment]
We'll be adding automated running of the tests upon submission in the next month or two

**Comment by sshine** [comment]
Since the automated test runners are server-side only, according to @iHiD in #4941, this issue can be closed.
