### ISSUE TITLE
Lua logo violating license agreement

### ISSUE THREAD

**Issue by ryanford-frontend** [exercism/exercism#4748]
The Lua logo is pretty strict as to the modifications that can be made:

> Copyright © 1998 Lua.org. Graphic design by Alexandre Nakonechnyj.
>
> Permission is hereby granted, without written agreement and without license or royalty fees, to use, copy, and distribute this logo for any purpose, including commercial applications, subject to the following conditions:
>
>* The origin of this logo must not be misrepresented; you must not claim that you drew the original logo.
>* The only modification you can make is to adapt the orbiting text to your product name.
>* The logo can be used in any scale as long as the relative proportions of its elements are maintained.

So changing the colors, or the size/shape of the orbiting dashed line in relation to the rest is not permitted.

[Source](https://www.lua.org/images/)

**Comment by SleeplessByte** [comment]
But I don't think they're using that graphic, but rather a new one. I don't think these apply if you draw it yourself? I might be wrong 👍

**Comment by kytrinyx** [comment]
I didn't see this issue originally.

Yes, we're not using the Lua logo, we've created our own icon to represent the Lua track on Exercism. As far as I know, the restrictions apply to their specific logo.
