### ISSUE TITLE
Cannot set a draft pull request to be mergeable

### ISSUE THREAD

**Issue by ee7** [exercism/exercism#4751]
### Expected behavior
I can make draft pull requests, and later set them as "ready for review".

### Actual behavior
I can make draft pull requests, but cannot set them as "ready for review".

For example, I can't set https://github.com/exercism/python/pull/1718 to be mergeable.

The "Ready for review" button has disappeared. It worked a few days ago with the same machine when I used it for https://github.com/exercism/nim/pull/161.

### Screenshot
![s](https://user-images.githubusercontent.com/45465154/54155690-ff1bfd00-4444-11e9-9e89-87cb4ed0e622.png)

Note that the "Ready for review" button is missing from the top-right of the image. Compare with the [documentation for "changing the stage of a pull request"](https://help.github.com/en/articles/changing-the-stage-of-a-pull-request).

(The "Ready for review" at the bottom isn't a button).

### Other links
- The GitHub blog post from a month ago that [introduces draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

- Change from a few days ago: [non-authors can now press the "ready for review" button](https://github.blog/changelog/2019-03-08-expand-ready-for-review-permissions-for-draft-pull-requests/).

### Diagnosis
I don't know whether this is a GitHub issue, an `exercism` repo issue, or something strange with my machine. So I don't know if this is the right place to report this issue. I have:
- Reproduced the behavior in another web browser.
- Searched https://github.community
- Checked https://www.githubstatus.com
- Looked at the `exercism` repos, but I couldn't find any related issues, or any draft pull requests that weren't mine.

**Comment by ee7** [comment]
The button has reappeared, so this issue can be closed. 

I'd like to understand the cause, though. Did somebody change anything? My browser and machine are unchanged.


> According to [this page](https://help.github.com/en/articles/githubs-products) draft pull requests are only available for the team and enterprise plans.

Yes, but it seemed like they *are* available. I could always create them, and until a few days ago, I could set them as mergeable.

It's not that I think that draft pull requests are a necessary feature for us. We already have [WIP](https://github.com/apps/wip) set up on all the `exercism` repos.

But if they can be created, they shouldn't be stuck in some unmergeable state.

**Comment by Smarticles101** [comment]
> According to [this page](https://help.github.com/en/articles/githubs-products) draft pull requests are only available for the team and enterprise plans.

@PatrickMcSweeny  AFAIK, the exercism org is on the [Teams for Open Source(https://help.github.com/en/articles/githubs-products#github-team-for-open-source) plan

**Comment by kytrinyx** [comment]
Exercism is on the Teams for Open Source plan. GitHub had an outage a couple of days ago which affected pull requests and issues. I believe that the problem with the missing "ready for review" state was related to the incident.
