### ISSUE TITLE
no response from the mentor

### ISSUE THREAD

**Issue by superliza** [exercism/exercism#4752]
I have done three exercises, one normal and two laterals of Javascript, but in none I have received feedback from a mentor and therefore I have not been able to advance in my exercises.
Do you know if I should configure something?

**Comment by Smarticles101** [comment]
Mentoring is a completely volunteer based process. Currently, the JavaScript track has 540 exercises in the mentoring queue, so they may understandably be a bit of a wait. Possibly several days to a week I would guess.

How long have you been waiting? If it's longer than a few days, could you post links to your solutions?

**Comment by superliza** [comment]
Thank you very much for answering.
I really did not know this fact, now I understand why it can take a long time.
Yes, this was the first one I solved: https://exercism.io/my/solutions/500379827af24a2681f9208262b56f93 and then I continued with these two: https://exercism.io/my/solutions/c85ef01f0fd0457d92ed4bd669ca8070, https://exercism.io/my/solutions/425de62ffaae468a9e833aeeffa12603
