### ISSUE TITLE
updated exercise files unfetchable if test file unaltered

### ISSUE THREAD

**Issue by bdjnk** [exercism/exercism#4753]
Often an exercise's `README.md` or other files will be updated while the test file remains unchanged. Downloading the exercise does not update those other files (nor is there an option to update within the website). Instead you are provided the version from when the test file was last updated.

A particularly egregious example is [javascript - wordy](https://github.com/exercism/javascript/tree/master/exercises/wordy) where the test file is two years old, while the `README.md` and `package.json` are only six and two months old respectively.

@iHiD Asked me to link these lines in the website source:
- [website/app/models/concerns/solution_base.rb:53](https://github.com/exercism/website/blob/45147d7a1c34f16ef4bc41b07ed9790667521420/app/models/concerns/solution_base.rb#L53)
- [website/test/models/solution_test.rb:131-173](https://github.com/exercism/website/blob/50adcd9f113ce8bf588c722cb07d92e26734f905/test/models/solution_test.rb#L131-L173)

**Comment by sshine** [comment]
@ihid: Was this eventually fixed?

**Comment by sshine** [comment]
Ping #5052.

**Comment by iHiD** [comment]
@sshine I think we covered this in #4480 and this issue can probably stand for the one you suggested opening there.

I don't have an easy solution for this right now.

**Comment by sshine** [comment]
@bdjnk: Just to clarify, does the copy of README.md that is displayed on the website update properly, or is it both this *and* the copy of README.md that is downloaded by the student that don't update properly until the test file is touched?

**Comment by bdjnk** [comment]
On the website the latest version of the README is displayed properly, even if it is newer than the test file. @sshine

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
