### ISSUE TITLE
Feature request: Hide solutions from a certain mentor

### ISSUE THREAD

**Issue by codeholic** [exercism/exercism#4757]
Some mentors have got a too formalistic approach and do not provide valuable feedback, even when explicitly asked for it. Unfortunately these mentors are at the same time among the most active ones (at least on certain tracks), which totally disrupts the whole learning process and frustrates a lot.

As a student, I want to be able to hide my solutions from a certain mentor anonymously, when I'm not satisfied with their performance.

**Comment by jangroth** [comment]
I understand the problem, but I don't think blacklisting mentors would solve it. 

Better to work on an approach that ensures mentoring standards are kept.

**Comment by sshine** [comment]
This relates to "Request new mentor" in #4758, but aims at making it impossible for a mentor to address a student's solutions. Like @jangroth, I don't think this is a good way to address mentor standards: If a mentor is sub-standard, why should this knowledge not propagate to other students?

As it currently is, we have exactly the standards that mentors bring themselves.

I imagine that if a "Request new mentor" feature is made, and it is made in such a way that the mentor is aware of having been the subject of a re-request, the UI should somehow remind them that this is perfectly reasonable.

I generally don't think a request to have another mentor is unreasonable, but if there is any cause to believe that mentors cause personal disputes often enough for someone to submit a feature request to avoid them, then that problem probably cascades to other students. As such, I think there is a better way.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
