### ISSUE TITLE
Ordering of tasks is broken

### ISSUE THREAD

**Issue by pim-pesochek** [exercism/exercism#4759]
I have noted that order of tasks on Rust track has changed. Previosly it was ordered by difficalty, now it is something different
![image](https://user-images.githubusercontent.com/7115941/54496667-135b7080-4903-11e9-88e2-f3d34b518b14.png)

**Comment by F3PiX** [comment]
This is related to the restructuring of the [Track Anatomy](https://exercism.io/blog/track-anatomy-project) that is currently going on. 

@exercism/rust

**Comment by coriolinus** [comment]
Perhaps it would have better not to have merged https://github.com/exercism/rust/pull/804 until a final ordering were decided on.

**Comment by F3PiX** [comment]
@coriolinus 
Well, getting the first step of the track reordering was super-important as the track's order was making life difficult for mentors, and waiting another month or two for the others steps to be done would be punitive to learners.

**Comment by sshine** [comment]
I'm closing this issue because time has passed and it appears that @coriolinus and @F3PiX were aware of this ordering. Feel free to continue discussing the subject in this thread or continue on the Rust issue tracker: https://github.com/exercism/rust/issues
