### ISSUE TITLE
No mentor feedback for 56 days

### ISSUE THREAD

**Issue by DavidSSL** [exercism/exercism#4760]
For the following exercise https://exercism.io/my/solutions/948599615b484cb7b58cee42e5d8d4ca?iteration_idx=2 I have not gotten feedback for over 50 days. 

I do understand that mentoring is done on a volunteer basis for which I am grateful. However, I would like to proceed. What are the options available to me at this point?

**Comment by iHiD** [comment]
Hi @DavidSSL. Sorry you've been waiting ages. I've just spoken to the lead mentor on the F# track and he suggests that right now they've so overloaded that your best bet would be to switch to Independent Mode, where you can continue at your own pace. You could also "Complete Unapproved" if you'd prefer that approach. Sorry again.

**Comment by ptyxs** [comment]
I have got same kind of problem on the Kotlin track. Could you please explain how to use the 'Complete Unappoved' ? I didn't see it on the relevant page. Thanks.

**Comment by DavidSSL** [comment]
Thanks iHiD

**Comment by DavidSSL** [comment]
@ptyxs 
![image](https://user-images.githubusercontent.com/483473/54812941-a6423500-4c8c-11e9-904c-2034fb6c8714.png)

**Comment by ptyxs** [comment]
Thank you DavidSSL. I see on the popup that this doesn't unlock any further exercise so I shall opt for independent mode...

**Comment by DavidSSL** [comment]
@ptyxs I'm surprised because I tried it and it worked. But I guess going independent should work.
