### ISSUE TITLE
exercism/website: Test coverage badge no longer works

### ISSUE THREAD

**Issue by jhsu802701** [exercism/exercism#4762]
The CodeClimate test coverage badge no longer works.  Somebody should fix it or replace it.  Because I am not a collaborator, I cannot this.

I had this happen with my Rails apps.  I couldn't figure out how to get the CodeClimate test coverage badge to work again, so I switched to Codecov.  I have a procedure on how to add this badge at https://www.railsneutrino.com/docs/chapter07 .

**Comment by tejasbubane** [comment]
I think someone with admin access needs to setup the test coverage?

<img width="374" alt="Screenshot 2019-04-10 at 2 57 45 PM" src="https://user-images.githubusercontent.com/980783/55867926-10ba0700-5ba1-11e9-9b7a-4d1f2bdf405e.png">


Screenshot from [this page](https://codeclimate.com/github/exercism/website/).

**Comment by sshine** [comment]
@iHiD: This sounds neat. I'll let you address this and close the issue.
