### ISSUE TITLE
Get exercise name by solution's uuid

### ISSUE THREAD

**Issue by QLaille** [exercism/exercism#4763]
As I keep writing my own tools, I've stumbled upon a small detail: as I dockerize students solutions in new terminals, I have nothing to differentiate them all.
![image](https://user-images.githubusercontent.com/24566679/54677563-6dc31f80-4b03-11e9-8a9c-aa1dbeb2d14e.png)

Is there a possibility to retrieve a solution's exercise name by giving its uuid ?

**Comment by sshine** [comment]
@QLaille: I don't know, did you find out in the meantime?

**Comment by QLaille** [comment]
I'm not contributing to exercism since April for reasons related to studies, so I have no more infos on that, sorry.

**Comment by sshine** [comment]
OK, no problems. I hope your studies are treating you well.

I'm closing this issue as it relates to independent API work that is currently not focused on.

Feel free to get back if/when you should want to work on API-related stuff. I personally think this is one of the most interesting potentials of Exercism, as it allows arbitrary crowdsourcing. I think only the Pharo track has really went far with it (making it possible to participate in the Pharo track from within their IDE.
