### ISSUE TITLE
Solution does not seem to belong at top of Ruby mentor queue

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism#4766]
The solution with id 0a5ff6272efa4b4cbddc71fc820fef06 is at the top of the Ruby mentor queue even though a mentor has left a comment on the most recent iteration.

**Comment by F3PiX** [comment]
Duplicate of #4725

**Comment by PatrickMcSweeny** [comment]
In that case I will close this issue since the other seems to be more thorough.
