### ISSUE TITLE
I am not able to submit my first exercise on Ruby track.

### ISSUE THREAD

**Issue by subhan98** [exercism/exercism#4767]
Hello there,
 I am trying to submit my exercise on Terminal but it gives some errors:-

# Running:

Finished in 0.000925s, 1081.0813 runs/s, 1081.0813 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
muhammads-MBP-2:hello-world muhammadsubhan$ exercism submit hello_world.rb

    WARNING: Skipping empty file
             /Users/muhammadsubhan/Exercism/ruby/hello-world/hello_world.rb

		Error: 

    No files found to submit.

		
muhammads-MBP-2:hello-world muhammadsubhan$ ls
GETTING_STARTED.md	hello_world.rb		subhan
README.md		hello_world_test.rb
muhammads-MBP-2:hello-world muhammadsubhan$ 

I have no idea what is going on .help required , thanks.
M Subhan

**Comment by NobbZ** [comment]
What is the content of `hello_world.rb`?

For some reason the CLI sees it as empty and therefore refuses to submit

**Comment by xianrusso** [comment]
Hey!  Were you able to resolve your issue?
