### ISSUE TITLE
Looks like it's impossible to unlock the “Binary Search Tree” problem of the C++ track

### ISSUE THREAD

**Issue by ikr** [exercism/exercism#4769]
I've solved all the core C++ exercises, but the “Binary Search Tree” is still locked:

![image](https://user-images.githubusercontent.com/55146/54904103-cfa5cf80-4edd-11e9-9f0f-61c87d83d9a4.png)

**Comment by NobbZ** [comment]
That exercise has only been added recently to the track, probably you already fulfilled the prerequisites when the exercise was added. 

@ihid needs to run a script to get database in sync again. This script does not run automatically, as it takes several hours to days.

**Comment by ikr** [comment]
Oh, alright, thanks for the answer.

**Comment by ikr** [comment]
The exercise is unlocked for me now.
