### ISSUE TITLE
Transfer ownership of `teams/thinkcompany`

### ISSUE THREAD

**Issue by tjnicolaides** [exercism/exercism#4770]
This seems related to #4558 , but I was hoping someone with site admin privileges could help us out in the interim.

I've left the thinkcompany organization and would like to transfer the owner seat to someone else. If someone could follow up with me privately, I've already started an email thread with hello@exercism.io.

Thanks!

**Comment by iHiD** [comment]
Done. Thanks for following the instructions in the auto-responder 💙

**Comment by tikaro** [comment]
Hello, Exercism (and hi @tjnicolaides , and hi @iHiD !)

Thank you very much for making the change to the team.  the `thinkcompany` team is now our canonical team, and we'd like to _delete_ the extra, deprecated team that I made before I knew how responsive you all are.

Good team, we'd like to keep this one: https://teams.exercism.io/teams/thinkcompany

Deprecated team -- could you please delete this one?
https://teams.exercism.io/teams/think-company-developers

**Comment by iHiD** [comment]
Deleted. 

I think that's the first time we've deleted a team so consider this fair warning of ¯\_(ツ)_/¯ :)

**Comment by tikaro** [comment]
Thank you very much! So far, everything seems
fi-

https://media1.tenor.com/images/f6637c4653407c406995cc06e378dc00/tenor.gif?itemid=10387204

**Comment by iHiD** [comment]
:)

**Comment by iHiD** [comment]
Can we close this?

**Comment by tikaro** [comment]
You most certainly can close this — and thank you!

**Comment by iHiD** [comment]
Awesome. Thanks :)
