### ISSUE TITLE
mentoring

### ISSUE THREAD

**Issue by amryounis** [exercism/exercism#4775]
Hi,

I would like first to thank you for you great effort. I am really enjoying my time with it.

Regarding mentoring, I believe there a room for improvement here. 

For example, I received the following reply from a mentor in the Haskell track:

> The solution can be simplified, explicit recursion eliminated by using a Prelude function.

I believe **mentoring is a key differentiator for Exercism** and leveraging it will leverage your efforts’ value.

Thank you,

Amr

**Comment by Smarticles101** [comment]
I think it would be helpful if you could explain more how you think replies like that could be improved. Mentoring is a completely voluntary process, so understandably, there are various styles of mentoring that different mentors use.

There are projects in place to improve the mentor-learner relationship, as well as the mentor-mentor relationship, which should greatly improve the experience.

Any insights you have on how you think mentoring could be improved would be helpful, and make great discussion points.

**Comment by iHiD** [comment]
@amryounis I'm closing this as there has been no response, but please feel free to reopen if you want to explain more as per @Smarticles101's comment :)
