### ISSUE TITLE
No mentoring on Java track

### ISSUE THREAD

**Issue by michailangelo** [exercism/exercism#4777]
Hello, I have submitted about a month ago my solution to the scrabble score problem but I have yet to see any feedback. I do realize that this is a volunteer's work but I would greatly appreciate any update on the status of mentoring.

**Comment by iHiD** [comment]
Could you provide a link to your solution pls?

**Comment by michailangelo** [comment]
Here you are : https://exercism.io/my/solutions/8de6668b57334ef69156707ff9f4d247

**Comment by michailangelo** [comment]
A mentor finally gave feedback!

**Comment by iHiD** [comment]
Thanks for letting us know and for your patience :)

**Comment by furnace915** [comment]
I have the same issue...been waiting about a month:  https://exercism.io/my/solutions/c275d54b1e944d5f89230b128010f274

**Comment by iHiD** [comment]
@furnace915 Could you open a new issue pls?
