### ISSUE TITLE
Mentors skipping exercises, related questions

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4778]
Today in a discussion the theory came up that all (active/remaining) mentors might have skipped mentoring for a certain solution. Due to this the following questions came into my mind which we decided to put in an issue to make them publicly answerable and maybe even derive further actionable issues from the answers.

* I remember @iHiD said once that when all existing mentors for a track skip mentoring then the solution will be requeued, is this still true?
* If many mentors have skipped but at least one mentor has left exercism or wont come back in a reasonable amount of time, but also hasn't revoked mentorship, what will happen to this exercise? Will it be lost forever or will the "skip" timeout after some reasonable time?
* After mentors have skipped a solution and the student iterates on his own, will the new iteration pop up again on the list for mentors that previously skipped?
* If a skipped solution is inserted back into the queue, there is currently nothing that holds mentors back from skipping it again. Are there solutions available to this infinite skipping?

**Comment by NobbZ** [comment]
As a quickfix for the last bulletpoint (re-skipping solutions) I think just disabling skip for re-inserted exercises would be sufficient.

Still we need to find a way to "enforce" mentoring on those earlier or later. Mentors might decide to simply ignore those exercises in the queue.

Therefore I think the following changes should be introduced to skipping in the mid- to long-term:

* Ask mentors for why they are skipping (not publicly visible)
* Show them how many other mentors already skipped
* Unskip exercise for everyone after it has not been mentored for X days in that it had been visible on the queue if it were not skipped with a public notice similar to a mentor that has been removed because of inactivity
* (Perhaps increase priority of the solution by artificially increasing its age)
* Do not allow to skip again
* After another Y days without mentoring while beeing visible in the queue notify a higher instance that gets access to the anonymous skipping reasons, this higher instance then should try to get the student the mentors on a table to get at least some improvements.

As a mentor I often have the instinct to skip because of me thinking the code is too complicated to mentor it. Other mentors might think the same and the student will never know about it. Even worse, even if he knew, he probably can't simplify/refactor without mentors guidance.

Also we should clearly communicate to mentors, that skipping is a "final" decission. "I have not the time to do this right now, but perhaps I can do tomorrow" is **not** a valid reason to skip a solution, instead it should be simply left unmentored in the queue.

**Comment by NobbZ** [comment]
I will do it like another member of this community, and delete this post after also adding the following bulletpoint into the list of the original post as the third item in the list.

* After mentors have skipped a solution and the student iterates on his own, will the new iteration pop up again on the list for mentors that previously skipped?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
