### ISSUE TITLE
My Rust track exercises structure seems broken

### ISSUE THREAD

**Issue by jerdna-regeiz** [exercism/exercism#4781]
Hey! Thanks for exercism!
A few days back I got bored to wait for a mentor on rust track and thought maybe previous exercises I completed without mentoring may get review  faster and thus reactivated them to get the side-exercises unlocked.
Getting feedback fast did work out quite fine and I completed reverse string (6655c1a59b214839a887e2f68e240a20) and gigasecond (c87c35c4b0de4ed9a1371d1f449d9de1). Text in gigasecond says it unlocked 3 sides as well as reverse string. But both show no side-exercises for me =(
Got bored again and completed bob unmentored (ee483052fea847c2a61bb9ce94407395) to solve clock (submitted). Felt bad about it and wanted a chance for the side-exercises and wanted to reactivate bob , but I can't (buttons for publish, view community, choose next, comment and complete unapproved).
I found Saddle Points under Extra exercises and know I have nth-Prime open.

Something does not fit here. Bob behaves like a side and core at the same time, Saddle Points unlocked but not under any core, bracked push (finished) under Bob (completed unapproved), 3 open side-exercies of which I can only see 2.

Could anyone have a look at that and tell me if everything is alright? Just don't want to miss anything :(

Cheers, Andrej

**Comment by iHiD** [comment]
I'll take a look on Monday for you. This track is undergoing restructuring
so it's possible something has gone a bit weird for you. If you've not
heard back by Tuesday, please add a comment to remind me.

**Comment by jerdna-regeiz** [comment]
gentle ping :)

**Comment by iHiD** [comment]
Could you send me a screenshot of the core part of the track please?

**Comment by iHiD** [comment]
From the db, it looks like you have two core exercises (bob, clock) waiting for mentoring and no side exercises waiting for mentoring. Bob was promoted to core last week and gigasecond doesn't unlock anything. I can't see anything actively wrong with your track, but if you send me a screenshot I can understand more :)

**Comment by jerdna-regeiz** [comment]
Sure. From my side it not really looks as if bob is awaiting mentoring, but I can't request it either.
Should "Reverse String" unlock anything? Still get the message "You have 1 unlocked core exercise and 3 unlocked side exercises", but see only "Luhn From" ( broken icon next to "bracket push" which was not thereyesterday =) sadly I do not have "Luhn").
I attached my options for Bob and the track overview. If everything is okay, I'll just keep on waiting for mentoring of bob and clock :)
Bob:
![rust_bob](https://user-images.githubusercontent.com/7195718/55434698-75b99f80-5598-11e9-8153-b51870d93818.jpg)
Track:
![rust_track](https://user-images.githubusercontent.com/7195718/55434699-75b99f80-5598-11e9-9e91-7f01601acd77.jpg)

**Comment by sshine** [comment]
@jerdna-regeiz: Seeing as this issue has grown a bit old, did you eventually progress?

**Comment by jerdna-regeiz** [comment]
Yes, sorry it works now =)
Thank you!
