### ISSUE TITLE
Waiting for mentor on Kotln track                                  OVER 20 DAYS

### ISSUE THREAD

**Issue by YonatanMyers** [exercism/exercism#4782]
Hi,
I really like your site and learn a lot from using it.
I understand this is a volunteer-based project and really appreciate the work.
I was wondering what would be considered an acceptable time to wait for mentor feedback?

It has been 21 days since I have posted a solution and have not gotten any kind of reply.
I would like to go on but do not want to loos the valuable molter input. 

My Ex is found at:

https://exercism.io/tracks/kotlin/exercises/flatten-array/solutions/8a158b6680794f459081153744b649f6

Thanks

**Comment by iHiD** [comment]
Replaced by https://github.com/exercism/exercism/issues/4800
