### ISSUE TITLE
Does mentorship include help/guidance when doing exercises, in case we need it? 

### ISSUE THREAD

**Issue by zimonbizkit** [exercism/exercism#4783]
First, just congratulate you guys behind exercism :) it's being really helpful to me!

I'm currently doing the rust track. As specified above, I would like to know if I'm able to contact a mentor via the track  for  either:
- help
- guidance
- assistance
In case I don't understand any exercise or stuck in a programming problem. That would be good as sometimes I upload exercises to have the comment box on the track exercise, and the exercise is not finished yet.

Thank you :) :+1:

**Comment by NobbZ** [comment]
Yes, an unfinished submission as far as you got is the way to go, additionally put your question in the comment box and submit it as well.

Usually mentors will adhere to your questions in their feedback.

Also, some languages communities have public boards that are eager to help with your problems, and sometimes feedback might even be quicker there as your audience is much bigger.

Just make sure, if you join a community to be honest and say "on exercism I have this problem". This gives us some advertisement ;) And also avoids "we don't do your homework" answers :)

**Comment by zimonbizkit** [comment]
Great! Closing this issue as my doubt was resolved. Thanks for the answer!
