### ISSUE TITLE
The Pharo track is ready to move from beta to live

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4790]
@iHiD asked me to raise an issue to see if we can get the Pharo track live on the site. We now have an icon, and docs and 24 exercises and several people writing new ones each day... so I think the momentum is there. We have also had several weeks of 3-5 beta testers working through the exercises and ensuring the process works.

@iHid suggested that @ErikSchierboom can look at our [config.json](https://github.com/exercism/pharo-smalltalk/blob/master/config.json) - we are looking at replacing leap with an alternate core exercise.

@kytrinyx I'm not sure if there are other boxes we need to tick.

If its at all possible to flip the switch in the next few days, I'm at a Pharo conference pitching for more mentors and more support writing exercises - so having a live track makes the description easier (just got to exercism.io vs. go there and modify the link).

However, if we genuinely aren't ready - then we can close this and re-open when any concerns are addressed.

**Comment by iHiD** [comment]
It sounds to me like you've done a fantastic job and are ready to launch. We need a PR from you to change active to true in your config.json and then if @kytrinyx approves, I will merge that and do any final bits in the db :)

One comment I would make is that the config.json should be formatted with two-spaces rather than tabs please :)

**Comment by kytrinyx** [comment]
Oh my goodness, yes! Let's do this.

How exciting ❤️ 💛 💚 💙 💜 🖤 


> One comment I would make is that the config.json should be formatted with two-spaces rather than tabs please :)

The `configlet fmt .` command _should_ take care of that.

**Comment by kytrinyx** [comment]
> If its at all possible to flip the switch in the next few days, I'm at a Pharo conference pitching for more mentors and more support writing exercises

Also, this is great! Let's get this live while you're there!

**Comment by macta** [comment]
Ok - I've adjusted it to use 2 spaces, and that now appears in the pr https://github.com/exercism/pharo-smalltalk/pull/254#pullrequestreview-222503027. And @kytrinyx seemed happy too.

So should i merge my new config in that pr ?

**Comment by kytrinyx** [comment]
I'm pretty sure we're live, closing this! 🎉
