### ISSUE TITLE
Travis CI 'sudo: false' deprecated

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#4793]
According to https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration,

    sudo: false

was deprecated on December 7, 2018. It still occurs in 24 copies of `.travis.yml` across our tracks.

Should we remove these lines and continue as usual, or should we react to this "container-based `sudo: false` environment no longer being available"?

```bash
$ find . -name .travis.yml -exec ack -li "sudo.*false" {} \;
plsql/.travis.yml
elixir/.travis.yml
scala/.travis.yml
php/.travis.yml
racket/.travis.yml
perl5/.travis.yml
bash/.travis.yml
ecmascript/.travis.yml
lua/.travis.yml
coffeescript/.travis.yml
sml/.travis.yml
dart/.travis.yml
kotlin/.travis.yml
erlang/.travis.yml
rust/.travis.yml
elm/.travis.yml
javascript/.travis.yml
haskell/.travis.yml
java/.travis.yml
clojure/.travis.yml
d/.travis.yml
cpp/.travis.yml
go/.travis.yml
ruby/.travis.yml
```

**Comment by NobbZ** [comment]
In erlang I just removed that line, build seems to do fine with and without the flag.

The PR is merged, exercism/erlang#384.

**Comment by iHiD** [comment]
@kytrinyx Could you do one of your magic multi-repo issues here pls?

**Comment by sshine** [comment]
Since Travis is being deprecated, so is its proper configuration.
