### ISSUE TITLE
PHP Track - Luhn exercise

### ISSUE THREAD

**Issue by nervaccio** [exercism/exercism#4794]
First, thank you to all the mentors for your time!

I'm stuck at the Luhn exercise, I'm waiting for feedback from a Mentor. I submitted the exercise a couple of weeks ago.
I would like to know if there is a problem with that track/exercise.

The PHPUnit testing is ok, and all the previous exercise too.

I can wait if the Mentor of that challenge is busy.

In the meantime, I'm going to start a new track! :D

Thank you!

**Comment by nervaccio** [comment]
If there is no more "support" from mentors on PHP, could I know?

https://exercism.io/my/solutions/eae3e322992e42678507e73e1108495c
Cheer

**Comment by iHiD** [comment]
I've pinged the PHP mentors asking for someone to reply here :)

**Comment by nervaccio** [comment]
Thank you so much!
