### ISSUE TITLE
Website Displaying Test Framework

### ISSUE THREAD

**Issue by patricksjackson** [exercism/exercism#4797]
The C and *C++ tracks ship our full test _frameworks_ along with each exercise to simplify setup. This lets the students only need to grab a set of standard build tools to get started instead of installing dependencies. It would be easier if we could download some common dependencies, but I believe that's been discussed in the past and not implemented, although I'd love to be wrong.

The problem is that the website seems to show every non-markdown file in the 'Test suite' tab for each exercise. Thankfully it shows the actual test suite first, but it also includes the multi-thousand lines of test framework code as well, which isn't really useful.

**Is there anything we can do to avoid showing an irrelevant, 15k line file on the website?**

Paging @exercism/c and @exercism/cpp for visibility

*C++ is still in the process of moving to this model, since we've long had to deal with problems with dependency installation, but you can view that on the latest hello-world exercise.

**Comment by ryanplusplus** [comment]
I would love for there to be an upstream solution to this. There are already similar methods for ignoring certain files in the track configuration so it doesn't seem like a stretch to have support something like this as well.

**Comment by iHiD** [comment]
Hello.

The website shows files that match the `test_pattern` set in `config.json` For example, [MIPS](https://github.com/exercism/mips/blob/master/config.json#L5) and [HAXE](https://github.com/exercism/haxe/blob/master/config.json#L6).

The CLI provides the user with all files that don't match the `ignore_pattern`.

So I believe you can do this by setting those. Let me know if that makes sense or if I've misunderstood something :)

**Comment by patricksjackson** [comment]
@iHiD That was exactly what we were missing :) We'll make sure to update that in our tracks.

Thanks!
