### ISSUE TITLE
No feedback for 50 days

### ISSUE THREAD

**Issue by keipoh6w** [exercism/exercism#4799]
I submitted my first solution to Simple Cipher exercise on TypeScript track 50 days ago, but have not got any feedback. Is something wrong?

**Comment by keipoh6w** [comment]
@iHiD Thank you for your reply.
Here is [my solution](https://exercism.io/my/solutions/1b28503eb4eb4a77b843aec81d1b2e86).
I am not sure but guess this URL includes the solution ID.

**Comment by iHiD** [comment]
Thanks. I've asked the Typescript mentors to provide some more information here for you.

**Comment by sproj** [comment]
Looking now.

**Comment by sproj** [comment]
Done, thanks for raising @keipoh6w.
