### ISSUE TITLE
Join teams submissions with main mentoring queue

### ISSUE THREAD

**Issue by bkhl** [exercism/exercism#4801]
Just made all the junior engineers in my team at work (ca 10) join Exercism and start the Python track, they will have time allocated and monetary incentives to complete it.

The idea is they'll send me links and I'll handle the mentoring if I get in there first, but they may also get other mentors.

I have also created a team on teams.exercism.io for them, but we are not using that for solutions for now, because:

* I want some of their solutions to be mentored by other people, not just me. I think I'm making up for that by doing some mentoring of solutions from the general public as well.
* I want them to follow the track. While that could be managed manually, using the regular mentored mode in the standard edition is a nicer experience.
* I want to get notified of new comments and submissions, which now I don't get in the teams edition (since there is no mentoring concept there).

# Suggestions

Here are some suggestions that I think would make Exercism better for my use case.

* Allow me to filter submissions on the mentoring dashboard on the main site to see submissions by my team. This would eliminate the need for team members to send me links to their solutions for mentoring, so would have a big benefit for me.
* Drop the separate submissions to a particular team. Instead just show any submissions by team members in the standard edition as part of the timeline. The current feature existing doesn't hurt me of course, but I think separating submissions into "standard" and "teams" is adds unnecessary complexity.
* Allow users to put solutions (by themselves or other team members) on a "featured solutions" board, similar to the one that's user profiles now. This is more of a nice-to-have, that would replace the team submissions from the second point.

**Comment by sshine** [comment]
Having used the Perl track and Teams for training juniors at work, I think you hit the nail on this one.

I don't think Teams or the use-case of commercial training via Exercism is a priority right now.

But it could become that in the future, so we'll save the feature request for now.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
