### ISSUE TITLE
Emacs reference manual is not always installed

### ISSUE THREAD

**Issue by stefanv** [exercism/exercism#4804]
On the "learning elisp" page, it is suggested that learners look at the built-in emacs reference guide.  This guide is not distributed on all systems (such as Debian), due to its license.

Here is the exercism page: https://exercism.io/tracks/elisp/learning

Here is the EmacsWiki page where the documentation can be accessed: https://www.emacswiki.org/emacs/EmacsLispReference

**Comment by kotp** [comment]
Thank you @stefanv for that.  Would you be up for creating a pull request for that?  The repository for this would be https://github.com/exercism/elisp and the file to change can be viewed at https://github.com/exercism/elisp/blob/master/docs/LEARNING.md.

**Comment by stefanv** [comment]
@kotp Sure! Done: https://github.com/exercism/elisp/pull/110

**Comment by tejasbubane** [comment]
This issue can be closed.
