### ISSUE TITLE
Missing guides

### ISSUE THREAD

**Issue by bradyt** [exercism/exercism#4805]
From Tracks / C Track / Hello World / Instructions.

> Getting Started
> Make sure you have read the "Guides" section of the C track on the Exercism site. This covers the basic information on setting up the development environment expected by the exercises.

I do not see anything labelled "Guides". Should there be documentation on using tests, etc?

I am in independent mode, was this content made available only to users in mentored mode?

**Comment by patricksjackson** [comment]
Thanks @bradyt, we didn't see this in the C track. We missed updating those docs to refer to sections on the new website (the design changed a while ago).

I've opened https://github.com/exercism/c/issues/396 for us to address it. This issue here can be closed and we will handle it in the C track.
