### ISSUE TITLE
Run shellcheck automatically on submissions in Bash track as a mentor aid

### ISSUE THREAD

**Issue by bkhl** [exercism/exercism#4806]
I find that when mentoring in the Bash track, a lot of the time, on the early exercises, a lot of my comments are about stuff that would have been caught by [shellcheck](https://www.shellcheck.net/) (static analysis tool for sh/Bash).

How about running it automatically and show the output to the mentor, augmented with ready-to-paste links to the explanations for their warnings on the shellcheck wiki? This seems like a simple to implement start towards "automatic analysis of solutions to recommend common improvements" mentioned in #4588.

**Comment by sshine** [comment]
That sounds like an excellent idea.

If you would like to spearhead an attempt at running shellcheck on the bash track, ping @exercism/bash and join the Slack channels `#automated-tests` and `#automated-analysis` to bootstrap.

I'm closing this issue now, but feel free to continue discussion here, there or on the bash issue tracker: https://github.com/exercism/bash/issues

**Comment by sshine** [comment]
On a similar note, it may be *just* as valuable to run shellcheck on all of Exercism's repos. There's a lot of CI scripts, and I know that I committed something that wouldn't pass shellcheck at one or more points in time. ;-)

**Comment by guygastineau** [comment]
This is a good idea.

I have wanting to get some automated analysis for the bash track for a while.

`shellcheck` (as far as I can tell) won't give us an AST (although I imagine it builds one), so I didn't think about how it could be used for static analysis (even though it is itself a static analysis tool 🤣).

At least for now having a disapproving only analysis model that gives `shellcheck` feedback to mentors on student iterations sounds great.

@bkhl we would certainly welcome an issue to track this.

**Comment by sshine** [comment]
Wrt. static analysis and extending shellcheck: I have much the same situation on the Haskell track with HLint. HLint is extensible with a YAML file, but it only lets you do so much. Forking HLint to extend it seems a little wrong, too (having to maintain upstream changes). So I thought about extending it with loadable modules, or something.
