### ISSUE TITLE
Feedback textfield should be resizeable

### ISSUE THREAD

**Issue by Wulthan** [exercism/exercism#4807]
The current feedback textfield has roughly a 3 line height. This is pretty small and writing longer texts in it can be a struggle since you can't resize it.
It should be resizeable and/or bigger by default.

**Comment by iHiD** [comment]
Please attach a screenshot. It is resizable for me.

**Comment by Wulthan** [comment]
![teams exercism io](https://user-images.githubusercontent.com/24566797/56216582-fc26b480-6061-11e9-85cb-adfb958251cc.png)
