### ISSUE TITLE
JS exercise content is not being downloaded.

### ISSUE THREAD

**Issue by gcoronado28** [exercism/exercism#4814]
The content inside one of the JS side exercises is not being fetched.
I ran `exercism download --exercise=matching-brackets --track=javascript` in the console and the exercise folder appears but its content doesn't, it comes with the _.exercism_ subfolder only. Any info about this? Is this because they're upgrading the exercise or what?

**Comment by iHiD** [comment]
This should be fixed now. Sorry. Please confirm.
