### ISSUE TITLE
Feature Request: Sort by number of submitted community solutions

### ISSUE THREAD

**Issue by wolverineks** [exercism/exercism#4820]
I would like to progress from the most commonly solved problems to the least commonly solved problems.

Allowing the user to sort the problems in each track by most submitted community solutions would enable this.

I believe this order would benefit new developers. It is unambiguous, nonjudgemental,  and community controlled.

Thanks!

**Comment by iHiD** [comment]
Hello. I presume you're referring to independent mode? If so, could you explain what the logic is behind you wanting to do this please?
