### ISSUE TITLE
Python WordCount exercise stuck > 100 days.

### ISSUE THREAD

**Issue by nicomo** [exercism/exercism#4821]
I made a mistake and submitted the test file first, then submitted the solution in a new iteration, then forgot about it. Now I'm back, it's been > 100 days, and the exercise is still not approved / commented upon by a mentor.
Maybe I did something wrong and it never appeared in the mentors review list?
Can someone have a look?
Thanks,

**Comment by F3PiX** [comment]
Can you post the link to your exercise please? So Python mentors can see if it appears in the queue.

**Comment by nicomo** [comment]
Sure: https://exercism.io/my/solutions/d3b770c7de6c41188391cf995fa5c03e
Regards,
N.

**Comment by cherylli** [comment]
Your solution is now on top of the queue for WordCount, showing last updated 18 days ago. I think the python mentors can't keep up with the submissions.

**Comment by nicomo** [comment]
And... mentored and approved. Another solution still waiting, but I'll just wait I guess.
Thanks.
