### ISSUE TITLE
Mentor feedback Rust track

### ISSUE THREAD

**Issue by hallodaniel** [exercism/exercism#4830]
Hi, 

Reviewing seems to be very slow on the Rust track. I have been waiting for feedback on clock for at least two weeks and would really like to continue: 4e1e1f12971640d7a3c20bdfd3564b65

Are the mentors all gone? Or is it an influx of students? Do I need to be more patient?

Thank you! Daniel

**Comment by iHiD** [comment]
Hello. Rust is struggling under the weight of submissions. Thousands of students, only ~50 active mentors. We're working on restructuring the track (which has fixed this problem in other Languages) and we have had a recent influx of mentors who are helping get through it.

**Comment by SleeplessByte** [comment]
This submission has been approved.

**Comment by macperez** [comment]
as @hallodaniel I am waiting feedback for clock exercise. I think when a track is in a bottle neck I'd suggest free more blocked exercises in order to continue while the mentor is working. I have been waiting almost 10 days.

**Comment by SleeplessByte** [comment]
@macperez please post your URL. What is the messaging of the queue?

**Comment by macperez** [comment]
https://exercism.io/my/solutions/5f5a979ccb7540538ff0c85c3302b80e

**Comment by hallodaniel** [comment]
Hi again, it's great that you added info about the mentor queue! I'm stuck on the atbash cipher exercise for two weeks now, awaiting mentor feedback, and the number of solutions ahead of me in the Rust queue is going up! I don't think this should happen in a FIFO queue :)

https://exercism.io/my/solutions/89ea88740b7241c2a382cf74e720a9f8?iteration_idx=2

Thanks
