### ISSUE TITLE
Stop mentoring

### ISSUE THREAD

**Issue by boastful-squirrel** [exercism/exercism#4837]
I sent you a request to stop my mentoring on exercism.io, please check your emails. Cheers !

**Comment by kotp** [comment]
Above e-mails checking task was probably meant for @iHiD not for anyone else that may read this.

**Comment by sshine** [comment]
@iHiD: What does `status/needs-triaging` do, and has this been done?

**Comment by iHiD** [comment]
Yes, it's been done.

`status/needs-triaging` meant it should be moved to a different repository (e.g. bugs/support/wip etc) before those had been created. I don't remember what my intention was at adding that at the time.
