### ISSUE TITLE
How about Smartphones?

### ISSUE THREAD

**Issue by giner** [exercism/exercism#4843]
I have just recently discovered exercism.io and I wish I had long time ago. This is an amazing project. Thank you!

Nowadays people spend a lot of time public in transport (well, at least we do in Tokyo) and this fantastic opportunity to be doing exercises and helping others in their journeys to the world of programming instead of killing time by playing games is hard to underestimate. How about extending [this](https://exercism.io/cli-walkthrough) page with instructions for Mobile phones? I'm not sure about iOS however it is quite easy to install and use exercism cli with [Termux](https://github.com/termux/termux-app) on Android (`pkg install golang && go get github.com/exercism/cli/exercism`). I'm personally doing bash and golang exercises exactly this way.

**Comment by iHiD** [comment]
Hello! Thanks for the encouragement and the idea :)

I'd happily accept a Pull request about Android installation. This CLI walkthrough repo would need it adding - there is documentation here if you'd like to do it :) https://github.com/exercism/interactive-cli-walkthrough/blob/master/CONTRIBUTING.md

**Comment by Tausif-Husine** [comment]
> `pkg install -y golang && pkg install -y git && go get github.com/exercism/cli/exercism && echo 'export PATH=$PATH:$HOME/go/bin' >> ~/.profile && source ~/.profile`  
>  
> This doesn't work anymore. Use `pkg install -y golang git && go install github.com/exercism/cli/exercism@latest && echo 'export PATH=$PATH:$HOME/go/bin' >> ~/.profile && source ~/.profile` instead.

**Comment by Tausif-Husain** [comment]
> `pkg install -y golang && pkg install -y git && go get github.com/exercism/cli/exercism && echo 'export PATH=$PATH:$HOME/go/bin' >> ~/.profile && source ~/.profile`  
>  
>  
This doesn't work anymore (kinda). Use `pkg install -y golang git && go install github.com/exercism/cli/exercism@latest && echo 'export PATH=$PATH:$HOME/go/bin' >> ~/.profile && source ~/.profile` instead.
