### ISSUE TITLE
problem with gem install minitest for mac

### ISSUE THREAD

**Issue by gabokappa** [exercism/exercism#4845]
Hello, new to Exercism and managed to submit the first exercise for Ruby fine (Hello World) so I'm not sure if there is much of an issue, but I keep on encountering the following permissions error, whenever I try to install _gem install minitest_

This is the error:
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory

When I manually navigate to the files through the finder, i can see that in the Ruby file there is a file called minitest-5.8.5. 

Any help, would be very much appreciated. Thanks!

**Comment by ShreeMsethi** [comment]
Hi i am getting the same error when trying to install minitest. I was not able to submit the test. I am unsure if not being able to install minitest was part of the problem. But since you were able to submit it without the minitest; i think i am doing something wrong while downloading the test.

**Comment by gabokappa** [comment]
It might be a slightly different issue as I’ve been able to submit two exercises now, without an issue. I still get an error when I try to run the install on the minitest. I did following the installation procedure as per Exercism instructions so unsure why the gem install is being problematic.

**Comment by ShreeMsethi** [comment]
Yeah i followed the download instructions to the T. I am not sure wether i should see some actual downloads when i copy paste the test download link onto the terminal and hit enter as per the instructor video.

**Comment by mikegee** [comment]
The version of ruby installed by default on macs need higher permissions to install gems. `sudo gem install minitest` should ask for your password then succeed.

**Comment by agathaeva** [comment]
> The version of ruby installed by default on macs need higher permissions to install gems. `sudo gem install minitest` should ask for your password then succeed.

I had the same issue.. but this works! Thank you!

**Comment by iHiD** [comment]
I would recommend using [RVM](https://rvm.io/) to manage Ruby, rather than using the Ruby that comes installed on your system. I'm going to close this as everyone seems to have progressed :)
