### ISSUE TITLE
Problem with exercise Luhn on the Python track

### ISSUE THREAD

**Issue by studiosi** [exercism/exercism#4850]
How is "59" a valid code according to the algorithm?

```
def test_a_simple_valid_SIN_that_becomes_invalid_if_reversed(self):
        self.assertIs(Luhn("59").is_valid(), True)
```

59 > 5 18 > 5 9 and 14 is not divisible by 10

or am I missing something?

**Comment by NobbZ** [comment]
Yes, you are.

IIRC Luhn doubles every second digit from the rear, so it is 5 9 -> 10 9 -> 1 9 -> 10.

**Comment by studiosi** [comment]
Ok, so all the rest of the tests pass anyway?

**Comment by NobbZ** [comment]
As far as I remember, the fact that other tests passes regardless of the direction you count from, has lead to the introduction of this test.

**Comment by studiosi** [comment]
Knowing that, it took half a minute to correct it 👍
