### ISSUE TITLE
Not all Font Awesome icons are rendered in Firefox on Linux

### ISSUE THREAD

**Issue by Stigjb** [exercism/exercism#4852]
I noticed that some icons on the Exercism website did not display in my browser, for instance the notification bell. I suspect an issue related to "v4-shims.css", since it has 0 rules according to my development tools. The notification bell has class `"fa fa-bell-o"`. The `-o` suffix is deprecated in Font Awesome v5, and would normally be handled by v4-shims.

The bell gets rendered in Opera on Android, so this is not an issue in all browsers.

Firefox 66.0.5
Linux Mint 18.3

Edit:

Other icons that aren't displayed are the follow links in the footer (Twitter, Facebook, Github), as they need a `fab` class in Font Awesome v5, something `v4-shims` would have taken care of.

**Comment by Stigjb** [comment]
I have identified the cause to be a Firefox extension, Privacy Badger, which was blocking cookies from pro.fontawesome.com. I'm closing the issue.

**Comment by iHiD** [comment]
Thanks for both opening the issues and housekeeping it when you found the resolution :blue_heart:
