### ISSUE TITLE
Ruby track - mentors haven't replied in a week

### ISSUE THREAD

**Issue by judan** [exercism/exercism#4853]
Hi,

I waited for over a week for a mentor to comment on one of my exercisms on the core Ruby track. While I was able to get mentors to comment on the side exercises, I have been stuck for a while on 5/15. How long on average does it take to get feedback? I've switched to independent mode for now. Please let me know.

Thanks!

**Comment by PatrickMcSweeny** [comment]
Feedback time varies based on a lot of factors. Recently, a bug was fixed that caused a lot of old solutions to go to the top of the queue, so that might be part of the reason for the delay.

**Comment by iHiD** [comment]
@judan Are you still waiting and if so, do you have a solution id pls?

**Comment by chadhamre** [comment]
Roughly how long should we expect to wait to have a solution reviewed?

**Comment by judan** [comment]
@iHiD Appreciate you checking on this. They seem to be more responsive now. Thanks!

**Comment by iHiD** [comment]
Great. I'm going to close this :)
