### ISSUE TITLE
Need Python Exercise Approved 

### ISSUE THREAD

**Issue by Camarbro** [exercism/exercism#4854]
It's been over a month since I submitted the 5th exercise on the Python Track and I'm still waiting for mentor approval.

Can someone help me out on how to get the exercise approved?

My solution link is: https://exercism.io/my/solutions/3e93436fb56f47cf9e1c27b00e456472

**Comment by yawpitch** [comment]
I'm sorry for the delay but the Python mentoring queue has a substantial backlog at the moment; you're currently 17th in the queue for Matrix (the 4th exercise), but there are currently several dozen submissions for other exercises that have been waiting longer than even the top Matrix submission. I'm afraid you'll have to be patient for a little while longer.

**Comment by SleeplessByte** [comment]
This exercise has been approved.
