### ISSUE TITLE
Submitting issues cont.

### ISSUE THREAD

**Issue by bissingerz93** [exercism/exercism#4855]
I can not for the life of me figure out how to submit this code. I am trying to submit Kotlin code and the instructions to submit it re beyond vague. I have tried entering it every which way and the furthest I got was "system can not find the file specified. I am lost. 

<img width="802" alt="Annotation 2019-05-19 184305" src="https://user-images.githubusercontent.com/50809564/57989262-47b7ee00-7a66-11e9-8b83-76affd4f5ad0.png">
<img width="500" alt="dd" src="https://user-images.githubusercontent.com/50809564/57989265-4b4b7500-7a66-11e9-87af-98dd7f1f11ae.png">

**Comment by NobbZ** [comment]
Hi @bissingerz93!

The screenshot makes it hard to understand what happens, I'd prefer a copy/pasted terminal output.

Anyway, as far as I can tell, you are randomly using `cd` to do `exercism` stuff.

Sometimes appended by other commands.

You need to do `cd` and `exercism submit` on separate lines.

Such that you use `cd` to change your working dir to be at the correct place and then use `exercism submit src/main/kotlin/helloworld.kt` to submit.

It should look roughly like this then:

```plain
C:\…\Exercism>cd kotlin\hello-world
C:\…\Exercism\kotlin\hello-world>exercism submit src\main\kotlin\helloworld.kt
```

**Comment by bissingerz93** [comment]
Thank you Nobbz, I will try that and see how it goes. My original thought process was to type out the file path and the submit code all in one line. Because I originally went to the file location then ran $ Submit.... ect and it kept giving me errors such as submit is not a recognized internal or external command or exercism is not a recognized internal or external command.. I will try running your version of the command and Ill update with the output

**Comment by bissingerz93** [comment]
@NobbZ Thank you! I tried your solution and I was still getting the 'exercism' is not recognized as an internal or external command. So I tried going through the admin command prompt and doing the same thing and it worked!

**Comment by NobbZ** [comment]
> So I tried going through the admin command prompt and doing the same thing and it worked!

This indicates that you did not install `exercism` correctly. It should be available in your regular terminal. Please check if you have set up your `PATH` correctly.
