### ISSUE TITLE
Ruby Track - Mentors haven't replied in 5 days

### ISSUE THREAD

**Issue by Padawanguz** [exercism/exercism#4857]
I submitted a partial solution 5 days ago and yesterday I submitted my final solution and I haven't received feedback. Please let me know if I should wait a week or more before asking here. 

Ruby 5/15 (Matrix)

Thanks

**Comment by iHiD** [comment]
What is your solution id?

**Comment by Padawanguz** [comment]
A mentor just replied 2 hours ago, so I believe i can close this...?
