### ISSUE TITLE
Windows 10 - Uninstall Exercism

### ISSUE THREAD

**Issue by rustumza** [exercism/exercism#4859]
Hello.
I need to uninstall Exercism in my laptop

I cannot find the program in the list of program and I cannot find an executable to uninstall under the Exercism folder.

Also, I cannot find the instructions on the webpage.

I am using Windows 10.

Thanks a lot.

**Comment by NobbZ** [comment]
How you remove `exercism` depends on how you actually installed it in the first place.

If you did a manual installation, try `where exercism` in a terminal and delete the folder the output points you to, also remember to remove that folder from your `PATH`, thats it.

If you used `choco`, then its `choco uninstall exercism-io-cli` as far as I remember

If you used the exercism installer though, I have no clue, never used it… Perhaps @exercism/windows 
or @exercism/windows-installer do know more about it?

**Comment by rustumza** [comment]
I could do it! Thanks a lot!
- -
Guillermo Puntons

**Comment by rpottsoh** [comment]
> do know more about it

Regarding the Windows Installer.  The only altering action it takes is to add the location of the CLI, indicated by the user, to the PATH.  The installer determines for you if you need the 32/64 bit version of the CLI.  Then fetches the appropriate ZIP file from GitHub and then extracts the CLI contained within to the indicated folder.  The extracted EXE is not registered with Windows so Windows knows nothing about the CLI.  To uninstall the CLI simply delete the executable and if you like remove the associated path information from PATH.

Whether you installed manually or used the Windows Installer the removal process is the same.

**Comment by rpottsoh** [comment]
This can probably be closed.
