### ISSUE TITLE
The Pharo track needs to send out a message to its users to upgrade

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4860]
The pharo-smalltalk track is slightly unusual as it provides tools to map source code exercises stored in Exercism to a package format that can work in Pharo.

In order to cleanly support some language features that some exercises require (and to show how Pharo is comparable to Ruby or Python) we needed to change the library that does this mapping and hence need our users to upgrade the library they use when running Exercism for Pharo.

Can we please arrange send out the following message to subscribed Pharo Smalltalk users:
```
Dear Pharo Exercism user, the pharo-smalltalk track has recently needed to update the way we represent exercises in Pharo to allow us to support some new features (namely, extension methods and the ability to and run code critics on an exercise by exercise basis). 

In order to facilitate this we needed to promote exercises from being “tagged” names on a shared Exercism package, to being independent exercises in their own right. The main difference being that when you load new exercises, they will now appear as a top level package named “Exercise@<name>”. 

To accommodate this change, you will need to update the Exercism tools in your image, and these steps are described here: https://github.com/exercism/pharo-smalltalk/blob/master/docs/UPGRADE.md

This change will re-enable the Exercism menu when you right click on an “Exercise@<name>” package, allowing you to submit your solutions to our mentors. Previously completed exercises will remain unchanged, however there are also instructions for moving them over to the new package format (but it’s not really necessary).

Thank you for trying Pharo and Exercism, and happy Smalltalking…
```

**Comment by macta** [comment]
@iHiD indicated, that this is something that is possible on an adhoc basis as there isn't currently a generic way to do it.

**Comment by sshine** [comment]
@macta, @iHiD: Was this resolved?

**Comment by macta** [comment]
No - but I think at this point the moment is passed - we had a few existing users complain about their old exercises and we have pointed them to the readme docs. However it would be helpful to have functionality to email users in a track,

**Comment by iHiD** [comment]
Sorry this never got done. 

> However it would be helpful to have functionality to email users in a track. 

We will be adding a Changelog soon, where maintainers can post things to students' dashboards (also a new feature). It's currently WIP by @kntsoriano. You can track at https://github.com/exercism/wip/issues/35

**Comment by sshine** [comment]
I'm closing this issue, then, as the initial request has expired and the feature request is somewhat replaced with the track maintainer changelog; I assume that the Pharo track intends to extract such a changelog if its users don't visit the site directly.
