### ISSUE TITLE
Waiting 25+ days for mentor feedback - Typescript

### ISSUE THREAD

**Issue by JBhagat841** [exercism/exercism#4861]
Tweeted over the weekend. Waiting 25+ days for feedback on Space Age problem for Typescript track. 

https://exercism.io/my/solutions/ba8d7906337b4bf28edc3abef8f723ff

**Comment by kotp** [comment]
I am not a mentor there, but wanted to give a mentor link for your exercise @JBhagat841 

https://exercism.io/mentor/solutions/ba8d7906337b4bf28edc3abef8f723ff
