### ISSUE TITLE
Waiting close to 3 months for TypeScript track exercise feedback

### ISSUE THREAD

**Issue by paparomeo** [exercism/exercism#4867]
My List Ops TypeScript exercise has been waiting for review for close to 3 months now (submitted on the 8th of March). Is this expected? Did it fall through the cracks? I would like to progress on the track. Any help is much appreciated.

https://exercism.io/my/solutions/f958057556064e05bf01a765f8cd1cd0

**Comment by iHiD** [comment]
Sorry for your wait. I've pinged the mentors to take a look and check whether there's just a big queue or something wrong.

**Comment by paparomeo** [comment]
Thank @iHiD! And apologies for the duplicate issue. GitHub was being funny and I must have submitted twice by mistake.

**Comment by id8872** [comment]
What sort of wait time is appropriate? I'm waiting 4 days and would like to move on.
There was an irregularity on my part. I accidentally ran submit twice; would this mean that it doesn't show up on the mentors radar?

**Comment by iHiD** [comment]
@paparomeo No probs :)

@id8872 Entirely depends on the queue length at any given time. Some tracks can be a few hours, some tracks have massive backlogs and can take a couple of weeks (or sometimes even more) at the moment. Submitting twice won't have made a difference.

For both of you, you might be interested in https://exercism.io/strategy to see how we're improving things.

**Comment by id8872** [comment]
Yeah it wasn't a deliberate resubmit... just pressing repeat command twice instead of once. I was really just wondering if having more than one submit would cause a mentor to overlook the exercise and also can I delete a submission.

**Comment by iHiD** [comment]
>  I was really just wondering if having more than one submit would cause a mentor to overlook the exercise.

Yeah - it won't change anything. 

> can I delete a submission.

No, but there's open issues for this.

**Comment by id8872** [comment]
Thanks Jeremy. Appreciate your replies 👍

**Comment by SleeplessByte** [comment]
To shed some more light on what likely happened here: list ops is one of the later exercises and it doesn't have mentor notes yet. Partially because of this, it's not an easy one to mentor.

We're in the process of writing these for this specific exercise. That should steadily but slowly help alleviate these one offs.

**Comment by paparomeo** [comment]
Thanks for the clarification. It makes sense. As a mentor in other tracks I can fully appreciate this. My fear was that it had somehow got lost and wasn't in any mentor's queue. Thanks again for the prompt and insightful review @SleeplessByte that has allowed me to progress in the track.
