### ISSUE TITLE
Mentoring: Approved iterations disappearing

### ISSUE THREAD

**Issue by TeaDrivenDev** [exercism/exercism#4873]
I am a mentor on the F# track.

In the past few days, I have seen this happening several times: 

From the Mentor Dashboard, I select "Status: Completed", and from there open a specific solution. The solution - that I have previously approved (hence it shows up in "Completed") - now shows as unapproved on its details page (I get the "Leave conversation" and "Approve" buttons again), and the last iteration (that would typically be the one that made me approve it) is gone.

Most solutions seem to be intact, but this has occurred more than once.

I don't know the rules around posting mentoring solution URLs here, but I can provide an example if needed.

**Comment by iHiD** [comment]
Please provide an id.

**Comment by TeaDrivenDev** [comment]
This is the most recent one I found: 7223bf9144f64dfe91002088b10957ae

**Comment by iHiD** [comment]
Are you certain you approved it? In the database it shows up as completed but not approved - the only want I can see that happening is if the person has hit the "Complete unapproved" button (there may be other ways - but they're not obvious to me if so)

**Comment by TeaDrivenDev** [comment]
Not 100%, but fairly certain. I remember this solution because it's slightly different than most, and I'm pretty sure the student actually made that last change I suggested.

**Comment by iHiD** [comment]
OK. So there's no codeline to delete iterations from the database, so if that has happened then something pretty bad has messed up. Next time you see it can you add a solution id here, and I'll quickly trace it through the logs to understand what's happened? Thanks!

**Comment by zeckdude** [comment]
How old were the answers you were reviewing? Have you checked the `Stale` filter? I noticed that for older answers, they are put into that category, so it might be there.

**Comment by sshine** [comment]
I'm closing this issue because this appears to be an unresolved Heisenbug.

@TeaDrivenDev: Should you ever run into this again, this ticket is still available.

And should someone else report it, @iHiD will deal with it on that occasion.
