### ISSUE TITLE
No mentor has checked my answer

### ISSUE THREAD

**Issue by miteshsevani** [exercism/exercism#4874]
Hi,

I submitted my code for review a while ago, but no mentor has looked at it and therefor i can't move on.

Please advise.

Mitesh Sevani
msevani@gmail.com
Exercei: Resistor Color - https://exercism.io/my/solutions/3530a18be9c94bcb9c02fba06164c2a1

**Comment by drio** [comment]
Interesting, same issue here on the exact *same track* and *exercise*.

**Comment by iHiD** [comment]
I imagine this means that that exercise has a long queue.

**Comment by mrios22** [comment]
Is there a "mentor timeout?" After a user has been waiting for, say, five days without a response, will the site let them go forward if their code passes all of the tests?

Thank you to all of the contributors and mentors for creating a wonderful website. It's a small miracle that forums like this can exist!

**Comment by SleeplessByte** [comment]
> Is there a "mentor timeout?" After a user has been waiting for, say, five days without a response, will the site let them go forward if their code passes all of the tests?

No.

> I imagine this means that that exercise has a long queue.

It wás 8 days. Now it's back to a few hours!
