### ISSUE TITLE
Make the reviews' review load more public

### ISSUE THREAD

**Issue by iselind** [exercism/exercism#4876]
I sometimes run into the unfortunate situation where I as a student have to wait quite a bit for a review, and I'm not aware of why. This causes me to "bump" the review, asking what happens.

My Haskell mentor suggested I submit a proposal for some improvements I suggested him [here](https://exercism.io/my/solutions/a220b3ebb72e41b0ad5d330f0c26e791).

It would help if, under "Next steps", there was somehing mentioning the detail that for each bump I get pushed last in the queue.

It would help me as a student to know the reviews' review "load". For example by showing my that there are about M reviews to be processed and N mentors along with some approximation in say weeks how long it might take to get my iteration reviewed. M doesn't have to be updated to the minute of course, once a week or daily event might be sufficient.

Just some friendly suggestions from my end as a student.

**Comment by ydrecords** [comment]
(similar to #4787)

**Comment by iselind** [comment]
Covered by #4787, closing
