### ISSUE TITLE
Independent Mode: Student cannot find problem where they requested feedback

### ISSUE THREAD

**Issue by ZacharyRSmith** [exercism/exercism#4878]
Also, in the Java track I requested feedback for Yacht.  After receiving feedback there, I'm unable to request feedback for another problem because

```
Request mentor feedback (disabled). Mentoring is disabled by default in Independent Mode. However, you can request feedback on a maximum of one solution at a time. You currently have no slots free.
```

It seems as if a request was automatically submitted for me for another problem?  If I could see where I "requested" feedback, then I could un-request for that problem in order to request for the problem I really want feedback on.

**Comment by iHiD** [comment]
Did you mark "Yacht" as completed? What's your handle?

**Comment by ZacharyRSmith** [comment]
@iHiD thanks for checking.  I can now request feedback.  Maybe I was blocked because my mentor needed to mark my problem as complete?

**Comment by iHiD** [comment]
No probs. Your mentor will approve when they're happen, then you can complete it. Once it's completed you can request another one.

Have fun :)

**Comment by ZacharyRSmith** [comment]
Could it be that I marked it complete, then I had to wait for the mentor to approve it?
