### ISSUE TITLE
Not all non-core exercises are unlocked

### ISSUE THREAD

**Issue by wolf99** [exercism/exercism#4881]
On the Java track (unaware if this affects other tracks), according to the config.json, some exercises should be unlocked by completing linked-list, but they are not (in fact they should be all unlocked by that stage as it appears to be the last core exercise).
e.g. diffie-hellman

https://github.com/exercism/java/blob/c5132d3a955556699c1e8e353c085039d1c3b619/config.json#L1264

linked-list completed
![image](https://user-images.githubusercontent.com/281700/59052549-3dc82480-8887-11e9-8321-be88c1ca6b5f.png)

But remaining non-core exercises not unlocked:
![image](https://user-images.githubusercontent.com/281700/59052857-f8582700-8887-11e9-82c6-e87df4bc64c3.png)

These exercises were **not** added later, after the time that the track was completed, screenshots above were taken immediately after finishing core exercises. So is not a duplicate of https://github.com/exercism/exercism/issues/4180

Unsure why this would occur?

(Had raised this on the Java track initially, but redirected here. https://github.com/exercism/java/issues/1695)

**Comment by iHiD** [comment]
You completed it "unmentored" so it doesn't unlock the side exercises as per the warning that comes up.

**Comment by zeckdude** [comment]
@iHiD Why is that setup like that? Are we trying to push people to use the mentorship version?

**Comment by iHiD** [comment]
If you're in mentored mode, yes. Otherwise the mentors have to deal with students who are not ready for more complex exercises, and then the mentoring takes loads longer and the queues get big, and mentors quit and it all becomes bad :)

If you don't want the mentored version, you can use Independent Mode, where there are no restrictions.

**Comment by wolf99** [comment]
FYI, initially I did wait for mentor comments on exercises, but they never came. So I moved on myself.
