### ISSUE TITLE
Bug in elisp track

### ISSUE THREAD

**Issue by EmilienMottet** [exercism/exercism#4882]
I have a bug on my emacs lisp track.

The exercise Bob is present 2 times. And second time, I can't interact with. The webpage seem bug. And I can't download the exercise

```
exercism download --exercise=bob-0aa89e85-c923-4f46-8474-62105dd99f42 --track=elisp
Error: unable to parse API response - invalid character '<' looking for beginning of value
```

![image](https://user-images.githubusercontent.com/15970369/59056302-29405800-8898-11e9-8c48-01694e8ec207.png)
![image](https://user-images.githubusercontent.com/15970369/59056326-35c4b080-8898-11e9-915e-d32ce0c34c9f.png)

**Comment by iHiD** [comment]
Thank you for raising this. A mistake was [made in a commit](https://github.com/exercism/elisp/commit/62075c8884e55c362de10a717bfae2bd45361ea9#diff-06b2d3b23dce96e1619d2b53d6c947ecR29) that has duplicated bob. @benreyn has just [fixed this}(https://github.com/exercism/elisp/commit/0212d6e09b0cc1455da525707b9568cb748185e0#diff-06b2d3b23dce96e1619d2b53d6c947ec) but it remains in the database. However it should now appear at the bottom of your track and not block you. Please could you upload another screenshot to confirm? 

Thank you.

**Comment by EmilienMottet** [comment]
It's ok now thanks !

**Comment by iHiD** [comment]
Great. Would you mind posting a screenshot so I can understand how it looks for please?

**Comment by EmilienMottet** [comment]
![image](https://user-images.githubusercontent.com/15970369/59103884-5b9d9400-8930-11e9-8667-57ae0e34f2bc.png)

**Comment by iHiD** [comment]
Great. Thanks :)
