### ISSUE TITLE
Dont see solution after submit

### ISSUE THREAD

**Issue by nevgin** [exercism/exercism#4889]
I am submit solution. Don't see in web interface.
➜  isogram exercism submit isogram.go
    Your solution has been submitted successfully.
    View it at:
    https://exercism.io/my/solutions/5d423707bd3d4124aa4d9b350c64dbef
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.11
Latest:  3.0.11

Operating System
----------------
OS:           linux
Architecture: amd64

Configuration
----------------
Home:      /home/anevgin
Workspace: /home/anevgin/exercism
Config:    /home/anevgin/.config/exercism
API key:   7007*****************************21e

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 452.822514ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 437.237056ms

**Comment by iHiD** [comment]
Could you try again now pls? We had some server issues about the time you reported this and I think that may have caused this.

**Comment by nevgin** [comment]
Thanks. All right. It is work.
