### ISSUE TITLE
Replacement exercise locked after current exercise moved out of core track

### ISSUE THREAD

**Issue by BeckaL** [exercism/exercism#4894]
I was completing the last exercise on the Scala core track, when this exercise was moved out of the core track and into side exercises, and replaced by a new final exercise. This new final exercise is locked to me, even though I have completed the previous exercise on the track. I therefore currently cannot complete the core track.

**Comment by BeckaL** [comment]
Resolved now

**Comment by iHiD** [comment]
Great. I just ran a script to sort it. Thanks for letting me know :)

**Comment by iHiD** [comment]
@exercism/scala Friendly reminder to let me know if you change the track around so I can run my magic script :)
