### ISSUE TITLE
C++ Circular Buffer locked despite having completed all track exercises

### ISSUE THREAD

**Issue by mstange22** [exercism/exercism#4896]
Subject pretty much says it all.  I completed the C++ track quite a while ago and I've seen that new side exercises have been added from time to time.  Was working on a few today and just realized that Circular Buffer is locked.

**Comment by iHiD** [comment]
I've set off a script that should fix this. It takes a few hours to complete as it check's everyone's trees. Please recheck and let me know if it's still an issue a few hours from now. Thanks.

**Comment by mstange22** [comment]
Fixed!  Thanks!

**Comment by iHiD** [comment]
Great :)

**Comment by iHiD** [comment]
Reminder to @exercism/cpp to tell me if you reorder or add new exercises so I can run this script :)

**Comment by patricksjackson** [comment]
Oops, my mistake. I thought it was only needed when the track was reordered.

@iHiD do you happen to have a link to discussion of that script/tool? I clearly missed it entirely, maybe I'm not watching the right places.

**Comment by iHiD** [comment]
> Do you happen to have a link to discussion of that script/tool

No. Because it shouldn't need to exist - so I've not documented it in the hope it will cease to exist soon :) But I've not yet worked out a way to automate things so that it can change. It'll come in the next couple of months, but until then, just ping me and I'll run it.

This is definitely my fault not yours :)

**Comment by patricksjackson** [comment]
Thanks!

**Comment by mstange22** [comment]
Hi guys, I can't access the new C++ exercise Collatz Conjecture.  Might need to re-run the script?

**Comment by iHiD** [comment]
@mstange22  It should be run now.

**Comment by mstange22** [comment]
Confirmed, thanks!
