### ISSUE TITLE
Unable to download exercise or connect to exercism via CLI

### ISSUE THREAD

**Issue by vfopersonal** [exercism/exercism#4897]
Hi everyone,

I'm trying to install Exercism in a Windows 10 machine but getting some errors.

When I tried to configure it for the first time I was getting an error saying I could not connect to the exercism server. I tried changing the timeout settings and decided to use the parameter to not check my registration to the server.

Now I can see that it's configured with my token (without validation), but now when I try to download the exercise, I get the following error:

C:\WINDOWS\system32>exercism download --exercise=pangram --track=python
Error: Get https://api.exercism.io/v1/solutions/latest?exercise_id=pangram&track_id=python: proxyconnect tcp: dial tcp 10.67.5.142:3128: connectex: No connection could be made because the target machine actively refused it.

When I run exercism debug, I get the following information:

C:\WINDOWS\system32>exercism debug

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.11
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: proxyconnect tcp: dial tcp 10.67.5.142:3128: connectex: No connection could be made because the target machine actively refused it.

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\Vinicius
Workspace: C:\Users\Vinicius\Exercism
Config:    C:\Users\Vinicius\AppData\Roaming\exercism
API key:   ee70*****************************9ec

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: proxyconnect tcp: dial tcp 10.67.5.142:3128: connectex: No connection could be made because the target machine actively refused it.]
    * 1.0186153s

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: proxyconnect tcp: dial tcp 10.67.5.142:3128: connectex: No connection could be made because the target machine actively refused it.]
    * 1.0186153s

If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.

Some troubleshooting that I tried:

Accessing the link below, I can get the server API status.
https://api.exercism.io/v1/ping
status	
website		true
database	true

I disabled the local firewall and included the exercism.exe into the firewall list to allow the application and I still can't connect to the server using CLI.

Another test to check if it was firewall or connectivity issue, I installed a Linux guest into VirtualBox and tried to install and configure Exercism and it worked fine, but I'd prefer using exercism in my windows machine and not into a VM.

Does anyone have any idea what could be this connectivity issue?

Best regards.

**Comment by NobbZ** [comment]
This looks as if you have set up a proxy, please check `HTTP_PROXY` and `HTTPS_PROXY` environment variables for correctnes.

**Comment by vfopersonal** [comment]
Hey NobbZ,

thank you for your reply, but I also verified that and there's no proxy configured. I even tried to run the netsh commands:

netsh winhttp reset proxy
netsh winhttp show proxy

The weird thing that I mentioned is that I can connect to the server from a linux guest installed in my virtualbox environment.

Regards,

**Comment by vfopersonal** [comment]
Reinstalled windows and now it's working fine. Thanks.
