### ISSUE TITLE
Teams Edition Exercises Missing Full Descriptions

### ISSUE THREAD

**Issue by MattCooke** [exercism/exercism#4900]
Most of the exercises are missing full descriptions within the exercise landing pages in comparison to the personal edition. It would be nice to have the full descriptions and suggestions for each exercise to help programmers with weaker skill levels. See images to see an example difference in descriptions.
![Screenshot from 2019-06-18 09-53-34](https://user-images.githubusercontent.com/10872696/59695086-40901700-91af-11e9-804a-065749fe3e4c.png)
![Screenshot from 2019-06-18 09-55-22](https://user-images.githubusercontent.com/10872696/59695102-471e8e80-91af-11e9-9b27-2d4605927905.png)

**Comment by rpottsoh** [comment]
The track specific information is not displayed.  Looks like only an exercise's description.md is being shown.

**Comment by MattCooke** [comment]
here is a better example. If you look at the hello world exercise, the team edition doesn't have the tips, doesn't have the running test information. It also doesn't have the links to install java and link to useful resources. Plus I would suggest renaming the "Been Here Before?" to the same as the personal edition of "Download".
![Screenshot from 2019-06-18 10-52-42](https://user-images.githubusercontent.com/10872696/59699836-dd56b280-91b7-11e9-8335-b18610c9e206.png)
![Screenshot from 2019-06-18 10-53-24](https://user-images.githubusercontent.com/10872696/59699849-e3e52a00-91b7-11e9-97c0-e0d7b10a0a15.png)

**Comment by MattCooke** [comment]
This is the same for every exercise I have looked at so far. I think for new users and programmers with weaker backgrounds, would benefit from all of the extra information.

**Comment by rpottsoh** [comment]
The track specific information is probably not displayed because in Teams you are not on a specific track at this particular place on the site.  However, from what I can see displayed on the screen the site appears to know which language, it says "Hello World in Java" after all.  So it would seem possible for the track specific information that is normally displayed with the README should be displayed here as well.

It is either a bug or I'm sure @iHiD has a logical explanation on how to find the missing information.

**Comment by iHiD** [comment]
Thanks. This should be fixed by https://github.com/exercism/website/pull/648 - I'll merge/deploy once it's through CI, then would appreciate you confirming it looks sensible to you. Thanks :)

**Comment by MattCooke** [comment]
It looks good. Thank you so much for the quick response on this. I have 20 kids I need to get practicing on java programming. This will help a bunch!!!!

**Comment by iHiD** [comment]
Great!! Enjoy and feel free to open any more issues if you find them :)
