### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4909]
We are going to be adding a bit more internal project management to Exercism to help us better utilize the people we have working on things. The most immediate way this will effect people is that we are splitting out this repository (exercism/exercism) into a variety of other repositories that we can work through. This will allow us to have better fine-grained control over how we manage things, with the ability to have different people managing different repositories, and  be able to create scripts that work within those spaces. 

We will use continue to use exercism/exercism as the sole place people should be opening issues, but will then triage to four new repositories:
- **[Support](https://github.com/exercism/support):** A repository for support requests. Over the next few months, we are intending to eliminate this altogether and move support to within Exercism, but for now we will have a dedicated repository for it.
- **[Bugs](https://github.com/exercism/bugs):** We will move genuine bugs to this repository. Our aim is to fix anything that's broken as a priority, and so keep this repository as close to zero as possible.
- **[Backlog](https://github.com/exercism/backlog):** Our backlog of new features and improvements will go here. We will then attempt to provide realistic information on how likely something is to get done, and how much of a priority it is.
- **[WIP](https://github.com/exercism/wip):** The WIP (Work in progress) space is everything that's on our current short-term (6month) roadmap. This will be the project-management space that our team live in most day-to-day, and will have a mixture of small standalone issues and also larger "project" issues, which might then be broken into their own short-term repositories.
- **[Discussions](https://github.com/exercism/discussions):** This will be a place for discussions about what we might want to change to Exercism, or ideas that aren't specific things that can be written as features and added to a backlog. The conclusion of a discussion might be to add an issue to **exercism/backlog**.
- **[Ideas](https://github.com/exercism/ideas):** This space is used to store ideas that people suggest. These can then be fleshed out by the product team and moved into **backlog** or **wip**.

All issues should be created in this repository (exercism/exercism) and will then be triaged once their status becomes understood. This repository should itself therefore stay close to zero open issues.

**Comment by mrtank** [comment]
I like that we comply to [Joel test](https://dev.to/checkgit/the-joel-test-20-years-later-1kjk) num. 5

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
