### ISSUE TITLE
I'm Learning Python The Hard Way Ex 25 and I have the issue below on comment section. Provided the code where the is to be located at

### ISSUE THREAD

**Issue by LupJose** [exercism/exercism#4930]
I have tried everything. I'm in the right dir. I have checked the area of code error and I have no idea why I'm getting an error message. Please help anyone!!!!!
 import ex25
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jge/lpthw/ex25.py", line 1
    def break_words(stuff):
    ^
IndentationError: unexpected indent

    def break_words(stuff):
        """This function will break up words for us."""
        words = stuff.split()
        return words

**Comment by LupJose** [comment]
Here is my file

**Comment by LupJose** [comment]
Sorry, I was not able to download the file
 Here is all my code on the exercise 25
    def break_words(stuff):
        """This function will break up words for us."""
        words = stuff.split()
        return words

    def sort_words(words):
        """Sort the words."""
        return sorted(words)

    def print_last_word(words):
        """Prints the last word after popping it off."""
        word = words.pop(-1)
        print(word)

    def sort_sentence(sentence):
        """Takes in a full sentence and returns the sorted words."""
        words = break_words(sentence)
        return sort_words(words)

    def print_first_and_last(sentence):
        """Prints the first and last words of the sentence."""
        words = break_words(sentence)
        print_first_word(words)
        print_last_word(words)

    def print_first_and_last_sorted(sentence):
        """Sorts the words then prints the first and last one."""
        words = sort_sentence(sentence)
        print_first_word(words)
        print_last_word(words)

**Comment by NobbZ** [comment]
Hello @LupJose!

I'm not sure whether or not you have fixed your problem.

You closed the issue, but then posted even more code.

Also I'm not sure which exercise you are talking about. On exercism exercises are not numbered but named. And the core track, which has to be done in order, has only 18 exercises (if I counted correctly).

**Comment by LupJose** [comment]
Sorry, I did fixed my issue. This was the first time I posted on exercism. Thanks for getting back to me

Jose
