### ISSUE TITLE
Mentor feedback Rust Track

### ISSUE THREAD

**Issue by hallodaniel** [exercism/exercism#4931]
Hi, 
it's great that you added info about the mentor queue! 

I'm stuck on the atbash cipher exercise for over two weeks now, awaiting mentor feedback, and the number of solutions ahead of me in the Rust queue is going up! I don't think this should happen in a FIFO queue?!?

https://exercism.io/my/solutions/89ea88740b7241c2a382cf74e720a9f8

Thanks

**Comment by iHiD** [comment]
Hello. I've been off tech for 2 weeks so sorry for the slow response.

>  I don't think this should happen in a FIFO queue?

It's not a strict FIFO queue - it's algorithmic but generally FIFO. That said, while I'd expect you to notice a few new exercises occasionally jumping you, I wouldn't expect a lot. Has this continued to be a problem since you opened this issue?

**Comment by hallodaniel** [comment]
Hi, thanks for your reply!

I do not know how mentors work on the queue, the number of solutions in the Rust track ahead of mine goes up and down, no clear trend. The number of solutions ahead of mine for this particular exercise has been alternating between 0 and 1 in the last week or so.

All in all it has been 30+ days now, maybe people are on vacation.

**Comment by dustypaws** [comment]
> There are currently 34 solutions ahead of this in the Rust queue, and 28 ahead in the Bob queue. The median waiting time for mentoring on this exercise is 14 days. Learn more about how mentor queues work. 

I don't really know how that is justified (even for a free service). If I have to wait approx. 14 days per solution, the whole Rust track would take 30 weeks to complete. I bet it's hard to find mentors, but then again, that's the whole idea behind the website. Automated test suites á la codewars already exist.
I don't want to be negative here, I really like exercism and the idea behind it. An I would gladly mentor if I was feeling up to the task (...I'm not...) But 14 days avg. time to catch a mentor is ridiculous. (No hard feelings really, just needed to get this out of my system. :) )

**Comment by iHiD** [comment]
> I don't really know how that is justified

I don't understand how something can be "justified" on a free service. If no-one volunteers to mentor, then no-one mentors you. It's pretty straightforward.

>  But 14 days avg. time to catch a mentor is ridiculous. 
> No hard feelings really, just needed to get this out of my system. :) 

You're not being constructive or helpful, or particular considerate that thousands of people submit solutions to exercism every day, and that mentors are giving up their time for **absolutely no reason other than being nice people** It's not ridiculous that it takes 14 days, it's wonderful that someone is willing to help you in the first place.

I'm not sure that that ranting helps or encourages people to give **more** of their free time to help other people.

> Automated test suites á la codewars already exist.

Then go enjoy codewars. Or use Independent Mode on Exercism where you don't have to wait for mentors.

**Comment by dustypaws** [comment]
Good luck! :) 👋

**Comment by iHiD** [comment]
Thank you. 

Should you be interested in what we're doing to improve this, you might want to read https://exercism.io/strategy - for tracks where things like Track Anatomy and Automatic Mentoring are applied, we have wait times of only a few hours now.

Also, Rust is down from 4 months to 14 days, which I think is a great improvement.

**Comment by dustypaws** [comment]
> You're not being constructive or helpful, or particular considerate that thousands of people submit solutions to exercism every day, and that mentors are giving up their time for absolutely no reason other than being nice people. 

No, No and No. 
1) I don't know how this is going to be fixed, nor do I have an idea. I guess it will involve money.
2) I'm learning on one of your tracks, you want me to solve problems scaling to the demand?
3) I know that there's no payment, it's their decision and the model the exercism team came up with to drive their site.

Criticism doesn't always have to be constructive or helpful, sometimes criticism itself is just an indicator. Don't expect your users just to shut up and take it just because they don't have a CompSci degree and have the solution to a problem they didn't create.

> Also, Rust is down from 4 months to 14 days, which I think is a great improvement.

In sheer numbers it is, but for a  coherent learning experience the gap between lessons is just too big.

Anyhow, I wish you and your team all the best. #noSarcasm

**Comment by iHiD** [comment]
> Criticism doesn't always have to be constructive or helpful, sometimes criticism itself is just an indicator. 

Sure. Trust me when I say we get enough criticism to know this is a problem. 

Imagine spending years of your life building something, and spending tens of thousands of pounds of your money to fund something, for literally no purpose other than to help people, and then having people just turn up and randomly criticise you. Can you imagine how that makes me, and others, feel, and how utterly demotivating it is?

> No hard feelings really, just needed to get this out of my system

You didn't **need** to get it out of your system. You were frustrated so decided to spoil other people's days by criticising their hard work, with no constructive comments, or reference to all the things they're already doing to try and fix it.

> Anyhow, I wish you and your team all the best. #noSarcasm

I appreciate this. I genuinely do. But I would respectfully suggest that in future, you consider that you're talking to real people with real emotions, who put their time, money, and hearts on the line to try and make the world a tiny bit better, and who are affected by the your words.

**Comment by iHiD** [comment]
@hallodaniel It looks like your solution got some mentoring so I'm closing this now. Thanks for reaching out.
