### ISSUE TITLE
automatic mentor dashboard: Redundant C language filter

### ISSUE THREAD

**Issue by ZapAnton** [exercism/exercism#4933]
The track filter form at the [auto-mentor dashboard](https://exercism.io/mentor/analyses) contains a redundant C language item, that does nothing and does not correspond to the C track analyzer, since, to my knowledge, there is none.

Not a critical bug, but I felt like a small report would be appropriate

**Comment by iHiD** [comment]
@ZapAnton Nice spot. Thanks :)
