### ISSUE TITLE
install automation?

### ISSUE THREAD

**Issue by marcinkubica** [exercism/exercism#4938]
Hi
Just found your website and downloaded linux cli for python.
Why no install automation?

Happy to kick it off, if you think it would have a value.

Best
Marcin

**Comment by guygastineau** [comment]
If you mean, 'why don't we have something users can `curl` and `|` to `sh`' I think it is beacauseusers might want to install it in their preferred way.

The manual instructions say to out the cli executable in `~/bin`. Then they instruct the user to add that to their path if it is not already.  What about systems where this isn't set up yet?

We could have a script that makes `~/bin` if not present.  It could also check the path and add it in the `.profile` or `.bash_profile` or whatever zsh uses or whatever fish uses (even whatever csh, tcsh, rc, es shell, ion uses).

I think it is best if we keep our mits off of other people's system setup.  I could want the executable in `~/.local/bin` or any number of other custom setups.

I might be persuaded that an install script that does these intrusive things is a good default option (so long as we can still install manually without relinquishing control of our resource files), but I also think that it is a some enough install process that it shouldn't be obfuscated.

It sounds like you know what you are doing, so I assume it wasn't confusing (maybe just a mild inconvenience).  Some students are much less experienced.  While an install script would lessen the barrier to entry it also would take away an opportunity for them to learn more about how their computer works/is set up.

If people disagree, then please feel free to say so.  I have simply thought about this a lot, so I figured I would add my thoughts.

**Comment by marcinkubica** [comment]
Hi

I only asked because I feel presenting new (and also maybe old) developers
with manual steps to install their stuff develops bad habits. Software
should never be deployed by hand in my opinion. Just never. Also installers
on linux aren't anything new (not need to be scripts, they also come as
bins). Also, there's no reason installer has to be intrusive. In fact
requiring root privileges here is another bad thing to ask for.

Surely, the manual steps should still remain, so people would know "the
runbook", but I have doubts this will significantly upskill anyone new.
They would normally take a linux course.

Best
M.

**Comment by guygastineau** [comment]
Thank you for your reply😀. You don't need to justify your question; it is completely valid ❤️

I suppose I tend to use words with strong connotations like `intrusive`.  Probably what is intrusive for me is not intrusive for others.  I do mean it strongly though.

I have very concise, customized run control files, so I have an OCD, keep-your-hands-off attitude about them when it comes to scripts from third parties.

To be honest, if an installer just automates the recommended manual installation steps, then it isn't different than manual installation.  The package manager certainly has no idea that it is there.

Whether this gets picked up as a feature is not my call, but here are some considerations that should be decided before implementation:
- order of preference for the install path.
- what to do if no preferred install path is present.
- whether to add to `$PATH` if necessary (, or it could just print a message telling the user to prepend their path).

**Comment by guygastineau** [comment]
PS. An installation script is always preferable to a binary installer. We should not encourage people to run system altering code they cannot review.

**Comment by sshine** [comment]
Hi @marcinkubica. I'm closing this issue because it seems unfeasible:

With 51 language tracks and no detailed knowledge of the operating system of users, the amount of combinations required is explosive. Also, typically, programming environments are not unambiguous: Students may freely choose their editor, and some languages even have competing compilers / interpreters. While the track documentation for getting started provides opinionated hints, they also provide an entry-point into that particular niche of programming tools.

If there is a particular track that you like on Exercism, and you think their installation instructions should refer to particularly useful installers for various mainstream operating systems, I would encourage you to submit an issue or PR to that language track.

Have a nice day!

**Comment by iHiD** [comment]
To build on what @sshine (rightly) says, we will be adding in-browser coding support in the next few months, and tracks will have the opportunity to opt-into that. So hopefully that will make it easier to get started on new tracks without having to commit to installing all the tools, etc.
