### ISSUE TITLE
Ranking algorithm

### ISSUE THREAD

**Issue by RafaelFigueiredo** [exercism/exercism#4940]
Hello community,
I am stuck in a golang queue exercise for 12 day and counting... and I read and other issues that this is recurrent problem.
My position on queue grows and reduce, and grows again, its not good be incapable of do a estimative of when I will be mentoring.
So my question for who is reading that issue: 
**The position in queue is real or is bugged?**

p.s.: i love to study in exercism, thanks.

**Comment by tehsphinx** [comment]
@ihid For when you get back. Have heard this a few times now from students.

**Comment by NobbZ** [comment]
I assigned @iHiD, as assigned issues are easier to track then just mentions.

Anyway, currently the only factor that plays into the queue position is the age of the submission.

Also beeing first, doesn't mean one is next. Mentors might still decide to do another one of the 25 visible exercises for any reason they like.

You should see an estimate after how much time you usually get reviewed. If that estimate is missing, then there was no mentoring of that exercise during the last 4 weeks. Please share your UUID in that case (the random looking part of your submissions URL).

**Comment by tehsphinx** [comment]
@NobbZ This is about the **ranking fluctuating up and down**. Going up should be a very rare exception if:
- A mentor timed out and the solution went back into the queue
- A student becomes active again and the solutions reappear in the queue
- (other cases)

I have heard from a few students now, that their position in the queue is going up and down all the time.

**Comment by tehsphinx** [comment]
@RafaelFigueiredo maybe we can simplify the issue description. I'd remove the whole `wainting experience` part and focus solely on the **queue position going up**. Best include samples with track/exercise, date/time, queue position.

**Comment by RafaelFigueiredo** [comment]
> @RafaelFigueiredo can you simplify the issue description. I'd remove the whole `wainting experience` part and focus solely on the **queue position going up**. Best include samples with track/exercise, date/time, queue position.

Issue edited to simplify, about samples I will track the progression in queue and take note

**Comment by iHiD** [comment]
I could do with some real data on this. Solution UUID and the stated positions at different times. (ie, what is it now, what was it a few weeks ago). Without that, it's pretty impossible to debug.

If it's happening to lots of people hopefully someone can provide this and then I can dig in.

**Comment by guygastineau** [comment]
I don't remember the stats exactly, but in the Haskell track I went from having an exercise in the second position to the right and then ultimately to the 20-somethingth position.

I assumed it was because a mentor times out on a bunch of students, because they are very low on mentors (also someone might have left).  To be clear, I never saw my solution jump back to the top.  It just got handled within a reasonable time after the queue grew in front of it.

Hopefully this is somewhat helpful.  Additional clarity - I think my case was not a bug.
