### ISSUE TITLE
Run tests prior to submission through CLI

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4941]
In #4936 I said in a comment (https://github.com/exercism/exercism/issues/4936#issuecomment-512671241) that I had an idea how to solve this when beeing offline, and I promised to form a proper proposal around it:

----

The current situation is (especially in the early exercises) that students obviously didn't run the tests locally (eg. `two-fer` that asks for user input or `hello-world` just printing to `stdout`).

This puts a lot of work to the mentors to explain to the student how to actually run the tests and in worst cases might lead to minimal effort mentoring like "please run tests, see <link>".

To avoid this extra burden on mentors, I propose to extend the exercism API and the CLI, to enable students to run tests through CLI and submit the test output along with the tests exit code.

The proposed syntax is `exercism submit $file […] --with-tests="run test command"`

The CLI will then run the argument to `--with-tests` flag and capture the output and check the exit code. Output is also redirected to terminal for students verification.

If the exitcode is non-zero, the CLI will ask to submit anyway. `--force` can be provided on the terminal to submit without user interaction even on failing tests, to enable students to easily submit on questions.

Omitting `--with-test` will explain the situation to the student and link to the tracks "running the tests" documentation. `--force` can be used to surpress the warning and submit anyway.

I'm aware of the fact that this would mean also implementation work on the server, not only client.

**Comment by Tom01098** [comment]
I think `--force` needs to be emphasised to the user as a way to submit code when they are stuck and not as a way to skip a problem.

**Comment by iHiD** [comment]
Thanks @NobbZ. We're planning to do server-side running of tests in August. We could then feedback to the user that the tests have failed and they should try again. If we did this, would we still need this proposal do you think?

**Comment by NobbZ** [comment]
Already in August? Thats nice!

Even though I think, that pushing the student to run them locally and to make him understand how the tests are run locally will teach them more about their languages tooling, my proposal would obfuscate the CLI interface even more and some students are already struggling with it today…

But also students do submit without running the tests usually only for `hello-world` and the follow-up, so the mentors can pick up the exercises early and tell the students about local test runs if necessary.

So if mentors will be able to see tests output and students will be able to submit solutions that do not pass the tests (or revoke them from mentoring if they realize their error), then I think remote running is a valid replacement for my proposal, but only if it will be available for all tracks (within reasonable time).

**Comment by sshine** [comment]
@iHiD: Since we're in September and you said August, what is the coverage now?

@NobbZ: If only some tracks got server-side test runners, would it not simply be status quo for the remaining tracks? Are you saying that you think forced client-side test runners require lower effort?

Forcing someone to run tests when they expect to submit is an annoying default. A less annoying default is alike a commit hook that denies submission until the local test runner has run at least once; but making this integration with the test tools of all tracks is also high-effort.

If we went with both, it should be possible to disable client-side test running ad-hoc as server-side test runners are added to tracks, without needing to update the CLI.

**Comment by iHiD** [comment]
> If we went with both 

We'll be going with server-side testing.

> Since we're in September and you said August, what is the coverage now?

You can see in-progress test-runners [here](https://github.com/exercism?utf8=%E2%9C%93&q=test-runner&type=&language=).

I'm just deployed an [(early) prototype on in-browser coding](https://github.com/exercism/website/pull/722), which is our initial integration point with the the test-runners. There are still issues to work through about running user-submitted code, which we are working on. Once we're happy with that we'll integrate it with iterations too (this will be a small amount of work - a day or so).

The main bulk of what @ccare is doing atm is giving maintainers the ability to ship updates to analyzers and test-runners without coming to him to do manually. We're getting this right first before we launch it as a feature.

It's in progress though, and is the main thing that Charles and I are both working on atm.

**Comment by sshine** [comment]
> We'll be going with server-side testing.

Then I can close both this one and #4746. :-)
