### ISSUE TITLE
Mentor feedback F# track

### ISSUE THREAD

**Issue by mastertheef** [exercism/exercism#4942]
Hello,

Not sure if this is the right place to ask such question but.
I am awaiting for mentor feedback for 3 days already. I am really excited about your site and I was very pleased when mentor replied to me in one day. But I want to continue my F# journey and nobody reviewing my solution. Am I doing smth wrong?
Here is the link 
https://exercism.io/my/solutions/23599e61b55549c4ac709d78fdb59de0

Thanks in advance,
Mykola

**Comment by iHiD** [comment]
Hello. Sorry for the slow response. Is this still an issue for you?

**Comment by mastertheef** [comment]
Hello. Mentor already commented and approved my solution. Thank you.
