### ISSUE TITLE
Accidentally chose independent mode, cannot go back to mentored mode

### ISSUE THREAD

**Issue by lightyear15** [exercism/exercism#4944]
I have read there has been some debate on giving the possibility to switch between mentored and independent mode. ( #3985 )
I can't understand though if this has become a bug or not, if the bug has been fixed or still under work; or if this is not a bug at all but a desired behaviour.
Thanks

**Comment by iHiD** [comment]
Hello. Could you explain what the actual problem you're facing is please?  When can you not go to mentored mode? Have you hit an error message etc? Thanks :)

**Comment by reifnotreef** [comment]
I'm having the same issue.
There is no option to return to mentored mode.

**Comment by lightyear15** [comment]
> 
> 
> Hello. Could you explain what the actual problem you're facing is please? When can you not go to mentored mode? Have you hit an error message etc? Thanks :)

When asked, I chose Independent mode. And now I can't find a way to change it back to mentored mode, no error message at all, simply I can't see any button or option or setting where I can change it.

**Comment by iHiD** [comment]
<img width="342" alt="Screenshot 2019-07-25 at 12 09 30" src="https://user-images.githubusercontent.com/286476/61870078-17ad2100-aed5-11e9-8d1c-b7f7f4fec41b.png">

There should be these buttons at the bottom of the track page. Are they there for you?

**Comment by lightyear15** [comment]
Oh jee...
I feel a complete idiot...
Closing the issue

**Comment by iHiD** [comment]
Don't feel an idiot - the UI obviously isn't clear enough :)

**Comment by reifnotreef** [comment]
@lightyear15 Oh man, I'm right there with you!
We just didn't scroll enough!

Thanks @iHiD
