### ISSUE TITLE
UI with mentor/mentee can be like creating a new pull request

### ISSUE THREAD

**Issue by dgiridharan** [exercism/exercism#4945]
It would be really amazing if we could change the UI of the Mentor/Mentee interaction. I think the existing is fine and it serves the purpose, however, it would be even better it can emulate of how a pull request is created.

For instance, it would be great if a Mentor/Mentee can leave inline comments, and categorize as:
1) Bug
2) Improvement
3) Comment

Also, it would be great if the mentee can mark something as resolved/read/unread. An example of this would be when creating a pull request through github:
![codecommit-pull-request-comment](https://user-images.githubusercontent.com/1533894/61600370-1fbf4500-abe5-11e9-821d-6bf370b71d28.png)

Or when creating a new review through code collaborator:
![aRAyP](https://user-images.githubusercontent.com/1533894/61600381-2bab0700-abe5-11e9-99ff-2b46f0a3845b.png)

P.S. I really think your product is awesome and I really love it!

**Comment by iHiD** [comment]
We will definitely eventually do this, but as you can imagine, it would be quite a lot of work, so you might have to be patient for a while :)

Thanks for the support and I'm glad you're enjoying Exercism!
