### ISSUE TITLE
Idea: Side exercise chains

### ISSUE THREAD

**Issue by Bubbler-4** [exercism/exercism#4946]
This is an idea from exercism/coq#6:

> Could it be possible to have such chains where the first quest in the chain is unlocked by reaching some point in the main quest line, but subsequent quests are unlocked by progressing through that particular chain?

It could be useful in several ways:

* Build a medium-sized project across multiple exercises.
  * In Coq, develop a complete theory on a small topic. (It often spans 100+ lines in Coq, so it's particularly challenging to find a topic that fits in just *one* exercise.)
* Organize exercises in a particular topic ordered by increasing difficulty, e.g. mathematics.

**Comment by F3PiX** [comment]
Hi Bubbler-4 . I can see how this could help, in other tracks too. 
This has been discussed previously, with regard to the [Track Anatomy Project](https://exercism.io/blog/track-anatomy-project). Currently, side exercises can't unlock other exercises, only core exercises can. And as I understand it, it's not an easy change. 

In the Track Anatomy Project, there are similar reasons for 'themes'. I'm experimenting with something called 'named paths', where exercises are related by a common theme. It is not exactly what you're looking for, but in combination with the implementation of levels (which is also experimental in the Ruby track), but it's coming close(r) - and meant to solve similar challenges as the ones you named.  

A named path could be something abstract like the Mathematics theme you mentioned, but also a series of exercises that build upon each other (see another experiment: Resistor series: https://github.com/exercism/problem-specifications/issues/1458). 

I'd love to discuss the Named Path concept with you, to see if it would be a useful addition in the coq track.

**Comment by iHiD** [comment]
I'm going to close this as @F3PiX has outlined where we currently stand. I love the idea, but it's too much work for the next 12 months.

@Bubbler-4 You might like to reach out to @F3PiX on Slack (she's `@Maud` there) to discuss the Track Anatomy Project with her :)
