### ISSUE TITLE
PHP track extra exercises unavailable

### ISSUE THREAD

**Issue by goodevilgenius** [exercism/exercism#4949]
A few issues related to extra exercises, primarily in the PHP track.

- On the PHP track, there are no extra exercises unlocked when a main exercise is completed.
- All extras for PHP are listed as unlocked.
- When clicking on any of the extras, it goes to my solutions page, rather than the exercise page.

A little more info on the last point:

All the exercises link to a URL like: https://exercism.io/my/solutions?exercise_id=word-count&track_id=php. This goes to the "My Solutions" page, rather than the page for the given exercise.

In other tracks, unlocked exercises link to a URL like https://exercism.io/my/solutions/87f20c31baab4b83b59a90cb3d59a089. This goes to the specific exercise.

*However*, I have seen some exercises in other tracks that are also incorrectly linked, e.g. https://exercism.io/my/solutions?exercise_id=yacht&track_id=python in Python or https://exercism.io/my/solutions?exercise_id=scale-generator&track_id=go in Go. Both of these also go to the "My Solutions" page.

**Comment by iHiD** [comment]
Hello :)

1 + 2 are just the way the PHP track is set up (or not set up really).

Is the third point true if you **click** on an exercise, rather than opening it in a new tab?

**Comment by goodevilgenius** [comment]
@iHiD No, if I just click on it, it redirects to the exercise page. I hadn't tried that because I *always* open in a new window.

I see in the code that a listener on the click event changes it into a form submission. I've never seen that technique before. It's a little odd, and, as we see, breaks opening in a new tab (or window).

I guess I can't open in a new tab for those exercises anymore. That's a bit annoying. 😧

I'm guessing the reason I'm seeing this mostly on PHP is because of how it's not set up to unlock those exercises. I guess unlocking extra exercises sets up whatever database entries are also set up during that form submission.

**Comment by iHiD** [comment]
It's standard Rails code for POST links, but it does have that annoying side effect.

I'm going to close this for now, as you've got a workaround, but I'll improve it some time in the future so opening things in new tabs works. It's not trivial though.

Thanks for working through it with me :)

**Comment by goodevilgenius** [comment]
Sounds good. Thanks!
