### ISSUE TITLE
C# Formatting Two-Fer challenge

### ISSUE THREAD

**Issue by OrdoFlammae** [exercism/exercism#4954]
When I submitted the Two Fer exercise on the C# track, the end-result formatting came back a bit weird. My local copy has good formatting, but the online copy does not. After the `if` header line, something appears to have un-tabbed all my lines.

The online copy:
![image](https://user-images.githubusercontent.com/30962639/62001080-82b15000-b0ad-11e9-9f80-adc019ef694d.png)

The local copy:
![Screenshot 2019-07-27 20:34:30](https://user-images.githubusercontent.com/30962639/62001105-fce1d480-b0ad-11e9-82cc-6da7107e3d5a.png)

**Comment by iHiD** [comment]
I'm going to guess that your local code has a mixture of spaces and tabs, and that the way that your tabs are displayed is wider than how Exercism displays tabs.

**Comment by OrdoFlammae** [comment]
OK, yep, it was my fault. Sorry, I was using a new extension, and assumed it would insert spaces instead of tabs like I had set it too.

**Comment by iHiD** [comment]
No probs :)
