### ISSUE TITLE
No file to edit on Two Fer exercise

### ISSUE THREAD

**Issue by N3w0nee** [exercism/exercism#4959]

**Comment by kytrinyx** [comment]
Thank you @N3w0nee 

I'm not sure which language track you're working in. Not all tracks add stub files. When there is no file present, you can create your own file.

We have discussions ongoing about creating stubs for all exercises in all tracks, but I don't know that they've concluded yet.

**Comment by kytrinyx** [comment]
Update: these discussions have, indeed, concluded that we will add stubs to all exercises. That will take some time to get implemented, though.

**Comment by NobbZ** [comment]
@kytrinyx, I've missed that conclusion and other maintainers might have as well, could you mass open tickets every where?

**Comment by kytrinyx** [comment]
Yeah, it's on my list to make all those tickets!
