### ISSUE TITLE
[Bash Track]: no exercise icon - 403

### ISSUE THREAD

**Issue by bynov** [exercism/exercism#4960]
Hi!
Resistor color trio in bash track has no icon, image returning with 403 error.
<img width="869" alt="Screen Shot 2019-08-02 at 11 18 19" src="https://user-images.githubusercontent.com/18293649/62355230-43ed2100-b517-11e9-8945-0652bf540cb5.png">

**Comment by glennj** [comment]
It appears Knapsack png is also missing

**Comment by iHiD** [comment]
@bynov Thanks. This is covered in https://github.com/exercism/website-icons/issues/31.
@glennj Would you like to open an issue in https://github.com/exercism/website-icons for that one pls, explaining a little what the exercise is about? Thanks :)

**Comment by F3PiX** [comment]
Related: https://github.com/exercism/exercism/issues/4460 
Proposing a default icon for exercises that don't have one.

**Comment by glennj** [comment]
> @glennj Would you like to open an issue in https://github.com/exercism/website-icons for that one pls, explaining a little what the exercise is about? Thanks :)

website-icons issue https://github.com/exercism/website-icons/issues/32
