### ISSUE TITLE
Comment window content wrapping issue -- Post wide code window change

### ISSUE THREAD

**Issue by neenjaw** [exercism/exercism#4965]
Hi, I was requested by @iHiD to post this issue here

Great work on the preference for a full-width code window with dark-mode code panels.  

After this change, noted that when using the site on mobile (android P, pixel 3a xl, chrome browser) noted that the panel cut off my comment.  When I used the 'request desktop version' the full comment is visible.

siebenschlaefer, another exercism mentor, noted on slack that they also had this problem on the desktop version using the split-pane option.  I have included screenshots.

Thanks for looking into this.

![exercism-neenjaw-mobile-comment-cutoff](https://user-images.githubusercontent.com/8953691/62445431-6cdf0300-b71d-11e9-984f-87f795cd6362.png)
![exercism-neenjaw-desktop-comment-visible](https://user-images.githubusercontent.com/8953691/62445444-74061100-b71d-11e9-9ebd-7a79c682af5d.png)
![exercism-siebenschlaefer-desktop-split-panel-cutoff-01](https://user-images.githubusercontent.com/8953691/62445451-77010180-b71d-11e9-8384-8705d0004184.png)
![exercism-siebenschlaefer-desktop-split-panel-cutoff-02](https://user-images.githubusercontent.com/8953691/62445461-79fbf200-b71d-11e9-929d-a1b17de1a962.png)

P.S. should I post the solution id? I don't want to expose the student, but if you need it I can provide it here or privately.

**Comment by iHiD** [comment]
> P.S. should I post the solution id

Posting ids is fine. Thanks for checking :)
