### ISSUE TITLE
Unlock new exercise from main track after tests passes.

### ISSUE THREAD

**Issue by miwojc** [exercism/exercism#4966]
I am on Python track at 4th exercise `Matrix`. After submitting i got message that it will take approx 1 month to receive feedback from mentor. For someone who wants to proceed to learn programming, proceed to next exercise this is very discouraging. One will forget everything in one month waiting. I know there are side exercises, but i am talking main track exercises.

I suggest to auto run the tests in the back end for the submitted exercise and once all tests passes `conditionally approve` the solution and unlock next main track exercise. `Full approval` will be given by mentor. However this will allow learner to progress with main track.

Thanks for the great work!

**Comment by NobbZ** [comment]
Hello @miwojc, there is ongoing work in automatic mentoring and testing.

It will take some time though to get this up and running across all tracks.

First automatic mentorings are already available for some tracks and exercises, tests shall be automated through the next month for the first tracks.

**Comment by sshine** [comment]
@miwojc: I am closing this issue because your thoughts are fully heard and covered. Thanks. :-)
