### ISSUE TITLE
how to set download location for exercises?

### ISSUE THREAD

**Issue by danieljobbagy** [exercism/exercism#4968]
Hi,

I would like the exercises to be downloaded in a folder I created for this purpose, not in the default (user/Exercism/{trackname} one. 
How can I do it?

Thank you.

**Comment by NobbZ** [comment]
You can use the `exercism config --workspace=...` setting. It will still organize it's subfolder a in tracks and exercises though.

**Comment by danieljobbagy** [comment]
Thank you it worked!
