### ISSUE TITLE
Java queue not moved for a week

### ISSUE THREAD

**Issue by justunbartlett** [exercism/exercism#4975]
Hi.
Is there a problem with the java track queue? The queue has remained the same for a week. It says there are 12 ahead of me in the queue and hasn't changed in that time. 
Is this normal?

Thanks.

**Comment by iHiD** [comment]
What's your solution id?

**Comment by justunbartlett** [comment]
Thanks for your response. How do I find that?
I'm logged in as finnsquib if that helps. Gigasecond exercise. 

On 11 August 2019 21:03:23 BST, Jeremy Walker <notifications@github.com> wrote:
>What's your solution id?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/exercism/issues/4975#issuecomment-520256126

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by justunbartlett** [comment]
Thanks for your response. How do I find that?
I'm logged in as finnsquib if that helps. Gigasecond exercise.

**Comment by NobbZ** [comment]
You can find your solution ID by looking at the URL. The easiest way tp provide it, is to share the URL of your solution, we can identify the important parts and copy it. This way we avoid missing to copy single chars from beginning or end.

**Comment by justunbartlett** [comment]
https://exercism.io/my/solutions/49f61a1a0b154e558b770b88efea0a12
Second iteration.

**Comment by justunbartlett** [comment]
Any update on this question?

**Comment by iHiD** [comment]
I've asked mentors to check :)

**Comment by justunbartlett** [comment]
Thank you.

**Comment by iHiD** [comment]
They tell me there's a backlog because they've been working on getting the Kotlin queue down, but they're going to shift priorities to get back on top of Java.

**Comment by jmrunkle** [comment]
I think I just picked up your exercise so you should be moving along now. I'm sorry for the delay. Usually there are enough of us mentors volunteering to keep the queues going down, but I have certainly been extra busy with normal life stuff lately. Anyways, hope we can get things evened out on the Java track now that they managed to get the Kotlin queue under control.
