### ISSUE TITLE
Warninig Levels for Visual Studio's C++ compiler

### ISSUE THREAD

**Issue by Nolshine** [exercism/exercism#4976]
In the C++ track, exercises come with a CMakeLists.txt file that configures CMake for each exercise, and I noticed that when building C++ solutions to exercises certain warnings I'd expect to see aren't appearing.

It looks like warning levels are set to be verbose for Clang and GNU compilers but there's no setting that addresses the default compiler MSVS ships with.

https://stackoverflow.com/questions/2368811/how-to-set-warning-level-in-cmake/50882216#50882216

This SO answer describes how that could be addressed for visual studio, and it would be a great help to new programmers such as myself if this configuration option could be added.

**Comment by iHiD** [comment]
(cc @exercism/cpp)

**Comment by KevinWMatthews** [comment]
@Nolshine Sounds like a good idea.

@iHiD I've opened an identical issue for this in [execism/cpp](https://github.com/exercism/cpp/issues/302). You can close this and we'll look into it over there.

**Comment by iHiD** [comment]
@KevinWMatthews Thanks :)
