### ISSUE TITLE
C++ headers

### ISSUE THREAD

**Issue by parhamrm** [exercism/exercism#4981]
It's better to change header files extension from .h to .hpp so code editors know that the file is a c++ header. It also helps c++ and c separation.
[https://github.com/lefticus/cppbestpractices/blob/master/03-Style.md#use-hpp-and-cpp-for-your-file-extensions](url)

**Comment by iHiD** [comment]
(cc @exercism/cpp)

**Comment by KevinWMatthews** [comment]
Hi @parhamrm , thanks for the suggestion. I'd like to move this over to the [C++ track](https://github.com/exercism/cpp/issues/305) - we'll find a better audience for discussion over there.

@iHiD thanks! You can close this issue.

**Comment by iHiD** [comment]
@KevinWMatthews Thanks! :) I can move issues between repos if you'd ever like me to that to save you the hassle of creating a second one :)

**Comment by KevinWMatthews** [comment]
@iHiD Cool! I didn't realize that was a feature. That would be convenient for sure.

**Comment by iHiD** [comment]
Great :) It's new (about 1 month old).
