### ISSUE TITLE
The file you are trying to submit cannot be found.

### ISSUE THREAD

**Issue by mikel99** [exercism/exercism#4983]
Hi, made sure capital E for Exercism, tried submitting with full path.

~  cd Exercism
 ~/Exercism  cd scala/space-age
 ~/Exercism/scala/space-age  ls
README.md build.sbt project   src       target
 ~/Exercism/scala/space-age  cd src/main/scala
 ~/Exercism/scala/space-age/src/main/scala  ls
SpaceAge.scala
 ~/Exercism/scala/space-age/src/main/scala  exercism submit SpageAge.scala
Error:

    The file you are trying to submit cannot be found.

        /Users/mikel/Exercism/scala/space-age/src/main/scala/SpageAge.scala

 ✘  ~/Exercism/scala/space-age/src/main/scala  exercism submit /Users/mikel/Exercism/scala/space-age/src/main/scala/SpageAge.scala
Error:

    The file you are trying to submit cannot be found.

        /Users/mikel/Exercism/scala/space-age/src/main/scala/SpageAge.scala

 ✘  ~/Exercism/scala/space-age/src/main/scala 

**Comment by NobbZ** [comment]
This looks really weird…

Can you please tell us which version of the CLI you are using (`exercism version`), as well as your operating system (Mac OS I guess? Please tell exact release version).

Also please tell the output of `file SpaceAge.scala` when in the folder that contains the file. `stat SpaceAge.scala` might be interesting as well.

**Comment by mikel99** [comment]
Hi,
✘  ~/Exercism/scala/space-age/src/main/scala  exercism version
exercism version 3.0.12

MacOs - Mojave - 10.14.5

SpaceAge.scala is a series of methods, each returning a Double.

 ~/Exercism/scala/space-age/src/main/scala  stat SpaceAge.scala
16777221 31812955 -rw-r--r-- 1 mikel staff 0 1077 "Aug 17 14:17:28 2019" "Aug 17 14:17:11 2019" "Aug 17 14:17:11 2019" "Aug 17 13:27:22 2019" 4096 8 0 SpaceAge.scala

thanks,
mike

**Comment by mikel99** [comment]
Hi,
✘  ~/Exercism/scala/space-age/src/main/scala  exercism version
exercism version 3.0.12

MacOs - Mojave - 10.14.5

SpaceAge.scala is a series of methods, each returning a Double.

 ~/Exercism/scala/space-age/src/main/scala  stat SpaceAge.scala
16777221 31812955 -rw-r--r-- 1 mikel staff 0 1077 "Aug 17 14:17:28 2019" "Aug 17 14:17:11 2019" "Aug 17 14:17:11 2019" "Aug 17 13:27:22 2019" 4096 8 0 SpaceAge.scala

thanks,
mike

**Comment by NobbZ** [comment]
The output of `stat` is now what I'm used to from my linux boxes, but it doesn't look suspicious…

Anyone can read the file, so that shouldn't be an issue. `ls` has proven the file is actually there…

@exercism/cli, anything that could help to debug this?

**Comment by iHiD** [comment]
`SpageAge` is a typo. It should be `SpaceAge`

**Comment by NobbZ** [comment]
Ouch… Sorry for not catching that… And I've tripple checked…

**Comment by mikel99** [comment]
Double Ouch! Sorry about wasting your time - I'm duly embarrassed!

**Comment by iHiD** [comment]
It's all good! :)

**Comment by Malik-Usman17** [comment]
After spending almost half an hour on my own and scratching my head, I came to this issue. Happily solve my issue then :)
