### ISSUE TITLE
Error downloading exercise

### ISSUE THREAD

**Issue by sayyedkamran** [exercism/exercism#4985]
I configured  exercism CLI tool on ubuntu. When downloading my first exercise using command:

"exercism download --exercise=hello-world --track=rust"

it gives error

Error: 

    Welcome to Exercism!

    To get started, you need to configure the tool with your API token.
    Find your token at

        https://exercism.io/my/settings

    Then run the configure command:

        /snap/exercism/2/./exercism configure --token=YOUR_TOKEN

**Comment by PatrickMcSweeny** [comment]
The error message gives instructions on what do to.

**Comment by sayyedkamran** [comment]
The issue resolved when I restarted my laptop.

Thanks PatrickMcSweeny. As I mentioned, I have completed all the configurations correctly.  The issue resolved by restarting my PC.

**Comment by NobbZ** [comment]
This is probably related to some sandboxing `snap` does.

Installing through `snap` is not yet officially supported. Be aware that the package downloaded by `snap` is not under the control of the exercism organisation.

There are plans to change this in the future, but we are not there yet.
