### ISSUE TITLE
Layout doesn't use available space, making code reading very annoying

### ISSUE THREAD

**Issue by Bios-Marcel** [exercism/exercism#4987]
![grafik](https://user-images.githubusercontent.com/19377618/63335670-163d1000-c33e-11e9-85e1-f6cb72d91e37.png)
The code viewer and the comment section should both expand horizontally. Because the way it is now, you can't really read the code without scrolling left and right.

Ignore the weird artifact in the image ^^'

**Comment by iHiD** [comment]
There's a setting at the bottom of [preferences](https://exercism.io/my/settings/preferences/edit)

**Comment by Bios-Marcel** [comment]
Those aren't available in team mode btw :D

**Comment by iHiD** [comment]
As in the setting doesn't affect the UI in team mode?

**Comment by Bios-Marcel** [comment]
No, that works fine, but it's not available in the UI. The whole preferences page I mean. Therefore I couldn't even notice it.

**Comment by iHiD** [comment]
Gotcha. Thanks. Teams is very "beta" :)

**Comment by Bios-Marcel** [comment]
I see ^^

**Comment by kotp** [comment]
It is available in settings, but I wish it were toggle-able in the page we are viewing.  Sometimes it is nice, but if we could toggle as we need it we could have the "best of both worlds", the "side by side" or "full page" style view.

**Comment by Bios-Marcel** [comment]
I also thought it's not very optimal for wide desktops. I had it over 2560 width, meaning the editor is much wider than needed. I ended up installing a custom style suing Stylus that grows both codeview and comments, making them both be 50% of the page in width.
