### ISSUE TITLE
Enforcing 2FA for the Exercism organization starting on September 1st, 2019

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4989]
This only applies to maintainers of Exercism-repositories.
We currently don't have a reliable way of notifying all org members on GitHub of something, so we're covering all bases to try to ensure that everyone who needs to sees this.

---

We're going to be turning on compulsory two factor authentication (2FA) for the Exercism organization on GitHub as of September 1st.

Please turn on 2FA before that date.

Note that once we turn on 2FA GitHub will remove your access to the organization automatically if you've not enabled 2FA on your account. You can update this in your settings: https://github.com/settings/security

If you happen to be on vacation or away from your laptop long enough that we've turned on 2FA before you got the notification, then please email me (email on my GitHub account) or contact me on Slack and I'll get you sorted out!

**Comment by iHiD** [comment]
(cc @exercism/track-maintainers @exercism/website-copy @exercism/cli)

**Comment by iHiD** [comment]
This has now been done (https://github.com/exercism/exercism/issues/5010)
