### ISSUE TITLE
Scala track unable to unlock next exercise

### ISSUE THREAD

**Issue by githubprojects** [exercism/exercism#4990]
For scala track,Unable to unlock the next exercise after one of the exercise solution is approved. Please help

**Comment by F3PiX** [comment]
Hi @githubprojects 
Check: did you click the 'complete this exercise'-button after the mentor approved the solution?  
If it still doesn't unlock the next exercise: Can you please post the url of the approved exercise?
Thanks!

**Comment by iHiD** [comment]
Hello. We merged a PR last night to reorder some of scala. We have a script currently running to ensure that everyone's tracks still work. I imagine it's not got to you yet. I think this should fix in the next hour. Please let me know then and sorry for the inconvenience.

**Comment by sshine** [comment]
@githubprojects: Can you confirm that this works?

Until then, I assume that it does, as this is something we experience once in a while.
