### ISSUE TITLE
Let the students know across Exercism that submitting test files causes test updates to not happen for them.

### ISSUE THREAD

**Issue by kotp** [exercism/exercism#4994]
As brought up in https://exercism-team.slack.com/messages/CAQP7JL3T we should let students know about issues that arise when test files are submitted with the exercise file(s).

![about_test_files](https://user-images.githubusercontent.com/16747/65270676-a3b08300-dae9-11e9-8b68-74cdc1fdc315.png) in case we get passed the 10k message mark, it will be enshrined here.

**Comment by sshine** [comment]
Could you edit the OP with a quotation of the message you're linking to?

Also, how do you imagine that students should be notified?

As far as I know, there is no clear way for the website to know which uploaded files are test files and which are not. Should it be some kind of output from an [automated test runner](https://github.com/exercism/automated-tests)? An alternative would be for the website to keep track of test files, but there is something about that kind of bookkeeping I find concerning.

**Comment by kotp** [comment]
> Could you edit the OP with a quotation of the message you're linking to?
I think "OP" is something about what I wrote, I added a graphic, hopefully this is what you meant by that.

> Also, how do you imagine that students should be notified?

It should probably be in the same place where we tell students how to submit files.

> As far as I know, there is no clear way for the website to know which uploaded files are test files and which are not. Should it be some kind of output from an [automated test runner](https://github.com/exercism/automated-tests)? An alternative would be for the website to keep track of test files, but there is something about that kind of bookkeeping I find concerning.

We already don't overwrite data that the student already has with updates from the website.  So I don't think we need to check for specific types of files, we should always not overwrite user supplied files.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
