### ISSUE TITLE
My answer has been submitted for a long time without unlocking the next question

### ISSUE THREAD

**Issue by Aquarian-Age** [exercism/exercism#4998]
My answer has been submitted for a long time without unlocking the next question
[Https://exercism.io/my/solutions/50b774c7a8344e16811cef7b98c9ba0a](Https://exercism.io/my/solutions/50b774c7a8344e16811cef7b98c9ba0a)

**Comment by iHiD** [comment]
Hello. You can either wait for a mentor in Mentored Mode, or you can go on without a mentor in Independent mode. The wait in the Go track isn't generally too long, but there is a bit of a backlog right now.

**Comment by aeamaea** [comment]
@iHiD Would you be able to mention how one can go into independent mode? I must have missed this in my profile/settings pages. Thanks.

**Comment by iHiD** [comment]
@aeamaea Thanks for posting the update. You can read more at https://exercism.io/strategy about what we're doing to improve things.
