### ISSUE TITLE
Queue position is increasing instead of decreasing

### ISSUE THREAD

**Issue by Moeser** [exercism/exercism#5004]
![queue_position](https://user-images.githubusercontent.com/14844623/63901323-eb476180-c9b8-11e9-8735-e48671986d16.png)

My queue position in the python track is increasing instead of decreasing.  Last week it was in the mid 200's (240 I think), and now it's just shy of 300.  I didn't screenshot it last week, but I'll start taking screenshots from now on.

Also, and possibly related: check out that wicked high median wait time for mentoring on this exercise.  8 months?  Is that right? (see image)

**Comment by NicholasDunham** [comment]
I'm seeing this in the Go track as well. My position in the queue for the specific exercise doesn't change, but my position in the overall track queue is going up.

**Comment by Moeser** [comment]
![queue_position2](https://user-images.githubusercontent.com/14844623/64048000-4f873400-cb25-11e9-8b6d-f451245f5439.png)

Here's another screenshot from today.  I've fallen behind another 7 spots in the last two days.  Is there a bug in how the queue works, or is this just a bug in how the queue position is displayed?

I really do appreciate having information about the queue position and median wait time though.  It's a helpful feature.  I'm hoping we can get this bug narrowed down so that it's even more helpful.  :)

**Comment by iHiD** [comment]
We're trying to work this out if this is a bug or not. People who don't use the site for >2months disappear from queues. If they come back then their solution reappears and so everyone else goes backwards. We think that might be what is happening.

But we're going to look into it and work it out :)

**Comment by Moeser** [comment]
A mentor picked up my solution, so I have no extra data to add, except that they picked it up more quickly than I would have expected from my queue position, and certainly more quickly than the median waiting time of 8 months.  So maybe it really is a bug on the display side?
