### ISSUE TITLE
Community solutions visible to all exercises when not logged in

### ISSUE THREAD

**Issue by miwojc** [exercism/exercism#5007]
When not logged in to exercism.io i can see all solutions to all Python track exercises, both core and side ones. Is this done on purpose?
When i am logged in to a website i am only able to view the community solutions once i submit the code for side exercises or get mentor approval for core exercises.
I know that solutions can be found on github too. But do we want to encourage students to look up solutions on the official site?

Steps to recreate:
1. open https://exercism.io/
2. select python https://exercism.io/tracks/python
3. click on `all the exercises here` https://exercism.io/tracks/python/exercises
4. choose exercise, for example the core exercise `Two Fer` https://exercism.io/tracks/python/exercises/two-fer/solutions/a1ec5f564aba409b8377f25ef1b80cee

**Comment by iHiD** [comment]
Hey @miwojc, Thanks for opening the issue!

> When not logged in to exercism.io i can see all solutions to all Python track exercises, both core and side ones. Is this done on purpose?

Yes :)

It's good for SEO, good for people linking to things, and good for people getting a feel for Exercism before they sign up.

We're going to be doing a  lot more with these solutions in the near future :)
