### ISSUE TITLE
Waiting for mentor for 5 days

### ISSUE THREAD

**Issue by youngrake** [exercism/exercism#5009]
i am waiting for mentor for 5 days, is it a bag?

**Comment by NobbZ** [comment]
For some tracks/exercises 5 days is a long time, for others its about none… Could you therefore elaborate which track/exercise you are waiting for a mentor?

**Comment by youngrake** [comment]
> For some tracks/exercises 5 days is a long time, for others its about none… Could you therefore elaborate which track/exercise you are waiting for a mentor?

Two-fer. Python

**Comment by iHiD** [comment]
Does it give you a median wait time and a queue position on the website?

**Comment by sbruinsje** [comment]
I have a similiar case in the javascript queue. I have been waiting for 2 days for Resistor Color Duo in the javascript track. 

The median is 3 hours. Also its saying:

> There are currently 53 solutions ahead of this in the JavaScript queue, and 4 ahead in the Resistor Color Duo queue.

I believe those numbers didn't change the last 2 days, at least not the last day.

**Comment by iHiD** [comment]
Each track is different and mentors mentor at variable rates. The weekends are normally quieter than the weeks. 

@sbruinsje I imagine that it'll get better today, but if not, please ping again.

**Comment by sbruinsje** [comment]
After another day it now says:

> There are currently 60 solutions ahead of this in the JavaScript queue, and 3 ahead in the Resistor Color Duo queue. 

If its because a lack of mentors there is no problem I can wait. I just want to make sure there is not some issue with the queuing system.

**Comment by youngrake** [comment]
> Does it give you a median wait time and a queue position on the website?

Nothing, waiting for 10 days. Seems like bug or idk.

**Comment by iHiD** [comment]
1. Yeah. I imagine just slow mentoring. Will ping js mentors to check. Thanks for being understanding.

2. If there's no queue position shown, that means it's a side exercise or you're independent mode, both of which take longer to get mentored.

**Comment by youngrake** [comment]
>     1. Yeah. I imagine just slow mentoring. Will ping js mentors to check. Thanks for being understanding.
> 
>     2. If there's no queue position shown, that means it's a side exercise or you're independent mode, both of which take longer to get mentored.

independent, what do you mean?

**Comment by iHiD** [comment]
You choose either "mentored mode" or "independent mode" when you chose when you joined the track. Depending on which you chose determines the speed that you get feedback if you request it.
