### ISSUE TITLE
2FA is now enforced for the Exercism GitHub organization

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5010]
As per https://github.com/exercism/exercism/issues/4989, 2FA is now enforced for the Exercism organisation.

This has resulted in 44 org members being removed. If you have been affected by that and would like to be added back (yay!), please add 2FA to your GitHub account and reply to this issue, email @kytrinyx (email on her GitHub account), or contact her on Slack, and she'll sort things for you.

I'll leave this open for a few days so people affected can see it.

**Comment by iHiD** [comment]
(cc @exercism/track-maintainers @exercism/website-copy @exercism/cli)

**Comment by sshine** [comment]
Should this either be pinned or closed?

**Comment by kotp** [comment]
I would leave it for another week, some may be out to vacation for their 30 days, and away.
