### ISSUE TITLE
Reassign Mentor (py)

### ISSUE THREAD

**Issue by jramdohr** [exercism/exercism#5015]
Hi, my mentor's account was deleted and unfortunately a new one hasn't been assigned for many days now. Is it possible to re-submit my solution for review?

https://exercism.io/my/solutions/635c6596d3034217b01b16ccf30c1a0a?iteration_idx=3

Thanks

**Comment by yawpitch** [comment]
Hi @jramdohr, has someone picked this up? I don’t see it in the mentor queue and the direct link comes up as private.

**Comment by iHiD** [comment]
@yawpitch Can you see https://exercism.io/mentor/solutions/635c6596d3034217b01b16ccf30c1a0a ?

**Comment by yawpitch** [comment]
> @yawpitch Can you see https://exercism.io/mentor/solutions/635c6596d3034217b01b16ccf30c1a0a ?

Yep, thanks!

**Comment by sshine** [comment]
Perhaps this issue should be closed then?
