### ISSUE TITLE
COBOL

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5020]
It's not a dead language. It's not going away any time soon. And there's a free, high quality compiler that runs on [Windows, Mac and Linux](https://sourceforge.net/projects/open-cobol/)

**Comment by iHiD** [comment]
@axtens I agree! Would you like to be responsible for starting and maintaining that language on Exercism?

**Comment by sshine** [comment]
@axtens: If you would like to consider this until some indefinite point in the future, I will close this issue.

When the interest arises, you may like to check out [these instructions](https://github.com/exercism/request-new-language-track#readme).

**Comment by axtens** [comment]
Yes, close it for now. We're there 25 hours in a day and 8 days in a week ...
