### ISSUE TITLE
python >matrix waiting for 14 days

### ISSUE THREAD

**Issue by diegoitaliait** [exercism/exercism#5023]
I wait about 14 days in mentor mode, to go on.

Is it possible to have a bonus or something like that that allows me to completely force the exercise for example if it passes all the tests?

**Comment by ollster333** [comment]
I've got the same problem. When I completed high scores both raindrops and matrix were unlocked. I have been waiting 10+ days for matrix to be mentored however raindrops, which I submitted afterwards, has been mentored.
I am wondering if it has slipped through the net.

**Comment by dhbarnett** [comment]
I had a similar problem, I thought it was because my mentor quit. Guess it's bigger than that

**Comment by linuxleep** [comment]
> For me it would be enough a feature that allows me to force the completion of the exercise if the tests pass all.
> 
> After all, it is I who take responsibility for not having the mentor's answer

There used to be a way to do that unless they have removed it. I am not saying that it is there anymore, but there used to be a button to complete without approval. 

Also and update, someone has gone through and reviewed mine. Hope they get to all of yours as well.

**Comment by NobbZ** [comment]
The button to complete without mentor is there, but it comes with a cost. You can't request mentorship for that exercise later (without abusing a bug) and also it won't unlock its side exercises.

If you feel slowed down to much by mentor mode, have you considered switching to independent mode?
