### ISSUE TITLE
Bug: Prolog code highlighting as perl instead of prolog

### ISSUE THREAD

**Issue by neenjaw** [exercism/exercism#5026]
Situation: Prolog code in submission codeblocks is not being properly highlighted as prolog syntax.

Background: There has been a longstanding conflict between perl and prolog as they both share a common filetype extension `.pl`, there have been so attempts to differentiate prolog with `.pro` or others, `.pl` remains popular

Assessment: In markdown codeblocks with the `prolog` they highlight appropriately.  But it seems that that the filetype is inappropriately identified as a perl script based off of the file extension.

Recommendation: In addition for checking for filetype, have it detect that the submission is a prolog submission and then override the `.pl` association for prolog

**Comment by iHiD** [comment]
Thanks for opening the issue.

I think the best solution would be to "unrecognise" the `pl` file-extension altogether and then purely determine the highlighting based on track. I can make some tweaks that achieves this in the code base and that I don't think should be disruptive. That should then get us to a good place.

---

For my future reference, `app/helpers/file_helper.rb:5` is what needs changing.
