### ISSUE TITLE
Problem with a few of my old (unapproved) submissions

### ISSUE THREAD

**Issue by verdammelt** [exercism/exercism#5028]
As mentor / maintainer of the common-lisp track I'd like to submit my own solutions to problems and get my own feedback from the track. Looking at my submissions I see that I have two that are yet to be approved - both from about 3 years ago:

* https://exercism.io/my/solutions/0c81b6a9f52143299fcfa994505b9a0b
* https://exercism.io/my/solutions/faf779b887bc402284f5f77f29205140

I asked fellow mentors if they could approve them so I could move on to submit new solutions, including to new exercises on the track. One such mentor reported to me that they got an error when trying to get to them: "Sorry, this solution is not public.".

I'm curious if these exercises are in some odd state. Any help debugging the situation would be great.

(I don't want to mark them completed but unapproved as the warning message on that action says that doing so will not unlock side exercises - which is something I would want).

Thanks in advance.

**Comment by NobbZ** [comment]
I can view the submissions once I change the URLs to be the mentor link:

* https://exercism.io/mentor/solutions/0c81b6a9f52143299fcfa994505b9a0b
* https://exercism.io/mentor/solutions/faf779b887bc402284f5f77f29205140

Obviously I can't mentor them.

**Comment by iHiD** [comment]
I think maybe the people hadn't just modified the URLs correctly. Does this solve your problem now? :)

**Comment by verdammelt** [comment]
"User Error" is a very likely cause for this "issue" I'm sure. I'll close this.

**Comment by verdammelt** [comment]
Thanks to you both for taking time to look into it.
