### ISSUE TITLE
Error with completion script on Mac OS + Oh My Zsh

### ISSUE THREAD

**Issue by Stigjb** [exercism/exercism#5029]
I have downloaded the Zsh completion script<sup>[1]</sup> and put it in ~/.oh-my-zsh/custom/. When I open a new shell, I get the following error:

`/Users/stig/.oh-my-zsh/custom/exercism_completion.zsh:local:6: options: can't change type of autoloaded parameter`

My Zsh version is `zsh 5.3 (x86_64-apple-darwin18.0)` I am using the Oh My Zsh framework.

[1] https://github.com/exercism/cli/blob/master/shell/exercism_completion.zsh

**Comment by Stigjb** [comment]
Ping :)

**Comment by NobbZ** [comment]
Oh sorry…

But its sad that I have to say, that I can not provide much more information as I've already pointed out.

Except that I can link to the PR now: exercism/cli#865

The basic conclusion is, that OMZ lacks documentation. It seems to have a folder `${ZSH}/completions` which is part of the `$fpath`.

You should be able to drop the `exercism` completion file there. Please also remember to rename it to `_exercism`, no need to make it `+x`.

**Comment by Stigjb** [comment]
Thank you for the reference to the PR!

> But as far as I can tell, the exercism completion is not a "plugin" in the way as omz defines its plugins. While I'm not sure what would make a plugin a plugin rather than a bare script.

I can find many instances of plugins in the main OMZ repository that only contain a completion script. E.g. https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/knife

I think the recommended approach would be to put the Exercism completion script in `~/.oh-my-zsh/custom/plugins/exercism/_exercism` and add `exercism` to the list of plugins in `~/.zshrc`. I have tried it on my system, and it works fine.

**Comment by NobbZ** [comment]
Thank you for investigating that.

Could you perhaps PR github.com/exercism/cli and provide documentation for getting completion work as a plugin in OMZ?

**Comment by GogoFC** [comment]
> I think the recommended approach would be to put the Exercism completion script in `~/.oh-my-zsh/custom/plugins/exercism/_exercism` and add `exercism` to the list of plugins in `~/.zshrc`. I have tried it on my system, and it works fine.
> 
> My `$fpath` now contains `/Users/stig/.oh-my-zsh/custom/plugins/exercism`, which I think is probably thanks to the plugins listed in `.zshrc`.

I tried both the `exercism completion zsh` and to download the `exercism_completion.zsh` in /custom/plugins. Neither seem to autocomplete.
