### ISSUE TITLE
Upgrading legacy exercise bypasses mentoring

### ISSUE THREAD

**Issue by bkhl** [exercism/exercism#5031]
I noticed this on one exercise on the Perl 5 track, I don't want to retest it
on my real exercises though, so bear in mind I only tried this once and maybe
just did some accidental click or anything. But anyway, here is what I *think*
happened on my "Bob" solution (`80c79a68ef8f431ca3a39876a0c22432`).

It seems that if I have a legacy solution, that also has been upgraded, and I
click "Update exercise to latest version", that also made the message "This
solution has been imported from an old version of the website. If you would
like to receive mentorship on it, please click here." disappear.

For now I'll click the "request mentoring" thing first, but certain of the
mentors on the track are very quick and often takes time to respond to my more
than a year old solution, before I have time to submit a new version.

**Comment by NobbZ** [comment]
Possible duplicate of #4741?

**Comment by bkhl** [comment]
Sound similar, though on the other ticket @NobbZ says he could still submit it for mentoring somehow? I can't see a way to do that on mine.

**Comment by NobbZ** [comment]
I was only able to re-submit because @iHiD reset the status of the solutions in the database.

**Comment by bkhl** [comment]
I see, same issue then.

**Comment by sshine** [comment]
Perhaps this issue should be closed in favor of keeping #4741?

**Comment by bkhl** [comment]
Closing as duplicate of #4741

**Comment by NobbZ** [comment]
PS: It also might help to post your UUIDs of the affected solutions in the other issue, asking to get them fixed.
