### ISSUE TITLE
exercism/request-new-language-track says clone 'tools' but 'tools' is a 404

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5034]
in One-time setup **Clone the tools repository.** has a link that 404s, specifically https://github.com/exercism/tools

**Comment by NobbZ** [comment]
Could you please point out where exactly you found that link?

**Comment by axtens** [comment]
https://github.com/exercism/request-new-language-track

**Comment by iHiD** [comment]
@axtens I believe those instructions are for the administrator creating the track. I've pinged @kytrinyx to check. Once that's clear, we'll improve that README to clarify for future.

If you [create issues](https://github.com/exercism/request-new-language-track/issues/new) in the repository for each language you want to start (using the template you'll see when you follow that link), repos will be populated for you and you can get started. We'll also invite you to our Slack room where you can chat to other maintainers to get help kicking off your track. We have several that have been launched recently so there will be people with recent knowledge to help :)

**Comment by bergjohan** [comment]
Yes, I think @kytrinyx is using that when bootstrapping a new track. Once the track has a repository, the maintainer will be pointed here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md
Note the first line:

> At this point you should have a repository to work in.

**Comment by axtens** [comment]
Okay, just looking at this point. Wouldn't mind seeing COBOL represented. Might have to wait till I retire.

**Comment by iHiD** [comment]
OK. @bergjohan can maybe provide you with an estimate of how many hours work he put in to get the x68-64-assembly track from zero to launch.

**Comment by kytrinyx** [comment]
Tools is, indeed, a 404 now. I'm the only one bootstrapping repos, I'll make sure to update the repo next time I do so that other admins (hello Jeremy) can also do this :)

**Comment by bergjohan** [comment]
Tough question. I worked on the track when I had the time. It actually took me 7 months from bootstrap until launch. I guess what I'm trying to say is, there is no rush in getting a track ready. Work on it when you have the time, you might even find someone who's interested in helping out along the way :)

**Comment by sshine** [comment]
Another point for comparison: The Tcl track repo was created Dec 1, 2018, but my first commit (the Hello World exercise and the docs/ directory) wasn't until Apr 8, 2019. Then @glennj wrote to me and expressed interest in participating on Aug 5, 2019, where I added some CI scripts, and we both added some exercises. From then he really went crazy with adding exercises, and I have no idea how much time he actually spent. ;-D

So probably in the 10s of hours. You could keep track infrastructure low and launch with 10-15 exercises, I guess? And you could stretch that effort into a full year like I did, or make as much as you can in as short a timespan as possible, like @glennj seems to have done. ;-)
