### ISSUE TITLE
Solution shown as text, not as code (Racket)

### ISSUE THREAD

**Issue by Marcelli** [exercism/exercism#5035]
I have submitted a solution to an exercise (two-fer) in the racket track using:
exercism submit [...]/two-fer/two-fer.rkt

On exercism.io my solution is shown not in racket, but as a text (the same text as if you open the rkt file with a text editor). The first fifteen lines look so:
```
#reader(lib"read.ss""wxme")WXME0108 ## 
#|
   This file uses the GRacket editor format.
   Open this file in DrRacket version 7.3 or later to read it.

   Most likely, it was created by saving a program in DrRacket,
   and it probably contains a program with non-text elements
   (such as images or comment boxes).

            http://racket-lang.org/
|#
 33 7 #"wxtext\0"
3 1 6 #"wxtab\0"
1 1 8 #"wximage\0"
2 0 8 #"wxmedia\0"
```

This is new: my solutions to earlier exercises are displayed in racket.

Any clue to why this is so?
Thanks!

**Comment by iHiD** [comment]
(cc @exercism/racket)

**Comment by NobbZ** [comment]
Your files get submitted as they are, and they get displayed as they are.

And even RKT files should be plain ASCII…

I'm wondering what you have done that it is saved differently from how its displayed…

Could you perhaps also provide a screenshot of how it looks for you in DrRacket?

**Comment by Marcelli** [comment]
Thanks for your answer, @NobbZ ! Here is a screenshot of my file in Racket. As you can see, it shows racket code. But the same file is shown as text in my solution to the two-fer problem on the website.
![image](https://user-images.githubusercontent.com/2535362/65165042-46132c80-da3e-11e9-9727-fe6bbc130dfe.png)

**Comment by NobbZ** [comment]
So thats probably the issue, the way you commented out the first implementation. This is probably considered "rich media" or "special feature" and therefore stored as obfuscated blob.

This is just an assumption though, and I'm not even sure if DrRacket would make it a non-rich-media file if you remove the first implementation from the file…

**Comment by Marcelli** [comment]
Thanks @NobbZ ! That was indeed the problem. Don't use box to comment out code in Racket! Replacing the box by semicolons made the trick, now the solution is read as racket code on exercism.io.

**Comment by timotheosh** [comment]
Sorry, I am late to the discussion. DrRacket can save in two different formats, plain text format and multimedia file format. Here are the docs with explanations: https://docs.racket-lang.org/drracket/drracket-files.html
