### ISSUE TITLE
What kind of tracks are allowed?

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#5036]
Is there a set of guidelines for what kind of tracks are allowed?

If so, it would be nice if they were mentioned in the beginning of:

https://github.com/exercism/request-new-language-track

**Comment by iHiD** [comment]
Nice idea. 

Anything that is a Turing-complete programming language. (So not Regexp, not a framework)

**Comment by sshine** [comment]
This is so unrestrictive that I withdraw my request to have it documented.
