### ISSUE TITLE
Decision: Re-evaluate exercism/cli presence on CodeTriage

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#5038]
In #4043, one task is to update the Exercism branding on https://www.codetriage.com/exercism/cli. This is hard because there is no branding, and the page is mostly a stub.

I propose that we evaluate Exercism's presence on the CodeTriage website: Do we want to request PRs for the CLI at this moment in time, or do we want to reconsider using CodeTriage more purposefully?

1. A no-op choice is to leave the page as a stub: This will confuse a very small amount of people who stumble upon it (e.g. there are 6 "subscribers" right now), but the choice comes at no other cost.
2. A clean-up-defer-to-later choice is to remove the exercism/cli presence on CodeTriage for now and reconsider if we'd like to use CodeTriage in some way as a separate concern (which can be discussed here). The cost here is that @kytrinyx probably needs to go and disable it, and the discussion here could stretch out.

We can also defer discussion, or at least keep it open-ended as so many other discussions are.

*(The exercism/cli presence on CodeTriage probably comes from a time when Exercism was smaller and CLI development wasn't bogged down by strategic decisions, product design and timelines. See e.g. #4711, #4087.)*

**Comment by iHiD** [comment]
I'd rather remove it and then readd it properly later when/if we have time/desire. Is that an option?

**Comment by sshine** [comment]
Yes, that would be 2. clean-up-defer-to-later. I'm sorry for any lack of clarity. :-)

**Comment by iHiD** [comment]
Let's do it! I'll ping @kytrinyx :)

**Comment by kytrinyx** [comment]
I'd also rather remove it :) I'll see what I can do.

**Comment by kytrinyx** [comment]
There's no way to remove repos, sorry: https://github.com/codetriage/codetriage/issues/350

**Comment by iHiD** [comment]
Meh. Thanks for checking. Shall we close this?
