### ISSUE TITLE
"request feeback if you get stuck"

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism#5040]
https://github.com/exercism/website/blob/master/app/views/my/tracks/_v1_migration_modal.html.haml

**Comment by shehbazjafri** [comment]
I'd like to fix this. :)

**Comment by sshine** [comment]
Let's hear @iHiD if my assessment of "difficulty/easy" is correct, and if this is something he is willing to outsource. :)

**Comment by iHiD** [comment]
Outsource :)

**Comment by ngsikai** [comment]
Hey @iHiD, forgot to link the PR to close this issue. This should be fixed for now.

**Comment by iHiD** [comment]
Thanks :)
