### ISSUE TITLE
Add more clarity on core exercise states on Track page

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5042]
I'm a nutjob tracking 12 languages at once. Currently the "Tracks" page tells me what I already know, that I have 12 language tracks. 

What I would like is some extra information on that page regarding where I am with each language. Currently I have to select a language, scroll a long way down to see where I'm at, click on the "In Progress" task and then look at the mentor/student discussion to see where I'm at.

It'd be nice to be able to have in the box for the language on the Tasks page some extra markers to show, for example, that I have or have not submitted code, that the mentor has or has not responded to the last code drop. Even to replicate the "In Progress" marker up one level to the Tasks would be a step in the right direction.

**Comment by iHiD** [comment]
Hi. Thanks for the ideas :) 

We are working on a general Dashboard atm that will provide some of this information as a snapshot of what's happened recently.

I like the idea of providing a bit more information on the `/my/tracks` page to show whether any tracks have things that require your action etc.

> It'd be nice to be able to have in the box for the language on the Tasks page some extra markers to show, for example, that I have or have not submitted code, that the mentor has or has not responded to the last code drop. Even to replicate the "In Progress" marker up one level to the Tasks would be a step in the right direction.

I'm not exactly sure which page you're refering to here. Maybe you could provide a sample URL? I'm going to guess you mean `/my/tracks/xxx` and that you're suggesting changing the "In progress" status on core exercises to say something a little more fine-grained, so as "Awaiting your comment" or "Awaiting mentor" or similar. Is that what you mean?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
