### ISSUE TITLE
Downloading exercises doesn't work

### ISSUE THREAD

**Issue by Darkace00** [exercism/exercism#5047]
Hello, when I’m downloading python exercises via your exercism codes, they don’t show up in the folder I assigned for them.
Don’t know how to fix this. 

Thank you

Evan Dokter.

**Comment by NobbZ** [comment]
Hello @Darkace00!

Have you been able to solve your problem or did you close the issue by accident?

If the latter, please tell us the full output of the download command.

**Comment by Darkace00** [comment]
I solved the problem, it was in a different folder. I looked in C:\exercism
and it was located in C:\Users\user\Exercism

**Comment by Darkace00** [comment]
I used the exercism debug command

**Comment by NobbZ** [comment]
The `exercism debug` isn't related to any of my questions.

* Did you try to configure the workspace to be somewhere else, but it still was in the default location?
* Did the printed location of `exercism download` not match the actual download location?

I just try to figure out the reason for why you have been confused and searched at the wrong place, as usually each time you download an exercise, the CLI prints the location.

**Comment by Darkace00** [comment]
No, I just overlooked it @did it give the wrong location
