### ISSUE TITLE
Merging student's solution with updated solution

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#5052]
Since this bug/feature has an impact on all tracks in multiple ways that are yet to be uncovered, I think it is crucial to document this and outline the consequences of having the bug/feature compared to the effects of any proposed solutions.

@iHiD asks the following (my highlight):
> What do people think about **not accepting submissions to the test file**? If people want to add extra tests *[...]* they would need to upload an additional test file. The reason for this is that when someone uploads a changed test file, they will never get updates to this file when the tests are updated by maintainers. *[...]*

@iHiD's elaborates in another thread:

> We don't override user-submitted *[files]*. So if a user submits new test-code, we don't override it.
>
> So, say an exercise is: `[code.rb, test.rb, readme.md]`. If they upload `code.rb` then that replaces what they downloaded. If they upload `test.rb` then that replaces the test file too.
>
> We basically do `original_files.merge(new_files)` where `new_files` replace `original_files` if there's a duplicate.

The first problematic implication that gets highlighted is that if a student uploads `test.rb`, they won't ever receive a modified `test.rb` for a newer version of the exercises when running `exercism download ...`. I can deduce from this statement that `new_files` is the sum of files across iterations, and not just of the latest iteration. @iHiD: Is that correct? *(Perhaps, as a digression, we could initially simplify the problem to only merge the files present in the latest iteration.)*

**A workaround could be to not accept submissions to the test file.**

But there are other problematic implications as well:
- On the Haskell track, two other problem cases arise: exercism/haskell#847
- On the OCaml track, yet another problem case arises: exercism/ocaml#368

These are not related to updates to the test file, but all kinds of other files as well, and these problems actively persist today. So my objection to "not accepting submissions to the test file" is not based on the fact that it's a sub-optimal solution, but that it only addresses a small part of the problem, and we cannot generalize "not accepting submissions to file *x*" for all *x* -- *especially* not the solution file.

**Edit:** Some drawbacks of "not accepting submissions to the test file" is that a track cannot have commented-out tests that are later enabled by the student and then submitted as a proof, and the student cannot, as part of the exercise, extend the test suite. (An elaboration is found in the track-specific issues above.)

An alternative solution to not accepting submissions of specific kinds of files is to improve on the merging strategy: Essentially, this is a merge conflict scenario where we cannot expect the student to be proficient with version control systems.

@iHiD has expressed that **realistically, we're not going to easily solve this wider problem right now.** So in the interest of having a more general solution, this issue attempts to gather the necessary information to design this properly and apply it later in time.

---

Here is a proposal for a plan:

- [x] Find the current code that performs the problematic merging.
- [ ] Submit a pull request that implements the workaround.
- [ ] Consider how to most simply relay that two versions of a file exists.
- [ ] Decide where, UX-wise, it is better to present the student with this:
  Here (before or after clicking "Update ...")?
  ![update-latest](https://user-images.githubusercontent.com/50879/65847444-d8220b80-e341-11e9-9bb4-2bb086e6ffa1.png)
  Or here?
  ```
  $ exercism download --exercise=leap --track=haskell
  ```
  On the one hand, we already know that there's a merge conflict as "Update ..." is clicked, and the website presentation of the uploaded files are also affected by this. *(Which version of any uploaded file do we show?)* On the other hand, it is more convenient to manipulate files at the point of typing `exercism download ...`, since the shell is closer to the filesystem. There are arguments for having both website and CLI support for handling this situation. And it would be possible to go entirely with one or the other.
- [ ] Reach conclusion on the a generalised fix: **Keep both the modified and the updated version around**, and either *ask the user which one to give the original name*, or *always give the same file the original name*, and **inform the user about this merge conflict and highlight affected filenames**.
- [ ] Submit a pull request that implements the generalised fix.

**Comment by sshine** [comment]
*(Notice that I've labelled this as "type/improvement"; it should perhaps be labelled "type/bug".)*

**Comment by iHiD** [comment]
@sshine Thanks for this. A few things that jumped out at me below.

> I can deduce from this statement that new_files is the sum of files across iterations, and not just of the latest iteration. @iHiD: Is that correct? (Perhaps, as a digression, we could initially simplify the problem to only merge the files present in the latest iteration.)

We only merge files present in the latest iteration.

> Find the current code that performs the problematic merging.

It's here: https://github.com/exercism/website/blob/master/app/models/api/solution_responder.rb#L76

>  Some drawbacks of "not accepting submissions to the test file" is that a track cannot have commented-out tests that are later enabled by the student and then submitted as a proof, 

Another key thing here is that very soon we'll have tests automatically run when someone submits. The tests will be run against the **original** test-suite with all tests unskipped, not a user-submitted update. This may be confusing to some users if they have submitted a different test-suite. We will also be adding in-browser coding, where they won't be able to update the test suite.

> and the student cannot, as part of the exercise, extend the test suite.

My original suggestion was that we ask students to submit extra tests in an additional file.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
