### ISSUE TITLE
Track maintenance dashboard: Show only exercises that are behind in version

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#5056]
@SleeplessByte's [Track maintenance tool](https://tracks.exercism.io/) is super neat; I've referred to it in exercism/haskell#852 for Hacktoberfest. I would like if there was a checkbox option so that the page only shows the exercises that are behind in version, i.e. the ones with an X in the right column.

*On a related note:*
- *The hyperlink in the "Canonical data version" column points to canonical-data.json for a given exercise, which is excellent because it contains both the current version and the current tests. The only resource I need then is the PR, which I will find manually.*
- *For the Haskell track, the hyperlink in the "Haskell version" column, however, currently points to package.yaml, where the "version: ..." marker resides. A more useful link would be the (invariantly named) test file test/Tests.hs. Depending on the purpose of the link in this column (whether it is to verify that yes, the version is indeed behind, or to compare the content of the tests), this could be altered. But this is not nearly as important (or thought out) as the above need for a checkbox. :)*

**Comment by SleeplessByte** [comment]
I'll add this checkbox :)

Yes, currently I'd like the link to be "where the version was retrieved". However I have plans of pulling in the tests so then that secondary feature can be satisfied.

P.S., there is a repo now! https://github.com/exercism/tracks-maintenance-dashboard

**Comment by SleeplessByte** [comment]
Once [this](https://github.com/exercism/tracks-maintenance-dashboard/commit/2d51f9205498f22bd747641b1ce925c5c007496d/checks?check_suite_id=258932628) is green, so you'll have it.

![image](https://user-images.githubusercontent.com/1964376/66533349-e676e100-eb12-11e9-820f-ea1f88c1838f.png)

It works on the aside, checklist, versions ánd topics list.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
