### ISSUE TITLE
Python -> matrix: mentor queue not working after 'Mentor deleteduser ... has left this conversatio'

### ISSUE THREAD

**Issue by astrorips** [exercism/exercism#5057]
It has been about a month since my last submission and comments from a mentor on the Python-Matrix-core exercise.

The mentor left the conversation (deleteduser), and since then the queue has been frozen or practically not evolving. I have re-submitted twice but it did not help.

I read other people had similar problems.

Is there any way to solve this issue without pushing the 'Complete exercise (unapproved)' button? I would prefer to avoid this solution if possible.

Thanks,
astrorips

**Comment by iHiD** [comment]
Can you link to your solution pls?

**Comment by astrorips** [comment]
The link is b99254cb5adf49b48f5d3ee4a07e743b

Thanks

**Comment by iHiD** [comment]
Hello. There's just a big queue atm. That mentor leaving has injected a lot of solutions back into the queue, which mentors are having to pick up. Sorry for the wait.

**Comment by astrorips** [comment]
Ok. Good to know. I will be just waiting for my turn then.
Thanks a lot for investigating.

**Comment by iHiD** [comment]
No problem, and thanks for understanding.
