### ISSUE TITLE
[Meta] What is involved in learning a new language?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#5059]
We've recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.
 
As a first step, we'll be examining the ways in which languages are unique and the ways in which they are similar. For this, we'd really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:
 
1. How was your experience learning language X? What was helpful while learning language X? What did you struggle with? How did you tackle problems?
1. In what ways did language X differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

We’ve opened issues in each track’s repository, where you can share your experiences with us. You can see them referenced below. If you’d like to discuss the general ideas we’re exploring, you can use the newly-created [#exploring-idioms](https://exercism-team.slack.com/messages/CNSFQJKU1) Slack channel. Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io. Finally, if you have questions about the process, please respond on this issue.

Thank you!

**Comment by verdammelt** [comment]
Is there a plan for getting students' feedback? Not sure how many people actively check out my track's repo (Common Lisp)

**Comment by ErikSchierboom** [comment]
> Is there a plan for getting students' feedback?

We currently do not have a great way to communicate with student to be honest, but if you know any students, feel free to point them to the [Common LISP](https://github.com/exercism/common-lisp/issues/258) issue and have them post their experiences there.

**Comment by wolf99** [comment]
Is there an expectation for completion for these issues?
What I mean is, when should we close one of these issues?
Thanks!

**Comment by ErikSchierboom** [comment]
Good question @wolf99! There is not yet a definitive end date, but I'll give it some thought next week.

**Comment by workingjubilee** [comment]
As a student, I pretty commonly visit my track's main page. You could try to embed a link to these issues on that page, or a link to some sort of survey collection, or even just embed a text dialog there, and then try to do a little bit of magic for tracking when they responded so you can hide it, or make it dismissable, aaaand maybe don't show it at all if they haven't even finished a single exercise.

**Comment by Lewiscowles1986** [comment]
As a student with experience (some of which may hinder or confuse learning new things); I like to explore the boundaries and ground-rules of languages.

* Is a string mutable, like a buffer?
* Are there links that might steer candidates away from wasting a mentors time?
* Are there institutional practices or expectations when using the platform?

A Colleague introduced me to Exercism as a thing we should use. They would like to become a mentor.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
