### ISSUE TITLE
Cannot download a second exercise for a team

### ISSUE THREAD

**Issue by lancejjohnson** [exercism/exercism#5060]
I recently created the team `peerfit-elixirists`. I downloaded an exercise with the following command:

```
exercism download --exercise=accumulate --track=elixir --team=peerfit-elixirists
```

I submitted two solutions to the exercise. Since then I cannot download another exercise for the team. I can download exercises without the team. For example, this command works:

```
exercism download --exercise=nucleotide-count --track=elixir
```

But this command

```
exercism download --exercise=nucleotide-count --track=elixir --team=peerfit-elixirists
```

produces:

```
Error: failed to parse API error response: invalid character 'o' in literal null (expecting 'u')
```

I've tried a few different exercises with the same results.

**Comment by iHiD** [comment]
@kntsoriano Can you check this request-id in the logs and see what the output was please?

**Comment by lancejjohnson** [comment]
@iHiD @kntsoriano I apologize. This was a user error on my part. It turns out that, for an exercise to be available for the download through the CLI, you need to go through the UI ({team-name} -> Your Solutions -> Start a new solution -> Pick the track and exercise) to indicate you want to work on it. After doing that I was able to download the new exercise. 

Closing this issue.

**Comment by iHiD** [comment]
Thank you for the update and no worries! 

It would be good if we provided a better error message though.
