### ISSUE TITLE
Request feedback on side exercise redirects to same page with no message

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism#5072]
Clicking on `Request Mentor Feedback` on side-exercise redirects to same page without any message.

Message remains same:

<img width="836" alt="Screenshot 2019-10-11 at 5 54 51 PM" src="https://user-images.githubusercontent.com/980783/66651297-4921c700-ec50-11e9-9412-d74f35f38db4.png">

Text above button still says `3 slots remaining`:

<img width="539" alt="Screenshot 2019-10-11 at 5 52 59 PM" src="https://user-images.githubusercontent.com/980783/66651174-04962b80-ec50-11e9-8248-c2fa7cff8c4e.png">

My profile: https://exercism.io/profiles/tejasbubane
Solution I encountered problem with (clojure track - clock exercise): https://exercism.io/my/solutions/51d30b604f0e4ff4b94fbe649ebf0988

**Comment by iHiD** [comment]
@kntsoriano Could you check this pls?

**Comment by sshine** [comment]
This appears related to #5075.
