### ISSUE TITLE
Solutions available via Google

### ISSUE THREAD

**Issue by wolf99** [exercism/exercism#5076]
Solutions are viewable via a google search.
For eample, try searching `exprational` (from the `rational-numbers` exercise). It is unique enough of a term that they should show up in the first page of results.

Two such results:
- https://exercism.io/tracks/javascript/exercises/rational-numbers/solutions/45f90077ed8e4dc5b54007357c1d8706
- https://exercism.io/tracks/typescript/exercises/rational-numbers/solutions/bb6f75b314524a22a87d673e390ab19d

I don't think this is what is intended. i.e. other users' solutions should be hidden until a specific user has submitted their first attempt at a given solution.

I think I recall this being a problem that was fixed once before (maybe in exercism v1?).

**Comment by iHiD** [comment]
Thanks for the report. It is intended. There's no value in "cheating" other than to yourself so we don't perceive it to be an issue, and we want the solutions to be there as they generate a lot of SEO/traffic for us.
