### ISSUE TITLE
Carry on coding message is wrong

### ISSUE THREAD

**Issue by markhm** [exercism/exercism#5077]
Hi team,

Smallest of smallest of issues. 

The block on the right side of an exercise page age mentions that there are n exercises _to be completed_, but n is actually the number that _have already been completed_ for a particular track. 

<img width="552" alt="Screenshot 2019-10-13 at 21 03 42" src="https://user-images.githubusercontent.com/1430451/66720485-86778780-edfd-11e9-820c-b55f653ddcf3.png">

**Comment by ngsikai** [comment]
Took a look at the underlying model code for this one, it is actually not showing how many _have already been completed_, _but how many have been submitted but not completed yet_.

I guess the intention is to motivate the user to move on to other challenges before coming back. 

Am I right on this one? @sshine

**Comment by iHiD** [comment]
> Took a look at the underlying model code for this one, it is actually not showing how many have already been completed, but how many have been submitted but not completed yet.

It's just absolutely shite code. I'll fix it.

**Comment by iHiD** [comment]
Deploying now. Thank y'all :)

**Comment by markhm** [comment]
👊🏻👍🏻
