### ISSUE TITLE
Removing feature to delete false submitted solutions

### ISSUE THREAD

**Issue by dnberlin** [exercism/exercism#5080]
Hello all,
thanks a million for offering such an amazing project! I am very passionate and hacking thought the different exercises. 

I pushed a wrong version by accident and couldnt find the delete button.

Would it be possible to add one?

Thanks,
Felix

**Comment by sshine** [comment]
Hi there! Sounds excellent. :-)

I'm closing this issue, as it's a duplicate, most recently of exercism/exercism#5067 from 10 days ago. See the comments made there for an overview and a status.

**Comment by iHiD** [comment]
@dnberlin Thanks for the lovely comments :)
