### ISSUE TITLE
Use "/usr/local/bin"

### ISSUE THREAD

**Issue by kfrohwein** [exercism/exercism#5084]
https://github.com/exercism/website-copy/blob/51067158972d960925614fb18b1ffa5b5a485871/walkthrough/index.html#L94

imho the file should be put inside of `/usr/local/bin` and not `/bin`. And I didn't fully test it on my Ubuntu but in any case you have to use `sudo` to put the file there. Last but not least the file should be owned by the root user and not my personal user.

https://unix.stackexchange.com/questions/8656/usr-bin-vs-usr-local-bin-on-linux
https://askubuntu.com/questions/427818/how-to-run-scripts-without-typing-the-full-path

If you agree on this I make a pull request with commands in regard :)

**Comment by sshine** [comment]
@kfrohwein: If this suggestion is based on a misunderstanding of `/` vs. `~`, should this issue be closed?

**Comment by sshine** [comment]
Alternatively, if this proposal is about installing the `exercism` binary via Ubuntu's PPA, Arch's AUR and similar package archives, such that the executable ends up in the system directory `/usr/local/bin`, then it should be assessed how to reliably maintain such package archives, e.g. via GitHub actions that perform automated releases.

**Comment by kfrohwein** [comment]
Oh I really missed the tilde... well sorry my fault... *facepalm*

Now I understand why you add this to path.

Well okay I personally prefer to put it to /usr/local/bin but yes that needs sudo.
I believe we can close this then.
