### ISSUE TITLE
Error in completing solution on site

### ISSUE THREAD

**Issue by krsanky** [exercism/exercism#5094]
I have submitted my solution for C: Resistor Color Duo
successfully using the CLI.

On the site I can see it at:
https://exercism.io/my/solutions/9325580845284036919bfe7d946c5e22
It has a link to "Complete" the solution:
https://exercism.io/my/solutions/9325580845284036919bfe7d946c5e22/complete

When I click that it says:
"Oh dear, we can't find that page. Sorry about that.

Continue by heading back to the homepage."

**Comment by camfilho** [comment]
I'm having the same problem on the Ruby Track.

**Comment by mvail52** [comment]
I think something is going on the with the website in general. It will not let me do anything besides view web page. It does nothing if i try to leave or join a track, redirects me randomly if i click on a course content. Is there any maintenance going on?

**Comment by B1tF8er** [comment]
I have the same issue in the C# track

**Comment by abatkin** [comment]
Looks like a bunch of things are broken.

If I look in my browser error console, I see a 403 when it tries to load https://assets.exercism.io/packs/js/application-b2843211cc037cee8702.js

When the "View community solutions" page opens, the console complains:
```
solutions:685 Uncaught ReferenceError: submitOnChange is not defined
    at solutions:685
```

**Comment by kotp** [comment]
It is being actively investigated right this minute... got in touch with the "active team" for where the sun is at now. Great having a global team!

**Comment by kntsoriano** [comment]
I just deployed a fix. Could you check if things work fine now?

**Comment by B1tF8er** [comment]
> I just deployed a fix. Could you check if things work fine now?

It works now in the C# track

**Comment by kotp** [comment]
Thanks @kntsoriano and all that reported...
