### ISSUE TITLE
Completed Exercise; Goes to Page Not Found

### ISSUE THREAD

**Issue by dalehurtt** [exercism/exercism#5095]
Using this account to log into Exercism, got an email from the mentor that the exercise is complete.

https://exercism.io/my/solutions/b8988dbb7fc243ce99d62ba6865f5d64

Click the "Complete Exercise" button (or the link at the top of the page) and it sends me to https://exercism.io/my/solutions/b8988dbb7fc243ce99d62ba6865f5d64/complete which contains the message "Oh dear, we can't find that page. Sorry about that.

Continue by heading back to the homepage." 

No amount of clicking links or buttons will allow me to move onward. It still shows one exercised completed and the current exercised approved.

Account: dalehurtt

**Comment by danjl1100** [comment]
I am getting the same error. Likely related to #5094...
Anyone know if site maintenance was going on recently?

**Comment by chaz-lambert** [comment]
I am also experiencing this issue.  Attempted to complete exercise and took me to error pages.

https://exercism.io/my/solutions/63089a38b2a7444c8497ad46aea57880/complete

Attempting to logout gives the same error.

**Comment by kotp** [comment]
This is a problem that is fairly widespread, but common for everyone.  I am trying to find out who has "beeper duty".

**Comment by brittGit** [comment]
I get the same error.

**Comment by kotp** [comment]
It is being actively investigated right this minute... got in touch with the "active team" for where the sun is at now.  Great having a global team!

**Comment by kntsoriano** [comment]
I just deployed a fix. Could you check if things work fine now?

**Comment by kotp** [comment]
Looking good for the 3 or 4 things I just tested.

**Comment by chaz-lambert** [comment]
Thank you. I was able to complete the section of my track and move on.

**Comment by kotp** [comment]
Thank you @chaz-lambert for reporting, and @kntsoriano for putting the change in place.  (and everyone that reported)
