### ISSUE TITLE
About contributions and becoming a track maintainer for exercism/elm

### ISSUE THREAD

**Issue by mpizenberg** [exercism/exercism#5096]
Hi there, I have few questions regarding contributions and becoming a track maintainer.

At the beginning of the month I animated a small elm workshop where some people, including me, contributed to the exercism/elm track (cf recent PRs: https://github.com/exercism/elm/pulls). I know it's work on free time and people are not always free, and so it seems that we are a little short on maintainers for the elm track since we haven't heard from anyone since then.

It would be really encouraging for the newcommers that participated in the workshop to have their PR reviewed in some way. Do you know of any maintainer familiar enough with exercism/elm to do so? Also if needed I could help maintaining that track when I can squeeze some time.

Best, and thank you for the exercism initiative,
Matthieu

**Comment by iHiD** [comment]
Hello! Thanks for reaching out :)

I'm sure @tuxagon would appreciate some support, and I can see if someone else can buddy up to help too. 

Are you currently a mentor on exercism and on our Slack?

(cc @exercism/elm)

**Comment by mpizenberg** [comment]
> Are you currently a mentor on exercism and on our Slack?

I've just now subscribed to it as a mentor for the elm track, user Matthieu Pizenberg. I see that is quite the organization you already have in place!

**Comment by iHiD** [comment]
Cool. If you 1-1 me on slack I can get you connected to the right places :)

**Comment by mpizenberg** [comment]
Great, It seems you've found me :) I'll probably reach out in the weekend or monday, a bit tired today.

**Comment by tuxagon** [comment]
I have been the sole, active maintainer for about 1-2 years and have sort of taken a hiatus because I got burnt out, changed jobs and didn't have much free time. Help is appreciated.

**Comment by iHiD** [comment]
Thanks @tuxagon! 💙

**Comment by mpizenberg** [comment]
Thanks a lot @tuxagon ! Would you mind if I ask on the elm discourse if a few other people are also willing to help with maintaining this track?
@iHiD sorry I've been busier than I hoped last weekend. Those PR will wait for November I guess ^^.

**Comment by iHiD** [comment]
We would always welcome some maintainers :) We're currently embarking on a project to redesign tracks (see [this issue](https://github.com/exercism/exercism/issues/5088)) and are looking to pad out all our language teams as part of this. We'll be announcing more details soon, but getting people onboard and interested now is definitely appreciated.
