### ISSUE TITLE
STOP MENTORING

### ISSUE THREAD

**Issue by fparrar** [exercism/exercism#5098]
Hi, 

¿Could you remove me from the mentor list please?

my user: fparrar

Thanks in advance,

**Comment by kotp** [comment]
If you want to uncheck the track for mentoring, you can find that page here: 
https://exercism.io/mentor/configure

**Comment by sshine** [comment]
@fparrar: I'm closing this issue as @kotp has provided a way for you to remove yourself from the mentor list.
