### ISSUE TITLE
Installing Python page links back to itself

### ISSUE THREAD

**Issue by davearonson** [exercism/exercism#5100]
I found an issue in the website-copy repo with a fairly easy fix (except the testing and verification now that this is such a huge site, so I haven't done that yet).  It wasn't marked community-pr-welcome (none are, over there), plus the fix goes in _this_ repo, not that one.  So, how do I get pre-agreement on it, as CONTRIBUTING.md implies I should?

As for the PR in question, long story short, someone complained that the Installing Python page links back to itself.  That is not limited to that link on that page, but true of _all_ the language-specific links in that list on such pages in _all_ language tracks.  I came up with an easy tweak that _omits_ the current page's link out of the list.  My fork is at https://github.com/davearonson/exercism-website and you can compare them at https://github.com/exercism/website/compare/master...davearonson:davearonson-omit-cur-pg-from-resources .

**Comment by sshine** [comment]
@iHiD: Would you accept this as a PR?

**Comment by iHiD** [comment]
Firstly, thanks for wanting to help out :)

> It wasn't marked community-pr-welcome (none are, over there)

The reason for this is that most community PRs tend to generate more work for us in reviewing/updating than if we just did the original coding internally. So we've stopped marking things with that label, at least for now.

> I found an issue in the website-copy repo 

As a sidenote, we probably should have moved that here or to exercism/bugs.

> So, how do I get pre-agreement on it, as CONTRIBUTING.md implies I should?

This was a good way :) You could also have posted a link on the issue and said "would you accept this", if you'd preferred. Either is cool.

> Would you accept this as a PR?

Yes, but please add a test to avoid me regressing your work in the future. I would suggest creating a file at `test/system/track_pages_test.rb` with something like:

```ruby
require 'application_system_test_case'

class TrackPagesTest < ApplicationSystemTestCase
  test "shows correct pages" do
    # Setup about the track. You might need to stub some of the git stuff
    track = create(:track)

    # Straight forward visit call
    visit track_path(track)

    # Assert the relevant selectors are here and that the correct one is missing
    assert_selector "...."
    assert_no_selector "...."
  end
end
```

If adding a test is too much hassle/work for you (I appreciate you are probably not looking to create a load of work for yourself), then I'm happy for you to create the PR still, but I reserve the right to assign an internal resource to create the test before merging. Right now, that'll be a couple of weeks from getting done as @kntsoriano is on holiday and I'm neck-deep in a million things. But that's fine as it **will** get done eventually :)

**Comment by kntsoriano** [comment]
@iHiD I'm back now and can work on this :)

**Comment by sshine** [comment]
From where do the links come that the template seeks to filter self-references out?

The track's repository? Would there be any point in just not mentioning those links there?

**Comment by iHiD** [comment]
I've opened a PR here https://github.com/exercism/website/pull/810 where @kntsoriano will add a test.

@sshine These are the links that are auto-generated based on the files [here](https://github.com/exercism/python/tree/master/docs). The nav is just the link of those things, and should be minus the current page you're looking at.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
