### ISSUE TITLE
Request to transfer account to another GitHub account

### ISSUE THREAD

**Issue by Noomann** [exercism/exercism#5102]
Hello,

I created my Exercism account a while ago using this GitHub account which I no longer use. I was wondering if it would be possible to have my account information transferred to my primary GitHub account to ease my workflow.

Thanks!

**Comment by iHiD** [comment]
Can you reply to this from the account you'd like it transfering to, confirming pls?

**Comment by Noomann** [comment]
I would like the account transferred from this account, 'Noomann', to my other account, 'bkonsela'

**Comment by bkonsela** [comment]
Hello!

**Comment by iHiD** [comment]
Thanks. I have no idea how to do this so will work it out when I get chance in the next couple of days.

**Comment by bkonsela** [comment]
Hello,

Any update on this? If it isn't feasible, I could just start resubmitting the old challenges under a new account. I didn't mean to make a whole lot of additional work for anybody.

Thanks!

**Comment by iHiD** [comment]
Sorry for the slow reply - I was away on holiday. Could you create a user with `bkonsela` on Exercism please? I can then try and do some magic :)

**Comment by bkonsela** [comment]
No problem. I will create a new account shortly.

Hope you had a pleasant holiday.

**Comment by bkonsela** [comment]
Done!

**Comment by sshine** [comment]
@iHiD: Did you perform some magic?

**Comment by bkonsela** [comment]
@sshine Thanks for the bump. I'm wondering if the best solution will end up being resubmitting my solutions under a new exercism account and just letting the mentors know. Not the end of the world either way, I suppose

**Comment by sshine** [comment]
@bkonsela: I think that would be the method in which you don't have to wait.

**Comment by iHiD** [comment]
So, I looked at this at the time, and was confused and so gave up for then. I've looked now and am confused still :)

- There's no exercism user with the handle of "Noomann"
- GitHub is just a method of logging into Exercism - your data isn't linked to a GitHub account as such. So I can move your login token from one account to another for you I think? (If you tell me the handle of the original account and we can verify that that's you)

**Comment by bkonsela** [comment]
I think that's what I found when looking into this as well, but I couldn't find the OAuth token on GitHub itself for my old account, so I wasn't sure if I could transfer it myself.

My original account handle should just be Noomann, but I'll have to log in with that account and check on exercism.

**Comment by iHiD** [comment]
> My original account handle should just be Noomann, but I'll have to log in with that account and check on exercism.

Cool - let me know :)

**Comment by Noomann** [comment]
Heh, just checked and It seems I put the cart before the horse making this issue. I updated my handle on exercism to `bkonsela` a while ago.

**Comment by iHiD** [comment]
I'm somewhat confused about what I should do then? Which Exercism account has the old exercises attached, and which Exercism account do you want them transferring to?

**Comment by bkonsela** [comment]
I'm sorry, I feel I've caused more confusion. I was hoping it would be as simple as transferring one GitHub account's OAuth token to the other.

I just changed the handle of my old account back to `Noomann` and updated the handle of my new account to `bkonsela`. I hope this makes things easier for you. I would like exercises transferred from `Noomann` to `bkonsela`.

I have not joined any tracks on my new exercism account yet, but if that will help please let me know and I'll do that.

Thanks again for your help on this!

**Comment by 0x6d6f7468** [comment]
I think this can be closed. I'm just going to resubmit all of the solutions I had already submitted and go from there because that's probably less painful for everybody at this point. Sorry for any confusion, and thank you all for your responses to this.

Hope you're all staying well.

**Comment by iHiD** [comment]
@0x6d6f7468 Sorry this never got sorted.
