### ISSUE TITLE
JS track not unlocking new exercise

### ISSUE THREAD

**Issue by miliberlin** [exercism/exercism#5103]
I did two exercises so far on the JS track.
I did "Hello World" while being in the unmentored track and then switched to mentored and did the "Two Fer" which has been approved by a mentor. But now the next exercises are not unlocking, probably because I did the "Hello World" exercised while being on the unmentored track and it has not been approved. How do I proceed from here?

**Comment by sshine** [comment]
Hello World should be auto-approved, but maybe it isn't?

@iHiD: I suspect that there is some state-sharing bug here.

**Comment by NobbZ** [comment]
@miliberlin I'm sorry that you are experiencing issues.

After you have done `two-fer` and it got approved by a mentor, did you complete the exercise and rate the mentor through the web interface? This is a mandatory step to unlock the following exercises.

**Comment by iHiD** [comment]
If @NobbZ's suggestion doesn't fix it for you, please provide screenshots of your track page and two-fer page to help us diagnose.

**Comment by miliberlin** [comment]
Ah okay, I totally missed that!
@NobbZ was right!

**Comment by iHiD** [comment]
He normally is :)
