### ISSUE TITLE
Go path luhn algorithm test suit is broken

### ISSUE THREAD

**Issue by NikosEfthias** [exercism/exercism#5106]
the test suit suggest 059 and 59 are valid but they are not therefor its impossible to complete the exercise with the given test suit

**Comment by NikosEfthias** [comment]
according to the readme 
![image](https://user-images.githubusercontent.com/9097437/68065739-e13e3800-fd46-11e9-8c16-fa9cc0182ce1.png)

059 will became 
0 5 18 -> 0 5 9 and 5+9 is 14 which is not divisible by 10

**Comment by NobbZ** [comment]
Those numbers are valid, you double every second digit from the **right**, so its only 5 to double. `0 (5) 9` -> `0 10 9` -> `0 1 9` -> `10` :heavy_check_mark:

As you can see, the test is valid and also fits the given specification.

**Comment by NikosEfthias** [comment]
oh i missed the part that it was supposed to be from the right :) thanks
