### ISSUE TITLE
Best place to ask questions about a particular problem's test case?

### ISSUE THREAD

**Issue by Manish-Giri** [exercism/exercism#5107]
I have some questions about a few test cases in the "Pig Latin" extra exercise in the Java track, but I'm not sure where to ask this/discuss about it.

Is there a forum for this, or something else?

**Comment by tejasbubane** [comment]
Initiate discussion in language-specific repository https://github.com/exercism/java 

You can also use this generic repo https://github.com/exercism/problem-specifications if you feel it applies is to other languages as well.
