### ISSUE TITLE
Integrate Keybase proofs into Exercism user profiles

### ISSUE THREAD

**Issue by ekingery** [exercism/exercism#5108]
I propose that we augment [exercism user profiles](https://exercism.io/profiles) by integrating [keybase identity proofs](https://keybase.io/docs/proof_integration_guide).

This would benefit Exercism users by allowing them to prove [their exercism profile](https://exercism.io/profiles) truly belongs to them. We would use the provided proof badge to link to a [user's keybase profile](https://keybase.io/docs/ekingery) once they proved their ID. 

On the flip side, Exercism would get some free marketing and referrals from having our user profiles show up as links in the keybase profiles of those users. Plus, we would be doing our part to nudge our users towards a safer, more secure internet experience.

For further information on Keybase proof integrations, see the [keybase proof integration guide](https://keybase.io/docs/proof_integration_guide) as well as the [Mastodon + Keybase Integration blog post](https://keybase.io/blog/keybase-proofs-for-mastodon-and-everyone). Thanks for the consideration and I'm happy to answer any questions, hear any enthusiasm, concerns, etc.

**Comment by kytrinyx** [comment]
Thanks @ekingery! Both @iHiD and I are in the middle of travel at the moment, but we'll talk through this and get back to you!

**Comment by iHiD** [comment]
Hey, so I would be up for this. However, as it'll involve some work on the website (both in terms of API - which is currently authenticated only - and in terms of the UI), I think I'd like to defer this until after we launch v3. We're also planning on launching Open Badges after v3, so this could work alongside that in the UI.

**Comment by ekingery** [comment]
Not that this request is on the radar, but it is worth noting that [Keybase was acquired by Zoom](https://keybase.io/blog/keybase-joins-zoom) in May of 2020 and it is not actively being developed (as of November 2020). We should hold off on this feature request until the Keybase project is resumed (if that ever happens).
