### ISSUE TITLE
snap package configuration woes.

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#5111]
Yesterday in the gitter there was a astudent, unable to configure the token.

They had 3.0.13 installed.

They were able to use `exercism configure --token=…` without any error message, though when trying to download, the CLI complained about the token were missing.

We figured out, after some try and error, that `exercism configure` wrote the config to `~/.config/exercism`, while `exercism debug` said config path were `~/snap/exercism/5/.config/exercism`.

I do not have a system available which had `snap` installed, therefore I can not confirm on another system right now.

**Comment by NobbZ** [comment]
PS: The problem occured to at least another 2 people asking in the gitter for help, my proposed fix of `mv $HOME/.config/exercism/* $HOME/snap/exercism/5/.config/exercism` is waiting for confirmation, as none of the users reported success or failure but disappeared.

**Comment by SSalekin** [comment]
@NobbZ  Thanks for your help, I  moved my `$HOME/.config/exercism/` folder to `HOME/snap/exercism/5/.config/`, and it fixed my issue. 
![Screenshot from 2019-11-23 17-21-06](https://user-images.githubusercontent.com/13296638/69486073-b01cc900-0e15-11ea-9b6b-5c24a75e2349.png)
