### ISSUE TITLE
Extremely long mentoring wait in C# queue

### ISSUE THREAD

**Issue by gorano79** [exercism/exercism#5112]
I'm doing exercises in the C# queue and it has been great so far with fairly quick and good responses. Now, however, on the exercise called "Allergies" the waiting time is 17 days! What's up with that?

**Comment by sshine** [comment]
Since mentoring is a voluntary task, we have no means to guarantee that mentors are available.

For comparison, the Haskell track currently has a ~10-22 days waiting time on average for the first five exercises.

**Comment by sshine** [comment]
I'm closing this issue as there's not much we can do about it.

@iHiD: We should perhaps set up a FAQ point linked to from where one sees the waiting time?

**Comment by iHiD** [comment]
It might also mean that allergies is a painful exercism to mentor on that track.

@sshine We could do, yes. That's a nice idea.
