### ISSUE TITLE
Access to Mentoring Slack

### ISSUE THREAD

**Issue by snsvrno** [exercism/exercism#5118]
Need to get another slack invite, my exercism accout wasn't using my main email (the same as github), I updated it but can't find a way to resubmit it.

**Comment by sshine** [comment]
@iHiD: Can you do this?

**Comment by NobbZ** [comment]
Hi @snsvrno it seems as if your email address is not part of your public profile on GitHub, could you please explicitely provide it?

Alternatively use your old account to send a private message to `@ihid` at the slack asking him for a re-invite with the new email address.

**Comment by iHiD** [comment]
You can also email me at jeremy@exercism.io if you want to tell me the correct email.
