### ISSUE TITLE
Explain mode abbreviations in solution queue

### ISSUE THREAD

**Issue by felixbuenemann** [exercism/exercism#5119]
The solutions in the review queue are currently marked with an abbreviation:

* CORE
* SIDE
* PM

However there is no explanation what these abbreviations mean.

I had to ask on the mentor Slack to find out.

I propose to mark these up as HTML abbreviations with a title that gives an explanation.

For example:

```html
<abbr title="Practice Mode">PM</abbr>
```

**Comment by sshine** [comment]
@iHiD: I believe this one is pretty easy.

I've seen questions about this three times in the last month, so I think it's worth investigating.

**Comment by felixbuenemann** [comment]
I'm a full stack dev, so if you point me at he right code location I can probably come up with a PR.

**Comment by sshine** [comment]
Yes, does seem like an issue suitable for a community PR.

The file is [app/views/mentor/dashboard/_solution.html.haml](https://github.com/exercism/website/blob/master/app/views/mentor/dashboard/_solution.html.haml).

It appears that this is only visible in the mentor dashboard and not for students.

Given the current structure of that HAML file, the easiest fix would be to change "PM" into "Practice" without the `<abbr>` tag. Let's hear what @iHiD thinks about restructuring the HAML file to add an `<abbr>` tag. (I don't really understand the HAML format well enough to quickly decipher what needs to be done, but it could be pretty trivial.)

**Comment by felixbuenemann** [comment]
HAML is pretty easy, you could just do:

```haml
%abbr.independent{title: "Practice Mode"} PM
```

However if you want to avoid possible styling issues , you can lose the semantic `<abbr/>`-Tag and just add the `title` attribute to the existing `div`-Tag:

```haml
.independent{title: "Practice Mode"} PM
```

While the title attribute on the div works nice on the desktop (it is shown on hover), it might be inaccessible on touch devices.
