### ISSUE TITLE
python track - Kindergarten Garden unit tests error

### ISSUE THREAD

**Issue by photonn** [exercism/exercism#5120]
Hi,

There is an error in both last two unit tests.

In "test_students_are_unordered_first_student", you should change: 

```
garden.plants("Patricia") --> garden.plants("Samantha")
```

and in test "test_students_are_unordered_last_student" you should change:

```
garden.plants("Xander") --> garden.plants("Roger")
```

Regards.

**Comment by photonn** [comment]
Right code:

`# Additional tests for this track

    def test_students_are_unordered_first_student(self):
        garden = Garden(
            "VCRRGVRG\nRVGCCGCV", students=["Samantha", "Patricia", "Xander", "Roger"]
        )
        self.assertEqual(
            garden.plants("Samantha"), ["Violets", "Clover", "Radishes", "Violets"]
        )

    def test_students_are_unordered_last_student(self):
        garden = Garden(
            "VCRRGVRG\nRVGCCGCV", students=["Samantha", "Patricia", "Xander", "Roger"]
        )
        self.assertEqual(
            garden.plants("Roger"), ["Radishes", "Grass", "Clover", "Violets"]
        )`

**Comment by iHiD** [comment]
cc @exercism/python

**Comment by cmccandless** [comment]
@iHiD, GitHub somewhat recently added the ability to [transfer issues to another repository](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository). Can you please transfer this to exercism/python?

**Comment by photonn** [comment]
Dont worry, I'll close this an open it at the right place. And maybe fix it myself as my first pull request to an open source project ;-P Thanks!

**Comment by iHiD** [comment]
@cmccandless Yep - always happy to move things :) I do like to check from the relevant team that they actually want me to move it first (ie, it's a valid issue) so as not to pollute language repos.
