### ISSUE TITLE
[Website issue] Some js code on pages isn't functional.

### ISSUE THREAD

**Issue by dector** [exercism/exercism#5124]
Exercism website isn't fully loading (some js code isn't working - e.g. mentor's dashboard code highlight, "approve and comment" etc) because `https://kit.fontawesome.com/e26ac64253.js` isn't loading.

```
$ ping kit.fontawesome.com                                                                                                                                                                         4203ms
PING m9r4n8i4.stackpathcdn.com (151.139.128.10) 56(84) bytes of data.
^C
--- m9r4n8i4.stackpathcdn.com ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 143ms
```

I guess we should load third-party resources asynchronously to avoid this kind of behavior.

**Temporary local fix for those who are afftected**: Block `kit.fontawesome.com` in `/etc/hosts/.

**Comment by iHiD** [comment]
Is this still an issue for you? (ie does that ping still fail?)

**Comment by dector** [comment]
It was an issues at the time of posting. Now `kit.fontawesome.com` is available.
But it would be nice to avoid this issue in the future as well. :smiley_cat:

**Comment by sshine** [comment]
Could this be achieved with a more reliable CDN?

**Comment by iHiD** [comment]
Probably. But I would expect FA to be pretty reliable, as it serves millions of sites, and secondly it's all done via licencing stuff (we're on pro) so I'm not exactly sure how it would work moving off it.

**Comment by dector** [comment]
It might be minor issue then. Let's hope it'll not happen in nearest future again. :smile:

**Comment by sshine** [comment]
Let's close this for now and address it again if it should occur again. It is a bit concerning that [fontawesome's CDN uptime stats](https://status.fortawesome.com) don't mention this downtime. I recall having experienced this a long time ago (>1 year ago).

**Comment by dector** [comment]
Sounds reasonable for me. :+1:
