### ISSUE TITLE
Can you run program yourself in IDE

### ISSUE THREAD

**Issue by hack1973** [exercism/exercism#5127]
I'm new to Exercism so I sorry if this is a stupid question. Can you run each problem/program your working on yourself in your IDE like I normally would when writing a program? Example I normally can run springboot/gradle programs in Intellij via gradle/applications/bootrun. I see you can run tests via IDE by running the test class which is similar to doing it via prompt. Just wondering because like to run programs while writing before testing.

**Comment by sshine** [comment]
When possible for a language track on Exercism, yes, we aim to be able to
code and test in ways as close to how you'd do professionally, but not
require it.

Judging by your mention of `gradlew.bat` I assume that you mean either Java
or Kotlin inside IntelliJ IDEA?

In that case, then yes you can. [This page] (
https://www.jetbrains.com/help/idea/work-with-tests-in-gradle.html) details
how, although I'm not sure if the exercise files exist in such a state that
IntelliJ immediately recognizes the Gradle file without additional
per-exercise configuration.

Perhaps you can verify this? And perhaps @exercism/java and
@exercism/kotlin maintainers have previously addressed this and have an
opinion.

There is after all many IDEs/editors and shipping additional project
configuration for the most common ones can be viewed as both neat and
invasive.

For any IDE/editor, binding a key to run `gradle test` in the exercise
directory will trigger testing, but for integration of the output, the
solution may vary per IDE/editor.

**Comment by eparovyshnaya** [comment]
*on behalf of Kotlin track*

Exercism provides niether IDE nor framework. The program you install is a command line tool for interacting with the site. 

So, to run say, a Kotlin program, you should have an entry point to it. We offer our students test suite for this purpose, but you can create `main` function for yourself. 

Thus, *run a problem you are working on yourself in your IDE* by default means precisely runing `gradlew test` from command line. 

You also can configure a progect in any IDE and run tests from it, as Kotlin track supplies all its exercises with sufficient build infrastructure. 

> Example for IJ Idea 2019.2 CE

After `exercism download` for a task you have proper project structure on your local file system: `gradle` and `src` dirs, `gradlew*` scripts and *build.gradle* script. Use *New* *Project from existing source* or *import project* by *gradle* model. 

Currently test suite comes uncompilable as there is no implementation by default, so the first step is to write some code in `src/main/kotlin` dir. We are working to provide stub implementations for all our exercises.

After the task is solved, test suite can be run either by creating JUnit run configuration or by one of test file context menu actions. 

All tests except the first one are delivered as `@Ignore`-ed, so you can  remove this annotations one by one following your own implementation pace.

**Comment by sshine** [comment]
@hack1973: I'm closing this issue as it appears answered.

Please feel free to reply in spite of this if you think a part of your question was not answered.
