### ISSUE TITLE
Add a button to copy the solution code to the clipboard

### ISSUE THREAD

**Issue by ScottHutchinson** [exercism/exercism#5129]
If necessary, this could be a mentor-only feature. It would facilitate the mentor workflow to be able to more easily copy the code into an IDE for testing and review. Copy short solutions is fairly easy, but copying longer solutions that do not fit in the window is more difficult without a copy button. An alternative solution would be to enable a "Select All" feature, maybe using the Ctrl+a keyboard shortcut to select just the code, not the entire web page.

The existing copy button for the "Download this solution" feature is also very helpful and works fine. But that requires more steps to get the tests all running than just a simple copy and paste. My mentor workflow is to use that button for the first review of a particular exercise, and then use copy and paste for subsequent reviews (if any).

An example of a web page that has such a button for copying code is https://docs.microsoft.com/en-us/dotnet/api/system.enum.getvalues?view=netframework-4.8#examples

Apparently, this was a feature once. See https://github.com/exercism/exercism/issues/1614 and  https://github.com/exercism/exercism/issues/2419.

**Comment by Nkemjiks** [comment]
Is this still open to worked on seeing that it is old?

**Comment by iHiD** [comment]
@Nkemjiks Hello :) We don't accept PRs to the website codebase. And we're currently rewriting everything anyway. But thank you for offering!

If you'd like to help us, we're looking for people to help us build out the new exercises for Exercism version 3. The main repo for this is at https://github.com/exercism/v3 and if you'd like more details please email me at jeremy@exercism.io :)

**Comment by Nkemjiks** [comment]
@iHiD I am interested in helping out. I have sent an email and will be waiting for your response. Thank you

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
