### ISSUE TITLE
Improve user interesting to continue tracks progress

### ISSUE THREAD

**Issue by shayanealcantara** [exercism/exercism#5130]
### Observation and feedback:
Giving some resources that are more intuitive or from easy understanding could improve the user interesting to continue the tracks progress and then the organization objective could be reached :)

### Propose:
My idea is to create a forum or even an community with easy access to unite recommended free resources to give more options to learn and then practice in Exercism plataform in a faster way. 
To be clear I understand that the Exercism core application is to propose a way for people learn new tech skills, so this is just a suggestion that came to me when practicing in the plataform. Like it's a new track to me, I missed some materials that people that had similar doubts from mine had when practicing.

I say this in my experience when studying to the bash track, in the [learning](https://exercism.io/tracks/bash/learning) page. Thanks!

**Comment by iHiD** [comment]
Hey. Thanks for the suggestion! :)

We're going to be doing exactly this sort of thing in the new Concept Exercises on v3 tracks (see [this issue](https://github.com/exercism/exercism/issues/5088) for some early details of the general ideas.

We currently have a working group looking at this, and will be opening up to our wider team of maintainers and the community in the next week or two. If there are any tracks you'd be interested in helping with, please let us know :)
