### ISSUE TITLE
Help to get started

### ISSUE THREAD

**Issue by filipareis-git** [exercism/exercism#5134]
Hello,

I've just registered on your website (Python track) but I don't understand how to submit the exercises. I already downloaded CLI, pytest and saved the exercises in Exercism folder. Could you please explain me how to proceed in Windows?

Thanks in advance.

**Comment by NobbZ** [comment]
Open a terminal, us  e the `cd` builtin to navigate to your exercises folder and then do `exercism submit <filename>` to submit your solutions file.

For the `hello-world` exercise in python the full command is typically `exercism submit hello_world.py`.

**Comment by sshine** [comment]
@filipareis-git: I'm closing this issue because of no response. Feel free to get back and we can open it again.
