### ISSUE TITLE
Publishing wrong Attempts

### ISSUE THREAD

**Issue by geoorge1d127** [exercism/exercism#5137]
My name is George Thompson and I am a Master’s Computer Science student at North Carolina A&T. I am working on a Master’s thesis relating to Prolog Fault Localizaiton. I am e-mailing you because it would help me out a lot if I could get my hands on some “faulty” prolog models.

As I understand it, Exercism works (At least the Prolog track does) by running a set of predefined tests on the submitted program. On GitHub, I noticed that you guys publish a correct attempt but I was wondering if you guys would be willing to publish some submissions that were not correct, as this would help me greatly on my Master’s Thesis.

Thanks

**Comment by iHiD** [comment]
Drop me an email at jeremy@exercism.io :)
