### ISSUE TITLE
Website: operators in language snippets have a different background colour

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5138]
The background colour behind operators in the code snippet on track pages is white, the rest of the background is greyish:

![grafik](https://user-images.githubusercontent.com/20866761/71306505-5e9a3680-23e1-11ea-8b3b-7f547860636b.png)

![grafik](https://user-images.githubusercontent.com/20866761/71306508-6d80e900-23e1-11ea-8e87-fb345bf8cdfb.png)

Not sure if that's intended or not. It's hard to spot but it looks slightly off once noticed.

**Comment by iHiD** [comment]
Interesting. This isn't the case for me. What browser/OS are you on?

<img width="655" alt="Screenshot 2020-01-06 at 11 24 07" src="https://user-images.githubusercontent.com/286476/71815360-1d5b8500-3077-11ea-958a-e01a0e1d14a1.png">

**Comment by SaschaMann** [comment]
Windows 10 Pro, Build 18362. Firefox 71.0 (64-Bit) but the same happens in Chrome 79 (64-Bit). Ad-/Scriptblockers that could interfere with fonts/CSS are disabled for exercism.io and all sources that the site loads assets from, only the GA Tracker is blocked but I don't know why that would affect this.

**Comment by SaschaMann** [comment]
Perhaps this helps to find out what causes it:

![grafik](https://user-images.githubusercontent.com/20866761/71857521-2173bb00-30e8-11ea-930e-c9b79573920f.png)

**Comment by rpottsoh** [comment]
What I see:
![image](https://user-images.githubusercontent.com/6978003/71860592-8667ea80-30c1-11ea-94bc-01274ab2f0ab.png)

![image](https://user-images.githubusercontent.com/6978003/71860638-af887b00-30c1-11ea-8d38-8837bdc91d7e.png)

Windows Version:
![image](https://user-images.githubusercontent.com/6978003/71860686-db0b6580-30c1-11ea-8044-31659f84ec58.png)

Same as @SaschaMann.

**Comment by sshine** [comment]
I experience the same.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
