### ISSUE TITLE
Go Gigasecond exercise - link in main file does not have a comment about package gigasecond 

### ISSUE THREAD

**Issue by ashleyelder** [exercism/exercism#5139]
the gigasecond.go file from this exercise has a link that says it should have a comment about the package gigasecond but that linked page doesn't have any information about it 

> // Package gigasecond should have a package comment that summarizes what it's about.
> // https://golang.org/doc/effective_go.html#commentary

**Comment by iHiD** [comment]
Hi @ashleyelder. If you submit your solution (if you've not already), you can ask your mentor that when they pick up your work.

FWIW - I think you're defining the package gigafile, and that the instruction is telling *you* to add a comment about the file you're writing, and linking you to a page that explains why and how the comment should be written.
