### ISSUE TITLE
Switching from practice mode to mentor mode

### ISSUE THREAD

**Issue by BMD-518** [exercism/exercism#5140]
I started the mentoring mode but wanted to try other activities while waiting for feedback. Now I'm in practice mode with no clear way of switching back. Can anyone advise me on how to get back into mentored mode?

Thanks!

**Comment by kellydanma** [comment]
I had the same problem. If you scroll to the bottom of the language track's page, there is a `Danger Zone` (with options to Pause track, Leave track, or Switch to Mentored Mode).

**Comment by BMD-518** [comment]
I was starting to get a little frustrated. It's funny though, because I think this is how I got into practice mode to begin with. Thank you for responding!
