### ISSUE TITLE
Viewing some suggested solution

### ISSUE THREAD

**Issue by sreenadhp** [exercism/exercism#5144]
This is actually a suggestion and not an issue. I am doing the python track and I see that there isn't sufficient mentors to give feedback. So, I would like to suggest that once submitted. To have the option to view suggested solutions, like a couple of solution/s that the mentors / an experienced python develop would give. This way I can understand and learn from different people.

In the current system of viewing other students work, I have no clue about the skill level of the author. Sorting it by stars, who starred it? Are the starred solutions right? Based on the comments, I have to guess if its right or wrong. What is the skill level of the person commenting? As a student myself, I am clueless and following my gut.

FYI: I don't mean to disrespect anyone. My python skill level is low. All I am trying to do is learn and just ensure that the source I am using to learn is good. Please dont take it personally. Anyone I mention below, please dont take it personally. I am just expressing my viewed and looking for feedback. No disrespect intented. I am just trying to fix the shortage of mentor issue.

Just state my latest situation, I just completed [Robot Name - Python](https://exercism.io/tracks/python/exercises/robot-name/solutions?order=num_stars). Looking at couple of top starred works:

1. [70 ⭐, 5 💬](https://exercism.io/solutions/d89f8f389d7d4696929b4952eea14379) - 3 positive comments, 1 negative and 1 from OP. I don't know if its a good solution, I am guess its not. 
2. [19 ⭐, 3 💬](https://exercism.io/solutions/a9ec3ff7452b85a7b8968929) - 3 neagtive & I too dont think its good.
3. [10 ⭐, 0 💬](https://exercism.io/solutions/57d6cf8a88414355b0360b69955524c1) - Seems good
4. [6 ⭐, 3 💬](https://exercism.io/solutions/79dc7b772834423195854b1be5b95857) - All positive and I like it too.
5. [4 ⭐, 2 💬](https://exercism.io/solutions/d0ceffe520eb9a67d38b4a75) - positive comments & seems good
6. [3 ⭐, 3 💬](https://exercism.io/solutions/3eea00c16e0e42aba5d86edc7a944ea3) - not sure
7. [3 ⭐, 3 💬](https://exercism.io/solutions/895b37d60d2b4d9b91151736e1a7fc07) - not positive
8. [2 ⭐, 0 💬](https://exercism.io/solutions/78ae71f5b82f43ceb05eea5515017923) -  not sure

The ability to view their other code is not there.

**Comment by kwikiel** [comment]
Ok, so do you want "canonical solutions" right? 

I don't think that having an easy way to get an answer would help - the point of the exercism is to exercise - the more time and sweat you put into trying to solve the problem the better.

**Comment by sreenadhp** [comment]
> Ok, so do you want "canonical solutions" right?

 No clue what that mean exactly. But to make a guess, "accepted solutions". If yes, that is what I meant. 

> I don't think that having an easy way to get an answer would help - the point of the exercism is to exercise - the more time and sweat you put into trying to solve the problem the better.

How is that easy? You display the solutions after the work is submitted. But the queue to get the work reviewed is long. All I am saying is there is more than one way to code, also there are many bad practices - only an experienced developer can figure that out. So, instead of listing all solutions to the student and making them pick. Just list the solutions moderated by serious developer.

Even if after that the student wants the code to be review, then request for a review. This will reduce the queue.

**Comment by sshine** [comment]
Your ideas are very reasonable! So this addresses what we call the "community solutions" page, and it's been mentioned in several other open feature requests:

- From a mentor's perspective: #4865 (idea: link mentor notes and community solutions)
- From a student's perspective: #4732 (idea: links to existing solutions should be shown to students after first submission), #4307 (idea: highlight solutions of mentors on community page), #4206 (idea: retrieve other solutions by the same author), and probably most significantly, **#4067 (idea: order of community solutions is suboptimal)**.

The "community solutions" page might get renewed within 2020, but I don't think it's been actively prioritized yet with so much stuff going on with Exercism v3 (#5135, [this blog post](https://exercism.io/blog/call-for-maintainers-2020)). Leaving this issue open for future discussion will not be in vain, so thanks a lot so far!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
