### ISSUE TITLE
Slack Invitation

### ISSUE THREAD

**Issue by MilaDog** [exercism/exercism#5146]
Recently found Exercism, and have been enjoying it.

Is it possible to get an invitation for the Slack team, please? And, is there only a Slack team, or also other platforms, such as Discord etc. 

Thank you 😄 

###### Need anything else, just message me

**Comment by iHiD** [comment]
Hello! Glad you're enjoying it :) 

The Slack room is for mentors and contributors. If you sign up to mentor, you'll receive an invitation. Thanks!

**Comment by kotp** [comment]
There is also https://gitter.im/exercism/support and other room from there.
