### ISSUE TITLE
error permission denied on exercism download

### ISSUE THREAD

**Issue by miwojc** [exercism/exercism#5152]
exercism download --exercise=isogram --track=python

finishes with Error: permission denied

when there is a space (" ") in the path to workspace

also gives error when there is no space in the path

system: ubuntu 18.04

exercism version 3.0.13

i can manually create directory using mkdir "/path to workspace with spaces/exercise"

also i can manually create directory using mkdir path_to_workspace/exercise

**Comment by kotp** [comment]
Is the problem that the `exercism` is not executable?

I get the same error message if I make the `exercism` file not an executable file.

**Comment by miwojc** [comment]
I am not sure what's the problem, It works on Windows, but Linux (Ubuntu 18.04) gives me the `Error: permission denied` when i try to download the exercise with command: `exercism download --exercise=isogram --track=python`

**Comment by iHiD** [comment]
@miwojc: @kotp is suggesting you make exercism executable. You can probably try doing something like:
```
chmod a+x `which exercism`
```

or maybe (depending on how it's installed)
```
sudo chmod a+x `which exercism`
```

**Comment by miwojc** [comment]
thanks @iHiD 
tried that, executed command `sudo chmod a+x `which exercism` but still can't download the exercise  with `exercism download --exercise=isogram --track=python` nor with `sudo exercism download --exercise=isogram --track=python `
gives the same error message as before:
`Error: mkdir /home/exercism: permission denied`

**Comment by iHiD** [comment]
What does `sudo ls /home/exercism` give you?

**Comment by miwojc** [comment]
ohhhh
should have been `/home/miwojc/exercism`
then it works :smile: 
thank you for helping troubleshoot this @iHiD !

**Comment by iHiD** [comment]
No probs. Have fun!
