### ISSUE TITLE
exercism configure error : base API url cannot be reached

### ISSUE THREAD

**Issue by umesh3034** [exercism/exercism#5154]
Hi,

I am using ubuntu app over windows 10 OS using wsl. Getting below error for exercism config.

===================

umesh3034@L-156149334:~$ exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           linux
Architecture: amd64

Configuration
----------------
Home:      /home/umesh3034
Workspace: /home/umesh3034/exercism (default)
Config:    /home/umesh3034/.config/exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 267.8011ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: x509: certificate signed by unknown authority]
    * 989.5458ms

If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
umesh3034@L-156149334:~$ exercism configure --token=88e117b6-829b-4f8f-9063-fddcde102fac
Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.

Get https://api.exercism.io/v1/ping: x509: certificate signed by unknown authority
umesh3034@L-156149334:~$

**Comment by ccare** [comment]
Hi @umesh3034 , two immediate thoughts:

1) Have you tried using the Window's CLI direct on Windows? It would be interesting if the main OS works, I've seen reports (on other projects) that WSL certificate authorities are not always up to date. Could be completely the wrong problem of course, but if it also fails on Windows then it'll point to a different problem.

2) Since the CLI is reporting an incorrectly signed certificate, it would be interesting to know more about that. Could you run the following in the WSL shell (assuming curl is installed) ?

```
curl --insecure -v https://api.exercism.io 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
```

Thanks!

**Comment by NobbZ** [comment]
@umesh3034 please also make sure to reset your token ASAP, visit https://exercism.io/my/settings to do so.

Other than that, please make sure your WSL linux is up to date, especially the `ca-certificates` (debian based systems at least).

**Comment by umesh3034** [comment]
@ccare 

for #2, output is below:


`umesh3034@L-156149334:~$ curl --insecure -v https://api.exercism.io 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=exercism.io
*  start date: Jun 12 00:00:00 2019 GMT
*  expire date: Jul 12 12:00:00 2020 GMT
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Connection #0 to host api.exercism.io left intact
umesh3034@L-156149334:~$
`

**Comment by umesh3034** [comment]
> @umesh3034 please also make sure to reset your token ASAP, visit https://exercism.io/my/settings to do so.
> 
@NobbZ 
Hi,

I reset the token and tried again, works now , thanks :-)

```
umesh3034@L-156149334:~$ exercism  configure --token=b5bd32c3-119c-4dc2-ac62-aff0f387d455

You have configured the Exercism command-line client:

Config dir:                       /home/umesh3034/.config/exercism
Token:         (-t, --token)      b5bd32c3-119c-4dc2-ac62-aff0f387d455
Workspace:     (-w, --workspace)  /home/umesh3034/exercism
API Base URL:  (-a, --api)        https://api.exercism.io/v1

```

**Comment by umesh3034** [comment]
fixed , @NobbZ

**Comment by NobbZ** [comment]
Well, then it wasw just some hickup or outdated config, also please reset your token *again*. It is not supposed to leak, it is a "secret", similar to a password!
