### ISSUE TITLE
REST request failed: error sending data

### ISSUE THREAD

**Issue by apoorva-dixit** [exercism/exercism#5158]
Hi, 
I am getting this error while trying to install the CLI

**Comment by NobbZ** [comment]
Additional information from the gitter:

The operating system in use is a Windows 10, and the error happens in the "Windows Installer Application".

**Comment by iHiD** [comment]
cc @exercism/windows

**Comment by rpottsoh** [comment]
Screen shots would be great to have, thanks.

**Comment by sshine** [comment]
I'm closing this issue because @apoorva-dixit hasn't responded. Please feel free to get back, though, and we'll reopen it! It surely would be nice to have bugs fixed.
