### ISSUE TITLE
CMake and Boost - Windows VS 2019 (CPP Track - Gigasecond)

### ISSUE THREAD

**Issue by CallumIllsley** [exercism/exercism#5160]
I'm trying to get boost working so I can complete the gigasecond task but am struggling to get boost working properly.

Here is the error:

**Comment by CallumIllsley** [comment]
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR date_time) (Required is at
  least version "1.58")		C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake	137

**Comment by NobbZ** [comment]
As far as I know, boost was a constant source of pain across all platforms, especially on windows.

The necessity of using boost has therefore removed from all exercises except a small number. All of those are related to time/date problems as far as I remember.

If they were not already side exercises, they have been made side, at least to my knowledge.

So they should not be mandatory and block you from progress.

Anyway cc @exercism/cpp

**Comment by patricksjackson** [comment]
@NobbZ is correct about Boost and Windows. Gigasecond and Meetup are the two remaining Boost exercises, and they're optional precisely so you can skip them if you have any issues with Boost. I would have preferred to remove them if I could.

If you'd like to still use VS 2019 with the exercises here is a current thread that has some instructions - https://github.com/exercism/cpp/issues/330

Though if you are at all familiar with linux, it is honestly easier to do those exercises on Windows by editing them with a normal text editor (VSCode or something), and using [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) to compile/run it.

**Comment by CallumIllsley** [comment]
Thanks for the reply, i'll skip this task for now then!
