### ISSUE TITLE
Install of Excercism and how to do Tasks

### ISSUE THREAD

**Issue by DeadPortal** [exercism/exercism#5162]
Hi, 
I did your "get started" - "begin walk-through" steps, within my c# track. I did configure exercism configure:

You have configured the Exercism command-line client: 

My question is now what I do next? I did copy this: exercism download --exercise=gigasecond --track=csharp ; and pasted it in to my powershell. It downloaded something, but what do I do with the files it downloaded?

**Comment by iHiD** [comment]
Read the README.md there :)

**Comment by sshine** [comment]
I'm closing this issue because no response was made in 18 days.

@DeadPortal: If you're still experiencing problems, feel free to get back in this thread.
