### ISSUE TITLE
How to submit or check if it works on Windows.

### ISSUE THREAD

**Issue by LedjoLleshaj** [exercism/exercism#5163]
it has been a while now that i try to sumbit a file but without success.I am currently working on windows 10 and i want to learn how to program in C language.I started doing the second exercise the one called Armstrong numbers, and i think it is ready and wanted to submit it .Tried submitting it by using the command-->

```
C:\Users\admin\Desktop>exercism submit NumArmstrong.c
```

but the response i get is-->

```
Error: not in workspace.
```

I serached for tutorials in youtube and google but still could not get anything done.
I would be grateful if you could help me with this problem, and thanks for your time.

**Comment by NobbZ** [comment]
You need to submit the file from the folder where the exercise was downloaded to, such that the CLI tool can extract track and exercise from the storage path relative to the exercism workspace.

Also expected names for the armstrong files in c are `src/armstrong_numbers.c` and `src/armstrong_numbers.h`.

**Comment by sshine** [comment]
I'm closing this issue because it was answered and no response was made in 18 days.

@LedjoLleshaj: If you have not made this work yet, feel free to respond.
