### ISSUE TITLE
Feature request: Visual indication of side-exercises status

### ISSUE THREAD

**Issue by blitzmann** [exercism/exercism#5164]
Hello all,

Currently, side exercises look like this:

![image](https://user-images.githubusercontent.com/3904767/72376462-fa1a8080-36db-11ea-9b7d-9a2edbfa6e40.png)

It's not possible to, at a glance, see which ones are completed, in progress, or simply unlocked. You have to hover over each one, which then tells you it's status along with the title at the top. It would be nice to have something like this (I'm horrible at colors, but you get the idea).

![image](https://user-images.githubusercontent.com/3904767/72376866-b5431980-36dc-11ea-8fde-7cc9a565fb55.png)

A soft yellow could indicate in progress, and a greenish could indicate completed.

**Comment by blitzmann** [comment]
For anyone running into this that wants to see this in action now before any sort of update, created a quite css that can be applied. Install this Chrome extension (I'm sure Firefox has a similar extension in their store):

https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb?hl=en

Then apply this css to the track page:

```
a.unlocked-exercise {
  position:relative;    

}

a.unlocked-exercise[data-status]:after {
  content: '';
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 0 10px 10px 0;
  border-color: transparent;
  right: 0;
  top: 0;
  position: absolute;
}

a.unlocked-exercise[data-status='Completed']:after {
  border-color: transparent #3AB292 transparent transparent;  
}

a.unlocked-exercise[data-status='In progress']:after {
  border-color: transparent #F9C57F transparent transparent;  
}

a.unlocked-exercise[data-status='Unlocked'] {
  opacity: 0.35;
}

a.unlocked-exercise[data-status='Unlocked']:hover {
  opacity: 1;
}
```

This give the following visuals:

![image](https://user-images.githubusercontent.com/3904767/73277756-9c486700-41b8-11ea-9ae5-9830ce5e2e74.png)

I went with a wedge indicator as the background color clashed with the icons (which are images instead of fonts, so can't change the color easily). I also reduced opacity of unstarted exercises to make the starts / completed ones more in focus. Obvious you can play around with it how ever you want (eg reduce opacity of those that are done instead). But I quite like how this came out.

YMMV, didn't really test how this CSS affects other parts of the site if they use the same classes elsewhere

**Comment by iHiD** [comment]
@blitzmann Thanks for this. I think we got half-way through doing this then stopped. FWIW all this UI will be changing in Exercism v3 and I'll be sure to incorporate this there. In the meantime I'll try and get chance to add a patch soon.

**Comment by blitzmann** [comment]
Hi @iHiD, glad to hear it. 😊

Is there a reason exercism itself is not open source? I feel like a lot of such issues could be fixed via the community, reducing the overhead of the exercism team. We are, after all, all programmers! 😛

**Comment by sshine** [comment]
@blitzmann: As @iHiD has phrased it to me once, it's a not-for-profit company that relies heavily on open source. And yes, as you noticed, the website actually *is* open source, but it isn't accepting community PRs unless previously agreed upon.

The experience report so far is that it takes more time for one-off contributors than it would to just make a change yourself. (Having received a bunch of PRs during Hacktoberfest 2019 I can only say that this is very true. I probably spent 4x the time on each PR than if I had just completed the task myself.)

This issue relates to #5155 in which better navigation is requested in practice mode. It sounds on @ihid's comment above, however, that what he mostly has planned is the navigation for what is to become "learning mode", the v3 successor to "mentored mode" of v2.

**Comment by a8t** [comment]
Thanks for the CSS, @blitzmann. I tweaked it for my own usage using Firefox's Stylus plugin.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
