### ISSUE TITLE
Waiting a long time for a feedback

### ISSUE THREAD

**Issue by MikHulk** [exercism/exercism#5168]
Hello,

I am stuck on the "Atbash Cipher" exercice of the Rust Track wating for a feed back. 

All tests pass. Yesterday I have this message:

> There are currently 26 solutions ahead of this in the Rust queue, and 1 ahead in the Atbash Cipher queue. The median waiting time for mentoring on this exercise is about 4 hours. Learn more about how mentor queues work. 

Right now:

> There are currently 27 solutions ahead of this in the Rust queue, and 2 ahead in the Atbash Cipher queue. The median waiting time for mentoring on this exercise is about 17 hours. Learn more about how mentor queues work. 

How is it possible ? It seems a solution comes from ahead mine. Perhaps something went wrong in the queue. 

Anyway, thank you for this amazing website.

**Comment by iHiD** [comment]
Thanks for the nice message. I imagine that a solution that was already being mentored timed out and dropped back into the queue (and therefore ahead of yours).

At the moment there is a big push towards version 3 of exercism which is taking up a lot of people's time, so mentoring is slower than normal. Sorry. You may wish to switch to Practice Mode if you don't want to wait.

**Comment by MikHulk** [comment]
Hi thank you for your prompt reply and the explanation which comes from.

No problem for the feedback. I can wait, I was jus afraid my post was lost somewhere.
