### ISSUE TITLE
Unable to submit solutions under a folder with spaces in his (or parents) name 

### ISSUE THREAD

**Issue by rafareino** [exercism/exercism#5171]
## What is the problem

After the last update (3.0.13) I am having problems with submitting my solutions.

I have got errors saying something around the lines of 
"cannot create c:\user\my.name\your folder has spaces\exercism"

## Workaround

as a wkaround I used 
`cygpath -d "c:\user\my.name\your folder has spaces\exercism" `
to obtain the DOS formated path, like
"c:\user\my.name\yourfo~1\exercism"
and then,
`exercism -w "c:\user\my.name\yourfo~1\exercism"`
(with quotes)
now I am able to submit, but others may have problems with this solution.

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\[redacted]
Workspace: C:\Users\\[redacted]\SCM\exercism
Config:    C:\Users\\[redacted]\AppData\Roaming\exercism
API key:   782e*****************************68e

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 623.333ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 3.5355471s

**Comment by NobbZ** [comment]
In the posted troubleshooting output, there is nothing that would cause `exercism` to create a path that includes spaces.

Could you please tell us the exact command you run and the *unredacted* output it produces?

**Comment by sshine** [comment]
@rafareino: Are you interested in resolving this bug, or should this issue be closed?

**Comment by sshine** [comment]
I've closed this issue. Feel free to get back and either comment or reopen it if it's still relevant.
