### ISSUE TITLE
Should people on the Rust mentor track switch to practice mode?

### ISSUE THREAD

**Issue by germania** [exercism/exercism#5174]
Hey guys,

I've been trying to work through the Rust track, but it seems I have to wait several days for a thumbs up from a mentor (certainly not the 3-4 hours it's been quoting).  In watching it since last Wednesday or so, only perhaps 5 solutions have been reviewed, with a backlog of 64 items as of this morning.

I fully understand the mentor reviews are volunteer work for a free service, and very much appreciate all of the work that continues to go into Exercism.  I would love to know whether there's a temporary holdup, or if it's a longer term shortage of mentors, so I can get the most out of this fantastic resource.

Thanks!

**Comment by lewisclement** [comment]
We're certainly a bit short on mentors. Until recently I've put in a lot of time reviewing, which probably has brought the predicted waiting time down.

**Comment by coriolinus** [comment]
I ended up switching to practice mode fairly early on; the mentor shortage is a real issue. We're hoping that v3 of the site will substantially help, but that's not going to be out even in beta mode for several months yet. My recommendation is yes: particularly if you're enjoying the more difficult exercises, you'll get more out of it as it stands right now by just switching to practice mode.

**Comment by germania** [comment]
Understood, thanks for the feedback guys - keep up the great work!
