### ISSUE TITLE
No Feedback for  178 Days.

### ISSUE THREAD

**Issue by tao524** [exercism/exercism#5175]
I have been waiting for feedback on [TypeScript | Bob | Exercism](https://exercism.io/mentor/solutions/bf2f6d9543874fc69fde669673c4022c).

Could you take a look? Thank you.

**Comment by iHiD** [comment]
Hello. Sorry for your wait. Are you in mentored or independent mode?

**Comment by tao524** [comment]
Hello. I am in mentored mode.

**Comment by tao524** [comment]
I have got feedback. Thank you.
