### ISSUE TITLE
Newbie question - getting started.

### ISSUE THREAD

**Issue by Sampajanno** [exercism/exercism#5178]
Apologies all. I'm struggling to get started. I'm all set up no problem. I can download, upload problems and solutions etc.

But, can anyone point me to a place I can better understand how to use exercism properly? I'm not clear on how to use the tests, what the export key word does etc. 

Any guidance would be really appreciated.

**Comment by sshine** [comment]
Hi @Sampajanno, and welcome aboard!

So all the exercises download in the same way regardless of the language you're practicing. Depending on the language track you've chosen, each exercise page it should come with some track-specific instructions on how to run the tests. For example, in Haskell it says you should run `stack test`

> I'm not clear on *[...]* what the export key word does

I'm not sure what you mean by this. But it sounds like you're asking for programming language specific help. So while Exercism features handcrafted feedback to solutions it doesn't actually offer any kind of in-depth teaching from ground zero. So maybe you're at a point where a book, online tutorial (written or YouTube) is where you'll get the most traction in combination with doing Exercism exercises?

**Comment by Sampajanno** [comment]
Thanks sshine - that's all good and clear thanks. I guess what I'm really not clear is how my code should link to the 'test suite', what I should be doing and how before I upload my proposed solution (I'm on the JS track). Any documentation on this anywhere? I've looked but can't find any. Apologies for taking up time with such simple questions.

**Comment by sshine** [comment]
@Sampajanno: I don't think it is documented any further than on the links on each exercise page. Some of the guides are specific to the language you're learning (e.g. how to install a compiler/interpreter for the language, how to install necessary libraries for the test suite to work, and so on), other guides are about how to install and use the `exercism.exe` command-line program.

1. Go to exercise's page, copy-paste command that downloads that particular exercise, e.g.:

   ```
   exercism download --exercise=sum-of-multiples --track=elm
   ```

2. Running that command in a command-line gives something similar to:

   ```
   Downloaded to
   /home/simon/exercism/exercism/elm/sum-of-multiples
   ```

   If you're on Windows or Mac that directory will look a bit different.

3. Go to that directory and run whatever command the guides for your language suggest, assuming you've made the prerequisite work for those commands to function. For example, with Elm I'd do:

```
$ elm-test

elm-test 0.19.1-revision2
-------------------------

Running 1 test. To reproduce these results, run: elm-test --fuzz 100 --seed 35141846945031 /home/simon/exercism/exercism/elm/sum-of-multiples/tests/Tests.elm

↓ Tests
↓ Sum Of Multiples
✗ [3, 5] 15

    This test failed because it threw an exception: "Error: TODO in module `SumOfMultiples` on line 6
    
    Please implement this function"



TEST RUN FAILED

Duration: 83 ms
Passed:   0
Failed:   1
```

But that will vary for the language, which you've still not been specific about.

I think this is as far as I can help you.

**Comment by Sampajanno** [comment]
OK thanks. Appreciate your inputs. I'll see if I can get things working.

**Comment by Sampajanno** [comment]
Just for the record I got it sorted. I had node install globally so when I checked the version it appeared that all was as it should be, but I needed to install it in the same folder as the files I was working on. All is well now! Thanks!!
