### ISSUE TITLE
What's the difference between signing up via github acc. or via name-email-password?

### ISSUE THREAD

**Issue by PavelSch** [exercism/exercism#5179]
Can you please explain somewhere, via some FAQ or so, what's the difference between these two? Once you decide to sign in with github, it seems you will find the answer. But would be fine to know the consequences for the people who are making such a choice for the first time like giving this kind of [link](https://help.github.com/en/github/authenticating-to-github/authorizing-oauth-apps) to the FAQ or Getting started.

**Comment by iHiD** [comment]
If you sign in via email/password, we store your email and (encrypted) password, and you can use them to log in next time. If you sign in via GitHub, we store your GitHub ID and use that to log you in next time. That's about the only difference :+1:
