### ISSUE TITLE
Failed download due to API error response

### ISSUE THREAD

**Issue by ysela** [exercism/exercism#5181]
Upon attempting to download the 3rd core exercise for the JavaScript track, I receive the error:

Error: failed to parse API error response: invalid character '<' looking for beginning of value

As visible below, I am using the latest version, such that previous solutions to similar problems don't seem to apply here.

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\bob
Workspace: C:\Users\bob\Exercism
Config:    C:\Users\bob\AppData\Roaming\exercism
API key:   cc6d*****************************e5d

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 189.6149ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 864.0925ms

**Comment by ysela** [comment]
Discovered local issues were keeping the API from being accessed.

**Comment by TravisSpangle** [comment]
What were the local issues?

**Comment by ysela** [comment]
In my case there was a router-based firewall that was stopping the data from being transferred properly. 
I am not sure what it recognized in that exercise that wasn't in others, but after toggling the settings, it worked.

**Comment by TravisSpangle** [comment]
Thank you, my problem was that I hadn't initiated the challenge through the teams site. I didn't know I had to do that!
