### ISSUE TITLE
CSS on exercism.io website is not functioning while using Chrome

### ISSUE THREAD

**Issue by piara108** [exercism/exercism#5183]
The CSS on the exercism.io site does not seem to be working on Chrome specifically. I've tried it on FireFox and Safari and both browsers load exercism's CSS. Chrome, however, does not. Any idea would greatly be appreciated!

**Comment by iHiD** [comment]
That sounds very strange. Thousands of people per day use Exercism in Chrome and I've never heard of any issues before, so I'm going to suggest it's down to some sort of setting, or an extension you have installed.

**Comment by sshine** [comment]
@piara108: Sounds like caching issues.

Exercism's CSS works fine here on Firefox and Chrome on both Linux and Android.

I've closed this issue, but feel free to get back and help us debug this if you think it's a general problem and we're blind to it.
