### ISSUE TITLE
Mention expected CLI version during the walkthrough

### ISSUE THREAD

**Issue by matschaffer** [exercism/exercism#5188]
When working through https://exercism.io/cli-walkthrough I noticed some of the commands didn't match up.

Would be helpful if this section mentioned at least roughly what version of the CLI is expected to be installed:

![Exercism](https://user-images.githubusercontent.com/690/74404222-2ce79e00-4e6d-11ea-84c7-34f46935e29b.png)

**Comment by matschaffer** [comment]
Tried this but it seems to have trouble with http vs https?

```
 ❯ exercism download (URL component)
1970/01/01 09:00:00 Get http://exercism.io/api/v1/submissions/e5efe35787564191b692d6590a3329dd: dial tcp 63.33.114.161:80: i/o timeout
```

**Comment by matschaffer** [comment]
Ahh.... I missed this


```
❯ brew update && brew install exercism
Already up-to-date.
Warning: exercism 3.0.13 is already installed and up-to-date
To reinstall 3.0.13, run `brew reinstall exercism`
```

Seems like 3.x works.

Guess I must have installed the old client and forgotten.

Would be nice if the walkthrough called out the expected version to avoid the confusion.

**Comment by iHiD** [comment]
You could change the language to 
```
Check the installed version with:
....

It should be at least version 3.x
```

Files can be found in exercism/interactive-cli-repo ([search results here](https://github.com/exercism/interactive-cli-walkthrough/search?q=check+the+installed&unscoped_q=check+the+installed)) if you'd like to PR :)

**Comment by matschaffer** [comment]
@iHiD good call. Done!

**Comment by NobbZ** [comment]
Well, if `exercism version` suceeds, its already 3.0 at least, as the versions before used a flag rather than a subcommand.
