### ISSUE TITLE
How to uninstall exercism (Mac)?

### ISSUE THREAD

**Issue by RedFoxArg** [exercism/exercism#5193]
Hi. I was installing excercim with brew but at some point I saw this

![Screen Shot 2020-02-16 at 12 55 40 PM](https://user-images.githubusercontent.com/55214140/74608172-b55c7d80-50bd-11ea-896e-1179b4aa0b68.png)

So I made a search in order to find some guidance on the matter but I haven't found anything.
I don't know if I have to delete some files and folder manually or to uninstall and how.

I'll really appreciate some help with this.

PS: I suggest you to add a system specifications section. If that already exist, maybe it needs to be in a more visible site because I couldn't found it.

**Comment by NobbZ** [comment]
Sadly the exercism team can not control how the requirements for the go language are, also they might change at any time without their notice.

Though as Homebrew seems to require a much newer version of macOS than El Capitan. Therefore I'm wondering why you have that problem at all.

If you really have a system that has a macOS version much older than that, your best bet might be a manual installation as described in the [CLI Walkthrough](https://exercism.io/cli-walkthrough).

Though even that might fail, as the provided release binary is compiled against a certain library target, if your system doesn't match those, it is likely to fail.

**Comment by iHiD** [comment]
Also, it seems to me that exercism hasn't installed. Homebrew has failed installing the Go binary, before it's got to exercism, so I don't think there's anything to uninstall.

**Comment by RedFoxArg** [comment]
Thanks for your answer @NobbZ .

> Sadly the exercism team can not control how the requirements for the go language are, also they might change at any time without their notice.

I know but I think maybe they should let us know what we'll be installing so we can know in advantage if our system matches their needs. I wasted time trying to install exercism and now I have a lot of useless things installed and will take some extra time to uninstall them.

> Though as Homebrew seems to require a much newer version of macOS than El Capitan. Therefore I'm wondering why you have that problem at all.

I have Yosemite and Brew was installed without problems, but when the installation was finished I received a warning, as you can see in the screenshot below

![Screen Shot 2020-02-17 at 4 53 51 AM](https://user-images.githubusercontent.com/55214140/74633995-b7682000-5141-11ea-8415-12627c4c7179.png)

> If you really have a system that has a macOS version much older than that, your best bet might be a manual installation as described in the CLI Walkthrough.

I will try this option. Thanks a lot for your advice and time.

**Comment by RedFoxArg** [comment]
Hi @iHiD 

> it seems to me that exercism hasn't installed... I don't think there's anything to uninstall.

That is all I needed to hear haha. Thank you for your time and answer.
