### ISSUE TITLE
"Update exercise to latest version" not present on exercise page before solution is submitted

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#5194]
When a student begins an exercise, but has not submitted a solution, it is not possible to click the "**Update exercise to latest version**" until they have submitted a solution. Students that return to a language after a while will not be informed that an exercise has changed until they've solved it in the old way.

The request is to have the "**Update exercise to latest version**" button enabled on the exercise page both before and after a solution has been submitted. Otherwise this will waste both student and mentor time and cause some confusion.

This first screenshot is of the solution page after:

1. Running `exercism download --exercise=collatz-conjecture --track=sml` before Oct 13, 2018
2. The exercise being updated on Oct 13, 2018 in https://github.com/exercism/sml/commit/881297bc0ae5f8641a615e2ae13f582671e0fa16
3. Running `exercism download ...` again after (whether or not I `rm -rf collatz-conjecture` first)

> ![collatz-broken-1](https://user-images.githubusercontent.com/50879/74669561-aeaa3500-51a7-11ea-8c38-eb23e962c9ae.png)

This second screenshot is of the solution page after I `exercism submit collatz-conjecture.sml`:

> ![collatz-broken-2](https://user-images.githubusercontent.com/50879/74669804-355f1200-51a8-11ea-9c37-e4995a5033b4.png)

Here the "**Update exercise to latest version**" button is correctly present.

The request is that it should also present in the first screenshot.

**Comment by rpottsoh** [comment]
Seems to me the site needs to be sensitive to when the student last downloaded the exercise and not when they uploaded a solution.

**Comment by iHiD** [comment]
I think the logic is correct, it's just missing that block on that page.

I'm trying out GitHub's new notifications, and I'll try and keep this "open" one as a quick win in my notifications to find time for this week :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
