### ISSUE TITLE
Not in workspace - Java

### ISSUE THREAD

**Issue by Kjc17** [exercism/exercism#5199]
I've read through other people's posts with the same issue but can't find one that's Java specific. I've tried changing the case of E vs e and that hasn't made a difference.
I'm trying to publish using exercism submit src/main/java/Greeter.java
What might be the issue is this:

/Users/Clark/exercism/java/hello-world/hello-world

Why is 'hello-world' in the workspace twice? when I go into Finder where my Greeter.java file is located, 'hello-world' is only there once:

Users⁩/Clark⁩/Exercism⁩/⁨java⁩/hello-world⁩/src⁩/main⁩/java⁩/Greeter.java

How do I submit it??

**Comment by glennj** [comment]
What is your current directory when you `exercism submit`? This should work:
```
cd ~/exercism/java/hello-world
exercism submit src/main/java/Greeter.java
```

**Comment by Kjc17** [comment]
I tried putting in what you said and this is what I got back:
Error: lstat /Users/Clark/exercism/java/hello-world/hello-world: no such file or directory

**Comment by glennj** [comment]
OK, let's step back: how did you install `exercism`?

https://exercism.io/cli-walkthrough

**Comment by glennj** [comment]
> What is your current directory when you `exercism submit`? This should work:
> 
> ```
> cd ~/exercism/java/hello-world
> exercism submit src/main/java/Greeter.java
> ```

For future readers, I have this convenient bash function
```bash
exercism () {
    local out
    readarray -t out < <(command exercism "$@")
    printf "%s\n" "${out[@]}"
    [[ $1 == "download" && -d "${out[-1]}" ]] && cd "${out[-1]}"
}
```
That puts me into the download directory automatically.

**Comment by Kjc17** [comment]
I went through the walkthrough for Mac and downloaded it manually via the Terminal.
Config: /Users/Clark/.config/exercism is what comes up if I troubleshoot in the Terminal

**Comment by glennj** [comment]
What does `exercism version` show?

**Comment by Kjc17** [comment]
exercism version 3.0.13

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           darwin
Architecture: amd64


Configuration
----------------
Home:      /Users/Clark
Workspace: /Users/Clark/exercism/java/hello-world/hello-world
Config:    /Users/Clark/.config/exercism
API key:   **********************************

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 151.724478ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 205.393442ms

**Comment by NobbZ** [comment]
You have run the command `exercism configure workspace /Users/Clark/exercism/java/hello-world/hello-world` in the past. This was probably **after** you ran `exercism download …`.

Please take a look at how exactly the `exercism` folder is spelled when you do `ls -l | grep -i exercism` in `~`, then do `exercism configure workspace ${HOME}/exercism` (or `…/Exercism`, depending on exact spelling!).

Then its best to use `cd $(exercism workspace)` to get into your workspace folder and get the spelling exactly as it should be.

You can also add an alias to your shells RC file like this:

```
alias cde='cd $(exercism workspace)'
```

Then you can use `cde` in future to get into your workspace.

**Comment by Kjc17** [comment]
I think I configured it when I was reading for solutions online and tried to make anything work, which ultimately made it worse. 

I've tried doing the above but I don't think it's made a difference? I'm probably still doing it wrong somehow. I'm also not quite understanding the ls -l | grep -i exercism in ~ ?
If I type cd $(exercism workspace) or cde it then comes up with:
-bash: cd: /Users/Clark/exercism/java/hello-world/hello-world: No such file or directory

It shows up consistently as exercism in the Terminal, but has a capital E on the file in Finder, so I'm not sure if that makes a difference.

**Comment by glennj** [comment]
You need to re-configure the workspace **first**:

```
exercism configure workspace ${HOME}/exercism
```

**then** `cd $(exercism workspace)`

**Comment by NobbZ** [comment]
> I'm also not quite understanding the ls -l | grep -i exercism in ~ ?

`ls -l | grep -i exercism` is a command, that you shall run when you are in `~` (aka your homefolder).

explainshell.com [explains the command](https://explainshell.com/explain?cmd=ls+-l+%7C+grep+-i+exercism) much better than I could.

In short it will find the `exercism` folder despite its casing. You have to remember that casing when reconfiguring `exercism`.

> If I type cd $(exercism workspace) or cde it then comes up with:
> ```plain
> -bash: cd: /Users/Clark/exercism/java/hello-world/hello-world: No such file or directory
> ```

Of course it does, the workspace is still not configured correctly.

> It shows up consistently as exercism in the Terminal, but has a capital E on the file in Finder, 

Even though macOS does not care for the casing, the CLI does. Therefore it is important to have the `exercism` tool configured the same way as the casing is written in the filesystem. The canonical way to find out is by the command I have given above. I have fear that the finder does some uppercasing on its own because that looks more nice or so… Too much of magic in mac and windows…

**Comment by Kjc17** [comment]
> You need to re-configure the workspace **first**:
> 
> ```
> exercism configure workspace ${HOME}/exercism
> ```

That configured it, and then I tried cd $(exercism workspace) which again said there was no such file or directory. 
Apologies for being so slow on this, I'm very new to Java and Exercism 😅

> explainshell.com [explains the command](https://explainshell.com/explain?cmd=ls+-l+%7C+grep+-i+exercism) much better than I could.

Thanks for the link and for explaining about everything so thoroughly!

**Comment by NobbZ** [comment]
Could you please show full output of the following commands?

```
exercism troubleshoot
cd $(exercism workspace)
```

**Comment by glennj** [comment]
Perhaps `cd && ls -ld *xercism` as well

**Comment by Kjc17** [comment]
> Could you please show full output of the following commands?
> 
> ```
> exercism troubleshoot
> cd $(exercism workspace)
> ```
Kacis-Air:hello-world Clark$ exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           darwin
Architecture: amd64


Configuration
----------------
Home:      /Users/Clark
Workspace: /Users/Clark/exercism/java/hello-world/hello-world
Config:    /Users/Clark/.config/exercism
API key:   ************************************

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 152.320089ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 281.604907ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
Kacis-Air:hello-world Clark$ cd $(exercism workspace)
-bash: cd: /Users/Clark/exercism/java/hello-world/hello-world: No such file or directory

> Perhaps `cd && ls -ld *xercism` as well
Kacis-Air:hello-world Clark$ cd && ls -ld *xercism
drwxr-xr-x  4 Clark  staff  128 21 Feb 12:59 Exercism

Apologies for the late reply, I've had family visiting so I've been unable to take another look at it until now.

**Comment by NobbZ** [comment]
> Workspace: /Users/Clark/exercism/java/hello-world/hello-world

You haven't configured your workspace correctly.

I doubt that a path like that exist at all, even more I doubt that it has the necessary folder structure beneath it.

Please run `exercism configure --workspace "${HOME}/Exercism"` (or with lowercase `e` depending on the canonical way your FS stored the name).

Please make also sure to report any output that command produced, to make sure we don't tell you an errornous command again (it seems the last command I gave you was not proper syntx).

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
