### ISSUE TITLE
Failed to configure API key

### ISSUE THREAD

**Issue by grbsy** [exercism/exercism#5200]
Hi!
`

> mrrobot@mrRobot:~$ sudo exercism configure --token=2a7b0856-89d4-4364-be58-40cfa2d7dc2b
> 
> You have configured the Exercism command-line client:
> 
> Config dir:                       /root/snap/exercism/4/.config/exercism
> Token:         (-t, --token)      2a7b0856-89d4-4364-be58-40cfa2d7dc2b
> Workspace:     (-w, --workspace)  /root/snap/exercism/4/exercism
> API Base URL:  (-a, --api)        https://api.exercism.io/v1

`
`

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           linux
Architecture: 386

Configuration
----------------
Home:      /home/mrrobot/snap/exercism/4
Workspace: /home/mrrobot/snap/exercism/4/exercism (default)
Config:    /home/mrrobot/.config/exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 200.424258ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 508.713401ms

`

**Comment by NobbZ** [comment]
Please visit [your settings](https://exercism.io/my/settings) and reset your API key. Please make sure to not leak it again. Even though its scope is limited, everyone who knows it can impersonate you.

To actually solve your problem:

Do not use `sudo` on any `exercism` related command (in general, only ever run something as root if you know what you are doing!).

If you drop `sudo` and continue to struggle please come back here and tell how new problems materialize.

**Comment by grbsy** [comment]
> Please visit [your settings](https://exercism.io/my/settings) and reset your API key. Please make sure to not leak it again. Even though its scope is limited, everyone who knows it can impersonate you.
> 
> To actually solve your problem:
> 
> Do not use `sudo` on any `exercism` related command (in general, only ever run something as root if you know what you are doing!).
> 
> If you drop `sudo` and continue to struggle please come back here and tell how new problems materialize.

I restarted API before posting it, but good you say tho.
This is output without `sudo`:
> Error: 
>     The default Exercism workspace is
> 
>       /home/mrrobot/snap/exercism/4/exercism
> 
>     There is already something there.
>     If it's a directory, that might be fine.
>     If it's a file, you will need to move it first, or choose a
>     different location for the workspace.
> 
>     You can choose the workspace location by rerunning this command
>     with the --workspace flag.
> 
>       /snap/exercism/4/exercism configure --token=3beb53c1-a622-4640-86ad-2892eb3b2cda --workspace=/home/mrrobot/snap/exercism/4/exercism

.../4/exercism is already empty, before tho i made there one .py file that should be deleted from there.

**Comment by NobbZ** [comment]
Empty, but there. Just try the command printed at the footer of the error. Of course with an appropriate token, since it leaked again…

**Comment by grbsy** [comment]
This either left me with the same result.

**Comment by NobbZ** [comment]
The command `  /snap/exercism/4/exercism configure --token=XXX --workspace=/home/mrrobot/snap/exercism/4/exercism` fails with this error?

> ```
> Error:
> The default Exercism workspace is
> 
>     /home/mrrobot/snap/exercism/4/exercism
>
> There is already something there.
> If it's a directory, that might be fine.
> If it's a file, you will need to move it first, or choose a
> different location for the workspace.
>
> You can choose the workspace location by rerunning this command
> with the --workspace flag.
>
>     /snap/exercism/4/exercism configure --token=XXX --workspace=/home/mrrobot/snap/exercism/4/exercism
> ```

Or do you have another "the same result"?

**Comment by Nswayze** [comment]
Hi I'm having the exact same issue as above. I'm running Manjaro
and when I run the command with the token inserted.
/snap/exercism/4/exercism configure --token=XXX 

It says it's updated but as soon as I try to pull project files
with exercism download --exercise=hello-world --track=c

It says

`Error: 

    Welcome to Exercism!

    To get started, you need to configure the tool with your API token.
    Find your token at

        https://exercism.io/my/settings

    Then run the configure command:

        /snap/exercism/5/exercism configure --token=YOUR_TOKEN`

Opening the user.json file in /home/shodan/.config/exercism/
it contains correct token information.

`Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/shodan/snap/exercism/5
Workspace: /home/shodan/snap/exercism/5/exercism (default)
Config:    /home/shodan/snap/exercism/5/.config/exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 244.187295ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 1.360298119s
`

**Comment by NobbZ** [comment]
Something in the snap messes with the searchpath for the config. It has shown to be the easiest to create a hard link between the regular config at `~/.config/exercism/user.json` (or whatever the name was) to where the snap searches for it ocassionally.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
