### ISSUE TITLE
Dart Robot Simulator locked despite having completed all track exercises

### ISSUE THREAD

**Issue by mstange22** [exercism/exercism#5201]
Subject pretty much says it all.  Just completed the last track exercise in the Dart track and Robot Simulator is greyed-out.

**Comment by sshine** [comment]
A similar report, but via a feedback comment:

> i see Matching Brackets, and a handful of others, are not unlocked, while i have completed all of the main exercises. How are the remaining exercises unlocked?

**Comment by iHiD** [comment]
@mstange22 Robot Simulator has only recently been added and not added to your account. I'm running a script to fix this, which should complete in the next few hours.

(cc @exercism/dart - Please mention me in any PRs that add new exercises once they have been merged :) )

**Comment by mstange22** [comment]
I can get it now.  Thank you!
