### ISSUE TITLE
I would like to download all solutions in a single file.

### ISSUE THREAD

**Issue by yugawara** [exercism/exercism#5204]
Is it possible to get something like a database dump of all solutions?  I am currently going through the Java course and need a very quick way to browse other people's solutions.   I learn so much from other peoples's solutions but it's just not practical to view each solution by repeated clicking...

**Comment by iHiD** [comment]
No, there isn't - sorry. In [v3](https://github.com/exercism/v3/issues/690) we'll be making this easier to work with though.
