### ISSUE TITLE
No response in over 1 month (javascript track)

### ISSUE THREAD

**Issue by l0n3star** [exercism/exercism#5206]
I submitted my solution to the Wordy core exercise but I have not heard from a mentor in over 1 month.  This is the first time I'm seeing this much delay.  What is the reason for the delay?

**Comment by iHiD** [comment]
I imagine there is a a backlog of people waiting for mentors, and not enough mentors to cope. We're also having a big push towards the next version of Exercism atm so people's time is split.

**Comment by SleeplessByte** [comment]
@l0n3star that exercise is also pretty late in the track and less people are good at mentoring that one properly. If you send me the link here, I'll look at it.

**Comment by l0n3star** [comment]
@SleeplessByte I actually just a response so I'm good.
