### ISSUE TITLE
Can't submit my exercise solutions, guess exercism is installed in the wrong directory!

### ISSUE THREAD

**Issue by NARUDESIGNS** [exercism/exercism#5207]

**Comment by iHiD** [comment]
Download it on your new computer and just carry on the same workflow as before.

**Comment by NARUDESIGNS** [comment]
Thanks to @iHiD I was able to get a new version but now i have a new problem. I can't submit my exercise solutions. I user a mac pc, please what directory should the exercism be in? this is all so confusing, any help? @kytrinyx

**Comment by iHiD** [comment]
`exercism` isn't in a directory - it's a program installed presumably by Homebrew if you've followed the instructions. You download using `exercism download ...` and upload via `exercism submit ...` exactly the same as you did previously.

Also - best not to ping individuals unless you know them and are asking for some specific help that only they can provide.

**Comment by NARUDESIGNS** [comment]
OK thank you
