### ISSUE TITLE
Submit now failing with 'unexpected end of JSON input'

### ISSUE THREAD

**Issue by ctincristi-acn** [exercism/exercism#5208]
On my Windows machine I am encountering an error while uploading my latest exercise:
>exercism submit acronym.py
Error: unexpected end of JSON input

I've checked the user.json even tried to re-install and reconfigure the CLI; the error is still there. On the same machine, with no changes, I've managed to upload some time ago other exercises just fine.

**Comment by iHiD** [comment]
What do you get when you run `exercism troubleshoot`?

**Comment by ctincristi-acn** [comment]
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\hidden.username
Workspace: C:\Users\hidden.username\OneDrive\Documente\Training\Exercism
Config:    C:\Users\hidden.username\AppData\Roaming\exercism
API key:   ce32*****************************ed3

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 163.9918ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 746.9899ms

**Comment by iHiD** [comment]
Thanks. And if you run `submit` with the `--verbose` flag?

**Comment by ctincristi-acn** [comment]
```
C:\Users\hidden.username\OneDrive\Documente\Training\Exercism\python\acronym>exercism submit acronym.py --verbose
Error: unexpected end of JSON input

C:\Users\hidden.username\OneDrive\Documente\Training\Exercism\python\acronym>exercism --verbose submit acronym.py
Error: unexpected end of JSON input

C:\Users\hidden.username\OneDrive\Documente\Training\Exercism\python\acronym>exercism submit --verbose acronym.py
Error: unexpected end of JSON input
```

**Comment by iHiD** [comment]
@kytrinyx @NobbZ Any ideas?

**Comment by NobbZ** [comment]
There should be some `.solution.json` or `.exercism/metadata.json` in the exercises folder, or at least something very close to this names…

Please check if that contains valid JSON.

If it does not, please rename your `acronym` folder to something like `acronym-bak`, redownload the exercise and copy the file that implements the solution over into the newly downloaded folder. Try to resubmit.

If the JSON is either valid, you don't know how to check, or it doesn't work after a re-download either, please show us the content of that file.

**Comment by ctincristi-acn** [comment]
`.exercism/metadata.json` was completely empty. I've backed up my folder, redownloaded the exercise, applied my .py solution and successfully uploaded it.
Thank you for your assistance.
