### ISSUE TITLE
Javascript - npm issue

### ISSUE THREAD

**Issue by abergquist** [exercism/exercism#5209]
I've successfully run **npm install** for other JavaScript exercises, but when I do so for leap:

--------------------------------------------------------------------------------------------------------------
```
PS C:\Users\...\Exercism\javascript\leap> **npm install**
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 894058 packages in 5.819s
found 0 vulnerabilities
```
--------------------------------------------------------------------------------------------------------------

and then try to **npm test**:

--------------------------------------------------------------------------------------------------------------
```
PS C:\Users\...\Exercism\javascript\leap> **npm test**

> exercism-javascript@1.6.0 test C:\Users\...\Exercism\javascript\leap
> jest --no-cache ./*

'jest' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
PS C:\Users\...\Exercism\javascript\leap> 
```

This appears to be a problem only with the _extra_ exercise, not the _regular_ exercise.

**Comment by sshine** [comment]
Ping @exercism/javascript.

**Comment by SleeplessByte** [comment]
Can you check in the folder `...\javascript\leap` that there is indeed a `node_modules` folder, and that inside of it, there is a `.bin` folder and that inside of that there is a file `jest`, `jest.cmd`, `jest.bat` or `jest.exe`? **I am expecting there to be `jest` and `jest.cmd`, given that you seem to be on windows.**

If the above is true, something in `npm` is breaking the resolution. You can temporarily work around it by using:

```shell
".\node_modules\.bin\jest.cmd" --no-cache ./*
# unix-like windows shells

.\node_modules\.bin\jest.cmd --no-cache ./*
# cmd
```

If that works, I would suggest:

- clearing the `npm` cache via `npm cache clean`
- removing node_modules (for example `rm node_module -rf` if you're on unix-like shell)
- reinstalling via `npm install`

**Make sure to run these commands inside the `leap` folder**

Then, if this doesn't solve anything, I would suggest re-installing node LTS (and thus also npm).

-------

If all else fails, please run `npm run env` and post the output here.

**Comment by abergquist** [comment]
Hi, SleeplessByte.

Deleting **node_modules** and re-installing via **npm install** did the trick.

Thanks so much!

**Comment by SleeplessByte** [comment]
Sweet. This can be closed @iHiD
