### ISSUE TITLE
waiting 4 months for mentor

### ISSUE THREAD

**Issue by hladkabarbora** [exercism/exercism#5210]
Hi there, it says it takes a few days for the mentor to get back to me, however, I have been waiting months on all my exercises.

**Comment by sshine** [comment]
A mitigation of this bad experience was most recently addressed [here](https://github.com/exercism/exercism/issues/5192#issuecomment-587068482) where an FAQ update was encouraged. For that reason I'm going to close this issue and refer to that issue for an elaboration on how to address mentor insufficiency.
