### ISSUE TITLE
(JS Track)Problem with npm install for scrabble-score problem

### ISSUE THREAD

**Issue by eermac949** [exercism/exercism#5212]
Vulnerability/support/bug??
After having installed the scrabble-score in the JS track using npm.

I believe this is a **new vulnerability(?)** from published(https://npmjs.com/advisories/1488) **6th of march 2020.**
I'm not sure if anything can be done to the existing package or...

```
npm audit
>  === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > @jest/core > @jest/reporters > jest-runtime >
                  jest-config > jest-environment-jsdom > jsdom > acorn-globals
                  > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > jest-cli > @jest/core > @jest/reporters >
                  jest-runtime > jest-config > jest-environment-jsdom > jsdom
                  > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > @jest/core > jest-runner > jest-jasmine2 >
                  jest-runtime > jest-config > jest-environment-jsdom > jsdom
                  > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > jest-cli > @jest/core > jest-runner > jest-jasmine2 >
                  jest-runtime > jest-config > jest-environment-jsdom > jsdom
                  > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > @jest/core > jest-runner > jest-runtime > jest-config
                  > jest-environment-jsdom > jsdom > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > jest-cli > @jest/core > jest-runner > jest-runtime >
                  jest-config > jest-environment-jsdom > jsdom > acorn-globals
                  > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > @jest/core > jest-runtime > jest-config >
                  jest-environment-jsdom > jsdom > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > jest-cli > @jest/core > jest-runtime > jest-config >
                  jest-environment-jsdom > jsdom > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > @jest/core > jest-runner > jest-config >
                  jest-environment-jsdom > jsdom > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > jest-cli > @jest/core > jest-runner > jest-config >
                  jest-environment-jsdom > jsdom > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > @jest/core > jest-config > jest-environment-jsdom >
                  jsdom > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > jest-cli > @jest/core > jest-config >
                  jest-environment-jsdom > jsdom > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488


  Moderate        Regular Expression Denial of Service

  Package         acorn

  Patched in      >=7.1.1

  Dependency of   jest [dev]

  Path            jest > jest-cli > jest-config > jest-environment-jsdom >
                  jsdom > acorn-globals > acorn

  More info       https://npmjs.com/advisories/1488

found 13 moderate severity vulnerabilities in 1215768 scanned packages
  13 vulnerabilities require manual review. See the full report for details.

```

**Comment by NobbZ** [comment]
cc @exercism/javascript

**Comment by SleeplessByte** [comment]
You don't run this "package" online, so you can ignore the vulnerabilities as no one will be able to DoS you.

We do accept a PR on `exercism/javascript` to _update_ the `jest` package, which will **resolve** this warning.

**Comment by tejasbubane** [comment]
@eermac949 Dependencies are updated in https://github.com/exercism/javascript/pull/845. Please click `Update this exercise to latest version` button on the exercise page & then download the exercise again.

**Comment by NobbZ** [comment]
The testfiles didn't change, so he won't be able to update. This is a known limitation of the website.

**Comment by tejasbubane** [comment]
Ohh I did not know of this limitation. I assumed entire directory snapshot(commit) gets updated.

**Comment by SleeplessByte** [comment]
As far as I know, it's the entire directory. Not just test files.



Cc @ihid

**Comment by iHiD** [comment]
The three general rules are:
- If the tests change, the button appears.
- If the button is pressed the entire directory will be updated. 
- Files that a student has submitted will never be overwritten.

So there are various outputs of that depending on what a student has done already. (e.g. if a student submitted the tests, the tests won't get overriden)

**Comment by SleeplessByte** [comment]
@tejasbubane I guess we can "touch" the test file by adding a comment?

**Comment by tejasbubane** [comment]
> I guess we can "touch" the test file by adding a comment?

@SleeplessByte I don't like the idea of adding random comments. But some questions we should think of:

1. We regularly update packages, do we want to show `update` button when nothing in the context of `the exercise` has changed?

2. If we decide to add comments, what should those be? Version number is already in package.json - duplicating it will add maintenance overhead. What do we change the comment to the next time we update packages?

Examples from other tracks not updating tests after package upgrades:
* Haskell: https://github.com/exercism/haskell/pull/846
* Clojure: https://github.com/exercism/clojure/pull/262

**Comment by SleeplessByte** [comment]
> We regularly update packages, do we want to show update button when nothing in the context of the exercise has changed?

I guess we don't. 

> If we decide to add comments, what should those be? Version number is already in package.json - duplicating it will add maintenance overhead. What do we change the comment to the next time we update packages?

We can _generate_ a comment based on the package.json or package-json lock file or whatever (md5 it)?

----

Mostly we just want to help people understand that these warnings are not applicable to running locally.

**Comment by tejasbubane** [comment]
> Mostly we just want to help people understand that these warnings are not applicable to running locally.

I guess this can be achieved by adding Readme hint to ignore the warnings.

**Comment by SleeplessByte** [comment]
Let's do that then. Perhaps we can try to add the explanation as:

```md
<details>
 <summary>Summary Goes Here</summary>
 ...this is hidden, collapsable content...
</details>
```
which is just html5: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

<details>
 <summary>Summary Goes Here</summary>
 ...this is hidden, collapsable content...
</details>

No clue if it will render correctly on exercism, but worth a try?

**Comment by tejasbubane** [comment]
HTML5 is when seen on github or even exercism if it works, but definitely not pleasant when reading in editor. I would stick to markdown like rest of the Readme.

**Comment by iHiD** [comment]
I'd happily support a custom markdown standard for summary/details tags. I also don't like seeing HTML in markdown, but I really do see the value of being able to parse it to those tags.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
