### ISSUE TITLE
Exercise listed under wrong difficulty

### ISSUE THREAD

**Issue by Woutuuur** [exercism/exercism#5214]
https://exercism.io/my/solutions/ef5ff8d8d3e14818ad9b98b55116e916

This exercise is listed as 'hard' on the Java track. The same exercise is listed as easy on the Python track. I don't think Java makes the problem much harder compared to Python.

**Comment by NobbZ** [comment]
Which exercise are you talking about.

Also, the difficulties have been assigned based on subjective experiences by different people. Perhaps those who did the exercise in Java simply had more trouble understanding how the exercise has to be solved and therefore considered it harder?

**Comment by Woutuuur** [comment]
I linked the exercise. How can I rate how difficult I found an exercise? I don't think I have had the option for it before.

**Comment by glennj** [comment]
IMO the python difficulty ratings are often too low.

**Comment by Woutuuur** [comment]
It's easy vs hard on the exact same problem, but different language. The language doesn't make it much easier as it is mainly a math related problem.

**Comment by iHiD** [comment]
@Woutuuur You linked to a page that only you can see. What exercise is it?

**Comment by glennj** [comment]
It looks like pythagorean-triplet. This exercise is easy to solve in a brute force way but trickier to do more efficiently. I have an 8 line python solution that completed the test suite in 50 seconds, and a 128 line java solution that words in 0.5 sec.

**Comment by Woutuuur** [comment]
@glennj Wouldn't it be possible to use the same algorithm you used in Java in Python?

**Comment by Woutuuur** [comment]
> Which exercise are you talking about.

It's the pythagorean-triplet exercise. @NobbZ

**Comment by glennj** [comment]
@Woutuuur of course, but then I wouldn't consider the python solution as "easy" either. My point is that I think the python track rates their difficulties too low.

**Comment by iHiD** [comment]
I agree. It should probably be hard everywhere. It's also "maths" and those are going to be marked clearly and not part of any core pathways in v3.

**Comment by glennj** [comment]
To wrap this up from my perspective, @Woutuuur if you think the java exercise should have a different difficulty, I suggest you open an issue in the [Java repo](https://github.com/exercism/java) and reference this issue.

**Comment by iHiD** [comment]
Or the python one :)

Thanks, both of you.
