### ISSUE TITLE
Powershell Track Not showing

### ISSUE THREAD

**Issue by mzsalam** [exercism/exercism#5217]
Hi,
I came across your portal while looking for a PS learning source. It is quite impressive the work you have done.
I have joined Python and PowerShell tracks. PowerShell track came up in Google search. However, even though I have joined this track, I cant see it in the list of my tracks under **https://exercism.io/my/tracks**.
PowerShell is also not listed in the tracks list but it came up on Google search. Could this be a bug or I am missing something.

Thanks

**Comment by glennj** [comment]
It seems that track has not been activated, even though there are a few exercises there (only 10).

You can get there by entering the track url directly: https://exercism.io/my/tracks/powershell

**Comment by glennj** [comment]
If you join the track, join in practice mode. I don't think there are any mentors there.

**Comment by iHiD** [comment]
I'll close this as @glennj has answered the question! :)
