### ISSUE TITLE
Token not Updating

### ISSUE THREAD

**Issue by cshelley-zz** [exercism/exercism#5218]
While configuring the CLI interface for python, I run the following command:
input:
/snap/exercism/5/exercism configure --token=XXXX
output: 
You have configured the Exercism command-line client:

Config dir:                       /home/me/.config/exercism
Token:         (-t, --token)      States correct token here
Workspace:     (-w, --workspace)  /home/me/exercism
API Base URL:  (-a, --api)        https://api.exercism.io/v1

input:
exercism download --exercise=hello-world --track=python 
output:
Error: 

    Welcome to Exercism!

    To get started, you need to configure the tool with your API token.
    Find your token at

        https://exercism.io/my/settings

    Then run the configure command:

        /snap/exercism/5/exercism configure --token=YOUR_TOKEN

input:
exercism troubleshoot
output:

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           linux
Architecture: amd64

Configuration
----------------
Home:      /home/me/snap/exercism/5
Workspace: /home/me/snap/exercism/5/exercism (default)
Config:    /home/me/.config/exercism
API key:   not configured
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 50.278ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 1.563304787s

If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.

The /home/me/.config/exercism/user.json file has the correct API token listed in it.

What do?

**Comment by cshelley-zz** [comment]
Not sure why it deleted the text I had input beside it but the

Token: (-t, --token) 

Line has the correct token listed alongside it.

**Comment by NobbZ** [comment]
This is a problem that happens occasionally with `snap` installations.

Some report it would help to run `exercism configure` rather than the snap suggested fully qualified command, others sayd, they had to find the configuration file in snaps folders and move it to `~/.config/exercism` manually.

**Comment by cshelley-zz** [comment]
Unfortunately, those options are not working either. I've manually created directories and files to no avail.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
