### ISSUE TITLE
Relax restrictions on secondary exercises

### ISSUE THREAD

**Issue by hanesi** [exercism/exercism#5222]
I am currently on the Go track and because there aren't a lot of mentors it takes a long time to get exercises reviews which under normal times is fine, but given the amount of people on lockdown, I was wondering if it were possible to relax restrictions on the additional exercises? I'm out of problems and the median wait time on the one I submitted is 6 more days. It would just be a really nice way to help pass the time.

**Comment by iHiD** [comment]
I recommend switching to Practice Mode, where there are no restrictions :)

**Comment by hanesi** [comment]
Oof. Awkward...

Thanks for reminding me!
