### ISSUE TITLE
Using source code instructions for Linux gets rid of color in terminal

### ISSUE THREAD

**Issue by chrph** [exercism/exercism#5223]
I have WSL 1 Ubuntu 18.04 on Windows 10. I successfully installed Exercism for Linux using the source code, however after installing, the font on my ubuntu terminal didn't have colors anymore.

I think this happened with the Bash file was configured with this code?
`echo 'export PATH=~/bin:$PATH' >> ~/.bash_profile
source ~/.bash_profile`

But I'm not really sure how it takes the color away or the best solution to gt the colors back.

Image for reference. Notice how the font is colored. After installing Exercism, the font is white: 
![ximg_591cd4da1e9cc png pagespeed gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md ic LzcOS2TmeB](https://user-images.githubusercontent.com/12645171/77434082-9b126f80-6de0-11ea-8389-02b4651d02eb.png)

**Comment by chrph** [comment]
After troubleshooting, I found a solution. I'm not sure what this does exactly but it worked to get the colors back.

**Running this command:**
`echo "source ~/.bashrc" >> ~/.bash_profile`

**Source:**
https://stackoverflow.com/questions/48761771/my-wsl-terminal-lost-color

**Comment by iHiD** [comment]
Thanks for following up :)
