### ISSUE TITLE
JS and VScode (Javascript Track)

### ISSUE THREAD

**Issue by heymajor** [exercism/exercism#5224]
No issues with beginning a problem, running tests, or submitting responses, but I'm having a hard time figuring out a good setup to debug javascript exercise scripts in VScode.

I can `console.log` at desired breakpoints and manually run the script from the command line, but as I continue, debugging through VScode with a launch.json file seems to work, but it's a rather tedious setup and could be prone to a lot of errors.

For example: Instead of using the provided skeleton file (`resistor-color-duo.js`) and receiving module export errors, I created a secondary file (`res.js`) to focus the coding. This is defined in the launch file: 

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/javascript/resistor-color-duo/res.js",
            "args": [
                "green",
                "brown"
            ],
            "console": "integratedTerminal"
        }
    ]
}
```

After walking through the setup, I work through the exercise and then paste the contents into the the main exercise test file (`resistor-color-duo.js`) and then run the exercise tests.

Is there an easier way to debug a scratch javascript script?

**Comment by iHiD** [comment]
cc @sleeplessbyte
(context https://twitter.com/MajorByDesign/status/1241611966495539200)

**Comment by heymajor** [comment]
Closing the issue: The more I think about it, this question might be a bit outside of scope. It's a more of a basic javascript question where I'm fighting with my tools/setup than code related to this repo. 

I haven't touched javascript in a few weeks, and after going through a few DOM scripting vids, I think my answer is for me to take it back to the basics. 

Thank you for responding to my tweet/encouraging me to open this issue!

**Comment by iHiD** [comment]
No probs. Shout if we can help :)

**Comment by SleeplessByte** [comment]
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Jest All",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": ["--runInBand"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      }
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Jest Current File",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": [
        "${fileBasenameNoExtension}",
        "--config",
        "jest.config.js"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      }
    }
  ]
}
```

Now, adding breakpoints in test files works and does this:

![Depiction of a debugger breakpoint reached in the hello-world exercise test file](https://user-images.githubusercontent.com/1964376/77704530-90610180-6fbd-11ea-996e-5dbcb6ca09a6.png)

Additionally, you can even add them in your source files:

![Depiction of a debugger breakpoint reached in the hello-world exercise stub file](https://user-images.githubusercontent.com/1964376/77704556-a1aa0e00-6fbd-11ea-9834-67d742e1f88d.png)

When you look at the call stack, ignore everything below `asyncJestTest`:

![Call stack during a test run](https://user-images.githubusercontent.com/1964376/77704640-d1f1ac80-6fbd-11ea-972a-ecf04dd498a0.png)

----

The "smart reader" will see that we really only need one of the two configurations, as _all exercises are always a single test file_. Whilst that is true, these configurations will work across the board, with any project using jest.

**Comment by heymajor** [comment]
I know it's been a few days, but I wanted to drop a quick note to @SleeplessByte: this is pretty great.

Thank you for taking the time to work through that (and introducing me to jest)!

I'm not able to work with this just yet, but I'm expecting to within the next few weeks when I start working on the JS track again.
