### ISSUE TITLE
npm dependencies

### ISSUE THREAD

**Issue by Ikeh-Akinyemi** [exercism/exercism#5225]
I have been trying to install npm on my exercise "resistor-color", then I will run my npm test but I have been having error issued whenever I try install npm and my npm test doesn't even run at all.

Here is the error issue when installing npm ;

withheld@withheld:~/snap/exercism/5/exercism/javascript/resistor-color$ npm install
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! Linux 4.15.0-88-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ikehakinyemi/snap/exercism/5/exercism/javascript/resistor-color/npm-debug.log

What is the possible solution to it please?

Then trying to run a npm test, i get this:

withheld@withheld:~/snap/exercism/5/exercism/javascript/resistor-color$ npm test

> exercism-javascript@1.0.0 test /home/ikehakinyemi/snap/exercism/5/exercism/javascript/resistor-color
> jest --no-cache ./*

**Comment by iHiD** [comment]
cc @sleeplessbyte

**Comment by SleeplessByte** [comment]
> npm ERR! typeerror This is an error with npm itself. Please report this error at:
> npm ERR! typeerror http://github.com/npm/npm/issues

We can not solve this.

Things you can try yourself:

- reinstall node completely (so uninstall, then install)
- clear npm cache (google will help)
- delete the `node_modules` AND `package-lock.json`
- `npm install`
- `npm test`

At this moment, the deprecation warnings of `request` and `mkdirp` are correct and expected. The error you're encountering isn't.

I did just download this exercise myself:

![Install results of installing resistor-color](https://user-images.githubusercontent.com/1964376/77705079-06b23380-6fbf-11ea-91bb-4f299f25ece5.png)

![Test results](https://user-images.githubusercontent.com/1964376/77705113-1cbff400-6fbf-11ea-87da-ace383ec5262.png)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
