### ISSUE TITLE
to verify gpg key ID before unzip rep

### ISSUE THREAD

**Issue by gdani2c4** [exercism/exercism#5229]
Concerning the excercism cli tarball, maybe the answer is there but I didn't see it... I looked for the gpg ID of the signer in the website https://exercism.io/cli-walkthrough ... I download outside of github infrequently, but the last time I did it, the gpg author ID was in the website, so I could verify that the signature belongs to a contributor. I wanted to report this in any case, even though I can also try to clone the rep. and delete the tarball. Thanks for exercism.io, I am excited to practice in Bash! -- Dan

**Comment by gdani2c4** [comment]
solved - I found the contributor in the rep contributor list, and his link is to the corresponding keybase.io key; maybe this should be added to the directions in https://exercism.io/cli-walkthrough ?

**Comment by iHiD** [comment]
@ErikSchierboom @ccare @kytrinyx Any thoughts on this?
