### ISSUE TITLE
Io language

### ISSUE THREAD

**Issue by A-ee** [exercism/exercism#5232]
I'd like to master the [Io](http://iolanguage.org/) language but I realized that there isn't an Io track here.

(So, is this the right place for language requests?)

**Comment by iHiD** [comment]
Hey :) You'd want to go here: https://github.com/exercism/request-new-language-track/

However, you'd need to find someone to create the language here. All the tracks n Exercism are created by volunteers. If you know someone that might want to help, maybe reach out to them and ask them to open the issue?
