### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by lonniegoins** [exercism/exercism#5235]
Ok so I am a complete newbie when it comes to coding. At the moment I am trying to get started on exercism to start to try to learn JavaScript. Usually I can muddle my way through things but I am stuck. I have downloaded CLI and installed it where it needs to go. I then downloaded the first exercise and here is what it says:
C:\Users\lonni> exercism download --exercise=hello-world --track=javascript

Downloaded to
C:\Users\lonni\Exercism\javascript\hello-world
But for the life of me I can't get the exercise to open. What am I doing wrong?

**Comment by glennj** [comment]
Have you read these? (These links show up in the right-hand column on the JavaScript track page)
* [Installing JavaScript](https://exercism.io/tracks/javascript/installation)
* [Running the Tests](https://exercism.io/tracks/javascript/tests)

I fear you may need to look elsewhere to ramp up if you're really just starting your programming journey: exercism (the current version of it anyway) assumes a certain level of experience already. But we'll help as much as we can.

**Comment by lonniegoins** [comment]
I have installed exercism when run in cmd this it what it says:
C:\Users\lonni>exercism
A command-line interface for the v2 redesign of Exercism.

Download exercises and submit your solutions.

Usage:
   [command]

Available Commands:
  configure    Configure the command-line client.
  download     Download an exercise.
  help         Help about any command
  open         Open an exercise on the website.
  prepare      Prepare does setup for Exercism and its tracks.
  submit       Submit your solution to an exercise.
  troubleshoot Troubleshoot does a diagnostic self-check.
  upgrade      Upgrade to the latest version of the CLI.
  version      Version outputs the version of CLI.
  workspace    Print out the path to your Exercism workspace.

Flags:
  -h, --help           help for this command
      --timeout int    override the default HTTP timeout (seconds)
      --unmask-token   will unmask the API during a request/response dump
  -v, --verbose        verbose output

Use " [command] --help" for more information about a command.

C:\Users\lonni>
All I am asking is since I have it installed why can't I open the exercise

**Comment by glennj** [comment]
What specifically are you doing to try to "open" the exercise?

Does `C:\Users\lonni\Exercism\javascript\hello-world` exist? What files are inside that folder?

**Comment by lonniegoins** [comment]
Yes that folder is there

**Comment by lonniegoins** [comment]
There is a .exercism folder
.eslintrc
babel.config.js
hello.world.js
package.json
and a read me file

**Comment by lonniegoins** [comment]
Does the exercise need to be opened in the cmd window and if so what command do I use to open it?
Thanks Lonnie

**Comment by glennj** [comment]
You need to read the links I provided above.
You will edit the hello.world.js file in a code editor.
Run the tests as documented.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
