### ISSUE TITLE
Downloading the next x exercises from track y

### ISSUE THREAD

**Issue by theFox6** [exercism/exercism#5237]
I would like to have the option to download the next n exercises in the cli.
I don't know it this is possible on the server side so I'm opening this issue in here.

**Comment by iHiD** [comment]
Hi. Thanks for this. it's unlikely that we'll be adding this in the foreseeable future as Exercism doesn't have a concept of "next n exercises" - there is no ordering in this way. Thanks for the suggestion though :)

**Comment by theFox6** [comment]
It would be nice to be able to do a pack of exercises offline and submit them later.
Especially in languages you already know partially where you wish to solidify your knowledge by a bit of training.
