### ISSUE TITLE
[Javascript track] waiting for a mentor for 5 days 

### ISSUE THREAD

**Issue by scalblog** [exercism/exercism#5245]
Hi everyone,
I'm in the first steps of the Javascript track and the code review seems blocked for 5 days : 

"There are currently 31 solutions ahead of this in the JavaScript queue, and 1 ahead in the Resistor Color Duo queue."

Can you check why it's blocked ?

Here is where I see the blocked queue : 
[mentor link to exercise](https://exercism.io/mentor/solutions/c9d5326d257244f9afefa70f541312d6)

I thank you for your help.

**Comment by kotp** [comment]
It looks like this has been mentored or is in the process.
