### ISSUE TITLE
Submitting

### ISSUE THREAD

**Issue by reggietech** [exercism/exercism#5246]
Quick question.  I am new to exercism. Installed everything. It works great. Ran pytest,  on the example hello world. Great. But i am not sure how to submit it.

IT only says the following.   exercism submit /path/to/file [/path/to/file2 ...]

what goes in the path to file. I cannot find anything on the website. Thanks for your help.

**Comment by kotp** [comment]
On the website when looking at your current exercise, there is a 3 step instruction block.

![3_steps](https://user-images.githubusercontent.com/16747/79075521-613ad780-7cc1-11ea-875a-57f63e55d102.png)

For the exercise that you are on, I think the command would be:

`exercism submit hello.py`

**Comment by reggietech** [comment]
Before your email I was able to figure it out. The only part was it was not clear how to submit it to the site. I posted a question on GitHub FAQ.  Unless you have used before and  how to submit it.

**Comment by dudley1985** [comment]
I have not been in controll of this phone in a long time I've called
countless times they get it straighting up then it started again but I did
not email or send nothing sir

**Comment by reggietech** [comment]
My mistake. I took this as email from a friend I was asking for help.  I did not realize this was from GitHub where I submitted my question. Apolgies.

**Comment by reggietech** [comment]
Worked perfectly. Only one last question. If it does submit successfully. What would I see. I read that you could submit something that you know is not successful and get a solution.

**Comment by kotp** [comment]
Another note is that you can use the `exercism` tool itself to get answers as well, and perhaps it is even clearer than the web page...

```
$ exercism help submit                 
Submit your solution to an Exercism exercise.

    Call the command with the list of files you want to submit.

Usage:
   submit FILE1 [FILE2 ...] [flags]

Aliases:
  submit, s

Flags:
  -h, --help   help for submit

Global Flags:
      --timeout int    override the default HTTP timeout (seconds)
      --unmask-token   will unmask the API during a request/response dump
  -v, --verbose        verbose output

```

If it does not submit successfully, you will see what it provides you.  (In other words, I would need to know the reason why it would be failing to submit, in order to predict what it would give you back as a message.)

However, this would be one message given a specific circumstance where it might fail:

```
exercism submit bananas              
Error: 

    The file you are trying to submit cannot be found.

        /home/student/exercism/ruby/gigasecond/bananas

```

**Comment by kotp** [comment]
Closing based on the response of "worked perfectly".
