### ISSUE TITLE
Submit not working. 

### ISSUE THREAD

**Issue by FionaDL** [exercism/exercism#5247]
~/Exercism/ruby/resistor-color-duo » exercism submit resistor-color-duo.rb                                                    
Error:

    The file you are trying to submit cannot be found.

        /Users/<username>/Exercism/ruby/resistor-color-duo/resistor-color-duo.rb

I have checked my file path including capital letters, and it is the correct path.

**Comment by iHiD** [comment]
> I have checked my file path including capital letters, and it is the correct path.

If you run
```
ls  /Users/<username>/Exercism/ruby/resistor-color-duo/resistor-color-duo.rb
```

Do you get a result?

---

I suspect the problem is hyphens instead of underscores in the filename.
