### ISSUE TITLE
I want to upload my solution to my github repository

### ISSUE THREAD

**Issue by JHLeeeMe** [exercism/exercism#5248]
Hello
I am a new Exercism student
I want to upload my solution to my github repository.
Are there any copyrights or restrictions I should be aware of?

**Comment by glennj** [comment]
Discussed in https://exercism.io/terms-of-service

**Comment by iHiD** [comment]
As @glennj says, your solutions are yours to do as you wish with. The only thing you can't do is claim some ownership over Exercism itself, the name, logo, etc. But you can say "These are my exercism solutions" and do as you wish with them :) Enjoy!
