### ISSUE TITLE
Cannot submit

### ISSUE THREAD

**Issue by vaughajm** [exercism/exercism#5249]
Submit is giving:
Error: not in workspace

**Comment by iHiD** [comment]
That means the file your submitting isn't in the workspace. If you'd like more detailed help, you're going to need to provide more details about what you've done so far, and what you're running to try and submit.

**Comment by lish90** [comment]
Hello,

im trying to submit my code for review and getting error message saying 
"➜  two-fer exercism submit Exercism/javascript/javascript/two-fer
Error: 

    The file you are trying to submit cannot be found.

        /Users/li/Exercism/javascript/javascript/two-fer/Exercism/javascript/javascript/two-fer"
 is there problem with file path and if so want can I do correct it ??

thank you in advanced

**Comment by kotp** [comment]
The path is suspicious for sure.

Can you look in the troubleshooting efforts that are in #5296?

**Comment by dudley1985** [comment]
I dont understand im just a student trying to learn coding,, cause i had
dreams off buying in microsoft , but th| country life dont in envovle all
this

**Comment by vaughajm** [comment]
Working now.
