### ISSUE TITLE
Code preview pane too narrow

### ISSUE THREAD

**Issue by cmcaine** [exercism/exercism#5250]
See: https://exercism.io/tracks/julia/exercises/isogram/solutions/f3790097a9b84f909bddad4438d74f5f

The code is the main focus, but I can't read it because it looks like this:
![image](https://user-images.githubusercontent.com/6000761/79279382-d5ce6b80-7ea5-11ea-8f14-d59a1316d4fb.png)

Moving the "what can you learn" box somewhere else would be helpful.

**Comment by cmcaine** [comment]
This is particularly exacerbated because it's code by my friend who doesn't believe in linebreaks in comments, but 1) I think that's mostly legit 2) real code can be wider than this sometimes, too

**Comment by kotp** [comment]
Have you tried changing your setings? [preferences](https://exercism.io/my/settings/preferences/edit)

![code_view_options](https://user-images.githubusercontent.com/16747/79280378-35b11c00-7e7e-11ea-9d65-60b05d6e8887.png)

This does not exist as a problem with that set to "wide".

**Comment by SleeplessByte** [comment]
(TIL, I didn't know that was a thing. Thanks @kotp)

**Comment by iHiD** [comment]
I can close this, right?

**Comment by kotp** [comment]
Not if I close it first.  (But I think that if it needs a reopen, @cmcaine will be able to comment and reopen.
