### ISSUE TITLE
sml track code formatting

### ISSUE THREAD

**Issue by idkjs** [exercism/exercism#5252]
Is it possible to get some direction on how to set up code formatting for the standardml track?

If this is not the right place to ask can you direct me to the correct place? 

Thank you.

**Comment by iHiD** [comment]
Hey. We use Prism. So the first step is to choose the closest language that will work from [here](https://prismjs.com/test.html) and then paste it back in this issue :)

**Comment by idkjs** [comment]
I cant say i understand what you mean. If I select `OCaml` and paste in:

```
<p class="hey">fun isLeapYear2(year) =
case (year mod 100, year mod 400) of
     (0,0) => true | (0,_) => false |
     _ => year mod 4 = 0;</p>
```
I get:

```
<p class="hey">fun isLeapYear2(year) =
case (year mod 100, year mod 400) of
     (0,0) => true | (0,_) => false |
     _ => year mod 4 = 0;</p>
```

I cant see that it does anything. Is this what you mean?

Thanks

**Comment by iHiD** [comment]
If I paste your code into the top box, and choose ocaml, I get the output of the second box as below:

<img width="428" alt="Screenshot 2020-04-20 at 15 55 46" src="https://user-images.githubusercontent.com/286476/79766129-7518b600-831f-11ea-8f51-b86fa7d9e0b2.png">

**Comment by idkjs** [comment]
I see the difference but the question was about code formatting. Have it worked on in vscode using the [stonebuddha/vscode-better-sml](https://github.com/stonebuddha/vscode-better-sml) extension and adding the following to `settings.json`:

```json
  "[sml]": {
    "editor.defaultFormatter": "stonebuddha.vscode-better-sml"
  },
```

For future reference...

Thanks for the feedback.
