### ISSUE TITLE
exercism.io for University Courses

### ISSUE THREAD

**Issue by nachovizzo** [exercism/exercism#5253]
Hello there,

I'm currently teaching Modren C++ at the University of Bonn in Germany(https://www.ipb.uni-bonn.de/teaching/cpp-2020/) We do have an automatic homework checker(https://github.com/PRBonn/ipb_homework_checker) But I'm highly interested in using exercism.io.

Do you know of any other Universities using your exercises? Does anyone successfully integrated these exercises into their courses?

Is there any way to use your exercises through an API? We have a Gitlab server for our git and CI/CD infrastructure.

In case this is not possible(I don't think to force all the students to make an account there would be possible) Is there any LICENSE requirement to use your exercises in our course? Maybe I can borrow the test code for the assignments?

Thanks

**Comment by SleeplessByte** [comment]
Until someone from @exercism/staff responds to this, you can absolutely use the [Teams feature](https://teams.exercism.io/teams) to use the platform in a team-setting (such as a course or class). I _think_ all the exercises (including C++) are MIT -- see https://github.com/exercism/cpp/blob/master/LICENSE. 

You can also take [the test runner](https://github.com/exercism/cpp-test-runner) and build your own little version.

We know of some educational platforms using the Teams future.

**Comment by iHiD** [comment]
Hey, sorry for the slow response. Thanks @SleeplessByte for the nudge.

Lots of places use Exercism to teach, yes :) As @SleeplessByte said you can use teams or just take the exercises/tests. If you do this, mentioning Exercism as the source would be appreciated :) 

In v3 (coming in the summer) we'll be integrating Teams much more closely into the product.
