### ISSUE TITLE
jest: command not found 

### ISSUE THREAD

**Issue by MrkH615** [exercism/exercism#5255]
The first test for two-fer failed with the message `sh: jest:  command not found`. I'm not sure how to fix this.

**Comment by glennj** [comment]
What language track?

**Comment by MrkH615** [comment]
JavaScript.

**Comment by glennj** [comment]
Did you `npm install`?

**Comment by MrkH615** [comment]
Yes. A while back

**Comment by MrkH615** [comment]
Version 6.13.7

**Comment by iHiD** [comment]
(cc @exercism/javascript)

**Comment by SleeplessByte** [comment]
Did you npm install I side the exercise directory (and not somewhere else)?

You can check this by looking for a folder inside the exercise directory called `node_modules`. Inside it should be a folder `.bin` and inside that you should find `jest`. 

If it's not there, run `npm install`.

**Comment by glennj** [comment]
> Yes. A while back

You'll need to do this for every new exercise, in the exercise directory.

**Comment by MrkH615** [comment]
Done. Not getting this error message anymore. Thanks.
