### ISSUE TITLE
Very long wait times for mentor feedback on Rust track

### ISSUE THREAD

**Issue by BPoserow** [exercism/exercism#5256]
Each exercise is taking at least 1-2 months and often a lot more to receive feedback from mentors per exercise.  If it is not realistic to get relatively frequent mentor feedback, would it be possible to unlock exercises on the Rust track so at least I can see what solutions others have provided and get access to more exercises?  Thanks for any feedback you can provide.

**Comment by iHiD** [comment]
Hi @BPoserow. Sorry for the wait and thank you for your nice message. You can switch to "Practice Mode" on the right hand side of the track (on desktop), which allows you to progress.

I'll also be putting this video live on the website later today which explains a bit more about why the wait times are so long: https://www.youtube.com/watch?v=XiV_vYn1Ea8

Thanks for your patience and understanding. If you have any issues getting into Practice Mode please reopen this issue.
