### ISSUE TITLE
Feature Request: Editor dotfiles (esp vscode)

### ISSUE THREAD

**Issue by acestronautical** [exercism/exercism#5259]
# Feature Request

Many editors support configuration via some form of hidden directory or hidden files (known as dotfiles because the filenames start with a ".")

I would like to suggest supporting the most popular editors ( VSCode, Visual Studio, Notepad++, IntelliJ, Vim), but at a minimum we should support VSCode as it is far and away the most popular editor (over 50% of developers according to stackoverflow, and probably more so for new devs/students).

This is especially important for languages like C, which are impossible for the beginner to debug without assistance.

To this end I have created VSCode dotfiles for the C projects, which should live in a .vscode folder in the root of the excercise folder.

## launch.json
```JSON
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/tests.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build"
        }
    ]
}
```
 
## tasks.json
```JSON
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "make tests.out",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

**Comment by Ace-Cassidy** [comment]
I'm requesting this because I just starting working through the C track, and honestly if I didn't already know C I would have been very lost.

**Comment by iHiD** [comment]
Thanks for this. I'm going to ask a few people to weight in.

**Comment by Ace-Cassidy** [comment]
Another option could be to create editor extensions/plugins/whatever to better support debugging etc... But I imagine that would be MUCH harder than setting up some config files. 

As far as I know the configs for different editors shouldn't interfere with each other so this could be implemented by simply including all the various configs into each excercise, though it would be better to provide a setting for which editor you are using which selectively bundles the correct config for your editor, or even just make these files available for manual download on the track page in some fine print.

I suspect that the config needed will stay the same within each track, and thus the same for each combination of track+editor. The number of configs to generate shouldn't much exceed number of editors supported * number of tracks.

**Comment by ErikSchierboom** [comment]
> This is especially important for languages like C, which are impossible for the beginner to debug without assistance.

What exactly will students be debugging? Most tracks have the students write a library, not an actual application. Or do you mean the option to debugging when running the tests?

**Comment by Ace-Cassidy** [comment]
Debugging the test cases so that students can figure why they are failing a given test case. The vscode files I uploaded provides a build task which runs '''make tests.out''' and a debug task which allows for setting breakpoint in the test or exercise files. Having these config files set up allows the student to click the debug icon in the UI to debug, or select build to build.

**Comment by Ace-Cassidy** [comment]
Additionally in VSCode there may be an extensions.json which when present will cue a prompt in the editor suggesting to install any extensions listed in the extensions.json. For example a user opens an excercise and they receive a prompt asking to install proper language support, formatting, highlighting, etc... This could be especially useful for typescript/JavaScript to set up the proper formatting standard and/or enable eslint with proper linting rules.

There is also a settings.json which can be included to set formatting style, auto format, auto save, and many other options.

Some of these settings may not be desirable/needed, but I'm just trying to give examples of how powerful the config files are for VSCode, and in fact for most editors.

**Comment by ErikSchierboom** [comment]
Alright, I get what you're suggesting. We'll look into it!

**Comment by SleeplessByte** [comment]
As a stop-gap, we can have maintainers add the extensions you recommend to the instructions starting the track.

**Comment by Ace-Cassidy** [comment]
I would think the launch.json and tasks.json are more important since without them your debugger won't work and they're kind of tricky to set up. But idk ┐( ∵ )┌

**Comment by SleeplessByte** [comment]
My comment would include adding that. So for example, for JavaScript I would turn [this comment I wrote](https://github.com/exercism/exercism/issues/5224#issuecomment-604730354) into content for the JavaScript track instructions 😄

**Comment by Ace-Cassidy** [comment]
That looks like exactly what we need :)

**Comment by iHiD** [comment]
Bearing in my that we have in-browser coding in v3 for "trying things out", I wonder if it would be better for each track to provide a specific bundle of things that people could install when they want to proceed with that track. I'm a little wary of the fact that an Exercism exercise would want to mess with my VSCode extensions etc (even if it was just installing extra stuff). But if I decided to settle into a language, then having that as an option would be nice.

I'm just thinking outloud here.

**Comment by Ace-Cassidy** [comment]
The in-browser coding goes along with this as having an environment already set up for you is one of the central ideas behind eclipse theia and gitpod. https://theia-ide.org/ https://gitpod.io/

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
