### ISSUE TITLE
Cannot Download Exercise

### ISSUE THREAD

**Issue by solidaycl** [exercism/exercism#5260]
Hello, so I downloaded exercism and ran it successfully on my mac. Hoorah! So I went to install it on my linux box and I have been running into issues configuring the api key. Here is the troubleshooting information below. 

![image](https://user-images.githubusercontent.com/12747691/79814540-8a580980-834c-11ea-8c20-5007aadf6bd7.png)

So right, easy I thought, just add the api key like I did on mac. It does not seem to work though. I have tried giving the command sudo and still nothing. I am stuck in a loop of successfully adding the api key and finding out the api key not being set. I reset my token after this post.

![image](https://user-images.githubusercontent.com/12747691/79814497-61377900-834c-11ea-9150-6e917ddccc82.png)

Any ideas?

**Comment by NobbZ** [comment]
Sadly there are issues with the snap install finding it's configuration, and we haven't figured out yet why.

Sometimes it just uses the correct location, sometimes it tries to use a sandboxed copy of the settings.

The thing is, it seem to have written the config to the proper place, but when reading it tries a different location.

I *think* this is related to the shim-wrapping that snap does. But I can not reproduce the issue.

Please create a hardlink (if possible) between `~/.config/exercism/user.json` and `~/snap/exercism/5/.config/exercism/user.json`. Copy if you can't link.

Also, a very important note: Your API key has leaked, please visit https://exercism.io/my/settings and reset your API key, reconfigure all your workstations after that.

**Comment by ak2012** [comment]
Hey NobbZ, i'm having the exact issue, could you expand on what you mean by creating a hardlink?

**Comment by NobbZ** [comment]
By "creating a hardlink" I mean creating a hardlink using the `ln` command without the `-s` switch.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
