### ISSUE TITLE
Request to delete account with handle 'jorgemsrs'

### ISSUE THREAD

**Issue by jorgemsrs** [exercism/exercism#5264]
Hi

When creating a new account, I most certainly made a typo in the email address and never got the confirmation link in my inbox. When I tried to recover it I got something along the lines "Email not found".

In the interim I've created an account with Github integration for the email (as it should have been created in the first step) "jorgemsrs@gmail.com" and my handle is now "jorgemsrs-1562". I just want to be able to change it to "jorgemsrs".

Can you help?

**Comment by ynfle** [comment]
If you go to https://exercism.io/my/settings, there is an option to change your handle
![image](https://user-images.githubusercontent.com/23086821/81844684-6f2c8400-951d-11ea-88b7-d6af30924026.png)

**Comment by iHiD** [comment]
I've sorted it for you.

**Comment by jorgemsrs** [comment]
Thank you!
