### ISSUE TITLE
Error: The file you are trying to submit cannot be found

### ISSUE THREAD

**Issue by RHieger** [exercism/exercism#5266]
As I understand it, to submit a solution to an exercise the CLI command syntax is:

`
exercism submit /path/to/file [/path/to/file2 ...]
`
What is unclear is from which part of the directory tree this command should be executed. I tried from within the root directory of `/exercism` with the following command:

`exercism submit /javascript/hello-world/hello-world.js`.

This command failed with the captioned error message. Execution from any other directory resulted in the following message:

`
Error:

       The file you are trying to submit cannot be found.

               /hello-world/hello-world.js
`

I know, for a fact that the file in question resides at the location specified as I have run the file successfully, run all tests and got a pass from all the tests.

Any insight into what might be going wrong is greatly appreciated. I wold very much like to move forward in my track.

**Comment by kotp** [comment]
The leading slash is stating to grab a file from the there, and that is not likely where that file is.

If you are in:

    /home/rhiger/exercism/javascript/hello-world

Then you would execute:

    exercism submit hello-world.js

**Comment by RHieger** [comment]
Thanks, this seems to have worked. I also discovered that the metadata required by exercism was missing from my project. That was probably the real issue. Once I downloaded a fresh copy, and copied and pasted my code from the original, it was possible to do the upload.

Thanks for your assistance. 👍
