### ISSUE TITLE
Why doesn't 'Hello, World!' work?

### ISSUE THREAD

**Issue by michaelpaulcuccia** [exercism/exercism#5272]
![hello-world](https://user-images.githubusercontent.com/54822888/80756154-0a763000-8b00-11ea-8a66-c7bc421f38bd.PNG)

**Comment by iHiD** [comment]
Hello. Well you've not solved the problem because your code is wrong :) I'm not sure if you'd like me to tell you the answer or not, but as a strong hint there's no requirement to log things to a console, the function is expected to return the string `"Hello, world"`.

**Comment by michaelpaulcuccia** [comment]
I just gave myself a very, very firm facepalm...

Thank you.
     On Thursday, April 30, 2020, 04:41:39 PM EDT, Jeremy Walker <notifications@github.com> wrote:  
 
 


Hello. Well you've not solved the problem because your code is wrong :) I'm not sure if you'd like me to tell you the answer or not, but as a strong hint there's no requirement to log things to a console, the function is expected to return the string "Hello, world".

**Comment by michaelpaulcuccia** [comment]
ok, so what about submission? Please take a look at the picture. 
![submission1](https://user-images.githubusercontent.com/54822888/80758741-2085ef80-8b04-11ea-8aea-e9041451251e.PNG)

**Comment by michaelpaulcuccia** [comment]
One more issue...submitting
I posted to GitHub, https://github.com/exercism/exercism/issues/5272
     On Thursday, April 30, 2020, 04:41:39 PM EDT, Jeremy Walker <notifications@github.com> wrote:  
 
 


Hello. Well you've not solved the problem because your code is wrong :) I'm not sure if you'd like me to tell you the answer or not, but as a strong hint there's no requirement to log things to a console, the function is expected to return the string "Hello, world".

**Comment by iHiD** [comment]
Try just `exercism submit hello-world.js` when you're in that directory.

**Comment by michaelpaulcuccia** [comment]
micha@LAPTOP-LMUECM7G MINGW64 /c/Exercism/javascript/hello-world
$ exercism submit hello-world.js
Error: CreateFile C:\Users\micha\Exercism: The system cannot find the file specified.

**Comment by iHiD** [comment]
No idea. I've never seen that before. Looking around two other people seem to have that issue. Maybe try [this](https://github.com/exercism/cli/issues/570#issuecomment-400799376). That thread seems helpful generally. I don't use Windows so I can't be much help personally.

@NobbZ @kotp @SleeplessByte? :)

**Comment by kotp** [comment]
It appears that it could be related to the upper case E in Exercism for the folder.  Can you change the folder to have a lower case e instead of the capital E?

The complaint states about the `C:\Users\micha\Exercism:` rather than past that point.

**Comment by michaelpaulcuccia** [comment]
...

**Comment by SleeplessByte** [comment]
It seems that you're in a linux-simulated environment on windows. Whilst I have it working in Bash on Windows, without any extra configuration, I would suggest you try `cmd.exe`.

The `cli` for windows is set up to use a _user path_ because that's always writable on windows. This would, for you be:

```text
C:\Users\micha\Exercism\javascript

```text
🖥 C:
└ 📂 Users
  └─ 📂 micha
     └─ 📂 Exercism
        ├─ 📂 javascript
        |  ├─ 📂 hello-world
        |  └─ 📂<other exercises>
        └─ 📂<other tracks>
```

The second suggestion here would be to use _that_ path and not `C:\Exercism`. On windows, the _only_ files present in `C:\Exercism` should be:

```text
🖥 C:
└ 📂 Exercism
  ├─ 📂 shell
  ├─ exercism.exe
  ├─ LICENSE
  └─ README.md
```

Final suggestion: don't use mingw unless you need that specific environment. WSL will do the job, as does Bash for Windows, Git Bash or any other linux-on-windows terminal. None of these things have anything to do with Exercism.
