### ISSUE TITLE
Still "in progress" 

### ISSUE THREAD

**Issue by KPH3802** [exercism/exercism#5273]
Hello-

I am new here but appreciate all you do! I have finished my first exercise in the Python Track with "Mentor" mode. A mentor has left a comment telling me "Good job" but I still cannot move to the next exercise and still says "In progress" It has been about 45 mins since leaving the comment.

Also, if I switch to "Practice" mode I realize there are no comments but do either of these have a certificate once finished? Is there a difference between Mentor and Practice beyond the comments? 

Thank you!

**Comment by iHiD** [comment]
Do you have a link to the solution? Maybe the mentor commented but didn't approve. Or maybe you haven't pressed the "Complete Exercise" button?

Neither mode has a certificate when you finish. Practice Mode doesn't have ordered exercises or progression, and while you can request mentoring, you get bumped down the queue a lot.

**Comment by KPH3802** [comment]
Link to the solution: https://exercism.io/my/solutions/037cf3a853c34589948a455a5a31509c

When I click on "Complete Exercise" it says the mentor hasn't clicked completed the exercise yet. I think he commented but didn't approve.

**Comment by kotp** [comment]
> When I click on "Complete Exercise" it says the mentor hasn't clicked
> completed the exercise yet. I think he commented but didn't approve. 

The second bullet indicates that you won't require a type check on name,
and that you can simplify the implementation.

I think the mentor is expecting some action on that.

**Comment by KPH3802** [comment]
Oh ok! Thank you! I'll try that.

**Comment by kotp** [comment]
Closing, feel free to reopen if I read into the mentor response incorrectly.
