### ISSUE TITLE
Highlighting wonky when multiline string contains backticks

### ISSUE THREAD

**Issue by cmcaine** [exercism/exercism#5274]
See: https://exercism.io/mentor/solutions/90a1e20b977e474ca75e48513faddc6b

![image](https://user-images.githubusercontent.com/6000761/80928899-c5702900-8d9f-11ea-940a-99b959a7d9fd.png)

Everything within the `"""` should be highlighted in the string colour (optionally, the backticked example bits could be highlighted red or something).

````julia
"""
    count_consecutive(str::AbstractString, start::Int)

Counts the number of identical characters in a given string `str` starting from index `start`.

# Examples 

```julia-repl
julia> count_consecutive("AAAB", 3)
('A', 3)

julia> count_consecutive("x y z", 3)
('y', 1)
```
"""
function count_consecutive(str, start)
    ...
end
````

**Comment by iHiD** [comment]
Does this work for Prism? https://prismjs.com/test.html#language=julia 

If not, you'll need to open this issue there. If so, I'll debug further :)

**Comment by cmcaine** [comment]
It's Prism's fault. Opened an issue with them :)

**Comment by iHiD** [comment]
Thanks! :) When they solve it and publish a new release, we'll need to update here, so feel free to reopen this then.

**Comment by cmcaine** [comment]
PrismJS has been updated, at least on master. Check the linked issue for details :)

**Comment by iHiD** [comment]
@kntsoriano One for you pls?

**Comment by kntsoriano** [comment]
@cmcaine Just waiting for a new version of Prism to be released. Thanks!

**Comment by cmcaine** [comment]
I've made an issue asking if they could cut a release :)

**Comment by cmcaine** [comment]
They say:

master is always stable.

The Prism download page gets its files directly from master (that's why master has to be stable), so you can get new features for there (if that's applicable to you).

We will probably make a new release for npm at the end of the month or a few days later.
(If you need it right now, you can tell npm to fetch Prism directly from master.)

---

So perhaps we can just use master?

**Comment by kntsoriano** [comment]
@cmcaine Currently we can't use master directly as we only rely on a CDN. We could always use webpack and host it ourselves, but will take a bit of time to do so as we need to make sure that that change doesn't break anything on the website.

**Comment by cmcaine** [comment]
Maybe just wait a few weeks for the release then, it's not important enough
for you to do loads of work on :)

**Comment by iHiD** [comment]
Thanks @cmcaine. Shout if you see a new release with it in and we'll update! :)

**Comment by cmcaine** [comment]
A new release of prism has been published :)

**Comment by iHiD** [comment]
@kntsoriano When you're back... :)

**Comment by kntsoriano** [comment]
@cmcaine Thank you so much! I've opened https://github.com/exercism/website/pull/962 to bump our Prism version.
