### ISSUE TITLE
Cannot download exercises, upgrade exercism, etc: socket: permission denied

### ISSUE THREAD

**Issue by dominklenda** [exercism/exercism#5276]
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: dial tcp: lookup api.github.com on [::1]:53: dial udp [::1]:53: socket: permission denied

Operating System
----------------
OS:           linux
Architecture: amd64

Configuration
----------------
Home:      /home/dominik_lenda/snap/exercism/5
Workspace: /home/dominik_lenda/snap/exercism/5/exercism
Config:    /home/dominik_lenda/snap/exercism/5/.config/exercism
API key:   6c55*****************************659

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: dial tcp: lookup api.github.com on [::1]:53: dial udp [::1]:53: socket: permission denied]
    * 592.852µs

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: dial tcp: lookup api.exercism.io on [::1]:53: dial udp [::1]:53: socket: permission denied]
    * 489.296µs

**Comment by iHiD** [comment]
Your machine doesn't (or didn't when you posted this) have connectivity to the internet. It could reach either GitHub nor Exercism. Maybe blocked by VPN?

**Comment by NobbZ** [comment]
Its not even getting that far.

It seems as if it had trouble to talk to a local DNS.

**Comment by dominklenda** [comment]
thanks for your replays.
i still don't know what caused the problem, so i just reinstalled exercism and everything's fine now.

**Comment by villagerz** [comment]
I had the same problem - exercism was working well two weeks back, I upgraded my Pop_OS! to 20.04 and things started to break. I used snap to install exercism. Reinstalling it fixes the problem. 

First, tried an updrage directly:
```
$> exercism upgrade
Error: 

We were not able to upgrade the cli because we encountered an error:
Get https://api.github.com/repos/exercism/cli/releases/latest: dial tcp: lookup api.github.com on [::1]:53: dial udp [::1]:53: socket: permission denied

Please check the FAQ for solutions to common upgrading issues.

https://exercism.io/faqs
```
Then ran `exercism troubleshoot` which also showed the same `dial tcp socket permission denied` messages.

Removed exercism at this point 
```
sudo snap remove exercism
[sudo] password for :
exercism removed
```
Finally, reinstalled, checked version, ran troubleshoot again and reconfigured exercism with my token:
```
sudo snap install exercism
exercism SNAPSHOT-ba48dcd from Exercism Team (exercism) installed
$ which exercism
/snap/bin/exercism
$ exercism version
exercism version 3.0.13
$ exercism troubleshoot
--- edited ---
$exercism configure --token=<edited>
```

And the final test:
```
exercism download --exercise=collatz-conjecture --track=haskell

Downloaded to
.../snap/exercism/5/exercism/haskell/collatz-conjecture
```

**Comment by Pasqat** [comment]
Same problem, but **solved** with solution proposed by @villagerz

**Comment by kotp** [comment]
Thanks for reporting success with that solution, @Pasqat  and it looks like the issue can be closed now, @dominklenda ?  Fee free to reopen, if that is not the case.
