### ISSUE TITLE
Java exercises locked despite having completed track

### ISSUE THREAD

**Issue by mstange22** [exercism/exercism#5281]
Similar to previous issues.  This time, 4 exercises show as locked for me:
* Micro Blog
* Rest API
* Hangman
* Satellite

Not really holding me up as there are plenty more to do still, but I was curious to check out Satellite as I haven't seen that in any of the other languages.

From past experience, seems like it's just a process that has to be run, so when you get a chance, could you let it rip?  Thanks!

**Comment by iHiD** [comment]
Script is running now :)

**Comment by mstange22** [comment]
Looks good, thanks!

**Comment by iHiD** [comment]
Great. Thanks for letting me know :)
