### ISSUE TITLE
Awaiting Mentor Change - Problem?

### ISSUE THREAD

**Issue by stefansilverio** [exercism/exercism#5282]
The exercise below on the C++ track has been waiting in the queue for mentor review for about four days. It says "There are currently 0 solutions ahead of this in the C++ queue, and 0 ahead in the Reverse String queue. The median waiting time for mentoring on this exercise is about 2 hours." I had a mentor change so I just want to make sure nothings wrong and that this gets picked up. Thanks.
https://exercism.io/my/solutions/0e39cbce3a8343d091e39967ae108540

**Comment by iHiD** [comment]
Hi. There's no problem per se. However, when a new mentor picks this solution up they're going to take a look at the conversation so far and decide if they want to mentor you on the exercise or not. So you're going to have to wait for a mentor who wants to go through helping you on this lower-level version of the exercise. If you don't want to use the mentors advice and just want to continue you might want to move to Practice Mode. Then you can ping mentors for advise but not be blocked from continuing (although they'll be slower to respond in this mode).
