### ISSUE TITLE
Not receiving Exercism emails to custom domain mail

### ISSUE THREAD

**Issue by jakubvavrik** [exercism/exercism#5284]
Hello there,

I have problem with not receiving emails from Exercism to my custom domain proton mail. I had to register through GitHub (registered on the same mail and receiving all automated mails just fine) because of this and now I dont get any notifications for mentors commenting my code.

I tried to switch email settings to my gmail account and it started working so it is not a huge issue for me, but maybe it could be worth to look into it for future generations?

Thanks and have a wonderful day
J.

**Comment by iHiD** [comment]
Strange, thanks. To clarify: 
- You first registered with your proton email and didn't get any. 
- Then you registered again with GitHub with the same email and did get some?

Have I understood that correctly?
Which account did you switch email settings on?

**Comment by jakubvavrik** [comment]
I tried to register to exercism with the custom domain mail and didnt get the email verification. So i registered on github with it without problems and then used the github account to login into Exercism. That didnt generate any Exercism email neither. Then i switched email setting inside Exercism to my gmail which works fine now and I am receiving emails.

My handle on Exercism is same as here - jakubvavrik.

**Comment by iHiD** [comment]
Mind either posting the email address here or emailing me from it at jeremy@exercism.io and I can check the logs?

**Comment by jakubvavrik** [comment]
Sent you a mail.

**Comment by iHiD** [comment]
Thanks. I've replied there. It seems to be some sort of issue with your domain. I'll close this and we can discuss over email :)
