### ISSUE TITLE
Cannot submit my solution

### ISSUE THREAD

**Issue by yuckyrat** [exercism/exercism#5288]
I've completed the hello world track in Python, and I have the files in the correct places, but submitting it as instructed results in it stating that the solution could not be found. I am submitting the filename with the directory as instructed.

What is happening, and how can I fix it?

(Additionally: the pytest for the function worked.)

**Comment by kotp** [comment]
What is the exact command you used, and what is your current working directory when you do so?

**Comment by glennj** [comment]
Please run `exercism troubleshoot` and paste the output here.

**Comment by yuckyrat** [comment]
> 
> 
> What is the exact command you used, and what is your current working directory when you do so?

I've tried the paths, ending with the filename, like the instructions said. It is a .py file and is located in the Exercism hello world folder.

**Comment by kotp** [comment]
Again, what is the exact command you used, rather than my interpretation of how you interpreted the instructions.

To clarify, let me show you how I submitted the file:

    exercism submit hello_world.py

My Exercism hello world directory is:

    /home/george/exercism/python/hello-world

And I execute that command from that directory.

**Comment by kotp** [comment]
Also, what glennj wrote may be helpful to find out if there is something else going on.

**Comment by yuckyrat** [comment]
Here's what happens.
![image](https://user-images.githubusercontent.com/60765813/82518471-763f2d80-9aed-11ea-9931-3bad8eed6b52.png)

@kotp

**Comment by kotp** [comment]
Thanks.

What do you get when you do the `exercism troubleshoot` command?

**Comment by yuckyrat** [comment]
![image](https://user-images.githubusercontent.com/60765813/82520474-3890d380-9af2-11ea-834c-dfb96c45d0a5.png)
![image](https://user-images.githubusercontent.com/60765813/82520483-3e86b480-9af2-11ea-8723-6680deff32da.png)
@kotp

**Comment by kotp** [comment]
What does the listing look like for that folder?

    dir C:\Users\asmit\Exercism\python\hello-world

**Comment by yuckyrat** [comment]
@kotp 
![image](https://user-images.githubusercontent.com/60765813/82521419-a8a05900-9af4-11ea-9fa6-414f50c32a00.png)

**Comment by kotp** [comment]
Thanks.  I have asked for help, because I totally did not expect this kind of listing from a `dir` command.

**Comment by kotp** [comment]
What terminal are you using?  Are you getting to the command line by using powershell or cmd?

**Comment by kotp** [comment]
Also, what happens when you do `exercism submit ./hello_world.py`. with the `./` before the name of the file?

**Comment by yuckyrat** [comment]
@kotp I'm using cmd, and the ./ still results in "This solution could not be found".

**Comment by NobbZ** [comment]
In the `.exercism` folder, is there a JSON file? What is its content?

**Comment by yuckyrat** [comment]
> 
> 
> In the `.exercism` folder, is there a JSON file? What is its content?

There is not.
![image](https://user-images.githubusercontent.com/60765813/82567623-9d2c4c80-9b4b-11ea-9ecf-58dd4543dd7f.png)

**Comment by glennj** [comment]
Try re-downloading it: `exercism download --exercise=hello-world --track=python` -- that should populate the .exercism directory with the needed contents.

**Comment by yuckyrat** [comment]
@glennj It worked! Thank you so much!
