### ISSUE TITLE
Script error on walk through

### ISSUE THREAD

**Issue by motdde** [exercism/exercism#5290]
![image](https://user-images.githubusercontent.com/12215060/82718988-5c911800-9c9e-11ea-97e1-869f5ea203df.png)

**Comment by iHiD** [comment]
That's not good. Is this repeatable every time for you:

**Comment by motdde** [comment]
Yes, it repeatable. Same step

**Comment by glennj** [comment]
What's the URL?

**Comment by motdde** [comment]
I just test about three challenges, I'll assume it's on all the get started walkthrough.

Here is how I got the error:

click(Begin Walk-Through) => click(Mac) => click(yes) =>
click(I don't know my processor architecture) => click(yes)

**Comment by iHiD** [comment]
@kntsoriano Could you take a look pls?

**Comment by kntsoriano** [comment]
@iHiD I've opened https://github.com/exercism/exercism/issues/5290 to fix this.

**Comment by motdde** [comment]
👍🏾, I have some other suggestions/bugs but I don't code in ruby 😭

**Comment by iHiD** [comment]
@motdde Great :)

The CI walkthrough isn't really Ruby. It's just lots of HTML files here: https://github.com/exercism/interactive-cli-walkthrough

So you can can put PRs together for changes in there and @kntsoriano can work his magic :)

**Comment by motdde** [comment]
Thanks, @iHiD I figured out after @kntsoriano fixed and raised a PR it.
