### ISSUE TITLE
Need more explianation

### ISSUE THREAD

**Issue by shoukreytom** [exercism/exercism#5291]
[Twelve Days](https://exercism.io/my/solutions/7072d07882854a7a904f36c3781f19b7): this exercise is not clear

**Comment by iHiD** [comment]
I think we also need more explanation about what isn't clear about it :)

**Comment by shoukreytom** [comment]
> I think we also need more explanation about what isn't clear about it :)

you should provide sample input, output or add some instruction or rules to it like in [Raindrops](https://exercism.io/my/solutions/d2e6d173cf7649c3aa6e2cec578ee1f4), [Matix](https://exercism.io/my/solutions/6b0c421bc88844de9803d421f3470dad) and all previous examples

**Comment by iHiD** [comment]
Well, it has all those, so it sounds more like there is some sort of issue going on. Maybe you could provide some more information, such as the track you're on, your solution id and a screenshot.

**Comment by shoukreytom** [comment]
![Screenshot from 2020-05-27 16-46-42](https://user-images.githubusercontent.com/45360813/83035588-eb54ba80-a039-11ea-905c-b5fd3864fe23.png)
here is the screenshot

**Comment by iHiD** [comment]
OK. And what is unclear about those instructions?
