### ISSUE TITLE
Cannot Upload - Error: Not in Workspace

### ISSUE THREAD

**Issue by mark-james-coder** [exercism/exercism#5296]
I am new to Exercism and on the second exercise of the Ruby track. I get the message 'Error: not in workspace' when trying to submit the exercise file.

I have looked through the Issues raised on here and it seems a common problem is because of the exercism directory being capitalized on a Mac, so I changed it to lowercase and still doesn't work.

Marks-MBP:gigasecond Mark$ exercism workspace
/Users/Mark/exercism

Marks-MBP:gigasecond Mark$ exercism submit gigasecond.rb
Error: not in workspace

**Comment by mark-james-coder** [comment]
I'm not sure where I should go.

```
Marks-MBP:gigasecond Mark$ cd /Users/Mark/Exercism/ruby/gigasecond
Marks-MBP:gigasecond Mark$ exercism workspace
/Users/Mark/exercism
```

**Comment by mark-james-coder** [comment]
```
Marks-MBP:gigasecond Mark$ ls
README.md		gigasecond.rb		gigasecond_test.rb
```

**Comment by kotp** [comment]
I wonder if exercism/exercism#5297 is related…

**Comment by iHiD** [comment]
@mark-james-coder Can you paste the results of `ls -lah /Users/Mark/Exercism/ruby/gigasecond` pls?

**Comment by mark-james-coder** [comment]
```
Marks-MBP:gigasecond Mark$ ls -lah /Users/Mark/Exercism/ruby/gigasecond
total 24
drwxr-xr-x  6 Mark  staff   192B 28 May 11:02 .
drwxr-xr-x  5 Mark  staff   160B 27 May 22:59 ..
drwxr-xr-x  3 Mark  staff    96B 27 May 16:08 .exercism
-rw-r--r--  1 Mark  staff   1.0K 28 May 10:58 README.md
-rw-r--r--  1 Mark  staff    66B 28 May 12:18 gigasecond.rb
-rw-r--r--@ 1 Mark  staff   957B 28 May 12:18 gigasecond_test.rb
```

**Comment by iHiD** [comment]
This is very odd. Could you paste the contents of `.exercism` pls and any files within it.

**Comment by mark-james-coder** [comment]
```
Marks-MBP:gigasecond Mark$ ls -lah /Users/Mark/Exercism/ruby/gigasecond/.exercism
total 8
drwxr-xr-x  3 Mark  staff    96B 27 May 16:08 .
drwxr-xr-x  6 Mark  staff   192B 28 May 11:02 ..
-rw-------  1 Mark  staff   213B 28 May 10:58 metadata.json
```
```
Marks-MBP:gigasecond Mark$ ls -lah /Users/Mark/Exercism/ruby/gigasecond/.exercism/metadata.json
-rw-------  1 Mark  staff   213B 28 May 10:58 /Users/Mark/Exercism/ruby/gigasecond/.exercism/metadata.json
```

**Comment by iHiD** [comment]
Thanks. Could you paste the content of `metadata.json` pls? (e.g. `less metadata.json`)

**Comment by mark-james-coder** [comment]
```{"track":"ruby","exercise":"gigasecond","id":"38be1c4e71d64597b67389c80a426b42","url":"https://exercism.io/my/solutions/38be1c4e71d64597b67389c80a426b42","handle":"markjp","is_requester":true,"auto_approve":false}```

**Comment by iHiD** [comment]
Thanks @mark-james-coder.

Very weird. @sleeplessbyte @nobbz Any ideas?

**Comment by SleeplessByte** [comment]
The issue might be that the directory is called `exercism` and not `Exercism`. Rename the directory; that should fix the issue.

**Comment by SleeplessByte** [comment]
It's probably a mismatch because of capitalisation. The `debug` says:

```
Workspace: /Users/Mark/exercism
Config:    /Users/Mark/.config/exercism
```

But your other paths say:

``` 
/Users/Mark/Exercism
```

Most likely this can be fixed by matching capitalisation.

**Comment by mark-james-coder** [comment]
Thanks, can you give me the command for that please, to make sure I do it right

**Comment by SleeplessByte** [comment]
I can't with confidence say which one it should be, BUT it seems that this issue might be exactly the same as one of these:

#36 #4081 #3820 #2468

If the directory is already named `Exercism`, maybe first try to rename it to `exercism`. You can do this from the file explorer? @NobbZ will know better what to do here -- but in the meanwhile that's something you can try.

FWIW, I don't know _why_ `exercism` picked the workspace with a lowercase letter e.

**Comment by iHiD** [comment]
@mark-james-coder Does this work?
```
cd /Users/Mark/exercism/ruby/gigasecond/
exercism submit gigasecond.rb
```

**Comment by mark-james-coder** [comment]
@iHiD Yes!
```
Marks-MBP:gigasecond Mark$ exercism submit gigasecond.rb


    Your solution has been submitted successfully.
    View it at:

    
    https://exercism.io/my/solutions/38be1c4e71d64597b67389c80a426b42
```

**Comment by iHiD** [comment]
Wonderful. Sorry that was such a hassle. So just make sure you `cd /Users/Mark/exercism/` with a  small `e` in future :)

**Comment by mark-james-coder** [comment]
oooh! That was a drama. Thanks so much for your help guys.

**Comment by SleeplessByte** [comment]
<3
