### ISSUE TITLE
 The exercise you are submitting doesn't have the necessary metadata.

### ISSUE THREAD

**Issue by jgeorgex** [exercism/exercism#5297]
**Error message:**

_The exercise you are submitting doesn't have the necessary metadata.
Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it._

______________

- Have visited the suggested link which suggests migrating to the new CLI.  
- Installed this week so latest version already running (3.0.13).
- Attempted reinstall to be sure.
- Can see metadata.json in the .exercism directory.  
- Also tried moving metadata.json into the route directory.

**Comment by glennj** [comment]
`exercism download --track=the_track --exercise=the_exercise` should populate the needed metadata files.

**Comment by jgeorgex** [comment]
Thanks @glennj looks like 
`exercism download --track=the_track --exercise=the_exercise `
has fixed the issue.
