### ISSUE TITLE
trying to submit first exercise in JavaScript

### ISSUE THREAD

**Issue by sdkramer** [exercism/exercism#5298]
I am a beginner in JS and command line, not completely new.
I did the exercise, ran test, copied and pasted submit command into terminal, and got response 'bad pattern':
[~/Exercism/javascript/hello-world]$ exercism submit /path/to/file [/path/to/file2 ...]
zsh: bad pattern: [/path/to/file2

Thanks for any help!

**Comment by iHiD** [comment]
You need to acutally put the path to the file. If you're in the correct directory that will probably be `exercism submit something.js` (replace `something.js` with the actual file you edited).

In command line notation you'll often see things like `path/to/file` and its' also worth noting that square brackets implies an optional argument. For example you could do `exercism submit something.js something_else.js` to upload two files.

**Comment by kotp** [comment]
I just want to mention that the other file should not be the test file that was delivered.

**Comment by x8a** [comment]
Maybe it'd be helpful to add a submit section in the README.md file of every exercise. I know it's in the website, but since we're coding in our editor, it'd be convenient to have it there.

**Comment by iHiD** [comment]
@x8a Thanks. @ErikSchierboom Let's consider this as something we auto-add for the README.md file that we give to users along with the CLI.md bit for v3

**Comment by kotp** [comment]
It already exists for some languages in v2.

**Comment by ErikSchierboom** [comment]
@iHiD Yes, this seems like a useful addition. We should at some point modify the CLI to automatically submit the right files, but that is future work.

**Comment by ErikSchierboom** [comment]
As @kotp said, languages _can_ already do this themselves. The easiest way to to so is to modify the `exercise_readme.go.tmpl` file to include such a message. For an example, see this [C# readme template](https://github.com/exercism/csharp/blob/master/config/exercise_readme.go.tmpl#L14) and what the output looks like: https://github.com/exercism/csharp/blob/master/exercises/bob/README.md#running-the-tests

@sdkramer I would suggest to post an issue on the [JavaScript repo](https://github.com/exercism/javascript/issues) stating your issue and linking to this issue for reference.

**Comment by iHiD** [comment]
> exercise_readme.go.tmpl

This will cease to be a thing in v3 though.

**Comment by ErikSchierboom** [comment]
> This will cease to be a thing in v3 though.

True, but it can help in the meantime while we're getting there :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
