### ISSUE TITLE
502 Bad Gateway when trying to sign up with Github account

### ISSUE THREAD

**Issue by Zlopez** [exercism/exercism#5299]
Hi,

today I tried to sign up to exercism with Github account and got the Github permission form and approved it. After this I was redirected to 502 Bad Gateway.

I'm now getting this for either sign up or login.

If this is of any help, here is the IP that returns the 502: `54.229.18.29:443`.

**Comment by iHiD** [comment]
That doesn't sound great. I'll try and take a look for you today or tomorrow. In the mean time, if you want to sign up with an email address instead, we can work things out later.

**Comment by Zlopez** [comment]
The sign-up using mail worked, so I was able to register and login. So it looks like this only affects GitHub account.

**Comment by iHiD** [comment]
Do you have a confirmed email on your GitHub? That has caused problems in the past?

**Comment by Zlopez** [comment]
I have, I'm using the GitHub account for day to day work.

**Comment by iHiD** [comment]
Thanks for checking. Does logging in work now for you?

**Comment by Zlopez** [comment]
Yeah, it's working. Probably it will be best to show some warning to user, when this happens. So they at least check if the e-mail is verified.

**Comment by joseph-so** [comment]
@iHiD , I am also facing this issue when I use firefox developer to login via GitHub. I do not have that issue for other browser.

**Comment by quixoticraindrp** [comment]
I just ran into this issue today (11 JAN 2021). My GitHub account has a verified email address, and I just double-checked to ensure that remains the case.

**Comment by quixoticraindrp** [comment]
> I just ran into this issue today (11 JAN 2021). My GitHub account has a verified email address, and I just double-checked to ensure that remains the case.

I did, however, notice that there were no SSH or GPG keys associated with my account. When I added these, the 502 Gateway Error cleared and I was able to log in. Could be coincidence (temporary network error, perhaps).

**Comment by iHiD** [comment]
Strange. Thanks for reporting.

**Comment by ksala** [comment]
Hey, I had the same issue here. Across several days, several browsers and several connections, so none of those seem to be the issue. What solved it for me was that my primary mail address associated with my github account was apparently not verified (I probably changed it and forgot to verify), once I verified it the login/signup completed.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by mohsenyahmadi** [comment]
i have the same problem i signed in for a student package and i started getting 502 Bad Gateway every time i try to check my student application

**Comment by mohamadreza99** [comment]
I have the same problem. when I am logged out of my github account, this [linke](https://education.github.com/pack) opens without any problem. however, when I log in to my account, the 502 Bad Gatewary error appears. it is independent of device or browser.

**Comment by SleeplessByte** [comment]
That link (GitHub Student Developer Pack) has nothing to do with Exercism @mohsenyahmadi and @mohamadreza99. Why do you think it's related to Exercism?

**Comment by soniyataneja** [comment]
> I have the same problem. when I am logged out of my github account, this [link](https://education.github.com/pack) opens without any problem. however, when I log in to my account, the 502 Bad Gatewary error appears. it is independent of device or browser.

I am facing a similar issue. Getting 502 Gateway error as soon as i login to sign up for student developer pack. Any workarounds for this?
