### ISSUE TITLE
'Test suite failed to run'

### ISSUE THREAD

**Issue by protekon** [exercism/exercism#5300]
I'm seeing this issue every time I try to run "npm test" on my Mac. Is this a known issue? (I've tried googling, but can't find anything.)

```
> exercism-javascript@1.0.0 test /.../Exercism/javascript/resistor-color
> jest --no-cache ./*

 FAIL  ./resistor-color.spec.js
  ● Test suite failed to run

    Cannot find module '@babel/plugin-syntax-bigint' from '/.../Exercism/javascript/resistor-color'

      at Function.resolveSync [as sync] (../../../../../usr/local/lib/node_modules/jest/node_modules/resolve/lib/sync.js:89:15)
          at Array.map (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.41 s
Ran all test suites matching /.\/README.md|.\/babel.config.js|.\/node_modules|.\/package-lock.json|.\/package.json|.\/resistor-color.js|.\/resistor-color.spec.js/i.
npm ERR! Test failed.  See above for more details.
```

**Comment by protekon** [comment]
Update: I have to run the install instructions below with each challenge, in order for the test suite to run properly.

https://babeljs.io/docs/en/babel-preset-env

**Comment by iHiD** [comment]
(cc @exercism/javascript)

**Comment by SleeplessByte** [comment]
As per the installation instructions on Exercism for the JavaScript track:

> **Assignment Requirements**
> Please follow [these instructions](https://exercism.io/cli-walkthrough) to download exercism cli for your OS.
> 
> Once CLI is all setup & configured, download the first exercise - `hello-world`:
> ```
> $ exercism download --exercise=hello-world --track=javascript
> ```
> Each assignment then needs some tools to run the tests. They can be installed running this command within each assignment directory:
> ```
> $ npm install
> ```
>
> https://exercism.io/tracks/javascript/installation

You must run `npm install` each time you download an exercise inside the exercise directory.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by Neossi** [comment]
@ https://github.com/exercism/exercism/issues/5300#issuecomment-636565989
Thanks, it was really informative.
Kind regards
