### ISSUE TITLE
Exercism in Windows Linux Subsystem (WLS) Issues...

### ISSUE THREAD

**Issue by Thorne-1717** [exercism/exercism#5302]
Hi all,
Exercism seems to have trouble submitting or downloading new exercises when using the Windows Linux Subsystem, although the test suite *mostly* works.

Issue, despite having installed, configured, and pointed exercism to the right workspace directory I get the following when using the submit function for an exercise:

`Error: not in workspace`

FYI the windows path to an exercism would be, for example

`c:\users\chris\onedrive\Code Training\exercism\ruby\hello-world\hello_world.rb`

For the WSL thats:

`/mnt/c/users/chris/onedrive/Code Training/exercism/ruby/hello-world/hello_world.rb`

Any ideas on how I could get this to work?

Here is the troubleshooting output

```Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/cduff
Workspace: /mnt/c/users/chris/onedrive/Code Training/exercism
Config:    /home/cduff/.config/exercism
API key:   929b*****************************fd9

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 53.6515ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 504.287ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.```

**Comment by Thorne-1717** [comment]
I suspect this has to do with Linux programs installed in the subsystem being unable to properly access files in mounted windows directories. If the Exercism folder is moved into the Ubuntu subsystem user's home folder the Linux Exercism program works as expected (downloading exercises, testing them, and submitting them).

Interestingly bash can be used to browse windows directories and alter their contents (which is how I got the Exercism folder into the Linux subsystems directories in the first place). So I was assuming if Exercism was installed in the subsystem it would be able to interact with windows files provided the right working directory was set but this is not the case. Furthermore I suspect this is an issue that Microsoft will have to address and there is nothing that the Exercism team can do about it, but I could be wrong.

**Comment by iHiD** [comment]
(cc @ErikSchierboom @sleeplessbyte)

**Comment by kotp** [comment]
The space may be causing some problems.

`/mnt/c/users/chris/onedrive/Code Training/exercism`  I would probably choose to not use a space.

**Comment by Thorne-1717** [comment]
Thanks kotp, I'll give that a try tomorrow

**Comment by Thorne-1717** [comment]
Yup, that fixed it, the space in "/mnt/c/users/chris/onedrive/Code Training/exercise" was messing it up.
