### ISSUE TITLE
can't configure API key

### ISSUE THREAD

**Issue by hdelan** [exercism/exercism#5304]
Hello. I am using exercism on Ubuntu. I configured API using:

```
/snap/exercism/5/exercism configure --token=e*********************c --no-verify
```

and I get the confirmation:

```
You have configured the Exercism command-line client:

Config dir: /root/.config/exercism
Token: (-t, --token) e**********************c
Workspace: (-w, --workspace) /root/exercism
API Base URL: (-a, --api) https://api.exercism.io/v1
```

However when I try to download something I get:

```
exercism download --exercise=hello-world --track=cpp
Error:

Welcome to Exercism!

To get started, you need to configure the tool with your API token.
Find your token at

    https://exercism.io/my/settings

Then run the configure command:

    /snap/exercism/5/exercism configure --token=YOUR_TOKEN
```

But when I run exercism debug it says my API key is not configured:

```
Troubleshooting Information
Version

Current: 3.0.13
Latest: 3.0.13
Operating System

OS: linux
Architecture: amd64
Configuration

Home: /home/hugh/snap/exercism/5
Workspace: /home/hugh/snap/exercism/5/exercism (default)
Config: /home/hugh/.config/exercism
API key: <not configured>
Find your API key at https://exercism.io/my/settings
API Reachability

GitHub:

* https://api.github.com
* [connected]
* 56.414953ms

Exercism:

* https://api.exercism.io/v1/ping
* [connected]
* 197.32874ms

If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

Any help would be greatly appreciated!

**Comment by iHiD** [comment]
There are various issues related to snap: https://github.com/exercism/exercism/search?q=snap&type=Issues

Someone might have some useful insight, but reading those (open and closed) might give you the quickest route to a solution.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
