### ISSUE TITLE
submitting error

### ISSUE THREAD

**Issue by kevxo** [exercism/exercism#5311]
Im working on the first ruby exercise and I'm having trouble submitting my work. When I type exercism submit hello_world.rb it returns "not in workspace"

**Comment by iHiD** [comment]
That probably means:
- You're not in the correct directory (the one with `hello_world.rb`) when you're running the command
- Something isn't configured correctly.

A screenshot and some information on how you installed Exercism will help us debug :)

**Comment by kevxo** [comment]
I was able to fix my problem! Thank you for your help.
