### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by reileyvs** [exercism/exercism#5313]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\VincentS>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\VincentS\pa
ckage.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\VincentS\packa
ge.json'
npm WARN VincentS No description
npm WARN VincentS No repository field.
npm WARN VincentS No README data
npm WARN VincentS No license field.

up to date in 1.345s
found 0 vulnerabilities

I've only just begun coding and have no idea whats wrong or why this isn't working. I went through the whole process to download everything including the hello-world requirements. Thank you.

**Comment by NobbZ** [comment]
You need to run `npm install` from your exercises folder, not from your users "home".

**Comment by reileyvs** [comment]
Where would I find my exercises folder? In my Exercism folder?

**Comment by NobbZ** [comment]
Yes, also when you download an exercise, it should print the absolute path to the download location.

**Comment by tejasbubane** [comment]
@reileyvs You can also use `exercism workspace` to print workspace path. Inside this workspace folder, you should have folders like `javascript/hello-world`.

**Comment by reileyvs** [comment]
Thank you! I figured it out!
