### ISSUE TITLE
I didn't understand how to test my code

### ISSUE THREAD

**Issue by lkmaster** [exercism/exercism#5315]
I installed everything using homebrew and also configured de CLI. 

Then I create my Exercism folder (I thought it should have been created automatically), then downloaded the Hello World exercise. I create the function inside the hello-world.js file that came with the download.

Then I saved and typed npm run test inside the Exercism folder. I received a bunch of different errors. 

Can someone please guide me on how to even start? Sorry for making this silly question.

**Comment by kotp** [comment]
Inside the `Exercism` folder, but inside, also the `hello_world` folder?

Can you show what you did, and what the results were?

For example, I might show what happened like this:

```
$> pwd
/home/kotp/exercism/javascript/hello-world
```

I do this command:

```
npm test hello-world.spec.js
```

And this is what I get back:

```
 FAIL  ./hello-world.spec.js
  Hello World
    ✕ Say Hi! (1ms)

  ● Hello World › Say Hi!

    TypeError: (0 , _helloWorld.hello) is not a function

      3 | describe('Hello World', () => {
      4 |   test('Say Hi!', () => {
    > 5 |     expect(hello()).toEqual('Hello, World!');
        |            ^
      6 |   });
      7 | });
      8 | 

      at Object.<anonymous> (hello-world.spec.js:5:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.765s
Ran all test suites matching /.\/README.md|.\/babel.config.js|.\/hello-world.js|.\/hello-world.spec.js|.\/node_modules|.\/package-lock.json|.\/package.json|hello-world.spec.js/i.             
npm ERR! Test failed.  See above for more details.

```

This will help us know what kind of errors you get.

**Comment by NobbZ** [comment]
Before running `npm test` you might need to install the dependencies using `npm install` in the exercises folder. This has usually to be done once per exercise in JavaScript.

**Comment by lkmaster** [comment]
I have run npm install inside the hello-world folder and it worked. Thanks a lot
