### ISSUE TITLE
Download Exercise Again Without Previous Solution

### ISSUE THREAD

**Issue by navneethc** [exercism/exercism#5317]
Hi. Is there a way to download the exercise that one has already solved but without the submitted solution? (Basically, a fresh copy of the exercise.)

I just downloaded an updated version of an exercise (Python/Hamming Distance) using the command provided, but it comes with my solution. 

I have read through the FAQ and searched through the issues, but couldn't quite find an answer to this question. Apologies if it has been answered elsewhere.

**Comment by iHiD** [comment]
@navneethc Hi. Thanks for the nice issue. No, it's not something you can do through the UI. However, you can find the exercise online and copy the file over the top of your existing solution manually. You want to look in `https://github.com/exercism/$LANG/tree/master/exercises/$EXERCISE`, for example, for the Bob exercise on the Ruby track it would be `https://github.com/exercism/ruby/tree/master/exercises/bob`.

Some exercises have stubs and some don't, but all the files should be in that directory.

Let me know if that solves your problem :)

**Comment by navneethc** [comment]
Thanks for the link, that does help. Since I'm being selective for the time being in which exercises I pick, I will simply overwrite the code file.

But I would also like to place this option to download a new copy of the code from the exercise page as a feature request. :)
