### ISSUE TITLE
Side Exercises Available Before Completing Main Exercise

### ISSUE THREAD

**Issue by elrolfe** [exercism/exercism#5318]
Hello,

I've recently started the Rust track, and have noticed a couple of the side exercises were available before I completed the main exercise that is supposed to unlock them according to the Rust track's config.json file.  Specifically, Bob was available after I completed Reverse String, but there was no indication that a side project had been unlocked after completing Reverse String.  Bob did appear in the unlocked exercise notification under Gigasecond when I completed it though, alongside Matching Brackets and High Scores.

The same thing happened with the Saddle Points exercise.  It was available for me to solve after I completed Gigasecond, but according to the config.json it shouldn't be unlocked until after completing Clock, which I'm currently in progress on waiting for mentoring.  The other exercises unlocked by Clock (Dot-DSL, Simple Linked List, Pascal's Triangle, etc) have not yet unlocked.

**Comment by elrolfe** [comment]
Hi @iHiD,

No, I started the track in mentored mode.

If I recall correctly, the same thing happened a few times during the Java track, which I also did completely in mentored mode. I didn't have time back them to explore the maintainer side of things.

**Comment by iHiD** [comment]
When you submit the first iteration of a solution, it unlocks the first side-exercise to give you something to do while you wait for mentoring. I think that's the behaviour you're seeing here if I understand correctly? So you have the first `clock` unlock available (saddle-points) but not the others. So I don't think there's a bug - just a little bonus that we don't make explicit in the website :)

**Comment by elrolfe** [comment]
That's a nice little bonus.  I honestly don't recall if I looked at the side exercises before or after tackling the newly unlocked main exercise.  I'll pay more attention when Clock is approved to see what happens, and will update here if it has anything extra before submitting the next main exercise.

Thanks!

**Comment by iHiD** [comment]
Great. Thanks :)

**Comment by elrolfe** [comment]
It looks like that feature is what's happening.  I completed the Clock exercise, and it unlocked Anagram and the 33 side exercises that it was supposed to (including Saddle Points).  I submitted the Anagram solution, and that unlocked the Protein Translation side exercise which wasn't available before submitting Anagram.

Thanks for the explanation, and for looking into this. :)

**Comment by iHiD** [comment]
Brilliant. Thanks for reporting and checking it. I'd totally forgotten about the feature tbh! :)
