### ISSUE TITLE
Exercism Submit suddenly broken - could be issue with Github

### ISSUE THREAD

**Issue by NyxtheFallen** [exercism/exercism#5320]
Hey all,

You'll find my troubleshooting info below. First, a description. Running `exercism submit scrabble-score.go` is not working. I have tried the following variations:

```
me@pop-os:~/exercism/go/scrabble-score/$ exercism submit scrabble-score.go
me@pop-os:~/exercism/go/scrabble-score/$ exercism submit /exercism/go/scrabble-score/scrabble-score.go
me@pop-os:~/exercism$ exercism submit ./go/scrabble-score/scrabble-score.go
```

I receive the error every time:

```
Error: 

    The file you are trying to submit cannot be found.

        /home/myname/exercism/go/scrabble-score/scrabble-score.go
```

I'm guessing it may have something to do with Github messing with some hidden exercism file? As you can see on my profile, I keep all of my exercism exercises in a repo--I don't have a gitignore set up, so it's possible there's some synchronization issue?

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/elliottjohnson
Workspace: /home/elliottjohnson/exercism
Config:    /home/elliottjohnson/.config/exercism
API key:   d3df*****************************895

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 52.530647ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 1.020865135s


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

**Comment by NyxtheFallen** [comment]
Hey all,

After around 15 minutes of playing around, I committed everything to my branch again and pulled it to master. after deleting the branch and switching back to master, `exercism submit scrabble_score.go` worked correctly. (Also, in my comment above, I notice I misspelled scrabble_score.go--however, even with the correct spelling, the same issue was occurring.)

As my issue is fixed, I'm closing this issue, but if you need any further information to help improve your services, I'm more than happy to help.

**Comment by iHiD** [comment]
@NyxtheFallen Thanks for closing when you solved it. That command is just locally saying it can't find the file you specify. It errors in that way before it hits our servers, so I think it's purely some sort of issue where the file you wanted to submit didn't exist at the time you wanted to submit it - maybe as you said to do with your Git setup etc.
