### ISSUE TITLE
C# ERROR MSB4025: Project file could not be loaded. Data at the root level is invalid.

### ISSUE THREAD

**Issue by danyroza** [exercism/exercism#5323]
When I try to run tests for my C# code with `dotnet test HelloWorldTests.cs` command in CMD, this error message appears: 

**(my directory)\Exercism\csharp\hello-world\HelloWorldTests.cs(1,1): error MSB4025: Project file could not be loaded. Data at the root level is invalid. Line 1, position 1.**

Any suggestions? I saw some fixes online, but of course, there is no project file provided (nor needed) for exercism testing.

**Comment by iHiD** [comment]
(cc @exercism/csharp)

**Comment by ErikSchierboom** [comment]
> I saw some fixes online, but of course, there is no project file provided (nor needed) for exercism testing.

Well, there should be a project file in your directory (`HelloWord.csproj`). Did you follow the [installation instructions](https://exercism.io/tracks/csharp/installation)? It might be that you don't have the right .NET Core version installed.

**Comment by ErikSchierboom** [comment]
Could you do `dotnet test` in the directory instead of specifying the test file (which I don't think is supported).

**Comment by danyroza** [comment]
> > I saw some fixes online, but of course, there is no project file provided (nor needed) for exercism testing.
> 
> Well, there should be a project file in your directory (`HelloWord.csproj`). Did you follow the [installation instructions](https://exercism.io/tracks/csharp/installation)? It might be that you don't have the right .NET Core version installed.

Yes, there is the project file, I just missed it. 

Then I tried the newest .NET Core installation and even .NET Core SDK, but does not seem to fix the error. I've always run the `dotnet test` command in the directory containing the .cs files.

You can check a screenshot of a console [HERE](https://imgur.com/a/Vk2Hys9) which should provide you with valuable information.

**Comment by ErikSchierboom** [comment]
>  I've always run the dotnet test command in the directory containing the .cs files.

But according to the screenshot, you are not running it the right way. You are doing `dotnet test HelloWorldTests.cs`, but you should do just `dotnet test` (see [the documentation](https://exercism.io/tracks/csharp/tests) for more information).

**Comment by danyroza** [comment]
> > I've always run the dotnet test command in the directory containing the .cs files.
> 
> But according to the screenshot, you are not running it the right way. You are doing `dotnet test HelloWorldTests.cs`, but you should do just `dotnet test` (see [the documentation](https://exercism.io/tracks/csharp/tests) for more information).

Oh my... That was such a stupid mistake. Probably came as bad habit from python course, where you run `pytest *filename*`.

**Thank you so much for your time!**

**Comment by ErikSchierboom** [comment]
No worries! Enjoy the track.
