### ISSUE TITLE
Ruby track - No movement in queue status

### ISSUE THREAD

**Issue by ketigid** [exercism/exercism#5324]
Hi, it has been 3 weeks since submitting a solution, and the following queue status message had remained the same.

```
There are currently 18 solutions ahead of this in the Ruby queue, and 0 ahead in the High Scores queue. The median waiting time for mentoring on this exercise is 1 day.
```

Wondering if it was some system issue?

Thanks for helping.

**Comment by kotp** [comment]
I picked it up, it doesn't appear to be a systems problem, just a mentor time problem.
