### ISSUE TITLE
Need some Devops advice for the Pharo-Smalltalk track, possibly for a build output repo

### ISSUE THREAD

**Issue by samWson** [exercism/exercism#5328]
I'm looking for some high level advice on what might be possible. It's to help make maintaining the [pharo-smalltalk](https://github.com/exercism/pharo-smalltalk) track less complex.

### Background
In the Pharo language all programming is done in the IDE and the source code is a part of the IDE image file, essentially serialized objects and their state. Nothing exists as plain text files. 

The exercism website requires plain text files for the language track pages. We have our own code in the IDE that generates the plain text from the source code in the image.

The [source code](https://github.com/exercism/pharo-smalltalk/tree/master/dev/src) that a maintainer works on in the IDE exists in the same repo as the [exercise files](https://github.com/exercism/pharo-smalltalk/tree/master/exercises) for the website.

### The Problem

Having the image source code and the website files exist in the same repository can be confusing. They are almost duplicated files with slight differences. Generating the website files requires a fork of the repository on a maintainers computer that they then have to check in manually the normal way with Git. This is a lot of extra cognitive overhead that takes the maintainer out of the normal Pharo development workflow.

This extra complexity will make it harder for new contributors to effectively contribute and it's extra overhead even for experienced maintainers.

### A Proposed Solution

Development of the exercises takes place in the IDE. The files for the exercism website are much like the output of any compilation process.

What I want to try is to have one Git repository for the development source code for the maintainers. A second repository will exist to hold only the files needed by the exercism website. In normal operations the second repository only gets updated by automated processes.

Here is a guess at what it looks like:
1. Maintainer develops exercises in the Pharo IDE and commits them to the dev repository
2. An automated process (Travis?) picks up changes from the dev repository master
3. The automated process compiles the code for the website
4. The website code is committed to a separate repository

Generating the website code isn't difficult since we can already do it. If we use Travis for example it would build a Pharo image, start the VM, and load the code from the dev repo. The image can then be given the command to generate the code.

### Where I Need Help

The part I don't know how or if it is possible is the second repository. Having a Travis build or something else automatically make commits to a separate GitHub repo.

Let me know if you have anymore questions.

**Comment by iHiD** [comment]
Hello. Thanks for the ideas. I have two thoughts. 

Firstly, regarding the devops, we should be able to do that pretty easily using GitHub Actions. (cc @ErikSchierboom, @sleeplessbyte, @saschamann as our resident experts on GHA).

---

Secondly, I'd like to just check that splitting this into two repos is the sane thing to do though. It feels like it might be easier if the compilation step was just to compile things to the correct folder within this repo, rather than create a whole extra repo.

> Having the image source code and the website files exist in the same repository can be confusing. They are almost duplicated files with slight differences. Generating the website files requires a fork of the repository on a maintainers computer that they then have to check in manually the normal way with Git. This is a lot of extra cognitive overhead that takes the maintainer out of the normal Pharo development workflow.

I'm not sure how this solution avoids the problem of a fork on a maintainer's computer. Surely they'll still need that to be able to work on the exercises within the IDE and submit a Pull Request? 

It feels to me at first reading/thinking that the hard bit is the compilation step and that we could just automate that via GHA, rather than the fact it's all in one repo. But happy to be told I'm entirely wrong :)

**Comment by SaschaMann** [comment]
> Secondly, I'd like to just check that splitting this into two repos is the sane thing to do though. It feels like it might be easier if the compilation step was just to compile things to the correct folder within this repo, rather than create a whole extra repo.

It might be easier to change the default branch on GitHub to something like `develop` and have a GHA or Travis script push the build output that the website requires to master. Similar to the way `gh-pages` branches work.

> The part I don't know how or if it is possible is the second repository. Having a Travis build or something else automatically make commits to a separate GitHub repo.

That would be possible. You'd have to configure a deploy key for the output repo and add it as secret in the travis config file. Then use CLI git and SSH to push to the 2nd repo. I think having it in one repo but "hidden" is easier, though.

**Comment by samWson** [comment]
> I'm not sure how this solution avoids the problem of a fork on a maintainer's computer. Surely they'll still need that to be able to work on the exercises within the IDE and submit a Pull Request?

@iHiD you have a good point there. I think there are two broad options when it comes to the Pharo IDE and git integration. The first is to do it entirely in the IDE: you set the remote Github repo as your origin and handle all git operations in the IDE. No extra source code exists on the computer. The second is to use git like you would any other language and have the repository on your computer file system. You point the IDE to the repo on your computer. You then use git normally outside the IDE for commits, branching, etc. Personally this is how I've always done it as git is (in my opinion) better than the IDE for this purpose. So your right in that this doesn't avoid having a forked repo on the maintainers computer.

> It feels to me at first reading/thinking that the hard bit is the compilation step and that we could just automate that via GHA, rather than the fact it's all in one repo. But happy to be told I'm entirely wrong :)

I like this idea. The compilation step is something manual that a maintainer must do before pushing changes. We have written our own custom code in the IDE for that purpose. If it is possible to just push only the Pharo source changes to Github, then a GHA handles the compilation process that would reduce the workload and it avoids an extra repo. 

The compilation step is not quite a 1 for 1 copy process. The Pharo IDE does not think in terms of file trees. The source code files are the same. The exercise solution would need to be placed in a `.meta` directory. The exercise README would need to be scraped from the test class comment. To give you an example [here](https://github.com/exercism/pharo-smalltalk/tree/master/dev/src/Exercise%40ReverseString) is an exercise as IDE source code and [here](https://github.com/exercism/pharo-smalltalk/tree/master/exercises/reverse-string) is the same exercise after it is compiled and ready for the exercism website.

> It might be easier to change the default branch on GitHub to something like develop and have a GHA or Travis script push the build output that the website requires to master. Similar to the way gh-pages branches work. Maintainers and contributors would never have to see the master branch. They'd open PRs against develop and the building happens in the background.

@SaschaMann This is my preferred option to explore. This would be dependent on a GHA doing the compilation job that we currently do in the IDE.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
