### ISSUE TITLE
Go through for CLI

### ISSUE THREAD

**Issue by nash981** [exercism/exercism#5329]
Greeting. 
The CLI is kind of a bit difficult to understand. I would really appreciate a walk thorough video for the same for Linux, Windows and macOS systems, which covers,
1. How to install exercism
2. How to enable CLI
3. How to download the exercises 
4. How to submit the exercises
5. How to confirm the submissions

**Comment by iHiD** [comment]
Hello. Have you worked through https://exercism.io/cli-walkthrough ?

**Comment by nash981** [comment]
Yes sir. And I was able to install cli on Ubuntu. But I couldn't  understand how to use the installed exercise  click interface to download the exercise and  submit it. Am stuck here

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nash981** [comment]
________________________________

**Comment by iHiD** [comment]
So if you look on the website next to an exercise you should see something like the image below. You should be able to follow the instructions there?

<img width="451" alt="Screenshot 2020-07-07 at 23 50 40" src="https://user-images.githubusercontent.com/286476/86852476-bd3cae80-c0ac-11ea-80a5-ea0130144029.png">

**Comment by nash981** [comment]
Got it . Thanks a tonne.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iHiD** [comment]
No probs :) If you get stuck, feel free to open a new exercise!

And remember, Exercism relies on volunteers for everything, so now you're an expert on installing/using it, if you make a video and put it on YouTube lots of other people will benefit from it :)
