### ISSUE TITLE
Facing an issue submitting my first Python problem

### ISSUE THREAD

**Issue by NevilleMthw** [exercism/exercism#5330]
Hi, I am a Linux user and I'm finding it difficult to submit my solution through the command line. I followed the instructions and put the two Python file solutions in the exercism folder of Python, then I tried to run the submit command but I keep getting errors, mainly saying that the file cannot be found in the path file. 

Any help will be appreciated since this is the first time I am using your website.

**Comment by iHiD** [comment]
Hello. What exactly do you mean by "I followed the instructions and put the two Python file solutions in the exercism folder of Python"?

**Comment by NevilleMthw** [comment]
These instructions:
```
Note that, when trying to submit an exercise, make sure the solution is in the $EXERCISM_WORKSPACE/python/hello-world directory.

You can find your Exercism workspace by running exercism debug and looking for the line that starts with Workspace.
```

**Comment by angellyna1088** [comment]
Vào Th 5, 9 thg 7, 2020 lúc 21:26 Neville Mathew <notifications@github.com>
đã viết:

**Comment by nash981** [comment]
so there is a specific directory for exercism exercises which is usually located in snap folder of you user.
use the terminal to go to the exercism-python folder and save your python file in that location.  copy the filepath between ':' and '$' .
then enter command as follows exercism submit  thefilepath/filename.py
hope this helps

**Comment by NobbZ** [comment]
@NevilleMthw can you please explain how exactly you have retrieved the exercises files? Usually it is done by using `exercism download` command, it will create all necessary folders for you, as well as some required metadata.

Also please tell us what command you are using to submit your solution, in what folder you are when you enter that command (`pwd`), what the content of that folder is (`ls`). Also please tell us the exact output of the submit command.

**Comment by NevilleMthw** [comment]
> so there is a specific directory for exercism exercises which is usually located in snap folder of you user.
> use the terminal to go to the exercism-python folder and save your python file in that location. copy the filepath between ':' and '$' .
> then enter command as follows exercism submit thefilepath/filename.py
> hope this helps

Yes this helped. Thanks a lot. It was kinda confusing for me to understand since there was no tutorial shown on how to do it.

**Comment by NevilleMthw** [comment]
> @NevilleMthw can you please explain how exactly you have retrieved the exercises files? Usually it is done by using `exercism download` command, it will create all necessary folders for you, as well as some required metadata.
> 
> Also please tell us what command you are using to submit your solution, in what folder you are when you enter that command (`pwd`), what the content of that folder is (`ls`). Also please tell us the exact output of the submit command.

Already got it. Thank you for your help!
