### ISSUE TITLE
Download Files Not Appearing In File Explorer

### ISSUE THREAD

**Issue by mitchelln11** [exercism/exercism#5331]
I just started using this today (07/10/2020). I installed the CLI. It's still making me use the regular cmd tool. Is that correct? If so, when I paste in the download and hit enter, the results display a:

Downloaded to
C:\path-name-here

When I go there, no folder is displayed for the new download

**Comment by iHiD** [comment]
Can you list exactly the commands you've run and leave your full paths in please.

**Comment by mitchelln11** [comment]
- Downloaded installer - Installation Complete! message returned
- Invoked the CLI from the command-line by calling exercism.exe:
C:\Users\mitch>exercism.exe

- Clicked finish on installer
- Changed directory to new Exercism folder
`cd C:\Exercism`

- CLI command run with token
`C:\Exercism>exercism configure --token={5 sets of letters and numbers-my token}`
- Message saying "You have configured the Exercism command-line client" - shows Config Dir, Token, Workspace, and API Base URL
`- Download --exercise=hello... run on terminal`
- Message saying "Downloaded to" -Shows file structure

When I go to that folder, it doesn't exist

**Comment by NobbZ** [comment]
Please tell us the exact output of `exercism download`, the *exact* command you used to download, the output of `exercism workspace`, and then please show us how you `cd` into the download location, exact command, as well as exact error.

Please copy and paste! If you can't because windows terminal doesn't make that easy, do screenshots.

PS: If there is a space in your workspace path, you might need to wrap the path in doublequotes when `cd`ing.

**Comment by mitchelln11** [comment]
![configured-cli-and-download-blurred-token](https://user-images.githubusercontent.com/17222791/87236967-aef4d800-c3b5-11ea-93d4-6aec44570168.jpg)

**Comment by NobbZ** [comment]
Your exercise should be in `C:\Users\mitch\Exercism\csharp\hello-world`, have you checked that folder?

`C:\Exercism` probably only contains your installed binaries (though that's a non-standard location), while your workspace is `C:\Users\mitch\Exercism`.

**Comment by mitchelln11** [comment]
You are right. I thought the mitch folder was the C drive for some reason
