### ISSUE TITLE
Cannot submit exercise.

### ISSUE THREAD

**Issue by rsonko98** [exercism/exercism#5338]
I completed the exercise and I cannot submit my solution. I tried both dragging the file to the terminal (which copies the path on a Mac as well as typing out the path manually and it says file not found.

**Comment by NobbZ** [comment]
Can you please show the full command you used with its full output, as well as the output of `exercism debug` and the output of `tree` from your exercises folder?

PS: If `tree` is not available on your system, then please show the output of `ls -l` your exercises folder and relevant subfolders.

**Comment by rsonko98** [comment]
<img width="387" alt="Screen Shot 2020-07-20 at 4 16 49 PM" src="https://user-images.githubusercontent.com/47840278/87982203-6d92b580-caa4-11ea-9a95-7435ba7c9928.png">

**Comment by rsonko98** [comment]
<img width="452" alt="Screen Shot 2020-07-20 at 4 19 46 PM" src="https://user-images.githubusercontent.com/47840278/87982471-d712c400-caa4-11ea-9115-b24b010ccea7.png">

**Comment by rsonko98** [comment]
<img width="794" alt="Screen Shot 2020-07-20 at 4 24 49 PM" src="https://user-images.githubusercontent.com/47840278/87982922-8a7bb880-caa5-11ea-8614-9f5b4cb980ca.png">

**Comment by rsonko98** [comment]
<img width="961" alt="Screen Shot 2020-07-20 at 4 25 20 PM" src="https://user-images.githubusercontent.com/47840278/87982956-9c5d5b80-caa5-11ea-9a19-fe147bd8f5ed.png">

**Comment by iHiD** [comment]
Your workspace should be set to `/Users/ramasonko/Documents/Exercism` - it's currently `/Users/ramasonko/Exercism`

**Comment by rsonko98** [comment]
Thank you, that worked! 

P.S. For those who may read this you change the workspace by typing: exercism configure -w "path/to/directory"
and don't use quotes by the way.
