### ISSUE TITLE
What is the diference between `/snap/exercism/5/exercism` and `exercism` command?

### ISSUE THREAD

**Issue by Alimektor** [exercism/exercism#5339]
I installed CLI using snap.

`$ sudo snap install exercism`

Then I tried:

`$ exercism configure -t=MY_TOKEN`

What I get:

`Error: open /home/alimektor/.config/exercism/user.json: permission denied`

Then I tried:

`$ exercism submit 1`

What I get:

```bash
Error: 

    Welcome to Exercism!

    To get started, you need to configure the tool with your API token.
    Find your token at

        https://exercism.io/my/settings

    Then run the configure command:

        /snap/exercism/5/exercism configure --token=YOUR_TOKEN
```

Pay attention to the last line: **`/snap/exercism/5/exercism configure --token=YOUR_TOKEN
`**

I can use `/snap/exercism/5/exercism` instead of just `exercism` command and it will be work nice and perfect, but I prefer shorter command.

My OS: Ubuntu 19.10 eoan

**Comment by NobbZ** [comment]
There shouldn't be any difference between either commands.

Theory is, that `exercism` is resolved through `PATH` resolution to a wrapper script in `/snap/bin` or something like that, and the symlink should point to `/snap/exercism/5/exercism`. (Thats at least how I understand it, I do not use `snap` myself)

In most of the cases this just seems to work, though for some people there is something that affects the environment of the "wrapped" binary in a bad way.

Could you please provide the output of `which exercism` and `env`? (Especially from the `ENV` output make sure to remove lines which might contain a secret)

I can't promise that the team can fix it, but at least I hope that knowing more about an environment where it fails might help to understand the problem, as the team wasn't able to reproduce the issue so far.

**Comment by watofundefined** [comment]
I had similar problems on Ubuntu 18.04 with Snap today, and it used to work before. My last submitted exercise was on 22nd May so it definitely worked back then.

For others experiencing the problem, here's a quick workaround: `ln -s /snap/exercism/5/exercism ~/.local/bin/exercism` (or wherever your local bin directory is).

Below might help you in tracking down the problem.

**Before creating the symlink:**

`~/.config/exercism/user.json`:
```json
{
  "apibaseurl": "https://api.exercism.io/v1",
  "token": "242f*****************************6d9",
  "workspace": "/home/watofundefined/src/exercism"
}
```

```sh
which exercism # ~> /snap/bin/exercism
```

Result of `exercism troubleshoot` -  notice the `Configuration` section - no API key and wrong workspace:
```
#
# Troubleshooting Information
# ===========================
# 
# Version
# ----------------
# Current: 3.0.13
# Latest:  3.0.13
# 
# 
# Operating System
# ----------------
# OS:           linux
# Architecture: amd64
# 
# 
# Configuration
# ----------------
# Home:      /home/watofundefined/snap/exercism/5
# Workspace: /home/watofundefined/snap/exercism/5/exercism (default)
# Config:    /home/watofundefined/.config/exercism
# API key:   <not configured>
# Find your API key at https://exercism.io/my/settings
# 
# API Reachability
# ----------------
# 
# GitHub:
#     * https://api.github.com
#     * [connected]
#     * 46.174016ms
# 
# Exercism:
#     * https://api.exercism.io/v1/ping
#     * [connected]
#     * 452.488078ms
```

**After creating the symlink:**

```sh
# Configuration
# ----------------
# Home:      /home/watofundefined
# Workspace: /home/watofundefined/src/exercism
# Config:    /home/watofundefined/.config/exercism
# API key:   242f*****************************6d9
```

And  `env`:

```
XDG_SEAT=seat0
XDG_SESSION_ID=1
WINDOWPATH=1
LC_IDENTIFICATION=en_US.UTF-8
DISPLAY=:0
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
COLORTERM=truecolor
GNOME_TERMINAL_SERVICE=:1.74
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
LOGNAME=watofundefined
TEXTDOMAIN=im-config
VISUAL=emacsclient -c -a emacs
LC_TIME=en_US.UTF-8
SHELL=/usr/bin/zsh
PAPERSIZE=letter
PATH=/home/watofundefined/.cargo/bin:/home/watofundefined/.deno/bin:/home/watofundefined/lib/apache-maven-3.6.3/bin:/usr/local/bin:/home/linuxbrew/.linuxbrew/bin:/home/watofundefined/bin:/home/watofundefined/.emacs.d/bin:/home/watofundefined/.local/bin:/home/watofundefined/.cargo/bin:/home/watofundefined/.local/bin:/home/watofundefined/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/home/watofundefined/bin:/home/watofundefined/.emacs.d/bin:/home/watofundefined/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
IM_CONFIG_PHASE=2
TEXTDOMAINDIR=/usr/share/locale/
CLUTTER_IM_MODULE=xim
QT4_IM_MODULE=xim
XMODIFIERS=@im=ibus
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_MENU_PREFIX=gnome-
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_SESSION_DESKTOP=ubuntu
GDMSESSION=ubuntu
QT_IM_MODULE=ibus
LC_ADDRESS=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
GNOME_SHELL_SESSION_MODE=ubuntu
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
LIBVIRT_DEFAULT_URI=qemu:///system
USERNAME=watofundefined
XDG_RUNTIME_DIR=/run/user/1000
DESKTOP_SESSION=ubuntu
GTK_IM_MODULE=ibus
USER=watofundefined
GTK_MODULES=gail:atk-bridge
PWD=/home/watofundefined/src/exercism/clojure
VTE_VERSION=5202
LC_MONETARY=en_US.UTF-8
HOME=/home/watofundefined
QT_ACCESSIBILITY=1
SSH_AGENT_PID=1745
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
LANG=en_US.UTF-8
LC_NAME=en_US.UTF-8
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/ceb59c2e_2292_470b_a269_69566edc79b5
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
SHLVL=1
GJS_DEBUG_OUTPUT=stderr
XDG_VTNR=1
EDITOR=emacsclient -c -a emacs
TERM=xterm-256color
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_CURRENT_DESKTOP=ubuntu:GNOME
XDG_SESSION_TYPE=x11
SESSION_MANAGER=local/o:@/tmp/.ICE-unix/1667,unix/o:/tmp/.ICE-unix/1667
LC_TELEPHONE=en_US.UTF-8
OLDPWD=/home/watofundefined
DENO_INSTALL=/home/watofundefined/.deno
JAVA_HOME=/usr/lib/jvm/jdk1.8.0_251
XDG_DATA_HOME=/home/watofundefined/.local/share
XDG_CONFIG_HOME=/home/watofundefined/.config
FZF_DEFAULT_COMMAND=rg --files
ZSH=/home/watofundefined/.oh-my-zsh
PAGER=less
LESS=-R
_=/usr/bin/env
```

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
