### ISSUE TITLE
How can I use gdb to debug code in c track?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [exercism/exercism#5345]
I'm new to c and I can only run gdb when there is an executable. In the current Exercism's C track, how can I use GDB to debug it?

**Comment by iHiD** [comment]
(cc @exercism/c)

**Comment by patricksjackson** [comment]
The `tests.out` file that is generated when you run `make test` is the executable.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
To debug the code with gdb, I have to compile the source code with the `-g` option, like `gcc -g main.c`. How to make `make test` compile the code with `-g`?

**Comment by patricksjackson** [comment]
`make test` [already has that option enabled](https://github.com/exercism/c/blob/110a8ed59f45920afc01be25938ecf657402b378/exercises/hello-world/makefile#L8),  so you shouldn't need to do anything special :)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thank you!
