### ISSUE TITLE
Can't understand the example of  live experiment Golang part

### ISSUE THREAD

**Issue by sansx** [exercism/exercism#5347]
Hi, I'm doing the live experiment in https://research.exercism.io/user_experiments/1/languages/go, but there is an example confused me `Describe(52) // Returns: "2 score or 3 dozen or 52"`, if 20 is a "score" and 12 is a "dozen", why 52 is 3 dozen, not 4 dozen. 
![](https://tva1.sinaimg.cn/large/007S8ZIlly1gh8qiz08tyj30ox0dnabn.jpg)

**Comment by charlie1404** [comment]
+1

**Comment by sansx** [comment]
@charlie1404  obviously that result  is wrong, Describe(52) should return  just `52`, guess maybe it's part of the experiment, LOL

**Comment by charlie1404** [comment]
@sansx I just happen to drop the idea of trying it any further 🤣 .

**Comment by iHiD** [comment]
@charlie1404 @sansx This is actually fixed, but you're probably locked onto old versions of the solution. Sorry. If you'd like me to update you to the latest version, let me know.

**Comment by sansx** [comment]
@iHiD thanks for your reply, good to know that problem is fixed. I had finished all parts of the experiment, so to me, the update is not necessary. @charlie1404 the other parts are fine and worth to have a try :), by the way, I'm looking for an exercise about how to make a complete project, it is hard to make a complete program without proper guidance.

**Comment by charlie1404** [comment]
@sansx thanks for the feedback i will give it a go again
