### ISSUE TITLE
Embed docs in mentor comments

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5351]
It would be nice if one could embed either links to docs or docstrings in mentoring comments. The format and method to retrieve it differs between languages, so it would likely require some language-specific infrastructure similar to test runners.

**Example:**

Comment: 
> You can leave out the `map` in L5. `sum` has a method `sum(f, itr)` that will apply the function `f` on each element of `itr` and then sum them.

I would like to be able to do something like `?sum` that will print the docs associated with `sum`, so that the comment would look like this:

---

Source:
```markdown
You can leave out the `map` in L5. `sum` has a method `sum(f, itr)` that will apply the function `f` on each element of `itr` and then sum them: 
?sum(f, itr)
```

---

Rendered:

You can leave out the `map` in L5. `sum` has a method `sum(f, itr)` that will apply the function `f` on each element of `itr` and then sum them: 

<details>
  <summary>Documentation of `sum(f, itr)`</summary>
```julia
help?> sum(f, itr)
  sum(f, itr)


  Sum the results of calling function f on each element of itr.

  The return type is Int for signed integers of less than system word size, and UInt for unsigned integers of less
  than system word size. For all other arguments, a common return type is found to which all arguments are promoted.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> sum(abs2, [2; 3; 4])
  29


  Note the important difference between sum(A) and reduce(+, A) for arrays with small integer eltype:

  julia> sum(Int8[100, 28])
  128

  julia> reduce(+, Int8[100, 28])
  -128


  In the former case, the integers are widened to system word size and therefore the result is 128. In the latter
  case, no such widening happens and integer overflow results in -128.

</details>

**Comment by SaschaMann** [comment]
This could potentially be generalised to arbitrary shortcuts configured in the docs-runner.

**Comment by SaschaMann** [comment]
Instead of having an on-demand "runner", it may also make sense to have an always-on web service. That saves the startup time etc.  no user code has to be run, we don't need sandboxing anyway.

**Comment by taiyab** [comment]
@SaschaMann 

A few questions just to help my understanding.

I'm actually not familiar with all the docs that might be available for a particular track, so are we talking about basically searching through (as an example): https://github.com/exercism/v3/tree/master/languages/julia for all the docs related to `sum(f, itr)`?

Would these only be things located in `/docs`?

**Comment by iHiD** [comment]
@taiyab These would be the Julia language docs, not Exercism docs. We're not going to be doing this for v3, but at some point in the future it might be nice. But it would be a lot (like a week plus) of work to do.

**Comment by SaschaMann** [comment]
What Jeremy said.

But your suggestion on slack of embedding concept docs is similar and likely a lot easier to add.

**Comment by taiyab** [comment]
Ah, cool. Makes sense. Yea, another one for the "at some point" backlog :D

**Comment by iHiD** [comment]
I really like the idea btw.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by SaschaMann** [comment]
AFAICT this is still relevant and should be reopened.
