### ISSUE TITLE
`gradle test` fails for Java/Anagram because of strange chars in the test file

### ISSUE THREAD

**Issue by casca** [exercism/exercism#5353]
I'm running

- Windows 10,
- Amazon Corretto JDK 11.0.7_10
- Gradle 6.5.1

I reproduce the issue by doing:
1. `exercism download --exercise=anagram --track=java`
1. `cd ~/personal/code/exercism-solutions/java/anagram/` (my Exercism workspace folder)
1. `gradle test`

```bash
✓ 10:16 anagram (master) $ gradle test

> Task :compileTestJava FAILED
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:28: error: illegal character: '\u2039'
            .containsExactlyInAnyOrder​("maters", "stream");
                                        ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:28: error: not a statement
            .containsExactlyInAnyOrder​("maters", "stream");
            ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:47: error: illegal character: '\u2039'
            .containsExactlyInAnyOrder​("inlets");
                                        ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:47: error: not a statement
            .containsExactlyInAnyOrder​("inlets");
            ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:63: error: illegal character: '\u2039'
            .containsExactlyInAnyOrder​("gallery", "regally", "largely");
                                        ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:63: error: not a statement
            .containsExactlyInAnyOrder​("gallery", "regally", "largely");
            ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:72: error: illegal character: '\u2039'
            .containsExactlyInAnyOrder​("Eons", "ONES");
                                        ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:72: error: not a statement
            .containsExactlyInAnyOrder​("Eons", "ONES");
            ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:92: error: illegal character: '\u2039'
            .containsExactlyInAnyOrder​("Carthorse");
                                        ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:92: error: not a statement
            .containsExactlyInAnyOrder​("Carthorse");
            ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:103: error: illegal character: '\u2039'
            .containsExactlyInAnyOrder​("carthorse");
                                        ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:103: error: not a statement
            .containsExactlyInAnyOrder​("carthorse");
            ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:114: error: illegal character: '\u2039'
            .containsExactlyInAnyOrder​("Carthorse");
                                        ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:114: error: not a statement
            .containsExactlyInAnyOrder​("Carthorse");
            ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:150: error: illegal character: '\u2039'
            .containsExactlyInAnyOrder​("Silent");
                                        ^
C:\Users\casca\personal\code\exercism-solutions\java\anagram\src\test\java\AnagramTest.java:150: error: not a statement
            .containsExactlyInAnyOrder​("Silent");
            ^
16 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
2 actionable tasks: 2 executed
```

If I open the file with Notepad++, switch to ANSI encoding and show all symbols I see some extra characters:
![image](https://user-images.githubusercontent.com/8927157/89728034-2d32b180-da2a-11ea-960a-c5baa6543121.png)

I solved the issue by adding an environment variable
- name: `GRADLE_OPTS`
- value: `-Dfile.encoding=utf-8`

and restarting my command prompt ([source](https://stackoverflow.com/questions/21267234/show-utf-8-text-properly-in-gradle)).

Other Java exercises like `hamming` worked without this environment variable.

**Comment by iHiD** [comment]
(cc @exercism/java - Any ideas?)

**Comment by mirkoperillo** [comment]
Interesting, I haven't any ideas at the moment, I have to go deep.

@casca can you provide the output of the command `gradle -v` ?

**Comment by casca** [comment]
Sure.

```bash
✓ 09:21 / $ gradle -v

------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_261 (Oracle Corporation 25.261-b12)
OS:           Windows 10 10.0 amd64
```

**Comment by mirkoperillo** [comment]
Hi @casca,
we'll try to fix the problem forcing Gradle to use UTF-8 for Java stuff compilation, thank you to @msomji

Can you provide a feedback if this PR fixes you problem ?
Thank you for helping us to improve the Java track

**Comment by casca** [comment]
It doesn't work. I get the same error as soon as I unset the `GRADLE_OPTS` env variable, clean the `build` folder and run `gradle test`.

I see that @msomji fixed a  `build.gradle` file common to all Java exercises, however I don't see the same change in the `build.gradle` file inside the `anagram` folder even if I download the exercise again.

I also tried upgrading the `exercism cli` but I'm already using the latest version.

**Comment by msomji** [comment]
Yes, I anticipated that would not have fixed the issue since I saw the same, no changes in the build.gradle. Will create another PR shortly and add the utf8 encoding the all build.gradle files. Stay tuned.

**Comment by JohnTheBastard** [comment]
I'm getting 8 instances of the following error when trying to run Anagram in Eclipse on Mac OS Catalina. (I deleted the `@Ignores` from the test file.)

The method `containsExactlyInAnyOrder​(String, String, String)` is undefined for the type `ObjectArrayAssert<String>`. I can file a separate issue, but it seemed likely related to changes made here.

**Comment by mirkoperillo** [comment]
@JohnTheBastard are you saying that the last PR ( so the putting of encoding settings into the main build.gradle) has broken something that worked previously ?

**Comment by JohnTheBastard** [comment]
I can't confirm that it worked previously because I hadn't started the Java track before the PR. However, as it exists now, I cannot get `AnagramTests.java` to compile without removing the `containsExactlyInAnyOrder` method from all tests.  

That is, if I change
```Java
@Test
public void testDetectLongerAnagram() {
    Anagram detector = new Anagram("listen");

    assertThat(detector.match(Arrays.asList("enlists", "google", "inlets", "banana")))
        .containsExactlyInAnyOrder("inlets");
}
```
to
```Java
@Test
public void testDetectLongerAnagram() {
    Anagram detector = new Anagram("listen");

    assertThat(detector.match(Arrays.asList("enlists", "google", "inlets", "banana")))
        .hasSize(1)
        .contains("inlets");
}
```
I can run without errors.

**Comment by casca** [comment]
@JohnTheBastard, you are probably experiencing this same issue.

I was getting 8 errors too (8 pairs of `error: not a statement` and `error: illegal character`) and all related to `containsExactlyInAnyOrder`. 

I bet Eclipse can't find the method because the method name contains extra characters.

**Comment by mirkoperillo** [comment]
@JohnTheBastard  thank you for the clarification,

We are working on it, for the moment I suggest to use the workaround found by @casca 

```
I solved the issue by adding an environment variable

    name: GRADLE_OPTS
    value: -Dfile.encoding=utf-8
```

**Comment by mirkoperillo** [comment]
Ok, we improved our fix and the UTF-8 encoding settings are now shipped in `build.gradle` of every exercise.

@casca @JohnTheBastard  can you confirm that now the issue is fixed ?
( Remember to force the update to the new exercise version from exercism.io exercise page)

**Comment by casca** [comment]
> Remember to force the update to the new exercise version from exercism.io exercise page

How to I force an update?

I don't see any option in my exercise page (maybe because I have already solved it?) and if I delete my local copy and re-download it using the exercism cli I get the old `build.gradle` file.

**Comment by mirkoperillo** [comment]
@msomji any suggestion ?
( I have the same problem )

**Comment by JohnTheBastard** [comment]
> How to I force an update?

Same question.

**Comment by NobbZ** [comment]
On the website for the exercise, there should be a box telling you that upstream has updated and contain a link to click, though this will only appear when actual test-files have changed.

If just the build file changed, you can not force an upgrade up until the point that tests have changed.

**Comment by mirkoperillo** [comment]
@NobbZ is it sufficient to introduce a fake update to the test ? ( something like a space or a new line )

**Comment by NobbZ** [comment]
Whatever makes `git` happy to accept it as a change.

**Comment by casca** [comment]
What about bumping the test version?

https://github.com/exercism/java/blob/master/exercises/acronym/.meta/version

**Comment by mirkoperillo** [comment]
Anagram seems to be already to the last version ( v1.5.0 )

**Comment by mirkoperillo** [comment]
@NobbZ thank you, now I'm able to update to the last exercise version

@casca @JohnTheBastard  now going to anagram exercise page on exercism.io you can find the box to force update to the last version.

You have to:
1. Force it
2. Download exercise on your pc `exercism download --exercise=anagram --track=java`

You should found new settings in build.gradle of the exercise and they resolve the econding problem

**Comment by NobbZ** [comment]
> What about bumping the test version?

No. A file matching the configured test-pattern has to be changed.

**Comment by casca** [comment]
The latest exercise version works fine for me.

I'll wait for feedback from @JohnTheBastard and then close this issue.

Thank you, everybody.

**Comment by JohnTheBastard** [comment]
I downloaded the new version and ran the test. I still get 8 instances of the following error:

java.lang.Error: Unresolved compilation problem: 
	The method `containsExactlyInAnyOrder​(String)` is undefined for the type `ListAssert<String>`

**Comment by mirkoperillo** [comment]
@JohnTheBastard  It seems an eclipse problem, probably it has the same problem with exercise encoding.
I think this is a different issue, feel free to open another one about.

@casca can we consider the issue closed ?

**Comment by casca** [comment]
@mirkoperillo, yes, closing it right now.
