### ISSUE TITLE
Run tests against old but popular community solutions

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5354]
It's frustrating if highly starred community solutions don't work anymore due to updated tests. However, _some_ may still work, and it would be good if one had a definitive way of finding out which ones work. Adding a label to all old solutions doesn't achieve this.

Rerunning tests against all published solutions is probably quite expensive. Two potential approaches to solve this problem:

- Add an on-demand "rerun tests" button for solutions that were published for a different test suite
- Automatically rerun tests against all popular (by some metric) solutions once the test suite is changed.

**Comment by SaschaMann** [comment]
In addition to this, it would be useful to be able to run a new test suite against solutions that previously passed the tests **before** merging the testsuite. Such a feature makes it easier to detect unintended breakage of valid solutions when introducing new test cases.

This would require some kind of (authenticated) API endpoint to download (a random set of) solutions in CI.

**Comment by iHiD** [comment]
I like both ideas

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by SaschaMann** [comment]
I think this is still relevant? Not 100% certain

**Comment by SaschaMann** [comment]
AFAICT this is still relevant and should be reopened.

**Comment by wischi-chr** [comment]
Maybe the first step could be to run tests against older solutions and show some sort of disclaimer or warning that a given solution no longer passes the test suite.

I'm currently learning on the rust track and it's sometimes confusing to see an answer that looks so elegant and simple, just to find out after going through the code that the solution doesn't handle three edge cases.

**Comment by SaschaMann** [comment]
See https://exercism-team.slack.com/archives/CARRG4MNC/p1638880191307700
