### ISSUE TITLE
Submitting scala solutions

### ISSUE THREAD

**Issue by kinga-k-farkas** [exercism/exercism#5365]
I am trying to submit a scala solution from the command line.  I am trying to follow the instructions, but it is not clear to me which file does the '/path/to/file' refer to.   
I tried 
sbt:hello-world> exercism submit src/main/scala/HelloWorld.scala 

but I got an error message:
[error] Expected ';'
[error] exercism submit src/main/scala/HelloWorld.scala
[error]

**Comment by NobbZ** [comment]
You need to run the `exercism` command from your shell, not the languages REPL.

**Comment by kinga-k-farkas** [comment]
Thank you!!!
