### ISSUE TITLE
Encoding text file rendered the code unreadable

### ISSUE THREAD

**Issue by skonce-of-Rivia** [exercism/exercism#5368]
Hi,

it's my first issue and I don't know if it's the right repository for that. 

So far I've been through the java track with my personnal computer which runs with Debian in English and Eclipse UTF-8. Today I've submitted an exercise from my work computer (Windows 10 in German, Eclpise UTF-8) and my file have been completely false encoded and I really don't know how to solve it or where I can change the settings to make it works.

It looks like this:

Êþº¾4mHandshakeCalculatorjava/lang/Object
handshakesLjava/util/List;	SignatureLjava/util/List<LSignal;>;representationAsBinary%Ljava/util/List<Ljava/lang/Integer;>;<init>()VCode
java/util/ArrayList

[here](https://exercism.io/my/solutions/16c0631de3fc41a593692cc369d34ef2)

I would be really thankful if someone can take a look on it or give me a hint.

**Comment by msomji** [comment]
Hi @skonce-of-Rivia, thanks for opening this issue, it appears that the solution link is private, so I can't view it currently.
Would you please provide the content of your local build.gradle file from your work computer.

**Comment by NobbZ** [comment]
Hi @skonce-of-Rivia!

I can see your "code" on the website, but can't download it.

But the existence of the phrase "`SourceFileHandshakeCalculator.java`" in the file makes me think that you have submitted your compiled `class` file rather than the source file.

**Comment by skonce-of-Rivia** [comment]
Thanks a lot @NobbZ ... I feel so tiny right now! Ahahahh

My bad I submited from bin/main (compiled class) folder and not src/main folder... Damn! And I was watching everywhere how to encode gradle and bla bla bla! 

Anyway thanks you both (@msomji )... For my first issue on internet I'm impressed about your sympathy and the time you took for me!

(BTW is there any possibility to delete our submited files? Because now I have like seven iterations and the 6 first are not relevant )

**Comment by iHiD** [comment]
There will be in v3.

**Comment by kotp** [comment]
You can make comments for each iteration that should be ignored (with a reason, if you want) and the mentor will get the message.
