### ISSUE TITLE
F# track still active?

### ISSUE THREAD

**Issue by cartsp** [exercism/exercism#5370]
It's been about a month now since I submitted my last solution but have not received any feedback.  I have tried being patient but its very hard to stay motivated for so long.  I did try commenting on my last solution a week ago in the hope it might flag to some mentor.  
I was wondering if the F# track is still active? I had previously been receiving feedback within a few days then it suddenly stopped.

**Comment by umbersar** [comment]
same here. No replies. thinking of changing track to practise mode from mentored.

**Comment by iHiD** [comment]
There's a lot of work going into v3 atm, with F# being a track in v3 that's getting lots of focus, so mentoring queues are backing up lots. Sorry.

**Comment by umbersar** [comment]
@iHiD Thanks for the update.
