### ISSUE TITLE
Javascript track - 'Bob' exercise - Community mentoring note incorrrect

### ISSUE THREAD

**Issue by nllerandi** [exercism/exercism#5371]
test('ending with whitespace') fails using the provided solution because `message.length` refers to the provided message, not the trimmed message, resulting in this function comparing ' ' (empty space) to '?'. 

`const isAsking = message => message.trim()[message.length - 1] === '?'`

should be...

`const isAsking = message => {
    message = message.trim()
    return message[message.length - 1] === '?'
  }
  // OR
  const isAsking = message => message.trim().endsWith("?")`

<img width="1017" alt="Screen Shot 2020-09-12 at 10 56 30 AM" src="https://user-images.githubusercontent.com/12804307/92998316-209cef80-f4e7-11ea-9813-cf5974af5b41.png">

**Comment by glennj** [comment]
I'd encourage your to fix it and submit a pull request. You'll find it under https://github.com/exercism/website-copy/tree/master/tracks

**Comment by nllerandi** [comment]
Submitted. https://github.com/exercism/website-copy/pull/1734
Thanks - will close issue.
