### ISSUE TITLE
no href in <a> tag for linux magazine at start page 

### ISSUE THREAD

**Issue by bubo-py** [exercism/exercism#5372]
There's no link provided in href of <a> tag of "linux magazine" icon at the start page of Exercism, thus it redirect to exercism.io

![image](https://user-images.githubusercontent.com/57272901/93330103-90301900-f81e-11ea-9f6e-6df4ab7bb87a.png)
![image](https://user-images.githubusercontent.com/57272901/93330174-adfd7e00-f81e-11ea-9335-de55c2ad2333.png)

**Comment by valdaarhun** [comment]
Hi. I see this issue hasn't been resolved yet. I would like to work on it.

**Comment by iHiD** [comment]
@valdaarhun Sure 🙂

**Comment by valdaarhun** [comment]
@iHiD I opened a new PR that resolves this issue in the `website` repository. However, the bot has labelled the PR as "invalid" and has closed it. I guess that's because it hasn't been pre-agreed as per the Contributing Guide. How do I resolve this?

**Comment by NobbZ** [comment]
Thats mostly a counter measure against spam PRs that came up during the first hours of the hacktoberfest.

We have notified @iHiD about the issue, and I am sure he will take care of it.
