### ISSUE TITLE
Allowing a mentor to resubscribe to a solution

### ISSUE THREAD

**Issue by bid0uille** [exercism/exercism#5375]
For now, I know three different ways for a solution to be unsubscribed by a mentor:
1) he clicked the "Skip this solution" button;
2) he clicked the "Leave conversation" button;
3) he was autoremoved because of too long inactivity (7 days for what I saw);
In each case, it makes the solution to go back to the shared queue.

From here, there is no way to "resubscribe" a solution, ie to make it back in the mentor own queue while removing it from shared queue. But.
1) He may want to unsubscribe because not being able to mentor it (not being mentored himself or not solved exercise), but that may change later while solution still having to be mentored.
2) He may want to leave conversation because of a planned absence, but the solution still having to be mentored when he's back.
3) He may have not seen the time pass about this solution, while being active on others, then still wanting to mentor it despite being autoremoved.
Furthermore, the solution may have been completed in the meantime, but even so, it still appears as unsubscribed. It shouldn't. And I feel like the "resubscribe" possibility would also solve that.

PS: I feel concerned about that since almost my beginning as a mentor, but I'm pretty sure the v3 will better handle that case, so I delayed about this issue. Now, I'm wondering if that's an easy change, and also to me it's related to another "issue" I'll raise next.

**Comment by iHiD** [comment]
Thanks 🙂 

As you say this will change quite a bit in v3 and as v2 is now frozen I won't be changing it. But it's really helpful to have the usecase written out and @taiyab and I will keep it as a reference. Thanks 🙂

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
