### ISSUE TITLE
Cannot install CLI on linux (snap)

### ISSUE THREAD

**Issue by einarpersson** [exercism/exercism#5380]
Hello. Trying to install exercism for the first time.

`sudo snap install exercism`
gives
`error: cannot communicate with server: Post http://localhost/v2/snaps/exercism: dial unix /run/snapd.socket: connect: no such file or directory`

Running Ubuntu 18.04.4 LTS (on WSL2 Win10)

Help?

**Comment by kotp** [comment]
It might be better to just grab the executable and place it in your path.  For Ubuntu, you can place it in your `~/bin` folder, and it will be added to your `$PATH`.

The instructions for doing so are [here](https://exercism.io/cli) and specifically the [GitHub](https://github.com/exercism/cli/releases/latest) link.

**Comment by einarpersson** [comment]
Thanks, got it working. But just out of curiosity, any ideas on why it didn't work with snap?

**Comment by NobbZ** [comment]
Snap isn't officially supported in WSL or WSL2.

Though it seems as if there are hacks available to make it work anyway:

https://discourse.ubuntu.com/t/using-snapd-in-wsl2/12113

Though I'd not suggest using it, instead try to use officially supported ways to get software running.

**Comment by kotp** [comment]
Closing, looks like you are up and running.
