### ISSUE TITLE
Unable to view queue after submitting new iteration

### ISSUE THREAD

**Issue by Shikogo** [exercism/exercism#5381]
I submitted a new iteration of the Hamming exercise on the python track. I had received feedback, but not approval, on my first iteration.
Now I only see the box to comment on my solution, but not my position in the queue. It is my understanding that new solutions get placed in the queue, and I would like to know my position in the queue.
Thank you.

**Comment by kotp** [comment]
I don't see "Shikogo" in the queue.  New solutions won't be put in the queue if there is a mentor that already has it under review.  No need to be re-queued because that is not the case, when a mentor has it under review.

Can you describe if this is the case?

**Comment by Shikogo** [comment]
Ah, a mentor does have it under review, I was under false assumptions about how it works, then. Thank you!

**Comment by kotp** [comment]
Thanks Shikogo.
