### ISSUE TITLE
Launch plan for version 3 of Exercism

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5383]
Hello 👋 

For the last 12 months we've been hard at work building a new version of Exercism. It aims to solve the problems I discussed in [4 ways that Exercism sucks](https://www.youtube.com/watch?v=5Cj1Dr9m3GM&ab_channel=Exercism).

The platform is a total rewrite and has loads of new features and content. We're **very** excited. 

For the first time we're starting to commit to some timescales for launch. The first major date is Halloween. On Oct 31st we're going to be putting live an early staging site to allow contributors to v3's content to start using and testing their new exercises and tooling. We'll then be iteratively adding new features over the rest of the year targeting feature-completeness at the end of December. We imagine that January will be a period of refinement and bug fixes, and hope to launch in either Feb or March 2021 (depending on just how many bugs there are to fix!). I'll keep this plan updated as things develop and change.

If you want to help with version 3 of Exercism, please check out the [v3 repository](https://github.com/exercism/v3#exercism---v3) for a feel of what needs to be done, and email erik@exercism.io to be added to our Slack room. For those of you already contributing - thank you 🙂  - we're really excited about getting all of your hard work in a state where you can see it asap.

Feel free to fire any questions on this issue. Thanks!

**Comment by iHiD** [comment]
Update on this. We're nearly there... 🙂 

We're expecting to launch a private beta during April for anyone who is a mentor or contributor, then hoping to launch publicly in May 🎉 

Note: At Exercism, we don't do deadlines - we instead focus on trying to make good decisions and causing 
people working on the project less stress - so this isn't fixed in stone - but it's realistic at this stage.

**Comment by scmbradley** [comment]
It is now May, and I, personally, would be interested to know whether the private beta launched on time and whether there are any updates on the v3 timeline.

Also, what will happen to current track progress on moving to v3? Will I have to start again? :)

**Comment by iHiD** [comment]
@scmbradley Some parts of now being tested, some parts are not quite ready for testing. I'm planning on putting a video together this weekend with a bit more of an update.

And no, all your progress will be carried over into v3 :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
