### ISSUE TITLE
Hacktoberfest 2020 - start here!

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5386]
Hello :wave:

Hacktoberfest 2020 is happening at the same time as we are making a big push towards the launch of v3. We would really love your help with getting us ready for v3 by adding new Concept Exercises. However, these take time to make and review. **The minimum time requirement to put a Concept Exercise PR together is approximately 5 hours,** so if you want to contribute to Exercism this year, you need to be prepared to commit that time. However, your contribution will be significant, meaningful, and help tens of thousands of people - so hopefully it's a worthwhile investment 🙂

Because our maintainers are so busy **we are not able this year to spend the time reviewing and merging unsolicited Pull Requests.** 

**If you would like to invest a few hours in helping us,** please take a read of the [v3 README](https://github.com/exercism/v3#exercism---v3), and take a look at the issues for the languages you know, and if you find something you want to work on, email erik@exercism.io with a link to the issue you want to work on, and he will add you to our Slack room where you can ask any questions etc.

Thank you for wanting to help Exercism - we really appreciate it 💙

**Comment by NobbZ** [comment]
@iHiD, Hacktoberfest is now opt-in, can you please opt for the corresponding repositories and add the repo-tag?

**Comment by iHiD** [comment]
@NobbZ Thanks. I'm not setting anything as opted-in. If any maintainers would like theirs doing, please let me know.

**Comment by Stargator** [comment]
@iHiD The Dart Track would like to be opt-in. But we can always wait til next year.

@devkabiir has done a great job applying the hacktoberfest accepted tags to PRs during the month.

**Comment by iHiD** [comment]
Great. As Hacktoberfest is over, remind me next year! :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
