### ISSUE TITLE
failed MSpanList_Insert after installation

### ISSUE THREAD

**Issue by mjunolainen** [exercism/exercism#5388]
Hi, 
installed Exercism (macOS Catalina 10.15.7), but running into the following error when just trying to run "exercism version" command or configuring the CLI:

```plain
failed MSpanList_Insert 0x5b4000 0x7ea6f59e0674 0x0
fatal error: MSpanList_Insert
runtime stack:
runtime.throw(0x5366fb)
/usr/local/go/src/pkg/runtime/panic.c:520 +0x69
runtime.MSpanList_Insert(0x54f908, 0x5b4000)
/usr/local/go/src/pkg/runtime/mheap.c:618 +0x8a
MHeap_FreeLocked(0x54b900, 0x5b4000)
/usr/local/go/src/pkg/runtime/mheap.c:447 +0x1a6
MHeap_Grow(0x54b900, 0x10)
/usr/local/go/src/pkg/runtime/mheap.c:341 +0x1ae
MHeap_AllocLocked(0x54b900, 0x1, 0x2)
/usr/local/go/src/pkg/runtime/mheap.c:222 +0x379
runtime.MHeap_Alloc(0x54b900, 0x1, 0x10000000002)
/usr/local/go/src/pkg/runtime/mheap.c:178 +0x7b
MCentral_Grow(0x553d18)
/usr/local/go/src/pkg/runtime/mcentral.c:265 +0x89
runtime.MCentral_CacheSpan(0x553d18)
/usr/local/go/src/pkg/runtime/mcentral.c:84 +0x14b
runtime.MCache_Refill(0x5b0000, 0x2)
/usr/local/go/src/pkg/runtime/mcache.c:78 +0x119
runtime.mallocgc(0x10, 0x0, 0x10)
/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease530016500/go/src/pkg/runtime/malloc.goc:152 +0x30e
runtime.malloc(0x10)
/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease530016500/go/src/pkg/runtime/malloc.goc:264 +0x39
runtime.mallocinit()
/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease530016500/go/src/pkg/runtime/malloc.goc:575 +0x2a5
runtime.schedinit()
/usr/local/go/src/pkg/runtime/proc.c:150 +0x36
_rt0_go()
/usr/local/go/src/pkg/runtime/asm_amd64.s:91 +0x114
```

the installation was ok. Can't check the version because of the said error, but when I run the install command again I get:

```plain
Warning: exercism 3.0.13 is already installed and up-to-date
To reinstall 3.0.13, run brew reinstall exercism
```

The output of `file $(which exercism); uname -a` is as follows:

```plain
/opt/X11/bin/exercism: Mach-O 64-bit executable x86_64
Darwin MacBook-Pro-2.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

I'm completely new on this, so any help is appreciated! Thanks!

**Comment by iHiD** [comment]
@mjunolainen I have no idea, sorry. Hopefully someone in the community will have some wisdom.

**Comment by NobbZ** [comment]
I googled a bit, and it seems as if this error often occurs on MacOS, if the compiler used to compile the Go program is older than the MacOS version.

Sadly I do not know which Go compiler version is used to build the prebuilt binary, nor do I know how exactly brew works and if it compiles from source or uses a pre built binary.

@mjunolainen do you think you can clone https://github.com/exercism/cli and build it from source and try running that binary?

Alternatively, please try uninstalling `exercism` using brew and then do a fresh install of `exercism`. Repeating this installation procedure seems to have helped some in the internet with their similar error message.

**Comment by mjunolainen** [comment]
Thanks for the help!
As said I'm very new to this, but took the courage to dive into the deep underbelly of my computer and looks like after eventually installing Apache ant and some other bits and bobs I managed to get all up and running!

**Comment by iHiD** [comment]
Nice work! 🙂 

(Thanks @NobbZ))
