### ISSUE TITLE
Prolog Submit Issues

### ISSUE THREAD

**Issue by MONKEYFACEFRESH** [exercism/exercism#5389]
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\Elijah Senegar
Workspace: C:\Users\Elijah Senegar\Exercism
Config:    C:\Users\Elijah Senegar\AppData\Roaming\exercism
API key:   7252*****************************790

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 18.4154ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 846.2571ms

Hey guys, I just started learning Prolog and I seem to be having problems with submitting my exercises. I input the correct pathname and the exercism cli tells me "this solution can't be found". Any tips?

**Comment by NobbZ** [comment]
If you have used the absolute path, you might need to quote/escape the space in the username. If you did use a relative path, please show us more context. Like your current working dir, the terminal/shell used and the command used to submit.

**Comment by MONKEYFACEFRESH** [comment]
I'm using Command Prompt (comes with Windows)
My pwd when I'm trying to submit is C:\Users\Elijah Senegar\Exercism\prolog\hello-world
The command I'm using to submit is "C:\Users\Elijah Senegar\Exercism\prolog\hello-world\hello_world.pl"
I'm already using quotes to escape the space in my username. I'm learning other languages with Exercism, the prolog track is the only one I'm having trouble submitting with...

Elijah
________________________________

**Comment by NobbZ** [comment]
That is really weird, can you please show us the output of `dir` in the exercises folder?

**Comment by MONKEYFACEFRESH** [comment]
[Image.jpeg]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iHiD** [comment]
The image hasn't worked.

**Comment by MONKEYFACEFRESH** [comment]
What do you mean? You can’t see the picture I sent?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iHiD** [comment]
Correct. It's the text `[Image.jpeg]`

**Comment by MONKEYFACEFRESH** [comment]
Can you see it now?

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by iHiD** [comment]
Nope.

**Comment by MONKEYFACEFRESH** [comment]
Um that doesn’t make sense but ok. Anyway, when I try to submit from the exercise directory, it just says “Error: This solution could not be found”.  Not “the FILE can’t be found”. So I’m not sure what it means by “the solution”.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NobbZ** [comment]
Can you please show the output of `dir` from the exercises folder?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
