### ISSUE TITLE
Minesweeper exercise on Rust track seems stuck

### ISSUE THREAD

**Issue by PaulDance** [exercism/exercism#5390]
Hello all,

I have been following the Rust track and completed several exercises from it. Exercism is really great for its Mentored mode, so I intend to finish the track staying in it. However, I have submitted an iteration for the Minesweeper core exercise more than a month ago and haven't received any feedback since. It seems this exercise in particular receives less attention than others. Indeed, the submission page states that:

> There are currently 18 solutions ahead of this in the Rust queue, and 15 ahead in the Minesweeper queue. The median waiting time for mentoring on this exercise is about 1 month.

Further to a discussion with @NobbZ, I am opening this issue in order to bring this forward to a broader audience, as trying to contact the Rust mentors on their dedicated conversation did not yield any result since yesterday morning.

Hoping this could help other Rust students and myself get their solutions reviewed,
Thanks in advance,
Paul.

**Comment by iHiD** [comment]
Hi Paul,

Thanks for the message. I'll reach out again to mentors for you.

We'll struggling a little bit for Rust mentoring atm. I think 2020 has meant that many people are struggling personally and are able to dedicate less time to Exercism than they did before.

My hope is that launching v3 will remove some of the challenges and frustrations around this, but in the interim, I'll have to ask for your patience until someone replies.

If you don't get a reply in the next day or so, it may be best for you to change to Practice Mode if you want to continue for now, and then I can always move you back into Mentored Mode in the future if you message me.

**Comment by PaulDance** [comment]
I definitely understand your concerns, it is true that things may have not gone as initially planned... I am not in *that* much of a hurry, so I can surely wait a few more days before switching to Practice Mode. Thanks for your quick answer anyway!

**Comment by PaulDance** [comment]
coriolinus just reviewed and approved it! I'm closing this then.

**Comment by namin** [comment]
Hi,

The minesweeper exercise on Rust track seems to be stuck again.

The message for me is:
"There are currently 57 solutions ahead of this in the Rust queue, and 36 ahead in the Minesweeper queue. The median waiting time for mentoring on this exercise is about 1 month."

What's odd is that as I've been waiting, the queue has been _increasing_ rather than decreasing. There were 35 ahead at some point, and now 36.

Is there any hope? Or should I switch to practice mode?

Thank you.

**Comment by PaulDance** [comment]
Hi @namin!

Indeed, the queue for Minesweeper is mostly getting longer over time instead of shorter. There aren't many mentors regularly active on the Rust track. Minesweeper is an exercise some don't review submissions for. Although I mentor all exercises, I personally haven't been there for quite a bit of time now, which definitely contributed to the long queue.

I should have time next week to get into mentoring again, so I hope I'll get the queue down by a good amount.

**Comment by namin** [comment]
Thanks @PaulDance, much appreciated.
