### ISSUE TITLE
Javascript resistor color duo exercise unable to complete

### ISSUE THREAD

**Issue by xenobrain** [exercism/exercism#5394]
Hello, I submitted a solution to the Javascript track Resistor Color Duo exercise that was automatically accepted by the static analysis.  I am unable to complete the exercise.  My solution does not appear on the page even when I resubmit and I am unable to progress.

Clicking the link in the console window upon submission does not take me to the page.

**Comment by kotp** [comment]
On 20/10/11 06:30PM, Michael Liptrap wrote:
> Clicking the link in the console window upon submission does not take
> me to the page.

Can you share that link that was given in the console?

**Comment by xenobrain** [comment]
https://exercism.io/my/solutions/b7e248dd4a994bca9e09c1d0ba3a1c80

It brought me to the page this time, but when I click "choose next exercise" it still shows as in progress

**Comment by kotp** [comment]
Can you show a screenshot what you see?  The entire page?  Hopefully it
can help someone that has more direct access to help you out.

**Comment by xenobrain** [comment]
I don't know how useful a screenshot is going to be but here they are
First:
![Screenshot_20201012_103827](https://user-images.githubusercontent.com/1247848/95775442-4bf63400-0c77-11eb-95c2-e2dbcffd22c9.png)

Second:
![Screenshot_20201012_103902](https://user-images.githubusercontent.com/1247848/95775450-4f89bb00-0c77-11eb-95bc-f72b83377cab.png)

**Comment by iHiD** [comment]
@xenobrain You spotted this issue? Resistor Colour vs Resistor Colour Duo.

**Comment by kotp** [comment]
There you go, a TON of help. ;)  Thanks.

**Comment by xenobrain** [comment]
Yes I spotted it then closed the issue.  Look it was late at night (do I work on exercism projects late at night, yes I do!) didn’t see it then and was frustrated.  Sorry for the bother

**Comment by iHiD** [comment]
No probs. Thanks for confirming!
