### ISSUE TITLE
Moving from Travis to GitHub Actions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#5396]
Over the last few months we've been transferring all our CI from Travis to GitHub Actions (GHA). We've found that GHA are easier to work with, more reliable, and much much faster.

Based on our success with GHA and increasing intermittent failures on Travis, we have now decided to try and remove Travis from Exercism's org altogether and shift everything to GHA. 

For most CI checks this should be a transposing from Travis' syntax to GHA syntax, and hopefully quite straightforward (see this PR for an example).

**Comment by verdammelt** [comment]
@ErikSchierboom Is there a person or persons who I could tag as a reviewer on my github actions, specifically to check to see if my actions are built well for what they do? Never wrote them before and while they *work*, perhaps they could be better.

(Maybe we need a exercism github-actions track to teach me the concepts and approaches for github-actions? :) )

**Comment by iHiD** [comment]
@verdammelt: It exists: @exercism/github-actions 🙂

**Comment by ErikSchierboom** [comment]
Maybe a #ci channel in the Slack could also be useful? 🤔

**Comment by ErikSchierboom** [comment]
Thanks to @sleeplessbyte, we now have a really nice document and some starting workflows that tracks can use to quickly get started with Github Actions: https://github.com/exercism/problem-specifications/tree/master/workflows#workflow-templates

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
