### ISSUE TITLE
Anyone can get an access to a solution page for unopened tasks

### ISSUE THREAD

**Issue by ITheCorgi** [exercism/exercism#5398]
Using routes user can get an access to a solution page for each track. So, this link helps to get a solution: https://exercism.io/tracks/<language>/exercises/<track_name>/solutions.
I checked that user cannot open page of an unopened task, but can open a solution page for that task at the same time. I guess it`s inappropriate behavior.

**Comment by iHiD** [comment]
Hello. They can, yes. If people want to "cheat" that's totally their choice. As we're not giving out certificates or rewards, I don't think the behaviour hurts anyone. But thank you for letting us know :)
