### ISSUE TITLE
Class 'hamming_test' could not be found in '../hamming_test.php' when I run phpunit.phar

### ISSUE THREAD

**Issue by ivanhercaz** [exercism/exercism#5403]
Hi everyone,
First of all, thank you very much for Exercism! It is an awesome project. I am doing the PHP track and I having problems with the tests. I submitted the first exercise, "Hello, World!", without performing the tests because when I run them with `./phpunit.phar hello-world/hello-world_test.php` I get the next:

> Class 'hello-world_test' could not be found in '/home/ivanhercaz/exercism/php/hello-world/hello-world_test.php'.

I just change the code inside the function in `hello-world.php`, nothing more. After many tries I submitted the exercise and decided to try with "Hamming" exercise. I completed the code I think it should works for this case, and when I run `phpunit.phar` I get the same as in the "Hello, World!" exercise:

> Class 'hamming_test' could not be found in '/home/ivanhercaz//exercism/php/hamming/hamming_test.php'.

I don't know if it is the correct place to ask about it, if not tell me and close the issue, please. I will ask in the correct place.

**Comment by glennj** [comment]
what if you
```
cd hello-world
../phpunit.phar hello-world_test.php
```
?

**Comment by ivanhercaz** [comment]
Hi @glennj!

Thank you for your comment. I already tried it and it persists the same message about the class not found.

**Comment by glennj** [comment]
> Class 'hello-world_test' could not be found in '../exercism/php/hello-world/hello-world_test.php'.

Is that `..` real? or are you eliding the full path to your exercism directory? What is your output for `exercism configure`?

**Comment by ivanhercaz** [comment]
> Is that `..` real? or are you eliding the full path to your exercism directory?

No, I am eliding the full path to simplify. I will avoid it and clarify in the latest comments, excuse me.

> What is your output for `exercism troubleshoot`?

The output is:

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/ivanhercaz
Workspace: /home/ivanhercaz/exercism
Config:    /home/ivanhercaz/.config/exercism
API key:   ************************************

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 60.924923ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 298.774077ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

I hide completely the token in this message.

**Comment by glennj** [comment]
I cannot reproduce. Anyone on @exercism/php able to help out?

**Comment by ivanhercaz** [comment]
> I cannot reproduce. Anyone on @exercism/php able to help out?

It seems a bit strange. I hope someone of @exercism/php knows about it, because I am really interested in this track. Thank you for your help, @glennj!

**Comment by glennj** [comment]
While I was looking at this, I installed phputil via Composer. Have a look at the php track documentation, that unfortunately is not visible in practice mode? https://github.com/exercism/php/tree/master/docs

**Comment by MatheusNaldi** [comment]
I had the same problem, it didn't work using directly downloaded phpunit or global composer, so I tried to rename the test file and the class name to PascalCase and it worked!

e.g: file HammingTest.php and class HammingTest

**Comment by eamon0989** [comment]
I'm having the exact same problem. Didn't work with Hello World or not with Hamming. Here is my terminal output.

eamon@pop-os:~/snap/exercism/5/exercism/php/hamming$ ./phpunit.phar hamming_test.php
Class 'hamming_test' could not be found in '/home/eamon/snap/exercism/5/exercism/php/hamming/hamming_test.php'.
eamon@pop-os:~/snap/exercism/5/exercism/php/hamming$ ls
hamming.php  hamming_test.php  phpunit  phpunit.phar  README.md

**Comment by iHiD** [comment]
(cc @neenjaw)

**Comment by neenjaw** [comment]
@MatheusNaldi @eamon0989 

The v2 track only works natively with PHPunit 8, and with the renaming trick, it will then work with PHPUnit 9. 

The instructions will be updated for v3, but the website is in code freeze right now. 

Solution:

```shell
> cd ~/exercism/php

> curl -L https://phar.phpunit.de/PHPUnit.phar -o phpunit-8.phar

> chmod +x phpunit-8.phar

> ./phpunit-8.phar hello-world/hello-world_test.php
```

**Comment by eamon0989** [comment]
> @MatheusNaldi @eamon0989
> 
> The v2 track only works natively with PHPunit 8, and with the renaming trick, it will then work with PHPUnit 9.
> 
> The instructions will be updated for v3, but the website is in code freeze right now.
> 
> Solution:
> 
> ```shell
> > cd ~/exercism/php
> 
> > curl -L https://phar.phpunit.de/phpunit-8.phar -o phpunit-8.phar
> 
> > chmod +x phpunit-8.phar
> 
> > ./phpunit-8.phar hello-world/hello-world_test.php
> ```

Thanks for the reply! I tried that in installed phpunit-8.phar, and I renamed the test file HammingTest.php, unfortunately it still doesn't work, I got this error:

```
eamon@pop-os:~/snap/exercism/5/exercism$ ./phpunit-8.phar hamming/HammingTest.php
Cannot open file "hamming/HammingTest.php".
```

Matheus mentioned renaming a class also? But I couldn't find any class to rename, am I missing something?

**Comment by MatheusNaldi** [comment]
> > @MatheusNaldi @eamon0989
> > The v2 track only works natively with PHPunit 8, and with the renaming trick, it will then work with PHPUnit 9.
> > The instructions will be updated for v3, but the website is in code freeze right now.
> > Solution:
> > ```shell
> > > cd ~/exercism/php
> > 
> > > curl -L https://phar.phpunit.de/phpunit-8.phar -o phpunit-8.phar
> > 
> > > chmod +x phpunit-8.phar
> > 
> > > ./phpunit-8.phar hello-world/hello-world_test.php
> > ```
> 
> Thanks for the reply! I tried that in installed phpunit-8.phar, and I renamed the test file HammingTest.php, unfortunately it still doesn't work, I got this error:
> 
> ```
> eamon@pop-os:~/snap/exercism/5/exercism$ ./phpunit-8.phar hamming/HammingTest.php
> Cannot open file "hamming/HammingTest.php".
> ```
> 
> Matheus mentioned renaming a class also? But I couldn't find any class to rename, am I missing something?

@eamon0989 The class is inside test file, but using the solution of @neenjaw with phpunit 8 you won't need to rename it... I guess this error is occurring because you don't have read permission, I've tried to remove the read permission of the file and it appeared the same message, try chmod +r or sudo

**Comment by neenjaw** [comment]
If you haven't renaming the file it would be `./phpunit-8.phar hamming/hamming_test.php`
