### ISSUE TITLE
v2 website: why are links to Guides not shown in practice mode

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#5405]
While thinking about issue #5403 I joined the PHP track this morning. It's oversubscribed so I was shunted into practice mode.  How are newcomers supposed to get information about installation, running the tests, etc, when the links to the guides are not shown.

**Comment by iHiD** [comment]
They're shown on the RHS of each solution (see bottom right here)

<img width="1081" alt="Screenshot 2020-10-25 at 00 45 17" src="https://user-images.githubusercontent.com/286476/97095755-60650400-165b-11eb-9607-c303772a8809.png">

**Comment by glennj** [comment]
Ah, right. Thanks.
