### ISSUE TITLE
Can I use exercism in a classroom?

### ISSUE THREAD

**Issue by abailly** [exercism/exercism#5407]
I recently discovered exercism.io and I find it amazing. I am going to teach a Javascript class and given the circumstances (eg. general lockdown) having online-first resources would seem more than appropriate, so I am considering using exercism as a basis for students' exercises. 
My first question is simple: Am I allowed to do that or is there any licensing restriction? 
Second question is: How should I do that? Create a team and have students register as a team's member?
Thanks for the awesome job!

**Comment by iHiD** [comment]
> I recently discovered exercism.io and I find it amazing.

Thanks 💙 

---

> My first question is simple: Am I allowed to do that or is there any licensing restriction?

100% fine.

Second question is: How should I do that? Create a team and have students register as a team's member?

Yeah - create a team.

---

In v3, this will be changing a bit and becoming a nicer experience (with teams integrated more tightly into the website). But for now, the existing teams site should hopefully fit your needs.
