### ISSUE TITLE
Unable to Submit solution code to servers

### ISSUE THREAD

**Issue by AMOfficalGithub** [exercism/exercism#5408]
Hello everyone,

I am doing the beginning C# track of the exercises but I'm having some issues. When using **dotnet test** in the appropriate folder where Exercism downloads it says the following: 

```plain
C:\Users\missm\Exercism\csharp\hello-world>dotnet test
HelloWorld.cs(5,26): error CS0161: 'HelloWorld.Hello()': not all code paths return a value [C:\Users\missm\Exercism\csharp\hello-world\HelloWorld.csproj]
```

This is the following code with the HelloWorld.cs file 

```csharp
using System;

public static class HelloWorld
{
    public static void Main(String[] args)
    {
        Console.WriteLine("Hello, World!");
    }
}
```

What is being done wrong that it won't submit the file?

**Comment by NobbZ** [comment]
The test asks for a method `Hello()`, though you only provide a method `Main()`.

**Comment by AMOfficalGithub** [comment]
Hello, Thanks!

I've got it sorted out now. The instructions said that I needed to return a string and that was one of the reasons why it wasn't accepting Console.WriteLine even though that is valid code.

**Comment by iHiD** [comment]
Can this be closed? :)
