### ISSUE TITLE
Error: This URL was not recognised

### ISSUE THREAD

**Issue by roccminton** [exercism/exercism#5415]
A few month ago I worked happily with exercism. No after some break I wanted to comeback, but I cannot download exercises anymore. I get the following _"Error: This URL was not recognized"_
Also I get a similar error when I trie to configure for example the token (even though there is already a configure with the right token in it): _"Error: The base API URL 'https://api.exercism.io//ping' cannot be reached."_
And if I open the URL in a browser I only get an empty {}. Any Ideas? The strange thing is that the troubleshoot says that I am connected to exercism:

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           darwin
Architecture: amd64


Configuration
----------------
Home:      /Users/roccminton
Workspace: /Users/roccminton/Exercism
Config:    /Users/roccminton/.config/exercism
API key:   4bc7*****************************50d

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 37.385156ms

Exercism:
    * https://api.exercism.io//ping/ping
    * [connected]
    * 241.389952ms
```

Many thanks for any help in advance!

**Comment by iHiD** [comment]
Looks like you've set your base URL to `https://api.exercism.io//ping` or something.

If you run `exercism configure` what output do you get? (Please hash out the token before pasting)

**Comment by roccminton** [comment]
I get the same error as for the configrue --token: 
```Error: The base API URL 'https://api.exercism.io//ping' cannot be reached. 

API returned 401 Unauthorized```

What should the base URL be set to? Can I set it manually in the user.json file?

**Comment by iHiD** [comment]
You get that error just running `exercism configure`?

**Comment by iHiD** [comment]
Set it to `https://api.exercism.io/v1`

**Comment by roccminton** [comment]
Nice! That was it! You are a hero! Thank you very much!
