### ISSUE TITLE
TypeScript queue barely moving

### ISSUE THREAD

**Issue by nina-py** [exercism/exercism#5416]
I submitted a solution to the "Resistor Color Duo" exercise 9 days ago and was advised the following:

> There are currently 46 solutions ahead of this in the TypeScript queue, and 12 ahead in the Resistor Color Duo queue. The median waiting time for mentoring on this exercise is 1 day.

As of today, the information on the exercise page is as follows:

> There are currently 41 solutions ahead of this in the TypeScript queue, and 9 ahead in the Resistor Color Duo queue. The median waiting time for mentoring on this exercise is 2 days.

This is the second core exercise (not counting the "Hello World" one) and the first one was looked at within a day. Has there been a sudden influx of students onto this track? Exercism running some TV ads maybe? Mentors all busy at this time of year? Or just not enough mentors? 

I'd love to get reviews on at least the core exercises I complete - having any side exercises reviewed seems unlikely with such long queues for the core ones. At this rate the above mentioned exercise will finally be reviewed in about 10 weeks' time. It seems that with such long waits the most pragmatic approach is to submit my solution and then use the "Complete exercise (unapproved)" button to be able to see how others have solved this exercise and move forward.

**Comment by iHiD** [comment]
> Exercism running some TV ads maybe

I wish!

---

You should been presented with [this video](https://www.youtube.com/watch?v=XiV_vYn1Ea8) when you signed in recently, which explains the cause. Basically everyone is working on v3 of Exercism right now fixing [some of the problems](https://www.youtube.com/watch?v=5Cj1Dr9m3GM) that mean we have long queues in the first place.

I recommend switching to Practice Mode instead for now. Sorry.

**Comment by nina-py** [comment]
> You should been presented with this video when you signed in recently, which explains the cause. 

I haven't - it would be good if I did but all I see when I go to exercism.io is the tracks page with the tracks I have joined and then all the other available tracks. There is an announcement on top of the page about Exercism Research but that is all. 

> Basically everyone is working on v3 of Exercism right now fixing some of the problems that mean we have long queues in the first place.
> I recommend switching to Practice Mode instead for now. Sorry.

Perhaps a temporary solution would be to stop accepting people into the Mentored Mode? I was allowed to switch from Practice Mode to Mentored Mode on the JavaScript track earlier this month and it's as bad if not worse there:

> There are currently 111 solutions ahead of this in the JavaScript queue [...] The median waiting time for mentoring on this exercise is 16 days. 

I understand all this work - mentoring for v2 and building v3 - is not being done by fairies but ideally there should be a balance between maintaining the current project and building the brand new version. v3 may command the developers' attention for some months yet, and meanwhile newcomers to the site will be puzzled why they're accepted into Mentored Mode yet there are no barely any mentors around.

**Comment by nina-py** [comment]
@iHiD , apologies - I think I did get shown that one-minute video. Now that I've watched it, it feels familiar. It was published in April and mentions "slightly longer wait times" - perhaps they were back then, but definitely not now! Never mind that though - I'll see if I can contribute to v3 to speed things along :).

**Comment by iHiD** [comment]
> Perhaps a temporary solution would be to stop accepting people into the Mentored Mode? 

This automatically kicks in when a track's median response time becomes too long (I can't remember the exact metric) though.

> I'll see if I can contribute to v3 to speed things along :)

Thanks! If you email erik@exercism.io he can point you in the right direction :)

**Comment by nina-py** [comment]
Thank you @iHiD, will do!
