### ISSUE TITLE
Solidity Language Track

### ISSUE THREAD

**Issue by ali2251** [exercism/exercism#5417]
Hi, 

I have been working with Rust track on exerecism and really like it, I was looking to see there isnt a Solidity track on Exercism yet and I would love to make it happen, I have been teaching Solidity for over 3 years now and would love to create a language track for it similar to Rust and others, Let me know how we can make it happen!

**Comment by iHiD** [comment]
Awesome! Fill this out as a starting point: https://github.com/exercism/request-new-language-track/issues/new 🙂

**Comment by ali2251** [comment]
Done, thanks!

**Comment by ali2251** [comment]
Linking it here for anyone interested: https://github.com/exercism/request-new-language-track/issues/80
