### ISSUE TITLE
Waiting for mentor for two weeks

### ISSUE THREAD

**Issue by AlBibox** [exercism/exercism#5427]
I am waiting for two week a mentor on gigasecond exercise. Can you help me?

**Comment by iHiD** [comment]
Which track?

**Comment by AlBibox** [comment]
JS track

**Comment by AlBibox** [comment]
> Which track?
JS track

**Comment by iHiD** [comment]
There's quite a long queue on the JS track atm. I know people are working through it, but there is a bit of a wait. Sorry.

**Comment by AlBibox** [comment]
Oh ok, i understand, thank you

Il lun 30 nov 2020, 3:56 PM Jeremy Walker <notifications@github.com> ha
scritto:
