### ISSUE TITLE
Bad unicode display.

### ISSUE THREAD

**Issue by iago-lito** [exercism/exercism#5430]
I've been toying around with messy unicode characters in Rust's anagram track, to find out that the chain `zi̇mri` was displaying incorrectly on my screen, and my mentor confirmed it was also weird on their side.

The chain contains the Turkish grapheme `i̇` (`U+0069 U+0307`), which is supposed to show a diacritic over `i`. Instead the diacritic showed up over the next char:

expected:
![expected](https://user-images.githubusercontent.com/10091387/101265638-62d17800-3748-11eb-9827-7bc9acab1524.png)

actual:
![actual](https://user-images.githubusercontent.com/10091387/101265627-47666d00-3748-11eb-82f0-ba71be405e54.png)

This occured both in the code window and in the discussion panel.

```
$ uname -a
Linux etak 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux
$ firefox --version
Mozilla Firefox 83.0
```

**Comment by iHiD** [comment]
Thanks for reporting. Got the id of your solution please?

**Comment by iago-lito** [comment]
@iHiD Sure, here's the link to the [published version](https://exercism.io/tracks/rust/exercises/anagram/solutions/d1149057fc7340e88c15a2b01e47a654) (line 17) :)

**Comment by iHiD** [comment]
@iago-lito Thanks 🙂 

---

<img width="1097" alt="Screenshot 2020-12-07 at 15 26 22" src="https://user-images.githubusercontent.com/286476/101369763-96271a80-38a0-11eb-9cbe-730efaa0c928.png">

Interesting. So in Chrome on Mac, I see this ^^ which I believe is correct?

So I imagine there's one of two things happening:
1. Firefox has a bug
2. The default linux font you're using has a bug (we default to your system font).

@SaschaMann @sleeplessbyte @NobbZ This seems like the sort of thing that one of you tend to know about.

**Comment by SaschaMann** [comment]
We ran into the same issue in Julia before. The conclusion was 

> This is unavoidable (at least, on our end) — it has nothing to do with Julia, and has to do with fonts and text-rendering software.

(https://github.com/JuliaLang/julia/issues/35941#issuecomment-642897139)

**Comment by NobbZ** [comment]
On chrome I see some `i` in the middle of the word that is different from the `i` at the end, and also rendered using a different font. It seems to be *not* monospaced, but only half of the width of the other characters.

On Firefox though I can not see any difference between both `i`s, though the `m` hasn't a dot as well…

Therefore I'd indeed say it is a problem in how the system renders the fonts, and there are a plentora of options, though indeed it has to be said, that many renderers begin to struggle when there are combined diacretics…

@iHiD do you [normalize into any of the 4 forms](https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization) or do you save and serve unicode data as is?

**Comment by iHiD** [comment]
> @iHiD do you normalize into any of the 4 forms or do you save and serve unicode data as is?

As far as I know, the later. Although the code goes through a DB and/or a markdown processor, so either of those could do things implicitely.

**Comment by SleeplessByte** [comment]
Ruby does `NFC` by default, FWIW. `NFKC` would result in different glyphs, right?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
