### ISSUE TITLE
exercism download will nuke your previous work for that exercise if (accidentally) run a second time

### ISSUE THREAD

**Issue by gilescope** [exercism/exercism#5432]
Users run the following to download and start an exercise:

`exercism download --exercise=simple-linked-list --track=rust`

but me being a numpty I managed to accidentally rerun that command while looking for something else in my history and the work in progress one I was doing got nuked. If I can do it I'm sure others can. Suggest it says `are you sure you want to do this?` if that dir already exists...

**Comment by kotp** [comment]
Since it is in progress, I would say "save the file in the editor" and you should save what is there in progress, overwriting what was delivered.

**Comment by iHiD** [comment]
@gilescope That sucks. Sorry!
@ekingery Any idea how hard this would be to implement in the CLI?

**Comment by ekingery** [comment]
This problem has a very rich history. Getting agreement on an implementation seems far more difficult than writing the code, which could potentially be as simple as a handful of lines, and I suspect it might have already be written in one or more forms. From a quick glance at the following issues, failing the download if the folder exists and providing a `--force` option seems reasonable and should be fairly simple to implement. See:

https://github.com/exercism/cli/pull/452
https://github.com/exercism/discussions/issues/129
https://github.com/exercism/cli/issues/362
https://github.com/exercism/cli/issues/411
https://github.com/exercism/cli/issues/457
https://github.com/exercism/cli/issues/795
https://github.com/exercism/cli/issues/872

**Comment by iHiD** [comment]
Thank you 💙 

> From a quick glance at the following issues, failing the download if the folder exists and providing a --force option seems reasonable and should be fairly simple to implement. 

If you fancy adding this to your ever-growing list of contributions, it would be a welcome PR 😁

**Comment by haguro** [comment]
@iHiD Beat @ekingery to it and sneaked in a PR. Hope that's cool 😅

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
