### ISSUE TITLE
Support private comments

### ISSUE THREAD

**Issue by kljensen** [exercism/exercism#5447]
As a user, when I see another user's solution, I'd like to take notes on what I learned. E.g.  "This user is storing the total minutes only and not storing the hours and minutes separately. That is a better approach because ...XYZ...". Often, I wish to make such comments for my own learning and I do not want to share them with the author (usually because it sounds like critique).

**Comment by glennj** [comment]
You might consider writing notes in a file in your solution directory.

**Comment by kljensen** [comment]
For sure it is totally fine and wonderful to take notes in one's own repo or on one's own computer. I think it would likely be a decent feature in the exercism web app too. Of course, I might be wrong.

**Comment by iHiD** [comment]
We're adding "scratchpad" to v3 where you can start to make notes as you use Exercism. Initially, this will only appear in the mentoring section (for mentors) but we intend to roll it out side-wide eventually. So consider this on the roadmap :)

**Comment by kljensen** [comment]
Thanks @iHiD. That sounds great. From the peanut gallery...a few features to consider.

* It would nice to have line-indexed comments similar to how one might comment on a code-review in GitHub. 
* When I view my solution to a problem, it would be nice to somehow also see the comments I made on other persons' solutions to the same problem and maybe solutions I've starred. 

(Random note. I'm surprised how effective exercism.io is for my learning. When I see others' solutions to the problem I just completed I am really primed to learn from them because I understand exactly what the code the code ought to do. This is quite different than reading code not understanding what it is doing. )

**Comment by iHiD** [comment]
We're planning on getting line references in in v3 (maybe not at launch). They won't be inline, but you will be able to reference lines (and probably blocks) in your code and see them highlighted or embeded (details to be worked out). At some point when I have more time I will write up the rationale.

Linking to other's solutions that you've commented on or mentored is a nice idea.

And it's great to hear that Exercism is proving valuable for you!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
