### ISSUE TITLE
Support versioned submittions

### ISSUE THREAD

**Issue by kljensen** [exercism/exercism#5448]
As a user, after completing my submission, I would like to update it to reflect what I learned from other people's submissions, but preserving my initial submission.

I often want to change my answer after seeing others' answers. But, if the initial submissions are not preserved, all submissions would start to look the same due to editing.

**Comment by kotp** [comment]
Being able to see multiple submissions would be helpful in this case, or a comment that links the other persons solution may be helpful to avoid the "all solutions migrate toward The Golden Solution."

**Comment by glennj** [comment]
The "my/solutions/uuid" page does show your iterations, so you can track your own journey. Although the published solution does only show the latest iteration. Are you suggesting you want to select which iteration should be the published one?

**Comment by kljensen** [comment]
For my personal use, I'd like to see my "initial solution" and my "final solution" or "latest solution". There's something to be learned from both when browsing others'. I'm hesitant to publish revised solutions after I see others' solutions because it feels like cheating. This would make it not so. (Of course, I acknowledge I could be in the minority, seeking this feature.)

**Comment by kotp** [comment]
When there are 10-20 iterations though, many of them are interesting, often the journey is more important than the first or the last iteration.

**Comment by kotp** [comment]
I would indeed like to be able to select multiples to "publish".

**Comment by kljensen** [comment]
I just noticed the " Iteration 3 of 3 " at the top right. I hadn't seen that. Closing issue.
