### ISSUE TITLE
Alternate way to install on Mac

### ISSUE THREAD

**Issue by singalen** [exercism/exercism#5449]
[Walkthrough beginning](https://exercism.io/cli-walkthrough), Mac branch, tells us to install Homebrew.

This is a no-go for many people. I, for example, use MacPorts.

There should be an alternative way to install `exercism`. I guess the page needs another paragraph "If you cannot install brew" that points to: https://exercism.io/cli

**Comment by NobbZ** [comment]
exercism.io/cli-walkthrough for mac does suggest manual installation as an alternative for using brew, in two pathes I tried, can you please elaborate which path does not suggest manual installation?

**Comment by singalen** [comment]
Sorry, my bad. I didn't read into the "To install manually" paragraph on that page, I took it as if it's another `brew` instruction.
