### ISSUE TITLE
FSharp Code Highlighter Comment  Bug

### ISSUE THREAD

**Issue by martinfreedman** [exercism/exercism#5450]
In F#, it is idiomatic to convert the multiplier operator to a function `(*)`

This causes a problem with the F#  syntax highlighter, which sees (`*...multi-line comment...*)` as a comment, as seen in this screenshot from [my solution](https://exercism.io/my/solutions/3d6c0ef35f884a5cb38f1b1cdd6d42c0). This does not occur in other markdown syntax highlighters I have used.

![image](https://user-images.githubusercontent.com/9550055/103380399-b1242d80-4ae0-11eb-867c-0e41f8df0e22.png)

**Comment by iHiD** [comment]
Does the same thing happen if you paste the code into [Prism's tester](https://prismjs.com/test.html#language=fsharp)?

**Comment by martinfreedman** [comment]
> Does the same thing happen if you paste the code into [Prism's tester](https://prismjs.com/test.html#language=fsharp)?

Yes

**Comment by martinfreedman** [comment]
Opened in Prism as [issue](https://github.com/PrismJS/prism/issues/2696)

**Comment by iHiD** [comment]
You pre-empted my next comment. Thanks :)

**Comment by martinfreedman** [comment]
It has generated a [PR](https://github.com/PrismJS/prism/pull/2703) but not committed to main yet.

**Comment by martinfreedman** [comment]
It has been committed/merged to main there. However the false positive issue still appears on my solution in exorcism.

**Comment by iHiD** [comment]
Yeah, we have to upgrade to the new version our end. @kntsoriano Could you action this asap pls (the v2 website gets permanently frozen from a git perspective on Friday FYI)

**Comment by kntsoriano** [comment]
I've opened https://github.com/exercism/website/pull/986 to bump Prism to the latest version. Unfortunately, they have yet to cut a release that contains a fix for your issue. We're unable to point to master as we rely on the latest version on the CDN.

**Comment by martinfreedman** [comment]
Thanks @kntsoriano I am closing this issue
