### ISSUE TITLE
Social log in stuck in a loop

### ISSUE THREAD

**Issue by JoshuaSkootsky** [exercism/exercism#5451]
Hello. Trying to try out Exercism for the first time.

At `https://exercism.io/users/sign_up` I try clicking on the GitHub social log in.

This takes me to `https://exercism.io/` without being logged in, but with an option to log in or sign up with GitHub social log in.

I click on that, and it takes me back to `https://exercism.io/users/sign_up`

So there's a loop for trying to do the social sign in with GitHub for the first time.

I got an email from Exercism saying that they got my email from GitHub, and that permission was added to my GitHub profile. But I can't 'log in' to Exercism.

[Screen shots here](https://imgur.com/a/mL91ghw)

**Comment by JoshuaSkootsky** [comment]
This was totally real as documented by the screenshots, but somehow resolved itself.

**Comment by iHiD** [comment]
Strange. Must have been some issue GH's end.
