### ISSUE TITLE
Test runner for the R track

### ISSUE THREAD

**Issue by jonmcalder** [exercism/exercism#5457]
Hey team!

I'm the (sole 😢 ) maintainer for the R track and at @ErikSchierboom's advice would like to get going on creating a test runner.

I've gone through the [docs here](https://github.com/exercism/v3-docs/tree/master/anatomy/track-tooling/test-runners) and have some basic experience with Docker but would appreciate any help in terms of how to get started and what's required.

Please could you assist me with bootstrapping a basic test-runner repo that I can begin working on. Thanks!

**Comment by iHiD** [comment]
Hey @jonmcalder 🙂 

I've created a repo for you and given you write access: https://github.com/exercism/r-test-runner

I recommend cloning https://github.com/exercism/generic-test-runner and using that as your base.

I'd also recommend not worrying about the docker bit atm. Getting the actual thing working for R is the key, then the Docker bit is normally quite straight-forward and @ErikSchierboom and others can help with that.

So the main thing is getting a problem that runs the tests and outputs them in the correct JSON format, as per the `interface.md` in the docs you list. We have a plethera of these now, so if there are other languages you're fluent in, I'd check to see if there's one written for that as a reference, and we can connect you to the author of that! :)

Thanks for doing this!

**Comment by jonmcalder** [comment]
Thanks @iHiD!
