### ISSUE TITLE
phpunit does not find test class

### ISSUE THREAD

**Issue by arty-hlr** [exercism/exercism#5458]
Hi,

Just setting up the PHP track of exercism, following the instructions on the problem's page:

```
Running the tests

    Go to the root of your PHP exercise directory, which is <EXERCISM_WORKSPACE>/php. To find the Exercism workspace run

     % exercism debug | grep Workspace

    Get PHPUnit if you don't have it already.

     % wget --no-check-certificate https://phar.phpunit.de/phpunit.phar
     % chmod +x phpunit.phar

    Execute the tests:

     % ./phpunit.phar hamming/hamming_test.php

```

And getting consistently the following error:
```
└──╼ $./phpunit.phar hello-world/hello-world_test.php
Class 'hello-world_test' could not be found in '/home/florian/Documents/Hacking/exercism/php/hello-world/hello-world_test.php'.
```

This seems to be related to [this](https://github.com/exercism/exercism/issues/5403#issue-727654355) issue, which unfortunately has not been solved.

For background, I just have PHP 7.4.13 installed, and have never developed in it, so it's a clean slate so to say.

I'd be grateful for any help in setting up the tests!

Thanks in advance,
Florian

**Comment by glennj** [comment]
I posted this before looking at the linked issue where I posted exactly the same advice ...

**Comment by neenjaw** [comment]
Hi @arty-hlr, I have a few questions to hopefully get you up and running with this.

Just want to first make sure that you have php installed correctly:
1. How did you install php?
   - when you type `php -v` into the console, what version is returned? ( I have 7.4.9 )
2. Did you install composer? locally? or globally?
   - when you type in `composer --version` what version is returned? ( I have 2.0.7 )
3. Did you install php unit with: `composer global require phpunit/phpunit ^8`?
   - when you type in `phpunit --version` what version is returned? ( I have 8.5.8 )

Now, if everything is installed correctly, from the exercise directory, the tests should be able to be run like so:
```shell
> cd ~/exercism/php/hello-world
> phpunit ./hello-world_test.php
```

Share your results, and let's get you going!

**Comment by arty-hlr** [comment]
Hi @neenjaw,

Thanks for your comment!

My php is 7.4.13 as stated above. I don't have composer, or phpunit installed through composer, I just followed the steps on the page that said to download phpunit as a .phar and run it from the php directory. I tried installing phpunit from AUR, which resulted in the same error.

I'll try through composer, but if that were required, it'd be great if it were in the guide for running the tests instead of the .phar! :)

**Comment by arty-hlr** [comment]
After installing composer, and phpunit, it works, only with the full path of phpunit though:
```
/home/florian/.config/composer/vendor/phpunit/phpunit/phpunit hello-world/hello-world_test.php
```
Would be great to correct the guide on the exercise pages! :)

**Comment by glennj** [comment]
> After installing composer, and phpunit, it works, only with the full path of phpunit though:
> 
> ```
> /home/florian/.config/composer/vendor/phpunit/phpunit/phpunit hello-world/hello-world_test.php
> ```

You'll certainly want to create an alias for that monstrous path.

**Comment by asahnoln** [comment]
Later versions of phpunit require the test file to be named as the class, thus not `hello-world_test.php`, but `HelloWorldTest.php`. It seems that all tests in PHP track rely on phpunit-8. I'd suggest to change the download command from 
`wget --no-check-certificate https://phar.phpunit.de/phpunit.phar`
to
`wget --no-check-certificate https://phar.phpunit.de/phpunit-8.phar -O phpunit.phar`

**Comment by arty-hlr** [comment]
That, or rename the test files like their classes, both options should solve the problem!
