### ISSUE TITLE
New exercise added after track completion is locked

### ISSUE THREAD

**Issue by ak4ra** [exercism/exercism#5460]
I completed the Typescript track a few months ago. I just noticed that a new exercise has been added to the core exercises but it is locked so I can't access it, even though I have completed all the previous ones.

**Comment by iHiD** [comment]
Thanks for letting us know. I'm running a script to resync everyone's tracks now. It'll take a couple of hours to run but then you should be sorted. Please let me know if that works :)

**Comment by ak4ra** [comment]
Thanks, it is unlocked now.

**Comment by iHiD** [comment]
Great. Thanks :)
