### ISSUE TITLE
D Leap not unlocked after Hello World submission

### ISSUE THREAD

**Issue by amoradell** [exercism/exercism#5467]
I have started D track last week in mentoring mode and submitted Hello World exercise
Leap exercise is not unlocked
I managed to download a side exercise, Two Fer and successfully submitted a solution

**Comment by iHiD** [comment]
In mentored mode, you currently need your mentor to approve a solution before you can move on. So the mentor needs to approve two-fer before leap becomes unlocked.

**Comment by amoradell** [comment]
Leap is the second mentored exercise, just after Hello World.
Two Fer is a side exercise with no mandatory mentoring. 
It's unlocked with 22 other exercises in this D track after submitting Hello World.
Maybe I will switch to Practice Mode

**Comment by iHiD** [comment]
Ah, my misunderstaning, sorry. Yes - I'd suggest Practice Mode might be a good plan for that Track!

**Comment by amoradell** [comment]
Switch to Practice mode, I close this issue
