### ISSUE TITLE
Clarification on the limits of practice mode

### ISSUE THREAD

**Issue by inprogresspleasehold** [exercism/exercism#5471]
Hi! I think this is a fantastic project, but I have a question about practice mode. There are conflicting descriptions of practice mode on the website. When you opt to declare an exercise completed yourself, you get this (relevant) text:

> "If you want to quickly move through the track without regular feedback, we recommend moving to Practice Mode, where you can choose which exercises to receive feedback on. You can do on the right-hand-side of the Track page."

But when you click on the practice mode option in the sidebar, you get this text: 

> "In Practice Mode all of the exercises within a track are unlocked and students can work through them freely. Note that in this mode Mentor feedback is disabled. This mode is for people who want to do fast deep-dives into a track and is not recommended for those that want the full Exercism experience."

Does practice mode allow you to opt-in for mentor feedback for selected exercises or not?

**Comment by iHiD** [comment]
Hello. Thanks :) 

You can request mentor feedback, but you go to the bottom of the queue, so for many tracks it's unlikely mentors will get to you.

In v3 (launching in the next few months), this all changes and both modes before more like Practice Mode, where you just request if you want, without ever being blocked.

**Comment by inprogresspleasehold** [comment]
Ah, that helps! v3 sounds like it will lessen the load on the mentors a bit. Thanks for making this!

**Comment by iHiD** [comment]
Thanks for saying thanks - it's always appreciated 💙 

Yeah - a big part of our aim is to make the barrier to getting mentoring **slightly** higher to encourage people who don't really care about the mentoring not to take our mentors time up, while also rewarding our mentors within exercism more (for example one's "reputation" is used to calculate queue position) while also trying to **lower** the barrier to getting started mentoring.

We'll see if it works!!
