### ISSUE TITLE
Problem with C# Clock task

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5473]
Many thanks to @AndrewShchetkin who recently took pity on my submission at https://exercism.io/my/solutions/c66546ec4fea40aebd89b2b7b77b2dad . He pointed out that I needed to change the Equal method in the tests.
Ordinarily I don't fiddle with the tests other than to remove the that which blocks the test from being run. Now it's being suggested that I change the tests which sounds a bit like cheating.

Here's my code
```csharp
using System;

public class Clock
{
    private int Minutes { get; set; }
    private const int MINUTES_PER_DAY = 24 * 60;

    private void CalculateMinutes(int mins) => Minutes = mins >= 0 ? mins % MINUTES_PER_DAY : MINUTES_PER_DAY + (mins % MINUTES_PER_DAY);

    public Clock(int hours, int minutes) => CalculateMinutes(hours * 60 + minutes);

    public Clock Add(int minutesToAdd)
    {
        CalculateMinutes(Minutes + minutesToAdd);
        return this;
    }

    public Clock Subtract(int minutesToSubtract)
    {
        CalculateMinutes(Minutes - minutesToSubtract);
        return this;
    }

    public override string ToString() => string.Format("{0:D2}:{1:D2}", Minutes / 60, Minutes % 60);
}
```
The test fails but with what appears to be a false negative, viz
```

[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET 5.0.1-servicing.20575.16)
[xUnit.net 00:00:00.54]   Discovering: Clock
[xUnit.net 00:00:00.66]   Discovered:  Clock
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET 5.0.1-servicing.20575.16)
[xUnit.net 00:00:00.51]   Starting:    Clock
[xUnit.net 00:00:00.63]     ClockTests.Clocks_with_same_time [FAIL]
[xUnit.net 00:00:00.63]       Assert.Equal() Failure
[xUnit.net 00:00:00.63]       Expected: 15:37
[xUnit.net 00:00:00.63]       Actual:   15:37
[xUnit.net 00:00:00.63]       Stack Trace:
[xUnit.net 00:00:00.64]         /home/bugmagnet/Dropbox/Exercism/csharp/clock/ClockTests.cs(263,0): at ClockTests.Clocks_with_same_time()
[xUnit.net 00:00:00.65]   Finished:    Clock
----- Test Execution Summary -----

ClockTests.Clocks_with_same_time:
    Outcome: Failed
    Error Message:
    Assert.Equal() Failure
Expected: 15:37
Actual:   15:37
    Stack Trace:
       at ClockTests.Clocks_with_same_time() in /home/bugmagnet/Dropbox/Exercism/csharp/clock/ClockTests.cs:line 263
    
Total tests: 1. Passed: 0. Failed: 1. Skipped: 0
```
Notice that the Expected and Actual are visually the same. So why is it an Assert.Equal() failure?

Andrew says, "You need override Equal method". Is that the case? Or does the test writer need to do that (and for all subsequent programmers who attempt that task)?

**Comment by iHiD** [comment]
cc @ErikSchierboom

**Comment by AndrewShchetkin** [comment]
Hi, @axtens!
I mean you need override Equals method into your class Clock, how did you do it with ToString() method :)

**Comment by AndrewShchetkin** [comment]
> Notice that the Expected and Actual are visually the same. So why is it an Assert.Equal() failure?

Expected and Actual equal, because uses ToString() method to get clock objects for log. But for comparison used method Equals()

**Comment by axtens** [comment]
Ahh ... my mistake. Okay, will see what I can do about it from this end.
