### ISSUE TITLE
GitHub authentication fails with "502 Bad Gateway"

### ISSUE THREAD

**Issue by joelnordell** [exercism/exercism#5475]
I am unable to sign up or log in to exercism.io using GitHub. After authenticating to GitHub, I get a "502 Bad Gateway" error on exercism.io. (The exercism app did register successfully on my github account.)

![image](https://user-images.githubusercontent.com/439499/108137911-7ff8c000-7082-11eb-9287-b5db22b59097.png)

**Comment by iHiD** [comment]
Thanks. This is strange. Is it repeatable for you?

**Comment by joelnordell** [comment]
Yes, it happens every time.

**Comment by iHiD** [comment]
Could you check your email addresses are all verified on GitHub please? https://github.com/settings/emails

**Comment by joelnordell** [comment]
Ah, I did have some old and unverified email addresses on my profile. Let me remove those and try again.

**Comment by joelnordell** [comment]
Following up -- removing the old/unverified email addresses from my Github profile solved it!

It would be great if exercism could provide a useful error message in that situation, instead of a 502 bad gateway error.

**Comment by kotp** [comment]
@joelnordell Thanks for the follow-up.

**Comment by iHiD** [comment]
I wrote a message in response to this but it seems to have got lost. Basically, yes, I agree, we should. The problem is that we don't actually know the cause (other than from experience) and the bad gateway failure is super low-level and unspecific so I struggled to catch the exception to rescue it. I'll take another look in v3.

**Comment by joelnordell** [comment]
Thanks @iHiD - let me know if there's anything I can do to help.
