### ISSUE TITLE
x86_64 on Apple Silicon: ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by TiiFuchs** [exercism/exercism#5476]
I tried running the tests of the hello_world program in the x86_64 Assembly track, but when running make I only get the error:

```
ld: warning: ignoring file hello_world.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
Undefined symbols for architecture arm64:
  "_hello", referenced from:
      _test_say_hi in hello_world_test.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tests] Error 1
```

I guess it doesn't work yet on macOS with Apple Silicon (M1) Chip?
Any recommendation how to bypass that?

**Comment by TiiFuchs** [comment]
I found a workaround, since Rosetta 2 can run x86_64 binaries, you need to tell gcc to compile for x86_64.

When I ran `gcc -v`, I found that the default target is `Target: arm64-apple-darwin20.3.0`.
So I added `-target x86_64-apple-darwin20.3.0` to the CFLAGS in the Makefile (provided by Exercism)
so it looks like this:

`CFLAGS = -g -Wall -Wextra -pedantic -Werror -target x86_64-apple-darwin20.3.0`

Then it works :)

**Comment by TiiFuchs** [comment]
`-target x86_64-apple-darwin` seems to work too.

**Comment by TiiFuchs** [comment]
Since nasm seems to be a x86 compiler, this seems to be the only solution.

**Comment by iHiD** [comment]
(cc @@bergjohan)

**Comment by bergjohan** [comment]
Since Mac is changing from x86_64 to ARM64 architecture, this track will stop working for macOS unfortunately.

I started an ARM64 track a while back, but I haven't had time to write more than a simple hello-world exercise for it: https://github.com/exercism/arm64-assembly

**Comment by TiiFuchs** [comment]
But as long as macOS can run x86-64 programs, it should be okay if we change the Makefile in every existing assembly exercise like described above. (I‘m not sure if the above ggc target is the default on x86 machines, but we could always use conditionals.)

And as far as I know Rosetta 2 should still work for a while. ;)

**Comment by bergjohan** [comment]
Yeah, that's true! :)

Right now we have the following in the Makefile: `ifeq ($(shell uname -s),Darwin)`. If we could do something similar to detect if we're on an ARM64 based Mac, we could add the compiler flag.

However, we're currently going through some restructuring in the repos due to the launch of Exercism v3. I'm not sure if it's possible to still make changes to the old v2 site, @iHiD ?

**Comment by iHiD** [comment]
You can make changes (please do!), but they won't go live on the website until v3 launches 🙂

**Comment by bergjohan** [comment]
@TiiFuchs Could you verify that the command `sysctl hw.optional.arm64` prints 1 and that `sysctl hw.optional.x86_64` doesn't on your machine?

**Comment by TiiFuchs** [comment]
I can confirm, that hw.optional.arm64 returns 1, hw.optional.x86_64 returns nothing.
![image](https://user-images.githubusercontent.com/1958744/108626801-61177680-7452-11eb-871d-ade7dce9900a.png)

**Comment by TiiFuchs** [comment]
For the record: This is the output on a mac with Intel chip:
![image](https://user-images.githubusercontent.com/1958744/108627348-60341400-7455-11eb-9735-1083edaadfad.png)

**Comment by bergjohan** [comment]
Perfect, thank you! I'll try to make the change to the Makefiles in the next couple of  days. I'll let you know when it's ready. It would be great if you could verify that it's working correctly then, since I don't have a Mac.

**Comment by TiiFuchs** [comment]
of course! :) I keep an eye out!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by luistejeda3006** [comment]
> 

I´m something Noob with React Native, Could u tell me where add --> CFLAGS = -g -Wall -Wextra -pedantic -Werror -target x86_64-apple-darwin20.3.0

**Comment by Brightchu** [comment]
> I found a workaround, since Rosetta 2 can run x86_64 binaries, you need to tell gcc to compile for x86_64.
> 
> When I ran `gcc -v`, I found that the default target is `Target: arm64-apple-darwin20.3.0`. So I added `-target x86_64-apple-darwin20.3.0` to the CFLAGS in the Makefile (provided by Exercism) so it looks like this:
> 
> `CFLAGS = -g -Wall -Wextra -pedantic -Werror -target x86_64-apple-darwin20.3.0`
> 
> Then it works :)

Thanks a lot. it works for me.

**Comment by owenramber1989** [comment]
> `-g -Wall -Wextra -pedantic -Werror -target x86_64-apple-darwin20.3.0`

I can't thank you enough. I was about to turn into my old-fashioned x64 laptop for just compiling a small cpp file when I saw your solution! That helps a lot.
