### ISSUE TITLE
Couldn't submit the solution for Go.

### ISSUE THREAD

**Issue by minsiyang** [exercism/exercism#5478]
Hi there, I just try my first Go kata. I was able to download it, run test and implement the solution. But I don't seem to be able to submit it. I looked up some other issue, and try some different way, but still no joy. Can you give me some advice?
<img width="482" alt="Screenshot 2021-02-23 at 21 44 18" src="https://user-images.githubusercontent.com/63360483/108913047-5ced8380-7621-11eb-81da-ace1d9789d1e.png">
<img width="648" alt="Screenshot 2021-02-23 at 21 47 10" src="https://user-images.githubusercontent.com/63360483/108913066-64149180-7621-11eb-916a-57223f9505cb.png">

**Comment by iHiD** [comment]
👋 

Try changing into the `/Users/xxx/exercism/go/hello-world` directory then running `exercism submit hello_world.go`

**Comment by minsiyang** [comment]
Thank you for the suggestion. Just tried that, it gave me the same response

```
➜  hello-world exercism submit hello_world.go
Error: not in workspace
```
😅

**Comment by iHiD** [comment]
Hmmm, odd!

Some questions:

1. What is the `workspace` in `exercism configure`?
2. How did you install the CLI?
3. What shell are you using?
4. Is your username ascii based or does it have unicode characters in? (This shouldn't matter but I'm not sure)

(cc @nobbz @kotp as this is about to move out of my fixing zone and I need some experts 🙂)

**Comment by NobbZ** [comment]
Your workspace seems to be `~/Exercism` with an **uppercas** `E` (as seen in the `exercism download` output), while you are trying to submit from `~/exercism` with a **lowercase** `e`.

While your MacOS' filesystem is not case sensitive by default and treats both folders the same, the `exercism` CLI does not. It is crucial for the CLI that you use the same casing that the CLI expects according to its configuration.

**Comment by minsiyang** [comment]
I see. I totally didn't spot that. I change between a few laptops, and have to make new folder each time. Thank you so much! It totally works now! I will make sure I alway start making a new directory with the capital ```E``` from now on 😅

**Comment by iHiD** [comment]
(Thanks @NobbZ!)
