### ISSUE TITLE
'exercism download' not pulling from respective repos

### ISSUE THREAD

**Issue by vjba** [exercism/exercism#5485]
When using `exercism download --exercise={exercise name} --track=csharp` there is a mismatch in code from what is downloaded vs. what is in the remote repo.

For example, assuming the `exercism download --exercise=allergies --track=csharp` command maps to the repo [exercism/csharp/tree/main/exercises/practice/allergies](https://github.com/exercism/csharp/tree/main/exercises/practice/allergies), the remote code in [`.csproj`](https://github.com/exercism/csharp/blob/a27e910807e22bb7cb523296ce686200562412ab/exercises/practice/allergies/Allergies.csproj#L4) shows 

```xml
<TargetFramework>net5.0</TargetFramework>
```

However, locally the .csproj shows

```xml
<TargetFramework>netcoreapp3.0</TargetFramework>
```

As netcoreapp3.0 is [unsupported as of March 3rd 2020](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) this throws console errors on any `dotnet ...` commands like below:

```
warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
```

**Comment by SaschaMann** [comment]
Tracks are no longer being synced to the website due to preparations for the upcoming new version of Exercism: https://github.com/exercism/csharp/issues/1438

The last version that's on the website, afaict, is [1de882c7](https://github.com/exercism/csharp/tree/1de882c79ac80b59baa82e2a42f968106895caf3).

**Comment by vjba** [comment]
Thanks for the info @SaschaMann!
