### ISSUE TITLE
[Rust] Installed but unsure were to run.

### ISSUE THREAD

**Issue by reedrainer** [exercism/exercism#5488]
So Ive been through everything stated in the walk through and can confirm that Ive installed exercism as stated and set it up. What im looking for now is the space i need to go to to run the stated ```cargo test```.

``` 
/home/reed/snap/exercism
[reed@reedpc exercism]$ ls -a
.  ..  5  common  current 
```

Might sound stupid ive tried to run ```cargo test``` in a few directories with the same result.

```error: could not find `Cargo.toml` in `/home/reed` or any parent directory```

could it be that i need to create the directory myself with ```cargo new``` which of course would create a new project with a .toml file. 
I know its a picky point but no where in the walk-through or instructions does it tell you to do this.

**Comment by iHiD** [comment]
Have you downloaded the exercise yet? (It's the "1" of the 1/2/3 on the exercise page on the website and will start `exercism download ...`). That will give you some more directories with the relevant files in.
