### ISSUE TITLE
Can't figure out where to input my exercise. (Python)

### ISSUE THREAD

**Issue by arvindr92** [exercism/exercism#5489]
Hi, 

I am on the Python track. I have Python 3.9 installed on my system.

I installed the CLI. 

I authenticated my token with the CLI and it's configured. 

I installed the pytest module

In the readme, it says the below

-Write a function that returns the string "Hello, World!".
- Run the test suite and make sure that it succeeds.
- Submit your solution and check it at the website.

I don't understand exactly what needs to be done. Do I write the 'hello world' code in a .py file and keep it in the same directory?  I am not able to run 'hello_world_test.py', either in PowerShell or using the GUI in Windows. I can't figure where I am supposed to write my code. In the CLI? In a separate text file? In a .py file?

Can you please help me figure this out?  

I am attaching a screenshot with the error messages.
![exercism](https://user-images.githubusercontent.com/80283820/110369709-c7b2ac00-8070-11eb-8158-ca08f15c739e.png)
at I get in PowerShell. I tried executing both 'hello_world_test.py as well as 'hello_world.py'

Thanks for your [help[](url)](url)

**Comment by arvindr92** [comment]
Hi NobbZ - Thanks for your reply. 

I have edited the stub function now, and the result Hello, World! is being produced, but I am still getting a fail error. 

I have attached the screenshot from powershell for you. After I took the screenshot, I tried the same again using py pytest hello_world_test and it failed again. 

![hello_world_fail](https://user-images.githubusercontent.com/80283820/110752224-fbf1bc80-826a-11eb-87e7-93a3bbf556ee.png)

**Comment by Phaedrus44** [comment]
Hi arvindr92, did you find a solution to this? Having similar issue. Running from MacOS terminal. Thanks

**Comment by glennj** [comment]
Pay close attention to the exercise's README:
> The objectives are simple:
> - Write a function that returns the string "Hello, World!".

The test is _calling the function_ and comparing the _return_ result to the expected string.

You might want to read about functions in [the Python tutorial](https://docs.python.org/3/tutorial/index.html)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
