### ISSUE TITLE
trouble running npm install for javascript hello-world

### ISSUE THREAD

**Issue by c-majkowski** [exercism/exercism#5490]
I'm trying to run npm install and npm test on my completed hello-world program, and it's not working. It gives me the following error and I don't know how to fix it.
![Screenshot (26)](https://user-images.githubusercontent.com/80363426/110571775-1e2df200-8126-11eb-8e1c-b89accd92f32.png)

**Comment by c-majkowski** [comment]
Ok, that made it work! Thanks :)

**Comment by iHiD** [comment]
Great :)
