### ISSUE TITLE
Approved exercise is stuck

### ISSUE THREAD

**Issue by eugene-stativka** [exercism/exercism#5491]
![image](https://user-images.githubusercontent.com/45566415/110681168-cf419480-81d9-11eb-9c58-bc44c9b80f13.png)

**Comment by iHiD** [comment]
Thanks @eugene-stativka. And what is the problem? Are you still seeing it as "In Progress" somewhere else? If so, could you screenshot me that pls?

**Comment by eugene-stativka** [comment]
Hi @iHiD! Thanks for your prompt feedback! Yes, it's still `In Progress`. I submitted my solution, the mentor approved it but it's still marked as `In Progress`.
![image](https://user-images.githubusercontent.com/45566415/110694763-534f4880-81e9-11eb-9eaa-cce3f81b05cc.png)
![image](https://user-images.githubusercontent.com/45566415/110694878-809bf680-81e9-11eb-85a7-639538848646.png)
![image](https://user-images.githubusercontent.com/45566415/110695064-b17c2b80-81e9-11eb-8189-a5f7643981ff.png)

**Comment by iHiD** [comment]
They're different exercises :)

One is `Resistor Color`, the other is `Resistor Color Duo` (the second in the series)

**Comment by eugene-stativka** [comment]
Oh, I'm sorry for this confusion

**Comment by iHiD** [comment]
That's ok! :)
