### ISSUE TITLE
Waiting for mentor, since 13/03/2021

### ISSUE THREAD

**Issue by sergree** [exercism/exercism#5499]
Hello! 🙏
Rust track
Forth exercise

UUID:
175c4eb61e12459e8f7d8142aa28e4a0

I'm sorry to bother you, I know that all mentoring is done on a volunteer basis.

**Comment by iHiD** [comment]
Thanks for the empathetic post 💙 I've pinged the Rust mentors to check it's not fallen through the cracks 🙂

**Comment by coriolinus** [comment]
Hi @sergree. Just wanted to give you a brief update.

Unfortunately, mentoring your solution is just taking some time. Forth is the last core exercise in Rust, chosen as a "capstone" exercise designed to both challenge and reward the student. A student who completes that exercise has demonstrated advanced working knowledge of lifetimes and mutability, which are the hardest parts of the language. However, positioning this particular exercise as a capstone was a choice made before mentoring was a thing, and unfortunately, it hasn't aged well.

Forth requires solutions which are invariably both relatively long and fairly idiosyncratic: there are just a _lot_ of different ways to implement the Forth language. This means that a proper review can easily eat up an hour or two. This in turn makes mentors tend to shy away from it; they can usually mentor between four and six simpler exercises (i.e. Luhn) in the same time. 

Right now there are five Forth solutions waiting for mentoring; of those, you appear to be in position 3. You haven't slipped through the cracks; you've just discovered the edge of mentor capacity.

**Comment by sergree** [comment]
Hello @coriolinus! Thank you very much for such a detailed explanation.

I just wanted to make sure there were no technical issues.
I had doubts because the page says: `The median waiting time for mentoring on this exercise is 3 days.`
And this number hasn't been updated in two weeks. 🙂

I also noticed that in the first week there was 1 solution ahead in the Forth queue, but then there were 2.

Your service helped me a lot in the practice of Rust, thank you very much for your work! 🙏

**Comment by sergree** [comment]
Thank you so much again!
