### ISSUE TITLE
C# mentor feedback slowed down -- can I see the full mentor queue?

### ISSUE THREAD

**Issue by MisterHill** [exercism/exercism#5507]
Hello! I am immensely grateful for mentor feedback, but I think all the C# mentors are busy as the overall queue has only gone down by 9 exercises since March 22.

I could switch to Practice Mode to move ahead but then my mentor queue position would go from 27th to the end, because practice mode is de-prioritized, yeah? But I don't know how big a jump that is -- if the entire queue is 100 submissions long, that'd probably be worth it to me, but if it's 500 then probably not.

Alternatively, is my understanding incorrect and only **future** submissions get placed at the bottom of the queue?

Thank you all. This site really is amazing.

**Comment by iHiD** [comment]
Hey 🙂  We're hard at work on v3 of the website, which is taking up lots of people's time. So, in all likelyhood mentoring is going to slow down a lot until we launch that (4-8 weeks away). I would recommend switching to Practice Mode. When we launch v3, the distinction between Learning Mode and Practice mode will be removed so you won't be penalised for your solutions that have been started in Practice mode then.

> Thank you all. This site really is amazing.

Thank you 💙

**Comment by MisterHill** [comment]
Gotcha, thank you! I saw the v3 site notice 2 weeks ago, but mentor feedback was chugging along nicely anyhow so it was odd when it dried up all of a sudden. Thankfully I also learn a lot while checking out other solutions, sorting by stars & comments. Maybe having one of those as the default sorting would be helpful too? 

Anyhow, thank you again.
