### ISSUE TITLE
Cannot move on without mentor discussion

### ISSUE THREAD

**Issue by jadely-lab** [exercism/exercism#5512]
I  submitted an answer about 2 weeks ago and I still haven't received a Mentor discussion, so I am stuck and cannot move on.
I am almost finished with all the side problems that are opened for me, so I would really love to move on with my track as soon as possible.
I resubmitted the solution today just to make sure it gets checked soon, but I haven't received anything yet.
Can you help me?
I am on Kotlin track and the problem I'm stuck on is "Two-fer."
Thank you.

**Comment by iHiD** [comment]
Hello. Sounds like we're short on Kotlin mentors atm. With the push towards v3 atm everyone is very busy. It might be better to move to Practice Mode until we launch v3, where you're not blocked by waiting.

**Comment by jadely-lab** [comment]
I didn't know about the practice mode so I'll try it out! Thank you!
