### ISSUE TITLE
Exercise resubmtted to que.

### ISSUE THREAD

**Issue by exordiri** [exercism/exercism#5520]
It has been a week since my mentor has 'been removed from this conversation due to inactivity', and no new mentor.
I don't want to complain, but I wonder if something has gone wrong.
Thank you for the cool website. I love the concept.

**Comment by iHiD** [comment]
Hello. Which track? Do you have a link to your solution please?

**Comment by exordiri** [comment]
> Hello. Which track? Do you have a link to your solution please?

Wow, I feel silly not providing that.
C++ https://exercism.io/my/solutions/c8782a2a57a5468f97f3f25b15448ebd
Thanks!

**Comment by iHiD** [comment]
(cc @exercism/cpp if anyone fancies mentoring https://exercism.io/mentor/solutions/c8782a2a57a5468f97f3f25b15448ebd 🙂)

**Comment by siebenschlaefer** [comment]
That mentor was me, the iteration and their e-mail got lost in my mailbox. I'm sorry about that.

I've just approved the solution, now they should be able to proceed.

**Comment by exordiri** [comment]
Great Thanks!
