### ISSUE TITLE
Crystal 

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5522]
```
There are currently 0 solutions ahead of this in the Crystal queue, and 0 ahead in the Triangle queue.
```
However, there's not the usual blurb about how long until someone checks on my progress. 

There are three Crystal mentors apparently.

**Comment by iHiD** [comment]
@axtens Thanks. Did anyone get to you on this?

**Comment by axtens** [comment]
Yes they did thank you. I've since closed it.

Warm regards,
Bruce
