### ISSUE TITLE
Issue downloading first exercise Javacript

### ISSUE THREAD

**Issue by KieranP-M** [exercism/exercism#5523]
Hi all

I have followed the instructions so far (I believe)- exercism CLI is installed. When I then enter the below:

'$ exercism download --exercise=hello-world --track=javascript'

I get this error:

'-bash: $: command not found'

Working off Terminal on a MacBook Pro. 

I am sure I am doing something obviously wrong, but have no experience here and am not sure what to do next. Have tried googling to no avail yet and tried a few other things in the terminal. 

Thanks :)

Kieran

**Comment by KieranP-M** [comment]
Hi All

Wow painful as I thought, I was copying the $ in and doubling up. First problem solved. 🤦‍♂️ 

Thanks!

Kieran

**Comment by iHiD** [comment]
Well done on sorting it :)

**Comment by KieranP-M** [comment]
Thank you! :) More challenges now, but I am trying to solve it again before I open another ticket!!
