### ISSUE TITLE
The connection times out when I try to configure token

### ISSUE THREAD

**Issue by danielsteman** [exercism/exercism#5524]
When I run `exercism troubleshoot` it gives me the following information: 
===========================

Version
----------------
Current: 3.0.13
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: dial tcp 140.82.121.5:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\dst015ont
Workspace: C:\Users\dst015ont\Exercism
Config:    C:\Users\dst015ont\AppData\Roaming\exercism
API key:   6a0f*****************************c4d

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: dial tcp 140.82.121.5:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.]
    * 21.0035086s

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: dial tcp 54.220.129.154:443: i/o timeout]
    * 30.000136s

I already restarted my computer a couple of times. I'm not able to switch off firewall due to restrictions on my company computer. When I visit https://api.exercism.io/v1/ping in browser everything appears to be fine.

**Comment by iHiD** [comment]
Hi @danielsteman. It seems that your terminal can't connect to the internet (we use GitHub there as a check that it's not just Exercism that's failing). So i guess there's some extra restrictions in your computer that are stopping that. I'm not sure there's much we can do to help you here - sorry 🙁

**Comment by danielsteman** [comment]
Hi @iHiD, thanks for your answer. When I `ping google.com` it seems like the command prompt can connect to the internet:

Pinging google.com [142.250.179.174] with 32 bytes of data:
Reply from 142.250.179.174: bytes=32 time=3ms TTL=120
Reply from 142.250.179.174: bytes=32 time=3ms TTL=120
Reply from 142.250.179.174: bytes=32 time=3ms TTL=120
Reply from 142.250.179.174: bytes=32 time=3ms TTL=120

Ping statistics for 142.250.179.174:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 3ms, Maximum = 3ms, Average = 3ms

I also tried it for github.com and the result is the same.

**Comment by iHiD** [comment]
Hi @danielsteman. I'm not sure then. Your firewall could be blocking a different level of network traffic (so pings get through but HTTP requests don't). Someone else will need to add more light onto that. Maybe @NobbZ or @kotp, or @ekingery from the CLI side of things?

**Comment by ekingery** [comment]
Hello. Yes, this is highly likely to be a block at the network level somewhere between (or maybe _on_) the windows host and github. Unfortunately I don't have recent windows troubleshooting experience. Similar to the commands that have already been run, I would try the following:

```exercism --timeout 180 troubleshoot```
 - see if it is just extreme slowness on your network?

 ```curl --head https://api.github.com/repos/exercism/cli/releases/latest```
 - make sure this returns a 200

```curl https://api.github.com/repos/exercism/cli/releases/latest```
 - make sure this returns a bunch of json data

```tracert api.github.com```
 - might give you some helpful additional information as to the networking routes

**Comment by NobbZ** [comment]
I have basically 2 ideas to the problem, as well as my usual legal advice when I read something about company hardware.

* Personal firewall blocking `exercism` "silently".
* Misconfigured proxy (check/set `HTTP_PROXY`/HTTPS_PROXY` env vars)

Also, best is probably to ask your IT department for permission to install third party software and their help to set it up.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
