### ISSUE TITLE
internal error, please report: running "exercism" failed: cannot find installed snap "exercism" at revision 5: missing file /snap/exercism/5/meta/snap.yaml

### ISSUE THREAD

**Issue by d0UBleW** [exercism/exercism#5525]
Hi, I was just starting to use exercism yesterday and it was working fine. However, when I try to use it again today something went wrong. I'm not really proficient in using UNIX operating system too. Thus, I had no idea how to fix it. And I'm running this on WSL2

![error](https://user-images.githubusercontent.com/66501624/116496430-3b35a480-a8cf-11eb-869e-c1c866b300f9.png)

![image](https://user-images.githubusercontent.com/66501624/116496546-80f26d00-a8cf-11eb-9f51-08ea72fc87ec.png)

![image](https://user-images.githubusercontent.com/66501624/116496572-9071b600-a8cf-11eb-96b4-ae51c83a3c35.png)

**Comment by revirth** [comment]
I had the same error in WSL2 so after remove the snap version, download the CLI like this article - https://raygervais.dev/articles/2021/2/learning_rust_with_exercism/ and it works :)

**Comment by d0UBleW** [comment]
> I had the same error in WSL2 so after remove the snap version, download the CLI like this article - https://raygervais.dev/articles/2021/2/learning_rust_with_exercism/ and it works :)

Thank you for the solution, now I can use exercism again.
