### ISSUE TITLE
Likely mentor response times

### ISSUE THREAD

**Issue by InkyLinesPlots** [exercism/exercism#5526]
First - congratulations on putting together such a great resource. 

I'm working through the java track and when i finish an exercise, I get this message

_There are currently 38 solutions ahead of this in the Java queue, and 1 ahead in the Binary Search queue. The median waiting time for mentoring on this exercise is about 3 hours._

But if I wait a day or two, I never get a mentor response. I've been getting around this by just using 'independent mode' but as the exercises get harder and my code scruffier, I feel I need some help...

So, my question, **is there a problem with the stated median waiting times, or am I doing something wrong?**

**Comment by iHiD** [comment]
Hello. Thanks for the nice message 🙂  

You should have got [this video](https://www.youtube.com/watch?v=XiV_vYn1Ea8) pop up at some point when using Exercism. It explains that there's a bit of a wait atm, as people are focussed on creating the new version of the site launching shortly. That's making the medians less reliable than normal. Hopefully once we've got everything launched we'll get to more reliable wait times again 🙂
