### ISSUE TITLE
Failed: Only ASCII alphanum

### ISSUE THREAD

**Issue by nightfury1103** [exercism/exercism#5527]
I don't understand what it is. I'm try anyway I can but it can't work :( 
![image](https://user-images.githubusercontent.com/61180080/116714458-ffe6c300-a9ff-11eb-8c78-ef058656220d.png)

**Comment by NobbZ** [comment]
Hello @nightfury1103, I'm sorry you are having problems, though sadly I do not recognise any tracks tooling or exercise on that screenshot, can you perhaps tell us more about what track you are doing and what exercise, such that we can ping the correct team to help you further?

**Comment by nightfury1103** [comment]
I'm in exercise 1 python language :(
![image](https://user-images.githubusercontent.com/61180080/117539207-d5b28800-b033-11eb-8fde-df8cd410fa1d.png)

**Comment by NobbZ** [comment]
I am not aware of any exercise that would ask to rewrite words or sentences to the NATO alphabet.

Usually the first exercise in the python track is `hello-world` which just asks for returning a static string `"Hello, World!"`.

PS: The newest image you attached looked a bit familiar, and I found exercise and design on another, more competitive, "rank up your coding skills" webpage. If you have problems with their exercises, you will need to reach out for their support. Exercism.io is not related to that other website.

**Comment by iHiD** [comment]
@nightfury1103 For this, if you can't work out how to solve it, then that in itself is useful for the purposes of the research, so it's probably best not addressed via support and then "artificially" solved. So I'm going to close this one :)
