### ISSUE TITLE
I have a technical problem with one of the test file in the "Sieve" side exercise

### ISSUE THREAD

**Issue by highspeedsteel** [exercism/exercism#5529]
From some reason the "SieveTests.cs" give me errors despite the fact that my code works fine in another project, the file gives me the following errors: 
"SieveTests.Limit_is_prime [FAIL]
SieveTests.Find_first_prime [FAIL]
SieveTests.Find_primes_up_to_10 [FAIL]" and tell me :
"SieveTests.Find_first_prime [4ms] Error Message: Assert.Equal() Failure Expected: Int32[] [2] Actual: Int32[] [2, 3, 5, 7, 11, ...]"
"SieveTests.Limit_is_prime [7ms] Error Message: Assert.Equal() Failure Expected: Int32[] [2, 3, 5, 7, 11, ...] Actual: Int32[] [2, 3, 5, 7, 11, ...]"
"SieveTests.Find_primes_up_to_10 [6ms] Error Message: Assert.Equal() Failure Expected: Int32[] [2, 3, 5, 7] Actual: Int32[] [2, 3, 5, 7, 11, ...]"

but when I copy past the same code into a different project and test the Primes function I get an array of 2,3,5,7 when the argument is 10, array of 2,3,5,7,11,13 when the argument is 13 and array with only the number 2 when the argument is 2 and this is exactly what the SieveTests.cs file expect. what is going on here?

**Comment by iHiD** [comment]
(cc @exercism/csharp)

**Comment by highspeedsteel** [comment]
> 
> 
> (cc @exercism/csharp)

the link doesn't work. am I supposed to post my question somewhere else?

**Comment by highspeedsteel** [comment]
weird thing I just discovered, when I put "(Skip = "Remove this Skip property to run this test")" in some of the tests it affects the results of unskipped tests without me changing anything in my code. when I skip Find_primes_up_to_1000() and Find_first_prime() my code pass the Limit_is_prime() test despite the fact that my code failed this test earlier. and when I add a skip to the Limit_is_prime() test my code pass the Find_primes_up_to_10() test. but when I remove the skips my code get errors again. 
someone know what is going on here?

**Comment by iHiD** [comment]
> the link doesn't work. am I supposed to post my question somewhere else?

No I'm cc'ing the csharp team into this issue for you :) 

It will probably help if you post your code so they can see what you're doing here.

**Comment by NobbZ** [comment]
Even though I do not do C# very much, but this really sounds like races are happening.

Are you perhaps relying on some shared mutable global state?

Though as iHiD sayd, its probably best to see your code to help you further, alternatively you can also submit it as is and provide a comment in the exercise that its not working and you are seeking for help with it.

**Comment by highspeedsteel** [comment]
> 
> 
> Even though I do not do C# very much, but this really sounds like races are happening.
> 
> Are you perhaps relying on some shared mutable global state?
> 
> Though as iHiD sayd, its probably best to see your code to help you further, alternatively you can also submit it as is and provide a comment in the exercise that its not working and you are seeking for help with it.

yeah this is what happened to me. I forgot the whole class is static and doesn't start as new for each test
