### ISSUE TITLE
Test suite report attached to all community solutions on website

### ISSUE THREAD

**Issue by ridhwaans** [exercism/exercism#5532]
I'm not sure why such vital information is missing on community solutions across all languages, track exercises.  

When I submit a solution, all the test cases are passed before publishing (no skip). I've seen many community solutions, and while they show the code implementation of which test suite was used, most of the ones I've checked dont pass all the test cases.   

Every exercism provides a test suite to a problem, it would be good if there is a report section showing on the code page about what passed and what failed.

**Comment by iHiD** [comment]
> I'm not sure why such vital information is missing on community solutions across all languages, track exercises.

Because we don't run students' tests :)

> most of the ones I've checked dont pass all the test cases.

That's mostly because the exercises have evolved. They will have passed the tests at the time.

---

In v3, we do run students' code and we will show the results.
