### ISSUE TITLE
 after installation of exercism my Code::Blocks ide suddenly generates errors on code that was fine before

### ISSUE THREAD

**Issue by mientje** [exercism/exercism#5534]
Hi,

Your platform is irresistible, I had to join.I'm quite the beginner in c++ and have also started the C++ for total beginners course. I do the exercises in code::blocks and copy the teacher's examples exactly. Everything worked fine until I installed exercism and now I have errors like this :  ‘Person::name’ should be initialized in the member initialization list [-Werror=effc++]| 
Is it possible that setting up exercism has somehow changed settings in my pc so that I'm getting these EMs and what can I do about it? 
The teacher explains what initialization lists are but it's annoying.  (He builds up his examples slowly step by step.  It's nice to see different versions  and stages of the same program.  
I have tried to adjust the settings,to follow c++11 , c++14 and so on, nothing helps). It's using the GNU GCC compiler and I'm working with ubuntu.   
Congratulations on this wonderful resource. The idea of allowing me to look at other people's code is simple and BRILLIANT! (though intimidating, I still have a long way to go)

Thank you and greetings
Karin Meersman
![Schermafdruk van 2021-05-14 21-26-26](https://user-images.githubusercontent.com/12875213/118319464-1c542680-b4fb-11eb-97bc-0d13b802de93.png)

**Comment by mientje** [comment]
Hi,

Something was altered but I've got used to it by now. I think I had a panic attack. That happens to me sometimes. I can work and I'm enjoying the exercises very much. So, just close this one, I'm sure there are more urgent matters than this one.

**Comment by iHiD** [comment]
Hi Karin. Sorry no-one answered, and thanks for the kind message. Exercism won't have broken your IDE at all (it doesn't install anything into it). The errors look quite "normal" - ie they're errors from errors in code, rather than signifying anything is broken. Glad things are working now, and thanks again for your kind words :)
