### ISSUE TITLE
Unable to download exercises

### ISSUE THREAD

**Issue by benjcabalona1029** [exercism/exercism#5535]
I have already runned 

```bash
sudo /snap/exercism/5/exercism configure --token=MYTOKEN
```
But i still get the error 

```
Error: 

    Welcome to Exercism!

    To get started, you need to configure the tool with your API token.
    Find your token at

        https://exercism.io/my/settings

    Then run the configure command:

        /snap/exercism/5/exercism configure --token=YOUR_TOKEN
```

I tried rebooting my machine but it's still not working. 

I've also checked  `~/.config/exercism/user.json` and my details are already there.

**Comment by iHiD** [comment]
I'm not sure you should be using `sudo`. I imagine that will look for credentials in the wrong place. @NobbZ ?

**Comment by NobbZ** [comment]
@iHiD: 

No, using `sudo` shouldn't be necessary, though this is one of the problems that gets reported 2 or 3 times a week in the gitter and we are usually suggesting manual installation as a fix there.

Please also see exercism/cli#973

---

@benjcabalona1029 please remove the snap and try again using manual installation, that usually works without all those problems.

**Comment by benjcabalona1029** [comment]
I tried running with or without sudo but it doesn't seem to fix it. I'll try to do manual install. Thanks.

**Comment by tlowrimore** [comment]
I am running into the same issue.  I have configured the API token, per the instructions provided in the `exercism download` error message.  If it helps, here is the `exercism troubleshoot` output for my environment:

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/tim/snap/exercism/5
Workspace: /home/tim/snap/exercism/5/exercism (default)
Config:    /home/tim/snap/exercism/5/.config/exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 79.265897ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 706.62227ms
```

**Comment by NobbZ** [comment]
The easiest solution is probably to remove the snap installed version of exercism, and removing the config file from `/home/tim/snap/exercism/5/.config/exercism` to make sure that it doesn't confuse future installations.

Then use the manual installation method to re-install `exercism`.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by kenjitamura** [comment]
Hello!  This issue is still present for me in V3, could we get this reopened?

Here's my troubleshoot:

```
 /snap/exercism/5/exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/adam
Workspace: /home/adam/exercism
Config:    /home/adam/.config/exercism
API key:   df99*****************************4a8

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 67.6843ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 385.970247ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

I noticed these are the permissions for the snap:
```
snap connections exercism
Interface        Plug                      Slot      Notes
home             exercism:home             :home     -
network          exercism:network          :network  -
removable-media  exercism:removable-media  -         -
```
The home interface does not support snap access to hidden directories.

Is it possible the published Snap's yaml needs the personal-files interface added for ~/.config/exercism to become accessible to the snap?
[https://forum.snapcraft.io/t/the-personal-files-interface/9357](url)

**Comment by NobbZ** [comment]
As said earlier, the easiest way to solve is to remove the snap and all of its configuration, then install manually.

Alternatively, use the online editor which is now available since September 2021.

**Comment by kamil-korczak** [comment]
> I have already runned
> 
> ```shell
> sudo /snap/exercism/5/exercism configure --token=MYTOKEN
> ```
> 
> But i still get the error
> 
> ```
> Error: 
> 
>     Welcome to Exercism!
> 
>     To get started, you need to configure the tool with your API token.
>     Find your token at
> 
>         https://exercism.io/my/settings
> 
>     Then run the configure command:
> 
>         /snap/exercism/5/exercism configure --token=YOUR_TOKEN
> ```
> 
> I tried rebooting my machine but it's still not working.
> 
> I've also checked `~/.config/exercism/user.json` and my details are already there.

If you downloaded installed it as SNAP.. you can't use this command
```
 sudo /snap/exercism/5/exercism configure --token=MYTOKEN
```

Use this instead:
```
exercism configure --token=MYTOKEN
```

For me it worked. And also don't add `sudo` before *exercism* while trying download exercise, somehow it doesn't work as well.
