### ISSUE TITLE
Mentor request disabled

### ISSUE THREAD

**Issue by stevensonmt** [exercism/exercism#5536]
I would like to request some feedback on a particular exercise but I'm seeing this on the website:
>Request mentor feedback (disabled). Mentoring is disabled by default in Practice Mode. However, you can request feedback on a maximum of one solution at a time. You currently have no slots free. 

I can't remember the last time I requested mentoring but it must have been quite a long time ago. Is there any way to find out which exercise is pending mentoring and remove that request from the queue?

**Comment by iHiD** [comment]
No-where to check on the current site. But take a look at elixir/nth-prime :)

**Comment by stevensonmt** [comment]
I had forgotten that. Anyway to clear that request as it has been so long?

**Comment by iHiD** [comment]
I think there's a cancel button? If not, send me a screenshot and the uuid of the exercise, and I can do it manually.

**Comment by stevensonmt** [comment]
Can't find a cancel button:

![image](https://user-images.githubusercontent.com/8891908/118416744-f5663380-b665-11eb-90ac-f1376b6ed088.png)

**Comment by stevensonmt** [comment]
I am not sure about the UUID. is that in the URL for the exercise?

**Comment by iHiD** [comment]
If you paste me the UUID from the browser's URL bar, I'll do it :)

**Comment by stevensonmt** [comment]
I believe it's this: 214a80010197458a90924f25f7a5a1c2

**Comment by iHiD** [comment]
How's that now?

**Comment by stevensonmt** [comment]
Awesome. Thank you so much!
