### ISSUE TITLE
Can I see Ruby, Python exercises without installing exercism?

### ISSUE THREAD

**Issue by thelmalu** [exercism/exercism#5540]
I would like try a few exercises in Ruby and Python. These would simply be amusements to stave off the terminal boredom I'm feeling at age 80. Since I'm not seeking efficiency, clean code, mentoring, etc., is there some way that I could just see the data base of exercises without the long, complex install of exercism?  (I have working installations of Python and Ruby on my iMac)

**Comment by iHiD** [comment]
> without the long, complex install of exercism

- If you have Homebrew, you only need to run one command to install Exercism. 
- If you don't, you can simply download the file manually and use it. Choose from the [list here](https://github.com/exercism/cli/releases/tag/v3.0.13) (probably mac 64bit for you?), download the zip, unzip it, then run the exercism command from your CLI.

If you don't want to do that, you can access the exercises at https://github.com/exercism/ruby/tree/main/exercises/practice or https://github.com/exercism/python/tree/main/exercises/practice etc.
