### ISSUE TITLE
JavaScript track solution is not reviewed from mentor even after 24 hours, info section says 6 hours waiting time

### ISSUE THREAD

**Issue by vikramvi** [exercism/exercism#5542]
Dear Team,

I've started with _JavaScript track_ and yesterday IST morning had submitted answer for review.
The info section says approximate wait time is 6 hours but even after 24 hours, I didn't hear back from mentor.

Can you please look into this ?

Thanks for this awesome platform.

Best,
Vikram

<img width="1440" alt="Screen Shot 2021-05-27 at 10 51 12 AM" src="https://user-images.githubusercontent.com/308490/119770182-80062880-bed9-11eb-9d54-434e78fd88a0.png">

**Comment by vikramvi** [comment]
Dear Team,

First of all apologies for complaining again.

But your review estimate timing seems to be totally wrong, as in my case 2nd case even after 36 hours there is not update on below solution

Kindly get the estimation timing issue fixed

<img width="1438" alt="Screen Shot 2021-05-29 at 12 07 56 PM" src="https://user-images.githubusercontent.com/308490/120060667-add4a400-c076-11eb-8168-6d8520b03d48.png">

**Comment by iHiD** [comment]
Hello. There's not an estimate, there's a median wait time calculated over the last month, which is correct.

**Comment by vikramvi** [comment]
Thanks for clarification but it doesn't seem to be matching with actual reply time. 
Can you please check 2 screenshots attached in this ticket ?

**Comment by hunkyjimpjorps** [comment]
All the solutions are reviewed by volunteers, so the median time may be right but there could be extenuating circumstances causing longer review times now.  For example, it's a three-day holiday weekend in the United States as of this comment.

**Comment by iHiD** [comment]
As @hunkyjimpjorps says, things affect these things, which is why we list the median time, not any sort of estimate. A median time of 6hrs over a month might mean 1000 have been mentored in 10 days, but 1002 have been mentored in 6 hours.

**Comment by vikramvi** [comment]
Thanks for clarification, hopefully I will as well join as mentor in few quarters.

**Comment by iHiD** [comment]
@vikramvi Thanks :) 

Also, in case you missed these videos, they explain about the wait and the changes we're making: 
- https://www.youtube.com/watch?v=XiV_vYn1Ea8&
- https://www.youtube.com/watch?v=5Cj1Dr9m3GM&ab_channel=ExercismExercism
