### ISSUE TITLE
Sign up with Github fail

### ISSUE THREAD

**Issue by OrdinaryYZH** [exercism/exercism#5554]
![image](https://user-images.githubusercontent.com/10287222/120884507-24911480-c616-11eb-962e-b31d2fae9c46.png)

I tried revoke Exercism in Github, but not work :-(

**Comment by iHiD** [comment]
Hi. It's likely you have an unverified email address on GitHub, which causes GitHub to blow up during auth.

**Comment by OrdinaryYZH** [comment]
> Hi. It's likely you have an unverified email address on GitHub, which causes GitHub to blow up during auth.

Oh yes,  thank you very much :-)
