### ISSUE TITLE
Python track Twelve Days : not enough information about the question.

### ISSUE THREAD

**Issue by F4R4N** [exercism/exercism#5558]
I believe there is not enough information in the README.md file for `Twelve Days` challenge in the python track.

**Comment by iHiD** [comment]
You'll need to give us some more information on what is unclear :)

**Comment by F4R4N** [comment]
It only provides the output of the lyrics. no information about what should we do.
was that on purpose? to go and try to find the question from the test file?

**Comment by iHiD** [comment]
It should say "Output the lyrics to 'The Twelve Days of Christmas'." and then gives the lyrics. That's the entirety of the task - how you choose to solve it is up to you :)

In terms of the actual interface to pass the tests, yes, for most exercises you need to check the test files to understand exactly what is required.

**Comment by F4R4N** [comment]
ok, thanks. :+1: 
I guess I didn't understand the logic of solving the problems in exercism.
