### ISSUE TITLE
F# track one month without mentor feedback

### ISSUE THREAD

**Issue by chadnt** [exercism/exercism#5559]
Exercism team,

Thank you for your hard work on this site. I'm a bit reluctant to report an issue here, but the guides I have found seem to indicate this is the place.

Submitted an [exercise on the F# track](https://exercism.io/my/solutions/d4f5b8a63ad24cb1ba78cffbdcee719d) on May 13, 2021 which has not yet received any feedback almost one month later. A banner near the top of the page does say "A mentor will leave you feedback as soon as possible." A card on right indicates "There are currently 2 solutions ahead of this in the F# queue...", my recollection is this has not changed for the past month, but I can't really confirm that.

The indications appear to suggest that there are no active mentors in the F# queue for the past month, which I can understand. I'm grateful for the feedback I have gotten. I understand the mentoring aspect depends on volunteers. Figured I'd open this issue just to make sure something had not gone wrong technically causing my submission to be lost.

**Comment by iHiD** [comment]
Thanks. I'll ask on our mentor's slack for you :)

**Comment by chadnt** [comment]
Big thanks to @ErikSchierboom for reviewing and approving my submission. Thank you for the support. I will close this issue.
