### ISSUE TITLE
Mentor needed on c# track

### ISSUE THREAD

**Issue by sven-dibowski** [exercism/exercism#5562]
Hello, i wait for montoring in c# track since weeks.

Exercise: Allergies (2 in this que)

**Comment by neenjaw** [comment]
Hi @sven-dibowski, the mentors are all volunteers.  I would assume if the mentors haven't been able to take up your request for mentoring it is likely that life circumstances have interfered.  The next version of exercism is ~60 days away (countdown.exercism.io) and will help to mitigate your feelings of being blocked by an absent mentor. In the meantime, you can either keep waiting, or complete the exercise without mentor approval to move on. :)
