### ISSUE TITLE
Unable to download exercises

### ISSUE THREAD

**Issue by Montjoie75** [exercism/exercism#5563]
Hello,
i have installed exercism using snap (Linux Mint). After running "sudo/snap/exercism/5/exercism configure --token=MYTOKEN", I have tried to download one exercise and I get the following response in my console : " downloaded to /home/XXX/snap/exercism/5/exercism/javascript/pangram", only the file named 5 still remains empty afterwards.
Can you help ? 
I am very new to this...
Thanks !
Oletta

**Comment by Montjoie75** [comment]
Good morning. Everything is solved now.
Many thanks.
Oletta

**Comment by iHiD** [comment]
Great :)
