### ISSUE TITLE
Where is the link to solutions?

### ISSUE THREAD

**Issue by kebiro** [exercism/exercism#5568]
I'm just doing practice mode, downloading the task and doing the exercise until I'm satisfied with the results. I'm not actually submitting them.

I like to compare mine to others to see what I could have done better or different, but to find the solution page I have to google something like "Exercism *Prog Lang* Solutions *Exercise Name*". Tbh having to do that is cumbersome.

I just cannot find the solutions' link on the webpage. Where is it?

**Comment by iHiD** [comment]
You get the link once you submit them. If you don't submit them, you won't get the link :)

**Comment by kebiro** [comment]
Is that really necessary though? Because clearly I have a way to get to the solutions, and it's not as if I gain anything from peeking into the solutions before doing it on my own. I think you could just put a link somewhere and let people decide whether they want to peek or not. At least in practice mode I don't see any harm in doing so.

Anyway, thanks for the quick response. At least I know now.

**Comment by iHiD** [comment]
Yeah. The website is designed to flow in a certain way. If you choose not to use it in the way its designed to flow then certain things won't show up as they're not intended to be seen at that stage.

**Comment by iago-lito** [comment]
Is this something being currently reconsidered for v3 btw?
(just curious uh, I like the idea of not looking at community solutions before I submit :)

**Comment by iHiD** [comment]
Nope :)
