### ISSUE TITLE
Cannot Submit, Error message: zsh: command not found: exercism

### ISSUE THREAD

**Issue by Quando-Alia-Agetur** [exercism/exercism#5570]
I just finished the "Hello World" Javascript exercise. My test was successful. I went to submit. I am in the proper directory, but I get the error message: zsh: command not found: exercism. Below is what I'm seeing on the command line:

```
dude@Dudes-MacBook-Pro hello-world % exercism submit hello-world.js
zsh: command not found: exercism
```

I have looked through other issues in both this board and the cli one, but no solutions work. Halp pls.

**Comment by Quando-Alia-Agetur** [comment]
I have found the solution: https://www.itech4mac.net/homebrew-tutorials/how-to-fix-zsh-command-not-found-brew-on-macbook-m1-silicon-devices

Relocating homebrew to its correct location also did the same for the Exercism files and folders. So now finally everything is working and I just submitted the exercise.

**Comment by iHiD** [comment]
Thanks for sharing your solution!
