### ISSUE TITLE
How can I see other's solutions to my current project?

### ISSUE THREAD

**Issue by CyanCoding** [exercism/exercism#5576]
I'm new to the Go language, so I'm working through the projects as best as I can. However, on one of my projects I'm stuck and want to see where I can correct my code. The estimated wait time is 4 days for a mentor, so obviously I don't want to wait that long.

At the bottom of the project page it says "**Submitting Incomplete Solutions:** It's possible to submit an incomplete solution so you can see how others have completed the exercise."

I did this, but I see no way to see other's solutions or interact with anyone besides mentors on the site. I just want to see how other people solved the problem so I can correct my code and learn. Where is this functionality?

**Comment by angelikatyborska** [comment]
@CyanCoding Is this a core exercise? For core exercises, mentor approval is necessary, and that postpones the ability to see the button "see community solutions". For non-core exercises, you should see that button after submitting a solution.

Anyway, even if the button is absent, you can always construct the URL to community solutions yourself. If you're sure that you really want to see them before talking with the mentor.

Here's an example URL: `https://exercism.io/tracks/go/exercises/raindrops/solutions`

Exchange the exercise name `raindrops` with something else 🙂

**Comment by bigbassroller** [comment]
@angelikatyborska so there is no way NOT to be able to see the solution before completing? The temptation is strong when stuck.

**Comment by angelikatyborska** [comment]
@bigbassroller the website tries to make it easy not to be able to see the solution before completing by not giving you any links, but in general it's impossible to completely prevent you from doing it. There are other sources of solutions for Exercism exercises. Every track needs to have a proof for every exercise that it is solvable and you can find it on GitHub. There are countless blog posts and streams where people solve specific exercises and talk about that. Real secrecy around solutions wouldn't be possible anyway 🙂

**Comment by glennj** [comment]
I view the library of community solutions as one of Exercism's greatest assets. I found them tremendous learning resources while I was working through tracks. I would have been very sad indeed if I was prevented from seeing them.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
