### ISSUE TITLE
Unable to see exercises in practice mode

### ISSUE THREAD

**Issue by AntonioCS** [exercism/exercism#5577]
Hey,

I've switched to practice mode as I am tired of waiting for a mentor to give his approval. I'm interested in doing something with C++ and move on to the next issue, waiting more than 48h for feedback on the Space Age problem is not reasonable for me.

So in practice mode I can see all exercises but then when I try to go to the "Triangle" exercise (which was next in the other mode) I get this:

![image](https://user-images.githubusercontent.com/1086401/124712059-be3e3100-def6-11eb-9132-f4c88ea93c86.png)

Why am I not seeing the exercise??? Some of the other exercises I can see and others I get the above output...
I just want to go through these exercises... that is it..

**Comment by iHiD** [comment]
You'll looking at a page/view of your completed solutions there (as you can see by the title).

**Comment by AntonioCS** [comment]
@iHiD then I'm redirected to that page because I am here:
![image](https://user-images.githubusercontent.com/1086401/124764757-34f62100-df2d-11eb-9e73-84061dbf7d15.png)
If I press the Gigasecond I can see this:
![image](https://user-images.githubusercontent.com/1086401/124764828-4808f100-df2d-11eb-85cb-7839cce3ef8c.png)
Now if I press Anagram (which is just below gigasecond) I get this:
![image](https://user-images.githubusercontent.com/1086401/124764926-640c9280-df2d-11eb-90de-b5929650924a.png)
How does this make sense???????

**Comment by iHiD** [comment]
Don't middle Anagram, just click on it normally.

**Comment by AntonioCS** [comment]
:confused:

**Comment by iHiD** [comment]
You're welcome.

**Comment by AntonioCS** [comment]
Yes... sorry... thank you for making something insane like this where a right click provides different output ON SOME of the exercises... yes.. thanks!!!

**Comment by AntonioCS** [comment]
Stuff like this just takes away any motivation to do the exercises... such a ridiculous programming flaw on something that is evaluating my programming skills...

**Comment by SleeplessByte** [comment]
Hi again,

No one is contesting that it's not the optimal behaviour, but the way that it does work as expected has been provided. As far as I can tell, this implementation and behaviour is absent in the major upgrade coming to you live in 55 days ([https://countdown.exercism.io/](https://countdown.exercism.io/)). 

Luckily enough, the website isn't written in C++, so any perceived incompetence shouldn't affect your track. If you do find flaws in the C++ track, the maintainers are happy to receive constructive feedback at [https://github.com/exercism/cpp](https://github.com/exercism/cpp).

Have fun learning C++!
