### ISSUE TITLE
error: type nullability specifier '_Nullable' is a Clang extension is blocking my tests

### ISSUE THREAD

**Issue by derboturbo** [exercism/exercism#5578]
I'm on the c path, but I cannot seem to run tests due to the errors I'm getting below.  I've been trying to figure out what's wrong with my machine that is causing this. I've even reached out to the CTO of my company and he is stumped.  

Any help is greatly appreciated.

`Compiling tests.out
In file included from test/vendor/unity.c:7:
In file included from test/vendor/unity.h:21:
In file included from test/vendor/unity_internals.h:257:
In file included from /usr/local/include/stdio.h:64:
/usr/local/include/_stdio.h:137:9: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
        int     (* _Nullable _close)(void *);
                   ^
/usr/local/include/_stdio.h:138:9: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
        int     (* _Nullable _read) (void *, char *, int);
                   ^
/usr/local/include/_stdio.h:139:12: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                   ^
/usr/local/include/_stdio.h:140:9: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
        int     (* _Nullable _write)(void *, const char *, int);
                   ^
In file included from test/vendor/unity.c:7:
In file included from test/vendor/unity.h:21:
In file included from test/vendor/unity_internals.h:257:
/usr/local/include/stdio.h:385:25: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
                 int (* _Nullable)(void *, char *, int),
                        ^
/usr/local/include/stdio.h:386:25: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
                 int (* _Nullable)(void *, const char *, int),
                        ^
/usr/local/include/stdio.h:387:28: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
                 fpos_t (* _Nullable)(void *, fpos_t, int),
                           ^
/usr/local/include/stdio.h:388:25: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
                 int (* _Nullable)(void *));
                        ^
8 errors generated.
In file included from test/test_hello_world.c:2:
In file included from test/vendor/unity.h:21:
In file included from test/vendor/unity_internals.h:257:
In file included from /usr/local/include/stdio.h:64:
/usr/local/include/_stdio.h:137:9: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
        int     (* _Nullable _close)(void *);
                   ^
/usr/local/include/_stdio.h:138:9: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
        int     (* _Nullable _read) (void *, char *, int);
                   ^
/usr/local/include/_stdio.h:139:12: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                   ^
/usr/local/include/_stdio.h:140:9: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
        int     (* _Nullable _write)(void *, const char *, int);
                   ^
In file included from test/test_hello_world.c:2:
In file included from test/vendor/unity.h:21:
In file included from test/vendor/unity_internals.h:257:
/usr/local/include/stdio.h:385:25: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
                 int (* _Nullable)(void *, char *, int),
                        ^
/usr/local/include/stdio.h:386:25: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
                 int (* _Nullable)(void *, const char *, int),
                        ^
/usr/local/include/stdio.h:387:28: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
                 fpos_t (* _Nullable)(void *, fpos_t, int),
                           ^
/usr/local/include/stdio.h:388:25: error: type nullability specifier '_Nullable' is a Clang extension [-Werror,-Wnullability-extension]
                 int (* _Nullable)(void *));
                        ^
8 errors generated.
make: *** [tests.out] Error 1`

**Comment by SleeplessByte** [comment]
cc @exercism/c

**Comment by ryanplusplus** [comment]
What platform? What compiler? What command are you running to compile and run the tests?

**Comment by derboturbo** [comment]
Actually, I was able to fix this by removing my /usr/local/include folder, uninstalling brew gcc and uninstalling/reinstalling Xcode command line tools. 

I think there was a conflict between brew gcc and Xcode command line tools.  My issue is fixed now and this can be closed.
