### ISSUE TITLE
Gradle build Failure

### ISSUE THREAD

**Issue by ihocher** [exercism/exercism#5585]
Hello everyone!
I have a problem with starting text bellow.
Can anybody help me fix it?

Thank you in advance.

C:\Users\Blueberry\Exercism\java\hello-world>gradle test
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Blueberry\Exercism\java\hello-world\build.gradle'

* What went wrong:
Could not compile build file 'C:\Users\Blueberry\Exercism\java\hello-world\build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60

**Comment by iHiD** [comment]
This is possibly related to https://github.com/exercism/java/issues/1944 ?

**Comment by SleeplessByte** [comment]
It's likely the same issue, yes :)

> This is possibly related to [exercism/java#1944](https://github.com/exercism/java/issues/1944) ?

**Comment by ihocher** [comment]
I've fixed it with change of jdk for older version (16->8)
Thank you for help.
