### ISSUE TITLE
long median time ofr mentor response // --exercise=matrix --track=javascript

### ISSUE THREAD

**Issue by dk1code** [exercism/exercism#5586]
After submitting my working solution for the mentioned exercise, GUI states:

 "There are currently 155 solutions ahead of this in the JavaScript queue, and 64 ahead in the Matrix queue. The median waiting time for mentoring on this exercise is 2 months."

I understand, that this is volunteer work and I am grateful for having the opportunity to be mentored. But I worry, that I might be stuck on this exercise for a while. Can anybody at least approve the exercise for me, so I don't lose the side exercises (which I lose, when switching to practice mode for just this exercise, right)?

My URI to my solution:
https://exercism.io/my/solutions/9d0b518986884fd2a748fb06c1e66dfa

**Comment by iHiD** [comment]
In v3 (launching in 41 days) approving is removed, so this won't be an issue. I've approved 🙂

**Comment by SleeplessByte** [comment]
Mark the date! [https://countdown.exercism.io/](https://countdown.exercism.io/)
