### ISSUE TITLE
New language request: vlang.io

### ISSUE THREAD

**Issue by Zhomart** [exercism/exercism#5589]
https://vlang.io/ is a new, fun, and fast experimental language. It's inspired by Rust, Go, Python and many others. I would love to train solving problems using V on exercism.

**Comment by Zhomart** [comment]
Creating issue here: https://github.com/exercism/request-new-language-track/issues/new

**Comment by angelikatyborska** [comment]
Looks like somebody already did a year ago: https://github.com/exercism/request-new-language-track/issues/74

**Comment by iHiD** [comment]
@Zhomart if you'd like to lead development on this language, please post a comment on exercism/request-new-language-track#74
