### ISSUE TITLE
No mentors available?

### ISSUE THREAD

**Issue by mikemaer1990** [exercism/exercism#5590]
Hey, I've been waiting two weeks for a mentor to review a solution of mine on the Javascript track.

Has everyone disappeared until the next version is released in September?

**Comment by SleeplessByte** [comment]
It depends on the exercise too. Which one is it and can you post the link?

**Comment by mikemaer1990** [comment]
It's Gigasecond in Javascript -- https://exercism.io/my/tracks/javascript#exercise-gigasecond

**Comment by iHiD** [comment]
@mikemaer1990 I think @SleeplessByte meant the link to your personal solution that needs mentoring :)

**Comment by mikemaer1990** [comment]
Oops haha, [here](https://exercism.io/my/solutions/b00334d6b3a947bebd908cb735b4a007)

**Comment by SleeplessByte** [comment]
Given that you've received feedback, I'm going to close this issue :)
