### ISSUE TITLE
Question: how version update will impact current tracks?

### ISSUE THREAD

**Issue by lguilhermers** [exercism/exercism#5592]
Hi,

First thanks for the amazing idea of Exercism and the community you created to help people to code.
I am almost finishing a track, so I want to know if  this new version will impact in any way the current tracks we have for the exercises and its progress? 
Or will it be more related to changes in interface and mentoring dynamics?

**Comment by angelikatyborska** [comment]
The new version is going to add a new type of exercise, a learning exercise, and change how practice exercises are unlocked. There will be no more "core" practice exercises and "side" practice exercises. All practice exercises will now be unlocked by doing learning exercises.

Some tracks didn't create any learning exercises at all. For those, all practice exercises will be unlocked as soon as you join the track. Other tracks created a lot (30-40) new learning exercises and you might need to solve them all before you gain access to all practice exercise.

Regardless, you can be sure that you will NOT lose your progress. All practice exercises that you already solved will be unlocked to you in the new version so you can continue improving them. You will then have the choice to either do the learning exercises to unlock the rest, or you can opt out of learning exercises completely and immediately unlock all practice exercises by activating "practice mode" (similar to "independent mode" now).

**Comment by SleeplessByte** [comment]
Which track are you finishing @lguilhermers ?

**Comment by lguilhermers** [comment]
Thanks for the reply and the overview, guys.
@SleeplessByte I am finishing the python track, just missing one exercise (going on a feedback round before that).

Would be great to finish in the current format, since I was working on it for around 1 year and looking at the finish line already.
But I understand in terms of knowledge acquired it doesn't make sense and it would be just more like a personal milestone.

**Comment by lguilhermers** [comment]
@SleeplessByte any chance I can start working on the last exercise (book store)? I am doing a feedback round which assume to be almost ending, but would be good if I can start working on the final one and maybe even get feedback for it before September 1st. I would just need the instructions and files (specially the test one). Thanks again!

**Comment by angelikatyborska** [comment]
@lguilhermers if you want to "work around" the platform and start working on an exercise early outside of the platform, I wouldn't recommend that, but there's always a way. You can find all Python exercises in https://github.com/exercism/python/ the practice exercises are in `exercises/practice`. Don't peak into `.meta/example.py` in the exercise directory or you will ruin the fun of solving the exercise on your own 🙂.

Note that the platform will be taken offline a week before September 1st, so you have even less time 😅.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
