### ISSUE TITLE
Problems with submiting solutions

### ISSUE THREAD

**Issue by DiskoSquid** [exercism/exercism#5593]
I have submitted my solution to the python track, exercise Raindrops and in the terminal i have no problems, it is accepted.
But on the exercism site it is not registered that i have submitted the solution.
Any help please?

Terminal response when i submited:
    Your solution has been submitted successfully.
    View it at:

    
    https://exercism.io/my/solutions/40e341e695cf4205baff1f4f1d551e0f

**Comment by angelikatyborska** [comment]
>  But on the exercism site it is not registered that i have submitted the solution.

Can you describe exactly what you see when you visit the URL `https://exercism.io/my/solutions/40e341e695cf4205baff1f4f1d551e0f`? Maybe you could provide a screenshot. That could help us debug the issue together.

**Comment by DiskoSquid** [comment]
Dear Angelikatyborska,
thank you for your help on this matter but the paige just had problems with refreshing its content. It changed after 30 minutes.
Sry for the inconvenience and thanks ounce again.
