### ISSUE TITLE
stuck on track waiting for exercise approval

### ISSUE THREAD

**Issue by dk1code** [exercism/exercism#5594]
Hi everyone!
Can somebody please approve my exercise. Wasn't on exercism for a while now and it's still queued. Cheers!

https://exercism.io/my/solutions/084e58addea7476887abfdde2d04729c

**Comment by SleeplessByte** [comment]
It seems that 18 hours ago you've been reviewed, with another review likely happening soon.

FYI: when you leave Exercism, all solutions get "dequeued", but then requeue when you come back.
