### ISSUE TITLE
Wren track does not show up

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5607]
The new Wren track doesn't seem to be showing, but it is enabled and was showing up fine on `.lol`.

**Comment by angelikatyborska** [comment]
This has been fixed and can be closed

**Comment by angelikatyborska** [comment]
Although... maybe not fully? The track has been configured to have a test runner but I'm seeing this:

![Screenshot 2021-09-01 at 19-01-30 Exercism](https://user-images.githubusercontent.com/7852553/131716034-06d0700a-052b-4145-94e0-ffcb2e8d37cc.png)

Could be related to https://github.com/exercism/exercism/issues/5619

**Comment by iHiD** [comment]
Opened the bug for this here: https://github.com/exercism/exercism/issues/5638

I've also tried to update wren. Could you confirm it works now pls and if so close this?

**Comment by joshgoebel** [comment]
Wren track is showing up now.

**Comment by iHiD** [comment]
Have those disabled buttons become enabled?
