### ISSUE TITLE
Cannot place the cursor in desired location when editing a mentoring comment

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5609]
Regardless of where I click, the cursor ends up at the end of the comment. See gif.

![2021-09-01 17 58 01](https://user-images.githubusercontent.com/7852553/131705181-9ba40c81-b774-4944-a90a-ea844871fd27.gif)

**Comment by joshgoebel** [comment]
Ditto on this one! :-)  Thanks for filing!

**Comment by kntsoriano** [comment]
Hi, @joshgoebel @angelikatyborska. We've merged a [fix for this](https://github.com/exercism/website/pull/1691).

Could you check this fixes the issue? If it still doesn't, please let me know how I could replicate the bug.

Thanks!

**Comment by joshgoebel** [comment]
Seems to work here.

**Comment by angelikatyborska** [comment]
Yes, this is fixed 🎉

**Comment by kntsoriano** [comment]
Thanks for checking!
