### ISSUE TITLE
Rendering solution preview: angle brackets

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#5610]
The solution previews (as shown on the published solutions page) seems to have a small problem where invalid html tags are stripped, but some languages like C use angle brackets:

An actual solution:
<img width="463" alt="solution actual" src="https://user-images.githubusercontent.com/122470/131705396-fceb86d4-2145-4d60-8a81-c1b29012ada5.png">

The solution preview:
<img width="463" alt="solution preview" src="https://user-images.githubusercontent.com/122470/131705448-80acdaf8-0d2a-46eb-aac2-5ebf2c5cbf63.png">

**Comment by joshgoebel** [comment]
Weird, highlight.js wouldn't do this... I think the content is getting stripped before it's given to us - which seems strange... we're quite able to properly HTML escape the highlighted code we generate - it doesn't need to be sanitized first.

**Comment by joshgoebel** [comment]
I assume they are colored by Highlight.js though... but yeah, it could be a bug in the snippet extractor too I suppose. :) So many moving pieces.

**Comment by angelikatyborska** [comment]
I'm pretty sure highlight.js is not to blame for this because the same solution looks good when you look at it in full, not just the snippet.

**Comment by angelikatyborska** [comment]
I double-checked and it's not the snippet extractor. It doesn't remove `<>`, they're still in the snippet. Something must we wrong with rendering this markup.

<img width="1680" alt="Screen Shot 2021-09-02 at 15 42 57" src="https://user-images.githubusercontent.com/7852553/131854713-6889dd75-3136-4127-bb4c-4155b3ce1a6d.png">

**Comment by glennj** [comment]
Perhaps this:
<img width="1764" alt="c darts" src="https://user-images.githubusercontent.com/122470/131859320-086b77e5-4fdb-4720-ad53-eb056713474a.png">

**Comment by SleeplessByte** [comment]
It's literally because it's not escaping html. 

@iHiD you'll want to add `h(the_snippet_content)` or do the same thing in React. Both would work.

**Comment by joshgoebel** [comment]
Ah, yes.  The HTML must be escaped properly or Highlight.js will simply remove it (which doesn't fix the problem, but forces people to become aware of such security issues - hopefully in dev).  Fix recommended by @SleeplessByte should work just fine.

**Comment by ErikSchierboom** [comment]
Should be fixed in https://github.com/exercism/website/pull/1737
