### ISSUE TITLE
Mentoring UI: download solution by uuid

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5611]
In v2, it was possible to copy a command to download a student's solution by uuid when mentoring. This is crucial, even when the test runners are there, because I need to be able to try out modifications to the code myself before suggesting them to the student.

It's not possible to comfortably copy-paste the solution from the editor because the output includes a lot of extra newlines.

I would need the same button in v3, or at the very least any way to find the uuid. I can assemble the command myself.

**Comment by dmaestro** [comment]
I prefer copying from the editor myself, and that's now broken as noted above. I would use the command line tool w/ uuid if I could control where it gets put in my filesystem.

**Comment by angelikatyborska** [comment]
@dmaestro The root path of where the solution gets downloaded is determined by the `workspace` value in the file `~/.config/exercism/user.json`. You can change it to whatever you want, but it will also affect where your own exercises get downloaded.

If you want more control, you could write youself a small shell function that moves the solution after downloading. For example

```bash
exercism-download-to() {
  local uuid=$1;
  local output=$(exercism download --uuid $uuid);
  echo $output;
  local dir=$(echo $output | sed 's/.*Downloaded to //');
  mv $dir $2;
}

# usage:
exercism-download-to uuid /some/path/
```

Note that I didn't test this function so it might be slightly wrong. I couldn't test it because downloading by uuid doesn't work 😅 but maybe you could use it the future.

I did test and use this function for many years to do mentoring of Elixir exericses:
```bash
exercism-download-and-test() {
  local uuid=$1;
  local output=$(exercism download --uuid $uuid);
  echo $output;
  local dir=$(echo $output | sed 's/.*Downloaded to //');
  cd $dir;
  mix test --include pending;
}
```

**Comment by taiyab** [comment]
Yea, the copy button didn't make it in too.

The intention is to add a copy function anywhere there is code preview (mentoring, community solutions, your own iteration previews, etc.)

Something like this might work (on hovering anywhere in the code window).

It might get a bit irritating behaviourally (when trying to maybe copy a bit of code from the top right), so it will need a bit of testing.

![image](https://user-images.githubusercontent.com/5337876/132007947-e5a93190-d2bc-467b-9071-41da80802bf1.png)
