### ISSUE TITLE
Constantly hitting bad gateway (502)

### ISSUE THREAD

**Issue by chris-free15** [exercism/exercism#5613]
First happened when I clicked start the track under Koltin. Refreshing then getting to the next page also caused this.

I have not tried any other tracks yet, so I'm unsure if this is just that track causing issues.

**Comment by FaisalAfroz** [comment]
Same with me. Also the v3 website appears sluggish.

**Comment by junedev** [comment]
@chris-free15 @FaisalAfroz Some (potential) fixes were applied to infrastructure. Do you still experience problems?

**Comment by lynnlangit** [comment]
Seems improved now (no 502s for awhile).  When the behavior was occurring, refreshing always 'fixed' the issue.

**Comment by FaisalAfroz** [comment]
I think it is working fine now. Not encountered a single 502 after that comment.

**Comment by iHiD** [comment]
We got hit by a lot more traffic (and a few fewer db indexes) than we had planned for. Sorry for the pain. Thanks for reporting :)
