### ISSUE TITLE
NoMethodError in Tracks::CommunitySolutions#show

### ISSUE THREAD

**Issue by siebenschlaefer** [exercism/exercism#5614]
https://exercism.org/tracks/go/exercises/queen-attack/solutions/srt32

```
Showing /opt/exercism/website/current/app/views/tracks/community_solutions/show.html.haml where line #80 raised:
undefined method `handle' for nil:NilClass
```

Let me know if you need more information.

**Comment by FaisalAfroz** [comment]
Same error occurred in C# track.
https://exercism.org/tracks/csharp/exercises/simple-cipher/solutions/bressain

**Comment by angelikatyborska** [comment]
I also have a question about that error page. Should it really be that detailed, with a stack trace and all? Wouldn't a web app running in production mode only show a very generic 500 error page?
