### ISSUE TITLE
Go concept exercises: go.mod is missing

### ISSUE THREAD

**Issue by siebenschlaefer** [exercism/exercism#5617]
When I download a concept exercise the file `go.mod` is missing.

```
$ exercism download --exercise=annalyns-infiltration --track=go

Downloaded to
/home/user/exercism/go/annalyns-infiltration

$ tree annalyns-infiltration
annalyns-infiltration
├── annalyns_infiltration.go
├── annalyns_infiltration_test.go
├── HELP.md
├── HINTS.md
└── README.md

0 directories, 5 files
```

But when I download a practice exercise, that file is present and I can start solving.
```
$ exercism download --exercise=tree-building --track=go

Downloaded to
/home/user/exercism/go/tree-building

$ tree tree-building
tree-building
├── go.mod
├── HELP.md
├── README.md
├── tree_building.go
└── tree_building_test.go

0 directories, 5 files
```

**Comment by angelikatyborska** [comment]
The file doesn't exist in that exercise: https://github.com/exercism/go/tree/main/exercises/concept/annalyns-infiltration

This issue should be moved to the repo https://github.com/exercism/go

**Comment by siebenschlaefer** [comment]
@angelikatyborska I don't think I have the rights to do that (or I just don't know how). Can you do it for me or should I close it and create a new one on that other repo?

**Comment by angelikatyborska** [comment]
I don't have the privileges either :( can you close this one and create a new one?

**Comment by siebenschlaefer** [comment]
Done. Thanks for the quick replies.
