### ISSUE TITLE
Wren test runner seems to always time out

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5619]
Perhaps some part of new infrastructure not completely working yet?

<img width="515" alt="Screen Shot 2021-09-01 at 1 19 51 PM" src="https://user-images.githubusercontent.com/6473/131715415-9d9e5bc1-5b7d-4914-81ea-39b5b583f458.png">

**Comment by joshgoebel** [comment]
It just worked (for the first time ever) right now... not sure if that means anything. :)

**Comment by iHiD** [comment]
Yeah. That sounds about right :) @ErikSchierboom This is because test_runner flag was set to false on each exercise as per #5638
