### ISSUE TITLE
Track repos descriptions include a broken link exercism.io/languages/<language>

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5623]
It should be `exercism.org/tracks/<language>`. I don't have the power to fix this. It's like that in many many repos. Examples:

![Screen Shot 2021-09-01 at 20 36 14](https://user-images.githubusercontent.com/7852553/131725537-059ec8bd-8fb0-4871-adfa-87247119c1b4.png)
![Screen Shot 2021-09-01 at 20 36 03](https://user-images.githubusercontent.com/7852553/131725541-51489c9c-5c14-458c-8892-fab5969a6300.png)
![Screen Shot 2021-09-01 at 20 35 59](https://user-images.githubusercontent.com/7852553/131725545-e546bc54-173a-43c2-8d37-677781a41072.png)

**Comment by michallepicki** [comment]
I think there are lots of links looking like that floating around the internet, so if it wouldn't cause issues, it would be great to keep them working via a redirect from`/languages/:lang` to tracks

**Comment by iHiD** [comment]
Wow. `/languages` is **old**. I'll add a redirect. Thanks :)

@erikschierboom - can we script these ones to be correct? (Sorry!)
