### ISSUE TITLE
DNS not found for local.exercism.io

### ISSUE THREAD

**Issue by FaisalAfroz** [exercism/exercism#5624]
When opening links from below like [Instruments of Texas](http://local.exercism.io:3020/tracks/csharp/exercises/instruments-of-texas)

<img src="https://user-images.githubusercontent.com/42181455/131726311-a1714434-faef-438d-b635-774e496036b5.jpg" width="650" height="400"/>

We get site can't be reached like below
<img width="729" alt="Screenshot 2021-09-02 at 12 11 50 AM" src="https://user-images.githubusercontent.com/42181455/131727058-dce80ff7-5d92-4d0a-99a5-098e746700e2.png">

**Comment by iHiD** [comment]
Fixed. Thanks.
