### ISSUE TITLE
F# Test Runner Error

### ISSUE THREAD

**Issue by simon-flanagan** [exercism/exercism#5628]
The F# test runner seems to be having issues. I've tried the same code locally and it passes all tests. This is affecting both the online editor and causing offline exercise submission to fail.

Tested with exercise: https://exercism.org/tracks/fsharp/exercises/lucians-luscious-lasagna/ 

![image](https://user-images.githubusercontent.com/15949351/131728513-e638eb97-468f-4500-a900-f2cd0adae957.png)

**Comment by lynnlangit** [comment]
I tested the F# track (Hello World) and observed the same result.

**Comment by angelikatyborska** [comment]
@ErikSchierboom I think it's the issue with the test runner not being deployed

```
exceptioned

STDERR:
------
Unable to find image '681735686245.dkr.ecr.eu-west-2.amazonaws.com/fsharp-test-runner:production' locally
docker: Error response from daemon: manifest for 681735686245.dkr.ecr.eu-west-2.amazonaws.com/fsharp-test-runner:production not found: manifest unknown: Requested image not found.
See 'docker run --help'.
```

**Comment by ErikSchierboom** [comment]
@angelikatyborska That was indeed it. With your PR merged, it now works:

![image](https://user-images.githubusercontent.com/135246/131791649-e416f140-f7d3-47b0-a35c-e4cf442e787f.png)

Thanks for reporting @simon-flanagan
