### ISSUE TITLE
Lack of a nice 404 page on unexpected paths

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5630]
A path like `https://exercism.org/tracks/foo` produces a nice 404 page. A path like `https://exercism.org/foo/bar` produces an ugly 404 page.

![Screenshot 2021-09-01 at 21-13-50 Action Controller Exception caught](https://user-images.githubusercontent.com/7852553/131730650-8d26909a-daf4-4016-8467-c3572f90c4db.png)

**Comment by joshgoebel** [comment]
We absolutely shouldn't be exposing raw Rails error pages once in production...  are we running in dev mode or something?

**Comment by iHiD** [comment]
Fixed.
