### ISSUE TITLE
Setup security.txt or equivalent

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5632]
There's no obvious contact mail for reporting security issues. Consider setting up a [`security.txt`](https://securitytxt.org/) or add a contact page for these purposes.

**Comment by iHiD** [comment]
Thanks. Want to PR the one from exercism/website to here too?

**Comment by SaschaMann** [comment]
I think we're talking about different things. I meant a `security.txt` file on the website itself, according to that proposed standard linked in the message above, not a file in the repo.

**Comment by iHiD** [comment]
Ah cool. Hadn't heard of that. I'll probably wait until it's accepted as a standard (it's currently an early draft idea from what I can see), but it seems sensible. For context, I do get security reports from bounty hunters daily already.

**Comment by SaschaMann** [comment]
It's a draft but plenty of websites use it already.

**Comment by iHiD** [comment]
Merging into https://github.com/exercism/exercism/issues/6555
