### ISSUE TITLE
Cannot navigate to community solutions which have comments

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5636]
NoMethodError whether logged in or not. Only for solutions that have comments.

Examples

[C Hamming](https://exercism.org/tracks/c/exercises/hamming/solutions/bobahop)

[Python Word Count](https://exercism.org/tracks/python/exercises/word-count/solutions/bobahop)

[Rust Clock](https://exercism.org/tracks/rust/exercises/clock/solutions/bobahop)

**Comment by bobahop** [comment]
Now I see 500 error page instead of NoMethodError.

**Comment by bobahop** [comment]
This may be related to issue [#5614](https://github.com/exercism/exercism/issues/5614)

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/1740 - thanks.
