### ISSUE TITLE
Unable to cancel /exit exercise publish operation/window

### ISSUE THREAD

**Issue by salouri** [exercism/exercism#5637]
![no-go-back-publish-exercism io](https://user-images.githubusercontent.com/8387481/131713744-0322b2e8-f02e-4ac0-aa5f-cf822d40b272.png)
After you are done with an exercise and you hit the Publish button...there is no way to cancel this! You have to publish your code.

I think there should be a "cancel", "back", or an "x" button to cancel the publish operation in case the user wanted to. Another way to do it is also by clicking outside the publish window.

**Comment by SleeplessByte** [comment]
Yes please, also from accessibility standpoint.

**Comment by salouri** [comment]
> You should be able to click on the background for it to close, but we should also add a close button to this modal.

I did try clicking outside the window but it didn't go away..
