### ISSUE TITLE
Honour all statuses when creating exercises

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5638]
Currently test_runner gets set to false. I think it's because the code path for updating (which is correct) is different to that for creating. It would be nice if they were DRY'd up. (Gut instinct - not checked the code)

**Comment by ErikSchierboom** [comment]
DRY-ing up is actually not that simple to do due to the way the exercise sync classes are modeled via inheritance (in short: they need an exercise to already exist)

**Comment by iHiD** [comment]
I think what I mean is putting [as much as possible of this bit](https://github.com/exercism/website/pull/1735/files#diff-53328c3cf21fa8f471d31829efb86191aca2e5febd1280197c5dd3aef41b5a90R93-R103) into a common hash that both use. But it's low on the urgent scale. We just need to remember to add to the create if we add to the update and vis-versa.
