### ISSUE TITLE
Old links to specific community solutions don't work now

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5641]
Here is an except from my mentoring notes with links that no longer work (404 pages), since we changed from a guid to using the username.

A [solution using for loops](https://exercism.io/tracks/rust/exercises/anagram/solutions/5f3a647796d744bb9781e49217864bef)
```rust
test test_multiple_anagrams ... bench:         888 ns/iter (+/- 108)
```

A [solution using u8s](https://exercism.io/tracks/rust/exercises/anagram/solutions/3cd55872b53048ecb3756daca3a877ae)
```rust
test test_multiple_anagrams  ... bench:       1,071 ns/iter (+/- 50)
```

A [solution using selective bitmask lower-casing](https://exercism.io/tracks/rust/exercises/anagram/solutions/6e048d224d514984bafd061c3f73799d)
```rust
test test_multiple_anagrams ... bench:       1,150 ns/iter (+/- 221)
```

Here's a specific example of [my old Leap solution link with guid](https://exercism.io/tracks/rust/exercises/leap/solutions/582124cfd58d4130816301bb44b39a0a) is now 
[new link with name](https://exercism.org/tracks/rust/exercises/leap/solutions/bobahop)

**Comment by angelikatyborska** [comment]
I have a similar problem. I managed to fix most links because we had the author's handle saved too but I cannot find one of them: https://github.com/exercism/elixir/pull/861/files/be516dabd15f133069032c66e2ed211d7c08406a#r700473003

**Comment by iHiD** [comment]
Ah, ok. So I only redirected URLs of the form `https://exercism.io/solutions/5f3a647796d744bb9781e49217864bef`

Fixed by https://github.com/exercism/website/pull/1739
