### ISSUE TITLE
The track headers are giving me night terrors, please fix

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5642]
![grafik](https://user-images.githubusercontent.com/20866761/131748221-9149d3dd-7376-4c70-a330-45e2ba159e91.png)

There's a space before the comma. Unfortunately I can't find it via code search on GitHub to fix it directly.

Shout out to @BethanyG for the issue title :P

**Comment by SleeplessByte** [comment]
Hahahahaha this issue title.

**Comment by angelikatyborska** [comment]
Here's the code: https://github.com/exercism/website/blob/69ccc455da868e47ef2fdc639183b2fed15adc29/app/views/tracks/about.html.haml#L21-L23 but it being HAML and using some `succeed` function to insert the comma, I wouldn't really know to how fix that.

**Comment by SaschaMann** [comment]
Thank you! I can finally sleep peacefully again ;p
