### ISSUE TITLE
Some ported mentoring comments have a ? in place of an emoji

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5645]
E.g. https://exercism.org/mentoring/discussions/7625584e-08c7-11ec-81c5-853579c25f94

It was meant to be a 👋

**Comment by SleeplessByte** [comment]
https://exercism.org/mentoring/discussions/74b19662-08c7-11ec-81c5-853579c25f94 seems to work (it was ✨)

**Comment by SleeplessByte** [comment]
https://exercism.org/mentoring/discussions/74ede9f0-08c7-11ec-81c5-853579c25f94 here some work, and some are broken. Pretty sure the broken ones are either compound or in the extended set. So likely a conversion issue.

**Comment by iHiD** [comment]
@ErikSchierboom Could you look at one of these and see what the actual text stored in the db is pls and if this is fixable?

**Comment by ErikSchierboom** [comment]
@iHiD I've looked into the database and the actual stored text there are unfortunately regular question marks :( I don't think we can fix them.
