### ISSUE TITLE
Launching exercism editor in new tab returns 404 error.

### ISSUE THREAD

**Issue by ashshuota** [exercism/exercism#5647]
When opening the editor in the same tab, the url is: `https://exercism.org/tracks/haskell/exercises/hello-world/edit`
When opening the editor in a new tab, the url is: `https://exercism.org/tracks/haskell/exercises/hello-world/start` which returns a 404.
Expecting a consistent behaviour from the editor launching buttons.

**Comment by iHiD** [comment]
I believe this is fixed now. Could you confirm pls?

**Comment by ashshuota** [comment]
Yes. It seems to be working well.
