### ISSUE TITLE
Aliases Are Gone

### ISSUE THREAD

**Issue by bjaress** [exercism/exercism#5648]
We used to be able to define track-specific aliases for ourselves, so that published solutions would show a different author name than our account name.  I used that feature quite a bit, and it looks like it's just gone.  All published solutions are now available under the account name.

I really enjoyed that feature.  It was fun.  Also, removing it like this means you've retroactively stripped away a form of anonymity from some of your users. Of course it's possible to create a new account with whatever name you want, but people who were logging in with their GitHub account and relying on aliases now have all their old published solutions public under a name they didn't expect to use for that.

**Comment by iHiD** [comment]
@bjaress Thanks for the issue.

Yes, various changes meant that published solutions needed to be attributable to someone. Maintaining the old system added a real level of complexity in loads of places, with every time something got rendered having to guard against alias mode, etc. It was a constant pain point.

That said, I had intended for old aliased solutions to be unpublished during ETL. For some reason that hasn't worked. I'll solve that asap and unpublish any previously-aliased solutions, but it'll be a little harder now as I'll have to merge data from both the old and new systems, so it might take a bit of time to get right. Sorry if that's caused you any hassle.

**Comment by kytrinyx** [comment]
> I'll solve that asap and unpublish any previously-aliased solutions

@iHiD did you take care of this step?
