### ISSUE TITLE
Start in editor shown for track without test runner

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#5653]
If you join a track without a test runner and go to an exercise (e.g. https://exercism.org/tracks/swift/exercises/hello-world), you'll see that the top "Start in editor" button is disabled due to there not being a test runner, but the bottom button isn't:

![image](https://user-images.githubusercontent.com/135246/131816313-0fdfa886-c7e9-4f67-aced-b56dada22c4d.png)

**Comment by kntsoriano** [comment]
Closing this as this is now fixed.
