### ISSUE TITLE
Rendering of list can easily break

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5654]
![image](https://user-images.githubusercontent.com/1964376/131823932-4956b5bc-c685-4765-bd56-e175514b792b.png)

on Annalyn's Infiltration in JavaScript

**Comment by angelikatyborska** [comment]
For reference, source and how GitHub renders it:

```markdown
Having found the kidnappers, Annalyn considers which of the following actions she can engage in:

- _Fast attack_: a fast attack can be made if the **knight** is **_sleeping_**, as it takes time for him to get his armor on, so he will be vulnerable.
- _Spy_: the group can be spied upon if **at least one** of them is **_awake_**. Otherwise, spying is a waste of time.
- _Signal prisoner_: the prisoner can be signalled using bird sounds if the **prisoner** is **_awake_** and the **archer** is **_sleeping_**, as archers are trained in bird signaling so they could intercept the message.
- _Free prisoner_: Annalyn can try sneaking into the camp to free the prisoner, but this tactic will only work if the **prisoner** is **_awake_** and the **other two characters** are **_sleeping_**.
  If the **prisoner** is **_sleeping_**, they'll be startled by Annalyn's sudden appearance and will awaken the other two characters.
  The prisoner can also be freed if the **archer** is **_sleeping_** and Annalyn has her **pet dog** **_with her_**, as the knight will be scared by the dog and will withdraw, and the archer can't equip his bow fast enough to prevent the prisoner from being freed.

You have four tasks: to implement the logic for determining if the above actions are available based on the state of the three characters found in the forest and whether Annalyn's pet dog is present or not.
```

![Screen Shot 2021-09-02 at 12 24 08](https://user-images.githubusercontent.com/7852553/131827722-1226a685-867e-4b1c-bd96-df5de873b96d.png)

**Comment by SleeplessByte** [comment]
(Thanks, I should have added that)

**Comment by iHiD** [comment]
Do you have the HTML that is being output by Exercism pls?

**Comment by angelikatyborska** [comment]
Let me pile on a similar list issue with the "grade school" description.

<img width="1045" alt="Screen Shot 2021-09-02 at 15 50 19" src="https://user-images.githubusercontent.com/7852553/131855828-c9a3924f-d5c3-42c9-b904-25478eb014f4.png">


List markup as copied from that page (it's correct so it must be a CSS issue)

``
<ul>
<li>Add a student's name to the roster for a grade
<ul>
<li>"Add Jim to grade 2."</li>
<li>"OK."</li>
</ul>
</li>
<li>Get a list of all students enrolled in a grade
<ul>
<li>"Which students are in grade 2?"</li>
<li>"We've only got Jim just now."</li>
</ul>
</li>
<li>Get a sorted list of all students in all grades.  Grades should sort
as 1, 2, 3, etc., and students within a grade should be sorted
alphabetically by name.
<ul>
<li>"Who all is enrolled in school right now?"</li>
<li>"Let me think. We have
Anna, Barb, and Charlie in grade 1,
Alex, Peter, and Zoe in grade 2
and Jim in grade 5.
So the answer is: Anna, Barb, Charlie, Alex, Peter, Zoe and Jim"</li>
</ul>
</li>
</ul>
```

Markdown source: https://github.com/exercism/problem-specifications/blob/main/exercises/grade-school/description.md

```
- Add a student's name to the roster for a grade
  - "Add Jim to grade 2."
  - "OK."
- Get a list of all students enrolled in a grade
  - "Which students are in grade 2?"
  - "We've only got Jim just now."
- Get a sorted list of all students in all grades.  Grades should sort
  as 1, 2, 3, etc., and students within a grade should be sorted
  alphabetically by name.
  - "Who all is enrolled in school right now?"
  - "Let me think. We have
  Anna, Barb, and Charlie in grade 1,
  Alex, Peter, and Zoe in grade 2
  and Jim in grade 5.
  So the answer is: Anna, Barb, Charlie, Alex, Peter, Zoe and Jim"
```

**Comment by angelikatyborska** [comment]
The problem only appears in mentoring view for me so I cannot see JavaScript's messed up list.

**Comment by iHiD** [comment]
This is fine in other places btw.

<img width="486" alt="Screenshot 2021-09-04 at 00 47 06" src="https://user-images.githubusercontent.com/286476/132074916-dc4b5955-7cad-44d1-80bc-a64e99b10b2d.png">

**Comment by angelikatyborska** [comment]
Yes, the bug is that in the mentoring UI in the "instructions" tab, there is this style for list items. Removing it fixes everything.
```
.c-code-pane li {
    display: flex;
}
```
![2021-09-04 08 35 39](https://user-images.githubusercontent.com/7852553/132085394-ca67ca0e-16eb-4a9b-97b7-db0d012ab3dd.gif)

**Comment by iHiD** [comment]
@angelikatyborska Do you know if this got fixed? (cc @ErikSchierboom to fix it if not)

**Comment by ErikSchierboom** [comment]
Looks to have been fixed:

![image](https://user-images.githubusercontent.com/135246/166894090-a052c6c4-662e-4d38-8fec-21dc354eb0ea.png)
![image](https://user-images.githubusercontent.com/135246/166894380-d3728d5d-36cd-418e-ae9e-c8421f0566a7.png)
