### ISSUE TITLE
Some test runners not working but Web UI visible and accessible (Kotlin, Swift, Dart)

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5657]
![image](https://user-images.githubusercontent.com/1964376/131828155-7e8f8c36-f163-4430-8e66-6caa37dddcd2.png)

@ErikSchierboom probably the same as the Swift issue.

**Comment by ErikSchierboom** [comment]
Yep. @working on it as we speak!

**Comment by ErikSchierboom** [comment]
@SleeplessByte We've found the issue and it should be fixed:

![image](https://user-images.githubusercontent.com/135246/131851693-bb3489d1-36f3-4b9b-abb7-07faa2fc1c24.png)

Could you verify?

**Comment by iHiD** [comment]
Two bugs here:
1. https://github.com/exercism/exercism/issues/5669
2. https://github.com/exercism/exercism/issues/5670

When those are both fixed, this also can be fixed.

**Comment by SleeplessByte** [comment]
![image](https://user-images.githubusercontent.com/1964376/131872251-04237580-645f-47d5-8966-09195fe2061a.png)

FYI @ErikSchierboom 

I know it's in progress :)

**Comment by masahx** [comment]
hi,
I think I have similar issue with Java. Tests passed on my computer, but not here. I used Java 15.

exercise: Forth 
my username: masahx

**Comment by angelikatyborska** [comment]
@masahx see this discussion https://github.com/exercism/exercism/discussions/5717 it's probably relevant to your problem
