### ISSUE TITLE
'Return to "Hello, World!" doesn't do anything

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5658]
After I complete hello world and publish my solution, I get this modal. I cannot close it in any way. The button 'Return to "Hello, World!"  doesn't do anything. I can only go to the syllabus ("show me the concepts") or to the exercises ("real exercises" inline link).

![Screenshot 2021-09-02 at 12-23-42 Hello World in JavaScript on Exercism](https://user-images.githubusercontent.com/7852553/131828245-efab9aec-f74a-481e-b875-1134bec1ad8b.png)

**Comment by iHiD** [comment]
Also button spacing 🤮

**Comment by angelikatyborska** [comment]
Both have been fixed, I'm closing.
