### ISSUE TITLE
Community solutions showing really old (and outdated) solutions first

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5659]
See the issue title

**Comment by iHiD** [comment]
Stars then newest.

**Comment by iHiD** [comment]
Duplicate of https://github.com/exercism/exercism/issues/5899

But also I think I fixed this?

**Comment by gmlewis** [comment]
@iHiD - check out this Elixir exercise where you have to navigate to Page 5 of the community solutions before you find the first one that is not outdated: https://exercism.org/tracks/elixir/exercises/list-ops/solutions?page=5

I would suggest that all "outdated" solutions be moved to the bottom of the list.

So the ordering should be:
Not-outdated: Stars, then newest.
Outdated: Stars, then newest.
