### ISSUE TITLE
Order of filters (order by oldest first) are not retained

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5660]
...which makes it very hard to browse. Not retained as in:

1. change order to newest first
2. click a link on the first page
3. come back to the page (NOT via back)
4. now you've lost your place because the first page is no longer "the first page"

**Comment by angelikatyborska** [comment]
Is this about a specific page? There a few views that have a "order by oldest first" option

**Comment by SleeplessByte** [comment]
This is on all pages that offer ordering

**Comment by iHiD** [comment]
So the work here would be using local-storage to remember previous preferences?

**Comment by iHiD** [comment]
@SleeplessByte @dem4ron I believe this got fixed in lots of places by updating the URL as changes are made (e.g. https://exercism.org/tracks/elixir/exercises/high-school-sweetheart/solutions?order=newest). Could you check to see if there are any wrong still. If things are ok, let's close this.

**Comment by SleeplessByte** [comment]
I think this was resolved.
