### ISSUE TITLE
Publish window can't be cancelled

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#5663]
If I click on the "Mark as complete" button, I get the following popup:

![image](https://user-images.githubusercontent.com/135246/131842811-3ff9c9a4-255d-4095-980d-529264f0837d.png)

There is no way for me to cancel/close this popup, which is annoying if you've mistakenly clicked on the button.

**Comment by kntsoriano** [comment]
Add close button to this as well.
