### ISSUE TITLE
Add option not to deploy website on merge

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5668]
Look for the test `[no-deploy]` or something in the title or body of a commit. If it's there, don't deploy in the GHA.

(@SaschaMann You might have a script for this too from the other stuff). The workflow is the deploy one in exercism/website

**Comment by SaschaMann** [comment]
I don't have a script but before github added support for `[CI skip]` there were workarounds that effectively implemented this. Should be able to find those in the github community board.

**Comment by iHiD** [comment]
Is [CI skip] what's used in the org-wide-files?

**Comment by SaschaMann** [comment]
Yes, it's a github-wide feature. Note that **all** workflows will not run, so if you have tests running on main, they'd also be skipped. If that doesn't matter, you can use `[ci skip]` without any changes to the workflow.

Any of these also work:

> [skip ci], [ci skip], [no ci], [skip actions], or [actions skip]

**Comment by ErikSchierboom** [comment]
I think this issue can be closed, as we can use the default GitHub behavior of `[skip ci]` and its variants.
