### ISSUE TITLE
can not execute binary file

### ISSUE THREAD

**Issue by Shiener** [exercism/exercism#5673]
<img width="511" alt="Ảnh chụp Màn hình 2021-09-02 lúc 21 18 35" src="https://user-images.githubusercontent.com/87566731/131860411-f5f8c987-74cd-411f-8ada-0e01d0bb3304.png">
somebody help me? i get "can not execute binary file" when i try to test my program. im learning swift

**Comment by SleeplessByte** [comment]
cc @exercism/swift (but also @ErikSchierboom might know). Is this a `git update-index --chmod=+x` thing? This user seems to be on Windows but then WSL or something like that.

**Comment by angelikatyborska** [comment]
What's WSL? `/Users/username`, the prompt about the default shell migration to zsh, and "please visit support.apple.com" sounds like a mac to me. What am I missing?

**Comment by ErikSchierboom** [comment]
Isn't `zsh` usually used on Macs?

**Comment by Shiener** [comment]
yah.. I use mac. I found the solution. https://stackoverflow.com/questions/61501298/xcrun-error-unable-to-find-utility-xctest-not-a-developer-tool-or-in-path

**Comment by Shiener** [comment]
mbj

**Comment by angelikatyborska** [comment]
@ErikSchierboom 

> Isn't zsh usually used on Macs?

Yes, but if you set up your mac before the system update that switched default shells, your user's shell didn't get force-migrated, you only get this prompt to do the change yourself.

**Comment by SleeplessByte** [comment]
That was going to be my next comment ha.

Thanks everyone!
