### ISSUE TITLE
Vimeo links are broken

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5679]
Vimeo links are broken: https://exercism.lol/docs/mentoring/choosing-a-solution

**Comment by angelikatyborska** [comment]
@iHiD they work on production 🙂 https://exercism.org/docs/mentoring/choosing-a-solution

But there are some ugly "[TODO: Image of queue]" there.

**Comment by iHiD** [comment]
Urgh. I was looking at .lol again!!!
