### ISSUE TITLE
Not for profit page yields error 500

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5680]
![image](https://user-images.githubusercontent.com/1964376/131871413-9d38811f-53bf-442e-bfb6-f5e20b1bddf9.png)

I got there pressing this link (not-for-profit) in the header:

![image](https://user-images.githubusercontent.com/1964376/131872157-ca5f9706-2c37-4aef-a975-0860cab26d69.png)

**Comment by corneliusroemer** [comment]
Just wanted to open this bug myself. Can confirm this still exists:
https://exercism.org/docs/organisation

**Comment by bobtfish** [comment]
Also came here to open this issue :)

**Comment by SleeplessByte** [comment]
The link is now gone, but the error isn't fixed. It's still giving me a 500. Opened #6341 .
