### ISSUE TITLE
Scala Track - Task 1 Hello World [BROKEN] Tests will not pass.

### ISSUE THREAD

**Issue by Andy-Lee14** [exercism/exercism#5682]
Hello, I'm currently trying to progress on the Scala track however the first task (Hello World) appears not to be working correctly as the tests are passing on my local machine, but not once they have been submitted. Any help with this would be appreciated. Thank you.

**Comment by SleeplessByte** [comment]
Probably same as #5657.

**Comment by angelikatyborska** [comment]
Yes, Scala doesn't have a working test runner as per https://github.com/exercism/scala/blob/main/config.json#L7

**Comment by ErikSchierboom** [comment]
This was a bug in the website where it looked like you could work with the online editor, but it doesn't yet have one (sorry).
