### ISSUE TITLE
Mentoring queue gets cached, requires a page reload to remove solutions I just mentored

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5691]
Observe on this gif how Pacman Rules by Stqa keeps appearing in the queue even though I already started mentoring it. I need to reload the page for it to disappear (after the reload, a new solution by the same user appears but don't be fooled, that's a different exercise)
![2021-09-02 18 46 30](https://user-images.githubusercontent.com/7852553/131884415-0e443243-afd2-4087-b738-bb98ba49dd35.gif)

**Comment by joshgoebel** [comment]
Feel like I've also seen this and would love a fix.

**Comment by kntsoriano** [comment]
@angelikatyborska Could you confirm if this still happens?

**Comment by angelikatyborska** [comment]
I think the caching issue for the submission list in the mentoring queue is resolved, but now sometimes I see the number in the tab ("Queue (3)") sometimes briefly go up and down after mentoring a student. I cannot capture it at the moment because it only happens once, and mentoring takes time so it cannot be recreated many times for debugging purposes :(.

**Comment by kntsoriano** [comment]
Thanks @angelikatyborska!

I think the bug you described above has something to do with Turbolinks and is different from the bug described in this issue. I will close this and open another issue for the comment above.
