### ISSUE TITLE
Recieved a mail about mentoring which is I think about a old version 

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/exercism#5695]
Hello,

I recieved a mail that someone was  mentoring me on High Score on the Ruby track.
But on .lol and on .org I did not solve that one so the link is a 404. 
Here a screenshot of the mail.

![afbeelding](https://user-images.githubusercontent.com/89863657/131892935-f2bceb87-bb61-4b7a-88c9-b47682867935.png)

if needed I can also add the mail to this issue.
The only thing it will be a thunderbird mail.

**Comment by iHiD** [comment]
I believe you started this exercise in the 26th august. All mentoring requests from August are still valid. So that's why you got mentored.

**Comment by iHiD** [comment]
@RoelofWobben Could you please forward the email to jeremy@exercism.org
