### ISSUE TITLE
No reputation being awarded to mentors

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/exercism#5697]
I've mentored some solutions since the v3 launch. Some students closed the conversations and even gave testimonials, but my reputation doesn't seem to change. Checking the ways I got reputation in the "My Journey" Page and filtering by "Mentoring" I only see entries from a while back. I'm also not receiving any notifications related to reputation gains.

**Comment by andrerfcsantos** [comment]
Not sure if it's related, but I also don't seem to be receiving reputation from PR's. I did one yesterday on the Go track and I didn't get reputation from it. But that might be because the PR was not accepted yet, maybe?

**Comment by SleeplessByte** [comment]
@andrerfcsantos correct. The PR must be approved and merged to get rep for it.

**Comment by iHiD** [comment]
Fixed. And back-awarded.
