### ISSUE TITLE
Sort of testimonials appears to be incorrect or reporting incorrectly.

### ISSUE THREAD

**Issue by kotp** [exercism/exercism#5698]
![image](https://user-images.githubusercontent.com/16747/131911209-bddd91af-6355-4cb5-b870-2254b10dace3.png)

**Comment by iHiD** [comment]
Thanks @kotp. Is this on page load or when you use the filters? Does using the filters work correctly?

**Comment by kotp** [comment]
The filters seem to work, (I tested it with a student where I typed their name, but they are using UTF-8 letters, but partial search also did not bring them up, I had to click on their exercise, copy and then paste their name/handle in the search.)

**Comment by kotp** [comment]
When I switch from recent first and then oldest first, this still shows in this way.
