### ISSUE TITLE
Can't submit the exercise solution with the tests completed if you leave the page and then return

### ISSUE THREAD

**Issue by Yardanico** [exercism/exercism#5701]
Steps to reproduce:
1. Go to any exercise and write a correct solution to the problem, then click "Run tests".
2. Without clicking "submit" leave the page (e.g. click "Back to Exercise")
3. Return to the page with the exercise

Now the "Submit" is visible but not active despite all tests showing as passed:
![image](https://user-images.githubusercontent.com/21169548/131921444-52b0a966-25de-4a3b-a179-81011d8cb642.png)

The current workaround is to modify the code (since you can't rerun the tests with the same code which makes sense), rerun the tests, modify the code back to the correct one, rerun the tests again and click "Submit".

**Comment by iHiD** [comment]
@Yardanico Thanks :)

---

@kntsoriano Let's have a chat about this and the other issues related to this area next week and agree a plan for how to address them all. There's a **lot** of complexity in all this!
