### ISSUE TITLE
CodeMirror lacks support for nim out of the box

### ISSUE THREAD

**Issue by ynfle** [exercism/exercism#5703]
Currently, there is no syntax highlighting for nim in the online editor.

There is 5 grammar for nim in [this](https://github.com/stisa/nim-codemirror-mode) repo.

Let me know how I could help

**Comment by Steffan153** [comment]
Same problem with CFML.

**Comment by ynfle** [comment]
And prolog

**Comment by SleeplessByte** [comment]
Yep. A lot of them are lacking out of the box, but PRs welcome ❤️

**Comment by ynfle** [comment]
I'm happy to PR. Is it just adding the package to `package.json`? If not, what else? Where else do I look?

**Comment by joshgoebel** [comment]
I'm not sure if this is the ONLY place, but it's a key place... though you likely need the stack working locally to confirm it, but @ErikSchierboom could probably review by site... the integration is slightly different if you have a version 5 or version 6 grammar.

**Comment by ynfle** [comment]
How do I get the stack locally? Is it more than 12 GB? @joshgoebel did you use 5 or 6 grammar?

**Comment by joshgoebel** [comment]
The Wren grammar I wrote is version 6... writing a version 5 grammar by hand looks nightmarish.

@ynfle I forget now, you'd need Docker... we have tools to fire up the entire stack (that I haven't looked at in a while) but yes it can be quite large.

**Comment by ynfle** [comment]
It's funny because in https://github.com/exercism/website/blob/5c4e8924d98221eeed7a21171c2f6e5dc8bc2a6a/app/javascript/components/misc/CodeMirror/languageCompartment.ts#L111 it seems that there is the nim plugin and in https://github.com/exercism/website/blob/5c4e8924d98221eeed7a21171c2f6e5dc8bc2a6a/package.json#L43

**Comment by ynfle** [comment]
And it's 0.2.0 not 0.3.0

**Comment by joshgoebel** [comment]
I know nothing about the version number, looks like `nim` is already there though at a glance, so I dunno why it's not working. :)

**Comment by ynfle** [comment]
So it turns out there is an exception
```javascript
Uncaught (in promise) TypeError: Cannot read property 'languageData' of undefined
    at new n (index.js:324)
    at Function.value (index.js:399)
    at languageCompartment.ts:113
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at B (18-25adb190473e554635ba.chunk.js:1)
    at o (18-25adb190473e554635ba.chunk.js:1)
```
@SleeplessByte any idea? 

The README of [nim-codemirror-mode](https://github.com/stisa/nim-codemirror-mode) says to write
```javascript
require("nim-codemirror-mode").register(CodeMirror)
```
instead of the current 
```javascript
const { nim } = await import('nim-codemirror-mode')
return compartment.of(StreamLanguage.define(nim))
```
Would that be related?

**Comment by joshgoebel** [comment]
```
require("nim-codemirror-mode").register(CodeMirror)
```

That's just some sugar the library is providing... I'd guess it does this behind the scenes... we should be able to register it like we do the others, but I'm not 100% sure.

**Comment by iHiD** [comment]
@kntsoriano @ErikSchierboom Thoughts on this?

**Comment by iHiD** [comment]
@kntsoriano Also see https://github.com/exercism/website/issues/1511 for the bugsnag

**Comment by ynfle** [comment]
![image](https://user-images.githubusercontent.com/23086821/132134514-5de05231-3fc9-4764-bac1-f35ff83e0a62.png)
Thanks, everyone! Great community and especially leadership!

**Comment by iHiD** [comment]
Brilliant!

**Comment by Steffan153** [comment]
Should I open another issue for the other languages (CFML, PHP, Prolog, etc) or do one issue each?

**Comment by iHiD** [comment]
Could you make one issue with a checkbox list pls? Thank you! I'll assign it to @kntsoriano as a priority.
