### ISSUE TITLE
Reading Docs should not require onboarding.

### ISSUE THREAD

**Issue by mabo3n** [exercism/exercism#5706]
If I go to https://exercism.org and log in with my GitHub account, I am redirected to https://exercism.org/user_onboarding but I can't open any links and I can't go back to the main page, unless I clear my browser cookies.

**Comment by iHiD** [comment]
Have you ticked the boxes and clicked "Save and get started"?

**Comment by mabo3n** [comment]
Hum, I usually like to actually give the terms a quick read before ticking I accept them. But hey I just found that the links open fine in a anonymous window! So far so good, logged in and ready to start using Exercism. 

But before closing this one... shouldn't the pages under /docs be accessible regardless of this login status? Maybe there's a simple way to handle that.

**Comment by iHiD** [comment]
OK, yeah. That's a bug. I'll rename the issue. Thanks.
