### ISSUE TITLE
Profiles require 5 rep

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5709]
You should not be able to create a profile until you have 5 rep. This is especially important to deter spam bots.

Steps for this:
- [ ] Guard in UI (there is UI in figma - so if @ErikSchierboom you create some placeholder HTML, I'll implement the actual stuff)
- [ ] Guard on creation command just to be safe.
- [ ] Delete profiles with <5rep.

**Comment by ErikSchierboom** [comment]
The query that we can use to delete the profiles:

```ruby
User::Profile.joins(:user).where('users.reputation < 5').delete_all
```

Interestingly, `76519` of the `103206` will be deleted.

**Comment by SleeplessByte** [comment]
I would do < 5 rep AND created after launch of v3 @ErikSchierboom

**Comment by ErikSchierboom** [comment]
What we ended up with it to just delete profile of users without reputation (64373):

```ruby
User::Profile.joins(:user).where('users.reputation': 0).count
```

**Comment by ErikSchierboom** [comment]
Closed by https://github.com/exercism/website/pull/2757
