### ISSUE TITLE
Progress percentage displayed as NaN%

### ISSUE THREAD

**Issue by roktas** [exercism/exercism#5712]
![image](https://user-images.githubusercontent.com/47842/131828641-ba7972f8-2916-446c-a3db-151f85e3b911.png)

This looks like an edge case.  I have no track enrolled.

**Comment by iHiD** [comment]
@taiyab Zero state if there's no learning tracks on journey page? Same as the others?

@kntsoriano Can you get a branch going for this pls.

**Comment by angelikatyborska** [comment]
This is a duplicate of https://github.com/exercism/exercism/issues/5625 but I will close the original issue because this one is already labelled and assigned.

**Comment by taiyab** [comment]
@iHiD Yep. On it.

**Comment by taiyab** [comment]
Once they've enrolled, it can say 0% progress made (and we remove the "Keep it up").

**Comment by taiyab** [comment]
![image](https://user-images.githubusercontent.com/5337876/132005525-eb8ba606-cf96-432c-bfd7-985759162cc9.png)
