### ISSUE TITLE
"Waiting on a mentor" status incorrect?

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5716]
I requested, received, and ended discussion and it still thinks I'm "Waiting on a mentor"...

<img width="882" alt="Screen Shot 2021-09-03 at 2 01 16 AM" src="https://user-images.githubusercontent.com/6473/131957846-a9e485e3-30db-482c-bf54-7f4d8859c2b6.png">

**Comment by iHiD** [comment]
Is this fixed now?

**Comment by kytrinyx** [comment]
(ping) @joshgoebel - do you know if this is fixed?
