### ISSUE TITLE
Create new track for Salesforce Apex

### ISSUE THREAD

**Issue by nilvon9wo** [exercism/exercism#5719]
Salesforce is a great and terrible platform with increasing demand.

While Salesforce offers "Trailhead", this does not really teach anyone to develop maintainable solutions, just to crudely get work done.   And this is mixed into a lot of material which is useless beyond marketing themselves and their partnerships.   Many "senior" developers on the platform don't know how to use collections, apply design patterns, how to distinguish unit tests from integration tests, or even how to write useful tests.

**Comment by SleeplessByte** [comment]
This probably wouldn't work well as a _language_ track but does work really well with out "3.5" idea of framework-tracks. 

I'll make sure this is mentioned during one of the 'weekly'-calls.

**Comment by iHiD** [comment]
I'm going to close this as per @SleeplessByte's comment. Currently we're only building language tracks but in the future, if that changes, we can reopen this.
