### ISSUE TITLE
The Rust "A Short Fibonacci Sequence" needs better tests

### ISSUE THREAD

**Issue by nilvon9wo** [exercism/exercism#5720]
Specifically, the test for the `fibonacci()` function will accept much the same code as the `create_buffer()` function, as the only test compares the first and second value against the third value, but it is quite possible for these to be equal without being the fibonacci sequence.

Also, this exercise is a bit ambiguous as it is not clear whether they want the developer to generate the sequence or just return it.  Just returning it is presently sufficient, but then this leaves "Fibonacci" rather a red herring and hardly seems like a challenge worth bothering with.

**Comment by angelikatyborska** [comment]
Thanks for the input! Could you create this issue in the repository https://github.com/exercism/rust/ so that the right people see it, and close this one? It needs to be handled by the team @exercism/rust

**Comment by nilvon9wo** [comment]
Done: https://github.com/exercism/rust/issues/1309
