### ISSUE TITLE
Wren track shows "0 contributors" but it has contributors

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5722]
Wren track shows "0 contributors" but when I browse the contributors, there are people with profiles. 

But it's a bit weird that it only shows exercises authored. There's no PR rep for Wren? No "PRs merged", "PRs reviewed"?

![Screenshot 2021-09-03 at 13-32-55 Wren on Exercism](https://user-images.githubusercontent.com/7852553/131999300-cda03508-d479-4188-8dd9-6caaf485d118.png)

![Screenshot 2021-09-03 at 13-33-08 Exercism](https://user-images.githubusercontent.com/7852553/131999307-73f40047-67cb-4c6e-8321-f41ce4cdf0b3.png)

**Comment by iHiD** [comment]
There's two things here:
1. https://github.com/exercism/website/pull/1759
2. The data for Wren probably hasn't imported as the track got added manually post launch. I'll check now.

**Comment by iHiD** [comment]
@ErikSchierboom Let's explore this together when you're next on. I don't massively get it.

**Comment by joshgoebel** [comment]
Possibly related: https://github.com/exercism/exercism/issues/5608

**Comment by joshgoebel** [comment]
Ok, but I feel like @glennj and myself are still missing some PR credits perhaps - do they need to be tagged a certain way to count?  And Glenn has definitely authored a few exercises now that have been merged.  (as well as fixed a few bugs)

How do we prevent merging an exercise from counting twice as a PR & as a "exercise authored" or is that not a problem?

**Comment by iHiD** [comment]
> How do we prevent merging an exercise from counting twice as a PR & as a "exercise authored" or is that not a problem?

It's intentional that that happens.

> Ok, but I feel like @glennj and myself are still missing some PR credits perhaps - do they need to be tagged a certain way to count? And Glenn has definitely authored a few exercises now that have been merged. (as well as fixed a few bugs)

Yeah - that's a separate issue: https://github.com/exercism/exercism/issues/5749
