### ISSUE TITLE
Get 1 rep for publishing a concept exercise

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5723]
Currently you don't get any rep for publishing concept exercises. We're changing this to give 1 rep instead.

@ErikSchierboom We'll also need to backfill.

**Comment by ErikSchierboom** [comment]
This has already been implemented. See https://github.com/exercism/website/blob/main/app/commands/solution/publish.rb#L24-L30 and  https://github.com/exercism/website/blob/main/app/models/user/reputation_tokens/published_solution_token.rb#L6
