### ISSUE TITLE
Whitespace only changes do not trigger updates to git_important_files_hash

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5724]
I made a whitespace change to try and invalidate `git_important_files_hash`: https://github.com/exercism/clojure/pull/395

However, that did not update because Rugged does not see any change in the diff. I've debugged it down to the fact that Rugged ignores whitespace only changes. There are a few [configuration options](https://www.rubydoc.info/github/libgit2/rugged/Rugged%2FTree.diff) which could be causing this, but I could work out which caused it.

I'm not sure if we should consider this a bug or a feature, but we should actively decide and comment it accordingly (I could see it being both). 

Sidenote: This PR did trigger a reload: https://github.com/exercism/clojure/commit/ae6ec535d04db2d09d2044d5caf314e77eb20d4e

**Comment by ErikSchierboom** [comment]
The best solution for this would be to have a way to include these configuration/project files in the `git_important_files_hash`. We currently include the following files:

```ruby
[
  instructions_filepath,
  instructions_append_filepath,
  introduction_filepath,
  introduction_append_filepath,
  hints_filepath,
  *test_filepaths
]
```

We might also want to include the `editor_filepaths` too now that I think of it. 

For the project/configuration files, I think we would need a new filepaths entry in the exercise's `.meta/config.json` file. I think we might have discussed this on a call sometime, but I can't remember what the conclusion of that discussion was.

**Comment by ErikSchierboom** [comment]
The `editor_filepaths` are no included in the import files hash. For the other files, there is [this issue](https://github.com/exercism/exercism/issues/5992).
