### ISSUE TITLE
Invite mentors to Slack

### ISSUE THREAD

**Issue by michallepicki** [exercism/exercism#5727]
There is a link to Slack at the bottom of [How to give great feedback](https://github.com/exercism/docs/blob/50bcff91e8871f08b9a69b76ccbd45e5a90493dd/mentoring/how_to_give_great_feedback.md)

Maybe I'm missing something but I think it doesn't make sense to include the link that is not a slack invitation link?

**Comment by michallepicki** [comment]
Makes sense, thanks. Not sure what's the threshold to be considered a "mentor", I did only 3 sessions, but I think the page is visible for anyone that never even mentored. In fact it's public to anonymous users as well. Maybe it could mention having to register and start mentoring to be invited to access slack.

**Comment by iHiD** [comment]
The way v2 worked was that you received an invite as soon as you signed up to be a mentor. I'll probably do the same here. Agree about having to register on the docs. I'll update. Thanks.

**Comment by michallepicki** [comment]
Searching the web for "exercism slack" brings up two links to old documents, they 404 on the new page though, previewing copy shows that they said something about having to be invited. Here are the links:
https://exercism.io/mentoring-guide
https://exercism.io/mentoring-faqs

**Comment by iHiD** [comment]
Doc updated :+1:

**Comment by henry-js** [comment]
I know on the C# track, it's still pointing potential contributors/mentors to gitter

**Comment by iHiD** [comment]
> I know on the C# track, it's still pointing potential contributors/mentors to gitter

Got a link pls? I know it point students to gitter, but it should be pointing mentors to Slack.
