### ISSUE TITLE
Help documents are nowhere to be found in the web editor

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5730]
People solving any exercise in the web editor don't see the content of `<track>/exercises/shared/.docs/help.md` anywhere or the global help document (can't find it ATM).

When you download the same exercise via the CLI, you get a `HELP.md` document that consists of a few different files, including those two.

As a result, a user in the web editor has no idea what to do when they're stuck, which can happen. They cannot ask for mentoring until the tests pass.

**Comment by iHiD** [comment]
I'm calling this a bug. I think we should have a button on the [...] menu for "Get Help" which opens a modal with this in. The only thing then is to ensure that the help.md content doesn't container CLI specific info everywhere.
