### ISSUE TITLE
Test succeeds locally but fails in online editor

### ISSUE THREAD

**Issue by tsvng** [exercism/exercism#5731]
I'm, currently trying out the Dart track via local machine. When I execute the test on local, it succeeds but when I submit it says my iteration is incorrect.

I then try executing the same exact code via the online editor and tests fail noting that "an error occurred". 
Please see attached image.

![image](https://user-images.githubusercontent.com/24418304/132041819-8b64bed1-69eb-46a7-94ef-cd41aacaed8a.png)

**Comment by SleeplessByte** [comment]
Same as #5657

**Comment by angelikatyborska** [comment]
I'll close this because it's a duplicate but as you can see, it's an urgent bug that we'll fix soon!
