### ISSUE TITLE
"How you solved it" requires some mental gymnastics

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5736]
When in the mentoring context, pressing "how you solved it" surfaces your solution, which is _great_. However, if you want to stay in the same context, you must middle click/open in new tab , followed by a click on "show in editor" or "your iterations". 

Would be nice to keep it more contextual inside the editor.

**Comment by iHiD** [comment]
1. Maybe we link straight to iterations?
2. Inside mentoring UI is harder due to space restrictions, but I mean it's not impossible!

**Comment by junedev** [comment]
+1 for a direct link to the code
