### ISSUE TITLE
UI: Yes/no buttons should be on one line

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5739]
Snap:

<img width="249" alt="Screen Shot 2021-09-03 at 12 05 01 PM (1)" src="https://user-images.githubusercontent.com/6473/132050857-7afb83a2-1995-4b72-a584-312dfff37ca0.png">

@iHiD

**Comment by iHiD** [comment]
Tagging as urgent.

**Comment by bobahop** [comment]
One thing I noticed is that if I were careless and accidentally double-clicked on the "popup" for ending the discussion I might be very close to clicking one of the "Do You Want to Mentor" buttons if the popup disappeared between clicks.
