### ISSUE TITLE
analysis tab is empty after submission.

### ISSUE THREAD

**Issue by Stqs** [exercism/exercism#5740]
Steps to reproduce:
1. Submit solution
After this I can see robot icons (1 red and 1 yellow) near my solution. Analysis tab contains some info
2. Fix issue, submit again
I still can see 1 red robot but analysis tab is now completely bank. 

Refresh of the page didn't help.
Exercise: https://exercism.org/tracks/elixir/exercises/high-score

**Comment by angelikatyborska** [comment]
For reference, I mentored @Stqs on that exercise and I was able to see the comments in the mentoring UI, so they definitely existed and were not empty.

**Comment by iHiD** [comment]
I've run your code for the two iterations and see this
<img width="1412" alt="Screenshot 2021-09-03 at 23 20 26" src="https://user-images.githubusercontent.com/286476/132070521-ef1815a0-5576-443c-8e35-6ad41bc844be.png">
<img width="1418" alt="Screenshot 2021-09-03 at 23 21 24" src="https://user-images.githubusercontent.com/286476/132070580-4b0b02ea-3263-43be-bab8-31c01c1e3e3a.png">

Could you send me a screenshot of what you see instead please?

**Comment by iHiD** [comment]
And maybe a screenshot of the developer console in the browser?

**Comment by iHiD** [comment]
OK. Yeah. I can reproduce.

@kntsoriano: https://www.loom.com/share/f580c60ce6b248a69ab3ceb6f5ae0d18
