### ISSUE TITLE
First time issue github workflow error

### ISSUE THREAD

**Issue by jakubdabek** [exercism/exercism#5747]
https://github.com/exercism/exercism/pull/5667 introduced an apostrophe `'` into the message and it doesn't parse now, resulting in errors (for some reason I got notified about that workflow when submitting my first issue)

**Comment by BigMoonTech** [comment]
I was notified about that workflow error when I sent my first issue too. a couple hours ago... It was supposed to be a nice little message when submitting your first issue. I read the message in the yml file though. It WAS nice lol

**Comment by iHiD** [comment]
Should be fixed now. Thanks.
