### ISSUE TITLE
Assign rep to Wren contributors

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5749]
See https://github.com/exercism/exercism/issues/5722

**Comment by iHiD** [comment]
@ErikSchierboom I'm not sure what I need to run to make this happen. Educate me.

**Comment by ErikSchierboom** [comment]
Could it be that the Wren track was only activated _after_ the pull requests syncing was run? If so, that would mean it would be fixed by importing the prs and syncing the track, which we periodically do. 

That would explain why it is now correct:

![image](https://user-images.githubusercontent.com/135246/132333774-16dc0e82-0c7e-4a89-beb1-a954cf77c1cc.png)

![image](https://user-images.githubusercontent.com/135246/132333926-00f44329-f0b3-4f7d-a61c-d4d4e1c62754.png)

**Comment by ErikSchierboom** [comment]
The PR counts do look off, so I'm gonna look into that.

**Comment by iHiD** [comment]
Fixed?

**Comment by ErikSchierboom** [comment]
Nope, doesn't look like it: https://exercism.org/contributing/contributors?track_slug=wren

**Comment by iHiD** [comment]
```
track = Track.find('wren')
Github::PullRequest::SyncRepo.('exercism/wren')
puts Github::PullRequest.where(track: track).count
Git::SyncTrack.(track)
User::ReputationToken::AwardForPullRequests.()
```

**Comment by joshgoebel** [comment]
What is exercise contribution vs exercise authorship?

**Comment by glennj** [comment]
I assume that's in the exercise config.json:
```json
$ cat ~/src/exercism/tracks/wren/exercises/practice/hello-world/.meta/config.json
{
    "blurb": "The classical introductory exercise. Just say \"Hello, World!\"",
    "authors": ["joshgoebel"],
    "contributors": [
    ],
...
```
But I'll leave the definitive answer to others.

**Comment by joshgoebel** [comment]
Ah, yes... so it's just whoever adds themselves?  I wasn't aware that many people had added themselves to the `contributors` keys in Wren though... since I've reviewed all those PRs.

**Comment by glennj** [comment]
```bash
$ find ~/src/exercism/tracks/wren/exercises/ -name config.json | xargs jq -r '.contributors[]' | sort | uniq -c | sort -nr
      2 tejasbubane
      2 ryanplusplus
      2 ovidiu141
      2 matthewmorgan
      2 ankorGH
      2 SleeplessByte
      1 tarunvelli
      1 msomji
      1 kytrinyx
      1 draalger
      1 ZacharyRSmith
      1 WebCu
```

**Comment by joshgoebel** [comment]
Oh wow, then I stand corrected I guess. :)

**Comment by ErikSchierboom** [comment]
Is this issue still relevant? I do see rep being awarded to wren contributors: https://exercism.org/contributing/contributors?track_slug=wren Or is there something missing?

**Comment by iHiD** [comment]
@joshgoebel Closing this due to no response, but pls reopen if something still needs doing.
