### ISSUE TITLE
The prior sessions mentored is perhaps off by one?

### ISSUE THREAD

**Issue by kotp** [exercism/exercism#5750]
![image](https://user-images.githubusercontent.com/16747/132074058-69e15698-ffae-43ee-aa96-617dd675da4a.png)

But then, when I click on it, it shows 2 instead of 1.

![image](https://user-images.githubusercontent.com/16747/132074100-c856949a-7c80-44c2-a23b-85da8969dbdc.png)

**Comment by iHiD** [comment]
Yes. There's an open PR for this I believe, that just need a few tweaks to sign off.

**Comment by kotp** [comment]
Indeed, when it says that I have previously mentored on one occasion, there is nothing to let me see it.
