### ISSUE TITLE
Queue numbers apparently off by one.

### ISSUE THREAD

**Issue by kotp** [exercism/exercism#5756]
![image](https://user-images.githubusercontent.com/16747/132079352-17861e8a-a855-4e49-91ba-de0b7e554660.png)

There are 3, but it reports 2.

**Comment by kotp** [comment]
Unless it is reporting the kind of exercise as 2, and it so happens the total is just different by 1.

**Comment by iHiD** [comment]
Is this still an issue?

**Comment by kotp** [comment]
I just looked at what is there and it appears to be accurate now.
