### ISSUE TITLE
Return to previous page when clicking 'x'

### ISSUE THREAD

**Issue by Minification** [exercism/exercism#5757]
When mentoring and I have made my comments, I would like to return to the queue. However, clicking the 'x' in the left hand upper corner does not take me back to the queue, but rather takes me back to the landing page for mentoring. I think this is unexpected because an 'x' like that in a webapp is associated with a modal, which is why I expected the same behaviour.

So, first, I see this:
![before](https://user-images.githubusercontent.com/3757010/132081418-1b962cc8-c3e4-4381-b4bb-04beb39bec28.png)

Then I click on the 'x', and see this:
![after](https://user-images.githubusercontent.com/3757010/132081439-2487e501-628f-47fb-9957-d25a289cf391.png)

When I would have expected to get back to the **exact** queue that I was mentoring. In this case, the "Allergies" queue.

**Comment by joshgoebel** [comment]
This is a duplicate of another issue I believe, so this is something we're looking into.

**Comment by Minification** [comment]
Hi Josh, you're completely right. I didn't see bobahop's issue while scrolling until after I used the search feature. My mistake.
