### ISSUE TITLE
Cannot unlock Nullability in C# 

### ISSUE THREAD

**Issue by davyzhu** [exercism/exercism#5758]
Hi, Nullability require "Memory Allocation". But I cannot find "Memory Allocation" in C# Syllabus. Any suggestion, thanks!
![image](https://user-images.githubusercontent.com/149704/132084464-28fed0c1-f48b-4da2-a155-c0ff4099c3d7.png)

**Comment by angelikatyborska** [comment]
@exercism/csharp It looks like you didn't create an exercise for memory allocation

**Comment by Willz42** [comment]
I think the "Dictionaries" exercise in c# is  is similarly unreachable currently - it requires "[indexers](https://exercism.org/tracks/csharp/concepts/indexers)" (reached by guessing the URL) which I don't see in the syllabus view, and has no exercises.
The [dictionaries learning activity](https://exercism.org/tracks/csharp/exercises/International-Calling-Connoisseur) has three prerequisite exercises that I've completed, but it's still locked.

**Comment by ErikSchierboom** [comment]
Thanks! Will be fixed in https://github.com/exercism/csharp/pull/1588

**Comment by iHiD** [comment]
@Willz42 Is this now fixed for you?

**Comment by iHiD** [comment]
(@ErikSchierboom Should this be closed now?)

**Comment by Willz42** [comment]
@iHiD thanks- looks like everything is reachable now

**Comment by SleeplessByte** [comment]
Oh woops. The original one isn't merged yet. RE-OPENING :D

**Comment by SleeplessByte** [comment]
Sweet. Nice. Thanks @Willz42 !
