### ISSUE TITLE
Learning exercise "guidance" tab in mentoring UI should show the exemplar solution

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5764]
For learning exercises, the _exemplar_ (not to be confused with the _example_ solution for practice exercises) is by definition the intended way to solve the learning exercise so it would be good to have it there.

**Comment by SleeplessByte** [comment]
Also removes the need for it to be inside the mentoring notes. Right now there are none-to-little for concept exercises so it's still good to do ;)

**Comment by iHiD** [comment]
Done via https://github.com/exercism/website/pull/1786

No syntax highlighting for now, but you could maybe open another issue for that when you've verified the actual code shows pls?
