### ISSUE TITLE
In Practice mode, Concept exercises are visible on the overview tab.

### ISSUE THREAD

**Issue by jiegillet** [exercism/exercism#5767]
In Practice mode, Concept exercises cannot be found from the search field "Exercises" tab, even though they can be accessed from the "Overview" tab (but are super hard to find obviously).

<img width="1280" alt="Screen Shot 2021-09-05 at 0 18 21" src="https://user-images.githubusercontent.com/16929078/132099502-65864aa5-dde2-47b8-bd82-9be15ec7287a.png">

<img width="1280" alt="Screen Shot 2021-09-05 at 0 18 40" src="https://user-images.githubusercontent.com/16929078/132099515-65f6bb02-f02e-4efb-b4c4-a2801b9172e6.png">

**Comment by iHiD** [comment]
The bug is actually the other way around. They shouldn't be visible on the overview page in practice mode. I've updated the title accordingly and will fix. Thanks :)

**Comment by iHiD** [comment]
I've changed my mind - they should show in both places in Practice Mode.
