### ISSUE TITLE
Link to create a new mentoring notes leads to 404

### ISSUE THREAD

**Issue by jmrunkle** [exercism/exercism#5769]
For example:

> This exercise doesn't have any mentoring notes yet. Mentoring notes are written by our community. Please help get them started for this exercise by sending a [Pull Request on GitHub](https://github.com/exercism/website-copy/edit/main/tracks/java/exercises/bird-watcher/mentoring.md).

This is what that link takes you to:

![Screenshot 2021-09-04 08 43 15](https://user-images.githubusercontent.com/4332810/132100248-2e6d511a-cc9e-4c89-8ac8-7b824440f779.png)

Changing the URL from github.com/exercism/website-copy/**edit**/main/tracks/java/exercises/bird-watcher/mentoring.md to github.com/exercism/website-copy/**new**/main/tracks/java/exercises/bird-watcher/mentoring.md seems to get the job done.

**Comment by iHiD** [comment]
@kntsoriano The link should be different for creating a new file, and editing the existing file. At the moment the link is only correct for editing.
