### ISSUE TITLE
Your Journey: Navigating to Publishing from Mentoring makes controls disappear

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5776]
I have 9 pages of Publishing contributions. If I am on page 13 or higher of Mentoring and I choose the Publishing Category, all of the controls disappear.

Page 13
![err_1](https://user-images.githubusercontent.com/32035397/132111370-4ae0c869-ea62-492c-a8f8-cb2c05329ca4.JPG)

If on Page 12 of Mentoring and choose Publishing I get this

![err_2](https://user-images.githubusercontent.com/32035397/132111420-d2aa94ba-5992-40ab-aadf-6ee61e4cb082.JPG)

If I then click on Page 1 I get the 9 pages as usual.

**Comment by iHiD** [comment]
@kntsoriano I imagine there's a bugsnag for this you can find.
