### ISSUE TITLE
Exemplar solution in "guidance" in mentoring UI lacks syntax highlighting

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5781]
![Screenshot 2021-09-05 at 12-30-44 Exercism](https://user-images.githubusercontent.com/7852553/132123805-04bfae9c-f029-4a71-bf2c-4cc7825f61f0.png)

**Comment by iHiD** [comment]
Thanks. Yes, this was the tradeoff of getting this added quickly. We'll get this done at some point, but I'll treat it as a lower priority than other issues.
