### ISSUE TITLE
List of contributions doesn't have a meaningful ordering

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#5783]
When I visit https://exercism.org/journey/reputation, I see a lonng list of contributionns, which do not have any meaningful ordering.

Onn the first page there are some items that are 3 years old, then has a 2 year old item and then more from 3 years ago follow.

The last page has items from 3 years ago and 5 years ago.

The second last page mostly has 6 year old items.

**Comment by iHiD** [comment]
They are probably ordered in the order that they were created on the system (which is probably loosely down to grouping by repo). We can probably tweak this, but I believe it's an ETL issue, rather than an ongoing on.

**Comment by iHiD** [comment]
@ErikSchierboom I feel like this got resolved. Could you check pls?

**Comment by ErikSchierboom** [comment]
Yep, this has been solved.
