### ISSUE TITLE
Items in "my contributions" are not always clickable

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#5784]
I'd like to revise my contributions on https://exercism.org/journey/reputation.

Some of the items are clickable, others aren't.

Why is this like this?

**Comment by iHiD** [comment]
Do you have an example of some that are not clickable pls?

**Comment by angelikatyborska** [comment]
@iHiD All the "you contributed to..." are links without `href`s:
![Screen Shot 2021-09-05 at 19 02 50](https://user-images.githubusercontent.com/7852553/132135205-8014f148-eb1f-47c6-8869-83c0f1e55713.png)

**Comment by iHiD** [comment]
@angelikatyborska Thank you. Fixed by https://github.com/exercism/website/pull/1810 - I'll also need to bust some caches so if it's still broken an hour after merging, I probably forgot to do that and would appreciate a nudge.

**Comment by SleeplessByte** [comment]
(idk if this is now also fixed in the notifications, but it was the same bug)

**Comment by iHiD** [comment]
Notifications different bug (probably similar forgetting to implement though). Could you open another issue pls? (sorry!)

I'm reopening this to remind me to run the script btw.

**Comment by iHiD** [comment]
These should be fixed now.
