### ISSUE TITLE
Reputation

### ISSUE THREAD

**Issue by mahbub-ul-islam** [exercism/exercism#5786]
There said reputation can gain from publishing.
But I have 3 reputations and publish new some new solution and yet my reputation hasn't increased.

Also, I would like to see all the badges and how to get them.

**Comment by dhovart** [comment]
I don’t care that much for points but it indeed seems that awarding +1 in reputation when publishing solutions seems to be broken.
I successfully submitted 12 solutions to the rust track, published them all but only got reputation points for 2 of them.

**Comment by iHiD** [comment]
Hello. You currently don't get rep for publishing Concept Exercises, only Practice Exercises. There is an issue to change this (it was a deliberate decision but we've changed our minds)

**Comment by dhovart** [comment]
Thank you for the clarification! I saw the change today.
