### ISSUE TITLE
Your Journey - Solutions - Started - Showing x solutions...  doesn't

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5787]
Showing 8 solutions? Ummm, no.

![err_1](https://user-images.githubusercontent.com/32035397/132129268-5360c01f-aa61-4036-8af5-5f90a296efa4.JPG)

**Comment by iHiD** [comment]
Is there a particular set of states where this happens? Or can you never see any solutions?

**Comment by glennj** [comment]
I can see my own started solutions. They were all started in v2.

**Comment by iHiD** [comment]
@kntsoriano Can you see a bugsnag for this pls?

**Comment by bobahop** [comment]
Sorry, if I am on a page higher than the highest Started page when I go from All to Started I get the blank controls. So, if I am on page 2 of All and choose Started I see no controls. If I am on page 1 of All and choose Started I see the controls. So this is a similar problem as [issue 5777](https://github.com/exercism/exercism/issues/5777).

**Comment by bobahop** [comment]
FYI, I just experienced being on page 1 of Solutions - All and in choosing Completed the controls disappear, even though I should have a page 1 for Completed. Although that is distinct from this issue and issue #5776. I'm not sure if it merits a separate issue. It seems the general issue is weirdness in changing filters on this page.
