### ISSUE TITLE
Mentoring request broken for an exercise

### ISSUE THREAD

**Issue by andinus** [exercism/exercism#5789]
This is related to C track's gigasecond exercise. Prior to v3, I had
pushed my solution and requested mentoring on it. After the migration,
it says that it's waiting for a mentor but when I try to view the
mentoring request it returns "500 error occurred" page.

It also doesn't take up any mentoring slots.

**Comment by iHiD** [comment]
Thanks for reporting. I'll take a look for you a little later.

**Comment by andinus** [comment]
I think it might have something to with earlier there being 4
mentoring slots (3 for optional + 1 for exercises) before the
migration.

**Comment by iHiD** [comment]
Linked: https://github.com/exercism/exercism/issues/5713

**Comment by iHiD** [comment]
Running a script to update. Will close this. Please reopen if it's still an issue. Thanks for reporting 🙂

**Comment by andinus** [comment]
Thank you :)
