### ISSUE TITLE
Python: Spyder: Some tests not returning rest message when run in spyder.

### ISSUE THREAD

**Issue by Malte-G** [exercism/exercism#5791]
Some of the tests of the Python track do not  return Error/Success messages when run locally in Spyder(4.1.5) in the usual form of:

"Ran 11 tests in 0.007s

OK"

I have noticed this with conditionals_test.py, strings_test.py and exchange_test.py thus far while grains_test.py is running fine.

The exercises can still be solved and submitted online via the API.

**Comment by angelikatyborska** [comment]
cc @exercism/python

**Comment by BethanyG** [comment]
@Malte-G 👋🏽   _Python track maintainer here..._  Thank you for logging this.

I am not sure how you are invoking the tests, but I _suspect_ the reason you are seeing differences between the `concept exercises` (_conditionals_test.py, strings_test.py and exchange_test.py_) vs the `practice exercises` (_grains_test.py, etc._) is that `concept exercises` now rely on some features of [PyTest](https://docs.pytest.org/en/6.2.x/) as a test runner whereas the practice exercises can be run using either Pytest or [unittest](https://docs.python.org/3/library/unittest.html).

You will need to have [Pytest installed](https://docs.pytest.org/en/6.2.x/getting-started.html) either globally, or inside the virtual env you are using for `exercism`.  Once that's done, there are a variety of ways you can call pytest and have it run tests and report results:

1.  From the Python Console in Spyder, after navigating to the exercise folder:
     `!pytest -v <exercise test file>.py` if pytest is **in** the venv.  
     `!python -m pytest` **or** `!python -m pytest -v` if pytest is installed _globally_
2.  Via the [spyder-unittest plugin](https://www.spyder-ide.org/blog/introducing-unittest-plugin/), which has a pretty spiffy UI:
      
![image](https://user-images.githubusercontent.com/5923094/132138542-edcb7f2f-f855-42b4-aaa0-54cfbd0a2dbf.png)
3.  Via the terminal _outside_ of spyder:
     (**with the venv active**) in the exercise directory --  `pytest -v <exericse test file>.py`
     (**with a global pytest install, and an appropriate Python install**) in the exercise directory  -- `python pytest -v <exericse test file>.py`

 I tested the above methods using spyder 4.1.5 in a `conda env` running Python 3.8.  If you'd like to use Python 3.9, I think that spyder 5.1 is out.  BUT spyder 5.1 does not support spyder-unittest as far as I know.

Let me know if any of those work for you, and what method you are using to run the tests.

**Comment by Malte-G** [comment]
@BethanyG 

Hi thank you for your help. I ve managed to get everything working again as per your instructions, by installing Pytest and the spyder-unittest plugin. 

I have also updated Python from 3.7.4 to 3.8.8 aswell as Spyder to 4.2.5

Option 1 and 2 of testing work for me now.  I havent gotten around to testing the third one yet.

As for your question how I used to run the tests. I simply had the  `<exercise test file>.py` open in Spyder and whenever I wanted to run the tests I switched to that tab in spyder and ran the testfile by pressing F5.

With Pytest and the unittest plugin installed  I have now switched to using the plugin via Alt+Shift+F11.

**Comment by BethanyG** [comment]
@Malte-G - I am so happy I was able to help! Great to hear you are back up and running, albeit with a plugin and different hotkey combo.  It's  also awesome that the Spyder Python terminal options worked - thank you for giving those a go.  😄 

>As for your question how I used to run the tests. I simply had the <exercise test file>.py open in Spyder and whenever I wanted to run the tests I switched to that tab in spyder and ran the testfile by pressing F5.

One of the big downsides of our decision to go with a `PyTest` dependency is that things no longer "magically" work for people running tests.  `unittest` is part of Python, so its installation is somewhat invisible, and invocation is also pretty seamless.  Unfortunately, `PyTest` requires a whole installation cycle and its own flags.   But it has some really nice features we just couldn't live without.  It's also pretty much standard as a test framework and runner in industry -- so learning its quirky ways doesn't hurt.  Apologies that we surprised you with it though.

Hopefully now you can get back to enjoying problem-solving on exercism!  Let us know if there is any additional help you need, or if you have further questions.  Happy coding 👋🏽 .

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this issue, as it appears to be solved. @BethanyG if there's anything actionable for the Python track, would you ensure that there's an open issue for it?

**Comment by BethanyG** [comment]
Linking up [Python Issue #2953](https://github.com/exercism/python/issues/2953), just to make sure we have a record.  Docs still need better clarification, and automatic download of the `init` is still in process.
