### ISSUE TITLE
Enable selecting download command

### ISSUE THREAD

**Issue by elshize** [exercism/exercism#5793]
Hi, great job on Exercism v3!

I'd like to make a suggestion for a minor UX change. In the new version, I cannot simply select and copy the link to download an exercise (under "Work locally (via CLI)"). The only option is to click to copy. A problem with this is that I disable javascript's access to the system clipboard for security reasons. It would be nice if I could somehow select the link and copy it myself.

I realize this might be a niche use case. Nevertheless, I want to document it so that you're aware of it.

**Comment by iHiD** [comment]
That's an annoying bug! Fixed it here: https://github.com/exercism/website/pull/1811

Sidenote: You got like a 10x response rate by writing such a nice issue. Thank you for that - it's really appreciated 💙

**Comment by elshize** [comment]
Thanks @iHiD :rocket:
