### ISSUE TITLE
Um, "Best practices writing feedback trrrrrruuuuunnnncaaatteeee" ?

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#5794]
![image](https://user-images.githubusercontent.com/122470/132137887-61a527ed-101d-414d-924a-b0ac28f4a805.png)

**Comment by iHiD** [comment]
@kntsoriano Almost certain there's an issue for this somewhere, but I can't find it.

Pls link to https://exercism.org/docs/using/feedback/guide-to-being-mentored with the title "Making the most of being mentored" and the date "1 Sept 2021" and delete the other two.
