### ISSUE TITLE
[Mentoring Queue] Student Able to Request More than Their Max Mentoring Slots

### ISSUE THREAD

**Issue by BethanyG** [exercism/exercism#5802]
Noticed this on the Python Queue.  Not Clear if it is this user account, or the queue in general, but they currently appear to have 12+ exercises in the queue for mentoring -- all from a short time period.
https://exercism.org/mentoring/queue?track_slug=python&order=recent

![image](https://user-images.githubusercontent.com/5923094/132143335-2f307a87-91a3-4a9a-91fe-9dd934a18e0f.png)

![image](https://user-images.githubusercontent.com/5923094/132143354-aa51967f-294a-4d12-84f9-68352ed5d561.png)

**Comment by iHiD** [comment]
The issue here was the person was already in negative equity of slots. And we were checking for zero not for zero or negative.

**Comment by BethanyG** [comment]
Not sure if this is because the change to the queue logic was recent an not retro-active, or there is a follow-on issue, or ... I am just hallucinating this morning here in CA...  screengrab taken Tue Sep 7 at 10:22 Pacific.

![image](https://user-images.githubusercontent.com/5923094/132385734-19bca6f6-153e-42d9-abb4-29502043fd9a.png)

**Comment by iHiD** [comment]
Yeah, it wasn't retroactive. I can do so, but I didn't want to delete people's requests if they'd written something useful in them.
