### ISSUE TITLE
Analyzers spinning forever when test-runner is disabled to run

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5803]
When #5657 was solved, test-runners no longer could get stuck when not implemented/active. This is good, yay. But the Analyzer waits for the test-result. Oh nay!.

This results in the analyzer being in the waiting state forever.

When there is no test runner, don't run the analyzer.

**Comment by iHiD** [comment]
@ErikSchierboom Is this still a bug?

**Comment by ErikSchierboom** [comment]
Nope, this has been resolved by https://github.com/exercism/website/pull/2621
