### ISSUE TITLE
Items in notifications dropdown are not always clickable

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5804]
See #5784, https://github.com/exercism/exercism/issues/5784#issuecomment-913240136

**Comment by iHiD** [comment]
@SleeplessByte For this did you mean the notifications one or the reputation-notifications one? I interpreted what you said to mean the first at the time, but I realise now you maybe meant the second?

**Comment by SleeplessByte** [comment]
No, meant the first

**Comment by iHiD** [comment]
In that case, do you have an example of one which isn't clickable pls? I can't find any myself.

**Comment by SleeplessByte** [comment]
Not anymore :P but when I have another one...

**Comment by iHiD** [comment]
I'm going to close this pending us finding an example in which case pls reopen! 🙂
