### ISSUE TITLE
Changing to Practice Mode is not reflected on the tracks page

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5807]
It shows this on https://exercism.org/tracks

![info_1](https://user-images.githubusercontent.com/32035397/132155822-41e783dd-659a-49a5-8318-412f1fdcf974.JPG)

even though it's this on https://exercism.org/tracks/python. It's not just Python where this happens.

![info_1](https://user-images.githubusercontent.com/32035397/132155918-111012e8-64c9-452c-8ac8-4f0c1b63158e.JPG)

**Comment by angelikatyborska** [comment]
Does a full page reload help? It could be the same issue as https://github.com/exercism/exercism/issues/5634

**Comment by bobahop** [comment]
Thank you for the suggestion, but the tracks page still shows "Learning Mode" for 7 of 10 solutions which are all in Practice Mode.

![err_1](https://user-images.githubusercontent.com/32035397/132258486-f845c522-61c1-4ee6-9f36-627a6645d9aa.JPG)
![err_2](https://user-images.githubusercontent.com/32035397/132258488-8b01caee-9c89-4809-926a-51cd6489681a.JPG)

**Comment by iHiD** [comment]
I hadn't actually intended to change that on the main tracks page. That is more of an indication that it's available rather than that you're in it, but I get that that's really confusing.

I feel like we should probably just remove the tag from tracks you've joined on that page - I'm not sure the info being on that page adds much. Thoughts?

**Comment by SleeplessByte** [comment]
I'd personally wouldn't have styled them the same if that was the goal.

You can see a track has learning mode when you click it. You likely search for features and languages anyway.

You might want to make it a filter tho!

**Comment by bobahop** [comment]
If it's easier to remove it then sync it I think that would be fine.

**Comment by iHiD** [comment]
@ErikSchierboom Don't show "Learning mode" tag on **joined** tracks on this page.
