### ISSUE TITLE
exercism download --uuid=  returns "Error: This solution could not be found"

### ISSUE THREAD

**Issue by mofrisch** [exercism/exercism#5808]
I tried this on Windows and Ubuntu. Whenever I try to download a file for mentoring, this happens.

**Comment by mofrisch** [comment]
I will move this to exercism/cli.

**Comment by SleeplessByte** [comment]
I'll re-open it here. `exercism/cli` is the correct spot, but it's possible that it has nothing to do with the CLI and rather the website itself.

Taggin @iHiD

**Comment by mofrisch** [comment]
see #5819

**Comment by angelikatyborska** [comment]
I'm experiencing this issue for every solution that I would want to mentor too. CLI 3.0.13, `"apibaseurl": "https://api.exercism.io/v1"`. I'm not 100% sure what is the correct one, I edited it a few times when testing with staging.

**Comment by iHiD** [comment]
Should be fixed by https://github.com/exercism/website/pull/1836 which should deploy soon.
