### ISSUE TITLE
Old solutions from v2 have not had the tests run on them.

### ISSUE THREAD

**Issue by danilo-bc** [exercism/exercism#5810]
I use Exercism since V2. With the new interface, I tried running my complete exercises with the new interface to check the new features. All exercises I tried on the Julia track are stuck as the image below.

![image](https://user-images.githubusercontent.com/7863971/132247533-e5599e9f-b837-46de-bd15-aed5e0ce7c5f.png)

I can try another track (like Python) later to see if it's track-related or OS/browser related.

Running on Fedora linux and Firefox browser.

**Comment by angelikatyborska** [comment]
I see the same for my old Elixir solutions. I don't think is track-specific. I think this just means that the job to run the tests for your old solution hasn't started yet. I think @iHiD already started the jobs to run tests on all the old solutions but there are so many that I don't know how long that would take?

**Comment by danilo-bc** [comment]
Great point. I see the interface is slightly different from my solutions to mentoring submissions. As if the ones that recently came to mentoring pass automated tests, where my own solutions have not passed through them.

**Comment by angelikatyborska** [comment]
Yes, solutions submitted after v3 was released get tested immediately.

**Comment by iHiD** [comment]
> think @iHiD already started the jobs to run tests on all the old solutions but there are so many that I don't know how long that would take?

I only ran solutions that had been submitted to mentoring. 

I can't easily run the rest yet, as doing so would block the main runners, and I don't have a way to split them into a seperate bank of test runners. Also, if we ran them in sequence they would take about 150 days to run. So we'd need say 10 servers churning away full time to get them done in the next couple of weeks. That's doable so I'll probably do it, but I need a way to put them in a seperate queue etc first.

**Comment by iHiD** [comment]
I'll leave this open to remind me to do it :)

**Comment by danilo-bc** [comment]
Alright, no problem!

Thank you!

**Comment by iHiD** [comment]
@ErikSchierboom We should do a check of how many solutions have not got test results, both in cloudsearch and the database and rerun them (on the background queues!!)

**Comment by ErikSchierboom** [comment]
> (on the background queues!!)

LOL

**Comment by ErikSchierboom** [comment]
@iHiD For a start, we should probably run the tests on published solutions on tracks that do have a test runner and where the solution does not have a test run queued. Something like:

```ruby
Solution.published.joins(exercise: :track).where(published_iteration_head_tests_status: :not_queued, exercise: {tracks: 
{has_test_runner: true}}).count
=> 45387  
```

Note that in production, `45387` solutions match this query.

Once that query has run, we can do the same for the head tests status.

After that has run, we can do the cloudsearch part of this.

**Comment by ErikSchierboom** [comment]
To run a test run in the background, would we do something like `Submission::TestRun::Init.(submission, run_in_background: true)`?

**Comment by iHiD** [comment]
Yep - that all sounds good.

**Comment by ErikSchierboom** [comment]
The published solutions have now all been processed. Some solutions weren't being processed properly (and the status did not update), which meant they would keep showing up in queries. There were two reasons for this:

1. There were 100 or so solutions that were published, but which did not have any active iteration. These solutions have all been unpublished using: `Solution.published.where('NOT EXISTS (:active_iterations)', active_iterations: Iteration.select('1').where('solution_id = solutions.id').where(deleted_at: nil)).each {|s| Solution::Unpublish.(s)}`
2. There were 100 or so failing ones due to an exercise rename (the `go/census` exercise), and these have all had their solution's `published_iteration_head_tests_status` and `latest_iteration_head_tests_status` manually set to `exceptioned`.

**Comment by ErikSchierboom** [comment]
This should now be fixed.
