### ISSUE TITLE
Cannot change email or handle

### ISSUE THREAD

**Issue by danstewart** [exercism/exercism#5811]
Getting 500 errors when trying to change my email or handle.

Noticed the calls are going to: https://exercism.org/api/v2/settings/sudo_update 
Should this be updated to a v3 endpoint now?

May also be related to #5661 since my account is linked to GitHub, but I don't see an error message:
![image](https://user-images.githubusercontent.com/10670565/132249890-67b7c433-d423-46fc-8511-90cd286407c7.png)

**Comment by angelikatyborska** [comment]
Did you try the workaround suggested in that issue? This one: https://github.com/exercism/exercism/issues/5661#issuecomment-911598839

**Comment by danstewart** [comment]
@angelikatyborska It did, thank you - sorry I missed that.

**Comment by angelikatyborska** [comment]
Great! That probably means that your issue is identical to https://github.com/exercism/exercism/issues/5661
