### ISSUE TITLE
Unable to see comments from mentor

### ISSUE THREAD

**Issue by vmrocha** [exercism/exercism#5813]
When accessing an exercise that I submitted on the old version of exercism, the counter on the title (Mentoring 1) says that I have 1 comment from a mentor, but the message at the bottom says "You have no past mentoring discussions".

User handle: vmrocha
Track: Ruby
Exercise: Leap
Page address: https://exercism.org/tracks/ruby/exercises/leap/mentor_discussions

I'm sure I have a feedback from kotp, but the UI is not showing it.

**Comment by iHiD** [comment]
Is this better now?

**Comment by vmrocha** [comment]
Yes! Now I have an "Open discussion" button. Thank you!
