### ISSUE TITLE
download --uid= broken in 3.013?

### ISSUE THREAD

**Issue by mofrisch** [exercism/exercism#5819]
I installed 3.0.13 on both Windows and Ubuntu and the download says "Error: Exercise not found." After installing 3.0.12 it works fine.

**Comment by mofrisch** [comment]
Actually, it does not. Now it says it has downloaded it, but the users directory is empty.

**Comment by iHiD** [comment]
Should be fixed by https://github.com/exercism/website/pull/1836 which should deploy soon.

**Comment by glennj** [comment]
@iHiD Is this currently (16:06 Canada/Eastern time) in a state of deployment? I'm seeing:
```bash
$ exercism download --uuid=fb963dee58a04972bc5ecf3fefec154c
Error: You do not have permission to view this solution
```

**Comment by iHiD** [comment]
@glennj See https://github.com/exercism/exercism/issues/5827#issuecomment-914607866

**Comment by glennj** [comment]
@iHiD This UUID is a solution that I am mentoring. It's at the top of my Awaiting student list.

**Comment by iHiD** [comment]
😞 

Will sort it in the morning. Sorry.

**Comment by iHiD** [comment]
Let's try again with: https://github.com/exercism/website/pull/1844

**Comment by iHiD** [comment]
FYI: I thought this method was done: https://github.com/exercism/website/pull/1844/files#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29bR186

It is done for a different part of the solution (submissions), but not for the top-level solution

**Comment by mofrisch** [comment]
It works! 👍

**Comment by glennj** [comment]
Yay! https://github.com/PaulDance/xr can now run again

**Comment by iHiD** [comment]
Great. Sorry it took a while :)
