### ISSUE TITLE
Accessibility: Need clear indicator whether solution has passed

### ISSUE THREAD

**Issue by serezlan** [exercism/exercism#5820]
Hello,

When I checked my solution, my screen reader announce  "Processing status passed" once after page load. I try to find where that word but could not find where it came from.
It would be great if we could add accessible indicator of the solution  status.  I assume it is already in the page but not yet accessible.

Thanks

**Comment by SleeplessByte** [comment]
The status indicator on the page only has a green dot and the word "Passed". What would help you? We can change it/add it!

Do you want it to live announce when it changes (It should), and if yes, what else should happen?

**Comment by serezlan** [comment]
There is a button which my screen reader read "Processing status". Perhaps that's what you meant?


``` html
<div class="c-iteration-processing-status --passed" role="status" aria-label="Processing status"><div role="presentation" class="--dot"></div><div class="--status">Passed</div></div>
```


I think SC extract info from area-label. Perhaps you can modify it to also has the word"passed" or something like that..?

**Comment by SleeplessByte** [comment]
Right. So instead make it like this? (removed all unrelated attributes):

```html
<div 
  role="status"
  aria-label="Processing status: passed">

  <div role="presentation"></div>
  <div role="presentation">Passed</div>
</div>
```

Have a single `aria-label` with the entire processing status? The reason we didn't do that before is so that it wouldn't read processing status: passed, passed, but it sounds like it's confusing because visually it's not clear that that's the processing status, and thus moving the content into a single label will help finding it on the page. Is that correct?

**Comment by serezlan** [comment]
Yes, that's right.
I can confirm that SC does pick up aria-label.

If this approach conflict with other arrangement, I'd be happy to help you exploring other possibilities.

**Comment by serezlan** [comment]
CMIIW:
Does the processing status passed mean it has passed test or it has been approved by mentor?
I was under impression the latter and that is what I'm looking in the page.

**Comment by SleeplessByte** [comment]
Understood. It means the tests have passed!

There is no mentor approval in v3.

**Comment by serezlan** [comment]
Ok. Then we can close this.
Thank you.
