### ISSUE TITLE
"I am not getting reputation for authoring an exercise"

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5822]
![image](https://user-images.githubusercontent.com/1964376/132333950-b456daa8-8104-4711-888a-4126d48f8cbb.png)

I authored/contributed that JS exercise and both those TS exercises, but my name is missing from the TS exercises and I also didn't get any reputation.

- Knapsack: https://github.com/exercism/typescript/commit/0a816f5c9eb833eabd0809394eff8bfb83c6ab1d#diff-72c802345e9356685776c0d45e8fefd084a45bf5b88dd8a9b1fe38dbfabf949bR3-R4
- DnD Character: https://github.com/exercism/typescript/commit/5a1ce7ed44d70f08c3186417d823593e56013167#diff-b4f0c7df36285180f16b37cb9ba40a6f2e94c3a7b7df104c86c39c4190cf959fR3

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/1829 (although that PR needs fleshing out by Erik).
I'll manually rerun the sync for now to check that fully fixes the issue.

**Comment by iHiD** [comment]
Also linked: https://github.com/exercism/exercism/issues/5825

@SleeplessByte I think any new exercises published post-launch should now be correct.

**Comment by ErikSchierboom** [comment]
@SleeplessByte And this shouldn't happen in the future: https://github.com/exercism/website/pull/1829/files

**Comment by ErikSchierboom** [comment]
![image](https://user-images.githubusercontent.com/135246/132522912-182cd1aa-6bba-41d7-8bbd-fdf0452533d5.png)

Looks good now. I'm closing this.
