### ISSUE TITLE
Tracks on profile outdated

### ISSUE THREAD

**Issue by mpas97** [exercism/exercism#5824]
Looking at my profile I can only choose between "All tracks" and "Haskell".
1. I left Haskell including reset a few days ago -> it shoud not appear here anymore
2. My main track Elixir is not even showing up

![grafik](https://user-images.githubusercontent.com/9994218/132343870-ba38a652-53a3-4e15-8b2b-ff1ce9433068.png)

**Comment by angelikatyborska** [comment]
Is it possible that you have 2 points of Haskell reputation that aren't for publishing solutions? E.g. a merged PR or mentoring. Resetting a track wouldn't remove those so it would still appear in this list. And do you have any Elixir reputation points already?

**Comment by mpas97** [comment]
I had two Haskell solutions that were removed by the reset. Now I see zero solutions and this map:
![grafik](https://user-images.githubusercontent.com/9994218/132347204-3ea67f24-96de-4d3b-8f92-6577d89c3c45.png)

And yes, I have submitted dozens of Elixir solutions and earned reputation for them. You can also see it in the description (11 rep total - 2 haskell = 9 Elixir)
