### ISSUE TITLE
Exercise UUIDs are hidden for published solutions

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#5827]
By design, I'm sure. 

This issue is tangentially related to the current `exercism download --uuid` problem. 

The `exercism help download` text says in part
> Download other people's solutions by providing the UUID.

This is currently not possible, except in a mentoring context.

Can we get the download and copy buttons available to the general public for all published solutions?

**Comment by iHiD** [comment]
What's the use case for doing that? Why do you want to download someone else's solution?

**Comment by angelikatyborska** [comment]
Related discussion: https://github.com/exercism/exercism/issues/5816

**Comment by glennj** [comment]
Ah, it's a duplicate. Closing.

**Comment by iHiD** [comment]
The other one is for mentoring downloads. This one is for community ones. The mentoring ones should be fixed, but the community ones are not :)

**Comment by iHiD** [comment]
Urgh! Sorry - this is a duplicate. I got my issues mixed up. Re-closing.
