### ISSUE TITLE
Clojure lasagna concept missing project.clj

### ISSUE THREAD

**Issue by Steffan153** [exercism/exercism#5832]
![Screenshot_20210907_161617](https://user-images.githubusercontent.com/40404519/132417773-823f75be-0f13-475d-8439-ee32538f534e.png)

I see someone like just enabled the concepts, but...?

**Comment by SleeplessByte** [comment]
Sorry! test-runner isn't merged yet. Will come tomorrow.

cc @exercism/clojurescript @porkostomus

**Comment by porkostomus** [comment]
Yes that was my mistake. I was so excited about getting the Concept exercises rolled out that I enabled them too soon!

**Comment by Steffan153** [comment]
Ok, so now that I started lasagna and concepts were disabled again now everything is locked except lasagna and the ones I did in v2 smh

**Comment by porkostomus** [comment]
I did the same, got stuck so then I reset my progress thinking that might unlock them but nope... Something I did likely broke it but I tried reverting my changes and am out of ideas. We'll have to debug this later when more people are up.

**Comment by Steffan153** [comment]
I do find all the locking a bit annoying personally anyway though, because say in JS, I have to do all these concepts I already know to do the other practice exercises that I could do freely in v2. Just my opinion though.

**Comment by porkostomus** [comment]
I thought there were 2 different modes, "Learning Mode", and something else, to customize that behavior but I could be mistaken.

**Comment by Steffan153** [comment]
You're right, I forgot about that.

**Comment by ErikSchierboom** [comment]
We're almost there to fix this issue! We'll keep you updated.

**Comment by ErikSchierboom** [comment]
@Steffan153 @porkostomus and I have worked together to fix the issue and have managed to do that! There are two things you need to do for this fix to apply:

1. Go to the exercise page at https://exercism.org/tracks/clojure/exercises/lucians-luscious-lasagna, where you'll see a message at the top stating that there are changes:

![image](https://user-images.githubusercontent.com/135246/132472069-2252a29c-55ca-46cb-bf7b-d0dc1ac0e410.png)

Click on the "See what's changed" link and in the resulting popup, click on the button to update the exercise. Once you've done this, the tests will be updated.

2. The second step is to change the `(ns exercism.lasagna)` code at the top of your implementation file to `(ns lucians-luscious-lasagna)`. 

With these two changes, everything should be working as expected. Can you try out the above steps and let us know if they resolve your issue?

**Comment by Steffan153** [comment]
Thanks, that worked.

**Comment by Steffan153** [comment]
So now I'm doing another concept and it thinks I failed because I got 0 wrong. Submit button is disabled and etc. ?????

![image](https://user-images.githubusercontent.com/40404519/132605344-3aa06a7e-2fed-4bb8-916d-b60fb62bc2d1.png)

**Comment by porkostomus** [comment]
This is related to https://github.com/exercism/clojure-test-runner/issues/20. A fix is in process :)
