### ISSUE TITLE
How long should I wait for the tests to complete before thinking something may be wrong?

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5836]
### Discussed in https://github.com/exercism/exercism/discussions/5834

<div type='discussions-op-text'>

<sup>Originally posted by **Urkchar** September  8, 2021</sup>
"This usually takes 5-20 seconds."
Most times that I submit an iteration seem to take so much longer than 20 seconds that I'm wondering if I'm doing something wrong. I understand that it takes time to run thousands of users' tests. But it's not really clear to me where the slowdown is occurring. 
Some examples of why it's taking so long are as follows. 
Perhaps my code itself is slow.
Perhaps the system is backed up with lots of test requests.
Perhaps the testing suite is just slow. 
Perhaps the tests have already ran but I'm not told that they are complete. </div>

**Comment by iHiD** [comment]
> But it's not really clear to me where the slowdown is occurring.

@Urkchar Me neither! :)

Could you answer the following pls?
- Do the tests finally update when you're looking at the page, or do you wait a while then refresh, they the results appear?
- Are you using the online editor or the CLI? If you're using the online editor, are the tests fast in the editor?

**Comment by Urkchar** [comment]
> * Do the tests finally update when you're looking at the page, or do you wait a while then refresh, they the results appear?
I have never seen the tests complete, even after refreshing the page. I even left the tests for Hello World on the Python track running overnight and they didn't complete. I then refreshed the page and they weren't complete. 
> * Are you using the online editor or the CLI? If you're using the online editor, are the tests fast in the editor?
I am using the CLI.

**Comment by iHiD** [comment]
Could you send me a screenshot of where this issue shows up on your python/grains exercise please? According to the database everything should be fine, so I need to understand where the UI is failing.

Re your hello-world, that's a duplicate of https://github.com/exercism/exercism/issues/5810

**Comment by Urkchar** [comment]
> Could you send me a screenshot of where this issue shows up on your python/grains exercise please? According to the database everything should be fine, so I need to understand where the UI is failing.
The tests finally completed on python/grains when I checked today. Here is an example of another Python exercise that's having what appears to be the same issue. 
![image](https://user-images.githubusercontent.com/49205496/132773760-0c0bccb0-538e-448e-92a8-1d3ace4326cc.png)

> 
> Re your hello-world, that's a duplicate of #5810
It sounds like old submitted v2 solutions will get tested but it will take some extra time.

**Comment by iHiD** [comment]
The two-fer also seems like a duplicate of #5810 as it's a v2 solution?

**Comment by Urkchar** [comment]
Yes, it is also a v2 solution. It appears as though the issue I'm having may only be happening with v2 solutions. Shall I try submitting a v3 solution to see what happens?

**Comment by iHiD** [comment]
Yes please :)

**Comment by Urkchar** [comment]
> Yes please :)

I have submitted a v3 solution for Little Sister's Vocabulary, `strings.py`. You can view it here https://exercism.org/tracks/python/exercises/little-sisters-vocab 
All the tests passed on the site instantly. 
Let me know what else you'd like to know about this experience.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this as a duplicate, since both issues mentioned are tracked elsewhere. Thanks for the report!
