### ISSUE TITLE
All clojure exercises locked

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5837]
### Discussed in https://github.com/exercism/exercism/discussions/5830

<div type='discussions-op-text'>

<sup>Originally posted by **gitrdm** September  7, 2021</sup>
In the Clojure track, I completed and exercise and went to start the next exercise. However, all of the exercises are now locked. This includes exercises that were previously unlocked. I don't know how to proceed from here. How do I get the exercises unlocked></div>

@gitrdm I've turned this into an issue here. Please let me know if you're still experiencing problems.

**Comment by gitrdm** [comment]
This seems resolved. It looks like there was a change to the system happening at the same time I was trying to make progress. All of the previously unlocked exercises are still locked, but checking just now, I see where I have been forced onto the learning path which includes some new unlocked exercises.

**Comment by SleeplessByte** [comment]
Sweet @gitrdm. Let us know if you can progress after you've completed one or multiple exercises, so this can be closed with confidence.
