### ISSUE TITLE
Csharp test runner fails on Booking Up For Beauty

### ISSUE THREAD

**Issue by CodeVelo** [exercism/exercism#5841]
Track: csharp
Exercise: booking-up-for-beauty

Using the CLI, I submitted a solution this is passing local tests:

```
❯ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  BookingUpForBeauty -> C:\src\github\codevelo\exercism\csharp\booking-up-for-beauty\bin\Debug\net5.0\BookingUpForBeauty.dll
Test run for C:\src\github\codevelo\exercism\csharp\booking-up-for-beauty\bin\Debug\net5.0\BookingUpForBeauty.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:    25, Skipped:     0, Total:    25, Duration: 27 ms - BookingUpForBeauty.dll (net5.0)
```

When I view the iteration on the website it reports that all tests failed with the error `A test class may only define a single public constructor.`

**Comment by angelikatyborska** [comment]
Take a look at https://github.com/exercism/csharp/issues/1586 it's the same issue. You can add somthing there or just subscribe for updates.

I will close this one to avoid duplicates.

**Comment by Th3Kh3d1v3** [comment]
This one is having problems again for the for the two tests that check the afternoon based on "DateTime.Now".
