### ISSUE TITLE
Add out-of-date icon to exercise card/serializer, and filter to journey/solutions page.

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5843]
In v2 when going to the page for an exercise you could see that a version of the exercise newer than the your most recent solution had become available. Currently that info apparently does not happen. But that was suboptimal anyway. I think it would be nice to at least have a filter on the track's Exercises page which might be named something like "Outdated" for completed exercises which have a version newer than your most recent solution. There are probably even better ideas out there for that.

**Comment by bobahop** [comment]
Yes, that is one of the situations that prompted me to raise this issue.

**Comment by SleeplessByte** [comment]
Likely a problem that will go away given that for all new submissions you get the "exercise updated" dialog.

**Comment by bobahop** [comment]
@SleeplessByte  I'm not sure what that means. If I solved something four months ago and changed this month, how will I know?

**Comment by SleeplessByte** [comment]
I don't think you'll know. But if you solve something now and it's updated in a month, then, you will now.

**Comment by iHiD** [comment]
We've actually done 99% of the work for this. You'll notice in a few places (e.g. in the Mentoring Interface) that it does say out of date. However, it doesn't for your own solutions.

The two places we intend to add this are:
- A symbol anywhere where an exercise card is shown (e.g. the exercise page, a tooltip, etc).
- A filter option on your own solutions on the journey/solutions page.

**Comment by iHiD** [comment]
- [ ] https://github.com/exercism/exercism/issues/5853
- [ ] https://github.com/exercism/exercism/issues/5854
