### ISSUE TITLE
Students can 'cheat' to see the community solutions of exercises

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/exercism#5848]
https://user-images.githubusercontent.com/73734376/132652481-c97c0c80-c686-4224-a835-45fc29d907f9.mp4

**Comment by junedev** [comment]
Thanks for reporting! We already have an issue for this but it was hard to find because it was in another repo https://github.com/exercism/v3-beta/issues/258.

**Comment by iHiD** [comment]
Issue moved to https://github.com/exercism/exercism/issues/5850
Closing as duplicate. Thanks.
