### ISSUE TITLE
Submitting rust solutions doesn't work when external crates are involved

### ISSUE THREAD

**Issue by dhovart** [exercism/exercism#5849]
It seems like submitting rust solutions doesn't work when external crates are involved. Here's the output of why tests are failing when I attempt to submit a solution to for instance "gigasecond":

```
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
```

I tried first in the online editor and then thought maybe using the CLI would change something (heh 🤷‍♂️ ) but no luck.
I can't find a way to upload my Cargo.lock anywhere as the error message tells me to.

**Comment by diogovk** [comment]
I can confirm this is indeed the case.
Submitting Cargo.toml and Cargo.lock results in the following error:
```
building gigasecond: external crates not supported
```

**Comment by RJK0** [comment]
I have the same issue with another exercise:

**Comment by joshgoebel** [comment]
I just tried to use something I thought was part of the "standard" lib (very new to Rust, sorry)... I found it on the rust website but then I got this same error as well... but now I forget what it was, grrrr... I think `round` or `math` or something?

**Comment by iHiD** [comment]
The solution to this is to build "common" crates into the Rust Test Runner. We "just" need someone to do this work.

**Comment by iHiD** [comment]
Duplicate of https://github.com/exercism/rust/issues/1307

**Comment by christian-oudard** [comment]
I'm having the same problem

**Comment by dulimarta** [comment]
I got the same issue with the `dot-dsl` exercise. The online dashboard at `exercism.org` says my submission is missing `Cargo.lock` so I tried the following command:

```bash
exercism submit Cargo.lock src/lib.rs
```

I'm using exercism version 3.0.13

**Comment by iHiD** [comment]
> Why would the gigasecond exercise be written with the external chrono crate if the checker can't use it?

Because the exercise predates the checker by several years.

**Comment by dhovart** [comment]
Fixed by https://github.com/exercism/rust-test-runner/pull/27

**Comment by Monsterlander** [comment]
same issue with 

fn main() {
    println!("Hello, World!")
}

Error:

We received the following error when we ran your code:

WARNING: student did not upload Cargo.lock. This may cause build errors.
   Compiling hello-world v1.1.0 (/mnt/exercism-iteration)
warning: function is never used: `main`
 --> src/lib.rs:1:4
  |
1 | fn main() {
  |    ^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: `hello-world` (lib) generated 1 warning
error[E0425]: cannot find function `hello` in crate `hello_world`
 --> tests/hello-world.rs:3:46
  |
3 |     assert_eq!("Hello, World!", hello_world::hello());
  |                                              ^^^^^ not found in `hello_world`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `hello-world` due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by wglane** [comment]
Did anyone get this to work? I'm also running into this problem when using Crossbeam for some of the concurrency problems.

**Comment by MeerKatDev** [comment]
doesn't work on the online editor
> WARNING: student did not upload Cargo.lock. This may cause build errors. ....

**Comment by SleeplessByte** [comment]
Only these crates are available, by design: https://github.com/dhovart/rust-test-runner/blob/main/local-registry/supported_crates

Please refactor your solutions to only use these crates or request one via the forum or a new issue.

**Comment by MeerKatDev** [comment]
I was trying to use `num`

**Comment by SleeplessByte** [comment]
Please open an issue at: https://github.com/exercism/rust-test-runner/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

I'll make sure it stays open until someone looks at it.
It would be best to include the solution you've tried.
