### ISSUE TITLE
Can access community solutions even if exercise is locked

### ISSUE THREAD

**Issue by kntsoriano** [exercism/exercism#5850]
A locked exercise's community solutions can be accessed directly from the URL.

**Comment by jmrunkle** [comment]
Is this worth fixing given that the reference solutions are on GitHub?

**Comment by bobahop** [comment]
For those who learn best by example, I think it's okay for the community solutions to be accessed somehow. For some exercises it's been the only way for me to "get it."

**Comment by SleeplessByte** [comment]
I thought this was a feature and not a bug.

**Comment by angelikatyborska** [comment]
As I mentor, I find that very useful so I also think it's a feature, not a bug. Who wants to cheat will find a way anyway.
