### ISSUE TITLE
C# - Online tests are failing

### ISSUE THREAD

**Issue by CodeVelo** [exercism/exercism#5851]
Track: csharp
Exercise: hyper-optimized-telemetry

I started this exercise using the CLI. Local tests are passing:
```
❯ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  HyperOptimizedTelemetry -> C:\src\github\codevelo\exercism\csharp\hyper-optimized-telemetry\bin\Debug\net5.0\HyperOptimizedTelemetry.dll
Test run for C:\src\github\codevelo\exercism\csharp\hyper-optimized-telemetry\bin\Debug\net5.0\HyperOptimizedTelemetry.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:    33, Skipped:     0, Total:    33, Duration: 29 ms - HyperOptimizedTelemetry.dll (net5.0)
```

However, the online tests are failing with this message:

>An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.
>
>Please check your code, and if nothing seems to be wrong, try running the tests again.

**Comment by iHiD** [comment]
@CodeVelo: @ErikSchierboom will take a look for you. What's your exercism handle/username please?

**Comment by CodeVelo** [comment]
My exercism user handle is @CodeVelo. Thanks!

**Comment by ErikSchierboom** [comment]
@CodeVelo This is now fixed. You'll need to update your exercise on its exercise page. This should update the tests and with the updated tests everything should now work as expected.
