### ISSUE TITLE
Create new track for HTML/CSS

### ISSUE THREAD

**Issue by antoniasymeonidou** [exercism/exercism#5852]
I was looking around your amazing website and I was thinking that there is no part about HTML OR CSS.
I would like to help and create some content.

**Comment by iHiD** [comment]
Hello. Thanks for your interest in helping!

As neither HTML or CSS are turing complete languages, neither are currently appropriate for Exercism. If and when we loosen the rules about that, they'd definitely be two we would do, but for now, they'e not 🙂
