### ISSUE TITLE
Analyzer message not being shown on iteration screen

### ISSUE THREAD

**Issue by sevenseacat** [exercism/exercism#5855]
* **Track**: JavaScript
* **Exercise**: Gigasecond

Not sure if this is only affecting this one exercise so it might be a JavaScript analyzer issue, or maybe it's a more general problem. I'm not too familiar with the analyzer process.

I submitted this exercise and the analyzer reported I had one issue - but it doesn't actually tell me what the issue is, the "Recommended" section is blank.

<img width="1396" alt="Screen Shot 2021-09-10 at 12 17 06 am" src="https://user-images.githubusercontent.com/543859/132723673-5b09cfb5-c9db-4b03-8834-7f296376cb18.png">

There's no JS errors in the dev console, and the generated DOM node for that text element has no content.

<img width="587" alt="Screen Shot 2021-09-10 at 12 19 05 am" src="https://user-images.githubusercontent.com/543859/132724012-e0b2218b-d396-46e6-b176-c244e248cbbb.png">

My solution link: https://exercism.org/tracks/javascript/exercises/gigasecond/solutions/sevenseacat

**Comment by SleeplessByte** [comment]
It's very likely that I made a typo in the analyzer. We'll run this solution through the analyzer manually and figure it out.

Thanks for reporting!
