### ISSUE TITLE
Intermittent enumeration error for Concept exercises

### ISSUE THREAD

**Issue by bobbicodes** [exercism/exercism#5857]
Yesterday someone reported a bug on the Clojure Concepts landing page (https://exercism.org/tracks/clojure/concepts) where the number of Concepts was incorrectly listed as `0`. I confirmed this behavior by signing out and witnessing it myself - today however the issue seems mysteriously fixed.

**Comment by iHiD** [comment]
@ErikSchierboom Any ideas on this one? I'm guessing it's because changing the status of the exercise doesn't rerun the code in `app/models/exercise/taught_concept.rb`.

**Comment by ErikSchierboom** [comment]
Hmmm, I'd have to dig a bit deeper. Your suggestions sounds plausible.
