### ISSUE TITLE
Mentor Notes

### ISSUE THREAD

**Issue by AndrewLawendy** [exercism/exercism#5859]
Hello all,

I noticed that the exercise Annalyn's Infiltration; Javascript track is missing Mentor Notes
and I'd like to add it, I'm just confused about where should I create my PR, if you can help me.
PS: I sent an email but I was directed here

Thanks

**Comment by jmrunkle** [comment]
Generally speaking they go here: https://github.com/exercism/website-copy/tree/main/tracks/javascript/exercises

You make a sub-directory that matches the stub for the exercise and then add a file there called mentoring.md. If you look at other directories in there you will get the picture. When you look at the exercise page you should see the stub in the URL.
