### ISSUE TITLE
Reputation timestamps in wrong timezone

### ISSUE THREAD

**Issue by Steffan153** [exercism/exercism#5860]
![image](https://user-images.githubusercontent.com/40404519/132784355-7bff34f5-136b-465e-81fa-b9ad6bee334d.png)

I'm UTC-6.

**Comment by iHiD** [comment]
Duplicate of https://github.com/exercism/exercism/issues/5860 when @kntsoriano is fixing :)

**Comment by Steffan153** [comment]
It's a duplicate of itself?? :joy:

**Comment by angelikatyborska** [comment]
Haha, I think @iHiD meant https://github.com/exercism/exercism/issues/5620 :D

**Comment by iHiD** [comment]
I did!
