### ISSUE TITLE
All my solutions are 0 lines and 0 views?

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5862]
<img width="602" alt="Screen Shot 2021-09-10 at 1 55 03 AM" src="https://user-images.githubusercontent.com/6473/132806685-c5e19f3e-80c5-4f27-aab7-863b84fc21ce.png">

Some sort of caching or cron-job issue?

**Comment by joshgoebel** [comment]
Even exercises with multiples stars and comments are 0 views...

**Comment by iHiD** [comment]
@kntsoriano Can you hide those icons for now pls.
