### ISSUE TITLE
Can access "Community Solutions" tab even without permission

### ISSUE THREAD

**Issue by RuiL1904** [exercism/exercism#5867]
Simple as adding "/solutions" after the exercise url will lead us to the "Community Solutions" tab even without permission.
Example: https://exercism.org/tracks/python/exercises/meltdown-mitigation/solutions

**Comment by FaisalAfroz** [comment]
Yes I think a route guard could prevent that.

**Comment by ProProgrammer2504** [comment]
Duplicate of #5850

**Comment by angelikatyborska** [comment]
I'll close this one but feel free to continue the conversation in #5850
