### ISSUE TITLE
Exemplar solutions for concept exercises only show one file even if there are multiple that make up the solution

### ISSUE THREAD

**Issue by jmrunkle** [exercism/exercism#5871]
For example (java/remote-control-competition):

![image](https://user-images.githubusercontent.com/4332810/132937556-625d2f8c-7566-457a-817a-4b63a0f4a422.png)

There are 3 more files that make up the full solution and only one of them is shown.

**Comment by iHiD** [comment]
@kntsoriano I imagine this needs changing all the way through to the Git level. Basically search for `exemplar_file` and change it to `exemplar_files` and then at the two ends handle the fact that it's an array not a single file. Here's the examplar from JS: https://github.com/exercism/java/blob/main/exercises/concept/remote-control-competition/.meta/config.json#L16-L21

Pls tag @ErikSchierboom to review it when you're done.
