### ISSUE TITLE
Comment Editing: the end of the line

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5875]
When the END key is pressed while in the Comment box the cursor goes to the end of the paragraph instead of the end of the line. This is unwelcome when editing in the middle of a paragraph.

**Comment by bobahop** [comment]
The reverse happens with the HOME key, moving the cursor to the beginning of the paragraph instead of to the beginning of the line. It brings a little tear to my eye.

**Comment by iHiD** [comment]
@bobahop Is this issue the same as https://github.com/Ionaru/easy-markdown-editor/issues/189 ? If so, @ErikSchierboom do you want to try implementing the solution there and checking with Bob that it works for him as expected (via a Loom or something)?

**Comment by bobahop** [comment]
It appears to be the same issue.

**Comment by ErikSchierboom** [comment]
Weird. I can't reproduce this locally. What OS/browser setup are you using? And could you perhaps make a small Loom recording to show the issue?

**Comment by bobahop** [comment]
This happens in Chrome, Firefox and Edge. The way to reproduce is to type in a few sentences with no line breaks. Press the home key. Instead of the cursor going to the beginning of the line it is on (as it does in the editor I'm using right now in GitHub) it will go to the beginning of the paragraph. This happens when commenting in a mentoring session. When I have time I may try to do a video.

**Comment by bobahop** [comment]
With cursor at the end of a line, I press HOME and it goes to the beginning of the paragraph, not to the beginning of the line. I press END, and the cursor goes to the end of the paragraph, not to the end of the line.

https://www.loom.com/share/00f46203745f4e91963dc63f74afd0ab

**Comment by kotp** [comment]
I always thought this behavior was expected, due to HOME and END being line movement keys.  And typing a single line (even if it flows) is still a single line.

**Comment by bobahop** [comment]
You'll notice that editing in GitHub comment box that the HOME and END keys go to the beginning and end of the wrapped line and not to the beginning and end of the typed line. That's how it works in every other editor I've used.

**Comment by bobahop** [comment]
Pressing HOME and END while editing the above comment to show the expected behavior.

https://www.loom.com/share/d33b4ca27e0842e497afc6f995aedeea

**Comment by kotp** [comment]
I just tested it in my editor, and I think I know why I thought it was normal behavior for an editor.  It does exactly that, the HOME key and END key go to the beginning and end of the actual line even when that line is wrapped to visually show "lines".  I never considered that the Github comment box was an editor while I thought it was apparent that editor behavior was the intent for the Web Editor.

**Comment by kotp** [comment]
The issue does read "Comment Box" and so modeling after what github comments do is a fair goal.

**Comment by kotp** [comment]
I usually do use my local editor to make comments though.  Writing any lengthy and formatted content in a comment box is tedious, unless you are copy/pasting template responses.

**Comment by bobahop** [comment]
I do a mix of both. I may paste in a templated response, but then tweak it for the particular solution. The tweaking is a bit more tedious with the current behavior.

**Comment by ErikSchierboom** [comment]
Thanks for the detailed repro! I'll look into it.

**Comment by iHiD** [comment]
@bobahop Let us know if this is better now! :)

**Comment by bobahop** [comment]
Looks good! Thank you very much!
