### ISSUE TITLE
Notifications cannot be marked as read by hovering (reputation notifications can)

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5879]
The dots do not disappear when I hover over the notification. I do manage to mark them as read in other ways but since I cannot easily reproduce having an unread notification, I couldn't deduct yet how by trial and error.

![2021-09-12 16 05 54](https://user-images.githubusercontent.com/7852553/132990871-b5380452-6dfd-4cca-98f3-d974376d0cf4.gif)

**Comment by iHiD** [comment]
This is by design. Notifications should only be cleared when they are seen. Whereas reputation is cleared automatically. The rationale is that notifications are things you **need** to see, whereas reputation is for stuff that you've already done so know about.

**Comment by angelikatyborska** [comment]
I feel fooled 😁 I would have expected two very similar UI components right next to one another to work in a similar way. I think the fact that I have to reload the page for the orange notification indicator to go way added to the feeling that something's wrong.

I think in both cases I would expect the orange notification indicator and the per-notification dots to go away just because I opened the dropdown, like it disappears on Twitter and YouTube.

This UI element on the website for me is anyway just an addition on top of the emails that I get, which is what I actually use to mark what needs attention (unread) and what's done (read/deleted).

Anyway, if this is by design, I'll close the issue.

**Comment by iHiD** [comment]
>  I would have expected two very similar UI components right next to one another to work in a similar way. 

Yeah - agree with this.

> I think in both cases I would expect the orange notification indicator and the per-notification dots to go away just because I opened the dropdown, like it disappears on Twitter and YouTube.

Because notifications are all intended to be acted upon, we've instead followed GitHub's model of "you must click to dismiss", which I think is right, but I think having it next to the more transient reputation ones is definitely confusing.
