### ISSUE TITLE
Key features overflow cutoff at bottom

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#5883]
![image](https://user-images.githubusercontent.com/135246/129725044-e9bd5ca9-2325-435a-b230-3ad3b1ed61a8.png)

See https://exercism.lol/tracks/csharp/about

**Comment by iHiD** [comment]
@erikschierboom This is probably a quick one for you to do if you fancy a bit of responsive CSS fun. If not, reassign it to me.
