### ISSUE TITLE
Seemingly Account in Frozen State

### ISSUE THREAD

**Issue by herbedev** [exercism/exercism#5887]
Hi, I think theres something wrong with my account. Its like a frozen state. When ever I try and view the elixir track or continue it, it shows a 500 page. I log out - I can view all the pages. I log back. in - back to 500 error.

I am using Github to login to Exercism and have tried Safari, Chrome and Firefox and the issue persists across all 3 browsers and private modes. 

Account Handle is @herbedev

![Screen Shot 2021-09-14 at 7 18 45 AM](https://user-images.githubusercontent.com/26552444/133248285-62501ec7-a10b-45eb-a16e-9461a2a47182.png)

**Comment by iHiD** [comment]
This issue is caused by https://github.com/exercism/elixir-analyzer/issues/151. I'll fix it at the website-level shortly. Sorry for the pain!

**Comment by iHiD** [comment]
(Deploying now, @herbedev)
