### ISSUE TITLE
How to reset web-compiler to default code

### ISSUE THREAD

**Issue by AMOfficalGithub** [exercism/exercism#5889]
Ran into an issue where I took out what looked like a boiler-plate method in the Java tracked and I used `public static void main(String[] args)` instead. Now the code doesn't run but I know that doing a simple Hello World it would be correct.

How do I reset the compiler so that it goes back to the original code?

**Comment by angelikatyborska** [comment]
If I understood the problem correctly, you're looking for this option?

![Screen Shot 2021-09-14 at 18 26 44](https://user-images.githubusercontent.com/7852553/133296794-8eac3d2a-01d2-4f08-9e0f-0a19109e9f01.png)

**Comment by AMOfficalGithub** [comment]
Thank you, that works
