### ISSUE TITLE
excaping the error in the web ide is not always working

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/exercism#5894]
Hello, 

I try to solve the simple calculator in ruby and when I try my code I see this :

![afbeelding](https://user-images.githubusercontent.com/89863657/133379685-f2206612-030a-4473-b0c5-8849ae4361ac.png)

It looks to me that a part of the exception or error message is not displayed.
So I cannot know what I have to change to make things work.

Regards,

Roelof

**Comment by iHiD** [comment]
Which part of the error message would you expect to be displayed. That all looks normal to me, but I might be missing something.

**Comment by RoelofWobben** [comment]
As far as I know I was expecting to see something like

```
CalculatorValidation::UnsupportedOperation:  this operation is not allowed
```

**Comment by iHiD** [comment]
I'm not sure why your code would return "This operation is not allowed". I think what the test runner is doing is correct. If you can find some code that runs locally that returns this, but doesn't do the same in the online editor, please reopen this :)
