### ISSUE TITLE
Code blocks in exemplar solutions for mentors are not escaping HTML entitites properly

### ISSUE THREAD

**Issue by phate45** [exercism/exercism#5896]
Yesterday, i consulted the exemplar solution when mentoring a student ([exercise link](https://exercism.org/tracks/rust/exercises/low-power-embedded-game)) and got misled by missing generics.

Expected code ([link to raw](https://github.com/exercism/rust/blob/main/exercises/concept/low-power-embedded-game/.meta/exemplar.rs)):
```rust
pub fn evens<T>(iter: impl Iterator<Item = T>) -> impl Iterator<Item = T> {
    iter.enumerate()
        .filter(|&(idx, _)| idx % 2 == 0)
        .map(|(_, t)| t)
}
```

Exemplar solution on site (with a screenshot):
```rust
pub fn evens(iter: impl Iterator) -> impl Iterator {
    iter.enumerate()
        .filter(|&(idx, _)| idx % 2 == 0)
        .map(|(_, t)| t)
}
```
![image](https://user-images.githubusercontent.com/1895614/133393738-83ff77ca-ce3d-4b10-be8f-c2f1f73f9236.png)

Reading through the issues on this repository (and `exercism/website`), the only other relevant issue i found is this one:
https://github.com/exercism/exercism/issues/5863

**Comment by joshgoebel** [comment]
Pretty sure this is a dup... but I thought we might have fixed it already, but perhaps you found yet another place we aren't properly encoding the HTML - which means that the `<HTMLLIKE>` symbols (like templates) disappear when highlighting.
