### ISSUE TITLE
[Exercise: Commuity Solutions / Solution] - Order By Newest?

### ISSUE THREAD

**Issue by pertrai1** [exercism/exercism#5899]
I was expecting to see solutions from the newest to oldest. Seeing that the oldest are Outdated, it would be more useful for me to see newer solutions that are not outdated.

![community-solution-order](https://user-images.githubusercontent.com/442374/131226512-43e5c71f-0241-4fde-bfb9-caf3b567fd27.jpg)

**Comment by iHiD** [comment]
Is this fixed now?

**Comment by SleeplessByte** [comment]
@cjpearce you'll want to check out #5963 which describes your issue and potential solutions.

**Comment by iHiD** [comment]
@ErikSchierboom I think this can probably be closed now?

**Comment by ErikSchierboom** [comment]
Yep. We've changed community solutions to be ordered by number of stars (descendingly) and added the option to order by newest first.

![image](https://user-images.githubusercontent.com/135246/169261054-4411a089-22fa-485b-b205-2d8d547dbe29.png)
