### ISSUE TITLE
[Docs] Broken links on https://exercism.lol/docs/using/faqs

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5900]
These six links get RecordNotFound

![err_1](https://user-images.githubusercontent.com/32035397/130490078-abe55b07-5d56-49f5-83bb-c52be2aecea9.JPG)
![err_1](https://user-images.githubusercontent.com/32035397/130490560-c3e8a4ef-65bd-413c-9e04-685b68e436fe.JPG)

**Comment by moates** [comment]
I will also add another, on the Pronouns page: https://exercism.org/docs/using/settings/pronouns

> "....You can set your pronouns by filling in the blanks in a sample sentence on **your settings page**. We provide some common options for you to use, but you can write whatever you like....."

There is a broken redirect to https://exercism.lol/settings
