### ISSUE TITLE
Broken link on https://exercism.lol/docs/tracks

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5901]
![docs_error_1b](https://user-images.githubusercontent.com/32035397/130336300-003d0ed0-80f4-43f8-b85e-ebe8d6f640ae.JPG)
![Docs_error_1](https://user-images.githubusercontent.com/32035397/130336303-4470df1e-cc12-49a7-8793-a66de49532fe.JPG)

**Comment by iHiD** [comment]
Closing as duplicate of https://github.com/exercism/exercism/issues/5680
