### ISSUE TITLE
Reprocess Elixir snippets please

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5903]
Needed due to the bug fixed in https://github.com/exercism/snippet-extractor/pull/32

String interpolation was wrongly removed from snippets. This will affect a lot of solutions of many exercises.

**Comment by kytrinyx** [comment]
Did this get done?

**Comment by iHiD** [comment]
@ErikSchierboom Can you see if this can be closed pls, and if it still needs doing, do it.

**Comment by ErikSchierboom** [comment]
See https://github.com/exercism/exercism/issues/5761#issuecomment-1125015637

**Comment by ErikSchierboom** [comment]
We've just reprocessed all of Elixir's published iterations, and it looks like this did indeed fix the issue. See https://exercism.org/tracks/elixir/exercises/two-fer/solutions where there are now no longer any cutoffs.
