### ISSUE TITLE
[Page: Track] After leaving a track, that track is still shown as `Joined`

### ISSUE THREAD

**Issue by codeiotic** [exercism/exercism#5907]
https://user-images.githubusercontent.com/73734376/130777497-d75cbe5e-ef57-47c9-babd-8129e8d6897d.mp4

After leaving the Z3 track, the track still has the `Joined` label & is shown amongst my other joined tracks. But after refreshing the page, it no more shows the `Joined` label & it is not shown amongst my other joined tracks.

**Comment by iHiD** [comment]
@kntsoriano Some sort of caching need fixing here?

**Comment by iHiD** [comment]
@ErikSchierboom You were going to see if this was now already fixed with the update to React.
