### ISSUE TITLE
[Exercises] Deleting the Only Iteration should unpublish a solution

### ISSUE THREAD

**Issue by BethanyG** [exercism/exercism#5909]
Working with an exercise that has been both completed and published, but has only one iteration.

1.  Visit the exercise page, and click the [iteration] section/tab.
2.  Click the [...] in the Analyzer/Tests area and select [Delete Iteration]

The following displays:

![image](https://user-images.githubusercontent.com/5923094/128568161-2098359d-14a5-4fbc-b7b8-b665b331d99d.png)

3. Select [Delete Iteration]

The following displays:
![image](https://user-images.githubusercontent.com/5923094/128568542-2834918c-39d2-4694-a0f3-31fb437fbf19.png)

🔴   -expected a warning about the solution no longer being published (_there is no iteration **to** publish_).
🔴   -expected a warning about the exercise no longer being completed/answered (_there is no iteration to base those states on_).

4. Return to the exercise overview.

The following displays:
![image](https://user-images.githubusercontent.com/5923094/128568746-99b25240-98c5-431c-b60a-43f673788b17.png)

🔴  -expected to not have a "completed" message.
🔴  -expected to not have a "Your published solution" message/section

5.  Click on the "published solution" box
The following displays:
![image](https://user-images.githubusercontent.com/5923094/128568938-0cf71400-2f41-4457-b199-87b549231212.png)

🔴  -expected a message about there being no published solution, or better yet -- this page would not exist.

From here, the state feels more confused.  If I now return to the exercise and "open in editor", the deleted iteration shows back up.  If I then "submit", the result is now two iterations, not one.  While this makes sense from an app perspective (_after all, there are really two iterations ... we just deleted one of them_), it feels a bit weird from a user perspective.

![image](https://user-images.githubusercontent.com/5923094/128569419-5d741c60-86c8-46f0-a1c7-de7c9f6dfebe.png)

**Comment by iHiD** [comment]
@ErikSchierboom Assigning this to you. This is to do with deleting iterations on published solutions. There are two things that need to happen when an iteration is deleted.
1. When an iteration is deleted (`Iteration::Destroy`) and it was the published iteration (`solution.published_iteration_id == iteration.id`), then the solution should become unpublished (`published_at: nil`)
1. When an iteration is deleted (`Iteration::Destroy`) and there are no undeleted iterations remaining, it should be unpublished (`published_at: nil`) and uncompleted (`completed_at: nil`)
