### ISSUE TITLE
The favorite star is not gold on the previous discussions modal

### ISSUE THREAD

**Issue by kotp** [exercism/exercism#5918]
![image](https://user-images.githubusercontent.com/16747/133541839-affb2a97-9f51-418e-961d-f4abf6d82742.png)

In other views the star is filled in what appears to be a golden color.  In this view, it is empty, though favorite.

**Comment by angelikatyborska** [comment]
You already reported the off-by-one error here: https://github.com/exercism/exercism/issues/5750
