### ISSUE TITLE
Awaiting Student sorted oldest first, sort by dropdown says Recent First, selecting Recent First does nothing.

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#5924]
Because "Recent First" is selected, I can't select it to change the sorting without _first_ selecting something else _then_ selecting Recent first.

Related to #5688

**Comment by iHiD** [comment]
@glennj Are you saying that "Recent First" is selected, but the data is not ordered by Recent First?

**Comment by iHiD** [comment]
@kntsoriano I confirm this isn't working as expected. Please can you look at this?

**Comment by angelikatyborska** [comment]
@iHiD Yes, see:
![2021-09-17 09 01 19](https://user-images.githubusercontent.com/7852553/133766091-6988082f-78eb-498d-a04d-15a8e87aaaaa.gif)
