### ISSUE TITLE
Markdown renderer seems buggy

### ISSUE THREAD

**Issue by Steffan153** [exercism/exercism#5925]
From Python "Meltdown Mitigation", here's some perfectly normal Markdown code:
```
The percentage value can be calculated as `(generated_power/theoretical_max_power)*100`
where `generated_power = voltage * current`.
Note that the percentage value is usually not an integer number, so make sure to consider the
proper use of the `<` and `<=` comparisons.
```

The Markdown renderer seems to think the `*` in `voltage * current` is the start of a list:
![image](https://user-images.githubusercontent.com/40404519/133861007-1a091412-39d9-4eb3-b983-a597c2de7b2d.png)

**Comment by iHiD** [comment]
@ErikSchierboom Any ideas on this?

**Comment by ErikSchierboom** [comment]
Not really. I'll check

**Comment by ErikSchierboom** [comment]
I can't seem to reproduce this

**Comment by angelikatyborska** [comment]
I suspect this change to the exercise's instructions "fixed" the problem on https://exercism.org/tracks/python/exercises/meltdown-mitigation: https://github.com/exercism/python/commit/d2ddf8b6fd4e1923f44ff2226e6f0b791240b8b3#diff-c320232590d75eeeab6ecd0d3c0619e223bfbf89a8c351b54206e240e2b8780d

**Comment by iHiD** [comment]
Would be good to solve the underlying problem still. Maybe throw the MD at the top into a test-case and see how it comes out, Erik?

**Comment by ErikSchierboom** [comment]
@iHiD I extracted the relevant parts and did exactly that. It worked fine for me, so it is probably something with a newline or something. I'll dig deeper.

**Comment by Steffan153** [comment]
It's not on https://exercism.org/tracks/python/exercises/meltdown-mitigation it's only on the split in the edit page.

**Comment by iHiD** [comment]
It looks right in both places for me now. Are you definitely on the latest version of the exercise?

Either way, could you copy the source code of the rendered page for us pls? (In Chrome: Right click, Inspect, Elements, Right-click on <html>, Copy -> Outer HTML) and then paste it here and we can debug? Thanks :)

**Comment by Steffan153** [comment]
Ah, I wasn't on the latest version. I didn't know it had been fixed.
