### ISSUE TITLE
Account deletion option does not work as intended. 

### ISSUE THREAD

**Issue by ashshuota** [exercism/exercism#5926]
Choosing to delete an account seems to reset the account instead. All track progress and public profile are removed but the account still remains.

**Comment by SleeplessByte** [comment]
cc @iHiD 

Related but probably not same: #5930

**Comment by iHiD** [comment]
@ashshuota Could you try again now please? Thank you.

**Comment by ashshuota** [comment]
Does not seem to be working yet. Clicking on the "Delete account" button in the deletion prompt does not seem to be doing anything. I can't confirm if it is resetting the account instead as mentioned in the original issue since my account was reset the last time around.

**Comment by iHiD** [comment]
@ashshuota I see that it failed again, but I've also fixed what failed. You have a lot of old data on your profile, which no-one has tried to delete before. Sorry.

Once again please?

**Comment by ashshuota** [comment]
It worked! I was able to delete my account.

**Comment by iHiD** [comment]
Thanks @ashshuota - sorry that took a while.

Could I ask why you wanted to delete your account?

**Comment by ashshuota** [comment]
No particular reason. Was just trying things out.
