### ISSUE TITLE
I am unable to delete my Exercism account

### ISSUE THREAD

**Issue by danieltran-97** [exercism/exercism#5930]
I am trying to delete my Exercism account via Account settings. I type in my handle and press delete account but nothing happens.

**Comment by SleeplessByte** [comment]
Hi @danieltran-97 . What's your Exercism handle? 

Did you also fill in your password?

**Comment by danieltran-97** [comment]
Hi @SleeplessByte, is also **danieltran-97**. I do have my password set up for the account, is it meant to ask me to fill in my password when I delete my account?

**Comment by SleeplessByte** [comment]
cc @iHiD 

Yes I think it's supposed to not work without entering a password.

**Comment by danieltran-97** [comment]
Yeah after entering my handle to delete it doesn't ask me to input my password anywhere

**Comment by iHiD** [comment]
@danieltran-97 Sorry about this. There was a stray foreign key lying around from v2 that you ran into. Could you try again pls. There's a change you'll hit the same issue with a different key, but I'll chase it down again if so. Thanks.

**Comment by danieltran-97** [comment]
thanks @iHiD, it deleted successfully!

**Comment by iHiD** [comment]
Great :) 

May I ask why you wanted to delete it?

**Comment by danieltran-97** [comment]
Hey @iHiD, I deleted this account because I wanted to use the email of this account for my other account. Because my other account uses my old work email and it contains all of my progress.

**Comment by L483** [comment]
I have the same issue. After a few minutes of waiting after typing my handle and hitting the "Delete account" button, a text feedback appears below the "Cancel" and "Delete account" buttons: "Unable to delete account"

**Comment by L483** [comment]
Despite this, it looks like the site was, in fact, able to delete my account - although with a huge delay.
