### ISSUE TITLE
Python: passes locally, not online

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5931]
Here is the student's code

```python
from datetime import datetime, timedelta

def add(moment):
    gigasecond = timedelta(seconds=1000000000)
    return moment + gigasecond
```

The error was this

```
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```

**Comment by BethanyG** [comment]
Hi @bobahop  -- Thanks for logging this!

Since I've completed `gigasecond`, I went to the website and ran that code on a new iteration from the browser.  I had no issues.  I then downloaded a new copy of the exericse to my machine and submitted an iteration via CLI.  That also had no issues.

I did see this for Python for a `Gigasecond` submission.  I can't tell _which_ submission, but there was an error:

```
exceptioned Exception Details: 

------

 {"message"=>"No space left on device @ dir_s_mkdir - /opt/jobs/4f17391801bb4bdeb7bf8ed79065a481-f44357eba09efac9cc6c1d5f5ee47205", "backtrace"=>["/opt/rubies/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir'", "/opt/rubies/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'", "/opt/rubies/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'", "/opt/rubies/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'", "/opt/rubies/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'", "/opt/rubies/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:200:in `each'", "/opt/rubies/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'", "/opt/tooling-invoker/lib/tooling_invoker/process_job.rb:20:in `prepare_input!'", "/opt/tooling-invoker/lib/tooling_invoker/process_job.rb:12:in `call'", "/home/exercism/.gem/ruby/2.6.6/gems/mandate-0.3.0/lib/mandate/call_injector.rb:10:in `call'", "/opt/tooling-invoker/lib/tooling_invoker/worker.rb:84:in `handle_job'", "/opt/tooling-invoker/lib/tooling_invoker/worker.rb:33:in `block in start!'", "/opt/tooling-invoker/lib/tooling_invoker/worker.rb:16:in `loop'", "/opt/tooling-invoker/lib/tooling_invoker/worker.rb:16:in `start!'", "/opt/tooling-invoker/lib/tooling_invoker/worker_pool.rb:22:in `block (2 levels) in start!'", "/opt/tooling-invoker/lib/tooling_invoker/worker_pool.rb:22:in `fork'", "/opt/tooling-invoker/lib/tooling_invoker/worker_pool.rb:22:in `block in start!'", "/opt/tooling-invoker/lib/tooling_invoker/worker_pool.rb:21:in `each'", "/opt/tooling-invoker/lib/tooling_invoker/worker_pool.rb:21:in `start!'", "bin/start:30:in `<main>'"]}
``` 

Can you give me some more details?  Did the student encounter this problem more than once?  Did the tests eventually pass, or did the student get stuck?  When you try, do you have the same problem?

**Comment by bobahop** [comment]
I tried it myself with this code and it failed

```python
from  datetime import timedelta

def add(startTime):
    return startTime + timedelta(0, 1_000_000_000)
```

I had previously passed the tests with this code

```python
import datetime

def add(startTime):
    return startTime + datetime.timedelta(0, 1_000_000_000)
```

which prompts me to speculate if it has a problem with `from x import y`.

**Comment by BethanyG** [comment]
I don't think this is a problem with the Python code.  Both of those examples work for me without any issue -- both within the site editor, and after uploading via the CLI. 

I also fired up my local version of the Python Test Runner inside docker (which is how the website runs these tests).  Neither of those code examples failed or errored for me.

So I suspect this is an issue with the container on the site, or some issue where the upload itself is perhaps causing issues.

**Comment by bobahop** [comment]
Have you tried uploading another iteration to the site instead of locally? Or is there another way to diagnose the site container? I'm not knowledgeable about containers.

**Comment by BethanyG** [comment]
Yes.  I did try ... three? or so iterations uploaded.  I am not getting a top-level error.  I did get an error when forgetting to uncomment the `datetime` import...but that's an expected error.

**Comment by bobahop** [comment]
What OS are you on? I'm on Windows 10. Just wondering if different line terminators might play a role.

**Comment by BethanyG** [comment]
I'm on a Mac (MacOS Mojave 10.14.6).  I can fire up my windows 10 on parallels and see if it makes a difference.  

Although if it were line termination,  I would think **everything** would fail for you.  But it's only `gigasecond` -- yes?

Nevertheless, we probably should test.  It might take me a bit (_I don't think my windows 10 is up to date_ 😱).

**Comment by BethanyG** [comment]
@iHiD @ErikSchierboom  -- I still can't get anything I do to fail top-level, except purposely munging the import.  I don't know what the issue is, only that @bobahop  is hitting it, and I am not.  

I've left all my various attempts for the exercise in my account, Starting at `iteration 5`  Iterations 9-12 were uploaded from my Windows 10.1 VM .  Iteration 13 was edited in the browser.  The remainder of the CLI uploads were done via my Mac.

**Comment by iHiD** [comment]
This should now be fixed. Sorry for the pain.
