### ISSUE TITLE
Want to mentor student?  Accept/Decline

### ISSUE THREAD

**Issue by kotp** [exercism/exercism#5933]
The invite page when a student specifically requests mentoring does not specify the track nor the exercise.  So how do we know before clicking on accept or decline if we want to do either of those?

**Comment by iHiD** [comment]
Could you show a screenshot pls?

**Comment by angelikatyborska** [comment]
This is what I see for my own direct mentoring link (Elixir / Freelancer Rates) when logged out that suffers form the some problem. I don't have a link for somebody else's request so @kotp will need to provide that.

![Screen Shot 2021-09-22 at 18 51 37](https://user-images.githubusercontent.com/7852553/134387535-04ae40e9-7563-4823-89ce-8bd655691474.png)

**Comment by kotp** [comment]
It is very similar if not exactly the same (aside from the sign up for free/login portion).

Whomever can, please snapshot what results from here while logged in… and place it in a message here?

https://exercism.org/mentoring/external_requests/d7276130326c44e98b62c56dc8737885  (I assume this invalidates once someone accepts or denies it? Or perhaps only one someone accepts it.)

**Comment by angelikatyborska** [comment]
> Whomever can, please snapshot what results from here while logged in… and place it in a message here?

![Screenshot 2021-09-23 at 09-39-11 Exercism](https://user-images.githubusercontent.com/7852553/134470582-efb14407-c3bc-4a7a-bb05-da4d54cec584.png)

**Comment by kotp** [comment]
Thank you @angelikatyborska for the screenshot!

**Comment by 0xE282B0** [comment]
Hi, I came across this problem too.
When you get that link you have no idea what you should mentor before accepting the request.
@iHiD is there a way to support this improvement request?

**Comment by kotp** [comment]
Since @taiyab is assigned, that is probably the more correct 🐪 _bump_.

**Comment by axtens** [comment]
This is for https://exercism.org/mentoring/external_requests/82460f89d0224f6bb12a485aa7c3f120 which is me asking for help with my "Rotation Cipher" exercise in COBOL. However the recipient of the link has absolutely no idea what task nor what language. @iHiD @taiyab @ErikSchierboom  
![image](https://user-images.githubusercontent.com/209621/182279957-fcc0d2e5-640c-4cf4-8f32-803df75e5aac.png)

**Comment by taiyab** [comment]
Hey.

Thanks for this.

I'm addressing it now.

**Comment by taiyab** [comment]
@axtens @0xE282B0 @kotp @angelikatyborska Something like this work OK?
<img width="814" alt="image" src="https://user-images.githubusercontent.com/5337876/182663908-66385fef-83a7-4a75-9629-2bff1c314e54.png">

**Comment by kotp** [comment]
Awesome!  If there is a message that gets mailed out, what does that look like?

**Comment by iHiD** [comment]
What message would get mailed out?

**Comment by kotp** [comment]
Been "a minute" since I have been the sender of this.   So I did not know if I would get an indicator that I requested a private mentoring of this exercise, perhaps in my e-mail.

**Comment by kotp** [comment]
It would serve to remind me that I have requested a mentoring of it, and the link that was sent out.  Or at least that a private mentor link has been generated, so that I can forward it to whomever I would want to request mentoring from.

**Comment by iHiD** [comment]
I'm not sure I'm understanding. There's no action within our UI for you  request a private mentor. There's a link that you copy and send to someone, but we have no way of knowing when you've sent that link to someone.

**Comment by kotp** [comment]
Right, but we do have a way to know when the request a private mentor link is created.  That is the "reminder" message that may make sense to send once that is clicked with what the link is.

**Comment by kotp** [comment]
The action to copy the link to the users clipboard, which I assume is an action, and in the users interface.  It may not hit the database, but it is definitely an action that I have taken, and it is user side, and it is how I interface with the web.  (Not sure what User Interface means if that is not what that means.  And not sure what "action" means if by me taking an action with a click on the site does not include that action.)  But I do not do front end development, so we may have different definitions of these words.

**Comment by kotp** [comment]
For sure, I do not have to copy it, I click a button and it places it on my clipboard. On a non-javascript based website, I would probably have to select it to copy it.  Here I do not have to do that.

**Comment by iHiD** [comment]
A private mentor link is never explicitly created. It's part of the solution. As we don't know whether someone has actually sent the link to anyone, I don't think there's an action here we can trigger anything on.

**Comment by kotp** [comment]
When building the view to accept or not when you open the link that the student share with you, is there no way to find out what the language and exercise is from that information?

**Comment by dem4ron** [comment]
@iHiD it did not.
