### ISSUE TITLE
Your Journey page (/journey/reputation) doesn't calculate dates correctly

### ISSUE THREAD

**Issue by bobtfish** [exercism/exercism#5938]
The dates calculated for contributions are all `today` or `yesterday` on my view of this page, and most of these are wrong - many were several days ago.

Once I click through to the actual contribution then the date is calculated correctly.

**Comment by iHiD** [comment]
Could you send me a screenshot pls?

**Comment by bobtfish** [comment]
[image: Screenshot 2021-09-22 at 22.18.27.png]
Seems to only be a thing on the first page of my experience - the dates on
the most recent page are just fine.

**Comment by iHiD** [comment]
Screenshot didn't upload :(

**Comment by bobtfish** [comment]
<img width="1212" alt="Screenshot 2021-09-22 at 22 18 27" src="https://user-images.githubusercontent.com/42338/134477423-bd666bf8-71cf-407c-a86d-d7e70fc67edc.png">

**Comment by angelikatyborska** [comment]
I noticed similar problems on my own journey page. See:

https://www.loom.com/share/e2cb1ed82e7744d89d2e11605846fcb9

<img width="1792" alt="Screen Shot 2021-09-23 at 10 47 56" src="https://user-images.githubusercontent.com/7852553/134479044-a3ec62dd-cce5-4c39-80f5-74779fb1f7dd.png">

**Comment by iHiD** [comment]
Thanks both. The confusing thing with reputation is that we have two dates:
1. When you did the thing
2. When the rep was awarded.

We order this based on when the rep was awarded (so things that are knew to you to see at the top). But that then can then be confusing with the other date showing.

Regardless, there's clearly some bug(s) here, so I'll look into it :)

**Comment by kntsoriano** [comment]
@iHiD I'm confused as to what the correct fix for this should be.

We currently render `created_at` as the date of the reputation token.

Should we:

(1) Change it to `earned_on`?
(2) Just clear the cache?

**Comment by iHiD** [comment]
@kntsoriano I don't know what the actual bug is here (other than clearly something is off). I'll check in a bit :)

**Comment by kytrinyx** [comment]
We think this is fixed. @bobtfish are you still seeing this issue?

**Comment by bobtfish** [comment]
lgtm now!
