### ISSUE TITLE
`Share it` functionality not implemented in blog posts

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/exercism#5940]
The `Share it` button at the end of every blog post does nothing when it is clicked

![2021-09-20 (18)](https://user-images.githubusercontent.com/73734376/133982803-9b908901-87e5-46e3-87c1-53e8fcfd5154.png)

**Comment by iHiD** [comment]
@kntsoriano This should scroll to the top of the page and up the share dialog modal thing.

**Comment by kntsoriano** [comment]
@iHiD What should we do about this? I don't want to wrap this in a React component as we would lose SEO. We can do either of the following:

1. Clicking the link just scrolls up to the share button but does not open it.
2. Clicking the link opens the panel below it.

**Comment by iHiD** [comment]
Let's discuss this when we chat :)

**Comment by kntsoriano** [comment]
We didn't get around this.
