### ISSUE TITLE
Code formatting doesn't work within spoilers

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5942]
Spoilers are frequently used to show example solutions or hide some optional hints. Unfortunately their contents aren't formatted properly:

````
<details><summary>Spoilers</summary>
```julia
for n in 0:26
    @eval macro $(Symbol(:R, n, :_str))(s)
        rotate($n, s)
    end
end
```
</details>
````

results in

![grafik](https://user-images.githubusercontent.com/20866761/134070309-23944e46-ceb4-4fa0-b5b3-35b73614d67b.png)

I assume this is a bug with the underlying Markdown renderer and might be hard to fix.

**Comment by joshgoebel** [comment]
Did this work in v2?

**Comment by BethanyG** [comment]
This may or may not be helpful.  But I have found from experience on GitHub with spoiler tags and with mixed HTML/Markdown content that you need at minimum 2 carriage returns  between the markdown and the HTML or the parser has trouble.  I would give that a go.

**Comment by BethanyG** [comment]
with two returns between the HTML and the Markdown backticks, I was able to get this result in mentoring comments:

![image](https://user-images.githubusercontent.com/5923094/134074194-31085cb4-e5f4-445f-a43f-3aa8abdc95b6.png)


what that looks like in the comment textbox:

![2021-09-20_13-55-45](https://user-images.githubusercontent.com/5923094/134074502-4da64f19-43af-4669-b701-4869250f1966.png)

**Comment by SaschaMann** [comment]
Neat, that works. Thanks! Maybe the UI could show a warning tooltip?

The syntax highlighting only appears after refreshing when you update/change a comment like that but that's a separate issue I guess.
