### ISSUE TITLE
The syntax highlighting only appears after refreshing when you update/change a comment 

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5945]
When editing comments (mentor conversation) the syntax highlighting is broken until after you refresh the page.  

_What should happen:_

Syntax highlighting should be reapplied after the update is saved.

**Comment by angelikatyborska** [comment]
FYI you actually need to change something else than whitespace in the comment for the bug to kick in. Just clicking "edit" and "update" without changing anything doesn't trigger the bug. The code element is missing the `hljs` class after editing the comment.


![2021-09-21 12 39 02](https://user-images.githubusercontent.com/7852553/134156820-d30fd7fa-43f2-4280-b05a-779e6f1d1e8f.gif)


![Screen Shot 2021-09-21 at 12 42 22](https://user-images.githubusercontent.com/7852553/134157185-49b405a0-16c6-42e3-ac93-34735569650f.png)

![Screen Shot 2021-09-21 at 12 42 01](https://user-images.githubusercontent.com/7852553/134157192-ae87d5d1-3248-4694-a93e-8ef7ffdbe78a.png)

**Comment by joshgoebel** [comment]
> FYI you actually need to change something else than whitespace in the comment for the bug to kick in.

I'd guess somewhere there is logic that avoids doing the update if there are not [effective] changes, hence preserving the highlighting.  But yes make a real edit, and save, and highlighting gone.
