### ISSUE TITLE
Contributors page: mentor rep since launch does not seem to count when a track is chosen

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5948]
For example, I have 12 finished conversations for C from less than 7 days ago. Here are some...

![info_2](https://user-images.githubusercontent.com/32035397/134259495-89016464-b1ec-4ced-bebd-177f59a8807f.JPG)

 yet when C is chosen on the Contributors page, this is all that displays...

![info](https://user-images.githubusercontent.com/32035397/134259617-0c2936c2-0c2a-4a05-9ade-9ac7f6d79b17.JPG)

The good news is that when All Tracks is chosen it does seem to count the mentored solutions correctly.

**Comment by iHiD** [comment]
@bobahop Do you know for sure that any of these have finished the conversation their end and rated the mentoring (e.g. have you got a testimonial from any of them?) That will save me some time in debugging.

**Comment by bobahop** [comment]
Here are six C testimonials received within the last 7 days. Yet nothing shown for C track contributions.
![info](https://user-images.githubusercontent.com/32035397/134437812-e26c20bc-a7bc-48f7-8973-5b0d35abf23f.JPG)

**Comment by iHiD** [comment]
That's helpful. Thank you.

**Comment by andrerfcsantos** [comment]
Maybe related with https://github.com/exercism/exercism/issues/5842?
