### ISSUE TITLE
Solutions only pass test on the web editor

### ISSUE THREAD

**Issue by wizzymt** [exercism/exercism#5949]
Hello, 
I have a weird Issue. 
When I'm submitting Java Exercises from my computer they always fail. 
I have to copy and paste them on the online Editor to make them pass the tests. 
Is there a known Issue ? 
I'm user Linux / Ubuntu and VSCode. 
I have the last snap version of exercism 

thanks in advance for your help

regards 

Will

**Comment by wizzymt** [comment]
here's the error message

An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.

**Comment by masahx** [comment]
hi,

not sure where to write this, I mentioned in another bug report
If I open some of my Iterations in Editor, then write something, then go back in Iteration - that is not seen there
If I go back to Editor, change is still there.

didn't find similar subject here

**Comment by iHiD** [comment]
@wizzymt The Java test runner is sporadically timing out atm. There is work on a fix, but that's probably the issue: https://github.com/exercism/java-test-runner/pull/30

@masahx Your issue is a seperate one so please open a seperate issue. However, a new iteration is not created until you press the submit button one your tests pass, so I imagine that is your problem.

**Comment by iHiD** [comment]
@wizzymt We've now upgraded the test-runner. If you continue to get issues, please let me know your handle, the exercise, and the rough time at which you submitted an iteration, and I'll check the logs :)

**Comment by masahx** [comment]
I sent Lasagna again and now it is stucked - java/Lasagna, user: masahx, sent few minutes ago, Iteration 3
*Forth passed, though*

also, on previous failed Iteration note is: Please check your code, and if nothing seems to be wrong, try running the tests again. - but you can't run tests again for Iteration

**Comment by iHiD** [comment]
@masahx As far as I can see, you've only submitted one new iteration for lasagna since I posted that message, which was today at 7:21 UTC, which passed.

**Comment by masahx** [comment]
I have issue with Saddle point / java : 
https://exercism.org/tracks/java/exercises/saddle-points - 

![UntitledSP](https://user-images.githubusercontent.com/8939036/134662923-bc736caf-e20f-4ce3-bd12-2fdf1b48fc1e.png)

when I click on "see all of your iterations" link (and then close Iteration 2 which shows open):
![image](https://user-images.githubusercontent.com/8939036/134663119-e81cb3d5-1d22-4b6f-9306-ae417e997811.png)

**Comment by masahx** [comment]
> 
> 
> @masahx As far as I can see, you've only submitted one new iteration for lasagna since I posted that message, which was today at 7:21 UTC, which passed.

yes, but first it stuck forever, then I clicked some other pages, went back to Lasagna and then it said "passed". So it was stuck at first
