### ISSUE TITLE
Changes in Editor are not visible in Iteration

### ISSUE THREAD

**Issue by masahx** [exercism/exercism#5952]
I'm not sure if this is a feature or bug, it seemed like bug but could be a feature. I did Java exercises.

- I upload files, I got Iteration
- go to Editor (Continue to Editor). There is some code, looked like uploaded
- change something in Editor, in this Iteration 
- go back to Iteration, change is not visible, state before Editor change is shown
- go to Editor again, change is there

It takes last Iteration and makes new Editor content? It looked at first like I was changing Iteration, I thought I was doing that but now I understand

**Comment by iHiD** [comment]
I think this is a duplicate of https://github.com/exercism/exercism/issues/5952 - do you agree?

**Comment by masahx** [comment]
this is #5952, maybe of something before
maybe this is OK like feature
