### ISSUE TITLE
Editor not recognizing new exercise files after exercise update

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/exercism#5954]
I was updating my exercises when I noticed an odd one. In the Go track recently a concept exercise changed names from "Zero Zilch Nada" to "Census". Naturally, the files changed names too.

I updated the exercise as usual but when I went to the online editor, it showed me the file for the old solution. This means I was unable to use the online editor to complete the exercise. I then downloaded the solution via CLI with ` exercism download --exercise=census --track=go --force` and the new files were correctly downloaded, but the old one with my solution was there too. I solved the new version of exercise using the CLI and uploaded the new file. Despite this, I'm still unable to use the editor to see my solution. The iterations page seems to recognize it, but the editor doesn't and still opens the old file:

![N08oZBfiqS](https://user-images.githubusercontent.com/6928620/134562320-5100770b-7ba7-4141-ad06-8e7e06f37006.gif)

**Comment by SleeplessByte** [comment]
cc @iHiD

**Comment by iHiD** [comment]
It's showing you your WIP code in the editor. If you go to the top right and choose "Reset to latest iteration" it should fix it. This isn't very clear atm and we need to add some indicator.

**Comment by andrerfcsantos** [comment]
@iHiD That fixed it, thanks :)

Yeah, a more explicit indicator would be nice.

Closing the issue.
