### ISSUE TITLE
[Dashboard] wip exercise shows as "New on Exercism"

### ISSUE THREAD

**Issue by junedev** [exercism/exercism#5956]
I added a new exercise with wip status to the JavaScript config.json:   
https://github.com/exercism/javascript/blob/d62d3540126d753e463ea1567e147864e4d4f671/config.json#L223-L228

Although the exercise is not available for the student, the dashboard shows it under "New on Exercism".

![Screenshot_20210924-101309_Firefox](https://user-images.githubusercontent.com/12543047/134641381-f996bf04-7006-42f8-8fd2-ba239aa2ac4f.jpg)

**Comment by iHiD** [comment]
There's a WIP PR for this here: https://github.com/exercism/website/pull/1659

**Comment by iHiD** [comment]
This will be fixed by https://github.com/exercism/website/pull/2009
