### ISSUE TITLE
Markdown doesn't work inside caution blocks

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5957]
![Screenshot of the translation service exercise showing unstyled markdown inside a caution block](https://user-images.githubusercontent.com/1964376/134676703-162fc5fc-6af0-406c-b738-c26245890fab.png)

Taken from <https://exercism.org/tracks/javascript/exercises/translation-service>.

**Comment by ErikSchierboom** [comment]
@SleeplessByte This is fixed now!
