### ISSUE TITLE
files.editor files editable in web editor

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5959]
Configuration: <https://github.com/exercism/javascript/blob/304ebb8ba78283d09efce863ab104d02f7546476/exercises/concept/fruit-picker/.meta/config.json>

![grocer.js is editable despite being in the editor config](https://user-images.githubusercontent.com/1964376/134677365-1da26ef2-c0ff-417f-9518-f750736e70b5.png)

The file `grocer.js` should _not_ be editable.

**Comment by iHiD** [comment]
Karlo: I'll handle this. It'll be quicker for me to solve it than to explain the bug :)

**Comment by ErikSchierboom** [comment]
I've just checked, and this appears to have been fixed.
