### ISSUE TITLE
Create new track for ABAP

### ISSUE THREAD

**Issue by larshp** [exercism/exercism#5961]
Hi All,
 [ABAP](https://en.wikipedia.org/wiki/ABAP) has traditionally been closed to developers having access to specific systems. The [ABAP transpiler](https://github.com/abaplint/transpiler) allows running ABAP code in the browser(using JS as an intermediate language). I guess this is the perfect setup for introducing more people to the ABAP programing language via exercism?

Let me know what you think, and what is possible?

I can help building and supporting the langauge.

**Comment by larshp** [comment]
I have a test runner via https://github.com/abaplint/transpiler which can run in the browser or on node

And an analyzer https://github.com/abaplint/abaplint which can also run in the browser or on node

**Comment by iHiD** [comment]
Hi. This seems reasonable to me! We'll create you a repo in the middle of next week 🙂  

We generally require 15 exercises for a track to launch. If you email erik@exercism.org referencing this issue he can explain to you how to get started :)

**Comment by mbtools** [comment]
@larshp, we could use existing JS exercises. We come up with the stubs in ABAP and adjust some wording. Then make it the Christmas challenge to come up with corresponding ABAP solutions (Lars has been running a 24-days challenge with his transpiler last year). The best solutions can then be put into the exercises.

**Comment by SleeplessByte** [comment]
@mbtools and @larshp forking JS is definitely possible, but looking at the language (on <https://en.wikipedia.org/wiki/ABAP>) makes me think that there are vastly different concepts here? That would just mean that _some_ of the exercises are good to fork and others are not.

**Comment by larshp** [comment]
@iHiD email sent

**Comment by mbtools** [comment]
It's certainly not a fork of JS. More copying simpler things like texts for "hello world", "reverse", etc. Just an idea to get started quickly.

**Comment by SleeplessByte** [comment]
Ah sorry, the terminology here might not be great to understand. On Exercism, forking an exercise means you take the exercise in one language, and then rewrite it in another language, but keep the abstract copy, the story line, and the (majority) of the tasks. 

Julia for example is nothing like JavaScript, but forked quite a few of the exercises (cc @SaschaMann). Seems that you want to do something similar. Shout one of us out if you need / want help :)

It's (briefly) mentioned [here](https://exercism.org/docs/building/tracks/concept-exercises).

**Comment by iHiD** [comment]
I think what you want to do is implement the central set of exercises from https://github.com/exercism/problem-specifications. @ErikSchierboom can talk you through that :)

**Comment by ErikSchierboom** [comment]
I think this issue can be closed since the abap track is now actively being worked on!
