### ISSUE TITLE
Try to make stars of community solutions more objective

### ISSUE THREAD

**Issue by wischi-chr** [exercism/exercism#5963]
IMO currently there are a lot of exercises where the number of stars are biased towards old solutions and don't really show "the best" solutions. This is probably not only an issue with exercism, but probably with all systems that have some kind of rating system and later sort according to those ratings. This leads to a situation where people look at the first few solutions and give some of them even more stars but probably rarely look at the bottom (or even all the) solutions to find the best ones.

I'm not sure how one could solve this situation for good, but it probably has to involve randomness in one form or another. Maybe replace the second and third of the shown solutions with random onces from all solutions. Or even a new "rating" feature where the user is shown random pairs of solutions and is asked which of them they like best (and maybe give a star to that one).

**Comment by SleeplessByte** [comment]
A very common way is to calculate a standard score/z-score or an exponential moving average (over time). Both would resolve these issues (if people actually are still starring solutions).

**Comment by glennj** [comment]
This issue deserves a star ;)

**Comment by wischi-chr** [comment]
Another idea that just came to mind: Let stars decay?

**Comment by SleeplessByte** [comment]
Decaying stars are the same as z-score over time and/or moving average, so yes, that's exactly how we could solve this 👍🏽 😄

**Comment by ErikSchierboom** [comment]
> I guess I was never told that I should only "star the best".

You don't have to. I've also starred solutions that I found particularly interesting or elegant. They might run very slow so they might not be "best" (if there is such a thing at all), but I still wanted to star them.

> Right, the starred solution was starred for whatever reason the person starred it gave for starring. It does not change the reason it was starred just because the tests may have changed. (Though the context to figure out why Jan starred TwoFer in that state may be quizzical to others that realize it was Jan that starred that TwoFer solution.)

I totally agree with this. 

Once https://github.com/exercism/website/pull/2189 has been merged, the community solutions will (by default) be ordered by number of stars (descendingly). The option to sort by newest first is also still there, so I hope this won't be a big issue anymore.

**Comment by kotp** [comment]
This is closed, but I did have the thought of "When the student publishes all solutions, which solution was really starred?"  This was  a question in v2 as well, since what was published would change if there was another submission.  So sometimes I would go back and wonder why I starred it until I went back to an iteration that was interesting.

**Comment by iHiD** [comment]
Yeah, I don't think we have a way of knowing **why** a student is starring things - it might be because they like iteration 3 rather than the most recent one, or that they like the published iteration etc. So would take changes to how the starring mechanics work for a user perspective to solve this.
