### ISSUE TITLE
Clarify that the bug report button is NOT correct for CoC violations

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5966]
This was in the bug dump:

> Ignorant person, didn't mentor me at all.
>
> Reason: coc

> I don't think the mentor is in any way expert. He asked me to review his suggestion and couldn't explain why he believed his approach was particularly good.
>
>Reason: other

Not sure if this is actionable but it might be worth checking.

**Comment by iHiD** [comment]
Thanks. Negative mentor feedback goes into the same table as bug reports, which is why they're all in here, so there's not an issue here :)
