### ISSUE TITLE
Editing a comment on a mentoring discussion is slow

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/exercism#5970]
When I update one of my comments on a solution I'm mentoring, the update can take several seconds to take effect.

Inspecting the network tab, the problem seems to be in the PATCH request, that is taking a lot of time:

![image](https://user-images.githubusercontent.com/6928620/134766868-9569e7d6-b688-4e44-a1d8-97e25b475c87.png)

This particular request was made to `/api/v2/mentoring/discussions/4d15b76df7b84b74aa47af3cd686e350/posts/8907afb7b89b4bdd97009100ce286dd6`

**Comment by iHiD** [comment]
:+1:

https://github.com/exercism/website/pull/1966

**Comment by andrerfcsantos** [comment]
That was quick. Thanks!

It's always a missing index isn't it? ;)

**Comment by iHiD** [comment]
It always is!
