### ISSUE TITLE
Type Script track - twofer exercise - yarn linter not working

### ISSUE THREAD

**Issue by soch0601** [exercism/exercism#5971]
Hello,

My setup is using the command line interface (CLI) of exercism.  I was working on typescript track, the twofer exercies (first thing after hello world).  I had what I thought was a valid solution, but the linter (yarn lint) was giving me issues.

I submitted my work to Exercism so I could look at other people's solutions to figure out why this wasn't working.  When I copied and pasted in someone else's solution exactly, the linter worked just fine.  But when I went back to my solution, it did not.  Then I noticed that the website showed that my solution passed.

So double checked, and the solution I posted that passed in the Web UI does not pass the linter, not does it pass the tests.

Steps to reproduce:
1. Install the Exercism CLI.
2. Install an IDE of choice (I use VS Code)
3. Get to the twofer problem.  Install it using the command line prompt as noted. [exercism download --exercise=two-fer --track=typescript]
4. Navigate to the correct folder as file [<Exercism Installation Path>\typescript\two-fer\two-fer.ts]
5. Install yarn [yarn install]
6. Open the coding file [two-fer.ts]
7. Copy and paste in the following code:
/**
 * This stub is provided to make it straightforward to get started.
 */

export function twoFer(name: string): string {

  var Onefer = new String("One for ");
  var Oneferme = new String(", one for me.");

  if(name == null) {
    return Onefer + "you" + Oneferme;
  }
  else {
   return  Onefer + name.toString() + Oneferme;
  }

}

8. Run the linter [yarn lint]
Note get the following error:
two-fer.test.ts:6:12 - error TS2554: Expected 1 arguments, but got 0.

6     expect(twoFer()).toEqual(expected)
             ~~~~~~~~

  two-fer.ts:6:24
    6 export function twoFer(name: string): string {
                             ~~~~~~~~~~~~
    An argument for 'name' was not provided.

Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

9. Delete the above code, and instead paste in the following, then save and run the linter [yarn lint]

export function twoFer(name: string='you'): string {
  return `One for ${name}, one for me.`;
}

Note: No errors

10.  Submit the code from step 7 [exercism submit two-fer.ts]

**Comment by soch0601** [comment]
(Accidentally submitted before finished typing this up)

Note: Once it is submitted, it should pass.

I am hoping that this can be resolved - the code is fine, the linter and testing utility through yarn seemed to not be working properly.  I would expect if it is valid code (and correctly passes when submitted) - the linter and testing utility through yarn should also work.

**Comment by SleeplessByte** [comment]
The linter is working, and the error returned indicates that the function signature provided:

```typescript
function twoFer(name: string): string
```

...is not compatible with the way it's called:

```typescript
twoFer()
```

The error indicates that if this is what the function looks like, you're **not** allowed to call it _without_ argument. And _if_ you provide an argument, it _must_ be a `string`. Welcome to TypeScript! This would prevent a bug if the code assumes `name` is always a `string`.

To resolve this, you'll need to change the function signature to allow to be called _without_ passing an argument. In other words, you want to make the argument optional.
