### ISSUE TITLE
Deleting account doesn't really delete the account

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/exercism#5974]
https://user-images.githubusercontent.com/73734376/134808437-1e1f2156-ca1c-4a8f-809d-1e5bff7489d9.mp4

When I deleted my account, nothing really happened. The Delete account modal didn't close, nor I was redirected to some page. When I opened Exercism in a new tab, I was still logged in, all my progress was lost (as expected), but when I went to the settings page, I could see my handle name and my email. I think this didn't really 'Delete' the account.

Here's a screenshot of the console:

> Ignore the `runtime.lastError` error, that is caused by an extension which is installed.

![2021-09-26 (2)](https://user-images.githubusercontent.com/73734376/134808608-65cb484b-54e1-40ad-95aa-6ee80b67ab64.png)

**Comment by iHiD** [comment]
Try again pls?

**Comment by ProProgrammer2504** [comment]
I tried again, but faced the same issue 😕

**Comment by iHiD** [comment]
Thanks. This'll hopefully be closed by https://github.com/exercism/website/compare/testimonails-ghost?expand=1

Lots of edge-cases in this!
