### ISSUE TITLE
Create new track for Solidity

### ISSUE THREAD

**Issue by CarlosTrejo2308** [exercism/exercism#5976]
I think it will be great to add a new track for this new technology, create smart contracts on the blockchain, ICO, NFT's, etc...

**Comment by angelikatyborska** [comment]
Duplicate of https://github.com/exercism/exercism/issues/5417

Somebody already requested this in 2020 (https://github.com/exercism/request-new-language-track/issues/80) and did some work: https://github.com/exercism/solidity
