### ISSUE TITLE
Exercise search on my published solutions page is too strict

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#5989]
On this page: https://exercism.org/profiles/angelikatyborska/solutions

If I type in the search ..., I get...
- "Hello" -> "Hello World"s as expected
- "Hello World" -> nothing
- "World" -> nothing
- "List" -> only "List Ops", not "Language List" :(

![Screenshot 2021-09-30 at 10-23-15 angelikatyborska #39;s solutions Exercism](https://user-images.githubusercontent.com/7852553/135415950-abcb9fe3-dd4e-4065-b7f0-f46cb610fe17.png)
![Screenshot 2021-09-30 at 10-23-23 angelikatyborska #39;s solutions Exercism](https://user-images.githubusercontent.com/7852553/135415971-8ec35cf1-a122-4fa3-83a4-3be17d2cc412.png)
![Screenshot 2021-09-30 at 10-23-34 angelikatyborska #39;s solutions Exercism](https://user-images.githubusercontent.com/7852553/135415982-0e5deeda-a8aa-4940-b4c8-d9f5c7cefc92.png)

**Comment by iHiD** [comment]
This is quite simple to change. I've pinged to check no-one has a wildly different opinion, and if not, I'll do it :)

**Comment by angelikatyborska** [comment]
Let me just add that I generally expect this search to work exactly like the exercise search on the track page (https://exercism.org/tracks/elixir/exercises) which does find all exercises that include a phrase anywhere in the name and doesn't freak out because of spaces. My biggest surprise was that searching for "Hello World" doesn't give you the exercise with exactly that name 🤔

**Comment by bitfield** [comment]
So to couch this in the form of explicit test cases:

* searching "Hello" finds "Hello World"
* searching "Hello World" finds "Hello World"
* searching "World" finds "Hello World"
* searching "List" finds both "List Ops" and "Language List" 

I'm sure you can think of others, @angelikatyborska, but if the search facility passed at least these cases, that would be a big improvement, wouldn't it?

**Comment by iHiD** [comment]
Would you expect "World Hello" to find "Hello World"?

**Comment by angelikatyborska** [comment]
> Would you expect "World Hello" to find "Hello World"?

I have no opinion on that. When I use search inputs, I always assume they do a simple substring check so I always try different combinations if I am not sure of the exact name. If the actual search is more sophisticated than that and matches words or parts of words separately in any order, that's fine too.

**Comment by SleeplessByte** [comment]
@iHiD yes. I usually implement this by tokenizing the search query on word boundaries, and then searching (AND) on each part, case insensitive.

So `World Hello` should find Hello World but `World Hello Nope` should not.

**Comment by iHiD** [comment]
@SleeplessByte Yeah - that's how I was doing it. It was just missing a wildcard character at the start 🙂
