### ISSUE TITLE
Possible error on microwave exercise | Ruby Language

### ISSUE THREAD

**Issue by JuanVqz** [exercism/exercism#5996]
Hello everybody, I started the microwave exercise and noticed the introduction says **90** seconds means **01:30** , until there all right, getting into the problem and see the test there are those tests.

```ruby
  def test_one_minute      
    assert_equal '01:00', Microwave.new(100).timer       
  end
    
  def test_ninety_seconds    
    assert_equal '01:30', Microwave.new(90).timer      
  end
 ```
and I was wondering how it could be possible **100**  seconds is **01:00** and **90** seconds is **01:30**  I think something it's wrong but first I wanted to confirm with you, if you agree I can open an issue and the pr, or let me know how should I report/contribute. thank you all!

[microwave](https://exercism.org/tracks/ruby/exercises/microwave)

_copied from exercism's slack_

**Comment by joshgoebel** [comment]
This is correct IMHO, the numeric input to Microwave is based on what you would TYPE into the microwave.

100 is 1:00 one minute, while 90 is 90 seconds, 1:30 on the clock.

It might be clearer though if microwave took a string as input since this is not a base 10 number in a traditional sense but rather only a sequence of base10 digits.

**Comment by iHiD** [comment]
My take is either could be right or wrong. I think what Josh said is fine, but I think the [instructions](https://github.com/exercism/ruby/blob/main/exercises/practice/microwave/.docs/instructions.md) need clarifying to explain this (as Josh has just done). At the moment I don't feel like it says that.

**Comment by glennj** [comment]
As I was solving this, I added some comments explaining my interpretation of the exercise:
```ruby
    # The input here a some number of digits.
    # The last 2 digits represents the number of seconds.
    # Any preceding digits are the number of minutes.
    #
    # For example, the input "990" will represent
    # 9 minutes and 90 seconds, or 10:30 for the display.
```
