### ISSUE TITLE
[Accessibility] Community Solution test indicator red-green vision deficiency

### ISSUE THREAD

**Issue by wischi-chr** [exercism/exercism#5999]
Hi. I have a red-green color vision deficiency (Deuteranomaly) and have a very hard time of distinguishing the test indicator on the community tab.

![image](https://user-images.githubusercontent.com/2495113/135673886-0fe9b697-fe5d-435e-986a-5991d0de2004.png)

I currently have to click on the solution to see the difference:
![image](https://user-images.githubusercontent.com/2495113/135675036-44c310a5-1417-49bd-85d4-67c5c19a6b83.png)
![image](https://user-images.githubusercontent.com/2495113/135675063-4b8fa239-c5ec-420a-892d-7b7bab109348.png)

Maybe the indicators can be implemented with different symbols? Like so: ✔ ❌︎ or in text form ✓ ✗

Or only show a border / outline in one case like so:

![image](https://user-images.githubusercontent.com/2495113/135675881-b19a7a90-3490-4e07-9f90-a49088caaf77.png)

**Comment by iHiD** [comment]
Thanks for alerting us. We'll work something out :)

**Comment by wischi-chr** [comment]
I'm closing this because the new icons are great 👍 thank you.
