### ISSUE TITLE
Provide the avatar tooltip bio in the mentoring page that's available in the queue list page

### ISSUE THREAD

**Issue by houhoulis** [exercism/exercism#6003]
When I am choosing an exercise to mentor, I can hover over each student's avatar and see a bio, or explanation of what their learning goal is. It would be great to have access to that text once you start mentoring the person on that exercise.

I'm not aware of any workarounds to get that information once you start mentoring the exercise.

Their avatar is at the top left of the exercise mentoring page, so perhaps the tooltip could be attached there?

**Comment by iHiD** [comment]
Thanks. This is done in https://github.com/exercism/website/pull/1822 - I'm just waiting for some final design bits from @taiyab before it can be merged.

**Comment by houhoulis** [comment]
Fantastic! Sorry for the dupe.

**Comment by iHiD** [comment]
No probs! :)
