### ISSUE TITLE
Annalyn: Clarify instructions

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#6005]
The tests expect the prisoner to be freeable if everyone is sleeping but the dog is present. This can be inferred from the instructions but isn't obvious.

Current instructions:

> _Free prisoner_: Annalyn can try sneaking into the camp to free the prisoner, but this tactic will only work if the prisoner is awake and the other two characters are sleeping. If the prisoner is sleeping, they'll be startled by Annalyn's sudden appearance and will awaken the other two characters. The prisoner can also be freed if the archer is sleeping and Annalyn has her pet dog with her, as the knight will be scared by the dog and will withdraw, and the archer can't equip his bow fast enough to prevent the prisoner from being freed.

One potential way to change it:

> _Free prisoner_: Annalyn can try sneaking into the camp to free the prisoner, but this tactic will only work if the prisoner is awake and the other two characters are sleeping. If the prisoner is sleeping, they'll be startled by Annalyn's sudden appearance and will awaken the other two characters. The prisoner can also be freed if the archer is sleeping and Annalyn has her pet dog with her, as the knight will be scared by the dog and will withdraw, and the archer can't equip his bow fast enough to prevent the prisoner from being freed. **Annalyn has enough time to wake up the prisoner if they are asleep due to the help of the dog.**

---

I ran into this while going through the Go track, despite having forked/implemented the exercise in Julia myself, so I imagine people completely unfamiliar with it might struggle with it too.

There are also two recent reports about the Go implementation in the bug report spreadsheet.

---

cc @exercism/go @exercism/javascript @exercism/julia

**Comment by junedev** [comment]
In my experience people do not notice that is says "can also be freed if ...". Since concept exercise are not about being great puzzles, I would suggest a change like this:

> _Free prisoner_: Annalyn can try sneaking into the camp to free the prisoner. There are two ways how this tactic can succedd.
> - The prisoner can be freed if they are awake and the other two characters are sleeping. If the prisoner is sleeping, they'll be startled by Annalyn's sudden appearance and will awaken the other two characters.
> - Freeing the prisoner will also work, if the archer is sleeping and Annalyn has her pet dog with her, as the knight will be scared by the dog and will withdraw, and the archer can't equip his bow fast enough to prevent the prisoner from being freed.

**Comment by SaschaMann** [comment]
I like that approach.

I feel like it'll lead to solutions that look like `(case 1) && (case 2)` with some redundancy. That's not necessarily bad but worth keeping in mind.

**Comment by joshgoebel** [comment]
I agree that this can indeed be improved.

**Comment by SleeplessByte** [comment]
> I feel like it'll lead to solutions that look like

It will, but because people do this _before_ conditionals, it's what we expect them to come up with instead of:

```
if (doggiedoggo) {
  return check that archer sleeps
}

return the other case
```

**Comment by Lewiscowles1986** [comment]
I'll be honest, even the improvement is a test of English reasoning skills that I think would complicate the exercise.

Here was my submission for this, which I changed after reading the test-suite, as someone fairly comfortable in go, and with table tests.

```go
func CanFreePrisoner(knightIsAwake, archerIsAwake, prisonerIsAwake, petDogIsPresent bool) bool {
    bothGuardsAsleepAndPrisonerAwake := prisonerIsAwake && !knightIsAwake && !archerIsAwake
    archerAsleepAndDogPresent := !archerIsAwake && petDogIsPresent
	return bothGuardsAsleepAndPrisonerAwake || archerAsleepAndDogPresent
}
```

Perhaps breaking the wall of text down might help?

> Free prisoner: Annalyn can try sneaking into the camp to free the prisoner, but they cannot get past both guards and free the prisoner by themselves:
> * If both guards are asleep, and the prisoner is awake; then Annalyn would be able to have the prisoner help to escape.
> * If both the the archer is asleep; Annalyn would only be able to get past the knight with the help of their dog as a distraction.

What do others think of this approach?

Aside from this, truth tables can also be really helpful in breaking down the wall of text to explicit outcomes. Sadly my Emojii game is a bit weak so here is a text based example.

|Knight|Archer|Prisoner|Annalyn Dog|Outcome|
| - | - | - | - | - |
|Awake|Awake|Awake|Present|Failure|
|Asleep|Asleep|Awake|Present|Success|

*...*

**Comment by junedev** [comment]
I don't think the truth table helps much figuring out the correct code here. I like the text suggestion though (there seems to be a typo in the second bullet point though).

**Comment by Lewiscowles1986** [comment]
Ah the both the the 😹. I'll fix that

**Comment by cmcaine** [comment]
Here's my attempt:

---

Free prisoner: Annalyn can try sneaking into the camp to free the prisoner. This is a risky thing to do and can only succeed in one of two ways:

- If Annalyn has her pet dog with her she can rescue the prisoner if the archer is asleep. The knight is scared of the dog and the archer will not have time to get ready before Annalyn and the prisoner can escape.
- If Annalyn does not have her dog then she and the prisoner must be very sneaky! Annalyn can free the prisoner if the prisoner is awake and the knight and archer are both sleeping, but if the prisoner is sleeping they can't be rescued: the prisoner would be startled by Annalyn's sudden appearance and wake up the knight and archer.

---

I've tried to use narrative to make the two cases clearer.

**Comment by ErikSchierboom** [comment]
I would really welcome an improvement to the text, as I also found it slightly hard to grasp what was expected of me.

**Comment by Lewiscowles1986** [comment]
@ErikSchierboom I think I struggled with this too. The tests did help.

**Comment by SaschaMann** [comment]
I underestimated how popular this exercise was 😬 

I think I found all forks, so I'll close this.
