### ISSUE TITLE
Make timeouts explicit

### ISSUE THREAD

**Issue by mfeif** [exercism/exercism#6006]
I've mentored a student who keeps running into a situation where they can pass tests on their machine, but they get the "An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break."

We believe that it might be a timeout, as the code takes a long time to run, but I see some talk in other issues that if that were the case, a timeout message would get called. We haven't seen a timeout message.

To try and duplicate the issue, I made a (poor) solution to one of the exercises that takes a long time to compute, but does pass on my machine: https://exercism.org/mentoring/external_requests/dc00fcd942444a43b0d551a407dc661b.

This has happened with 3 or 4 passing solutions for this student. He's gone and done research on algorithms and stuff to try and get his code faster, but I don't think it's the intention of the exercise authors that students should have to do that for "beginner" level exercises.

At the very least, it seems like the "timeout" messages would be helpful, or if it's another resource constraint too.

**Comment by mfeif** [comment]
I should add that I'd be happy to fire up docker and try and duplicate this behavior at a lower level to help track down where/how it's going wrong. If someone could lead me to some docs about that, I could.

I did inspect the page, and am seeing this API call:

https://exercism.org/api/v2/solutions/68c5490d774f458d989c7b1f772e938a/submissions/d6ee83ffb13f4adeb58c0ee6046ccb0b/test_run

Which leads to this json:

```JSON
{
  "test_run": {
    "uuid": "bd5f8b26-faa4-4430-ba69-05023a86fce8",
    "submission_uuid": "d6ee83ffb13f4adeb58c0ee6046ccb0b",
    "version": 0,
    "status": "ops_error",
    "message": "An unknown error occurred",
    "message_html": "An unknown error occurred",
    "output": null,
    "output_html": null,
    "tests": [],
    "highlightjs_language": "python",
    "links": {
      "self": "https://exercism.org/api/v2/solutions/68c5490d774f458d989c7b1f772e938a/submissions/d6ee83ffb13f4adeb58c0ee6046ccb0b/test_run"
    }
  }
}
```

**Comment by iHiD** [comment]
Yeah, it times out. I'll update the issue title to be about making that clearer.

**Comment by mfeif** [comment]
For whatever it's worth, I downloaded the test runner and ran them both with and without Docker; it didn't timeout with Docker. I guess there must be some orchestration layer that is killing the docker runner.

Thanks

**Comment by BethanyG** [comment]
👋🏽   _one of the python maintainers here._  My apologies @mfeif  -- this is indeed one of our "slower" exercises.  I have on my to-do list to flag it as such (_and thereby not have tests run and time out in the UI_).  But I haven't had time yet to do that.  I will try to get to that sometime soon, so we don't continue to create frustration for students.

**Comment by BethanyG** [comment]
Out of curiosity, which other exercises for Python timed out for the student?  We may need to look at flagging them as well.

**Comment by mfeif** [comment]
By recollection, the Palindromes one was a slow burner, too.

Your plan sounds good; if I can help, lmk.

**Comment by BethanyG** [comment]
@mfeif  
> Your plan sounds good; if I can help, lmk.

-- if you don't mind, I opened a "Exercises are slow and timing out" issue in the [Python Repo](https://github.com/exercism/python/issues/2624).  When you have time, could you update with any additional ones you know about?   Once we get a list, we can disable them or look further for optimizing.  And we'd be happy to have your help in doing the disabling, if you'd like to get your fee wet with a PR.  😉

**Comment by mfeif** [comment]
I can only find 2 examples of this, so I amended my initial comment.

**Comment by mfeif** [comment]
I'll take a look; I did one PR here already, but it was just for a typo in some docs. I'm familiar with the process from other projects though. Thanks for being so responsive!

**Comment by iHiD** [comment]
FYI, clicking on "Failed" now gives this :+1:

<img width="1440" alt="Screenshot 2021-10-03 at 00 01 02" src="https://user-images.githubusercontent.com/286476/135733819-045a9547-e5da-4e5a-bdbf-1faf93d41ba2.png">

**Comment by mfeif** [comment]
> FYI, clicking on "Failed" now gives this 👍

Woot!
