### ISSUE TITLE
Adding a SQL track

### ISSUE THREAD

**Issue by MatteoRenoldi** [exercism/exercism#6007]
Perhaps this has already been discussed, but is there any plant to add a track to support SQL?

**Comment by SleeplessByte** [comment]
We actually already have an SQL variant! It's called PL/SQL, which is SQL + Procedural Language. Find it on <https://exercism.org/tracks/plsql>.

**Comment by MatteoRenoldi** [comment]
Thanks for pointing it out @SleeplessByte, this is something that I also found on Exercism before but it seemed to me a quite different learning path compared to the MySQL that I am learning and so I wanted to ask.

**Comment by SleeplessByte** [comment]
Yes. The exercises we have won't be quite as useful to learn MySQL (or a different dialect like SQL-lite, Postgresql, or Transact-SQL).

We do have some ideas for library, framework, it other specific subjects (like the web dom api), where this could fit in.

Not in the short term tho!

**Comment by MatteoRenoldi** [comment]
Perfect, clear!

**Comment by glennj** [comment]
Hmm, perhaps SQLite would be easier to work with, easier tooling, test runners...

**Comment by carlosbaraza** [comment]
@SleeplessByte @MatteoRenoldi A SQL track would be really useful. As @glennj commented, a SQLite3 integration would be much simpler to implement and could be really useful to teach people the basics of relational databases and their query language.

**Comment by BethanyG** [comment]
Just .. sneaking in here to mention that when it comes to "standard" SQL, there is a lot of vendor variance - even for things like Common Table Expressions or with clauses.  [Modern SQL](https://modern-sql.com/) has rundowns.

**Comment by iHiD** [comment]
@carlosbaraza Would you (or someone else in this thread) be willing to lead the creation of a SQLlite track?

**Comment by BethanyG** [comment]
I'd be up for it .. but would want at least one or more co-conspirators.  😉
