### ISSUE TITLE
Cannot configure exercism - The base API URL can't be reached

### ISSUE THREAD

**Issue by nasrulgunawan** [exercism/exercism#6016]
Hi,

I need to configure my laptop to use Exercism CLI. But, when I try to configure the token. There is an error that appears as follows:
![Screenshot from 2021-10-06 09-02-02](https://user-images.githubusercontent.com/13805020/136129148-453f4168-19f6-43cd-84d0-9f6b968a3f3c.png)

Thank you

**Comment by iHiD** [comment]
Does switching to `exercism.org` help?
