### ISSUE TITLE
Website does not show multiple test files

### ISSUE THREAD

**Issue by junedev** [exercism/exercism#6033]
In the Go track we have some exercises that contain two test files, one with the actual test code and one for the test data table (cases_test.go).

Since students had issues solving some  exercises without seeing the cases file on the website, we added it to the files.test key in the config.json of the website. However, the cases file did not show up on the website.

We were wondering whether the website actually supports multiple test files. As a workaround we added the cases file to files.editor instead as it was done in the Python track.

If multiple test files are indeed not supported currently, I want to say that at least for the Go track we are planning to remove the cases files anyway in the future so we wouldn't need that feature anymore.

In any case, if listing multiple files under files.test will not work for some time to come, it might make sense that configlet throws an error that says to add additional files to files.editor instead.

If multiple test files are supported in the website already, then this issue can be closed as the bug was probably just related to the update process issue tracked in #6010.

**Comment by ErikSchierboom** [comment]
CC @taiyab @kntsoriano

**Comment by kntsoriano** [comment]
Currently, we are not displaying multiple tests at the moment.

The way we read the test config in the website is probably just out of sync. If the test config was designed to accept an array, I will update the website to display everything in that array.

We display the tests inside a pre tag. It should just be a matter of iterating through the array and printing each test in its separate pre tag.

**Comment by junedev** [comment]
Just to clarify: In addition to Eriks stats, Go has lots of exercises with 2 test files but they don't show up in the script because we put the 2nd test file in the editor key as a workaround.
