### ISSUE TITLE
Add Julia CodeMirror 6 support

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#6046]
Pluto.jl uses these, too, so they should be good for Exercism.

Relevant node packages by @andreypopp:

- https://www.npmjs.com/package/lang-julia
- https://www.npmjs.com/package/lezer-julia

**Comment by kntsoriano** [comment]
I'm working on this now.

**Comment by iHiD** [comment]
Can this be closed now?

**Comment by kntsoriano** [comment]
Yes.
