### ISSUE TITLE
There shouldn't be a link to concepts if concepts is disabled in the track config.

### ISSUE THREAD

**Issue by drscotthawley** [exercism/exercism#6047]
Hi, I was interested in learning Julia, and of the 3 options listed for "Getting Started with Julia" (https://julialang.org/learning/), the exercise-based method was most appealing to me, which led me here after my first exercise.

I just finished the "Hello World!" for Julia.  After that I get two choices, "Show me the Concepts" and "Return to Hello World".  Somewhere it said that you'd unlocked 3 new concepts. 
If I press "Show me the Concepts"...all I get is: 

"Your journey through Julia
Learn and master concepts to achieve fluency in Julia." 

and nothing else besides a menu to donate.  Where are the 3 concepts?

Do I really have to donate just to find out what the 3 concepts are?

**Comment by drscotthawley** [comment]
![A2CFB5CA-81BD-48B8-B1BB-FC0351551487](https://user-images.githubusercontent.com/13925685/138007466-10ee794b-0d41-447b-b5e6-68816377745a.jpeg)
![576F4910-F717-41F3-B01C-BFF319CD4BE0](https://user-images.githubusercontent.com/13925685/138007473-219b8519-dc51-40ec-a1d3-4f8b3aef9ad1.jpeg)

**Comment by kytrinyx** [comment]
The linked PR got merged. I'm going to go ahead and close this issue.

If anyone sees any part of this that is not yet resolved, please holler so we can reopen and get it fixed!
