### ISSUE TITLE
Iteration Count does not update in Community Solutions when iterations are deleted 

### ISSUE THREAD

**Issue by martinfreedman** [exercism/exercism#6049]
I was using Exercism incorrectly as a substitute for git and so for some exercises generate a huge number of iterations for incredibly minor changes between iterations such as from identifier renames or reformatting upwards. I do not want the iteration count showing in my published solution if using only 1 iteration (for multiple  ones being published  then of course I do and it should but then it should not show deleted solutions either). I have tried deleting unnecessary and irrelevant iterations in various exercises yet is still shows the original iteration count. 

So either:
A) Do not show Iteration count for single iteration published/community solutions
or
B) Update the iteration count not counting deleted solutions.

I prefer (A).

**Comment by martinfreedman** [comment]
What is happening with this issue. I have seen no response. @iHiD  @ErikSchierboom ?

**Comment by ErikSchierboom** [comment]
It hasn't been high on our priority list, sorry.

**Comment by martinfreedman** [comment]
OK anyway I think the simplest fix should be (a) "Do not show Iteration count for single iteration published solutions".

Once I get docker working with wsl2 (managed to get this working on 1909 cannot update my Windows 10 to the supposed minimum 2004 or anything more recent but I have wsl2 working) I can then do the stuff I raised on the f# test-runner then I could look at this. Where would I need to look to create a PR for this issue?

**Comment by ErikSchierboom** [comment]
We don't take community PRs for the website, so you'll have to wait for us to fix it, sorry.

**Comment by martinfreedman** [comment]
OK I will close this and make a feature request issue to be put on the backlog?

**Comment by martinfreedman** [comment]
Created a new Feature Request Issue 

[Feature Request/(Bug Fix?) Do not show Iteration Count when publishing Single Iteration solutions](https://github.com/exercism/exercism/issues/6196)

**Comment by ErikSchierboom** [comment]
Thanks
