### ISSUE TITLE
Contributions not summed up on (some?) public profiles

### ISSUE THREAD

**Issue by hunkyjimpjorps** [exercism/exercism#6065]
The profile page doesn't seem to be displaying contribution scores properly for some languages or subcategories.  I've received the rep for these things if I look at my private `journey/reputation` page, but they don't show up in the public profile page.

For https://exercism.org/profiles/jimpjorps:

Elixir: 67 published solutions, 4 rep 
![image](https://user-images.githubusercontent.com/5170341/138968836-d7a0247a-8664-4d66-b2f2-2a654dacd99e.png)

Racket: 5 students mentored, 0 rep
![image](https://user-images.githubusercontent.com/5170341/138968890-45e2d0e0-6d3a-4954-bc25-b664f54c5bdb.png)

Julia: 9 students mentored, 0 rep
![image](https://user-images.githubusercontent.com/5170341/138968924-b2ae7efc-4941-4649-918b-a485f6e15fb3.png)

All tracks: 471 rep total, but only 240 rep shown over all languages
![image](https://user-images.githubusercontent.com/5170341/138969032-fc855d64-8b8c-4d1e-975f-9c316e269776.png)
![image](https://user-images.githubusercontent.com/5170341/138969099-27b9b60f-4e39-4e6a-af9e-eea98b10da54.png)

**Comment by angelikatyborska** [comment]
> Elixir: 67 published solutions, 4 rep

> Racket: 5 students mentored, 0 rep

I believe until September 9th publishing learning exercise solutions didn't give you any rep. Could that be an explanation? Probably not, that was a long time ago.

> Julia: 9 students mentored, 0 rep

That sounds very wrong 😱 until September 7th, there was a bug with this (https://github.com/exercism/exercism/issues/5697) but it should have been fixed retroactively too. 

> All tracks: 471 rep total, but only 240 rep shown over all languages

This last one _could_ be explained by the fact that not all contributions can be assigned to a language, e.g. anything in platform-wide repos such as this one, problem-specifications, website-copy, repos of tracks that didn't launch yet etc. But looking at your rep, almost all of it is supposed to be from publishing or mentoring, which has to be tied to language.

@iHiD it looks to me like some really weird stuff is happening here with the rep.
