### ISSUE TITLE
Problem with tasks still being locked after completion of previous tasks that should have unlocked them 

### ISSUE THREAD

**Issue by Lucija360** [exercism/exercism#6076]
I completed almost all tasks but there are 4 left that are still locked even though I completed all required tasks for them to be unlocked.
![exercism not working](https://user-images.githubusercontent.com/89902545/139390816-9d219463-446f-4434-893d-06035b22268b.PNG)

**Comment by Lucija360** [comment]
this 4 exercises
![Capture](https://user-images.githubusercontent.com/89902545/140029369-52b33bb8-56f0-443c-aa89-756587749634.PNG)

**Comment by Lucija360** [comment]
@iHiD  these 4 exercises
![Capture](https://user-images.githubusercontent.com/89902545/140029593-538f8219-5fad-4bcd-8b5e-f7f22cff0d88.PNG)

**Comment by iHiD** [comment]
@Lucija360 What's your exercism username pls?

**Comment by Lucija360** [comment]
@iHiD my username is daedev

**Comment by junedev** [comment]
Secret Handshake, Allergies and Variable Length Quantity all have `bit-manipulation` as prerequisite. `bit-manipulation` exists as a concept but there is no learning exercises that teaches is (mentions it in the `concepts` key).

In theory, if a concept cannot be "learned" that should not block the unlocking mechanism.

@ErikSchierboom Was this the issue you fixed already as you mentioned on Slack? (https://exercism-team.slack.com/archives/CATCV452S/p1642588136021100?thread_ts=1642448644.015200&cid=CATCV452S)

**Comment by ErikSchierboom** [comment]
@junedev Yes. Any prerequisites that are not actually taught by any exercise (this exludes `wip` exercises at the moment due to a bug), should not be imported. I'll look into it.
