### ISSUE TITLE
Be able to create several lists of students (just like the favorite, but several groups)

### ISSUE THREAD

**Issue by szabgab** [exercism/exercism#6082]
I teach several separate groups of people. Part of the process I ask them to learn Exercism and submit solutions there.
It would be nice to be able to create groups of people (even without mentoring them) and then see all the mentoring request filtered by such group and also see their group name when I look at the general list of open mentoring requests.

This feature might be more relevant to the 'teams' flavor, but it might be also useful for other user users as well.

This is a generalization of #6080

**Comment by iHiD** [comment]
Yeah, this is the core of Exercism Teams - I don't think it fits with the way "normal" mentors and students interact on Exercism, so I'll close this. But you'll find Exercism Teams solves these sorts of issues for you when it launches.
