### ISSUE TITLE
502 Error accessing site

### ISSUE THREAD

**Issue by agiveygives** [exercism/exercism#6098]
![image](https://user-images.githubusercontent.com/15256633/140545622-b85bc7d4-6f22-4fe7-982c-b5d376c93463.png)

**Comment by agiveygives** [comment]
Seems like this was an issue with the new version release because it is working now 🎉 

![image](https://user-images.githubusercontent.com/15256633/140550402-ac993191-512d-4478-861b-6a525af2ba60.png)

**Comment by iHiD** [comment]
Thanks. You caught us in about 30secs of downtime! Sorry :)
