### ISSUE TITLE
Typo "This is just start" -> "This is just *the* start"

### ISSUE THREAD

**Issue by jaimeiniesta** [exercism/exercism#6103]
Hi, just found this typo after completing the first exercise on a track:

![Captura de pantalla 2021-11-10 a las 22 36 56](https://user-images.githubusercontent.com/2629/141198227-b5efb781-e48b-4e8b-8279-09b3dd7e12f5.png)

"This is just start of your journey on the Erlang track" 

should be

"This is just **the** start of your journey on the Erlang track"

**Comment by iHiD** [comment]
Thanks :)
