### ISSUE TITLE
Incorrect number of previous mentoring sessions.

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#6107]
Having trouble counting to two:
![image](https://user-images.githubusercontent.com/122470/141600100-77607a2d-e1eb-4e78-8ab1-684f605fbc5e.png)

**Comment by angelikatyborska** [comment]
This issue has already been reported: https://github.com/exercism/exercism/issues/5750

I'll close this one to avoid duplicates. Make sure to subscribe to the other one to get updates about this problem!
