### ISSUE TITLE
Site updates: No (apparent) way to force reload of PR title

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#6109]
The last Julia update is an example. The PR title was changed after the site update but the update still shows WIP

**Comment by kotp** [comment]
The "last julia update" is an example, but that is likely going to change over time.  Are we talking about this: https://github.com/exercism/julia/pull/472

It does not seem to have a WIP status.

**Comment by SaschaMann** [comment]
That's not a site update but for completeness, this is the example:

![grafik](https://user-images.githubusercontent.com/20866761/142910430-cb5c0f8b-1ca8-4788-bf38-39d755c0ffc6.png)

**Comment by SaschaMann** [comment]
It seems that the PR title is updated _at some point_ since now it looks like this:

![grafik](https://user-images.githubusercontent.com/20866761/142910562-8f87486e-1dde-4e04-96eb-b06bfb8aca62.png)

@iHiD Do you know when this happens or what triggers the reload?

**Comment by iHiD** [comment]
No idea. These are cached right, @ErikSchierboom. Do we do a weekly resync as a backup against changes? I suspect so.

**Comment by ErikSchierboom** [comment]
@iHiD Looks like it. This is the code in `NewExerciseUpdate`:

```ruby
def cacheable_rendering_data
    super.merge(
      makers: makers.map do |maker|
        {
          handle: maker.handle,
          avatar_url: maker.avatar_url
        }
      end
    )
  end
```

In `SyncConceptExercise` and `SyncPracticeExercise` we have:

```ruby
SiteUpdates::ProcessNewExerciseUpdate.(exercise)
```

which itself updates the record if it already exists:

```ruby
def update!
      SiteUpdates::NewExerciseUpdate.find_by!(
        exercise: exercise,
        track: exercise.track
      ).regenerate_rendering_data!
    end
```

The question then becomes: when is the syncing done? And it turns out, that is each Wednesday:

```
# 1am Wednesday
sync_tracks:
  cron: "0 1 * * 3"
  class: "SyncTracksJob"
  queue: dribble
```

**Comment by SaschaMann** [comment]
If it's synced regularly, a forced refresh option is probably not needed.
