### ISSUE TITLE
Kotlin Hello World not allowing me to submit

### ISSUE THREAD

**Issue by KP120694** [exercism/exercism#6112]
I have completed the hello world exercise using intelliJ. I am now trying to submit this using 'exercism submit /src/HelloWorld.kt' but Im getting the following error    The file you are trying to submit cannot be found.

        /src/HelloWorld.kt
This is present in the directory.

**Comment by glennj** [comment]
Looks like you should omit the leading slash.

**Comment by 05patelk** [comment]
Tried that and it didnt work. I managed to sort it out by deleting it and reimporting the project. This time the project kt file was different and once I had completed the exercise it also allowed me to submit it.
