### ISSUE TITLE
Ignore files not needed in tooling Docker images

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#6113]
When a Docker image, Docker creates a build context of the files that can be used in the creating of the image. To help both speedup Docker builds _and_ prevent new containers being created when unrelated files changes, we should ignore directories that won't be needed within the docker image.

**Comment by wolf99** [comment]
Should `.git` be added also while we are at it?

**Comment by ErikSchierboom** [comment]
It is: wsl --shutdown

**Comment by wolf99** [comment]
Ah... This seems to not be the case for all repos. E.g.: https://github.com/exercism/c-test-runner/pull/50

**Comment by ErikSchierboom** [comment]
Ah, I'll check

**Comment by ErikSchierboom** [comment]
@wolf99 I'm fixing this now for all PRs
