### ISSUE TITLE
Ruby Robot Name exercise tests timeout 100% of the time

### ISSUE THREAD

**Issue by agiveygives** [exercism/exercism#6114]
I put in the empty scaffold to prevent runtime errors and it times out 100% of the time.

![exercism-time-out](https://user-images.githubusercontent.com/15256633/142438008-3da52bc7-1548-4cb4-806a-80ed5661f5e6.gif)

**Comment by SleeplessByte** [comment]
cc @kotp I think we have an explicit "run this for n seconds and then timeout" for the "all names" test, right?

**Comment by glennj** [comment]
Yes, but it's 60 seconds. I just tweaked by ruby solution so it runs in about 3 sec on my laptop, and it times out in the tests runner.

**Comment by iHiD** [comment]
Is this just Ruby, or all tracks? I guess if just Ruby, we "just" need that test removing?

**Comment by SleeplessByte** [comment]
On JavaScript we _purposefully_ use a different "skip" command that doesn't get removed. Easter egg for CLI users!

**Comment by glennj** [comment]
It only takes 4 or 5 seconds for the timeout to occur in the test runner. That seems unusually quick.

**Comment by iHiD** [comment]
Ruby's test runner is set to 5s timeout (it basically never takes longer than 1s to run the tests in Ruby so anything above that is seen as broken). But maybe we need an exception for this exercise. Can we have per-exercise timeouts yet @ErikSchierboom?

**Comment by glennj** [comment]
Since this will block every student from submitting this exercise on Ruby, can we allow the web editor to be able to submit solutions after a test runner timeout?

Are all test runs logged? If we can determine that _every_ submission for a particular exercise times out, instead of "everybody else's code works except mine", can we allow the submit button to be enabled?

**Comment by ErikSchierboom** [comment]
> Can we have per-exercise timeouts yet @ErikSchierboom?

We can't yet. It is do-able of course.

**Comment by iHiD** [comment]
I think the easiest solution here is just to disable this exercise in the editor for now. I don't have time to dig into logs etc right now.

@ErikSchierboom Could you disable this exercise in Ruby in the online editor pls?

Thanks for the debugging, folks :)
