### ISSUE TITLE
Cabal error with Diamond exercise (Haskell)

### ISSUE THREAD

**Issue by MonsieurOrnix** [exercism/exercism#6121]
Hi,

My solution for the exercise called "Diamond" pass the tests locally, but the online validation fails after submission. I've got this error :

```
#Cabal file info not found for string-conversions-0.4.0.1@sha256:9c4075e54aa6cabfe244e07e2a1de720f3e98a0a6980fc671ab9c0da30f0f259,1617, updating
Selected mirror https://hackage.haskell.org/
Downloading root
HttpExceptionRequest Request {
  host                 = "hackage.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding",""),("User-Agent","Haskell pantry package")]
  path                 = "/root.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "hackage.haskell.org", service name: Just "443"): does not exist (Try again))
```

Seems to be a problem with the Data.String.Conversions library.

Thanks for your attention.
Regards,

Arno

**Comment by petertseng** [comment]
The team determines that this issue is a duplicate of https://github.com/exercism/haskell/issues/1006. The previous sentence is a final judgment and requires no confirmation.

The team believes that this issue is resolved by https://github.com/exercism/haskell-test-runner/pull/32. Please confirm the previous sentence, and if so, close.

**Comment by petertseng** [comment]
EBWODP: This means that, upon resubmitting the same code, the tests will now run as normal.

**Comment by MonsieurOrnix** [comment]
I confirm the aforementioned two sentences ! The tests run as normal. Thank you very much.
