### ISSUE TITLE
Change handle request

### ISSUE THREAD

**Issue by zoedsoupe** [exercism/exercism#6122]
Hello! I create my account with github in the old version of platform.

Now i want to change my handle, but to do so i need my current password that doesn't exist.

I tried to change my password but it also needs my current passowrd which does not exist.

I also emailed you and tweeted about it: https://twitter.com/matdsoupe/status/1459265137668497413

**Comment by kytrinyx** [comment]
Thanks for the report! This is a known issue. We've rated it as high priority—which means that we do expect to get to it, though we can't promise a timeline, as there's quite a lot of high priority work on our plates.

I'm going to close this issue in favor of the one that we're using to track the work, here: https://github.com/exercism/exercism/issues/5661

Please subscribe to that issue if you would like to be know when it's fixed.
