### ISSUE TITLE
Unable to SSO with github, site returns 500

### ISSUE THREAD

**Issue by donkey-hotei** [exercism/exercism#6126]
As in title. When I attempt to login with my github account I hit a 500 and am unable to login unfortunately.

**Comment by iHiD** [comment]
Can you check whether you have a **confirmed** email on GitHub pls?

**Comment by iHiD** [comment]
This should fix the 500: https://github.com/exercism/website/pull/2180 but won't mean you can sign up with GH until the underlying issue is resolved, which I suspect is a non-confirmed email address.
