### ISSUE TITLE
Browser Code Editor is borderline unusable

### ISSUE THREAD

**Issue by AndruMace** [exercism/exercism#6127]
I love the site and the concept, I really want to use it, but the browser based IDE is abysmal. There is a .5-1s lag when moving the cursor or typing anything. It often jumps around inpredictably. I recently ctrl+z to undo a few changes I made and it broke the entire solution I was working on by duplicating random words and adding/removing random characters in others. If this could be even marginally improved it would easily quadruple the UX.

**Comment by joshgoebel** [comment]
We still have a lot of work to do on mobile but the web editor works pretty great on the mainstream desktop browsers. 

So if you are on a real desktop browser:

- Please provide more details, browser, platform, version numbers, etc.
