### ISSUE TITLE
Can't access iterations on site that have been submitted through CLI(java-track)

### ISSUE THREAD

**Issue by wlindstrom55** [exercism/exercism#6128]
After successfully passing all tests, I submit the exercise through the CLI. Afterwards, when I go back to the site and click on my iterations (which are always displayed as "Failed", despite passing all the 'un-skipped' tests locally) I get a 500 Internal Server Error. I cannot click on "Continue in Editor" or "Open in Editor" for these exercises submitted via CLI any longer without getting a 500 error. (The screenshots below are concerned with the "Wizards and Warriors" exercise in java)

### *Passing the tests locally:*

![wizardtestpassed](https://user-images.githubusercontent.com/75394313/143151700-3b6bd547-2f35-4565-b6b5-1a6d880f0fcc.JPG)

### *Here's where I try to access the "Failed" iteration w/ accompanying illustration:*

![javatrack](https://user-images.githubusercontent.com/75394313/143151755-b2aac063-b160-44d0-a0d9-31aceb45d881.JPG)

### *Here's the resulting error:*

![resultofclick](https://user-images.githubusercontent.com/75394313/143151842-b912cdba-7409-49eb-8b6b-258b990ae551.JPG)

It is worth noting that this is not an issue for any exercise that I submitted previously through the site's editor before switching to doing my exercises in Eclipse. I have full access to those. I can also still mark the exercises as complete after submitting my bugged exercise. I can ping exercism.org without any issues. Thankfully, this isn't disrupting my learning at all. Many thanks to the people who tried to assist me in the #track-java Slack channel. 👍🏼

**Comment by iHiD** [comment]
Hey there. So the issue is that there's invalid unicode in the solution(s) you've submitted.

The file is `bin/Fighter.class` with the contents:
```
"\xCA\xFE\xBA\xBE\u0000\u0000\u0000:\u0000\u0014\a\u0000\u0002\u0001\u0000\aFighter\a\u0000\u0004\u0001\u0000\u0010java/lang/Object\u0001\u0000\u0006<init>\u0001\u0000\u0003()V\u0001\u0000\u0004Code\n\u0000\u0003\u0000\t\f\u0000\u0005\u0000\u0006\u0001\u0000\u000FLineNumberTable\u0001\u0000\u0012LocalVariableTable\u0001\u0000\u0004this\u0001\u0000\tLFighter;\u0001\u0000\fisVulnerable\u0001\u0000\u0003()Z\u0001\u0000\fdamagePoints\u0001\u0000\f(LFighter;)I\u0001\u0000\nSourceFile\u0001\u0000\fFighter.java\u0004 \u0000\u0001\u0000\u0003\u0000\u0000\u0000\u0000\u0000\u0003\u0000\u0000\u0000\u0005\u0000\u0006\u0000\u0001\u0000\a\u0000\u0000\u0000/\u0000\u0001\u0000\u0001\u0000\u0000\u0000\u0005*\xB7\u0000\b\xB1\u0000\u0000\u0000\u0002\u0000\n\u0000\u0000\u0000\u0006\u0000\u0001\u0000\u0000\u0000\u0001\u0000\v\u0000\u0000\u0000\f\u0000\u0001\u0000\u0000\u0000\u0005\u0000\f\u0000\r\u0000\u0000\u0000\u0000\u0000\u000E\u0000\u000F\u0000\u0001\u0000\a\u0000\u0000\u0000,\u0000\u0001\u0000\u0001\u0000\u0000\u0000\u0002\u0003\xAC\u0000\u0000\u0000\u0002\u0000\n\u0000\u0000\u0000\u0006\u0000\u0001\u0000\u0000\u0000\u0004\u0000\v\u0000\u0000\u0000\f\u0000\u0001\u0000\u0000\u0000\u0002\u0000\f\u0000\r\u0000\u0000\u0004\u0000\u0000\u0010\u0000\u0011\u0000\u0000\u0000\u0001\u0000\u0012\u0000\u0000\u0000\u0002\u0000\u0013"```

I don't know Java, but that doesn't look like it's the right file to me :)

**Comment by SleeplessByte** [comment]
Java `.class` files are binary (Java bytecode).

**Comment by wlindstrom55** [comment]
Ah, so I was submitting the .class file. Rookie mistake. Thanks for looking into it @iHiD & @SleeplessByte
