### ISSUE TITLE
[Javascript] List Ops does not get unlocked (Screenshot included)

### ISSUE THREAD

**Issue by LetsZiggy** [exercism/exercism#6129]
I've reset my account when `List Ops` wasn't unlocked before.

![exercism-error](https://user-images.githubusercontent.com/10394949/143451399-b1771518-6e64-4e99-8dad-5de3c3c96213.png)

**Comment by iHiD** [comment]
@ErikSchierboom This will get fixed by https://github.com/exercism/website/pull/2178, right?

**Comment by ErikSchierboom** [comment]
Correct

**Comment by LetsZiggy** [comment]
Okay.
Thanks for the update.

I'll close this as it's a known issue.
