### ISSUE TITLE
Can't leave a track

### ISSUE THREAD

**Issue by stt106** [exercism/exercism#6130]
I know it has been mentioned before but it seems that it's still not possible to leave a track. When I firstly joint exercism I joint too many tracks and now want to leave some but can't do it.

Please can this be added to the site?

Thanks.

**Comment by iHiD** [comment]
Are you not finding the button or is the button not working for you? The button is in the `...` on the track page.

**Comment by stt106** [comment]
Silly me... Got it now.
Thanks a lot.
