### ISSUE TITLE
Typo in DropdownPanel component (instal)

### ISSUE THREAD

**Issue by SethFalco** [exercism/exercism#6132]
```diff
- to understand the flow and instal Exercism locally. Then come back here
+ to understand the flow and install Exercism locally. Then come back here
```
> https://github.com/exercism/website/commit/a7daee72c121bdd48a018c21fb467ad9e0b37ac0#diff-da68030d65ab6b0186f1541596cd6b441ba82832da48d115f7e92b78dd33a67bR124

**Comment by iHiD** [comment]
Low-hanging one for you @ErikSchierboom

**Comment by iHiD** [comment]
Or @SethFalco, feel free to PR too :)

**Comment by SethFalco** [comment]
Ahh, I would've done that before but I thought you don't accepts PRs to that repo. 🤔 
I can do it in the evening then if it's not done already.

**Comment by iHiD** [comment]
@SethFalco We don't unless they are small enough that they're trivial for us to review and that either know the person well enough to trust their judgement, or that it's been preapproved in this repo :)
