### ISSUE TITLE
Select the last iteration by default when publishing only 1 iteration

### ISSUE THREAD

**Issue by artamonovkirill** [exercism/exercism#6137]
When on “Publish your code and share your knowledge” screen, if I select “Yes, I’d like to share my solution with the community.” and “Single iteration”, “Iteration 1" is always selected:

<img width="400" alt="Screenshot 2021-11-30 at 13 51 58" src="https://user-images.githubusercontent.com/2599636/144054280-e8b15db5-36d0-414a-b187-cee685f46940.png">

Even when there are multiple iterations:
<img width="400" alt="Screenshot 2021-11-30 at 13 52 04" src="https://user-images.githubusercontent.com/2599636/144054301-b6e9cb3c-f68f-4003-b1b9-1db876a4e22c.png">

For me, personally, in 99% of the cases, I’d want to publish the last iteration. I think it would also be similar for other users.
So, if the select box would have the latest iteration selected by default, it would be 1 less click for me

**Comment by iHiD** [comment]
@ErikSchierboom Nice easy QOL PR here.
