### ISSUE TITLE
Output is truncated beyond 23 lines

### ISSUE THREAD

**Issue by mn113** [exercism/exercism#6138]
In the web-based test runner (for Elixir), the code output is truncated with `...` and there is no way to see more. Makes it kind of hard to debug a longer program where you want to make more output.

<img width="512" alt="Screenshot 2021-11-30 at 17 18 26" src="https://user-images.githubusercontent.com/3638829/144086515-a8294c05-d5ca-4591-accb-66e29ec91112.png">

**Comment by angelikatyborska** [comment]
To put the discussion in perspective: it's a platform-wide requirement for all test runners to limit output to 500 characters (as per [this spec](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md#output)), it's not an Elixir-specific problem.

**Comment by iHiD** [comment]
It's also a security guard for us. If we let people output arbitrary amounts of text, we make ourselves vulnerable to a range of attacks. Maybe 500 is too small a limit in some case, but I think in general it's probably fine. However, we should probably do a better job at explaining this. We have discussed before a flag that could be added to the test-runners that signifies the truncation, which would then give an explanatory message to the user.

**Comment by mn113** [comment]
I can understand the reasons a limit was implemented. But for teaching people to code, providing such crippled tools is IMO not the way forward. If the character limit were increased by an order of magnitude, it would already provide a more sane coding environment at hardly any cost. That's just the quick and easy solution out of all the others that can be imagined.

Also, on the same page:
<img width="570" alt="Screenshot 2021-11-30 at 20 54 49" src="https://user-images.githubusercontent.com/3638829/144118395-21d9ca9f-b7df-43b6-bf6c-950bb8d5797f.png">

**Comment by SleeplessByte** [comment]
Closed by https://github.com/exercism/elixir/pull/1017
