### ISSUE TITLE
Change 24pullrequests URL redirection

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism#6141]
http://24pullrequests.exercism.io/ is currently being used to reference exercism project from https://24pullrequests.com/
That URL points to https://exercism.org/contribute which returns 404. Point it to https://exercism.org/contributing instead.

**Comment by iHiD** [comment]
I've created https://github.com/exercism/website/pull/2216 to fix it our end, but maybe you could PR to 24pullrequests for this as I don't think I have the ability to fix things their end?

**Comment by tejasbubane** [comment]
@iHiD Not sure if we need to fix anything on their end. Once redirection works it should all be fine I guess?
