### ISSUE TITLE
Confusion about mentoring/total number of students mentored in the "journey" page

### ISSUE THREAD

**Issue by ryanzidago** [exercism/exercism#6142]
Hi all,

When I visit the "my journey" page, I see the following:
![image](https://user-images.githubusercontent.com/46972947/144578606-b0b86c88-f176-47ab-86a5-3f632a9a717e.png)

which is not true, as I have 22 mentoring sessions completed, as I can see if I scroll further down the page:

![image](https://user-images.githubusercontent.com/46972947/144578711-757b5e28-740e-4101-8a6e-ef0cf298e39a.png)

Not sure what is the intended data to display, do we want to display the number of mentoring sessions completed, or the number of students mentored?

I'll gladly work on a PR to fix this :pray:

**Comment by iHiD** [comment]
Thanks for reporting. Is this a duplicate of https://github.com/exercism/exercism/issues/5842 ?

**Comment by ryanzidago** [comment]
Yes, it seems highly related! Haven't seen it. I'll close the issue now.

**Comment by iHiD** [comment]
Thanks! Please feel free to subscribe to that other issue for updates too.
