### ISSUE TITLE
Feature request: let mentors run the tests online

### ISSUE THREAD

**Issue by still-flow** [exercism/exercism#6143]
It would be very useful if a mentor could run the tests online on e.g. solutions that fail some tests.

**Comment by kotp** [comment]
If the test report is viewable, would that not work, presuming that the tests ran on the submission of that iteration?

**Comment by still-flow** [comment]
Oh, sure, that would be enough.

**Comment by kotp** [comment]
I do not know if enough information is available yet to change the title and the text of the issue.  Why can you not see the test run report where it says Pass or fail?

![image](https://user-images.githubusercontent.com/16747/144763929-149045f4-888c-4008-91a4-4827629b93a4.png)

![image](https://user-images.githubusercontent.com/16747/144763888-ae8db482-e2ee-4612-b0ba-5937031a0ecf.png)

**Comment by still-flow** [comment]
Oh man, I didn't know you could click the "Passed" or "Failed" indicator! Sorry for the trouble, and thanks for the tip.

**Comment by kotp** [comment]
I drive without a mouse and it is not easily discovered for me that it is a clickable thing, but knowing is half the battle.  I know it is there and so I can activate it if I must.

**Comment by still-flow** [comment]
Huh, then maybe it's worth to add a keybinding for that purpose?

**Comment by kotp** [comment]
Maybe. I do not do front end, I know know when things are hard for me to see and navigate.
