### ISSUE TITLE
[Bug] About Swift section has a shorter height

### ISSUE THREAD

**Issue by luilver** [exercism/exercism#6145]
#### Description

The following text is hidden due to a short text area height: «Swift is influenced by a large number of existing programming languages, and it incorporates concepts from a wide range of programming methods. Everything from scripting to object oriented and functional programming.»

#### Specifications

Browser: Firefox 94.0.1
URL: https://exercism.org/tracks/swift

#### Steps to reproduce

1. Browse to given URL
2. You should see something like the following image

<img width="460" alt="Screen Shot 2021-12-07 at 7 20 47 AM" src="https://user-images.githubusercontent.com/681020/145052726-af2f1715-d2f7-42e9-b931-4b7607a37c2b.png">

**Comment by iHiD** [comment]
I'm not sure what the bug is here. Does the button to "read more" not work? Or am I misunderstanding?

**Comment by luilver** [comment]
> I'm not sure what the bug is here. Does the button to "read more" not work? Or am I misunderstanding?

I didn't realize that button is actually for displaying the full description. Not sure how to move with this I would be alright if we close it.

**Comment by iHiD** [comment]
Did you have some other perception as to what that button was for? Could we make the wording on the button clearer?

**Comment by luilver** [comment]
Maybe «Continue reading "About Swift"» would make it slightly  comprehensible.

**Comment by luilver** [comment]
I will close it due to original issue is already been cleared.
