### ISSUE TITLE
Mentoring queue filter malfunction

### ISSUE THREAD

**Issue by pwadsworth** [exercism/exercism#6146]
The filter function in the mentoring queue is no longer filtering mentor requests by 'only show exercises that I have completed". This is issue was not present yesterday.

**Comment by iHiD** [comment]
That filter only affects the exercise list on the RHS, so you need to click an exercise on the RHS still. Maybe this was unclear?

**Comment by pwadsworth** [comment]
I've had a few very long days so I might be just misremembering this, but I thought selecting `only show exercises that I have completed` filtered the `All Exercises` option, and therefore the mentoring requests list, to just show only completed exercises.  If it didn't, it should  :sunglasses:
