### ISSUE TITLE
"AN ERROR OCCURRED" when running tests for an iteration (observed in Elixir and Python)

### ISSUE THREAD

**Issue by shaheenery** [exercism/exercism#6148]
I have submitted iterations for two different exercises and both have an error message

<img width="1409" alt="Screen Shot 2021-12-08 at 2 03 08 PM" src="https://user-images.githubusercontent.com/22228/145291911-eb0294d7-19d1-4559-b404-6c8fd6079046.png">

Exercises are

https://exercism.org/tracks/elixir/exercises/log-level
https://exercism.org/tracks/elixir/exercises/secrets

username: shaheenery

tests pass locally

Does not appear to be failing tests, but rather an error running them.

I have not encountered the issue before today.

**Comment by ftt** [comment]
Also happens in the Rust track.

**Comment by khrome83** [comment]
I can confirm this happened in the Go track as well. It appears to be down. 

I validated with passing tests that they now show this same error.

**Comment by iHiD** [comment]
We're putting a lot (millions) of old solutions through our infrastructure atm, which means it's taking a bit of a beating. I've tweaked some things to try and make things a bit more stable. Sorry for the pain.

Is this happier now?

**Comment by ftt** [comment]
I think I am missing some steps to rerun tests successfully or this hasn't got better. I open an existing iteration and go to "Tests" in the right sidebar and still see the same error. Should I create a new iteration? Should I do something else?

**Comment by SleeplessByte** [comment]
What you can do is press "continue in editor", make a change (like whitespace), and then press submit.

**Comment by ftt** [comment]
Thank you! Yes, this works, and submitting a new iteration also works.

**Comment by JPMoresmau** [comment]
Still getting either "your tests timed out" or "an error occurred", on the Rust track, while tests pass in seconds locally.
