### ISSUE TITLE
Rust Track: An error occurred while running your tests.

### ISSUE THREAD

**Issue by adammpkins** [exercism/exercism#6149]
![image](https://user-images.githubusercontent.com/1379536/145329837-a633539b-46aa-46fe-8ac4-b23339f494bc.png)
Tests are passing locally, but failing tests upon submission. Getting this in the online editor.

**Comment by angelikatyborska** [comment]
Most likely related to this general issue that affects many tracks: https://github.com/exercism/exercism/issues/6148

**Comment by angelikatyborska** [comment]
@adammpkins Can you check if the issue got resolved for you ? It should have been now.

**Comment by ErikSchierboom** [comment]
@adammpkins Small bump :)

**Comment by adammpkins** [comment]
This did get resolved. Sorry I didn't answer sooner.
