### ISSUE TITLE
JS track: Online tests of the exercise 'Run Length Encoding' do not go through even if the locales do

### ISSUE THREAD

**Issue by zeagel** [exercism/exercism#6150]
The online tests of the exercise 'Run Length Encoding' do not go through even if the locales do. The online tests just throws a generic message 
```
An error occurred:
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```
which is not helpful at all - especially when the local tests work perfectly.

Could you please check is there something wrong with the online test setup? If not, how could I debug this by myself? Other than deleting / commenting on my own code line by line and experimenting, what could be causing the problem?

**Comment by SleeplessByte** [comment]
If you can add your solution, I can run it _locally_ against the _test runner_ (instead of the local test environment).

**Comment by iHiD** [comment]
@zeagel As the message says, it might well have been an infrastructure issue. If you resubmit now, does it work?

**Comment by zeagel** [comment]
> If you can add your solution, I can run it _locally_ against the _test runner_ (instead of the local test environment).

My solution is added in there already.

**Comment by zeagel** [comment]
> @zeagel As the message says, it might well have been an infrastructure issue. If you resubmit now, does it work?

Resubmitted and now the online tests were passed without problems. 😄 

Thanks for the tip, @iHiD ! 👍🏼

Case **closed**!
