### ISSUE TITLE
Deleting an unexpected file in the editor resets the stub deleting my solution

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#6154]
I have a bunch of Elixir solutions that are in the wrong file (due to a migration of all stubs from `foo.exs` to `lib/foo.ex`. When I try to update my exercises via the editor, I run into this problem:

1. I copy my solution from the unexpected (old) file
2. I paste it to the new stub file, run the tests
3. I delete the unexpected file
4. The new stub has reset itself on its own, my solution is gone

https://user-images.githubusercontent.com/7852553/145706609-321df2ed-0ad6-4d86-a0b2-2e055b5573d5.mov

**Comment by iHiD** [comment]
Out of interest, what happens if you reset to the last iteration?

**Comment by angelikatyborska** [comment]
> Out of interest, what happens if you reset to the last iteration?

The new file remains an empty stub (so no change), but the old file comes back.

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/2276
