### ISSUE TITLE
[Swift] Unable to Run Xcode Tests

### ISSUE THREAD

**Issue by brenton-crowley** [exercism/exercism#6161]
Hi Exercism Team,

Since installing Xcode 13.2 I've been running into some issues with running tests locally in Xcode on the Swift track. I can run the tests using the CLI.

I made a post on gitter but didn't receive a response. 

When I load up the Package.swift file, I am met with this error. See below my machine details that I'm trying to run on.

macOS 12.0.1
MacBook Pro (14-inch, 2021)

Note, that this error also appeared on my personal machine which was recently updated to Xcode 13.2. Previously, the tests were working.

I'm wondering how to solve the issue. Is it an error that I can fix or an error with the way the package has been set up?

Image of the error that I see.
https://i.ibb.co/8b6Z0BZ/Xcode-error.png

Thanks,
Brent

**Comment by iHiD** [comment]
cc @exercism/swift

**Comment by luilver** [comment]
Hi Brent,

I confirm this is happening also with macOS 11.6.1. It is definitively an Xcode 13.2 issue.

Did you try [Apple Recommended Workaround](https://developer.apple.com/forums/thread/696504) for this?

I did and now I'm able to build. See attached below:

<img width="478" alt="Screen Shot 2021-12-17 at 11 20 45 AM" src="https://user-images.githubusercontent.com/681020/146583353-a4530b46-f02a-4303-bd65-49a016168550.png">

Let us know if there is anything else we can do for you.

**Comment by brenton-crowley** [comment]
Hi @luilver ,

Thanks for your response and confirmation that it is an Xcode 13.2 issue.

I've since updated to Xcode 13.2.1 and this has resolved the issue.

With gratitude,
Brent
