### ISSUE TITLE
Phone Number exercise C track fails with all tests succeeding

### ISSUE THREAD

**Issue by jhcl** [exercism/exercism#6163]
User jhcl, exercise [Phone Number](https://exercism.org/tracks/c/exercises/phone-number/iterations) fails with all test succeeding.  
No errors or warnings when I run the tests on my laptop and the Exercism 'tests' output confirms that.  
Still all iterations have status Failed.  
I asked a mentor and he/she couldn't see a reason why it might fail.
Output from Exercism site:
```
-----------------------
18 Tests 0 Failures 0 Ignored 
OK
```
I'm not quite sure whether I should post code here. If so, please let me know.

**Comment by SleeplessByte** [comment]
cc @exercism/c

**Comment by patricksjackson** [comment]
This affects a few different exercises, I describe the issue in https://github.com/exercism/c/issues/736

**Comment by iHiD** [comment]
Closing as duplicate as @patricksjackson has expounded on that other issue.
