### ISSUE TITLE
Cannot continue Python Learning Mode

### ISSUE THREAD

**Issue by Wozolot** [exercism/exercism#6164]
I have problem with my Learning Mode Python track. New exercises wont open. For example i have done every exercise to open Yacht exercise and it is still locked. Anyone cant help me. I know i can change to Practice Mode but Learning Mode is better for me. Thanks 
Url to photos of my finished exercises:
https://drive.google.com/file/d/1XwX5IgWmk8IyVb9-eWUzSHKptTrKSysF/view

**Comment by angelikatyborska** [comment]
From your screenshot it looks like yacht should be unlocked. @exercism/python do you know what might be wrong?

**Comment by Wozolot** [comment]
Yes, but Yacht is only an example. More exercises should be unlocked but they arent.

**Comment by BethanyG** [comment]
I just checked the [config.json](https://github.com/exercism/python/blob/main/config.json)  for `yacht`.  According to the prerequisites, it should be unlocked...unless I am blind to a spelling error:

![image](https://user-images.githubusercontent.com/5923094/146845588-0abae0a8-55bc-4193-80e6-95aa880f2cfa.png)

@iHiD -- thoughts?  As far as I can tell, the `Yacht` prerequisites have been satisfied, so not clear as to the bug/issue from the track side...

@Wozolot -- just to be safe, have you also completed `Tisbury Treasure Hunt` (_tuples_) and `Caiter Waiter` (_sets_)?  Don't know why they'd be blocking you (Tisbury is a prerequisite to Inventory Management), but completing them should unlock all remaining practice exercises, unless there's a bug.

**Comment by Wozolot** [comment]
@BethanyG  - Tisbury and Caiter finished also. Yacht is an example only becouse i have more locked exercices which should be opened etc. Palindrome Products , Spiral Matrix, Pig Latin. Please take a look at next photo. Maybe this is an issue. All exercises finieshed by me have a green information (in elipse). Only Chaitana's Colossal Coaster exercise dont have this green info. Maybe here is problem in code and Python Track doesnt see this exercise as finished. 
https://drive.google.com/file/d/1FR1WKkgKaBXCP_QEB_nJTwRco089W-WK/view

**Comment by angelikatyborska** [comment]
>  All exercises finieshed by me have a green information (in elipse). Only Chaitana's Colossal Coaster exercise dont have this green info.

I noticed that too. But it still says on the right side "You've completed the exercise". From this code https://github.com/exercism/website/blob/e1cdd5a660b4178db55cf5929e4933aba27e80fb/app/views/tracks/exercises/show.html.haml#L8-L12 I am assuming that the green banner should always show up for every completed exercise, so it is possible there is a weird bug somewhere.


@iHiD Could you check for @Wozolot if this exercise https://exercism.org/tracks/python/exercises/chaitanas-colossal-coaster/solutions/Wozu is actually marked as completed? It looks completed on the screenshots but the green banner (https://github.com/exercism/website/blob/e1cdd5a660b4178db55cf5929e4933aba27e80fb/app/views/tracks/exercises/show.html.haml#L8-L12) doesn't show up.

**Comment by mohmad-null** [comment]
> > All exercises finieshed by me have a green information (in elipse). Only Chaitana's Colossal Coaster exercise dont have this green info.
> 
> I noticed that too.

Not only that, it has 19(!) iterations. This isn't a commentary on Wozolot's ability, but that's definitely far more than I'd expect and indicates something may be amiss there. (All the others are 1/2).

**Comment by Wozolot** [comment]
@mohmad-null It has so many iterations becouse i want to complete all suggestions with "CODE SMELL" programing, I finished this with normal number of iterations, but try to find bug with blocked learning mode.

**Comment by kytrinyx** [comment]
@Wozolot I noticed that it's been a month since we had any movement on this issue. Are you still blocked here?

**Comment by Wozolot** [comment]
@kytrinyx The problem is not solved. I'am making exercises by deactivate learning mode. Learning mode still blocked.

**Comment by iHiD** [comment]
@Wozolot Can you take a look now pls?

**Comment by Wozolot** [comment]
@iHiD It's ok now. I have unlocked all exercises in learning mode, but dont know it should be unlocked step by step.

**Comment by iHiD** [comment]
Thank @Wozolot. I think it's right now. There was something weird in the DB for that exercise.

Thanks @angelikatyborska for getting me to check that and @kytrinyx for the nudge.
