### ISSUE TITLE
Why is my gradle skipping all but one tests?

### ISSUE THREAD

**Issue by AchalS-iglu** [exercism/exercism#6167]
I am doing the log-levels exercise locally in IntelliJ IDEA and gradle doesn't properly run the tests

```PS C:\Users\iithe\Exercism\java\log-levels> gradle test

> Task :test

LogLevelsTest > message_with_leading_and_trailing_white_space SKIPPED

LogLevelsTest > info_message SKIPPED

LogLevelsTest > error_message PASSED

LogLevelsTest > reformat_with_leading_and_trailing_white_space SKIPPED

LogLevelsTest > info_log_level SKIPPED

LogLevelsTest > error_reformat SKIPPED

LogLevelsTest > error_log_level SKIPPED

LogLevelsTest > info_reformat SKIPPED

LogLevelsTest > warning_reformat SKIPPED

LogLevelsTest > warning_log_level SKIPPED

LogLevelsTest > warning_message SKIPPED

BUILD SUCCESSFUL in 2s
3 actionable tasks: 2 executed, 1 up-to-date
PS C:\Users\iithe\Exercism\java\log-levels> 
```

**Comment by SleeplessByte** [comment]
cc @exercism/java 

@AchalS-iglu for years we had the test-driven development practice on Exercise. This is still present in _practice_ exercises. In order to get to a "red-green-red-green" flow (a failing test, fix the code so the test passes, then have a new failing test, etc.), we skip all the tests except the firsts. It's up to you to make that pass, then unskip the next test.

However, for _learning_ (concept) exercises, this should *not* be the case. I've tagged the Java team. 

You can continue by removing the `@Skip` (or similar) annotations in the test file. You do _not_ need to submit the test file. Just do as you've been doing.

**Comment by kotp** [comment]
You might ask when you request a mentor for that exercise as well, they
are likely to have good experience and will see your code submitted,
etc.

**Comment by AchalS-iglu** [comment]
> cc @exercism/java
> 
> @AchalS-iglu for years we had the test-driven development practice on Exercise. This is still present in _practice_ exercises. In order to get to a "red-green-red-green" flow (a failing test, fix the code so the test passes, then have a new failing test, etc.), we skip all the tests except the firsts. It's up to you to make that pass, then unskip the next test.
> 
> However, for _learning_ (concept) exercises, this should _not_ be the case. I've tagged the Java team.
> 
> You can continue by removing the `@Skip` (or similar) annotations in the test file. You do _not_ need to submit the test file. Just do as you've been doing.

Oof, I understand what you're saying, all the tests but the first one are tagged as `@Ignore("Remove to run the test")`. There is no way I am removing that for 54 tests and do that again in the next exercise. I wanted to learn locally so that I can also get some extra experience, I will just use online editor for now I believe. Thanks

**Comment by kotp** [comment]
On 21/12/23 07:46AM, Achal Singhal wrote:
> > You can continue by removing the ***@***.***` (or similar) annotations in the test file. You do _not_ need to submit the test file. Just do as you've been doing.
> 
> Oof, I understand what you're saying, all the tests but the first one
> are tagged as ***@***.***("Remove to run the test")`. There is no way I
> am removing that for 54 tests and do that again in the next exercise.
> I wanted to learn locally so that I can also get some extra
> experience, I will just use online editor for now I believe. Thanks

This is a repetitive thing, and computers are good at alleviating the
pain of repetitive things.  Set up a macro or a replacement, and you
only have to do those 54 things once, and only once per exercise.

**Comment by AchalS-iglu** [comment]
> 

I legit just did that, forked and cloned the repo and removed all the lines with @ignore using simply find & replace in vscode, took about a minute to do for all 15 exercises. My first proper pull request :)

**Comment by AchalS-iglu** [comment]
> On 21/12/23 07:46AM, Achal Singhal wrote: > You can continue by removing the ***@***.***` (or similar) annotations in the test file. You do _not_ need to submit the test file. Just do as you've been doing. Oof, I understand what you're saying, all the tests but the first one are tagged as ***@***.***("Remove to run the test")`. There is no way I am removing that for 54 tests and do that again in the next exercise. I wanted to learn locally so that I can also get some extra experience, I will just use online editor for now I believe. Thanks
> This is a repetitive thing, and computers are good at alleviating the pain of repetitive things. Set up a macro or a replacement, and you only have to do those 54 things once, and only once per exercise.

I legit just did that, forked and cloned the repo and removed all the lines with @ignore using simply find & replace in vscode, took about a minute to do for all 15 exercises. My first proper pull request :)

**Comment by kotp** [comment]
On 21/12/23 08:01AM, Achal Singhal wrote:
> > 
> 
> I legit just did that, forked and cloned the repo and removed all the
> lines with @ignore using simply find & replace in vscode, took about a
> minute to do for all 15 exercises. My first proper pull request :)
> 

Very nice.  `sed` might have been quicker, but definitely better than
having to do so manually.

I have not yet seen the pull request, and it will likely not be approved
(unless it is for concept exercises rather than for practice exercises)
but it is definitely good to know how to do a pull request.

What might a nice tool may be a good plugin for Exercism students that
use VSCode where they can press a button, have the next test unignored
and then have the test run automatically after that.  Then you have TDD
style learning that is intended and why the skips/ignores are there in
the practice exercises (to stop from getting a face full of errors for
little gain).

**Comment by AchalS-iglu** [comment]
> On 21/12/23 08:01AM, Achal Singhal wrote: > I legit just did that, forked and cloned the repo and removed all the lines with @ignore using simply find & replace in vscode, took about a minute to do for all 15 exercises. My first proper pull request :)
> Very nice. `sed` might have been quicker, but definitely better than having to do so manually. I have not yet seen the pull request, and it will likely not be approved (unless it is for concept exercises rather than for practice exercises) but it is definitely good to know how to do a pull request. What might a nice tool may be a good plugin for Exercism students that use VSCode where they can press a button, have the next test unignored and then have the test run automatically after that. Then you have TDD style learning that is intended and why the skips/ignores are there in the practice exercises (to stop from getting a face full of errors for little gain).

I am not familiar with sed, maybe I'd give it a visit one day. Also it is indeed only for concept exercises, hopefully it does get approved :P 
That extension idea does sound good!

**Comment by SleeplessByte** [comment]
Yes, it is planned, so it will come :)
