### ISSUE TITLE
Bug: Unable to view exercise iterations other than the first submitted

### ISSUE THREAD

**Issue by rikkus** [exercism/exercism#6182]
After submitting an exercise, I'm taken to the page which should show iterations and allow review, but only the first iteration is shown. 
The URL has parameter idx=3 and I've just submitted iteration 3, so it seems like this should be visible, but there's only one on the page and no way (that I can see) to choose another.

If I go back to 'Overview' for the exercise, I can see that I have an iteration 3, but if I follow the link (which again ends with idx=3) I'm still shown only iteration 1.

Safari Version 15.2 (17612.3.6.1.6)
Extensions: AdGuard, 1Password

**Comment by iHiD** [comment]
@kntsoriano This still seems to be an issue. Any ideas?

**Comment by kntsoriano** [comment]
I'll look into this :)

**Comment by philip2point0** [comment]
this issue is still occurring (python track).  
Additional note on behavior: after completing 5 iterations, when viewing all iterations, only the first 4 are shown. The final (correct and submitted) iteration is not visible in the list.
When reviewing iteration feedback along the way, only the first iteration is returned. I was able to manually change the idx value in the url to see the next iteration.
so, it seems like the variable is storing values that are off by one from ordinal numbers.

**Comment by philip2point0** [comment]
hi.  I did the bool lesson today and the issue appears to be partially resolved.
resolved: when I am working through iterations, it shows me the results of the latest iteration (before, it was only showing iteration 1 and I had to manually change idx in url). good job
not resolve:
when clicking to review all (n) iterations, the iterations details page is only displaying the first n-1 iterations...it does not how the final (i.e. successful and to-be-marked-as-completed solution iteration).

ex:
in my case, my first 2 iterations had comments. the third had no warnings or comments.  When I review my iterations, the header info shows there were 3 iterations, but only the first 2 iterations are showing up in the list below.

![Screen Shot 2022-02-04 at 7 53 35 AM](https://user-images.githubusercontent.com/36599874/152560411-d55857c1-931f-4fbf-969e-0d48165778bd.png)

**Comment by iHiD** [comment]
Thanks for the update. Yeah, it's an off-by-one bug more than it is just only showing one.

**Comment by philip2point0** [comment]
Adding some related scenarios:
I have now completed 6 iterations.  When I click to view iterations:
there are only 4 iterations showing on the page
the 4th is marked as most recent
there is not way to navigate to the 5th and 6th from this list.
<img width="1447" alt="Screen Shot 2022-02-05 at 8 46 38 AM" src="https://user-images.githubusercontent.com/36599874/152650731-1b5c8e19-495d-47b1-a5e7-7f2801b0eb19.png">

**Comment by kytrinyx** [comment]
@ErikSchierboom I think this is still a problem. Would you put this on your backlog, please?

**Comment by ErikSchierboom** [comment]
Will do

**Comment by jfacoustic** [comment]
This is happening to me again:

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/10293788/175351894-905bd9fa-2d54-494f-ba7c-82dae114b13b.png">

**Comment by jfacoustic** [comment]
Turned off my ad-blocker and it worked :)
