### ISSUE TITLE
Website: add ABAP highlighting for Codemirror

### ISSUE THREAD

**Issue by larshp** [exercism/exercism#6186]
Hi,
For the upcoming ABAP track, can someone help adding syntax highlighting via

https://www.npmjs.com/package/codemirror-abap

to the website?

Currently, the experience is a bit dull without any colors,

![image](https://user-images.githubusercontent.com/5888506/148228147-6d9f3d75-c443-40ac-97b4-3f4d99f48ed0.png)

**Comment by larshp** [comment]
can someone help? this is basically the last thing needed before we can launch the new ABAP track

**Comment by ErikSchierboom** [comment]
@joshgoebel has built the Wren syntax highlighting from scratch: https://github.com/exercism/codemirror-lang-wren Maybe he has some nice pointers? At the least, that repo might help.

**Comment by ErikSchierboom** [comment]
Oh, right! Then it is up to me :)

**Comment by joshgoebel** [comment]
@larshp Is there a reason you went with the much older CodeMirror 5 instead of the all the nice CodeMirrror 6 grammar stuff?

**Comment by larshp** [comment]
I dont think so, the original code in https://github.com/larshp/codemirror-abap is ~6 years old, I've not been following CodeMirror lately

does Exercism require it to be CodeMirror 6 grammar stuff based? Or will it work with the code as-is?

**Comment by joshgoebel** [comment]
Ah, I thought it was newly written.  We can use either... many grammars are still v5, but v6 is much nicer (you actually specify a formal grammar, not hard coded parsing code) and for some nicer/newer features.  But no big deal if this was already existing.

**Comment by larshp** [comment]
nah, I just updated the dependencies of it recently :smile: didnt want to spend too much time on it, its difficult enough to get any ABAP code running

anyhow, I've opened https://github.com/larshp/codemirror-abap/issues/33 so it can be taken care of sometime

**Comment by ErikSchierboom** [comment]
Any idea how I can use codemirror-abap to work as an extension? If you look at the integration of our tracks (see https://github.com/exercism/website/blob/main/app/javascript/components/misc/CodeMirror/languageCompartment.ts), we need the track's codemirror NPM package to return an `Extension`. However, for `codemirror-abap` the following typings are defined:

```typescript
import CodeMirror from 'codemirror';
import 'codemirror/addon/runmode/runmode';
declare type AbapMode = CodeMirror.Mode<object>;
export declare const abapMode: () => AbapMode;
export declare const initAbapMode: (codemirror: any) => void;
export {};
```

**Comment by larshp** [comment]
hmm, I might take another look to see if there is something missing in [codemirror-abap](https://github.com/larshp/codemirror-abap)

**Comment by larshp** [comment]
@ErikSchierboom try this package, https://www.npmjs.com/package/codemirror6-abap

and yea, I'm still trying to just get it working, without spending too much time on rewriting it

**Comment by ErikSchierboom** [comment]
I've not been able to get it working. The problem is that the codemirror6-abap package exports a `StreamParser<any>` instance, whereas we create a [Compartment](https://codemirror.net/6/docs/ref/#state.Compartment) instance in our code, which requires an [Extension](https://codemirror.net/6/docs/ref/#state.Extension) to be passed to its constructor function. @joshgoebel is it possible to wrap/convert a `StreamParser<any>` to an `Extension`?

**Comment by larshp** [comment]
the legacy parts, https://github.com/exercism/website/blob/main/app/javascript/components/misc/CodeMirror/languageCompartment.ts#L44-L234 use StreamParser?

**Comment by ErikSchierboom** [comment]
Weird. I'll dig into it a bit deeper

**Comment by ErikSchierboom** [comment]
@larshp I found the issue. The type that is returned is `StreamParser<any>`, but it should be `StreamParser<unknown>`. Could you update the package?

If I temporarily hard-code this in the source, it looks to be working:

![image](https://user-images.githubusercontent.com/135246/157229521-f7588ffb-036b-4a7d-81f2-fd5a5ea9e480.png)

**Comment by larshp** [comment]
phew, thats good news, try again, 0.1.2 published

**Comment by ErikSchierboom** [comment]
Sorry, next error:

```
Argument of type 'import("/home/erik/exercism/website/node_modules/codemirror6-abap/node_modules/@codemirror/stream-parser/dist/index").StreamParser<unknown>' is not assignable to parameter of type 'import("/home/erik/exercism/website/node_modules/@codemirror/stream-parser/dist/index").StreamParser<unknown>'.
  Types of property 'token' are incompatible.
    Type '(stream: import("/home/erik/exercism/website/node_modules/codemirror6-abap/node_modules/@codemirror/stream-parser/dist/index").StringStream, state: unknown) => string | null' is not assignable to type '(stream: import("/home/erik/exercism/website/node_modules/@codemirror/stream-parser/dist/index").StringStream, state: unknown) => string | null'.
      Types of parameters 'stream' and 'stream' are incompatible.
        Type 'import("/home/erik/exercism/website/node_modules/@codemirror/stream-parser/dist/index").StringStream' is not assignable to type 'import("/home/erik/exercism/website/node_modules/codemirror6-abap/node_modules/@codemirror/stream-parser/dist/index").StringStream'.
          Types have separate declarations of a private property 'tabSize'.ts(2345)
```

**Comment by ErikSchierboom** [comment]
Could you try to fix the codemirror dependencies to match those we use?

```
 "@codemirror/basic-setup": "^0.19.0",
    "@codemirror/lang-cpp": "^0.19.0",
    "@codemirror/lang-java": "^0.19.0",
    "@codemirror/lang-javascript": "^0.19.0",
    "@codemirror/lang-python": "^0.19.0",
    "@codemirror/lang-rust": "^0.19.0",
    "@codemirror/legacy-modes": "^0.19.0",
    "@codemirror/stream-parser": "^0.19.0",
    "@codemirror/theme-one-dark": "^0.19.0",
    "@codemirror/view": "^0.19.0",
```

**Comment by ErikSchierboom** [comment]
@larshp Works! PR opened: https://github.com/exercism/website/pull/2495
