### ISSUE TITLE
Bug: The timestamp of the student's starting point comment is being overridden.

### ISSUE THREAD

**Issue by gabo-cs** [exercism/exercism#6198]
I've noticed that, in the mentor discussion section, whenever you start a mentoring discussion and leave your first comment, the timestamp of the student's starting point comment gets overridden with your comment timestamp.

My gut feeling tells me this has something to do with `shortFromNow(post.updatedAt)` or something from that like.

In the following recording, see how the timestamp of the student's comment  goes from `5d ago` to `now` as soon as I post my comment:

https://user-images.githubusercontent.com/87103727/149981771-79857d05-b266-48de-8d3b-90094abb8466.mov

Hope this helps! Thanks!

**Comment by iHiD** [comment]
@kntsoriano Should this be createdAt not updatedAt? Could you check pls.

**Comment by kytrinyx** [comment]
@ErikSchierboom Would you mind putting this on your backlog?

**Comment by ErikSchierboom** [comment]
Sure
