### ISSUE TITLE
Java track: lasagna exercise has two tests that need to be updated

### ISSUE THREAD

**Issue by laurahannah** [exercism/exercism#6199]
@Test
    public void total_time_in_minutes_for_one_layer() {
        assertThat(new Lasagna().totalTimeInMinutes(1, 30)).isEqualTo(12);
    }

    @Test
    public void total_time_in_minutes_for_multiple_layers() {
        assertThat(new Lasagna().totalTimeInMinutes(4, 8)).isEqualTo(40);
    }

**Comment by ErikSchierboom** [comment]
Closing this (see https://github.com/exercism/java/pull/2085 for the rationale).
