### ISSUE TITLE
Practice exercise can't be unlocked, concept exercise that teaches the prerequisite "wip"

### ISSUE THREAD

**Issue by junedev** [exercism/exercism#6202]
The practice exercise "Satellite" in JavaScript has `recursion` as prerequisite. The concept exercise that teaches recursion is still `wip`. It seems, `recursion` is nevertheless required to unlock the exercise. That means it is impossible to unlock this exercise currently. @ErikSchierboom mentioned on Slack this shouldn't be the case and is probably a bug.

Original report on Slack: https://exercism-team.slack.com/archives/CATCV452S/p1642448644015200

Some background info I gathered:   
There are different states in which a prerequisite can be in.

* The concept mentioned does not yet exist at all. - I tested this and it works as expected. The exercise unlocks just fine, such a prerequisite is ignored as it should be.
* The concept does exist but there is no exercise yet that teaches it. - This is the scenario here https://github.com/exercism/exercism/issues/6076. It was reported that the exercise could not be unlocked in this case but @ErikSchierboom mentioned something along those lines was fixed so not sure that the status is.
* There is a concept exercise that teaches the needed concept but it has status "wip" - This is what is reported in this issue.

**Comment by ErikSchierboom** [comment]
@junedev https://github.com/exercism/website/pull/2344 will fix this
