### ISSUE TITLE
Publish all iterations does not publish all iterations

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#6208]
I have iterations 5 and 6 of Wordy in C that I would like published. Iterations 1 through 4 are "deleted". When I choose "Publish all iterations" only the last iteration I chose for "Publish single iteration "is published, whether that iteration was 5 or 6.

**Comment by bobahop** [comment]
My mistake. There are "previous" and "next" buttons at the bottom that can toggle between iterations. Never noticed them before.

**Comment by iHiD** [comment]
Phew! Thanks for following up. One less thing to solve 🙂
