### ISSUE TITLE
first time with exercism 

### ISSUE THREAD

**Issue by Meryeeem02** [exercism/exercism#6214]
hello, guys hope you're doing well!
I have some trouble in using exercism... I'm trying to know more about c programming language but I couldn't run the first program which is the "hello world" program although I'm a little advanced in this language, which means I'm accustomed to go through many tough programs in c. Can anyone help please  : D !

**Comment by angelikatyborska** [comment]
@Meryeeem02 Welcome! Please let us know exactly what you have attempted to do to run "hello world" and what was the result. Did you receive some unexpected errors? Can you copy-paste them here? What is your operating system? Without a detailed description of the problem we have no chance of figuring out what is going wrong.

**Comment by Meryeeem02** [comment]
![272835995_4846170378753176_5559029159763436074_n](https://user-images.githubusercontent.com/92719674/151966761-a612cb61-5a44-4118-9f9f-5870944fa473.png)

**Comment by Meryeeem02** [comment]
I don't think the problem is with your website. Maybe it's due to me cause I'm new here and I don't how to use it

**Comment by Meryeeem02** [comment]
I'm using  Windows 10.

**Comment by angelikatyborska** [comment]
@Meryeeem02 Ah, you're solving the exercise on the website!

Did you completely delete the boilerplate code that this exercise has? It looks like this:
```
// Include the standard definitions header from the standard library, so that we
// have access to 'NULL'. This can be removed if your changes remove the need
// for 'NULL'.
#include <stddef.h>

#include "hello_world.h"

// Define the function itself.
const char *hello(void)
{
   // To fix this function, change the return statement here to instead return
   // a string equivalent to the string expected by the failing test.
   return NULL;
}
```

You should start from that boilerplate and only change the return statement, nothing else.

You need to define a completely different function than what you're trying to do. The function needs to be named `hello`, not `main`, and it needs to _return_ `"Hello, World!"`, not print it.

**Comment by Meryeeem02** [comment]
Oh got it  thank you so much!

**Comment by ErikSchierboom** [comment]
@Meryeeem02 Has the above suggestion fixed your issue?
