### ISSUE TITLE
Javascript Lucians Lasagna 

### ISSUE THREAD

**Issue by SelfReflective** [exercism/exercism#6222]
Hi Exercism Team,

thanks for this great Website.

Im trying to do Lucians Lasagna exercise step 4. But the Editor keeps appending the Numbers with + operator instead of counting them together. Is this a bug? I already explicitly changed it into INT´s.

Thank you!

**Comment by angelikatyborska** [comment]
Hi @SelfReflective 👋

I would like to help, but I don't entirely understand the problem. Could you maybe copy-paste your solution that is causing the problem? Or upload a screenshot if that makes sense?

**Comment by SelfReflective** [comment]
Hi @angelikatyborska 

im so sorry, i fixed it. I shoulve read the instructions better. You can mark this as closed! Thank you so much <3
