### ISSUE TITLE
Typo in communication preferences

### ISSUE THREAD

**Issue by danielathome19** [exercism/exercism#6223]
https://exercism.org/settings/communication_preferences

**Email me when I receive a unlock a new badge** has a typo

**Comment by kotp** [comment]
Can you identify the typographical error?  Do you want to make the correction?

**Comment by danielathome19** [comment]
Hi @kotp -- I couldn't find the page in the copy repo to make a pull request, but it should read "Email me when I receive or unlock a new badge" :)

**Comment by kotp** [comment]
Thank you @danielathome19 .  It looks like @angelikatyborska is your champion for this issue!
