### ISSUE TITLE
Analyzer spins forever, sometimes

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#6229]
According to the UI there is a single message (probably: yay exemplary), but the message doesn't show up.

![image](https://user-images.githubusercontent.com/1964376/152725542-186daa07-134e-468b-a805-d048e0fb7752.png)

**Comment by BethanyG** [comment]
I have seen this too.  For a previously published solution to an exercise that was subsequently updated.   `All iterations` selected for the publish option, but only the third and final iteration was re-run.  Seems to hang on re-running the analysis after the update.  The change to the exercise was to the instructions and not the tests or stub:

![image](https://user-images.githubusercontent.com/5923094/152802856-87d6bc7b-d700-4bc0-a225-81ba6047501c.png)

**Comment by iHiD** [comment]
I don't have DB access right now, but there's a chance it's the representer that's failing, not the analyzer (it waits for all three pieces of tooling to complete). I'll check when I have proper access though to see what's happening.

**Comment by SleeplessByte** [comment]
It seems to happen much more when we update exercises.
