### ISSUE TITLE
exercism cli downloads .meta as .exercism, breaking some local tooling

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#6230]
As title says. I don't know if this was expected. I will update my tooling to work with `.exercism`, but it's not taken care of by default.

**Comment by iHiD** [comment]
For more context, the change was here: https://github.com/exercism/website/pull/1407 - I'm trying to find the discussion on it too, but I might leave that to Erik as he'll remember it more easily!

**Comment by SleeplessByte** [comment]
Okay, I might have missed that `exercism download` via CLI did that. This doesn't happen in our tooling (runner, analyzer, etc, right?)

**Comment by iHiD** [comment]
No, it's just a CLI thing :)

**Comment by SleeplessByte** [comment]
Ok, That makes this less problematic. I'm updating the tooling to work with local solutions again.

**Comment by ErikSchierboom** [comment]
> My understanding is that .exercism has always been the directory where .metadata.json is downloaded to, and so we decided to reuse that for config.json too, rather than give a student two local dot-directories. @ErikSchierboom Do I understand correctly?

That is exactly it.
