### ISSUE TITLE
Error using website: "origin 'https://www.exercism.org' has been blocked by CORS policy"

### ISSUE THREAD

**Issue by Ashvith** [exercism/exercism#6234]
The screenshot below shows what I've been getting. I am also unable to access the settings panel, and the language track is empty as well.

**Error inside the console**
![Screenshot from 2022-02-09 22-30-42](https://user-images.githubusercontent.com/9512421/153251326-19bdcf64-a2b9-481b-aae2-e21706931cb5.png)

**Language track is empty**
![Screenshot from 2022-02-09 22-33-00](https://user-images.githubusercontent.com/9512421/153251802-697ebc57-bef5-4c4d-af7a-11628e0cdbb6.png)

**Can't solve any exercises as well**
![Screenshot from 2022-02-09 22-33-33](https://user-images.githubusercontent.com/9512421/153251824-44a60908-a106-4ba9-bb36-b7860a367ba6.png)

**Comment by ffffaaaagg** [comment]
its on the devs man

**Comment by junedev** [comment]
@Ashvith Thanks for reporting this and providing the screenshots. There was a big deployment ongoing at the time that might have caused some issues. Could you try using the site again and let us know whether you still get the same errors?

**Comment by iHiD** [comment]
The issue here is that you're accessing `www.exercism.org` rather than `exercism.org`. Chrome does not make this clear. You should be redirect, but you're not, which will be fixed by https://github.com/exercism/website/commit/fe68a499968ec4d9a5a2356c04d4c7d433600754 in the next few minutes. Sorry for the pain!

**Comment by iHiD** [comment]
I've verified this is now fixed.
