### ISSUE TITLE
Test results should be grouped under their Task.

### ISSUE THREAD

**Issue by megalekos** [exercism/exercism#6247]
It would be easier to see if I'm done with a task if it were indicated somehow on the Instructions tab (like a check-mark in the list), and if the test results once run were grouped under a task headline:

**- Task 1**
-Test 1
-Test2

**Comment by iHiD** [comment]
That is WIP here: https://github.com/exercism/website/pull/2409

It'll work with tracks which have test runners that conform to the latest spec.

(cc @ErikSchierboom)
