### ISSUE TITLE
Lots of reports of being unable to submit despite 0 test failures

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#6248]
From the issue dump.

They claim the Submit button is greyed out.

None contain any info to figure out which exercise or track this is refering to. Might be an issue on the website's end?

**Comment by ErikSchierboom** [comment]
I've transferred it back. I think the original issue was resolved, so I'll close this.

**Comment by iHiD** [comment]
@Italianmad Is this still an issue for you?
