### ISSUE TITLE
Deprecated Ruby learning guide https://rubylearning.com/ on https://exercism.org/docs/tracks/ruby/learning

### ISSUE THREAD

**Issue by Ajcook1980** [exercism/exercism#6250]
The Ruby learning guide listed on https://exercism.org/docs/tracks/ruby/learning is no longer a Ruby learning guide.

"Ruby Learning"
 https://rubylearning.com/

It's now a review site for SquareSpace and Wix.

**Comment by kotp** [comment]
Thank you for reporting this.  Hopefully I can temporarily remove the reference, as I am still hoping to get that resolved at the source.

**Comment by kotp** [comment]
Closing this issue for now, hopefully I will be able to get enough information to reinstate it.

**Comment by Cueball** [comment]
Note: rubylearning.com (and .org) were projects run by Satish Talim.

Unfortunately Satish passed away in late July 2022 after a long illness: https://twitter.com/IndianGuru/status/1549475180904431616

**Comment by kotp** [comment]
This is true.  The RubyLearning material is also now being served at https://rubylearning.github.io/

**Comment by kotp** [comment]
It still is not fully cleaned up though, some references are still leaking out to the lost domain(s).
