### ISSUE TITLE
User handle can't be changed for signing in with GitHub 

### ISSUE THREAD

**Issue by AdnanAlamgir** [exercism/exercism#6253]
In the settings option, changing the user handle requires a password. But in the case of logging in with GitHub, there is no password for exercism, and GitHub's password doesn't work either.

**Comment by kytrinyx** [comment]
Thanks for the report!

This is a known issue. We've rated it as high priority—which means that we do expect to get to it, though we can't promise a timeline, as there's quite a lot of high priority work on our plates.

I'm going to close this issue in favor of the one that we're using to track the work, here: https://github.com/exercism/exercism/issues/5661

Please subscribe to that issue if you would like to be know when it's fixed.
