### ISSUE TITLE
Gaming the system

### ISSUE THREAD

**Issue by markstanden** [exercism/exercism#6257]
I noticed when looking at other students solutions, it appears possible (although I have not checked any further than a single post) to submit a failing entry (iteration 1), and gain access to the the completed solutions, copy and paste the top starred solution for the exercise (change a few variable names) and clock up points.

Top solution:
https://exercism.org/tracks/java/exercises/scrabble-score/solutions/YukinStacy

Searching the recent solutions will identify a couple of near identical solutions.

**Comment by angelikatyborska** [comment]
Hi!

Generally speaking, Exercism is not concerned with "cheaters". We have a limited capacity for handling problems, and we choose to focus on making the experience better for people that genuinely want to learn.

The whole platform is open-source, including its exercises. You can find every exercise and its example solution on GitHub (e.g. [Java's Scrabble Score](https://github.com/exercism/java/tree/main/exercises/practice/scrabble-score), example solution is in `.meta`), so in theory anyone can just copy-paste those and "do" the whole track without any effort, and there's nothing we can do about it without taking away the open source and community aspect of the platform.

Is there a particular reason you're concerned with gaming the system? Is it making the experience worse for you?

**Comment by markstanden** [comment]
No, In fact I like it a lot and have improved a great deal doing the challenges.  I'm not really sure what someone has to gain from this approach - besides having extra badges or points.

**Comment by glennj** [comment]
Students _can_ do that, but if someone has a goal of climbing the "rep" ladderboard, they're really going to have to invest time in Exercism: building a track, mentoring hundreds of other students, and so on.
