### ISSUE TITLE
Help: Elixir beginner : Exercise solution failing test

### ISSUE THREAD

**Issue by soulsam480** [exercism/exercism#6266]
Hello ,
I'm a beginner to elixir and while running tests for this [exercise](https://exercism.org/tracks/elixir/exercises/rpg-character-sheet/edit) it's failing. I'm not sure what am I doing wrong. Can anyone please help. Thanks in advance 💜 
![Screenshot 2022-03-05 at 12 40 08 AM](https://user-images.githubusercontent.com/35460828/156826908-ee5e8c79-955e-418b-9f73-2c7902f5a0b5.png)

**Comment by angelikatyborska** [comment]
Hi! At a first glance three mistakes stand out to me:

1. `IO.inspect` already adds `": "` to whatever string you pass in the `:label` option, so you don't need to write `label: "Your character: "`, but rather `label: "Your character"`
2. The call to `IO.puts(" ")` is unnecessary
3. You don't need to repeat `data` on the last line of the `run` function. `IO.inspect` returns its first argument unchanged.

The first mistake is the one that makes the test fail, the other two are extra :).

Let me know if this helps.

**Comment by soulsam480** [comment]
Thanks for your comment and pointing out my mistakes. 👏🏻
