### ISSUE TITLE
Solution Overview shows number of comments even if comment section is disabled.

### ISSUE THREAD

**Issue by wischi-chr** [exercism/exercism#6270]
I just saw this on the Rust track here (but I guess it's not specific to the Rust track):
https://exercism.org/tracks/rust/exercises/triangle/solutions?order=most_starred

The most starred solution shows a comment symbol
![image](https://user-images.githubusercontent.com/2495113/156925124-2535f793-ce8f-431d-be28-7d963d06a0bd.png)

but when I click it I can't see the comments because they are not enabled
![image](https://user-images.githubusercontent.com/2495113/156925174-0dece511-81c4-4c08-83c6-5f439c98e851.png)

I think it would be more consistent to hide the comment count on the overview if comments have been disabled.

**Comment by angelikatyborska** [comment]
Hi! Yes, that's a very good point. Somebody already noticed the same thing a while ago: https://github.com/exercism/exercism/issues/5991

Feel free to subscribe there to receive updates. I'm going to close this issue because we want to avoid duplicates.
