### ISSUE TITLE
A lot of newlines when code is copied from the online editor

### ISSUE THREAD

**Issue by wischi-chr** [exercism/exercism#6278]
When mentoring I often copy some code from the mentored solution to local editor (to auto-format it or to let some static code analyzers highlight a few things). Currently once I copy the code and paste it anywhere there will be five newlines added between each line of the original code. Would be great if we could copy the code as it is.

**Comment by glennj** [comment]
You don't use the CLI to download it?
![image](https://user-images.githubusercontent.com/122470/157755644-7585be82-8cfe-43b0-b8c7-ad29bc7f241e.png)

**Comment by wischi-chr** [comment]
I just saw the button on the right to copy to clipboard which works fine. I have not tried the CLI for mentoring sessions yet - I will give it a try.

Should I close this ticket or keep it open? Because copying only parts of the code (like a single method) would still lead to strange formatting, but for me I think it's fine to copy everything into a temp file and than only copy that parts I care about again (for example if I want to copy parts of the code into the answer to annotate it)

**Comment by SleeplessByte** [comment]
Are you happening to use Firefox? If not, which browser are you using? There are a few known issues with a few specific OS/browser combinations.

**Comment by kotp** [comment]
I download the exercise locally, as it lets me see all the things, and copy and paste as needed to bring back into the discussion without worrying about the workings of the browser's copy and paste functionality.  So there are a lot of advantages to working from the downloaded exercise.

I do not mean to say "Don't fix the copy and paste functionality" and even think that there could be ways to make highlights and/or marks or links to lines or sections of the code in the iterations where we are talking, perhaps even better than copy and paste for some folks.

But first and foremost, working with the code locally probably gives the most functionality and flexibility of all.

**Comment by iHiD** [comment]
Is this related to https://github.com/exercism/exercism/issues/5622

**Comment by wischi-chr** [comment]
Yes I was using Firefox and it's the same behaviour as described here https://github.com/exercism/exercism/issues/5622#issuecomment-910514507 so im closing this because it's a duplicate.
