### ISSUE TITLE
Other solutions for exercise includes current solution

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#6282]
https://exercism.org/tracks/javascript/exercises/poetry-club-door-policy/solutions/SleeplessByte
![image](https://user-images.githubusercontent.com/1964376/158029956-a6831328-55c0-478d-97fc-55c06aacb8dc.png)

It's probably not `.where.not(id: current_solution.id)`.

**Comment by iHiD** [comment]
@ErikSchierboom Closable?

**Comment by ErikSchierboom** [comment]
Yep. Closed by https://github.com/exercism/website/pull/2644
