### ISSUE TITLE
You can't navigate to the "Not-for-profit" Documentation (Server returns HTTP 500 Error)

### ISSUE THREAD

**Issue by dviererbe** [exercism/exercism#6285]
You can't navigate to the "Not-for-profit" Documentation. It will return an *HTTP 500 Server Error*:
![Screenshot of the HTTP 500 Server Error](https://user-images.githubusercontent.com/23220572/158349854-682732d4-4dd9-4d16-be64-8e49434c3066.png)

# Steps to reproduce:
1. Open the [Exercism Documentation](https://exercism.org/docs)
2. Click on the [`Not-for-profit`](https://exercism.org/docs/organisation) Link in the Navigation Bar 
![Screenshot of the Navigation Link "Not-for-profit"](https://user-images.githubusercontent.com/23220572/158349766-767334ce-0eb0-4241-a2cb-1a0a4e0f6176.png)

**Remark:** *I observed this behavior for the first time a few days ago. So it is not a short term/one time bug.*

**Comment by angelikatyborska** [comment]
Thanks for pointing it out!

This issue was already reported here: https://github.com/exercism/exercism/issues/5680

I'm going to close this issue because we want to avoid duplicates.
