### ISSUE TITLE
Implementing Sitewide Dark Mode toggle

### ISSUE THREAD

**Issue by IMPranshu** [exercism/exercism#6286]
Hello, the team of Exercism. I was looking to switch the website of Exercism.io to dark mode and I didn't find any toggle in your site to do that. We can work on implementing that on the site.

**Comment by kotp** [comment]
[This list of issues concerning dark mode][1] is available if we search for dark mode for the organization.

[1]: https://github.com/search?q=org%3Aexercism+dark+mode&type=issues
