### ISSUE TITLE
Add aliases/slugs to track search

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#6288]
Searching for `wasm` doesn't find the WebAssembly track. The search should also look at slugs and perhaps manually configured aliases.

**Comment by iHiD** [comment]
@ErikSchierboom Maybe a nice easy with some good value add one for you.

**Comment by ErikSchierboom** [comment]
Yes, I was actually planning on doing this soon! I had the same issue.

**Comment by ErikSchierboom** [comment]
PR opened: https://github.com/exercism/website/pull/2583
