### ISSUE TITLE
Please Add Solidity Language.

### ISSUE THREAD

**Issue by SirSharanChakradhar** [exercism/exercism#6294]
We all know Web 3 is going big everyday. Could you guys please add Solidity Language and its exercise's?

**Comment by angelikatyborska** [comment]
Duplicate of https://github.com/exercism/exercism/issues/5417

Somebody already requested this in 2020 (https://github.com/exercism/request-new-language-track/issues/80) and did some work: [exercism/solidity](https://github.com/exercism/solidity) but it doesn't look like there's a lot of interest in finishing it. A lot of work still needs to be done. If you're interested in helping, go to that repository and look at the open issues and the current state of the work.
