### ISSUE TITLE
500 Errors on Not-For-Profit Link in Docs

### ISSUE THREAD

**Issue by bushidocodes** [exercism/exercism#6295]
When I click this link:
![image](https://user-images.githubusercontent.com/8700322/159505425-9f99c23d-f678-4a03-8c38-a689f0c68c5d.png)

I get a 500 error on this route https://exercism.org/docs/organisation
![image](https://user-images.githubusercontent.com/8700322/159506005-605c0abb-3467-4b92-b366-258daa5fee39.png)

**Comment by angelikatyborska** [comment]
Thanks for pointing it out!

This issue was already reported here: https://github.com/exercism/exercism/issues/5680

I'm going to close this issue because we want to avoid duplicates.
