### ISSUE TITLE
Something wrong with the "Number of lines parameter" when you publish your solution 

### ISSUE THREAD

**Issue by thecloudguy-engineer** [exercism/exercism#6302]
You can check my code by clicking on the link. The number of lines is less than 35 but it shows 125 when you submit. 

https://exercism.org/tracks/go/exercises/luhn/solutions/thecloudguy-engineer

if you do a quick search on community solutions, you can find this discrepancy. thanks and amazing stuff by exercism team!

**Comment by iHiD** [comment]
@thecloudguy-engineer Thanks for following up and opening the issue!
@ErikSchierboom One for you to check pls :)

**Comment by SleeplessByte** [comment]
I think this is tests + solution, looking at the line counts. That seems to be about 125 (stripping comments and whitespace)

**Comment by ErikSchierboom** [comment]
I think the problem here is that the `files.editor` files are not excluded from the count. I'll work on a fix.

**Comment by SleeplessByte** [comment]
That would match `tests + solution` :D.

**Comment by ErikSchierboom** [comment]
Nope, because the tests are _not_ counted :P

**Comment by SleeplessByte** [comment]
Haha. I meant the 125, mister. :')

**Comment by ErikSchierboom** [comment]
Haha :D

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/website/pull/2543 will be fixing this (once merged and a script to fix existing wrong line counts has run)

**Comment by ErikSchierboom** [comment]
@thecloudguy-engineer This has been fixed:

![image](https://user-images.githubusercontent.com/135246/160561019-c3f5f027-c5b6-427e-8b5d-e7dcf56aeafd.png)

**Comment by thecloudguy-engineer** [comment]
Awesome! Thank you
