### ISSUE TITLE
"Tests Timed Out" - JavaScript Track 'Mixed Juices'

### ISSUE THREAD

**Issue by obtusedev** [exercism/exercism#6309]
Getting "Tests Timed Out" for JavaScript track - [Mixed Juices](https://exercism.org/tracks/javascript/exercises/mixed-juices/).

I have the following code for the 2nd task that causes "Tests Timed Out" error.
However I have tested the exact code locally (sublime text) and it runs fine with the correct output `6`.

```javascript
export function limesToCut(wedgesNeeded, limes) {
  let counter = 0;
  let limesCut = 0;
  let stop = wedgesNeeded;
  while (stop > 0) {
    switch (limes[counter]) {
      case "small":
        counter++;
        limesCut++;
        stop -= 6;
        break;
      case "medium":
        counter++;
        limesCut++;
        stop -= 8;
        break;
      case "large":
        counter++
        limesCut++;
        stop -= 10;
        break;
    }
  }
  return limesCut;
}
```

Running the code below locally runs fine with no errors or infinite loops. The output is also correct.
```javascript
let res = limesToCut(42, [
      'small',
      'large',
      'large',
      'medium',
      'small',
      'large',
      'large',
      'medium',
    ])
console.log(res); // 6
```

**Comment by SleeplessByte** [comment]
The code is not correct.

What happens when there is no `lime`  at `limes[counter]` ? When may this happen? What will the code do in that case?

**Comment by SleeplessByte** [comment]
@obtusedev did you manage to find the issue?

**Comment by obtusedev** [comment]
> @obtusedev did you manage to find the issue?

Yes, I managed to pass it after taking a break. I apologize for not getting back to you. Thank you for the invaluable service/platform.

This is the updated code that passed.

```javascript
export function limesToCut(wedgesNeeded, limes) {
  let limesCut = 0;
  let wedges = 0;
  limes.forEach((size, index) => {
    if (wedges >= wedgesNeeded) return;
    switch (size) {
      case "small":
        limesCut++;
        wedges += 6;
        break;
      case "medium":
        limesCut++;
        wedges += 8;
        break;
      case "large":
        limesCut++;
        wedges += 10;
        break;
    }
  })
  return limesCut;
}
```

**Comment by SleeplessByte** [comment]
Great! Good luck on the next one 😄
