### ISSUE TITLE
Bug report: redirected to site.manifest after going through GitHub Oauth flow

### ISSUE THREAD

**Issue by philcrissman** [exercism/exercism#6314]
IIRC what I did was:

1. Was viewing the list of tracks https://exercism.org/tracks
2. Selected a track (I selected Racket)
3. Saw the login-with-github-or-create-an-account-page
4. Clicked GitHub
5. Clicked whatever on the GitHub page that gives permission to exercism for me to login
6. When redirected to exercism, wound up looking at: https://exercism.org/site.webmanifest

As soon as I just went to a new tab and went to exercism.org, I saw the main site and was already authenticated; so the auth worked, but something about the redirect probably did something it wasn't supposed to.

Just wanted you all to know!

PS, just visiting the site after not having seen it for many years and it looks AMAZING, you all are awesome & thank you!

**Comment by philcrissman** [comment]
I didn't mention this issue on twitter: I did do a little shout-out for exercism.org, but did not mention the login/redirect issue, I figured reporting it on GitHub would be good enough. :)

**Comment by iHiD** [comment]
No, that's great. Thanks. OK, @ErikSchierboom could you look at this as a priority pls. I suspect we need to stop `site.webmanifest` being added to the devise redirect chain (ie, add it here: https://github.com/exercism/website/blob/main/app/controllers/application_controller.rb#L75)

**Comment by philcrissman** [comment]
🎉 🤘
