### ISSUE TITLE
Suboptimal rendering of emphasized elements in list

### ISSUE THREAD

**Issue by siebenschlaefer** [exercism/exercism#6320]
Emphasized text insider a list gets rendered without distance to the previous or next word.

This is a screenshot of the instructions of the word-count exercise on the C++ track, as shown by Firefox (v99.0):
![firefox-99 0](https://user-images.githubusercontent.com/1228739/162368112-7038c6a0-1f9e-4e23-be15-7431612b1282.png)

This is how it is shown by Chrome (v100.0.4896-75)
![chrome-100 0 4896 75](https://user-images.githubusercontent.com/1228739/162368115-42d74820-3084-4431-9354-cbbcc9358955.png)

(both on Ubuntu-21.10)

As you can see the "word" in the first two sentences gets rendered correctly, but "number" or "simple word" in the list gets visually joined with the preceding and following words.

I'm pretty sure this is some CSS issue, because the [original Markdown file](https://raw.githubusercontent.com/exercism/cpp/main/exercises/practice/word-count/.docs/instructions.md) looks correct, and a quick look with the inspector did not show anything wrong in the DOM.

**Comment by siebenschlaefer** [comment]
This might or might not be a duplicate of issue #5654

**Comment by NobbZ** [comment]
Do you perhaps have any user styles or overrides active?

I just checked the instructions for the word count exercise via https://exercism.org/tracks/cpp/exercises/word-count, and there I do see a numbered list that does not use a monospace font, and also has the spaces between words as expected.

I do not have any instructions in my iterations though.

**Comment by siebenschlaefer** [comment]
No, no user styles or overrides.  
Take a look at the tab "Instructions" on the mentoring page of [my solution](https://exercism.org/mentoring/external_requests/64d60652-08d0-11ec-81c5-853579c25f94). Does it render the emphasized words in the list correctly?

**Comment by NobbZ** [comment]
Indeed, there it looks weird for me as well:

![image](https://user-images.githubusercontent.com/58951/162379316-603adb94-bb66-406c-9735-d6df06271623.png)

Checked using:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
--
Command Line | /nix/store/gp9qv0izh6ssq3xxnb271wrysmk6qr6d-google-chrome-100.0.4896.60/share/google/chrome/google-chrome --enable-crashpad --flag-switches-begin --flag-switches-end
```

**Comment by NobbZ** [comment]
Perhaps that is related to `codemirror` trying to be smart and rendering the markdown instead of "source highlighting" it?

**Comment by siebenschlaefer** [comment]
Might be but I'm out at this point. I'm not a web developer, I know far too little about modern CSS any of the building blocks that Exercism uses. I hope somebody else can figure that out.

**Comment by NobbZ** [comment]
Yeah, it is the same for me, though the source editor is basically the only difference I see between my first and second screenshot.

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/2589

The issue was that the CSS for dealing with the linenumbers on the code tab, was also being applied here. I've improved the scoping of the CSS so that's no longer the case.
