### ISSUE TITLE
In-browser editor timing out?

### ISSUE THREAD

**Issue by Applefrittr** [exercism/exercism#6321]
Hi all,

The in-browser editor is currently timing out on all submitted code.  I've even tried re-running some of my solved solutions and quite literally passed 'return "test"' on a few of them as well to no avail.  Anyone else experiencing this?  Running on Firefox version 99.0

**Comment by Applefrittr** [comment]
Oh forgot to mention this is on the JavaScript track

**Comment by SleeplessByte** [comment]
Sorry! We've accidentally scheduled a bunch of work in the regular queue instead of background. It will be back to normal soon!

**Comment by ErikSchierboom** [comment]
Yes, sorry! We've canceled the background work, and I've just been able to successfully run the test runner for a Ruby exercise. So hopefully, you'll be able to run online tests again.

**Comment by iHiD** [comment]
Things should be back to normal now. Could you please confirm thanks.

**Comment by Applefrittr** [comment]
Smooth sailing now, thanks!
