### ISSUE TITLE
Admonitions should have some bottom margin

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/exercism#6323]
I created an admonition that comes directly before a h4 and it looks too cramped to me because the admonition has no bottom margin:
![Screenshot 2022-04-10 at 16 53 24](https://user-images.githubusercontent.com/7852553/162625456-346b67da-8d04-4dc0-ba90-af0e6b4c842c.png)

**Comment by iHiD** [comment]
Got a link to the concept/exercise pls?

**Comment by angelikatyborska** [comment]
In exercise `introduction.md` in the editor: https://exercism.org/tracks/elixir/exercises/dancing-dots

Concept `introduction.md`s with the same content on concept pages look better (https://exercism.org/tracks/elixir/concepts/behaviours), they do have some margins.

**Comment by iHiD** [comment]
Thanks. https://github.com/exercism/website/pull/2592
