### ISSUE TITLE
Linux and COBOL

### ISSUE THREAD

**Issue by FaII-en1** [exercism/exercism#6328]
I feel like Linux and COBOL both should be on the list because they have their own sub categories especially linux as we have full access of the Kernel of the device.

**Comment by kytrinyx** [comment]
@FaII-en1 If Would you please clarify what your request is about? Which list do you mean? Are you asking that we provide an Exercism Linux track and an Exercism COBOL track?

**Comment by FaII-en1** [comment]
Sorry if you misunderstood me. The thing is I was redirected here after opening a link on your browser page to submit a request for any other programming languages that you can also give lessons for, that's all. Since linux is in its own league and COBOL codes are still being executed with every electronic transaction, I was browsing the course list for it because I haven't found a credible source as how to acquire the different distributions and run them on Oracle VM because after many failed attempts, I really don't understand if I am missing a step or if I am following a step that's causing the issue.

**Comment by kytrinyx** [comment]
Thank you for the suggestions.

Linux is not a programming language, but rather an operating system. As such, it falls outside the scope of what Exercism does.

COBOL is an excellent language, and there are indeed many systems that are still in production. About 6 months ago, someone offered to create a COBOL track, and we created a repository for it here: https://github.com/exercism/gnucobol/issues/1

If you are interested in assisting, please comment in the issue there, and you can discuss with the person leading this effort how best you can help out.
