### ISSUE TITLE
Problems with promises (JS) exercise

### ISSUE THREAD

**Issue by leerohrer1** [exercism/exercism#6329]
Hello! 

When I try to run tests locally on the promises exercise, I get this error:
Cannot find module 'core-js/fn/promise' from 'promises.js'

When I run my code in the exercism editor, I get this error: 
ReferenceError: resolve is not defined

Here is my code:

import { reject } from "core-js/fn/promise";
import { resolve } from "path";

export const promisify = (functionToPromisify) => {
  return functionToPromisify = new Promise(resolve, reject)
  .then((a) => {resolve(a)})
  .catch((e) => {reject(e)})
};

I'm not sure how to solve this problem. Please help!

Thank you,
Lee

**Comment by SleeplessByte** [comment]
```javascript
export const promisify = (functionToPromisify) => {
return functionToPromisify = new Promise(resolve, reject)
.then((a) => {resolve(a)})
.catch((e) => {reject(e)})
};
```

Hi there @leerohrer1, the code you've posted is calling `new Promise` with two arguments: `resolve`, `reject`. It's trying to import those values from two packages: `cor-js/fn/promise` and `path`. This is probably not what you meant to do. The `Promise` constructor doesn't take two arguments, but only a single:

a callback that receives two arguments

```javascript
// Not this
import { reject } from "core-js/fn/promise";
import { resolve } from "path";

new Promise(resolve, reject)
```

```javascript
// But this

// no imports

new Promise((resolve, reject) => {
  // ... do something with resolve and/or reject
})
```

Does this help?

**Comment by leerohrer1** [comment]
Derp. Yes that is very helpful, thank you so much!

**Comment by SleeplessByte** [comment]
Sweet. Feel free to leave another comment if you're still stuck.
