### ISSUE TITLE
When/How are exercises updated to new versions?

### ISSUE THREAD

**Issue by patricksjackson** [exercism/exercism#6332]
(I'm a maintainer on the Cpp track)

We had an issue with the online editor for 2 exercises, which required a change to a build file to fix (https://github.com/exercism/cpp/pull/495). Some users are still seeing issues even though others seem to be able to use it just fine (https://github.com/exercism/cpp-test-runner/issues/48)

What I _think_ is happening is that new users have no issues solving it, however if a user has already submitted a solution there doesn't seem to be a way to update to the latest version. My account has submitted one of those exercises but not the other so I can see both of those states on the website, and I confirmed with a test account that the exercises work fine for a new user.

I don't really understand how the process of updating a users exercise version actually works and I couldn't find a description in the `exercism/docs` repo, so I'm not sure what's going on. There used to be a way to update the version on the website but the option in the editor to "Revert to exercise start" doesn't seem to update the build file.

My wild guess is that existing exercises aren't updated to a new commit unless a file listed in the `.meta/config.json` file is updated, but newcomers to the exercise get the latest version. The build file that we needed to change isn't listed in the `config.json`.

Q1: Is there still a way to force update a users exercise to the latest version?
Q2: How can we make sure that updates to the build files cause an update to the user's existing solutions?

**Comment by ErikSchierboom** [comment]
> My wild guess is that existing exercises aren't updated to a new commit unless a file listed in the .meta/config.json file is updated,

That is indeed correct. We do have a plan that involves adding a new field to the `files` property in the `.meta/config.json` file, which is for files that should also be taken into account when determining whether or not an exercise can be updated. We just not haven't gotten around to implementing it. I'll move it more to the top of my todo list.

**Comment by patricksjackson** [comment]
Thanks Erik, that helps a lot. We can workaround it now that I understand what's going on.
