### ISSUE TITLE
Incorrent exercises count in rust syllabus concepts

### ISSUE THREAD

**Issue by me-ZaidAli** [exercism/exercism#6337]
The exercises count in each one of the concepts for rust's pathway syllabus doesn't match the actual number of exercises in that concept

<img width="1531" alt="Screenshot 2022-04-26 at 1 50 27 AM" src="https://user-images.githubusercontent.com/61061679/165175694-2f97fff3-1549-4d8a-8686-e3802ef31691.png">
<img width="1469" alt="Screenshot 2022-04-26 at 1 51 15 AM" src="https://user-images.githubusercontent.com/61061679/165175716-128a39ee-d87a-41cf-95ce-187b019f45b8.png">

Would be more than happy to work on it :)

**Comment by iHiD** [comment]
@me-ZaidAli Thanks for reporting.
@ErikSchierboom I'm guessing this is an artifact of WIP exercises?
