### ISSUE TITLE
Feature Request: please make pagination a multiple of your view

### ISSUE THREAD

**Issue by gacallea** [exercism/exercism#6339]
Hi,

a picture is worth a thousand words:

![FRQgBWnXEAArmKk](https://user-images.githubusercontent.com/3269984/165751622-6e2481c1-b90d-4357-9be2-9fd1e6c261d4.jpg)

that is the pagination of my profile -> solutions. I'm not sure if this is a valid concern on all different type of screens/resolutions, but it would make sense for pagination to be a multiple of the solutions "view". In this case 24 vs 25 would result in an evenly distributed number of "cards".

Thank you :)

**Comment by iHiD** [comment]
@ErikSchierboom It'll need to be a multiple of 1, 2 and 3.

**Comment by SleeplessByte** [comment]
12 and 24 are good candidates.

```
12 / 1 = 12
12 / 2 = 6
12 / 3 = 4

24 / 1 = 24
24 / 2  = 12
24 / 3 = 8
```

**Comment by ErikSchierboom** [comment]
12 and 24 also have the benefit of being divisible by 4, in case we ever do want to support that.

**Comment by SleeplessByte** [comment]
Don't stop there. You can also divide by 6. 

The magic of base 12

**Comment by gacallea** [comment]
Hi @iHiD @SleeplessByte @ErikSchierboom :)

thank you so much for implementing this, I appreciate <3

I was wondering if this is going to show up on my Exercism profile/rep?

Cheers!

**Comment by ErikSchierboom** [comment]
@gacallea I'm afraid not. We only award reputation for issue authors when the issues them have required a large amount of work. That's not to downplay your issue, as it was a great bug report, but it doesn't match our criteria for awarding reputation to issues authors, sorry.

**Comment by gacallea** [comment]
> @gacallea I'm afraid not. We only award reputation for issue authors when the issues them have required a large amount of work. That's not to downplay your issue, as it was a great bug report, but it doesn't match our criteria for awarding reputation to issues authors, sorry.

Hi @ErikSchierboom :)

I understand and won't “take it personally”, I'm just glad to help. However, allow me this suggestion: adjust your criteria to reward every contribution, regardless of it being gargantuan or not. The way you are currently putting this, could make any potential contributor feel their feedback is insignificant and “so, what's the point of even contributing?!?!”

An idea could be to reward meaningful contributions (e.g: they bring actual improvements) and have a different scale to measure them and give more rep points to large ones.

My 2c.

Cheers!

**Comment by iHiD** [comment]
Hi @gacallea - thanks for your suggestion. To be clear, Erik wasn't saying we only award big pieces of work. If someone fixes something via submitted a PR we award rep regardless of whether it's big or small. However, we currently don't award reputation for opening issues about bugs. 

If we did that we'd end up very quickly getting spammed by people just doing so for reputation, rather than who were creating helpful bug reports, and as it takes us a lot of time to read all the issues that people opened, even if we only awarded it conditionally we'd still likely get swamped. 

If you see a way around that, I'd love to hear it as I'd love to reward helpful bug reports, but unless we solve that potential spam-vector it's not something we can do.

**Comment by gacallea** [comment]
> If we did that we'd end up very quickly getting spammed by people just doing so for reputation, rather than who were creating helpful bug reports, and as it takes us a lot of time to read all the issues that people opened, even if we only awarded it conditionally we'd still likely get swamped.

Hi @iHiD,

I didn't consider this, and I agree. Also, I kinda forgot that I did not PR this for a minute. I don't think I have a solution to my “idea”, and if you are already rewarding all kind of contribution (as long as they are PRs), then my comment is moot. :)

Thank you for taking the time to discuss this.

Cheers!
