### ISSUE TITLE
Rust: YOUR TESTS TIMED OUT

### ISSUE THREAD

**Issue by Araxeus** [exercism/exercism#6353]
![image](https://user-images.githubusercontent.com/78568641/167254002-89efa0da-f907-4d85-b841-abd34b820999.png)

I've tested the code locally and it works perfectly, I also tried submitting both from CLI and in the website

Exercise: https://exercism.org/tracks/rust/exercises/resistor-color

Code:
```rust
use int_enum::IntEnum;
use enum_iterator::IntoEnumIterator;

#[repr(usize)]
#[derive(Clone, Copy, Debug, PartialEq, IntEnum, IntoEnumIterator)]
pub enum ResistorColor {
    Black = 0,
    Brown = 1,
    Red = 2,
    Orange = 3,
    Yellow = 4,
    Green = 5,
    Blue = 6,
    Violet = 7,
    Grey = 8,
    White = 9,
}

pub fn color_to_value(_color: ResistorColor) -> usize {
    _color.int_value()
}

pub fn value_to_color_string(value: usize) -> String {
    match ResistorColor::from_int(value) {
        Ok(color) => format!("{:?}", color),
        Err(_e) => String::from("value out of range")
    }
}

pub fn colors() -> Vec<ResistorColor> {
    ResistorColor::into_enum_iter().collect()
}
```

Since tests run fine on my PC, I assume this is a bug?

**Comment by Araxeus** [comment]
FYI I've tried over 20 times at different times of day, and I always get the same error on submit

**Comment by SleeplessByte** [comment]
cc @exercism/rust

**Comment by Araxeus** [comment]
This is still happening and very annoying...

Is anyone looking into this?

**Comment by coriolinus** [comment]
Procedural macros can substantially slow down the Rust compiler, and in this example you're using at least two of them: `IntEnum` and `IntoEnumIterator`. Add that to the additional time required to compile dependencies, and it's not that surprising that you're timing out; the timeout limit is only two seconds. I'd kind of expect this to take more than two seconds to compile, at least the first time, and the student test runners can't take advantage of a compilation cache.

In general, particularly if you're developing locally, you should feel free to just not run the online tests. If they pass locally, that's sufficient. Mark the exercise as complete and move on. If you really want to use the online test runner, then try implementing this without those procedural macros.

**Comment by Araxeus** [comment]
Wait are you serious? the exercise literally tells you to use those crates:

> For tasks number two and three, you will need external crates [enum-iterator](https://docs.rs/enum-iterator/0.7.0/enum_iterator/) and [int-enum](https://docs.rs/int-enum/0.4.0/int_enum/), which are included in this exercise's Cargo.toml. Be sure to check the crates' documentation to learn how to use them.

Either fix the exercise or rewrite it....

**Comment by coriolinus** [comment]
There are two competing goals in play:

- Teach Rust; this involves knowing about the crate ecosystem and procedural macros and how to use each. This is why we have this exercise.
- Offer a smooth web experience without requiring students to install a development environment on their local computer and without spending excessively large amounts of money on cloud resources running the student tests. This is why we have timeouts. 

Note: your code is not failing the tests. As you have said, it works fine locally. Just mark the exercise as complete and move on.

**Comment by Araxeus** [comment]
So you expect that every time a user faces this 'bug', they come here and open an issue and then you tell them to skip the tests?

Why don't you rewrite the instructions(/add a note), explaining what you just told me, that the online tests will always fail?

**Comment by iHiD** [comment]
> Wait are you serious?

@Araxeus Please be careful of your tone.

---

@coriolinus You can set the `test_runner: false` in the exercise's `config.json`, which will mean that the website doesn't expect test runners to succeed within the timeframe, and then it informs the user accordingly.

**Comment by Araxeus** [comment]
@iHiD Thank you and sorry for my seemingly aggressive tone

**Comment by iHiD** [comment]
@Araxeus Thanks 🙂 

I believe @coriolinus has now updated the track, so I think this can be closed.
