### ISSUE TITLE
JavaScript | Mixed Juices Exercise | Timed out tests

### ISSUE THREAD

**Issue by kajajaronska** [exercism/exercism#6355]
I receive "Your tests timed out error" on JavaScript Mixed Juices exercise - Task 2. I have came up with two possible solutions for the exercise and checked both on my local machine and also in CodePen environment (links below), so I am certain that I have no infinite loops. Thank you for looking into this for me. 

https://codepen.io/kajkajajka/pen/abqdZzM
https://codepen.io/kajkajajka/pen/dydGXYP

**Comment by iHiD** [comment]
(cc @exercism/javascript)

**Comment by iHiD** [comment]
@kajajaronska You might like to look at https://github.com/exercism/exercism/issues/6309 as I suspect this is a duplicate of that 🙂

**Comment by SleeplessByte** [comment]
Both of the solutions have infinite loops :). @kajajaronska shout if you want help finding them. If you want to try yourself first, the issue linked by @iHiD should help. The same issue is present in both provided solutions.

**Comment by kajajaronska** [comment]
thank you Both! I will look for the infinite loops and will be back if I am stuck (again!) 🙌🏼

**Comment by kajajaronska** [comment]
Got it - thank you so much again! I tend to forget to return from functions ... 🙈 

`function limesToCut(wedgesNeeded, limes) {
  let limesUsed = 0;

  while (wedgesNeeded > 0) {
    if(limes.length === 0) return limesUsed;

    switch (limes[0]) {
      case "small":
        wedgesNeeded -= 6;
        limesUsed++;
        break;

      case "medium":
        wedgesNeeded -= 8;
        limesUsed++;
        break;

      case "large":
        wedgesNeeded -= 10;
        limesUsed++;
        break;
      default:
        return limesUsed;
    }

    limes.shift();
  
  }

  return limesUsed;
}`
