### ISSUE TITLE
track repos: README top-level header: some still have old `x` prefix

### ISSUE THREAD

**Issue by ee7** [exercism/exercism#6363]
For example, the [`README.md`](https://github.com/exercism/plsql/blob/82abf9d18e0f/README.md) for `plsql`:

Currently:

```
# xPL/SQL
```

Expected:

```
# Exercism PL/SQL Track
```

Like e.g. the [`README.md`](https://github.com/exercism/ruby/blob/758b70398d04/README.md) for the `ruby` track.

**Comment by kytrinyx** [comment]
I wrote a script that checks all the track READMEs. Some had the `x` prefix, others had just the programming language name as the title.

I've now normalized everything to **Exercism {LANGUAGE} Track** to match what the bootstrap script has.

**Comment by kytrinyx** [comment]
This should now be in order. Thanks again for reporting!
