### ISSUE TITLE
How to get files of a solution?

### ISSUE THREAD

**Issue by lf94** [exercism/exercism#6364]
I'm trying to make a benchmark comparator using exercism.io solutions - while I'm able to get a list of solutions, it seems the URL to get the actual file contents is constructed in the backend?...

My goal is to simply compare some Standard ML solutions to Go solutions (speed, resource usage).

**Comment by iHiD** [comment]
Yeah, the API isn't intended for scraping like that at the moment really. What exactly are you trying to download? Maybe we can send you some instead?

**Comment by lf94** [comment]
I was just going to write some simple shell script where you input a source and target language, the solution, and then it tries to download both and run them... It's all good, thank you for the reply!
