### ISSUE TITLE
Fixup Stripe donations

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#6365]
Stripe donations were not correctly being taken after the first month. This step was missing from the implementation:
<img width="833" alt="Screenshot 2022-05-16 at 19 09 37" src="https://user-images.githubusercontent.com/286476/168687956-25eeecf4-cec7-4f96-b581-bb575c04f527.png">

This is fixed in https://github.com/exercism/website/pull/2659 but data now needs sorting and people contacting. In addition, there is some future work needed to avoid some of the spamming issues we are getting. 

**This issue is a tracking issue for @iHiD/@erikschierboom to get us to a good state again.**

## Summary

- [x] Find/fix the issue (Jeremy)
- [x] Merge/deploy https://github.com/exercism/website/pull/2659 (Erik)
- [x] Update all live subscriptions to have correct card (Erik - see below)
- [x] Get a list of failed subscriptions (Erik - see below)
- [x] Email old subscribers (Jeremy)
- [x] Remove Stripe when not logged in (https://github.com/exercism/website/pull/2665)
- [x] Cleanup old customers (Erik - see below)

## Update all live subscriptions to have correct card

There are lots of subscriptions where the payments failed. Initially these all got cancelled. I then changed it so that these **wouldn't** get cancelled, but would just continue failing.

- Cancelled: https://dashboard.stripe.com/customers/cus_K9YWvv91OnRJnY
- Retrying: https://dashboard.stripe.com/subscriptions/sub_1Ko8XaEoOT0Jqx0UErNZ5Pdr
- Lots of drafts: https://dashboard.stripe.com/subscriptions/sub_1Jrq64EoOT0Jqx0U8mrWJtAx (e.g. https://dashboard.stripe.com/invoices/in_1KvSMmEoOT0Jqx0UMNiKK6S6)

We want a couple of scripts here. 

For the ones that are cancelled:
1. Put their name/email in a list for me.
2. Cancel their subscriptions in the DB too.

For the ones that are active but failing, we want to fix the account and charge the most recent invoice only:
1. Set the default card on the Subscription to be the most recent payment method on the customer
2. "Charge" the most recent invoice (this might be "overdue" or "draft" I think).
3. Cancel the old (unpaid/draft) invoices.

If you put two scripts together for those two scenarios, I'll pair with you on running them later in the week.

## Cleanup old customers

Due to spam issues, we have about 168,000 customers who aren't actually customers but are on our account. Me doing "Remove Stripe when not logged in" will fix this, but the old customers need deleting.

I think the easiest way to do this is to paginate through all customers, finding any who have **never** donated any money, and removing them from our account. We should only remove accounts that were created 24hrs or more before the script runs (ie don't touch anything created within the last day).

If you look on 21st Feb on the Stripe Dashboard, you'll see lots of example spam customers that can be removed.

Put together a script and we can run it together.

**Comment by ErikSchierboom** [comment]
I think this can now be closed. There are some individual cases to look into, but the tasks listed here have been taken care of I think?
