### ISSUE TITLE
I'm getting an error when trying to run 'npm test'

### ISSUE THREAD

**Issue by rockysingh3** [exercism/exercism#6368]
So I get the error:    Cannot find module 'core-js/fn/promise' from 'promises.js'

What do you think this could be from? I'm importing resolve and reject like this: 

import { reject, resolve } from "core-js/fn/promise";

I checked the core-js file and it looks right

**Comment by iHiD** [comment]
Hello, which exercise? Presumably the JS track? Could you paste all your code pls?

**Comment by angelikatyborska** [comment]
@rockysingh3 Please see this comment on a similar issue: https://github.com/exercism/exercism/issues/6329#issuecomment-1102638475 the gist of it is that you don't need to import anything.

**Comment by SleeplessByte** [comment]
Rocky responded on Slack that they had figured it out.
