### ISSUE TITLE
unauthorized access to exercise solutions

### ISSUE THREAD

**Issue by wojciech-lasota** [exercism/exercism#6378]
Hi,
The lock next to Community Solutions link says, you can not enter until you finished exercise, its only cliceable after finish exercise, but its enaught to add /solutions to the end of current site adress to enter Community Solutions page.

**Comment by iHiD** [comment]
Hi. Thanks for reporting! This is by design though, rather than a vulnerability, so I'm going to close this. We don't mind if people "cheat" on Exercism as they get nothing as a reward.

**Comment by SleeplessByte** [comment]
(closing per your comment)
