### ISSUE TITLE
A Suggestion about "Publish Your Iteration(s)"

### ISSUE THREAD

**Issue by Cv03** [exercism/exercism#6379]
> When I finish an exercise, I mark it as completed, and I choose either all my iterations or one of them and publish them (it).

I think this is somehow strange, as showing the whole collection of iterations can help others understand the evolution of your code (and your thought), but sometimes not all iterations are "good enough" for publishing, I mean trivial mistakes like missing semicolons, misspelling in comments, text reformating, etc. It would be better to be able to choose **some part** of your iterations, *not **all** or **just one***.

**Comment by glennj** [comment]
You can delete the iterations you're not happy with.

**Comment by Cv03** [comment]
> You can delete the iterations you're not happy with, or that provide no additional value. I do that frequently.

It was… amazing. Seems like I had asked a stupid question? Thank you!🤣
