### ISSUE TITLE
Is there a way to change the location of the work environment?

### ISSUE THREAD

**Issue by RHieger** [exercism/exercism#6383]
Hi,

I am coming back to exercism after a long hiatus during which I did quite a bit of independent study. I have elected to start from the beginning and plow through the exercises that are easier.

**I am wondering, however, if it is possible to move the location of the Exercism work environment, and if so, how.**

I am working on a MacBook Pro with a 1TB SSD, but I have an external HDD that is 2TB that I use for development. It would be preferable for me to have the work environment there if at all possible.

I look forward to any insight you can provide.

Thank you,

Robert Hieger

**Comment by kytrinyx** [comment]
If you call the CLI's `configure` command (`exercism configure`) it will show you what the current workspace is. You can call the same command and pass `-w` to set the workspace to a different path.

**Comment by RHieger** [comment]
Thank you for your assistance.

Ironically, I accidentally fell onto this solution just before reading your suggestion and was able to set the path to the volume of my choice.

Again, thanks for the assistance,

Robert Hieer
