### ISSUE TITLE
"Change published iterations" doesn't show all iterations

### ISSUE THREAD

**Issue by asarkar** [exercism/exercism#6385]
"Change published iterations" only shows the first iteration. The workaround is to unpublish and publish again.

**Comment by glennj** [comment]
Can't reproduce. Can you give some details about your browser, and give a screenshot if possible.

**Comment by asarkar** [comment]
https://user-images.githubusercontent.com/1302775/170859553-a044e6aa-91e5-44ee-94ae-8357a471f32a.mov

I made this video to demonstrate the issue. GitHub doesn't allow uploading files > 10 MB, so the resolution is crappy, but if you increase the player window, you'll be see enough.

I'm using Chrome.

**Comment by asarkar** [comment]
I found a similar bug is already open, except the workaround I suggested.
https://github.com/exercism/exercism/issues/6303
