### ISSUE TITLE
Fetch next exercise

### ISSUE THREAD

**Issue by marcesdan** [exercism/exercism#6394]
Hi! Time ago you could fetch the next exercise through the CLI (or I dreamed it?)

It is currently possible to do it?

**Comment by kytrinyx** [comment]
@marcesdan You didn't dream it!

For a while it was possible, but there's no longer a clear concept of "next" so we couldn't figure out a reasonable way to implement it.

I know we've had a (super interesting) discussion about this, but I can't find the issue at the moment. I'm going to leave this open so I can take another stab at digging around to see if I can find it.

**Comment by kytrinyx** [comment]
Ok! Here is the comment I was thinking about: https://github.com/exercism/exercism/issues/6333#issuecomment-1106771380

I'm going to go ahead and close this one, and if you have more thoughts or suggestions, please add them to the conversation in the linked issue.
