### ISSUE TITLE
Rate the solutions by time taken and memory used 

### ISSUE THREAD

**Issue by asarkar** [exercism/exercism#6395]
Currently, there's a bunch of community solutions, some better than others, there's no way to tell how they "rank" against each other. If I want to learn from others, understandably, I only want to learn from the best. Same goes for a student's own solution, they may work hard to optimize the algorithm, or go for a naive one, it's all the same if it passes the tests.

It'll be nice to see each published solution rated as "80% faster (21ms),  33% less memory (2MB), out of 2951 total solutions". The number of total solutions at the time is important because it will obviously keep increasing over time.

Student should see the same data when they submit their own solution, published or not.

**Comment by kytrinyx** [comment]
Yes, while speed and memory are not always the most important factor in what makes good code, it certainly is a factor to be taken into account. We have an open issue tracking this here: #5043

I'm going to go ahead and close this as a duplicate, but please do read through the linked discussion, and if you feel there are more things to add, please do so there.
