### ISSUE TITLE
Individual students' "solutions" display on exercism.org not working for Common Lisp

### ISSUE THREAD

**Issue by eigenhombre** [exercism/exercism#6398]
Moved from [1].

https://exercism.org/profiles/eigenhombre/solutions?track_slug=common-lisp shows no completed exercises (there should be >20), but
https://exercism.org/profiles/eigenhombre/solutions?track_slug=python shows several.

This is on Firefox 100.0.2 on MacOS 11.6.4.

[1] https://github.com/exercism/common-lisp/issues/647

**Comment by glennj** [comment]
Are those common-lisp solutions actually published? That's a separate step than completing a solution.

**Comment by eigenhombre** [comment]
@glennj Yes, as far as I can tell they are.  For example, I see "Your published solution... published 10d ago" on one of the problems.

**Comment by eigenhombre** [comment]
Also, my solutions for other tracks (e.g. Python, Clojure) *do* appear under their corresponding URL(s).

**Comment by glennj** [comment]
What's one of your CL solutions? I'd like to check if I can see it in the community solutions

**Comment by eigenhombre** [comment]
https://exercism.org/tracks/common-lisp/exercises/pizza-pi/solutions/eigenhombre

**Comment by glennj** [comment]
Yes, I can see that.

**Comment by glennj** [comment]
I note that my own common-lisp solutions are not visible under my profile.

If this is useful, the metadata for my common-lisp grains exercise, showing that it has been published
```json
{
  "solution": {
    "uuid": "3f33274300514093817cd4c357a99682",
    "private_url": "https://exercism.org/tracks/common-lisp/exercises/grains",
    "public_url": "https://exercism.org/tracks/common-lisp/exercises/grains/solutions/glennj",
    "status": "published",
    "mentoring_status": "none",
    "published_iteration_head_tests_status": "passed",
    "has_notifications": false,
    "num_views": 0,
    "num_stars": 0,
    "num_comments": 0,
    "num_iterations": 1,
    "num_loc": 0,
    "is_out_of_date": true,
    "published_at": "2019-08-03T12:21:30Z",
    "completed_at": "2019-08-03T12:21:28Z",
    "updated_at": "2022-06-07T13:59:40Z",
    "last_iterated_at": null,
    "exercise": {
      "slug": "grains",
      "title": "Grains",
      "icon_url": "https://dg8krxphbh767.cloudfront.net/exercises/grains.svg"
    },
    "track": {
      "slug": "common-lisp",
      "title": "Common Lisp",
      "icon_url": "https://dg8krxphbh767.cloudfront.net/tracks/common-lisp.svg"
    }
  }
}
```

**Comment by SleeplessByte** [comment]
Possible issue: because of the `-` in the slug. 

I can see `emacs-lisp` also not working, but all "single word" tracks _are_ working. Is it possible that the `-` is decoded out of the url / value during querying and that makes the slug incorrect and thus the solutions not show @ErikSchierboom ?

**Comment by ErikSchierboom** [comment]
I'll look into this!

**Comment by ErikSchierboom** [comment]
Found the issue and created [a PR](https://github.com/exercism/website/pull/2699) to fix this.
