### ISSUE TITLE
Email change issue

### ISSUE THREAD

**Issue by iamramanavenkat** [exercism/exercism#6401]
When I'm trying to **change** my mail ID I'm getting this but I didn't get any email to change my email to that specific email that mentioned
![image](https://user-images.githubusercontent.com/63152308/172748112-75f797c2-62ca-4eeb-a8df-34f9a9ae74c7.png)

**Comment by iHiD** [comment]
Have you checked your promotions folder and spam? It often ends up in one of those.

**Comment by iamramanavenkat** [comment]
Yes I've checked that. There's no mail from Exercism regarding that.

**Comment by iHiD** [comment]
I'll need your email address to check. If you email jeremy@exercism.org I'll take a look tomorrow.

**Comment by iamramanavenkat** [comment]
Now I changed my mail ID. I did a silly mistake that I entered the email I'm using actually instead of new mail ID.
Thanks for your support. I'm closing this issue.
