### ISSUE TITLE
Create new track for Selenium Automation Web Driver

### ISSUE THREAD

**Issue by ashwinran18** [exercism/exercism#6406]
Hi,
I would like to request you to please add Selenium Full track on Exercism.org.
Thank you.

**Comment by kytrinyx** [comment]
Thank you for your suggestion @ashwinran18.

At the moment we don't make courses for specific frameworks, libraries, tools, or technologies. While we may change the scope of things in the future, at the moment we're only making new tracks for programming languages.

As such I'm going to close this issue as `wontfix`.
