### ISSUE TITLE
New test runner repo fails Deploy workflow: missing secrets?

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#6407]
I merged to main in exercism/awk-test-runner, and the Deploy workflow failed:
```
Run docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
  with:
    ecr: auto
    logout: true
  env:
    ECR_REGISTRY: ***.dkr.ecr.***.amazonaws.com
Error: Username and password required
```
https://github.com/exercism/awk-test-runner/runs/6901931906?check_suite_focus=true

**Comment by glennj** [comment]
@ErikSchierboom , if you would be so kind...

**Comment by ErikSchierboom** [comment]
@glennj Ah, yes. I've created https://github.com/exercism/terraform/pull/76 to allow the test runner to be used in production. Unfortunately, I can't add the secrets, @iHiD has to do that. He's busy today, but he can perhaps do this tomorrow.

**Comment by iHiD** [comment]
https://github.com/exercism/awk-test-runner/actions/runs/2502978265 🙂

**Comment by ErikSchierboom** [comment]
With the above workflow running successfully, the AWK test runner is now ready to be used/tested in production. I've just added the awk track to the production database. As the track is still inactive (rightly so), only maintainers will be able to see the track. As inactive tracks are not shown in the tracks overview, you need to directly go to https://exercism.org/tracks/awk/ Currently, the online editor is still disabled in the track's `config.json`. To enable the test runner, set the `status.test_runner` field to `true`. 

Apart from that, you should be able to test the track (CLI should already be working).
