### ISSUE TITLE
"Files" tab bar height is inconsistent in solutions view

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#6420]
Consider https://exercism.org/tracks/awk/exercises/two-bucket/solutions/glennj
I have submitted 3 files, and the tab bar height changes for each one:
* [![first][tb1]][imgs]
* [![second][tb2]][imgs]
* [![third][tb3]][imgs]

Consider this extreme case on https://exercism.org/tracks/awk/exercises/secret-handshake/solutions/glennj
* [![barely readable][sh]][imgs]

[sh]: https://raw.githubusercontent.com/glennj/glennj.github.io/master/exercism/issue_img/secret-handshake.png
[tb1]: https://raw.githubusercontent.com/glennj/glennj.github.io/master/exercism/issue_img/two-bucket.1.png
[tb2]: https://raw.githubusercontent.com/glennj/glennj.github.io/master/exercism/issue_img/two-bucket.2.png
[tb3]: https://raw.githubusercontent.com/glennj/glennj.github.io/master/exercism/issue_img/two-bucket.3.png
[imgs]: https://github.com/glennj/glennj.github.io/tree/master/exercism/issue_img

**Comment by iHiD** [comment]
@ErikSchierboom This is a result of one of the PRs to do with overflowing on tabs I suspect.
