### ISSUE TITLE
Create new track for [LANGUAGE]

### ISSUE THREAD

**Issue by Ramsey555** [exercism/exercism#6444]
DIs exercism still active?

**Comment by kytrinyx** [comment]
Yes, it's still active.

If you want to develop a new track, you can make the request here: https://github.com/exercism/request-new-language-track

**Comment by Ramsey555** [comment]
Thanks I didn't see much activity and I thought the site is dead

**Comment by kytrinyx** [comment]
Which site are you looking at? There's a ton of activity every day, much more than there's ever been before.

**Comment by Ramsey555** [comment]
Thanks I am looking for Php and Python.

**Comment by kytrinyx** [comment]
PHP is here: https://exercism.org/tracks/php and Python is here: https://exercism.org/tracks/python

**Comment by Ramsey555** [comment]
Thank you let me share with my work colleagues also

**Comment by iHiD** [comment]
@Ramsey555 Out of interest, what sort of activity were you expecting to see to make you feel like it was more alive?

**Comment by Ramsey555** [comment]
> @Ramsey555 Out of interest, what sort of activity were you expecting to see to make you feel like it was more alive?

I thought I would see a chat center like code wars
