### ISSUE TITLE
[Observation] Consistency with Community Solutions

### ISSUE THREAD

**Issue by habere-et-dispertire** [exercism/exercism#6447]
Community Solutions currently default to showing solutions which pass the latest tests.

However, any particular solution has a side panel with "Other" community solutions which do not have the same default.

I am not sure if this is intentional.

**Comment by iHiD** [comment]
@habere-et-dispertire Thanks.
@ErikSchierboom This is probably a low-hanging one that would be useful for people.

**Comment by habere-et-dispertire** [comment]
Wonderful!
*Mille mercis !* :)
