### ISSUE TITLE
Run Tests Error

### ISSUE THREAD

**Issue by schackbrian2012** [exercism/exercism#6448]
I am solving the Robot Name exercise on the Java track. The editor contains a block comment and no code. I clicked the Run Tests button. I got the error message, "An error occurred while running your tests." I tried running the tests again. I also tried logging out and logging in again. Same error. Can you help please?

https://exercism.org/tracks/java/exercises/robot-name

**Comment by glennj** [comment]
The README for that exercise states:

> Since this exercise has difficulty 5 it doesn't come with any starter implementation.

You'll need to start by reading the tests to see what class name is expected.

**Comment by schackbrian2012** [comment]
Dear glennj,

This is not the usual error for referencing an undefined class. Nevertheless, I changed the code in the editor to the following. This defines the class Robot expected by the setUp method of RobotTest. Unfortunately, this did not resolve the error.

```
class Robot {
}
```

Regards,
Brian Schack

**Comment by glennj** [comment]
@exercism/java folks, anyone care to jump in?

**Comment by andrerfcsantos** [comment]
Other people seem to be reporting this. The only change we did that might have caused this was https://github.com/exercism/java-test-runner/pull/50

@ErikSchierboom Do you have any way of confirming that change caused the problem?

Meanwhile, made a PR to revert the change https://github.com/exercism/java-test-runner/pull/52

@glennj Thanks for the heads up!

**Comment by ErikSchierboom** [comment]
@andrerfcsantos I'll look into it!

**Comment by ErikSchierboom** [comment]
Very weird. I'll take a look. It does seem to be track-specific, as other tracks seem to be working fine.

**Comment by ErikSchierboom** [comment]
This is what is in the log:

```shell
[0.008s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.\n#\n# There is insufficient memory for the Java Runtime Environment to continue.\n# Cannot create worker GC thread. Out of system resources.\n# An error report file with more information is saved as:\n# /tmp/solution/hs_err_pid17.log\n
```

CC @iHiD

**Comment by iHiD** [comment]
Could we have changed some dependency that wasn't pinned during build/deploy? So now, even reverting the PR means that some newer version of something is being brought in?

**Comment by ErikSchierboom** [comment]
Possibly. @andrerfcsantos any ideas?

**Comment by andrerfcsantos** [comment]
That can be the issue. Found this: https://github.com/flyway/flyway/issues/3457

If you feel like trying that fix: https://github.com/exercism/java-test-runner/pull/53

**Comment by ErikSchierboom** [comment]
Deploying: https://github.com/exercism/java-test-runner/runs/7468028534?check_suite_focus=true

**Comment by ErikSchierboom** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/135246/180437920-12a750d5-ea6b-4bd5-9e8f-aead0f4d1edc.png)

**Comment by schackbrian2012** [comment]
I originally reported this issue, and your fix worked for me!
