### ISSUE TITLE
CODEOWNERS error?

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#6453]
@ErikSchierboom Seeing this in exercism/awk-test-runner

![image](https://user-images.githubusercontent.com/122470/180878039-98682385-6a75-40a5-a49b-e9e7049b9f11.png)

**Comment by iHiD** [comment]
I've added the team to the repo. Is it fixed now?

**Comment by glennj** [comment]
Yes.

Is something that ought to be validated across all repos?

**Comment by iHiD** [comment]
Yeah, @ErikSchierboom's working on a global script for it that builds on the one we ran week-before-last for the tracks. Currently I have to manually add it everywhere, which is a pain! :)

**Comment by glennj** [comment]
OK, closing this one.

**Comment by iHiD** [comment]
Thanks :)
