### ISSUE TITLE
Loading tracks for self-hosted or local builds

### ISSUE THREAD

**Issue by adamjonas** [exercism/exercism#6455]
I am having trouble finding documentation for a track creator/maintainer to be able to load tracks for a local build of the website. The docs on getting the website up and running locally are clear and straightforward, but I'm not seeing how language tracks from the repos are pulled into the database.

Apologies if I'm missing something obvious!

**Comment by iHiD** [comment]
Hi @adamjonas. Thanks for the issue. Self-hosting isn't something we particularly support or encourage so there's not documentation on it. Why are you wanting to self-host?

**Comment by adamjonas** [comment]
Understood. Thank you @iHiD and thanks for all the work you are doing to make this product and community so spectacular.

**Comment by iHiD** [comment]
Thank you 🙂 

I do think sometime in the future we might choose to support building other communities from Exercism's model (a bit like StackExchange allows new StackOverflow things), but I feel like we need to be very stable before that, so it's a year or two off at the least :)
