### ISSUE TITLE
Keep getting issues Timeout YOUR TESTS TIMED OUT Running Exercism locally 

### ISSUE THREAD

**Issue by ahmadhaidarahmad** [exercism/exercism#6457]
Everything is running properly and as it should but I found that `test_run = SerializeSubmissionTestRun.(submission.test_run)`  is always returning a nil and the any anycable-go result is giving ` WARN 2022-07-29T12:49:52.485Z context=node sid=1AdTSgdvt9tqWTdjCM6Yq Failed to handle incoming message '{"command":"unsubscribe","identifier":"{\"channel\":\"Submission::TestRunsChannel\",\"submission_uuid\":\"d086378fb9c040558789da59e7d2bd08\"}"}' with error: Unknown subscription {"channel":"Submission::TestRunsChannel","submission_uuid":"d086378fb9c040558789da59e7d2bd08"}`

Please check screenshots for the services that are running and for the issue as well, and If anyone can help in explaining how does the test runner work exactly ( it executes the saved S3 file in the console or how exactly and how are they saved in the database) 
Any help would be much appreciated. Thank you.
![Screen Shot 2022-07-29 at 3 53 22 PM](https://user-images.githubusercontent.com/12075928/181765182-30d991cd-cd81-4df3-9476-8e3864815632.png)
![Screen Shot 2022-07-29 at 3 53 08 PM](https://user-images.githubusercontent.com/12075928/181765192-53bf6ab6-5b4c-4115-a015-91a67f23c2e7.png)
![Screen Shot 2022-07-29 at 3 52 38 PM](https://user-images.githubusercontent.com/12075928/181765196-2cf1c00e-3bd4-4742-bf2d-a123eb262f3b.png)
![Screen Shot 2022-07-29 at 3 52 17 PM](https://user-images.githubusercontent.com/12075928/181765197-eceb4f65-9244-463f-8bb3-8a9a96073291.png)

**Comment by ahmadhaidarahmad** [comment]
@kytrinyx  @PatrickMcSweeny

**Comment by SleeplessByte** [comment]
@iHiD @ErikSchierboom you may want to check. Probably hiccup in the system?

@ahmadhaidarahmad I was able to just submit a solution on ruby! Want to give it another go?

**Comment by ahmadhaidarahmad** [comment]
Hi @SleeplessByte Thank you a lot for replying, I tried a lot and still having the same issue FYI I'm working locally, Do you want me to provide any details to see if you can help me ?

**Comment by SleeplessByte** [comment]
Ah. You're trying to run the entire exercism website locally?

I don't think we provide support for that.

**Comment by ahmadhaidarahmad** [comment]
How can I contribute to the code and add new features if I can't run the project locally ?

**Comment by ahmadhaidarahmad** [comment]
@SleeplessByte  If you can't help, can you just explain to me please how does the test run works ?

**Comment by glennj** [comment]
> How can I contribute to the code and add new features if I can't run the project locally ?

This is a conversation you should have 1:1 with @iHiD

**Comment by ahmadhaidarahmad** [comment]
Thank you @glennj  for your reply 😊 @iHiD  when can we have a one to one conversation?

**Comment by SleeplessByte** [comment]
In general, as the web repository states, outside contributions on that code are not accepted (or expected).

However, pick one of the 60 tracks. They all have content, code, tooling that generally does accept contributions!

**Comment by iHiD** [comment]
Yeah, the website doesn't accept PRs, sorry. As DJ says, you're very welcome to contribute to any of the other 300 or so repos though, which nearly all of which accept contributions.

For posterity, to get the test-runners working you'd need to get a tooling-invoker running, a tooling-orchestrator running, and then have whichever tooling repos you want (e.g. ruby-test-runner, ruby-representer, ruby-analyzer) installed via Docker too.

**Comment by ahmadhaidarahmad** [comment]
@iHiD  Thank you a lot for the clarification much appreciated 😊🙏
