### ISSUE TITLE
Recently launched language not appearing in list of languages on bottom of front page

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#6458]
COBOL was launched recently. The 60th language. There are still 59 languages listed at the bottom of the front page. COBOL is not there.
@iHiD  says, 
> The problem is that https://github.com/exercism/website/blob/main/app/helpers/view_components/site_footer.rb#L12 should include Track.active.count in the cache key

![image](https://user-images.githubusercontent.com/209621/181863463-c847a278-a9ff-40a0-91e6-844cdb4204c3.png)

**Comment by ErikSchierboom** [comment]
This has been fixed! COBOL is now shown in the list of languages in the footer.
