### ISSUE TITLE
Create new track for Solidity

### ISSUE THREAD

**Issue by DeFiDruid** [exercism/exercism#6463]

**Comment by kytrinyx** [comment]
There's been work on a Solidity track here:
https://github.com/exercism/solidity

@ErikSchierboom do you know if there's been any recent activity to get this track into shape to be launched?

**Comment by iHiD** [comment]
There's not, and as it's such a different language to other Exercism ones, porting from Problem Specs doesn't really work, so it's a lot of effort to make exercises.

**Comment by ErikSchierboom** [comment]
As @iHiD said: I don't think there was much work being done. Exercises must indeed be crafted manually mostly. It might be possible to use some problem-specifications exercises, but I don't know Solidity well enough to have an educated opinion. If you'd like to help out with a Solidity track, send an email to erik at exercism.org and I'll get you updated.
