### ISSUE TITLE
[Raku] List programming languages in alphabetical order

### ISSUE THREAD

**Issue by habere-et-dispertire** [exercism/exercism#6465]
I occasionally can't find raku on Exercism.

Currently under `https://exercism.org/docs/tracks`, raku follows after its sister language perl 5. If possible, please can this be put into alphabetical order.

I'm guessing the relevant file may be:

exercism > website > app > helpers > view_components > docs_track_list.rb

Thanks.

**Comment by habere-et-dispertire** [comment]
I spotted another one:

https://tracks.exercism.io/

**Comment by iHiD** [comment]
That's probably one for @SleeplessByte

**Comment by SleeplessByte** [comment]
Yes, if https://github.com/exercism/tracks-maintenance-dashboard/blob/main/src/data/tracks.json#L275-L282 is moved down in that file, the order changes! Do you want to contribute that @habere-et-dispertire ?

**Comment by habere-et-dispertire** [comment]
[Done](https://github.com/exercism/tracks-maintenance-dashboard/pull/101). Thanks @SleeplessByte for the pointer! :)

**Comment by SleeplessByte** [comment]
https://github.com/exercism/tracks-maintenance-dashboard/releases/tag/v0.12.0
https://github.com/exercism/tracks-maintenance-dashboard/actions/runs/2785765892

It's being deployed. Cache invalidation is broken at the moment, but this will appear soon.
