### ISSUE TITLE
( Feature request ) Quiz in exercism 

### ISSUE THREAD

**Issue by ashwathirao** [exercism/exercism#6466]
Do exercism has future scope towards having quizzes in some concept based exercise.

Scenario -> After every concept based exercise quiz acts as a factor to enable upcoming exercise!

**Comment by kytrinyx** [comment]
Hi @ashwathirao. We currently don't have any plans to add a feature like this. We believe that once you've done the concept exercise, that is sufficient to unlock the exercises that depend on that concept.

**Comment by ashwathips** [comment]
Thank you for the response!
But I could see an option "mark as complete" for an exercise even though the user hasn't completed the concept (test still fails)

**Comment by ashwathirao** [comment]
Thank you for the response!
But I could see an option "mark as complete" for an exercise even though the user hasn't completed the concept (test still fails)

**Comment by iHiD** [comment]
That's because we cannot be certain the tests fail due to the user's error, rather than infrastructure error. And as Exercism isn't intended for "exam-style" studying, we don't mind if the user wants to continue if they judge it as the correct thing to do.
