### ISSUE TITLE
Add flag --dest to download command

### ISSUE THREAD

**Issue by Gene-94** [exercism/exercism#6467]
Hi, I understand that I can specify my workspace directory but I would like to specify were I download each exercise, it would be far easier for me to mesh different exercises from different sources and have them all grouped by content and not source.  

I think all this would require is to have something like a --dest flag for the download command that would allow me to specify a destiny path for the download. 

I couldn't find anything, readily available, that would allow me to do that, based on a quick search. If there is already such solution I kindly ask to point me in the right way.

**Comment by joshgoebel** [comment]
Is it so hard to just download the exercise and then move it whenever you'd like it to be stored?  I bet you could whip us a tiny Bash script to do what you're wanting in only a few lines of code. 

> for me to mesh different exercises from different sources and have them all grouped by content 

Are you meaning to say you want all the "matrix" exercises in a single tree, or something else entirely?

```
- matrix
 - java
 - javascript
 - ruby
```

Like that?

**Comment by Gene-94** [comment]
I mean, you do have a point, I could move the exercises manually. For me it just made sense to have a flag that allowed me some control over the destiny path.

**Comment by iHiD** [comment]
I think as this might potentially limits future CLIE features that might expect a certain directory structure (e.g. auto updating or submitting), it's probably something we won't do. But a simple bash wrapper might be a nice community addition you could create that others would find useful. We'll be creating a page of such community projects soon so we could list it there :)
