### ISSUE TITLE
[bug] homepage has wrong language count, 59 vs 60 languages

### ISSUE THREAD

**Issue by MenkeTechnologies** [exercism/exercism#6476]
<img width="810" alt="Screen Shot 2022-08-04 at 11 32 09 AM" src="https://user-images.githubusercontent.com/18195247/182887210-85ece451-5b00-449c-867d-1db9b0d13f6b.png">

<img width="895" alt="Screen Shot 2022-08-04 at 11 33 40 AM" src="https://user-images.githubusercontent.com/18195247/182887522-b0c89436-a692-4587-adf5-82bea3dea285.png">

Seems like the language count is not parameterized or parameterized incorrectly

**Comment by glennj** [comment]
There are 60, as shown on the https://exercism.org/tracks page.

The footer is missing new track Cobol, and there are issues tracking that.

**Comment by MenkeTechnologies** [comment]
ok sorry for dup
