### ISSUE TITLE
Exercism does not display on folder

### ISSUE THREAD

**Issue by omzoSamb** [exercism/exercism#6478]
Hi,

I downloaded my first exercism which to display "hello world" but it is not present in the folder.  

In other side, i create a file on the IntelliJ IDE to solve the exercism and i wanted to submit it but the error that i got is "Error: not in workspace". 

- This is the directory where i am : /Users/PapeOmarSAMB/Documents/Exercism/Kotlin/Exercism_HelloWorld/src/main/kotlin
- the exact command, i typed to download the exercism is : exercism download --exercise=hello-world --track=kotlin
-  the exact command i typed to submit the exercism is : exercism submit helloWorld.kt   
and i tried this command too to submit : Exercism submit helloWorld.kt

Can you help me to fix them please ?

**Comment by omzoSamb** [comment]
I fixed now.

**Comment by iHiD** [comment]
Could you tell others how you fixed your problem in case they come across the same issue please? :)
