### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Braden-077** [exercism/exercism#6500]
I think there should be an implementation of dark mode in Exercism! It may be a tough challenge, but I think it could be great for a User Experience and Interface!

**Comment by iHiD** [comment]
Closing as duplicate of https://github.com/exercism/exercism/issues/5436

While I appreciate the issue, please do look for existing issues before opening new ones: https://github.com/exercism/exercism/issues?q=is%3Aissue+is%3Aclosed+dark+mode
