### ISSUE TITLE
Preload tracks

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#6501]
It drives me mad that the tracks on the tracks page load async (via a second request). Let's fix this :)

**Comment by SleeplessByte** [comment]
You'll want to include the initial data on the page as JSON / encoded JSON and then do one of the following:
- `react-query` use placeholder data. This allows you to literally do what it says. It will not be cached, it will still do the second request, but use that as the placeholder until it's done. If any other things on the page use the same cache and cache key, they will _not_ observe the placeholder data.
- `react-query` use initial data (recommended by me). Same as placeholder data, but will be pushed to the cache initially.
- `react-query` prime the cache by using `setData`. 🤷🏽

**Comment by iHiD** [comment]
Thanks @SleeplessByte!

---

I'm closing this as it turns out we already do this, but the page was so slow it looked like it was re-fetching...

@ErikSchierboom @dem4ron You might like to use this info above for https://github.com/exercism/exercism/issues/6505
