### ISSUE TITLE
Export endpoint for testing the representer should return first iterations

### ISSUE THREAD

**Issue by junedev** [exercism/exercism#6511]
I looked at 3 exercises so far. From the 500 solutions I got from the export endpoint, less then 200 compile and pass the tests. That makes the statistics rather "small".

Looking at those numbers, it feels to me the endpoint currently returns first submissions instead of first iterations (the successful ones coming from the CLI). I think it should return first iterations because this is what the representer will run on. Than, failing solutions can happen but should be rare.

(@ErikSchierboom here the issue as discussed)

**Comment by iHiD** [comment]
Yeah, agreed.
