### ISSUE TITLE
Browser navigation breaks content

### ISSUE THREAD

**Issue by adamroyle** [exercism/exercism#6517]
I think this is a new bug from the past few days (I have only been using Exercism for 2 weeks).

When using the browser's page navigation buttons (back/next), the content that should be there is removed.

This occurs on pretty much every page. Here is an example.

https://user-images.githubusercontent.com/25002779/185768013-e98e2a10-62e6-4f02-8f09-fbe6cf3541ed.mp4

**Comment by iHiD** [comment]
Thanks, yes, we deployed some new stuff last week that had the potential to break a bit. I'll take a look on monday. Thanks for the alert :)

**Comment by iHiD** [comment]
This should be fixed now 🙂

**Comment by iHiD** [comment]
@adamroyle Let me know if things are better for you now, and I'll close this if so :)
