### ISSUE TITLE
Creation of pony-test-runner

### ISSUE THREAD

**Issue by redvers** [exercism/exercism#6521]
Title is self-explanatory.

I have a prototype that I am working on… Once I have it working I'm not sure next steps.

Advice please on how to integrate?

**Comment by iHiD** [comment]
@redvers: Here's a repo: https://github.com/exercism/pony-test-runner

> Advice please on how to integrate?

Get it working in a PR, add @ErikSchierboom as a reviewer, he'll review it. Then we'll deploy it and you can test it on the website 🙂 

---

(cc @ErikSchierboom to set the correct branch protections)
