### ISSUE TITLE
"/solutions" view is always visible

### ISSUE THREAD

**Issue by rajaboja** [exercism/exercism#6525]
For a given exercise if the 'user' has not solved/completed it the "Community Solutions" tab is locked and cannot be accessed by clicking on it. But if you append it's path (`/solutions`) to the exercise overview's URL you can still access it. The `/mentor_discussions`  view, which is designed similarly, cannot just be accessed if you haven't solved the exercise by going to it's path.

Is it designed to be this way or a bug?

**Comment by glennj** [comment]
It's a design decision. There are several duplicate issues on this exact topic.

If the student wants to use community solutions as a learning resource, that's great.
If the student wants to "cheat", well that's on them.

**Comment by rajaboja** [comment]
I see the point now.
Sorry for the repetition, I might have missed the duplicates while searching if they already existed.

Thanks!
