### ISSUE TITLE
Weird GUI error

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#6531]
After loading the Python exercise page I had the image for Diamond got stuck to my mouse somehow. I only got rid of it by refreshing the page.

![info](https://user-images.githubusercontent.com/32035397/187553288-65316098-b606-4527-972e-08d330a3dce1.JPG)

**Comment by glennj** [comment]
Perhaps, because you're such a **valuable** contributor, you get extra jewels

**Comment by iHiD** [comment]
Fun! No idea! Sounds like a bug in popper (the tooltip library) or our implementation of it. I'll leave this open to see if anyone else reports the same :)

**Comment by iHiD** [comment]
OK, cool. It's probably something to do with the changes we did with Turbo recently (which sped things up). I'll see if I can consistently replicate somehow.

**Comment by bobahop** [comment]
I can reproduce this problem at will.

Be in Queue.
Click on Workspace and immediately move mouse over a blurb.
Workspace loads and the blurb is stuck to the mouse.

**Comment by glennj** [comment]
I can reproduce using Vivaldi browser (which uses Chromium) but not Safari.

@bobahop what's your browser?

**Comment by bobahop** [comment]
Using Chrome
