### ISSUE TITLE
repo topics: missing for some test runner repos

### ISSUE THREAD

**Issue by ee7** [exercism/exercism#6533]
It looks like the newer test runner repos are missing the topics of `exercism-test-runner` and `exercism-tooling`.

```shell
gh repo list exercism --limit 300 --no-archived --visibility public \
    --json name,repositoryTopics \
    --jq '.[] | select(.name | contains("runner")) | select(.repositoryTopics == null) | .name' \
    | sort
```

```text
awk-test-runner
cobol-test-runner
pony-test-runner
unison-test-runner
```

Questions:
1. Can we add both topics to all those repos?
1. Should we add the topics when a test-runner repo is created, or when a test runner is fully launched, or some other time?
1. Can we automate the answer to question 2, or add it to some checklist?
1. Are there any GitHub repo settings that are both important and unautomated/"fragile", such that it'd be worthwhile to run some similar `gh` commands periodically?

I've forgotten exactly how these topics are used, but IIRC at least @exercism-bot uses them to target repos from `exercism/org-wide-files`.

---

Update 2023-01-17: output is currently just:

```text
vlang-test-runner
```

**Comment by iHiD** [comment]
@ErikSchierboom Can you check and close this pls?
