### ISSUE TITLE
Error: not in workspace when running Exercism submit ...

### ISSUE THREAD

**Issue by cooperd1958** [exercism/exercism#6534]
When I run: PS C:\CooperDell\OneDrive\Cooper_Data\Documents\Coding\Learning\Exercism\python\little-sisters-vocab> Exercism submit strings.py
from VS Code terminal.

I get:  Error: not in workspace

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\coope
Workspace: C:\Users\coope\Exercism
Config:    C:\Users\coope\AppData\Roaming\exercism
API key:   a2c0*****************************4e7

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 39.9077ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 870.6581ms

**Comment by glennj** [comment]
Notice this in the Configuration section of the troubleshooting:

> Workspace: C:\Users\coope\Exercism

But you're implementing the exercises in

> C:\CooperDell\OneDrive\Cooper_Data\Documents\Coding\Learning\Exercism

You can do:
```sh
exercism configure --workspace C:\CooperDell\OneDrive\Cooper_Data\Documents\Coding\Learning\Exercism
```
and try submitting again.

**Comment by cooperd1958** [comment]
Problem solved. Thanks.
________________________________
