### ISSUE TITLE
Iteration is stuck in "Processing" status

### ISSUE THREAD

**Issue by snezhanata** [exercism/exercism#6536]
Hello
https://exercism.org/tracks/python/exercises/hello-world/iterations?idx=1 is stuck in "Processing" status

**Comment by iHiD** [comment]
Hello. Sorry for this. This is almost certainly linked to https://twitter.com/exercism_io/status/1565334548636139523 - it should have fixed itself after about an hour. Could you confirm pls?

**Comment by snezhanata** [comment]
Hi Jeremy,
it is working fine now
Thank you!

Snezhana

пт, 2 сент. 2022 г. в 18:26, Jeremy Walker ***@***.***>:
