### ISSUE TITLE
Create new track for Front End Web Development (HTML, CSS)

### ISSUE THREAD

**Issue by ghost** [exercism/exercism#6538]
I believe in the power of what open source can achieve and that is why I want propose to add a new language to Exercism for Front End Developers which can include HTML, CSS and related topics.

Really hope this vision turns into a reality, so that existing and budding frontend developers alike could benefit from Exercism.

Regards,
Devansh Rawat

**Comment by kytrinyx** [comment]
@ghost Thank you for the suggestion.

At the moment this is out of scope for Exercism.
While we may consider expanding Exercism's scope in the future, we're not adding this to the roadmap at this time.
