### ISSUE TITLE
Consider removing empty “Learn More” section in concept pages

### ISSUE THREAD

**Issue by emtes** [exercism/exercism#6539]
Hello,

If a concept page has no external links to show under the “Learn More” section, seeing the empty section header can be confusing. It was for me, at least. I thought it was maybe a broken link or button to additional information.

If this isn't intentional and worth fixing, I think the code for this is [here](https://github.com/exercism/website/blob/f0e655912cfe93d0c526998d47dfff8051956a8d/app/views/tracks/concepts/show.html.haml#L58), and the `if` statement could be moved up.

<img width="853" alt="Screen Shot 2022-09-04 at 3 30 48 AM" src="https://user-images.githubusercontent.com/54204155/188302881-b54eefa4-9da1-4243-86cf-4ae321099bbf.png">

**Comment by iHiD** [comment]
Thanks @emtes. @dem4ron will fix this one next week :)
