### ISSUE TITLE
python mentor queue is zero for all exercises

### ISSUE THREAD

**Issue by brocla** [exercism/exercism#6545]
The python mentoring queue is empty. That seems unlikely. 

Is there someway to reset the queue? or give it a nudge?

![image](https://user-images.githubusercontent.com/8603050/190839862-f4321be8-30b7-43c6-a242-c77ac70977ec.png)

**Comment by glennj** [comment]
Congratulations to the hardworking python mentors for clearing the queue!

**Comment by iHiD** [comment]
It's not a bug - the queue is just empty 🙂
