### ISSUE TITLE
Representer feedback

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#6547]
## Unsorted Feedback

- After submitting the "Feedback Submitted' tab isn't refetched/updated until refreshed manually sometimes
- Search / track doesn't retain when going back / forth. Workaround: open each in a new tab
- Preview doesn't highlight the code, and isn't scrollable (top/bottom)
- Not being able to see the analysis (analyzer) is problematic because it will lead to double feedback
- Not being able to see the mapping means I cannot refer to variable names
- NTH: being able to see the actual representation 
- As a tool maintainer, how can I check which submissions cause my tools to return errors? I am pretty sure the Elixir representer might be crashing on some corner cases, but don’t have an easy way of verifying that assumption.
Not being able to see analyzer === double feedback
Pagination will become issue as you only want feedback on concept exercises right now. You notice it quite soon.

## More details required (by iHiD)

I can't reproduce these things: 
- pagination seems to be offset/limit; gets incredibly slow for higher page numbers
- Number of requests doesn't go down when representations have been provided. I think it will give endorphins if it did. _(Potentially the caching bug below? Or the fact more representations are added at a faster rate than cleared?)_

### List view changes
- [ ] **https://github.com/exercism/exercism/issues/6554**
- [ ] Aron to work with DJ on how to persist search/track in the most optimal way..
- [ ] Fix bug that number of requests doesn't go down when representations have been provided.

### Individual representation view changes
- [ ] Make it clear that if an exercise is "as good as it can be", positive feedback should be given.
- [ ] Add variable interpolation
  - [ ] Add use of variable interpolation in feedback.
  - [ ] Show variable mapping.
  - [ ] Add a note about not using variable names in the text.
- [ ] Show representation behind button.
- [ ] **Show analysis given to solution (@dem4ron / @erikschierboom)**
- [x] **Fix this caching bug: https://www.loom.com/share/f50400a550484b2889693b911cdee80b?from_recorder=1&focus_title=1**
- [x] **Add syntax highlighting + scrolling on Preview.** (@dem4ron)

### Maintainer-facing changes
- [ ] Give maintainers access to explore all solutions

**Comment by dem4ron** [comment]
For persisting track/search filter is calling `histroy.back()` too naive?

**Comment by iHiD** [comment]
> Is calling history.back() on X click too naive?

Yes. I don't believe the URL needs fixing as much as the page needs to check it's initial localstorage state once it loads. But ping DJ on Slack and he'll tell you the pattern he uses :)

**Comment by SleeplessByte** [comment]
I don't know how the current UI works, but basically you want the _url_ to be the _single source of truth_. So changing the dropdown / typing something / whatevs should *update the url* and then components should react to that. That way, you don't need to do any state syncing on back clicks, because clicking back will restore the URL!

**Comment by dem4ron** [comment]
@SleeplessByte Yes, the URL updates as filters update, that's why I thought it would be enough to just go back on clicking the X.

**Comment by SleeplessByte** [comment]
It should be. When its not, it means that the elements that use the state are not using the url state as ground truth 😁

**Comment by dem4ron** [comment]
Then would you say it's fine to use `history.back()`?

**Comment by dem4ron** [comment]
yeah, I tried it out before I proposed the idea. :)

**Comment by SleeplessByte** [comment]
I think I have an example of this in my hiring-example repository, where I fetch the url state / query param on mount, and use that to "hydrate" the query.

**Comment by verdammelt** [comment]
Just a +1 on seeing the representation. My track's representer returns the errors encountered for syntactically invalid submissions so seeing *which* error was hit will help when writing the feedback.

(Also it will help me see how well the representer is working - so a secondary benefit to me from seeing the output)
