### ISSUE TITLE
A completed concept exercise does not link to the concept

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#6548]
Or perhaps the link is just too hard to find (for me)

This snapshot from my Elixir Lasagna overview page:
![image](https://user-images.githubusercontent.com/122470/191137671-e7ed97bf-d7fc-439c-8b3d-98346fcaf703.png)
The "[BA] Basics" label should link to /tracks/elixir/concepts/basics

**Comment by iHiD** [comment]
Welcome to @SleeplessByte's biggest bugbear :D

**Comment by iHiD** [comment]
@dem4ron Fixing this would be a nice one for you to learn this bit of the codebase a little (the first one should be a link)
