### ISSUE TITLE
add c3lang in exercism

### ISSUE THREAD

**Issue by codehangen** [exercism/exercism#6550]
Hi all.

I would like to add exercises from the [c3](https://github.com/c3lang/c3c) programming language, which is based on C in exercism. *How can I do this? How can I create a repository and keep it here? Can someone help me?*

**Comment by kytrinyx** [comment]
For requesting new languages, please open an issue in the https://github.com/exercism/request-new-language-track repository.

(I'm not transferring the issue, because there's an issue template that we need you to fill out there)

Thanks!
