### ISSUE TITLE
SSL server cert has expired

### ISSUE THREAD

**Issue by yeochinyi** [exercism/exercism#6556]
Exercism:                                                                                │~
    * https://api.exercism.io/v1/ping                                                    │~
    * [Get &#34;https://api.exercism.io/v1/ping&#34;: x509: certificate has expired or is│~
 not yet valid: current time 2022-09-27T08:10:20&#43;08:00 is after 2022-09-26T23:59:59Z]│~
    * 33.568167ms

**Comment by EQt** [comment]
I have similar problems when I use the cli `exercism` tool.

**Comment by iHiD** [comment]
Thanks. This should now be resolved.
