### ISSUE TITLE
Concept exercises are visible even when the syllabus is hidden

### ISSUE THREAD

**Issue by MatthijsBlom** [exercism/exercism#6559]
Currently on the Haskell track the work-in-progress concept exercises and concept pages are available to students, even though the syllabus itself is still hidden. In [exercism\haskell#1109](https://github.com/exercism/haskell/pull/1109#issuecomment-1260547963) @ErikSchierboom suggests this might be a bug.

**Comment by MatthijsBlom** [comment]
@ErikSchierboom What would be the preferred short-term course of action here? Work around this issue by marking all concept exercises as unavailable? Leave them as they are?

**Comment by ErikSchierboom** [comment]
@MatthijsBlom You could mark them as `wip` which would hide them, but that would mean students that previously started them won't see them. So probably wait until I've fixed this? Hopefully next week, sorry.

**Comment by MatthijsBlom** [comment]
> [hiding them] would mean students that previously started them won't see them.

Not hiding them now would mean that even more students that (will have) started them will not see them.

Not too unlikely that concept exercises will be changed or even scrapped before the syllabus goes up.

**Comment by ErikSchierboom** [comment]
Yes, but I'm worried that things would break for these students. I think the CLI commands would start failing e.g. I'll try and fix this early next week.

**Comment by ErikSchierboom** [comment]
@MatthijsBlom Just so you know: I _am_ working on this, it's just slightly tricky.
