### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by rexbutler** [exercism/exercism#6564]
The password reset is not working for my email address rexbutler@gmail.com.  When I am sent to https://exercism.org/users/password/new, enter my email address (rexbutler@gmail.com), and click "Send instructions" it states "You will receive an email with instructions on how to reset your password in a few minutes." however no email arrives.

Note:  I've checked my spam folder, no email has arrived after multiple attempts.

**Comment by iHiD** [comment]
Hi. In Oct 2020 you marked our emails as spam, which meant you were automatically added to a supression list by our mail provider and so now they block all email sending attempts.

I've manually removed you from the supression list and you should now be able to request a new password.
