### ISSUE TITLE
How to use the Teams Edition?

### ISSUE THREAD

**Issue by padauer** [exercism/exercism#6566]
Hello,

In the [docs](https://exercism.org/docs/using/editions/teams) there is a Teams Edition listed with the note that you will announce this early 2022.
How can we use this feature?

Thank you in advance!

**Comment by kotp** [comment]
While this is on the roadmap, it seems that we have missed the "Early 2022". However, currently, the closest thing to "team" functionality is being able to request a private mentor, obtaining a link, and sending it to the person we would want to have mentor.

@iHiD can talk more about where this is, on the horizon, though.  And maybe get this [page updated].

[page updated]: https://github.com/exercism/docs/blob/main/using/editions/teams.md

**Comment by cowlike** [comment]
> @iHiD can talk more about where this is, on the horizon, though. And maybe get this [page updated](https://github.com/exercism/docs/blob/main/using/editions/teams.md).

I recently had someone ask me how to access the teams edition and I told them it looks like the date slipped, based on the above page. Since that is the public statement about Team Edition, someone really should go make it a little less specific regarding delivery. Sure, dates slip all the time and I'm fine with that but this seems like a very simple change to get rid of the specificity.

**Comment by iHiD** [comment]
Thanks. I've updated it to late 2022. At some point soon we'll be putting up a pre-registration page where people can help tell us exactly what features they'd like to see. We'll be launching this at some point in 2023 - the features we decide will determine the exact date :)

**Comment by kotp** [comment]
Was it changed elsewhere?  Or was it that it was not updated on that line, and only referenced later as "announcement coming late 2022"?

**Comment by cowlike** [comment]
I just sent a trivial [PR](https://github.com/exercism/docs/pull/401) to fix this confusion.
