### ISSUE TITLE
Translation exercise test error

### ISSUE THREAD

**Issue by madzi-hove** [exercism/exercism#6568]
Hi. I am working on the javascript track and am currently doing the translation exercise. I am using the online editor and receiving this error when ever i try to run tests We received the following error when we ran your code:

● Test suite failed to run

Cannot find module 'core-js/modules/es.array.push.js' from '../..<solution>/api.js'

Require stack:
  <solution>/api.js
  <solution>/service.spec.js

![Screenshot (6)](https://user-images.githubusercontent.com/82516667/193524367-a42903f9-105a-4783-9225-614cf2266c98.png)

I have refreshed the page, flushed the browser cache,reverted the exercise to start and still this keeps appearing. Any help will be greatly appreciated.

I have also noticed that all my exercises are unlocked even though I am in learning mode.

**Comment by SleeplessByte** [comment]
Same as https://github.com/exercism/javascript/issues/1932
