### ISSUE TITLE
Cannot find module 'core-js/modules/es.array.push.js' from '../..<solution>/enchantments.js'

### ISSUE THREAD

**Issue by sreejithliterally** [exercism/exercism#6569]
We received the following error when we ran your code:
  ● Test suite failed to run

    Cannot find module 'core-js/modules/es.array.push.js' from '../..<solution>/enchantments.js'

    Require stack:
      <solution>/enchantments.js
      <solution>/enchantments.spec.js

**Comment by SleeplessByte** [comment]
Same as https://github.com/exercism/javascript/issues/1932
