### ISSUE TITLE
Error when running website locally

### ISSUE THREAD

**Issue by Y-CAT** [exercism/exercism#6574]
Validation failed: Track must exist
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/validations.rb:53:in `save!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/transactions.rb:302:in `block in save!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/transactions.rb:302:in `save!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/suppressor.rb:54:in `save!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/persistence.rb:55:in `create!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:869:in `_create!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:115:in `block in create!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:880:in `_scoping'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:428:in `scoping'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:115:in `create!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:219:in `block in create_or_find_by!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/home/op/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/op/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/op/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/op/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/transactions.rb:209:in `transaction'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation/delegation.rb:108:in `public_send'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation/delegation.rb:108:in `block in method_missing'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:880:in `_scoping'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:428:in `scoping'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation/delegation.rb:108:in `method_missing'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:219:in `create_or_find_by!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/querying.rb:22:in `create_or_find_by!'
/home/op/softwares/exercism/web/website-main/config/initializers/active_record.rb:9:in `rescue in find_create_or_find_by!'
/home/op/softwares/exercism/web/website-main/config/initializers/active_record.rb:6:in `find_create_or_find_by!'
/home/op/softwares/exercism/web/website-main/db/migrate/20220720075556_add_cohort_to_cohort_memberships.rb:7:in `change'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:869:in `exec_migration'

Caused by:
ActiveRecord::RecordNotFound: Couldn't find Cohort with [WHERE `cohorts`.`slug` = ?]
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation/finder_methods.rb:378:in `raise_record_not_found_exception!'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/core.rb:330:in `find_by!'
/home/op/softwares/exercism/web/website-main/config/initializers/active_record.rb:7:in `find_create_or_find_by!'
/home/op/softwares/exercism/web/website-main/db/migrate/20220720075556_add_cohort_to_cohort_memberships.rb:7:in `change'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:869:in `exec_migration'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:853:in `block (2 levels) in migrate'
/home/op/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:852:in `block in migrate'

**Comment by Y-CAT** [comment]
error is reported when running the command  "RAILS_ENV=development rake db:migrate"
error code is in db/migrate/20220720075556_add_cohort_to_cohort_memberships.rb:'
The reason for the error is that there is no data in the track table

**Comment by Y-CAT** [comment]
exercism-website  main

**Comment by kytrinyx** [comment]
I see. I thought you were trying to submit to a track on https://exercism.org/ and getting that error message from the command-line client.

What are you trying to do?

It's worth noting that the website repository is treated as an internal repo. That means the source code is public, but we do not accept Pull Requests and we do not officially support the app being run locally.

**Comment by kytrinyx** [comment]
As it's been over a month with no response, I'm going to go ahead and close this.
