### ISSUE TITLE
bqn-test-runner

### ISSUE THREAD

**Issue by m3m0ry** [exercism/exercism#6575]
Hello there,

we are in the process to create the [BQN track](https://github.com/exercism/bqn).
We would like to create a test runner as well.

BR,
Jan

**Comment by kytrinyx** [comment]
@ErikSchierboom Are you the best one to help out with this? Are there any other folks who have enough experience with doing it themselves to provide input as well?

**Comment by ErikSchierboom** [comment]
@kytrinyx I think this issue is about creating the test runner repository based on the BQN issues I read. And yes: if there are issues/questions, I'm probably the your best guess

**Comment by m3m0ry** [comment]
Oh yeah, sorry, really dump from me not to be specific. Yes, we just need the repository. Preferably under the bqn team: https://github.com/orgs/exercism/teams/bqn/repositories

**Comment by kytrinyx** [comment]
@m3m0ry no problem at all, I can very much relate!

**Comment by m3m0ry** [comment]
I don't think the repository was created yet. Could you open for us a `bqn-test-runner` repository?

**Comment by iHiD** [comment]
@m3m0ry Done. 

---

@kytrinyx for reference I do this through the UI, basing it off the `generic-test-runner` template (you get the option when creating the repo). And then I add the track team (`bqn` in this case) with write and maintainers with maintain privileges.

@ErikSchierboom Do we then have something that sets up branch protections etc?

**Comment by m3m0ry** [comment]
Ah and if I would read even more documentation, I would know to create first a repo from the template myself, implement it and then create an issue to MOVE the repo to exercise. Sorry for the overhead here.

**Comment by kytrinyx** [comment]
@m3m0ry it's no overhead. It's up to us to reduce the mental burden for you by creating good enough docs and guides (we are constantly trying to improve these; it's a lifelong battle, I suspect). We're the ones who know how it all fits together—please always ask questions!

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom Do we then have something that sets up branch protections etc?

An open PR: https://github.com/exercism/website/pull/2782 :)
