### ISSUE TITLE
I'm frustrated -- please help

### ISSUE THREAD

**Issue by larssec** [exercism/exercism#6576]
There is no way to provide feedback, just bugs.  I was excited to try exercise but found it useless as there is no way to see what exercises are actually trying to teach.  When I get stuck I can can only reach out to mentors, but there is no way to help myself?

**Comment by kytrinyx** [comment]
Hello @larssec,

There are a few different questions that you seem to be asking and I will try to answer each of them.

> Is there a place to provide feedback rather than just report bugs?

You've come to the right place! If you have feedback, please feel free to open an issue in this repository.

> How do you know what exercises are trying to teach?

This is a really good question, and the answer is actually a bit bigger than you might have anticipated.

A fully developed language track on Exercism will have both Learning Mode and Practice Mode.

Learning Mode has a syllabus where each exercise teaches one (or sometimes two) concepts. It's very clear in this case which concept an exercise is teaching, and the concepts are explained directly.

Practice Mode does not have a syllabus, and exercises are intended to be a place to experiment with the language. There will often be several ways that you can approach the exercise.

When a track is first launched on Exercism we usually only have Practice Mode. There are a number of good reasons for this, but it means that getting started in these tracks can be a little bit bewildering (as you have pointed out) as there's nothing really telling you what to do, and so you might find that you're flailing around a bit trying to get your bearings.

We apologize for the frustration, and we hope to get a proper syllabus in place for all of our tracks. Tracks are built by volunteers, and we aim to focus on recruiting volunteers to help flesh out tracks as part of our near-term roadmap.

> What can I do to get help when I am stuck, beyond asking a mentor for help?

We're in the process of putting something in place for this right now. Hopefully we'll have something more for you in the next couple of weeks. In the meanwhile, please do feel free to reach out to a mentor, and we will try to help you get past the hurdle.

Out of curiosity, what language are you trying to learn?

**Comment by kytrinyx** [comment]
Since it has been three weeks and we've not heard back from the original author, I'm going to go ahead and close this.

@larssec If you wish to discuss further, would you please post in the Exercism community forum? https://forum.exercism.org/
