### ISSUE TITLE
I want to run the platform locally but I get this error

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [exercism/exercism#6577]
ws       | WebSocket server at http://local.exercism.io:3334 stopped: listen tcp: lookup local.exercism.io: no such host

**Comment by SleeplessByte** [comment]
Hi @FranciscoImanolSuarez. Self-hosting isn't something we particularly support or encourage so there's not documentation on it. Why are you wanting to self-host?

**Comment by kytrinyx** [comment]
As it's been a month with no response, I'm going to go ahead and close this.
