### ISSUE TITLE
Feature request: Make external links open in a new tab

### ISSUE THREAD

**Issue by Bharath314** [exercism/exercism#6580]
It would be great if external links like the [ones here](https://exercism.org/tracks/javascript/concepts/increment-decrement) opened in a new tab automatically. It would be less distracting to the learning flow.

**Comment by iHiD** [comment]
Thanks.

I always find this a controversial topic. Some people hate it when the website decides that for them, others find it helpful as you suggest. I'll ask around and see if we can get a consensus 🙂

**Comment by SleeplessByte** [comment]
IMO the definitive [read on this](https://adrianroselli.com/2020/02/link-targets-and-3-2-5.html).

If we decide that the links on articles that _are_ external open in a new window (whereas I think we really shouldn't), then _any_ place that uses that icon you currently use _must_ become a link that opens in a new window.
