### ISSUE TITLE
Exercises activity remains un-updated unless page is refreshed

### ISSUE THREAD

**Issue by vishalxk** [exercism/exercism#6583]
Hi, first time opening an issue here. When working through the exercises, I noticed that the exercises page seems to get stuck and get out of sync by not updating the _Completed_, _In Progress_, ... tabs until refreshed. Images attached below for reference.

### Complete exercise and submit
<img width="1512" alt="Screen Shot 2022-10-14 at 14 31 08" src="https://user-images.githubusercontent.com/84175901/195809861-54379dbb-b422-4fa3-80e9-45ca6a4837e1.png">

### Exercises page stuck and out of sync (i.e., exercises _completed_ should be 20 and so on...)
<img width="1512" alt="Screen Shot 2022-10-14 at 14 31 40" src="https://user-images.githubusercontent.com/84175901/195810423-7375520b-76f3-4ffb-835e-eeb17b1fb8ed.png">

### Exercises page back in sync after refresh
<img width="1512" alt="Screen Shot 2022-10-14 at 14 31 51" src="https://user-images.githubusercontent.com/84175901/195810514-495d336f-3d48-4524-953b-229b7772f655.png">

Let me know if there is anything else I can do to help!

**Comment by glennj** [comment]
side note: the number of tabs in your browser makes me anxious.

**Comment by iHiD** [comment]
Thanks! (cc @dem4ron)

**Comment by dem4ron** [comment]
Hey @vishalxk , thanks for spotting this bug!

I highly recommend using tab groups on Chrome, it has made my life easier and cleaner :)

**Comment by vishalxk** [comment]
Hi @dem4ron, I see that you fixed the bug! Also, thanks for recommending tab groups. I can see that the tab situation is quickly going out of control.
