### ISSUE TITLE
How to open Exercise in Visual Studio

### ISSUE THREAD

**Issue by jackiebgregory** [exercism/exercism#6584]
Hello, I followed the directions to install the CLI and I downloaded the first exercise (in the C# track). How do I open the exercise in Visual Studio?

**Comment by BNAndras** [comment]
Hi Jackie,
In Visual Studio, browse to the folder where the CLI downloaded the exercise. There should be a .csproj file present with the name of the exercise. Open that file to load the exercise.

**Comment by SleeplessByte** [comment]
Could you also tell us if you're on a Windows, Mac, or Linux? We can then help you find the location the CLI downloaded the exercise to :)

**Comment by kytrinyx** [comment]
It's been two weeks and we've not heard back from the original author. I'm going to go ahead and close this.

@jackiebgregory if you still need help, will you please post in the Exercism community forum? https://forum.exercism.org/c/programming/80-category/80
