### ISSUE TITLE
Mentoring before getting tests to pass?

### ISSUE THREAD

**Issue by jtlapp** [exercism/exercism#6586]
I have been unable to get an exercise to work. Is it possible to get mentoring assistance before tests pass? The submit button seems to remain disabled until tests pass.

Or should I look for help from someone outside of the exercism community?

**Comment by iHiD** [comment]
Hello. You should look for help from the community. Next week (or maybe even this week!) we'll be launching our new community forum for exactly this sort of purpose.

**Comment by jtlapp** [comment]
Awesome. Thank you! I'll keep an eye out for a change. Meanwhile, I'll move on to other exercises.
