### ISSUE TITLE
Is the track exercises page counting students differently?

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#6590]
The Wren overview page: 
![image](https://user-images.githubusercontent.com/122470/196775988-a589af72-e528-491d-93a4-dd51a4388f81.png)

The Wren exercises page: 
![image](https://user-images.githubusercontent.com/122470/196775959-f02a414c-a63b-4411-b0b6-fa68bac9d7b7.png)

Where is the discrepancy?

**Comment by glennj** [comment]
https://twitter.com/codinghorror/status/506010907021828096?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E506010907021828096%7Ctwgr%5E23991ff1eaa6dcdcbd26ba3ebe59c2c50d7581e3%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fblog.frankel.ch%2Fhard-things-computer-science%2F

**Comment by iHiD** [comment]
The heading is cached per page the first time it is seen each day. So I guess there was an extra user between the two!

**Comment by glennj** [comment]
However, I did observe the same effect for about 5 or 6 different tracks. I think it could use a look.

**Comment by glennj** [comment]
Hmm, it seems that the tracks I looked at yesterday had all lost one student each during the day.

**Comment by iHiD** [comment]
Interesting. Maybe a bot that joined everything then deleted its account (we get all sorts of weird shit!)
