### ISSUE TITLE
[Tracking] Update fetch-configlet scripts across all tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#6591]
I'm opening pull requests across all the track repositories.

This issue allows us to easily see the state of these pull requests.

**Comment by kerolloz** [comment]
@kytrinyx 
Currently, the remaining open PRs have failing checks.

**Comment by kytrinyx** [comment]
@kerolloz Thank you so much for going through and doing that.
@ErikSchierboom for the failing ones, should we admin-merge provided that `main` is failing in the repo?

**Comment by kytrinyx** [comment]
The remaining scripts can be merged if someone decides to dig into the tracks in questions.
