### ISSUE TITLE
[feature request] flair for display on external websites

### ISSUE THREAD

**Issue by jtmoon79** [exercism/exercism#6592]
## Problem

I want to show off my progress on exercism.org from my github profile page. I can URL link my exercism user badges page https://exercism.org/profiles/jtmoon101/badges . But this is visually uninteresting, and requires the viewer to click the link.

## Solution

Allow exercism "flair" for displaying a little graphic communicating progress at exercism.

### Stackoverflow example

The stackoverflow flair is embeddable in many places, including `README.md` files, which become automatically rendered by github.

Stackoverflow provides a little HTML code snippet too make image embedding easy
```html
<a href="https://stackexchange.com/users/216253/jamesthomasmoon">
<img src="https://stackexchange.com/users/flair/216253.png" 
  width="208" height="58"
  alt="profile for JamesThomasMoon on Stack Exchange, a network of free, community-driven Q&amp;A sites"
  title="profile for JamesThomasMoon on Stack Exchange, a network of free, community-driven Q&amp;A sites"
/>
</a>
```

Checkout my stackoverflow flair https://stackexchange.com/users/216253/jamesthomasmoon?tab=flair
![SO-flair-20221020](https://user-images.githubusercontent.com/815261/197064830-02ca7161-0e8b-40a0-aa37-b6646a0b2af6.png)
It shows my profile pic, username, and my Stackoverflow awards in one graphic.  I've added it to my own github personal page. https://github.com/jtmoon79/#stackexchange
I also add it to the bottom of the primary `README.md` for my projects, for example https://github.com/jtmoon79/super-speedy-syslog-searcher#further-reading
It's like a little business card of Stackoverflow accomplishments.

### exercism

It'd be cool if excercism offered something similar.  A little infographic expressing badges collected, tracks completed, overall reputation, etc.

**Comment by iHiD** [comment]
Hey. I like this idea. Maybe you could open this on our new forum so other can discuss what the Flair would contain? forum.exercism.org :)

**Comment by jtmoon79** [comment]
@iHiD good suggestion!
Posted at https://forum.exercism.org/t/feature-request-flair-for-display-on-external-websites/463

Go ahead and close this Issue as you see fit.

**Comment by SleeplessByte** [comment]
Closed in favour of the forum post
