### ISSUE TITLE
I tried to debug with console.log() and I can't

### ISSUE THREAD

**Issue by Guayamarinei** [exercism/exercism#6593]
I'm just starting with exercism.
I'm trying to debug an exercise with console.log() and I can't find where the messages go.
I thought that the message was showed in the Test results info or in the Developer tools' Console but I can't find them.
I tried the same exercise in Mozilla and Chrome but nothing is to see.
I'm using the Exercism web editor.
One think that caught my attention is that 'console' or 'log' or just a text inside isn't highlighted whithin the code.
I know that this must be a noob issue but I can't find something about it in the FAQ or in the issues search.
Thanks

**Comment by SleeplessByte** [comment]
Hi there.

Each language that supports the web editor is supposed to have a debugging section at the bottom of each exercise instructions page, as highlighted in the following screenshot:

![debug section in exercism exercise instructions](https://user-images.githubusercontent.com/1964376/197354239-f4f62c85-0ff9-45b0-ab83-4b2abd4d8f87.png)

It is _absolutely_ possible that the *debug* functionality isn't working for you. In order for us to further investigate, can you let us know which track you are working on? When we know this, we can take appropriate steps to resolve your issue.

**Comment by Guayamarinei** [comment]
Hi.
I was working on 'Freelancer Rates' form the Javascript exercises.
The published solutions doesn't have any console.log() left because I
deleted them before de Submit.

I knew about the 'How to debug' section at the bottom of the 'Instructions'
tab (the one in the image that you send me).
And it's because of that image that I think that something is wrong with
the editor because there is no color highlight when I type 'console.log()'.

At the end I copy and paste the code to Visual Studio and debbuged it in
the browser.

Thanks for the quick reply

**Comment by iHiD** [comment]
We've highlighted this as a fun. We'll have a fix in place soon. Sorry for the inconvenience.

**Comment by SleeplessByte** [comment]
You can subscribe to https://github.com/exercism/javascript/issues/1966 if you want to be kept up to date, but will also post here once it's fixed!

**Comment by SleeplessByte** [comment]
It has now been fixed @Guayamarinei.

**Comment by iHiD** [comment]
Thank you @SleeplessByte !
