### ISSUE TITLE
RSS feeds for mentoring requests

### ISSUE THREAD

**Issue by BNAndras** [exercism/exercism#6594]
[Per an ongoing conversation on Slack about the Mentoring Request Notifier](https://exercism-team.slack.com/archives/C03P0B0TU00/p1666380865051189), we identified that it'd be advantageous for the Exercism website to host individual RSS feeds for each track's mentoring requests. Then, mentors can consume the feeds in whatever way is best for them without depending on push notifications through Slack from the bot. For example, I could use push notifications for less busy tracks and daily digests for busy ones on a case-by-case basis without needing to know the API to create my own solution separate from Mentoring Request Notifier. To be clear, I don't mean to deprecate the Slack bot at all. I just want more flexibility in the notification system that track-specific RSS feeds could provide.

**Comment by iHiD** [comment]
As we're deprecating Slack (in general) anyway in favour of our new forums, I think this makes a lot of sense. Does it matter with RSS feeds that things would be deleted as they're removed from the queue?

**Comment by BNAndras** [comment]
They aren’t being deleted in the current Slack solution so I think it’s fine to not prune the items.

**Comment by iHiD** [comment]
Ah - I meant the other way. We *have* to prune items really as the RSS feed will be generated on the fly, so it'll just show what's in the table at the time the data is requested.

**Comment by cmcaine** [comment]
Deleting items is not in the Atom or RSS standards tho there are extensions. Support is likely very low. But most readers support an item being modified (i.e. for a given item, they will show only the most recent version of the item that they have downloaded from the feed).

Exercism could publish an RSS feed where mentoring requests that have been met recently are rendered in the RSS response as deleted (with the extensions, in case anyone supports them) and are also edited to say that they have been served.

It's not a great solution, but it's fairly low effort and better than nothing. Lots of RSS feeders allow writing filters to exclude items as well, so they could match on the deleted placeholder. Folks could also patch their RSS readers to support deletion.

**Comment by cmcaine** [comment]
RSS has an fh:incremental option you can set to false that may be much better supported than deletion and wouldn't require the exercism server to include old edited responses in the feed.
