### ISSUE TITLE
some remaining mentions of `exercism.io` in repo descriptions

### ISSUE THREAD

**Issue by ee7** [exercism/exercism#6596]
https://github.com/exercism/cli
https://github.com/exercism/Exercism.jl

```shell
gh repo list exercism --no-archived --limit 500 --json description,name \
    --jq '[.[] | select(.description | contains("exercism.io"))]' \
    | jq
```

```json
[
  {
    "description": "A Go based command line tool for exercism.io.",
    "name": "cli"
  },
  {
    "description": "Exercism.jl provides tooling and utility functions to solve exercises on exercism.io in interactive environments such as IJulia notebooks.",
    "name": "Exercism.jl"
  }
]
```

---

Note that [tracks.exercism.io](https://tracks.exercism.io/) is referenced in the homepage on https://github.com/exercism/tracks-maintenance-dashboard. But I believe is what we want for now, because https://tracks.exercism.org/ does not work.

Previously:

- https://github.com/exercism/exercism/issues/6361
- https://github.com/exercism/exercism/issues/6362
- https://github.com/exercism/exercism/issues/6363
- https://github.com/exercism/exercism/issues/6527

**Comment by kytrinyx** [comment]
I've fixed the two mentions above. I re-ran the command and got back an empty array.

Thanks for the heads up, @ee7.
