### ISSUE TITLE
Connecting to API results in connection error

### ISSUE THREAD

**Issue by MenouerBetty** [exercism/exercism#6598]
Heya,

I'm trying to run exercism locally on a linux laptop, however it seems it can't connect to both github and exercism API.
```
Error:
GitHub:
    * https://api.github.com
    * [Get https://api.github.com: dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:42732-&gt;[::1]:53: read: connection refused]
    * 530.59µs

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: dial tcp: lookup api.exercism.io on [::1]:53: read udp [::1]:60289-&gt;[::1]:53: read: connection refused]
    * 300.25µs
```
Tried running it as sudo but that doesn't work either and my internet is working fine.

**Comment by kytrinyx** [comment]
@MenouerBetty Your best bet for getting help is going to be the Support channel in the community forum: https://forum.exercism.org/c/support/8
Would you go ahead and post there?

**Comment by MenouerBetty** [comment]
Sure! @kytrinyx

**Comment by iHiD** [comment]
(For posterity, this has moved to https://forum.exercism.org/t/trouble-connecting-to-exercism-github-api/515)
