### ISSUE TITLE
Gleam test runner

### ISSUE THREAD

**Issue by lpil** [exercism/exercism#6602]
Hello!

I would like to create an Exercism test runner for Gleam. I am the creator of Gleam and have a good understanding of what is required after reading the documentation.

Could you create a repository for it please? The [generic template](https://github.com/exercism/generic-test-runner) or a blank repo would be great 💜 

Thanks,
Louis

**Comment by iHiD** [comment]
https://github.com/exercism/gleam-test-runner

Thanks! Have fun 💙
