### ISSUE TITLE
Cannot complete registration, email not sent

### ISSUE THREAD

**Issue by asfrent** [exercism/exercism#6603]
I have been trying to sign up for 2 days now, the confirmation email never arrives. I tried with @proton.me and @gmail.com addresses, still no luck. I know I can use github login, but I prefer to avoid linking services. Could you please take a look? The service looks awesome and I can't wait to try it out!

**Comment by asfrent** [comment]
Forum is not a good place to report this kind of bug, since you need to be logged in in order to post, thus you need an account, thus you need the registration email to be sent.

**Comment by SleeplessByte** [comment]
@asfrent no worries. That's an auto-response bot. Is your e-mail handle the same as your github username?

Looping in @iHiD.

**Comment by asfrent** [comment]
Hi, no, but the issue seems to be resolved since a few hours ago, I received the email, woohoo!

**Comment by SleeplessByte** [comment]
Great. Rock on 🎸
