### ISSUE TITLE
Create ballerina-test-runner repo

### ISSUE THREAD

**Issue by vordimous** [exercism/exercism#6604]
Hello exercism team,

I have been working on updating the exercism/ballerina track repo to the GA ballerina release `swan-lake`. I didn't find an existing test-runner repo and request one to be created so I can add the necessary docker env for the test cases.

Ballerina is a cloud-native language whose features rely heavily on network communications and data transformation. We may need to install extra development services in the test environment in order to introduce more concepts through exercism. We already have 20 additional exercises with dockerfiles that we could convert to work. What is allowed to run in these test runners besides the base ballerina runtime?

**Comment by vordimous** [comment]
@ErikSchierboom is this re correct way to ask for this repo to be created?

**Comment by ErikSchierboom** [comment]
Yes! @iHiD will create the repo for you once he's had the time to do so

**Comment by ErikSchierboom** [comment]
Created: https://github.com/exercism/ballerina-test-runner/

**Comment by vordimous** [comment]
Awesome thank you! I think I have it working. Ill make a PR.
