### ISSUE TITLE
https://exercism.org/cli-walkthrough typo ?

### ISSUE THREAD

**Issue by iranzo** [exercism/exercism#6605]
Hi,
Page https://exercism.org/cli-walkthrough shows:
![image](https://user-images.githubusercontent.com/312463/200853230-cba99d7a-dc20-4462-9a5c-ae18d48c2f14.png)

Where I think it should say 'processor' or 'CPU'

**Comment by kytrinyx** [comment]
Hiya - you're absolutely right. Thank you!

**Comment by iranzo** [comment]
@kytrinyx if you point me to the repo I can PR this :-)

**Comment by iranzo** [comment]
Fixed in https://github.com/exercism/interactive-cli-walkthrough/pull/123
