### ISSUE TITLE
 Completed and Correct Answer submissison still shows as 'in-progress'

### ISSUE THREAD

**Issue by Earthchild33** [exercism/exercism#6607]
After completing a bash exercise (Reverse String), I noticed on my activity track that it was still showing as 'in progress' even though I've submitted my solution and it passed. I also noticed compared to the other completed exercises that had been submitted it also says published whereas the Reverse String just only says submitted. I was wondering how I could to fix this issue.

**Comment by iHiD** [comment]
Posted in the forum: https://forum.exercism.org/t/completed-and-correct-answer-submissison-still-shows-as-in-progress/776/3
