### ISSUE TITLE
Missing Haskell characteristics when filtering Tracks.

### ISSUE THREAD

**Issue by gacallea** [exercism/exercism#6610]
Hi :)

when filtering tracks with either of [these characteristics](https://exercism.org/tracks?page=1&tags%5B%5D=paradigm%2Ffunctional&tags%5B%5D=typing%2Fstatic&tags%5B%5D=typing%2Fstrong&tags%5B%5D=execution_mode%2Fcompiled&tags%5B%5D=platform%2Fwindows&tags%5B%5D=platform%2Fmac&tags%5B%5D=platform%2Flinux), Haskell doesn't show up. However, it really should show up. Since it is a (purely) functional language with a strong, static type system. Same thing goes for platforms, it doesn't show up when filtering by Windows, macOS, and/or Linux.

Cheers and thank you for Exercism :)

**Comment by kytrinyx** [comment]
Hiya!
These are the tags that the Haskell track is marked with at the moment...
https://github.com/exercism/haskell/blob/main/config.json#L1322-L1324
Perhaps a bit sparse :-)

**Comment by SleeplessByte** [comment]
The task that was supposed to define the tags was [incorrectly closed](https://github.com/exercism/haskell/issues/939#issuecomment-1312531221). Tags are not yet defined for Haskell which, once defined, should resolve this issue.

**Comment by gacallea** [comment]
Hi :)I’d gladly contribute a PR if welcome, as soon as I get back home.Cheers Sent from Proton Mail for iOS On Sat, Nov 12, 2022 at 6:17 PM, Derk-Jan Karrenbeld ***@***.***> wrote:  
The task that was supposed to define the tags was incorrectly closed. Tags are not yet defined for Haskell which, once defined, should resolve this issue.

**Comment by gacallea** [comment]
fixed with https://github.com/exercism/haskell/pull/1124
