### ISSUE TITLE
Some exercises grouped under a concept remain locked after learning exercise has been solved

### ISSUE THREAD

**Issue by csage** [exercism/exercism#6615]
In the Python Syllabus, I currently have two concepts where apparently I cannot unlock all of the exercises. This may well be due to my inability to find the right button or trigger for doing so, or it may be unintended behaviour of the software. 

One example is the "String Methods" concept. I've solved the learning exercise, "Little Sister's Essay". The other solved exercise, "RNA Transcription" I had already done ~3 years ago. The remaining two are locked. The "Lists" concept is in a similar state, as you can see from the following snapshot of the overview graph:

<img width="953" alt="Bildschirmfoto 2022-11-21 um 22 18 49" src="https://user-images.githubusercontent.com/213280/203160429-0f490e74-819a-4f72-81f2-3dd8b447bcb5.png">

In case I am doing something wrong, could you please point out to me where I would have found instructions on how to unlock the remaining exercises? Thanks a lot in advance for your help!

**Comment by csage** [comment]
I'm going to ask for help in the community forum instead. My apologies for coming to the wrong place with this.

**Comment by iHiD** [comment]
@csage No problem and thanks for asking in the forum. 

Do you happen to remember which link you followed to discover this repo? It was our support-space for many years and  we're still trying to track down any signposts to it and change them to point to the forum. So if you do remember, that'd help!
