### ISSUE TITLE
Create new track for [LANGUAGE]

### ISSUE THREAD

**Issue by Ishandixit1198** [exercism/exercism#6632]
I have a problem I don't know why but your site is crashing very  regularly I don't know why but when I try to code or even doing something or say practicing on editor it crashed I don't know please fix it

**Comment by SleeplessByte** [comment]
@Ishandixit1198 please report your bug here: https://forum.exercism.org/c/exercism/bugs-and-features/126

It will help if you include a description of what it means to "crash", like a screenshot of your browser crashing.

**Comment by Ishandixit1198** [comment]
Sure
