### ISSUE TITLE
Community Final 2022 Tweaks

### ISSUE THREAD

**Issue by jonathandmiddleton** [exercism/exercism#6633]
@ErikSchierboom

I thought it would be best to put the items I need from you in this issue so everything is in one place.
If you could get these items done before the 16:00 UTC on the 23rd December that would be awesome.

- [x] [Merge this](https://github.com/exercism/blog/pull/170) and include the thumbnail URL for DJ's podcast that is in the PR comments and attached below.
- [x] Send me a list of all the maintainers in CSV format. Can I have their **first name** and **email** address?
- [x] If you have time, get transcripts for the following two podcast by **Thelma Lubkin** and **Carl Oscar** - they can be downloaded from this link -> https://we.tl/t-3tCSA5Hsnz

Think that's it for 2022!

![DJ-Thumbnail](https://user-images.githubusercontent.com/58132850/209069476-24bbeeb5-c1b1-4437-a607-553626141a66.png)

**Comment by SleeplessByte** [comment]
All checked by Erik 😄
