### ISSUE TITLE
Create new track for [V]

### ISSUE THREAD

**Issue by holder66** [exercism/exercism#6642]
Since spring 2022, I've been coding in a new language called V (https://vlang.io) which while still in development is already very useful, fun to code in, easy to learn, fast, and supported by a friendly and helpful group of developers. 
A couple of years ago, I found the exercism platform, its exercises, and the mentoring highly engaging when learning Elixir. I hope that it could be equally useful for others to learn V. 
Thank you for reading!

**Comment by glennj** [comment]
It's already being built. See https://forum.exercism.org/t/requesting-v-test-runner-repo/1959

If you're willing to volunteer to help out, I'm sure your time will be appreciated!
