### ISSUE TITLE
Create new track for SmallTalk

### ISSUE THREAD

**Issue by ghf-redwards** [exercism/exercism#6643]
I've always been interested in learning SmallTalk, but learning resources seem to be scarce. I've often heard the language is good at teaching foundational "pure" OO.

**Comment by glennj** [comment]
Hi @ghf-redwards 
There already is one: https://exercism.org/tracks/pharo-smalltalk

**Comment by ghf-redwards** [comment]
Awesome! I must have missed it in the language list. Thanks for letting me know!
