### ISSUE TITLE
Create new track for SQL

### ISSUE THREAD

**Issue by giriprasathd** [exercism/exercism#6647]
Dear Exercism Team,

I have recently discovered Exercism, and I am impressed by the quality of the courses and the platform.

I am particularly interested in SQL and I noticed that your courses do not currently have a dedicated track for SQL. As a fresher, I would like to contribute to the development of a SQL track on Exercism. I am confident that my knowledge and skills in SQL will be an asset to the team.

I understand that creating a new track is a big undertaking and would be happy to assist in any way possible. I am willing to contribute to the development of the course materials, proofreading, and testing. I am also open to any other opportunities that may be available for me to contribute.

I believe that a SQL track on Exercism would be a valuable resource for software developers and data analysts looking to improve their skills and advance their careers. I would greatly appreciate it if you would consider allowing me to contribute to the development of the SQL track.

Please feel free to contact me at hapisnake@gmail.com  to discuss this further.

Thank you for your time and consideration.

Best regards,
**GiriPrasath D**

**Comment by glennj** [comment]
There already is a track for [PL/SQL](https://exercism.org/tracks/plsql). It is focused on the "PL" part of the programming language. 

Let's continue on the forum. Please create a topic there.

**Comment by iHiD** [comment]
@giriprasathd If you're interested in this, do you mind continuing the discussion at https://forum.exercism.org/t/create-a-new-track-for-postgresql/3802 please.

I'm unsure of how a SQL track fits within the Exercism ecosystem as it's a bit different to other programming languages. But I'm not against it on principle.

**Comment by giriprasathd** [comment]
Sure
