### ISSUE TITLE
Create new track for Jolie

### ISSUE THREAD

**Issue by michalporeba** [exercism/exercism#6651]
What would it take to add [Jolie](https://www.jolie-lang.org/) to exercism? 

I think it is an interesting language offering a different perspective to what has been before - service orientation. 

Is it difficult to add new languages? Is there any documentation I could have a look at to see if this is something I could consider helping with?

**Comment by glennj** [comment]
The documentation on building a track starts here: https://exercism.org/docs/building/tracks
