### ISSUE TITLE
[PHP] A php-reprensenter

### ISSUE THREAD

**Issue by homersimpsons** [exercism/exercism#6654]
I would like to create a [representer](https://exercism.org/docs/building/tooling/representers) for PHP.

I did initiate the work in https://github.com/homersimpsons/php-representer and would happily include it in the exercism organization.

I did read the doc carefully, and I have some more questions:
- The doc says that there could be multiple files in the `solutionDir` directory, I see that for instance `rust-representer` only looks for `lib.rs`. For PHP should I look for only one file (currently I am looking for `soltution.php`) ?
- About the `representation.json`, is it just for the version ?

**Comment by homersimpsons** [comment]
For the record I did open an issue on the forum https://forum.exercism.org/t/php-a-php-reprensenter/3178

**Comment by ErikSchierboom** [comment]
Thanks for wanting to work on this!

@iHiD Could you create the corresponding repo?

**Comment by iHiD** [comment]
Great :)

- Repo at https://github.com/exercism/php-representer
- @homersimpsons You have write access.
- @ErikSchierboom Note there were a couple of questions in the OP too (they might have already been answered on the forum though - I've not checked)

**Comment by ErikSchierboom** [comment]
@iHiD They were :)

**Comment by homersimpsons** [comment]
Thank you for the repository @iHiD 

In fact the questions were answered.

I do have some more question though (maybe I should put them in the forum or in a dedicated issue):
- Is it possible to collect a corpus of solution to run the representer in local ? The goal is to identify possible normalization. I already checked some submitted solution here and there to find potential normalization.
- Is it possible to collect the nomalization result, or to have an idea on how it behaves ? I know there are some insight in the "Build Status" page, but they are rather high level
- I see that there are some fsharp tests files, can I freely remove them ? I already designed a similar test suite for the PHP Representer

**Comment by ErikSchierboom** [comment]
> Is it possible to collect a corpus of solution to run the representer in local ? The goal is to identify possible normalization. I already checked some submitted solution here and there to find potential normalization.

We have the ability to download a corpus of solutions for an exercises via our API. For that, I need to register you as a maintainer. What is your Exercism username?

> Is it possible to collect the nomalization result, or to have an idea on how it behaves ? I know there are some insight in the "Build Status" page, but they are rather high level
I'm not entirely sure what you're asking here. The representer should be creating some files, including a `representation.txt` file which contains the actual representation. We then use that normalization to see if comments are linked to that representation, and if so, use those. We have some docs: https://exercism.org/docs/mentoring/how-to-give-feedback-on-representations and https://exercism.org/docs/building/tooling/representers

> I see that there are some fsharp tests files, can I freely remove them ? I already designed a similar test suite for the PHP Representer

Where do you see those?

**Comment by homersimpsons** [comment]
> We have the ability to download a corpus of solutions for an exercises via our API. For that, I need to register you as a maintainer. What is your Exercism username?

My username is homersimpsons: https://exercism.org/profiles/homersimpsons (care for the extra **s** at the end)

> Where do you see those?

In the following directory: https://github.com/exercism/php-representer/tree/main/tests

**Comment by ErikSchierboom** [comment]
> My username is homersimpsons: https://exercism.org/profiles/homersimpsons (care for the extra s at the end)

You're now a maintainer in our DB. I've sent you a DM on the forum with the API URL.

> In the following directory: https://github.com/exercism/php-representer/tree/main/tests

No idea why they're there! Feel free to remove.

**Comment by homersimpsons** [comment]
Thank you @ErikSchierboom I had to update a bit my code to fit the proposed structure. I just pushed a first version for the php-representer.

I confirm I can export the solutions and I will check how the representer behave with those solutions.
