### ISSUE TITLE
Mentee dispected me for just asked testimonials 

### ISSUE THREAD

**Issue by SanthoshS20** [exercism/exercism#6655]
Hello team,

i mentored a person who disrespected me.

I asked for the testimonial. The reason why asked is some people are looking for mentorship once completed they are not giving anything. so i asked each and everyone for testimonial, once the mentorship completed. I didn't forced anyone to put testimonial. i just used this statement- "Can you please give me testimonials ?" 

The above statement is in demand for testimonial ?

Completely disrespecting the mentors. @exercism-bot  

if asking testimonials is a demand then please charge a case against all the youtube channel that they are asking to like, share and subscribe the channel

**Comment by SanthoshS20** [comment]
Hello team,

i mentored a person who disrespected me.

I asked for the testimonial. The reason why asked is some people are looking for mentorship once completed they are not giving anything. so i asked each and everyone for testimonial, once the mentorship completed. I didn't forced anyone to put testimonial. i just used this statement- "Can you please give me testimonials ?"

The above statement is in demand for testimonial ?

Completely disrespecting the mentors. @exercism-bot

if asking testimonials is a demand then please charge a case against all the youtube channel that they are asking to like, share and subscribe the channel

**Comment by SanthoshS20** [comment]
@kytrinyx
@iHiD
@jonathandmiddleton

**Comment by jonathandmiddleton** [comment]
Hi there - thanks for reaching out.  Please can you email me - jonathan@exercism.org with more information. Thanks
