### ISSUE TITLE
[HELP] Directions for a starter

### ISSUE THREAD

**Issue by Tultra** [exercism/exercism#6656]
Hi! I'm willing to get my head around how Exercism integrates all those 300 repos into a single website. It's kinda overwhelming, as someone who is willing to contribute to it in the future (I must say that I'm still learning Ruby, which might be making things a bit harder). Is there any general explanation on how all these repos fit together? Some direct questions I have are the following, (just to get you a feeling of what I mean):

- How does the website gets access to tracks/exercises/solutions? Is there an API to access each repo, or is it by directly referencing the path for the folders (on the server)?
- I suppose submission tests run in a separate machine/instance, inside a docker container. But I can't seem to find an API that supports this (would it be inside each repository, or is it something else entirely?)

Even though the repos are well documented, I've seen no comments on how all these technologies/repositories integrate. 

Thanks for any help!

**Comment by SleeplessByte** [comment]
Hi Tultra,

Most people who contribute will contribute to a _specific_ track, each with their own contribution documentation. If you want to read up on anything, [you can start on the contribute page](https://exercism.org/contribute) and make your way to the [contribute help docs](https://exercism.org/docs/building).

For further discussion I recommend you open a post on the forum.
