### ISSUE TITLE
Clear red badge for reputation

### ISSUE THREAD

**Issue by rootulp** [exercism/exercism#6660]
On https://exercism.org/dashboard I would like the ability to clear the red badge from

<img width="129" alt="Screenshot 2023-02-08 at 1 52 35 PM" src="https://user-images.githubusercontent.com/3699047/217625055-373f9604-fb53-4cb8-a6cb-0ecf89786fa5.png">

**Comment by rootulp** [comment]
it doesn't seem worthwhile to create a forum topic for this feature request 😞

**Comment by glennj** [comment]
From the "dots" menu, go to "Your Journey". On the Reputation tab click "Mark all as seen".
