### ISSUE TITLE
Unlocked mechanical march without publishing exercises

### ISSUE THREAD

**Issue by cmcaine** [exercism/exercism#6671]
I earnt this badge:

> Completed and published five exercises in a systems language in March
> Earned on 17th Mar 2023

I've only published 1 (maybe 2) solutions this month and they were in Julia. Also, should that say five solutions rather than exercises?

Do you count all previous years' Marchs as well, maybe?

**Comment by glennj** [comment]
> Do you count all previous years' Marchs as well, maybe?

yes.
