### ISSUE TITLE
syllabus: consider showing to maintainers even when `concept_exercises` is `false`

### ISSUE THREAD

**Issue by ee7** [exercism/exercism#6680]
See Discord discussion in the maintaining channel, 2023-03-30.

Ping @ErikSchierboom.

**Comment by ErikSchierboom** [comment]
What would the logic be? Show the syllabus tab regardless, or only if length(concept exercises) > 1? I assume the latter

**Comment by iHiD** [comment]
I think it should only show the syllabus to maintainers *of that track* ideally and then the "WIP" bit is less important. (I can never remember if we can do that or not)

**Comment by ErikSchierboom** [comment]
Ah yes, that's even better!

**Comment by ErikSchierboom** [comment]
@iHiD The only downside is that you can't easily get other maintainers to look at the syllabus 🤷

**Comment by iHiD** [comment]
True. I did consider that and decide screenshots were ok 🤷 :)
