### ISSUE TITLE
Problem with Analytical April badge

### ISSUE THREAD

**Issue by SimaDovakin** [exercism/exercism#6681]
Hello!

I already solved and published more than 5 exercises in Python in April, but I didn't get a badge.

P. S. Exercism is so cool. Thank you very much)

**Comment by SleeplessByte** [comment]
Tracked here: https://forum.exercism.org/t/badge-for-analytical-april-not-awarded-after-finishing-5-exercies/4967

**Comment by SimaDovakin** [comment]
@SleeplessByte Thanks
