### ISSUE TITLE
Create new track for Nix

### ISSUE THREAD

**Issue by aszlig** [exercism/exercism#6685]
Just joined Exercism and found out to my dismay that there is no Nix track.

I'm also very much fluent with Nix and using it daily, so I'd be willing to help.

While Nix is a package manager it's also a purely functional programming language, you can find more information here:

https://nixos.org/manual/nix/stable/language/index.html

**Comment by aszlig** [comment]
Hm certainly understand that, maybe it's a good idea to remove the following from the site:

> Want to add a language track to Exercism?
>
> [Open an issue](https://github.com/exercism/exercism/issues/new?title=Create%20new%20track%20for%20[LANGUAGE]) and let's discuss it.

**Comment by jonathandmiddleton** [comment]
Hey @aszlig - thanks for reaching out.

If you want to explore creating a track, then the place for discussing this is now at the [Exercism Forum](forum.exercism.org).

If you open a discussion then there will hopefully be others who might be keen to help you out.

Thanks

**Comment by iHiD** [comment]
@aszlig Thanks. That link got updated.
