### ISSUE TITLE
Address in email footer incomplete

### ISSUE THREAD

**Issue by JohnVeness** [exercism/exercism#6690]
Emails I receive from Exercism have the following at the bottom:

> You received this email because you've signed up to Exercism.
> You can change your notification settings
> Sent by Exercism: Unit G3; 81 Bournville Lane, United Kingdom 

That postal address is not complete - what town? What postcode?

I'm not particularly wishing to write to you, but it seems to me that you should either have a complete address or none at all!

**Comment by SleeplessByte** [comment]
FWIW, there is only one (1) Bournville Lane with a number 81 in the entirety of the UK, so in this particular case, mail addressed there will arrive, albeit with delays.

**Comment by JohnVeness** [comment]
Thanks. iHiD said the same on https://forum.exercism.org/t/address-in-email-footer-incomplete/6195 . It still reads oddly to me, but I won't push it!
