### ISSUE TITLE
Sporadic, spurious "One of the tests timed out" errors using `exercism` CLI

### ISSUE THREAD

**Issue by ntc2** [exercism/exercism#6697]
I'm new to Exercism, doing the Rust track, **using the `exercism` command line tool to submit my solutions**. I've done 6 exercises so far -- perhaps 15 iterations total -- and twice I've gotten the "One of the tests timed out" error, and both times resubmitting my code (semantically) unchanged passes all tests with no timeouts. So, I'm getting some kind of random timeout error, for code that should not be timing out.

Related, the `exercism` CLI won't let me resubmit a syntactically unchanged solution, so I have to insert meaningless white space (or whatever syntactic tweak that doesn't affect semantics) in order to resubmit the "timed out" solutions, which is annoying.

My Exercism username is `ntc2`, and one of the spurious timeout is for my first iteration of the `space-age` exercise. I can't see how to get a link to that iteration, but I mean this exercise: https://exercism.org/tracks/rust/exercises/space-age.

**Comment by iHiD** [comment]
I opened a forum post for you: https://forum.exercism.org/t/rust-why-does-this-code-take-a-long-time-to-run/6550

**Comment by ntc2** [comment]
@iHiD thanks!
