### ISSUE TITLE
Copy for ReasonML course is confusing newcomers

### ISSUE THREAD

**Issue by davesnx** [exercism/exercism#6701]
Hi,

I would like to report a miss-copy on the ReasonML course: https://exercism.org/tracks/reasonml
There are a few mentions to ReScript, which is in fact Reason. Fixed copy here:

---

**OCaml's type system**
Reason brings OCaml's battle-tested powerful type system to Javascript.

**Functional Programming**
Like OCaml, Reason is a functional programming language with pattern matching, variants and more.

**Inferred types**
No need to specify types, types are inferred by the compiler and are guaranteed to be correct.

**Fast compiler**
Compilation times are super fast which means fast iteration cycles.

---

I removed the places where ReScript compiler was mentioned and left it as "the compiler" to refer to OCaml compiler. 

For context, there's was some confusion between all the pieces back in the day, and a rebranding made it a little worst (https://rescript-lang.org/blog/bucklescript-is-rebranding)

ReasonML - the syntax
OCaml - the compiler to native code
ReScript - the syntax and the compiler to JS (doesn't work with ReasonML)

**Comment by iHiD** [comment]
Thanks. If you could open a PR, that'd be great. it's probably worth you also converting this to a forum post as per the auomated message (the PR will auto-get closed too), so that relevant people see it and act upon it :)

**Comment by davesnx** [comment]
Thanks, I wasn't aware of the right place to issue. Done it here: https://github.com/exercism/reasonml/pull/275
