### ISSUE TITLE
48in24 not counting already solved languages on main page

### ISSUE THREAD

**Issue by mcastorina** [exercism/exercism#6719]
The [main page](https://exercism.org/challenges/48in24) for the 48in24 shows "3 completed" when I've done it in 6. I already had 3 completed before 48in24 launched.

<img width="288" alt="image" src="https://github.com/exercism/exercism/assets/5395814/ff02968f-ed7e-4699-a1be-346be5a359ab">

<img width="493" alt="image" src="https://github.com/exercism/exercism/assets/5395814/321c0b04-60b9-4f74-acd8-4b6a6d4c735c">

This might be related, but I had to complete it in 3 *more* languages to see the award.

Is this the intended behavior? It seems like a bug at first glance, but maybe that's how it's supposed to be. Thanks!

**Comment by iHiD** [comment]
The instructions say:
- Bronze: Solve the exercise during 2024.
- Silver: Solve the exercise in any three languages during 2024.
- Gold: Qualify for silver status. Plus have solved the exercise in the three featured languages at some point (not necessarily in 2024).

From what I can tell, it's working in line with those instructions. If you see it deviating, could you explain where please?

(Also, this would be better on the forum normally as this repo isn't maintained/checked any more, but I'm happy to make an exception and leave this open)

**Comment by mcastorina** [comment]
Ohh I missed the *in 2024* part! Sorry for making the non-issue, I didn't know about the forum. Thanks! I'm looking forward to more 48in24 challenges :)

**Comment by iHiD** [comment]
No probs! :)
